### ISSUE TITLE
pindel insert size error

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1001]
Hi I just got this error running pindel in bcbio

[2015-09-04T18:26Z] Genotyping with pindel
[2015-09-04T18:26Z] Initializing parameters...
[2015-09-04T18:26Z] Pindel version 0.2.5a7, Sept 16 2014.
[2015-09-04T18:26Z] Loading reference genome ...
[2015-09-04T19:05Z] Loading reference genome done.
[2015-09-04T19:05Z] Initializing parameters done.
[2015-09-04T19:05Z] SearchRegion::SearchRegion
[2015-09-04T19:05Z] Processing region: 1	119961676	119961771
[2015-09-04T19:05Z] Chromosome Size: 249250621
[2015-09-04T19:06Z] NumBoxes: 60001	BoxSize: 8315
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] Looking at chromosome 1 bases 119961676 to 119961771 of the bed region: chromosome 1:119961676-119961771
[2015-09-04T19:06Z] No discordant RP reads in Bamfile /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/bamclean/28/28-reorder-fixrgs-gatkfilter-dedup.bam
[2015-09-04T19:06Z] Discovery RP: 0
[2015-09-04T19:06Z] sorting RP complete.
[2015-09-04T19:06Z] Reads_RP.size(): 0
[2015-09-04T19:06Z] Modify RP complete.
[2015-09-04T19:06Z] adding BD from RP.
[2015-09-04T19:06Z] modify and summarize interchr RP.
[2015-09-04T19:06Z] adding BD from interChr RP.
[2015-09-04T19:06Z] summarize BP as BD complete. Now start sorting BD...
[2015-09-04T19:06Z] sorting BD... done.
[2015-09-04T19:06Z] external BD events: 0 Added BreakDancer-like events: 0
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] Insertsize in config: 250
[2015-09-04T19:06Z] Error: the insert size is only 250 while the read length is 251 251
[2015-09-04T19:06Z] in paired end sequencing, the insert size is the total size of the fragment to be sequenced, with a read length of 100 bp the entire fragment may for example look like
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] |----100 bp: first read of the read pair--|-------------------300 bp: unsequenced DNA---------------------|----100 bp: second read of the read pair--|
[2015-09-04T19:06Z] <-----------------------------------------------------------insert size=500 ------------------------------------------------------------------------->
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] In the configuration file (the -i option) please check/correct the insert size (second item on each line). If you continue to have problems, please contact us (Kai Ye, kye@genome.wustl.edu)
[2015-09-04T19:06Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/pastore/usr/local/bcbio/bin/pindel -f /home/pastore/usr/local/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -i /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/tx/tmpUyUYDL/pindel.txt -o /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/tx/tmpUyUYDL/pindelroot -j /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/mutect/1/28T-1_119961676_201709283-raw-somaticIndels-regions-nolcr-nolcr.bed --report_inversions false --report_duplications false --report_long_insertions false --report_breakpoints false --report_interchromosomal_events false --max_range_index 2
Initializing parameters...
Pindel version 0.2.5a7, Sept 16 2014.
Loading reference genome ...
Loading reference genome done.
Initializing parameters done.
SearchRegion::SearchRegion
Processing region: 1	119961676	119961771
Chromosome Size: 249250621
NumBoxes: 60001	BoxSize: 8315

Looking at chromosome 1 bases 119961676 to 119961771 of the bed region: chromosome 1:119961676-119961771 
No discordant RP reads in Bamfile /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/bamclean/28/28-reorder-fixrgs-gatkfilter-dedup.bam
Discovery RP: 0
sorting RP complete.
Reads_RP.size(): 0
Modify RP complete.
adding BD from RP.
modify and summarize interchr RP.
adding BD from interChr RP.
summarize BP as BD complete. Now start sorting BD...
sorting BD... done.
external BD events: 0 Added BreakDancer-like events: 0

Insertsize in config: 250
Error: the insert size is only 250 while the read length is 251 251
in paired end sequencing, the insert size is the total size of the fragment to be sequenced, with a read length of 100 bp the entire fragment may for example look like

|----100 bp: first read of the read pair--|-------------------300 bp: unsequenced DNA---------------------|----100 bp: second read of the read pair--|
<-----------------------------------------------------------insert size=500 ------------------------------------------------------------------------->

In the configuration file (the -i option) please check/correct the insert size (second item on each line). If you continue to have problems, please contact us (Kai Ye, kye@genome.wustl.edu)
' returned non-zero exit status 1
[2015-09-04T19:06Z] Loading reference genome done.
[2015-09-04T19:06Z] Initializing parameters done.
[2015-09-04T19:06Z] SearchRegion::SearchRegion
[2015-09-04T19:06Z] Processing region: 1	1746903	1747061
[2015-09-04T19:06Z] Chromosome Size: 249250621
[2015-09-04T19:06Z] NumBoxes: 60001	BoxSize: 8315
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] Looking at chromosome 1 bases 1746903 to 1747061 of the bed region: chromosome 1:1746903-1747061
[2015-09-04T19:06Z] No discordant RP reads in Bamfile /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/bamclean/28/28-reorder-fixrgs-gatkfilter-dedup.bam
[2015-09-04T19:06Z] Discovery RP: 0
[2015-09-04T19:06Z] sorting RP complete.
[2015-09-04T19:06Z] Reads_RP.size(): 0
[2015-09-04T19:06Z] Modify RP complete.
[2015-09-04T19:06Z] adding BD from RP.
[2015-09-04T19:06Z] modify and summarize interchr RP.
[2015-09-04T19:06Z] adding BD from interChr RP.
[2015-09-04T19:06Z] summarize BP as BD complete. Now start sorting BD...
[2015-09-04T19:06Z] sorting BD... done.
[2015-09-04T19:06Z] external BD events: 0 Added BreakDancer-like events: 0
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] Insertsize in config: 250
[2015-09-04T19:06Z] Error: the insert size is only 250 while the read length is 251 251
[2015-09-04T19:06Z] in paired end sequencing, the insert size is the total size of the fragment to be sequenced, with a read length of 100 bp the entire fragment may for example look like
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] |----100 bp: first read of the read pair--|-------------------300 bp: unsequenced DNA---------------------|----100 bp: second read of the read pair--|
[2015-09-04T19:06Z] <-----------------------------------------------------------insert size=500 ------------------------------------------------------------------------->
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] In the configuration file (the -i option) please check/correct the insert size (second item on each line). If you continue to have problems, please contact us (Kai Ye, kye@genome.wustl.edu)
[2015-09-04T19:06Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/pastore/usr/local/bcbio/bin/pindel -f /home/pastore/usr/local/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -i /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/tx/tmpWPHn52/pindel.txt -o /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/tx/tmpWPHn52/pindelroot -j /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/mutect/1/28T-1_0_101185175-raw-somaticIndels-regions-nolcr-nolcr.bed --report_inversions false --report_duplications false --report_long_insertions false --report_breakpoints false --report_interchromosomal_events false --max_range_index 2
Initializing parameters...
Pindel version 0.2.5a7, Sept 16 2014.
Loading reference genome ...
Loading reference genome done.
Initializing parameters done.
SearchRegion::SearchRegion
Processing region: 1	1746903	1747061
Chromosome Size: 249250621
NumBoxes: 60001	BoxSize: 8315

Looking at chromosome 1 bases 1746903 to 1747061 of the bed region: chromosome 1:1746903-1747061 
No discordant RP reads in Bamfile /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/bamclean/28/28-reorder-fixrgs-gatkfilter-dedup.bam
Discovery RP: 0
sorting RP complete.
Reads_RP.size(): 0
Modify RP complete.
adding BD from RP.
modify and summarize interchr RP.
adding BD from interChr RP.
summarize BP as BD complete. Now start sorting BD...
sorting BD... done.
external BD events: 0 Added BreakDancer-like events: 0

Insertsize in config: 250
Error: the insert size is only 250 while the read length is 251 251
in paired end sequencing, the insert size is the total size of the fragment to be sequenced, with a read length of 100 bp the entire fragment may for example look like

|----100 bp: first read of the read pair--|-------------------300 bp: unsequenced DNA---------------------|----100 bp: second read of the read pair--|
<-----------------------------------------------------------insert size=500 ------------------------------------------------------------------------->

In the configuration file (the -i option) please check/correct the insert size (second item on each line). If you continue to have problems, please contact us (Kai Ye, kye@genome.wustl.edu)
' returned non-zero exit status 1
[2015-09-04T19:06Z] MuTect: MuTect
[2015-09-04T19:06Z] Loading reference genome done.
[2015-09-04T19:06Z] Initializing parameters done.
[2015-09-04T19:06Z] SearchRegion::SearchRegion
[2015-09-04T19:06Z] Processing region: 3	38181792	38182142
[2015-09-04T19:06Z] Chromosome Size: 198022430
[2015-09-04T19:06Z] NumBoxes: 60004	BoxSize: 6607
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] Looking at chromosome 3 bases 38181792 to 38182142 of the bed region: chromosome 3:38181792-38182142
[2015-09-04T19:06Z] No discordant RP reads in Bamfile /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/bamclean/28/28-reorder-fixrgs-gatkfilter-dedup.bam
[2015-09-04T19:06Z] Discovery RP: 0
[2015-09-04T19:06Z] sorting RP complete.
[2015-09-04T19:06Z] Reads_RP.size(): 0
[2015-09-04T19:06Z] Modify RP complete.
[2015-09-04T19:06Z] adding BD from RP.
[2015-09-04T19:06Z] modify and summarize interchr RP.
[2015-09-04T19:06Z] adding BD from interChr RP.
[2015-09-04T19:06Z] summarize BP as BD complete. Now start sorting BD...
[2015-09-04T19:06Z] sorting BD... done.
[2015-09-04T19:06Z] external BD events: 0 Added BreakDancer-like events: 0
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] Insertsize in config: 250
[2015-09-04T19:06Z] Error: the insert size is only 250 while the read length is 250 250
[2015-09-04T19:06Z] in paired end sequencing, the insert size is the total size of the fragment to be sequenced, with a read length of 100 bp the entire fragment may for example look like
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] |----100 bp: first read of the read pair--|-------------------300 bp: unsequenced DNA---------------------|----100 bp: second read of the read pair--|
[2015-09-04T19:06Z] <-----------------------------------------------------------insert size=500 ------------------------------------------------------------------------->
[2015-09-04T19:06Z] 
[2015-09-04T19:06Z] In the configuration file (the -i option) please check/correct the insert size (second item on each line). If you continue to have problems, please contact us (Kai Ye, kye@genome.wustl.edu)
[2015-09-04T19:06Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/pastore/usr/local/bcbio/bin/pindel -f /home/pastore/usr/local/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -i /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/tx/tmp9Xj9me/pindel.txt -o /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/tx/tmp9Xj9me/pindelroot -j /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/mutect/3/28T-3_0_113847938-raw-somaticIndels-regions-nolcr-nolcr.bed --report_inversions false --report_duplications false --report_long_insertions false --report_breakpoints false --report_interchromosomal_events false --max_range_index 2
Initializing parameters...
Pindel version 0.2.5a7, Sept 16 2014.
Loading reference genome ...
Loading reference genome done.
Initializing parameters done.
SearchRegion::SearchRegion
Processing region: 3	38181792	38182142
Chromosome Size: 198022430
NumBoxes: 60004	BoxSize: 6607

Looking at chromosome 3 bases 38181792 to 38182142 of the bed region: chromosome 3:38181792-38182142 
No discordant RP reads in Bamfile /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/bamclean/28/28-reorder-fixrgs-gatkfilter-dedup.bam
Discovery RP: 0
sorting RP complete.
Reads_RP.size(): 0
Modify RP complete.
adding BD from RP.
modify and summarize interchr RP.
adding BD from interChr RP.
summarize BP as BD complete. Now start sorting BD...
sorting BD... done.
external BD events: 0 Added BreakDancer-like events: 0

Insertsize in config: 250
Error: the insert size is only 250 while the read length is 250 250
in paired end sequencing, the insert size is the total size of the fragment to be sequenced, with a read length of 100 bp the entire fragment may for example look like

|----100 bp: first read of the read pair--|-------------------300 bp: unsequenced DNA---------------------|----100 bp: second read of the read pair--|
<-----------------------------------------------------------insert size=500 ------------------------------------------------------------------------->

In the configuration file (the -i option) please check/correct the insert size (second item on each line). If you continue to have problems, please contact us (Kai Ye, kye@genome.wustl.edu)
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/pastore/usr/local/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/pastore/usr/local/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 164, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by chapmanb** [comment]
Sorry about the problems. pindel support is not very well tested and supported in bcbio. We're thinking about removing it from bcbio, or at least undocumenting and labelling it as experimental. We did some initial validation on it and it wasn't as sensitive as scalpel for small indels and was as slow, so we didn't spend additional time on it. What are you looking to get out of pindel that scalpel does not currently provide?

If you'd like to take on debugging and improving it, that would also be very welcome. Thanks again for reporting this.

**Comment by apastore** [comment]
Thanks Brad, my aim was to compare pinned vs scalpel to decide which one should I use as a default to add INDELs call to mutect. I will probably omit the indelcaller parameter.

**Comment by chapmanb** [comment]
scalpel is definitely the preferred choice. It's got good sensitivity with the only downside being the speed. Thanks for testing this and let us know if you plan to do more work in pindel.
