### ISSUE TITLE
gemini 0.17.0 --no-bcolz

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1005]
it seams that the new gemini do not support the --no-bcolz argument

thanks!

[2015-09-07T17:54Z] Create gemini database for /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/60T-vepeffects-ploidyfix-filter.vcf.gz : 60
[2015-09-07T17:54Z] usage: gemini [-h] [-v] [--annotation-dir ANNOTATION_DIR]
[2015-09-07T17:54Z] 
[2015-09-07T17:54Z]               {load,roh,dump,fusions,annotate,lof_interactions,set_somatic,query,autosomal_recessive,stats,de_novo,autosomal_dominant,interactions,update,load_chunk,windower,pathways,burden,gene_wise,mendel_errors,merge_chunks,amend,region,comp_hets,bcolz_index,db_info,qc,actionable_mutations,browser,lof_sieve,examples}
[2015-09-07T17:54Z]               ...
[2015-09-07T17:54Z] gemini: error: unrecognized arguments: --no-bcolz
[2015-09-07T17:54Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/pastore/usr/local/bcbio/anaconda/bin/gemini  load  --passonly --skip-cadd --skip-gerp-bp  -v /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/60T-vepeffects-ploidyfix-filter.vcf.gz -t VEP --cores 6 --tempdir /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/tx/tmpXM0Pbp --no-bcolz /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/tx/tmpXM0Pbp/60T-vepeffects-ploidyfix-filter.db
usage: gemini [-h] [-v] [--annotation-dir ANNOTATION_DIR]
              
              {load,roh,dump,fusions,annotate,lof_interactions,set_somatic,query,autosomal_recessive,stats,de_novo,autosomal_dominant,interactions,update,load_chunk,windower,pathways,burden,gene_wise,mendel_errors,merge_chunks,amend,region,comp_hets,bcolz_index,db_info,qc,actionable_mutations,browser,lof_sieve,examples}
              ...
gemini: error: unrecognized arguments: --no-bcolz
' returned non-zero exit status 2
Traceback (most recent call last):
  File "/home/pastore/usr/local/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/pastore/usr/local/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 174, in run
    samples = run_parallel("postprocess_variants", samples)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 90, in postprocess_variants
    return variation.postprocess_variants(*args)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 28, in postprocess_variants
    data["vrn_file"] = prioritize.handle_vcf_calls(data["vrn_file"], data)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/prioritize.py", line 33, in handle_vcf_calls
    gemini_db = population.create_gemini_db(vcf_file, data)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 79, in create_gemini_db
    do.run(cmd, "Create gemini database for %s" % gemini_vcf, data)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/pastore/usr/local/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/pastore/usr/local/bcbio/anaconda/bin/gemini  load  --passonly --skip-cadd --skip-gerp-bp  -v /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/60T-vepeffects-ploidyfix-filter.vcf.gz -t VEP --cores 6 --tempdir /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/tx/tmpXM0Pbp --no-bcolz /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/tx/tmpXM0Pbp/60T-vepeffects-ploidyfix-filter.db
usage: gemini [-h] [-v] [--annotation-dir ANNOTATION_DIR]
              
              {load,roh,dump,fusions,annotate,lof_interactions,set_somatic,query,autosomal_recessive,stats,de_novo,autosomal_dominant,interactions,update,load_chunk,windower,pathways,burden,gene_wise,mendel_errors,merge_chunks,amend,region,comp_hets,bcolz_index,db_info,qc,actionable_mutations,browser,lof_sieve,examples}
              ...
gemini: error: unrecognized arguments: --no-bcolz
' returned non-zero exit status 2
-bash-4.1$ /home/pastore/usr/local/bcbio/anaconda/bin/gemini  load -h
usage: gemini load [-h] [-v VCF] [-t {snpEff,VEP}] [-p PED_FILE]
                   [--skip-gerp-bp] [--skip-cadd] [--skip-gene-tables]
                   [--save-info-string] [--no-load-genotypes] [--no-genotypes]
                   [--cores CORES] [--scheduler {lsf,sge,slurm,torque}]
                   [--queue QUEUE] [--tempdir TEMPDIR] [--passonly]
                   [--test-mode]
                   db

positional arguments:
  db                    The name of the database to be created.

optional arguments:
  -h, --help            show this help message and exit
  -v VCF                The VCF file to be loaded.
  -t {snpEff,VEP}       The annotations to be used with the input vcf.
  -p PED_FILE           Sample information file in PED+ format.
  --skip-gerp-bp        Do not load GERP scores at base pair resolution.
                        Loaded by default.
  --skip-cadd           Do not load CADD scores. Loaded by default
  --skip-gene-tables    Do not load gene tables. Loaded by default.
  --save-info-string    Load INFO string from VCF file. Not loaded by default
  --no-load-genotypes   Genotypes exist in the file, but should not be stored.
  --no-genotypes        There are no genotypes in the file (e.g. some 1000G
                        VCFs)
  --cores CORES         Number of cores to use to load in parallel.
  --scheduler {lsf,sge,slurm,torque}
                        Cluster scheduler to use.
  --queue QUEUE         Cluster queue to use.
  --tempdir TEMPDIR     Temp directory for storing intermediate files when
                        loading in parallel.
  --passonly            Keep only variants that pass all filters.
  --test-mode           Load in test mode (faster)

**Comment by chapmanb** [comment]
Thanks much for the heads up and testing the new version so quickly. I pushed a fix for this and will have a new release soon with all the recent fixes and updates.

**Comment by apastore** [comment]
I am sorry, but even after running the update I still get the same error message.
Thanks!

bcbio_nextgen.py upgrade -u stable --tools --data --toolplus data

[2015-09-10T20:30Z] Prioritization for 60, freebayes
[2015-09-10T20:51Z] Create gemini database for /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/60T-vepeffects-ploidyfix-filter.vcf.gz : 60
[2015-09-10T20:56Z] usage: gemini [-h] [-v] [--annotation-dir ANNOTATION_DIR]
[2015-09-10T20:56Z] 
[2015-09-10T20:56Z]               {load,roh,dump,fusions,annotate,lof_interactions,set_somatic,query,autosomal_recessive,stats,de_novo,autosomal_dominant,interactions,update,load_chunk,windower,pathways,burden,gene_wise,mendel_errors,merge_chunks,amend,region,comp_hets,bcolz_index,db_info,qc,actionable_mutations,browser,lof_sieve,examples}
[2015-09-10T20:56Z]               ...
[2015-09-10T20:56Z] gemini: error: unrecognized arguments: --no-bcolz
[2015-09-10T20:56Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/pastore/data/bcbio/anaconda/bin/gemini  load  --passonly --skip-gerp-bp  -v /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/60T-vepeffects-ploidyfix-filter.vcf.gz -t VEP --cores 6 --tempdir /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/tx/tmpmH9rJD --no-bcolz /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/tx/tmpmH9rJD/60T-vepeffects-ploidyfix-filter.db
usage: gemini [-h] [-v] [--annotation-dir ANNOTATION_DIR]
              
              {load,roh,dump,fusions,annotate,lof_interactions,set_somatic,query,autosomal_recessive,stats,de_novo,autosomal_dominant,interactions,update,load_chunk,windower,pathways,burden,gene_wise,mendel_errors,merge_chunks,amend,region,comp_hets,bcolz_index,db_info,qc,actionable_mutations,browser,lof_sieve,examples}
              ...
gemini: error: unrecognized arguments: --no-bcolz
' returned non-zero exit status 2
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/pastore/data/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 174, in run
    samples = run_parallel("postprocess_variants", samples)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 90, in postprocess_variants
    return variation.postprocess_variants(*args)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 28, in postprocess_variants
    data["vrn_file"] = prioritize.handle_vcf_calls(data["vrn_file"], data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/prioritize.py", line 33, in handle_vcf_calls
    gemini_db = population.create_gemini_db(vcf_file, data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 79, in create_gemini_db
    do.run(cmd, "Create gemini database for %s" % gemini_vcf, data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/pastore/data/bcbio/anaconda/bin/gemini  load  --passonly --skip-gerp-bp  -v /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/60T-vepeffects-ploidyfix-filter.vcf.gz -t VEP --cores 6 --tempdir /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/tx/tmpmH9rJD --no-bcolz /ifs/e63data/sander-lab/pastore/project/HZL/hzl_noaln/work/freebayes/tx/tmpmH9rJD/60T-vepeffects-ploidyfix-filter.db
usage: gemini [-h] [-v] [--annotation-dir ANNOTATION_DIR]
              
              {load,roh,dump,fusions,annotate,lof_interactions,set_somatic,query,autosomal_recessive,stats,de_novo,autosomal_dominant,interactions,update,load_chunk,windower,pathways,burden,gene_wise,mendel_errors,merge_chunks,amend,region,comp_hets,bcolz_index,db_info,qc,actionable_mutations,browser,lof_sieve,examples}
              ...
gemini: error: unrecognized arguments: --no-bcolz
' returned non-zero exit status 2

**Comment by chapmanb** [comment]
Alessandro;
That fix is in the development version since the new GEMINI came out after the last release. You can do:
```
bcbio_nextgen.py upgrade -u development
```
to get it. We're hoping to have a release soon with this fix included. Hopefully this will also get you going on chapmanb/bcbio-nextgen#112

**Comment by apastore** [comment]
ThankS!!! I have not tried that one!
