### ISSUE TITLE
ipyparallel.error.CompositeError

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1009]
Hi,
Could you please help me to debug the following error?
Thanks!

Using existing profile dir: u'./project/work/log/ipython'
2015-09-05 00:36:24.369 [IPClusterStop] Stopping cluster [pid=230181] with [signal=2]
2015-09-05 00:36:25.809 [IPClusterStop] Using existing profile dir: u'./project/work/log/ipython'
2015-09-05 00:36:25.819 [IPClusterStop] Stopping cluster [pid=230181] with [signal=2]

0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
1 Engines running
Sending a shutdown signal to the controller and engines.

0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
16 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "./bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "./bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = region.parallel_prep_region(samples, run_parallel)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 127, in parallel_prep_region
    "piped_bamprep", _add_combine_info, file_key, ["config"])
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 135, in run
    for data in view.map_sync(fn, items, track=False):
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<string>", line 2, in map
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in map
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<string>", line 2, in __call__
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: piped_bamprep
[13:apply]: CalledProcessError: Command 'set -o pipefail; ./bcbio/bin/gatk-framework -Xms250m -Xmx666m -XX:+UseSerialGC -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -T PrintReads -L 2:95326380-126344487 -R ./bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I ./project/work/align/9781Germ/12_2015-08-06_project_1-6-merged-sort.bam --downsample_to_coverage 10000 -BQSR ./project/work/align/9781Germ/12_2015-08-06_project_1-6-merged-sort.grp -o /tmp/bcbiotx/3c3c11f1-6f8b-4817-869f-5bddb0ab025d/tmp5nt23q/12_2015-08-06_project_1-6-merged-sort-2_95326379_126344487-prep-prealign.bam
Picked up _JAVA_OPTIONS: -Xmx2g

**Comment by lpantano** [comment]
Hi @pengxiao78,

sorry about the problem. Not sure what is going on. Could you check if the job was killed by memory problems. It should be in the err/out of the batch scripts (bcbio*err/out). Another option is to try to run that command stand alone and see if it needs more than that memory or breaks with some error? maybe that helps us to see more.

**Comment by pengxiao78** [comment]
I have solved it by deleting 'export _JAVA_OPTIONS=-Xmx2g' in the bashrc file, which I added during the installation. Thank you.
