### ISSUE TITLE
ValueError: Unexpected variant effects configuration: ['snpeff', 'vep']

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1014]
Hi,
I intended to get automatic snpeff and vep annotated exome-seq results and added     
effects:
    - snpeff
    - vep 
under the - algorithm: in the yaml file. However, the following error appeared in each variantcaller. I used 
    variantcaller:
    - mutect
    - freebayes
    - vardict
    - varscan
 Can you help me to debug it?
Thank you.

[2015-09-11T21:55Z] *.edu: Finalizing variant calls: tumor1, freebayes
[2015-09-11T21:55Z] *.edu: Calculating variation effects for tumor1, freebayes
[2015-09-11T21:55Z] *.edu: Unexpected error
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 44, in _setup_logging
    yield config
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 181, in postprocess_variants
    return ipython.zip_args(apply(variation.postprocess_variants, *args))
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 18, in postprocess_variants
    ann_vrn_file, vrn_stats = effects.add_to_vcf(data["vrn_file"], data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 35, in add_to_vcf
    raise ValueError("Unexpected variant effects configuration: %s" % effect_todo)
ValueError: Unexpected variant effects configuration: ['snpeff', 'vep']

**Comment by chapmanb** [comment]
Sorry about any confusion. The effects values can be a single choice, `snpeff` or `vep` not a list of choices. Practically, both provide good annotations so there is not a lot of value in supporting two sets of annotations throughout bcbio. Hope this helps.

**Comment by FedericoComoglio** [comment]
Hi @chapmanb, I ran into a closely related issue. While the fact that `snpeff` and `vep` are mutually exclusive was clear from the documentation (https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html), I still passed my single choice as a list (i.e. [`vep`]) and got

**Comment by chapmanb** [comment]
Federico;
Thanks for reporting the issue you ran into and apologies for the confusing error message. We pushed a fix to the latest development so it'll now handle this case correctly and pull the effects type from a single item list. Multiple options are still not allowed, but this gives you flexibility to specify either as a list or just a plain item.

**Comment by FedericoComoglio** [comment]
This is very nice, thanks a lot @chapmanb
