### ISSUE TITLE
Isolated install on Cluster fails to complete

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1021]
Greetings,
Im still unable to successfully rerun sample data that was successful on our local server, when running on an isolated install on our computer cluster. The input should be identical. I dislike just dumping error text into a post and I apologize that Im about to do so, but Im really not sure what is going on.

```
...
[2015-09-09T22:24Z] bedtools genomecov: 9 : CM214MP4MouseNum3571-sort.nsorted.disambiguatedSpeciesA.sorted.bam
[2015-09-09T22:24Z] bedtools genomecov: 10 : CM214MP4MouseNum3571-sort.nsorted.disambiguatedSpeciesA.sorted.bam
[2015-09-09T22:24Z] bedtools genomecov: 11 : CM214MP4MouseNum3571-sort.nsorted.disambiguatedSpeciesA.sorted.bam
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 149, in run
    samples = run_parallel("postprocess_alignment", samples)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 42, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 160, in postprocess_alignment
    callable.block_regions(data["work_bam"], ref_file, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 321, in block_regions
    callable_bed = parallel_callable_loci(in_bam, ref_file, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 49, in parallel_callable_loci
    "callable_bed", ["config"])[0]
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes exactly 3 arguments (2 given)
```

executed simply as `bcbio_nextgen.py ../config/CM214MP4MouseNum3571.yaml -n 4`

I can post the yaml too if required. Thank you.

**Comment by chapmanb** [comment]
Brad;
Sorry about the issue. Would it be possible to re-run this with `-n 1` and post the error message from that? Unfortunately multiprocessing often loses the original exception so in this case the error stack you posted only tells us something went wrong during the callable calculation, but we're not sure exactly what. Hopefully the stacktrace from a non-parallel run will be more informative. Thanks much for the help debugging.

**Comment by bwubb** [comment]
Please, you all are helping me. Im not sure if this error is related or not...

```
[2015-09-17T15:19Z] bedtools genomecov: 1 : CM214MP4MouseNum3571-sort.nsorted.disambiguatedSpeciesA.sorted.bam
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 149, in run
    samples = run_parallel("postprocess_alignment", samples)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 42, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 160, in postprocess_alignment
    callable.block_regions(data["work_bam"], ref_file, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 321, in block_regions
    callable_bed = parallel_callable_loci(in_bam, ref_file, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 49, in parallel_callable_loci
    "callable_bed", ["config"])[0]
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 178, in calc_callable_loci
    return callable.calc_callable_loci(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 63, in wrapper
    out = f(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 68, in calc_callable_loci
    depth, region_file, tx_out_file, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 91, in _group_by_ctype
    .groupby(**kwargs).fn):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 668, in decorated
    result = method(self, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 243, in wrapped
    check_stderr=check_stderr)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pybedtools/helpers.py", line 440, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools groupby -prec 21 -ops first,first,max,first -i /home/bwubb/NGS/MelanomaTargeted/bcbio/sample_data/CM214MP4MouseNum3571/work/tx/tmpCevhef/pybedtools.qCy134.tmp -g 1,4 -c 1,2,3,4

Error message was:

*****ERROR: Unrecognized parameter: -prec *****


*****ERROR: Unrecognized parameter: 21 *****


*****
*****ERROR: Invalid operation selection "first
"  *****

*****
*****ERROR: Invalid operation selection "first
"  *****

*****
*****ERROR: Invalid operation selection "first
"  *****

Tool:    bedtools intersect (aka intersectBed)
Version: 2.15.0
Summary: Summarizes a dataset column based upon
	 common column groupings. Akin to the SQL "group by" command.

Usage:	 bedtools groupby -g [group_column(s)] -c [op_column(s)] -o [ops] 
	 cat [FILE] | bedtools groupby -g [group_column(s)] -c [op_column(s)] -o [ops] 
...
```

**Comment by chapmanb** [comment]
Sorry about the problem. This is due to a bug in the latest bedtools. More details are in #1016 but the short answer is that you can fix this by upgrading to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
Hope this gets it running cleanly and please let us know if you run into any other issues.

**Comment by bwubb** [comment]
This did not correct the error. I ran the upgrade twice to be sure.

**Comment by chapmanb** [comment]
Apologies, I missed that you must have a different non-bcbio installed bedtools in your PATH, specifically `2.15.0`. bcbio installs a more up to date one (`2.25.0` right now) that will have the additional options used here. If you're injecting other tools into your path via modules or other approaches, you can try setting the PATH to bcbio tools as the very first item so it takes precedence over others. Hope this helps resolve it.
