### ISSUE TITLE
ImportError: cannot import name Client -linked to issue #1026

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1031]
Thanks Brad
I tried to re-run the analysis after the new fix but I get an Import error.
```
/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 35, in <module>
    from bcbio.distributed import runfn, clargs
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 11, in <module>
    from bcbio.distributed import multitasks
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 3, in <module>
    from bcbio import heterogeneity, structural, utils, chipseq, upload
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/__init__.py", line 10, in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 21, in <module>
    from bcbio.heterogeneity import chromhacks, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/theta.py", line 22, in <module>
    from bcbio.structural import cnvkit, convert
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 10, in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly,
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cn_mops.py", line 20, in <module>
    from bcbio.structural import shared as sshared
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/shared.py", line 17, in <module>
    from bcbio.bam import callable
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 26, in <module>
    from bcbio.distributed import multi, prun
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 9, in <module>
    from bcbio.distributed import clusterk, ipython, multi, resources
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 31, in <module>
    from cluster_helper import cluster as ipython_cluster
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 22, in <module>
    from IPython.parallel import Client
ImportError: cannot import name Client
```
Thanks for making these changes by the way.
This issue relates to a a previously closed issue  #1026
I opened this as a new issue as the previous issue in  #1026 had been closed.

**Comment by chapmanb** [comment]
Kevin;
Sorry about the problem. It looks like you must have been upgrading from a slightly older version of bcbio and the IPython libraries changed. There is a bit more detail in: #978 but it looks like you didn't get the latest ipython-cluster-helper. You should be able to fix this with:
```
/usr/local/share/bcbio/anaconda/bin/conda install -c bcbio ipython-cluster-helper ipython ipyparallel
```
Hope that gets it working for you.

**Comment by kevjp** [comment]
Thanks that seems to have fixed the Import Error. You mentioned in #1026 that the fix you pushed will increase the size of blocks it uses to split on to 250bp which makes sense but what did you mean by your fix `being more aggressive about filtering very small regions`? Surely that is why the indel was incorrectly filtered out in the first place

**Comment by chapmanb** [comment]
Kevin;
Great, glad that fixed the problem.

Sorry, I didn't write the block size description clearly. I meant it's more aggressive about filtering out small non-covered regions where we split analyses. This means there should be bigger coverage blocks and hopefully no filtering of indels like you're seeing. Definitely let me know if that's not the case and you still have problems and we can reopen #1026 and work more on it.

**Comment by kevjp** [comment]
Thanks Brad that makes sense. Will let you know if I have any further problems.
