### ISSUE TITLE
install bcbio-nextgene in aws ec2 instance

### ISSUE THREAD

**Issue by hurchu** [chapmanb/bcbio-nextgen#1035]
Hi,

I tried to install it isolately in one aws ec2 instance, but had the following error. It seems that it can't determine the distribution. Could you please tell me how to fix it in fabricrc.txt? Thanks!

Traceback (most recent call last):
  File "/mnt/giant2/software/bcbio/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/giant2/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 81, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/mnt/giant2/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 373, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/mnt/giant2/software/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/mnt/giant2/software/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 101, in _setup_vm
    _setup_cloudbiolinux(options)
  File "/mnt/giant2/software/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 195, in _setup_cloudbiolinux
    ignore_distcheck=not need_distcheck)
  File "/mnt/giant2/software/tmpbcbio-install/cloudbiolinux/cloudbio/utils.py", line 93, in _configure_fabric_environment
    _setup_distribution_environment(ignore_distcheck=ignore_distcheck)
  File "/mnt/giant2/software/tmpbcbio-install/cloudbiolinux/cloudbio/distribution.py", line 33, in _setup_distribution_environment
    env.distribution = _determine_distribution(env)
  File "/mnt/giant2/software/tmpbcbio-install/cloudbiolinux/cloudbio/distribution.py", line 310, in _determine_distribution
    raise Exception("Attempt to automatically determine Linux distribution of target machine failed, please manually specify distribution in fabricrc.txt")
Exception: Attempt to automatically determine Linux distribution of target machine failed, please manually specify distribution in fabricrc.txt
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 276, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by chapmanb** [comment]
Sorry about the issues. We'd be happy to update the detection code to be able to handle your system. Would you be able to provide more details about what type of machine you're running on? It would help us to know the output of:
```
cat /etc/*release
cat /proc/version
cat /etc/issue
```
Thanks for helping with debugging.

**Comment by hurchu** [comment]
$ cat /etc/*release
Amazon Linux AMI release 2014.03

$ cat /proc/version
Linux version 3.10.42-52.145.amzn1.x86_64 (mockbuild@gobi-build-64003) (gcc
version 4.8.2 20131212 (Red Hat 4.8.2-7) (GCC) ) #1 SMP Tue Jun 10 23:46:43
UTC 2014

$ cat /etc/issue
Amazon Linux AMI release 2014.03
Kernel \r on an \m

Thank you very much for your help!

Best,

On Fri, Sep 25, 2015 at 12:28 PM, Brad Chapman <notifications@github.com>
wrote:

> Sorry about the issues. We'd be happy to update the detection code to be
> able to handle your system. Would you be able to provide more details about
> what type of machine you're running on? It would help us to know the output
> of:
>
> cat /etc/*release
> cat /proc/version
> cat /etc/issue
>
> Thanks for helping with debugging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chapmanb/bcbio-nextgen/issues/1035#issuecomment-143315329>
> .
>



-- 
Junfei Zhu

**Comment by chapmanb** [comment]
Thanks much for the details. I pushed a fix which should detect these older Amazon AMIs. If you remove any cached directories (`rm -rf tmpbcbio-install`) and re-run the command it should hopefully detect this correctly and proceed with installation. Please let us know if you run into any other problems and happy to re-open this.

**Comment by hurchu** [comment]
​Thanks! I have installed successfully.

Best,​

On Fri, Sep 25, 2015 at 1:45 PM, Brad Chapman <notifications@github.com>
wrote:

> Thanks much for the details. I pushed a fix which should detect these
> older Amazon AMIs. If you remove any cached directories (rm -rf
> tmpbcbio-install) and re-run the command it should hopefully detect this
> correctly and proceed with installation. Please let us know if you run into
> any other problems and happy to re-open this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chapmanb/bcbio-nextgen/issues/1035#issuecomment-143335142>
> .
>



-- 
Junfei Zhu
