### ISSUE TITLE
Downsampling bam files

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1043]
I am trying to downsample my analysis to a maximum read depth of x30 and added the  coverage_depth_max: 30 argument to my config Yaml. I presume this will downsample regions with more than 30 reads but the docs seem to indicate that the downsampling will reduce only reads with the same start position so if a region is covered by other reads but with a different start position those reads will not be reduced. Therefore the read coverage is likely to be greater than 30 in most cases. The docs mention that for GATK though that the it will downsample to exactly this coverage per position. Does this mean that by setting coverage_depth_max: 30, GATK will base its variant calling on regions with a max read depth of 30? 

That aside when I tried to run the variant2 pipeline with the config Yaml below I got the following error:
```
INFO  08:36:35,376 HelpFormatter - Date/Time: 2015/09/30 08:36:35 
INFO  08:36:35,376 HelpFormatter - --------------------------------------------------------------------------------- 
INFO  08:36:35,377 HelpFormatter - --------------------------------------------------------------------------------- 
INFO  08:36:36,606 GATKRunReport - Uploaded run statistics report to AWS S3 
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.4-46-gbc02625): 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Invalid command line: Cannot use -dcov or --downsample_to_coverage for ActiveRegionWalkers, use another downsampling argument
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
[2015-09-30T07:36Z] GATK: HaplotypeCaller
[2015-09-30T07:36Z] GATK: HaplotypeCaller
[2015-09-30T07:36Z] GATK: HaplotypeCaller
[2015-09-30T07:36Z] GATK: HaplotypeCaller
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```

Config Yaml
```
details:
- algorithm:
    align_split_size: 5000000
    aligner: bwa
    coverage_interval: amplicon
    coverage_depth_max: 30
    ensemble:
      numpass: 2
    merge_bamprep: true
    realign: gatk
    recalibrate: gatk
    variantcaller:
    - platypus
    - gatk-haplotype
    - samtools
  analysis: variant2
  description: NGS43a_H_141105A_HapMapNA12878_Pan81_ACTTGA_L001_001
  files:
  - /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation1/NA12878-exome-eval/input/NGS43a_H_141105A_HapMapNA12878_Pan81_ACTTGA_L001_001_1.fastq.gz
  - /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation1/NA12878-exome-eval/input/NGS43a_H_141105A_HapMapNA12878_Pan81_ACTTGA_L001_001_2.fastq.gz
  genome_build: GRCh37
fc_date: '2015-09-16'
fc_name: qxtindel1
upload:
  dir: ../final
```
I'm a little confused what the issue is here.

**Comment by chapmanb** [comment]
Sorry about the problems and confusion. The issue isn't anything on your part, it's that the `coverage_depth_max` parameter is no longer useful. GATK 3.4 HaplotypeCaller doesn't support downsampling, which is the error you saw, and that was the main use case for it. No other callers supported it beyond GATK/MuTect and the attempt to pre-downsample to coverage was not successful since there aren't tools that work by downsampling BAM coverage.

So the fix for this was to remove `coverage_depth_max` and avoid the confusion entirely. Practically, what are you trying to do with the downsampling? If you want to look at less coverage results, you could pre-downsample with samtools or sambamba and feed the downsampled BAM into bcbio. If you want to limit memory by coverage, I don't know of an effective way to do that right now. I'd be happy to explore this again if there were tools to support downsampling only based on coverage.

Sorry to not have a real fix for you but hope the explanation helps. Thanks again for bringing up the issue.

**Comment by kevjp** [comment]
No problem Brad I can downsample the bams first and then feed it into BCBIO as you suggested just thought I might be able to do this by re-running the pipeline but with this setting. Thanks for highlighting this.
