### ISSUE TITLE
CatVariant not handling allele "*" in gatk-haplotype-joint

### ISSUE THREAD

**Issue by whitejbiii** [chapmanb/bcbio-nextgen#1057]
I am trying bcbio on an exome trio using joint calling with various callers. My run of gatk-haplotype-joint is failing with the following error.
```
##### ERROR stack trace 
htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 649: unparsable vcf record with allele *, for input source: /media/jawhite/Data/662-exome-trio/work/joint/gatk-haplotype-joint/trio-bwa-j/1/trio-bwa-j-1_0_15543565.vcf.gz
	at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:793)
	at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:578)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseSingleAltAllele(AbstractVCFCodec.java:618)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:548)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:342)
	at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:285)
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:263)
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:60)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:150)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:183)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:125)
	at org.broadinstitute.gatk.tools.CatVariants.execute(CatVariants.java:300)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:248)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:155)
	at org.broadinstitute.gatk.tools.CatVariants.main(CatVariants.java:317)
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A GATK RUNTIME ERROR has occurred (version 3.2-18-g478145d):
##### ERROR
```
Line 649 does indeed have an ALT entry of `A,*`, presumably generated by HaplotypeCaller. I looked at the CatVariants code on Github, and it appears to handle `*` alleles for ALT in the current version. Is this a version problem? I haven't figured out how to upgrade the htsjdk version that bcbio uses.

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for reporting it. We package the MIT licensed parts of the GATK in a separate script/jar to avoid needing to install GATK when running non-variant calling parts of the GATK code. This package was, as you noticed, out of date and on version 3.2. I updated it to 3.4-46 to match the latest release so it should hopefully work cleanly for you now if you upgrade with:
```
bcbio_nextgen.py upgrade -u development --tools
```
Hope this gets everything running cleanly for you. Thanks again for the report.
