### ISSUE TITLE
Missing reference file rtg/GRCh37.sdf required for validation

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1058]
Hi I am trying to validate some indels using exome calling pipeline but I seem to get this error being thrown up when it comes to the validation step. The error relates to this file /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/rtg/GRCh37.sdf which I don't seem to have on my system. I tried running the suggested command in the error message 
```bcbio_nextgen.py upgrade --data --aligners rtg``` but this did not solve the issue. Any help would be great. Thanks

Error message below:

```
[2015-10-09T17:24Z] Intersect callable intervals for rtg vcfeval
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 179, in run
    samples = run_parallel("compare_to_rm", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 190, in compare_to_rm
    return validate.compare_to_rm(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/validate.py", line 99, in compare_to_rm
    eval_files = _run_rtg_eval(vrn_file, rm_file, rm_interval_file, base_dir, toval_data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/validate.py", line 152, in _run_rtg_eval
    "Run bcbio_nextgen.py upgrade --data --aligners rtg" % rtg_ref)
AssertionError: Did not find rtg indexed reference file for validation:
/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/rtg/GRCh37.sdf
Run bcbio_nextgen.py upgrade --data --aligners rtg
```

**Comment by chapmanb** [comment]
Sorry about the problem. The new bcbio versions use an updated approach for validation with Real Time Genomics vcfeval tool. bcbio should be building the indexes for these automatically now, but the command you ran should definitely do it.

What type of output do you get when you run:
```
bcbio_nextgen.py upgrade --data --aligners rtg
```
Are there error messages or attempts to run the rtg indexing that fail?

Is there any rtg directory in `/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/`?

Happy to try and debug more with any details about what is going on with the indexing attempts. Thanks much for the report.

**Comment by kevjp** [comment]
Thanks my apologies didn't mean to waste your time, not sure what happened but I reran the command and it worked perhaps there were connectivity issues.
