### ISSUE TITLE
Error using coverage_report

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1061]
[2015-10-11T21:43Z] doing coverage for SMPL9_analysis
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 201, in run
    samples = qcsummary.report_summary(samples, run_parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 1030, in report_summary
    samples = run_parallel("coverage_report", samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 98, in coverage_report
    return qcsummary.coverage_report(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 1047, in coverage_report
    data = cov.coverage(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage_experimental.py", line 172, in coverage
    _silence_run(cmd.format(**locals()))
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage_experimental.py", line 93, in _silence_run
    do._do_run(cmd, False)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
' returned non-zero exit status 1

**Comment by lpantano** [comment]
Hi,

sorry about this problem. Any chance you are not in the last development version. This code is changing a lot, and maybe you got some version with some bug. Could you try to update and run again to see if this error goes?

sorry about this. hope the update fixes it.

**Comment by deber1980** [comment]
Yeah, its not the most op to date version. I'll try updating. Thanks

**Comment by roryk** [comment]
Thanks, let us know if you run into any problems. We've done a bunch of development in that section over the past couple of weeks so there might be some unresolved issues.

**Comment by deber1980** [comment]
OK. Is it still under heavy dev? Would it be better to wait few more days before updating?

**Comment by roryk** [comment]
Hi @deber1980,

We've been using it and it works great, it should work out of the box for you so if it doesn't, we'd appreciate knowing if it doesn't. :)

**Comment by deber1980** [comment]
Sure. thanks

**Comment by deber1980** [comment]
I've updated the code but I'm still getting this error.
Any clue?

Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 198, in run
    samples = qcsummary.report_summary(samples, run_parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 1039, in report_summary
    samples = run_parallel("coverage_report", samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 98, in coverage_report
    return qcsummary.coverage_report(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 1058, in coverage_report
    data = cov.priority_coverage(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage_experimental.py", line 180, in priority_coverage
    _silence_run(cmd.format(**locals()))
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage_experimental.py", line 18, in _silence_run
    do._do_run(cmd, False)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
' returned non-zero exit status 1

**Comment by lpantano** [comment]
Hi,
sorry about this problem. We tried to get this step quicker calling samtools with many regions at the same time. I guess we are not getting that maximum argument value correctly in your case. 

could you do ` getconf ARG_MAX` and tell us what gives you?

thanks

**Comment by deber1980** [comment]
I'm using bcbio_vm. Here is the output:
ubuntu@frontend001:~$ getconf ARG_MAX
2097152

**Comment by roryk** [comment]
Hi @deber1980,

Is frontend001 where you run the jobs, or do they get submitted to other machines? Is it the same on the nodes you run the jobs on?

Best,

Rory

**Comment by deber1980** [comment]
Hey Rory. I run the jobs on frontend. Its c3.2xlarge

**Comment by roryk** [comment]
Hi @deber1980,

Sorry about that-- there is a section of code where we try to figure out what the maximum argument length is so we can break up a command into as few commands as possible, I thought we were being pretty conservative about it but it looks like we weren't. I added some code to turn this down a little bit and hopefully that fixes the problem. Let us know if that works, if not we can turn it down even more.

It would be helpful if it doesn't work if you could post up a gist of your bcbio-nextgen-commands.log file, so we can look and see how long the command is.

Best,

Rory

**Comment by deber1980** [comment]
Thanks. I'll check it out

**Comment by roryk** [comment]
Did this end up working eventually or are you still having some issues? Thanks!

**Comment by deber1980** [comment]
Hi Rory,
I didn't got the chance to examine it again yet. I'm closing it for now and re-open in case I'll encountered it again.
Thanks

**Comment by roryk** [comment]
Thanks!
