### ISSUE TITLE
cnvkit error if no probe on a chromosome

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1064]
I would like to run cnvkit on a target caputre baitset project. I am getting this error if not probe are present on a chromosome. This is really common for the Contig Chromosome. 
e.g. chr19_gl000209_random	500	158669	-	-1.0053	_
if I remove this line from the cns file I do not get any error.

Thanks!

subprocess.CalledProcessError: Command '/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/cnvkit.py gainloss -s /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Hemepact_PCNSL/Hemepact_PCNSL/work/structural/s_IM_pcnsl_037_T/cnvkit/raw/25_2015-10-01_Hemepact_PCNSL-sort.cns -o /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Hemepact_PCNSL/Hemepact_PCNSL/work/structural/s_IM_pcnsl_037_T/cnvkit/raw/tx/tmpIomhiQ/25_2015-10-01_Hemepact_PCNSL-sort-gainloss.txt /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Hemepact_PCNSL/Hemepact_PCNSL/work/structural/s_IM_pcnsl_037_T/cnvkit/raw/25_2015-10-01_Hemepact_PCNSL-sort.cns
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1162, in _cmd_gainloss
    args.min_probes)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1172, in do_gainloss
    probes = probes.shift_xx(male_reference)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/cnary.py", line 245, in shift_xx
    is_xx = self.guess_xx(male_reference=male_reference)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/cnary.py", line 266, in guess_xx
    rel_chrx_cvg = self.get_relative_chrx_cvg()
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/cnary.py", line 289, in get_relative_chrx_cvg
    np.average(auto_cvgs, weights=auto_sizes))
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 518, in average
    wgt = np.array(weights, dtype=a.dtype, copy=0)
ValueError: could not convert string to float: _
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the problem. Eric pushed a fix in CNVkit 0.7.2 which should resolve this issue and I updated the conda package so if you do:
```
bcbio_nextgen.py upgrade --tools
```
You should get the latest version which fixes the issue. You'll have to re-run the CNVkit calling to regenerate the cns and cnr files with the problem characters. Hope this fixes it for you.

**Comment by apastore** [comment]
Thanks!
