### ISSUE TITLE
metasv error after last lumpy/svtyper update

### ISSUE THREAD

**Issue by druvus** [chapmanb/bcbio-nextgen#1075]
Hi Brad, 
I run into problem with metaSV after the latest lumpy/svtyper update (using latest development version). The same example dataset run smoothly before the update both from pre-aligned bam and fastq files. Not sure what is going on so included a snipped from the debug file. 

<pre>
[2015-10-23T07:18Z] m157.uppmax.uu.se: INFO 2015-10-23 09:18:50,725 generate_sc_intervals-<Process(PoolWorker-6, started daemon)> Generating candidate insertion intervals from /pica/v5/b2011196_nobackup/work/andreas/bcbio/SV/analysis/SV_test/work/prealign/19_102/19_102.bwa-mem.sorted.md.real.fm.recal.bam for chromsome GL000196.1
[2015-10-23T07:18Z] m157.uppmax.uu.se: INFO 2015-10-23 09:18:50,745 generate_sc_intervals-<Process(PoolWorker-11, started daemon)> 23 merged intervals
[2015-10-23T07:18Z] m157.uppmax.uu.se: INFO 2015-10-23 09:18:50,747 generate_sc_intervals-<Process(PoolWorker-10, started daemon)> 41 merged intervals
[2015-10-23T07:18Z] m157.uppmax.uu.se: ERROR 2015-10-23 09:18:50,755 generate_sc_intervals-<Process(PoolWorker-10, started daemon)> Caught exception in worker thread
[2015-10-23T07:18Z] m157.uppmax.uu.se: Traceback (most recent call last):
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 143, in generate_sc_intervals
[2015-10-23T07:18Z] m157.uppmax.uu.se:     filtered_bed)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 775, in decorated
[2015-10-23T07:18Z] m157.uppmax.uu.se:     result = method(self, *args, **kwargs)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2913, in moveto
[2015-10-23T07:18Z] m157.uppmax.uu.se:     fn = self._collapse(self, fn=fn)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1215, in _collapse
[2015-10-23T07:18Z] m157.uppmax.uu.se:     for i in iterable:
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pybedtools/cbedtools.pyx", line 731, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:10588)
[2015-10-23T07:18Z] m157.uppmax.uu.se: ERROR 2015-10-23 09:18:50,758 generate_sc_intervals-<Process(PoolWorker-11, started daemon)> Caught exception in worker thread
[2015-10-23T07:18Z] m157.uppmax.uu.se: Traceback (most recent call last):
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 143, in generate_sc_intervals
[2015-10-23T07:18Z] m157.uppmax.uu.se:     filtered_bed)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 775, in decorated
[2015-10-23T07:18Z] m157.uppmax.uu.se:     result = method(self, *args, **kwargs)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2913, in moveto
[2015-10-23T07:18Z] m157.uppmax.uu.se:     fn = self._collapse(self, fn=fn)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1215, in _collapse
[2015-10-23T07:18Z] m157.uppmax.uu.se:     for i in iterable:
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pybedtools/cbedtools.pyx", line 731, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:10588)
[2015-10-23T07:18Z] m157.uppmax.uu.se:     line = next(self.stream)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 876, in _generator
[2015-10-23T07:18Z] m157.uppmax.uu.se:     result = func(f, *args, **kwargs)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 81, in merged_interval_features
[2015-10-23T07:18Z] m157.uppmax.uu.se:     interval_readcount = bam_handle.count(reference=feature.chrom, start=feature.start, end=feature.end)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 1123, in pysam.calignmentfile.AlignmentFile.count (pysam/calignmentfile.c:12851)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 857, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10761)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 712, in pysam.calignmentfile.AlignmentFile.parse_region (pysam/calignmentfile.c:9552)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 1565, in pysam.calignmentfile.AlignmentFile.gettid (pysam/calignmentfile.c:17644)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 630, in pysam.calignmentfile.AlignmentFile.get_tid (pysam/calignmentfile.c:8625)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/cutils.pyx", line 102, in pysam.cutils.force_bytes (pysam/cutils.c:2175)
[2015-10-23T07:18Z] m157.uppmax.uu.se: TypeError: Expected bytes, got unicode
[2015-10-23T07:18Z] m157.uppmax.uu.se:     line = next(self.stream)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 876, in _generator
[2015-10-23T07:18Z] m157.uppmax.uu.se:     result = func(f, *args, **kwargs)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 81, in merged_interval_features
[2015-10-23T07:18Z] m157.uppmax.uu.se:     interval_readcount = bam_handle.count(reference=feature.chrom, start=feature.start, end=feature.end)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 1123, in pysam.calignmentfile.AlignmentFile.count (pysam/calignmentfile.c:12851)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 857, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10761)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 712, in pysam.calignmentfile.AlignmentFile.parse_region (pysam/calignmentfile.c:9552)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 1565, in pysam.calignmentfile.AlignmentFile.gettid (pysam/calignmentfile.c:17644)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/calignmentfile.pyx", line 630, in pysam.calignmentfile.AlignmentFile.get_tid (pysam/calignmentfile.c:8625)
[2015-10-23T07:18Z] m157.uppmax.uu.se:   File "pysam/cutils.pyx", line 102, in pysam.cutils.force_bytes (pysam/cutils.c:2175)
[2015-10-23T07:18Z] m157.uppmax.uu.se: TypeError: Expected bytes, got unicode
[2015-10-23T07:18Z] m157.uppmax.uu.se: INFO 2015-10-23 09:18:50,769 generate_sc_intervals-<Process(PoolWorker-10, started daemon)> Generating candidate insertion intervals from /pica/v5/b2011196_nobackup/work/andreas/bcbio/SV/analysis/SV_test/work/prealign/19_102/19_102.bwa-mem.sorted.md.real.fm.recal.bam for chromsome GL000227.1
[2015-10-23T07:18Z] m157.uppmax.uu.se: INFO 2015-10-23 09:18:50,957 generate_sc_intervals-<Process(PoolWorker-11, started daemon)> Generating candidate insertion intervals from /pica/v5/b2011196_nobackup/work/andreas/bcbio/SV/analysis/SV_test/work/prealign/19_102/19_102.bwa-mem.sorted.md.real.fm.recal.bam for chromsome GL000248.1
[2015-10-23T07:18Z] m157.uppmax.uu.se: INFO 2015-10-23 09:18:50,962 generate_sc_intervals-<Process(PoolWorker-6, started daemon)> 1 candidate reads
[2015-10-23T07:18Z] m157.uppmax.uu.se: INFO 2015-10-23 09:18:50,997 generate_sc_intervals-<Process(PoolWorker-6, started daemon)> 1 merged intervals
[2015-10-23T07:18Z] m157.uppmax.uu.se: INFO 2015-10-23 09:18:50,999 generate_sc_intervals-<Process(PoolWorker-6, started daemon)> 0 filtered intervals
</pre>

Andreas

**Comment by chapmanb** [comment]
Andreas;
Sorry about the issue. I think what triggered it is that pybedtools returns unicode in the latest versions and feeding unicode chromosome names to pysam causes issues. I pushed a fix to MetaSV that will hopefully resolve this if you upgrade the `--tools`. Let me know if this doesn't fix things and happy to dig into it more. Thanks again.
