### ISSUE TITLE
Changes in metasv variables

### ISSUE THREAD

**Issue by druvus** [chapmanb/bcbio-nextgen#1078]
I found some additional issues while testing metasv. It seems that Metasv removed the --boost_ins variable and replaced it with the more generic --boost-sc variable. However just swapping doesn't work and I get the following error: 

```
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:11,736 generate_sc_intervals-<Process(PoolWorker-5, started daemon)> 22765 candidate reads
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:13,113 generate_sc_intervals-<Process(PoolWorker-12, started daemon)> Generated intervals in 22.8473 seconds for region
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:13,114 generate_sc_intervals-<Process(PoolWorker-12, started daemon)> Generating candidate intervals from /pica/v5/b201
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:14,545 generate_sc_intervals-<Process(PoolWorker-10, started daemon)> Generated intervals in 24.18 seconds for region G
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:14,545 generate_sc_intervals-<Process(PoolWorker-10, started daemon)> Generating candidate intervals from /pica/v5/b201
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:14,669 generate_sc_intervals-<Process(PoolWorker-15, started daemon)> 1413 candidate reads
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:16,050 generate_sc_intervals-<Process(PoolWorker-7, started daemon)> Generated intervals in 25.6849 seconds for region
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:16,218 generate_sc_intervals-<Process(PoolWorker-7, started daemon)> Generating candidate intervals from /pica/v5/b2011
[2015-10-25T19:23Z] m35.uppmax.uu.se: ERROR 2015-10-25 20:23:28,063 generate_sc_intervals-<Process(PoolWorker-5, started daemon)> Caught exception in worker thread
[2015-10-25T19:23Z] m35.uppmax.uu.se: Traceback (most recent call last):
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 486, in generate_s
[2015-10-25T19:23Z] m35.uppmax.uu.se:     reciprocal_for_2bp=False, sv_type_field = [6,0])
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 334, in merge_for_
[2015-10-25T19:23Z] m35.uppmax.uu.se:     merged_bedtool=sv_bedtool.cat(merged_bedtool,postmerge=False)
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 775, in decorated
[2015-10-25T19:23Z] m35.uppmax.uu.se:     result = method(self, *args, **kwargs)
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2796, in cat
[2015-10-25T19:23Z] m35.uppmax.uu.se:     + [i.file_type for i in other_beds]).difference(['empty'])
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 969, in file_type
[2015-10-25T19:23Z] m35.uppmax.uu.se:     self._file_type = six.advance_iterator(iter(self)).file_type
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "pybedtools/cbedtools.pyx", line 772, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:11001)
[2015-10-25T19:23Z] m35.uppmax.uu.se:     return create_interval_from_list(fields)
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "pybedtools/cbedtools.pyx", line 637, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:9068)
[2015-10-25T19:23Z] m35.uppmax.uu.se:     elif isdigit(fields[1]) and isdigit(fields[2]):
[2015-10-25T19:23Z] m35.uppmax.uu.se: IndexError: list index out of range
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:28,292 generate_sc_intervals-<Process(PoolWorker-5, started daemon)> Generating candidate intervals from /pica/v5/b2011
[2015-10-25T19:23Z] m35.uppmax.uu.se: ERROR 2015-10-25 20:23:31,744 generate_sc_intervals-<Process(PoolWorker-15, started daemon)> Caught exception in worker thread
[2015-10-25T19:23Z] m35.uppmax.uu.se: Traceback (most recent call last):
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 486, in generate_s
[2015-10-25T19:23Z] m35.uppmax.uu.se:     reciprocal_for_2bp=False, sv_type_field = [6,0])
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 334, in merge_for_
[2015-10-25T19:23Z] m35.uppmax.uu.se:     merged_bedtool=sv_bedtool.cat(merged_bedtool,postmerge=False)
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 775, in decorated
[2015-10-25T19:23Z] m35.uppmax.uu.se:     result = method(self, *args, **kwargs)
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2796, in cat
[2015-10-25T19:23Z] m35.uppmax.uu.se:     + [i.file_type for i in other_beds]).difference(['empty'])
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "/proj/b2014086/nobackup/bin/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 969, in file_type
[2015-10-25T19:23Z] m35.uppmax.uu.se:     self._file_type = six.advance_iterator(iter(self)).file_type
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "pybedtools/cbedtools.pyx", line 772, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:11001)
[2015-10-25T19:23Z] m35.uppmax.uu.se:     return create_interval_from_list(fields)
[2015-10-25T19:23Z] m35.uppmax.uu.se:   File "pybedtools/cbedtools.pyx", line 637, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:9068)
[2015-10-25T19:23Z] m35.uppmax.uu.se:     elif isdigit(fields[1]) and isdigit(fields[2]):
[2015-10-25T19:23Z] m35.uppmax.uu.se: IndexError: list index out of range
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:31,951 generate_sc_intervals-<Process(PoolWorker-15, started daemon)> Generating candidate intervals from /pica/v5/b201
[2015-10-25T19:23Z] m35.uppmax.uu.se: WARNING 2015-10-25 20:23:32,787 generate_sc_intervals-<Process(PoolWorker-15, started daemon)> No intervals generated
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:32,987 generate_sc_intervals-<Process(PoolWorker-15, started daemon)> Generating candidate intervals from /pica/v5/b201
[2015-10-25T19:23Z] m35.uppmax.uu.se: WARNING 2015-10-25 20:23:34,570 generate_sc_intervals-<Process(PoolWorker-15, started daemon)> No intervals generated
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:34,755 generate_sc_intervals-<Process(PoolWorker-15, started daemon)> Generating candidate intervals from /pica/v5/b201
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:36,006 generate_sc_intervals-<Process(PoolWorker-5, started daemon)> 165 candidate reads
[2015-10-25T19:23Z] m35.uppmax.uu.se: INFO 2015-10-25 20:23:41,779 generate_sc_intervals-<Process(PoolWorker-15, started daemon)> 8 candidate reads
```

**Comment by chapmanb** [comment]
Andreas;
Sorry for the delay in finalizing this. I didn't want to make you chase down bugs so ran through the full validation on the synthetic 4 dataset to chase down issues. If you update to the latest development (`bcbio_nextgen.py upgrade -u development --tools`) it should now work correctly and I've also sent a PR to the main MetaSV repo (bioinform/metasv#76). The source of your specific error here is an issue with sending empty files to pybedtools.cat, which will also be fixed in the next pybedtools release (daler/pybedtools#149), but we have workarounds in place now.

Thanks again for testing this out, hope the new version works cleanly for you.
