### ISSUE TITLE
gemini upgrade fails

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1085]
I can't get passed gemini on one my installs. Ideas?

```
Requirement already satisfied (use --upgrade to upgrade): pandas>=0.11.0 in /srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 16))                                                                             [33/1733]
Requirement already satisfied (use --upgrade to upgrade): openpyxl<2.0.0,>=1.6.1 in /srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.12.0 in /srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): Unidecode>=0.04.14 in /srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): cyordereddict==0.2.2 in /srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 20))
Collecting bcolz>=0.11.3 (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 21))
  Using cached bcolz-0.11.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numexpr>=2.4.3 in /srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 22))
Collecting gemini==0.17.2 (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 23))
  Using cached gemini-0.17.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in gemini setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2dbSRv/gemini
Traceback (most recent call last):
  File "gemini_install.py", line 388, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 91, in main
    gemini = install_gemini(anaconda, remotes, args.datadir, args.tooldir, args.sudo)
  File "gemini_install.py", line 164, in install_gemini
    subprocess.check_call([anaconda["pip"], "install"] + pip_compat + ["-r", remotes["requirements_pip"]])
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/bin/pip', 'install', '--allow-external', 'python-graph-core', '--allow-unverified', 'python-graph-core', '--allow-external', 'python-graph-dot', '--allow-unverified', 'python-graph-dot', '-r', 'https://raw.github.com/arq5x/gemi
ni/master/requirements.txt']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/srv/gsfs0/projects/ashley/apps/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 88, in upgrade_bcbio
    _install_toolplus(args)
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 396, in _install_toolplus
    _install_gemini(args.tooldir, _get_data_dir(), args)
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 479, in _install_gemini
    subprocess.check_call(cmd)
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/bin/python', '-Es', 'gemini_install.py', '/srv/gsfs0/projects/ashley/apps', '/srv/gsfs0/projects/ashley/apps/bcbio', '--notools', '--nodata', '--sharedpy', '--nosudo']' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issue. I've been trying to reproduce this but haven't had any luck. What version of pip are you using:
```
/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/bin/pip --version
```
Maybe running an update of that:
```
/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/bin/conda install pip
```
will get you a version that installs gemini cleanly. Hope this helps.

**Comment by dwaggott** [comment]
pip looks up to date. Is there a manual purge and gemini reinstall possibility before I do a reinstall? I'm running an isolated gemini install to see if anything shows up.

**Comment by dwaggott** [comment]
The independent install of gemini was fine. Attempting a bcbio upgrade right after actually worked. I guess I have some unexpected system dependencies. Yikes! Closing.
