### ISSUE TITLE
Possible error in Test suite

### ISSUE THREAD

**Issue by yanickpouliot** [chapmanb/bcbio-nextgen#1087]
Howdy yall. I'm going through the test-suite (https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#test-suite) and running into the error below.

Specifically, for "sudo ./run_tests.sh devel", test_automated_analysis.py eventually fails to find the requisite input file 7_100326_FC6107FAAXX-grade.vcf. At the beginning of the run, the file is there, but later on it gets compressed and a .gzip extension added to the filename. After that, the program no longer finds it 'cause of the .gzip and everything dies in sorrow...
 
[2015-10-29T20:42Z] Using input YAML configuration: /usr/local/share/bcbio/bcbio-nextgen/tests/data/automated/run_info-bam.yaml
[2015-10-29T20:42Z] Checking sample YAML configuration: /usr/local/share/bcbio/bcbio-nextgen/tests/data/automated/run_info-bam.yaml
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 139, in run
    [x[0]["description"] for x in samples]]])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 226, in organize_samples
    return run_info.organize(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 55, in organize
    item = add_reference_resources(item)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 142, in add_reference_resources
    data = _fill_validation_targets(data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 161, in _fill_validation_targets
    (vtarget, val))
ValueError: Configuration problem. Validation file not found for validate: ../data/reference_material/7_100326_FC6107FAAXX-grade.vcf
ERROR

======================================================================
ERROR: Allow BAM files as input to pipeline.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/share/bcbio/bcbio-nextgen/tests/test_automated_analysis.py", line 285, in test_5_bam
    subprocess.check_call(cl)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['bcbio_nextgen.py', '/usr/local/share/bcbio/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '/usr/local/share/bcbio/bcbio-nextgen/tests/data/automated/run_info-bam.yaml']' returned non-zero exit status 1

**Comment by yanickpouliot** [comment]
I'm noticing this problem also manifests when running the docker test...

[2015-10-29T21:36Z] Checking sample YAML configuration: /mnt/work/bcbio_sample-forvm.yaml
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 139, in run
    [x[0]["description"] for x in samples]]])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 230, in organize_samples
    return run_info.organize(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 55, in organize
    item = add_reference_resources(item)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 142, in add_reference_resources
    data = _fill_validation_targets(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 161, in _fill_validation_targets
    (vtarget, val))
ValueError: Configuration problem. Validation file not found for validate: /usr/local/share/bcbio/bcbio-nextgen/tests/data/reference_material/7_100326_FC6107FAAXX-grade.vcf
' returned non-zero exit status 1
ERROR

======================================================================
ERROR: Run an analysis with code and tools inside a docker container.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/share/bcbio/bcbio-nextgen/tests/test_automated_analysis.py", line 365, in test_docker
    subprocess.check_call(cl)
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['bcbio_vm.py', '--datadir=/usr/local/share/bcbio/bcbio-nextgen/tests/data/automated', 'run', '--systemconfig=/usr/local/share/bcbio/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '--fcdir=/usr/local/share/bcbio/bcbio-nextgen/tests/data/automated/../100326_FC6107FAAXX', '/usr/local/share/bcbio/bcbio-nextgen/tests/data/automated/run_info-bam.yaml']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 1 test in 53.878s

FAILED (errors=1)

**Comment by chapmanb** [comment]
Yannick;
Sorry about the issue. This is fixed in the latest development version of the code and avoids bgzipping these inputs in the original directory (which was a bad idea: https://github.com/chapmanb/bcbio-nextgen/commit/91ddd1b379e10f561293d7425d08001c0fae619a#diff-0cf3043ab7d23b5c690b55cd4e4bc6e7). If you upgrade with:
```
bcbio_nextgen.py upgrade -u development
```
and restore the original file: 
```
gunzip data/reference_material/7_100326_FC6107FAAXX-grade.vcf.gz
```
it should work cleanly. We might also need to update the docker container to have this fix and I'll push a new version of this over the weekend. Thanks again for the heads up and hope this fixes it for you.

**Comment by yanickpouliot** [comment]
Awesome! Thx so much Brad! I'm particularly looking forward to the update to the Docker Hub update, 'cause I'm experimenting with Amazon's EC2 Container Service (ECS) to launch images, and for some reason Docker Hub seems to be the only external image repository they support. Anyway, I see a great future to ECS in systematizing robust container launching management. And no, I don't work for Amazon :-)

PS: would you believe I refer to you as "Saint Brad" because of your incredible contributions to the field? :-)

**Comment by chapmanb** [comment]
Yannick;
Thanks much, although I think you're a bit premature in canonizing me. I agree that ECS looks great and saves a lot of the overhead we currently have in our AWS approach. Practically the major issue will be mounting the external data and making it available to the Docker containers. Our goal with bcbio is to move to using the common workflow langage (CWL) with Docker and then we can rely on external CWL-supporting infrastructure to do the underlying interaction with ECS (or other approaches). The documentation on the in-progress CWL is here: https://github.com/chapmanb/bcbio-nextgen/tree/master/cwl

Practically, we'll definitely still work on Docker hub support, but letting you know the current thoughts on infrastructure direction. Thanks again.
