### ISSUE TITLE
snpEff database address is incorrect

### ISSUE THREAD

**Issue by mdeboth** [chapmanb/bcbio-nextgen#1090]
When installing a genome, bcbio is trying to grab the snpEff database from the wrong address... snpEff should be v4_1, not v4_12.
```
Updating rn5 genome resources configuration
Installing snpEff database Rnor_5.0.78 in /packages/bcbio/v0.8.8/genomes/Rnorvegicus/rn5/snpeff
Traceback (most recent call last):
  File "/packages/bcbio/v0.8.8/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/packages/bcbio/v0.8.8/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 98, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/packages/bcbio/v0.8.8/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 260, in upgrade_bcbio_data
    _upgrade_snpeff_data(s["fabricrc_overrides"]["galaxy_home"], args, remotes)
  File "/packages/bcbio/v0.8.8/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 319, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "-c", "-O", dl_file, dl_url])
  File "/packages/bcbio/v0.8.8/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '-c', '-O', 'snpEff_v4_12_Rnor_5.0.78.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v4_12/snpEff_v4_12_Rnor_5.0.78.zip']' returned non-zero exit status 8
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/packages/python/python-2.7.10/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/packages/bcbio/v0.8.8/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=.', '--isolate', '--genomes', 'rn5', '--aligners', 'star', '--data']' returned non-zero exit status 1
```

It looks like bcbio might build the web address from the version number in brew-packages.yaml...
```
snpeff:
  name: snpeff
  version: 4.1l_2
```

A recent commit in homebrew-science adds a revision number (2) in the [snpEff recipe](https://github.com/Homebrew/homebrew-science/blob/fa709d2a15a43c1fce409c9321a0b4ea93ab6369/snpeff.rb#L9), which might be getting pulled into bcbio and breaking things.

Hope I got somewhere close to diagnosing this... I'll leave the fix to the brains of the operation.

**Comment by chapmanb** [comment]
Matt;
Thanks much for the heads up and the detailed investigation. You're right that we weren't handling the revisions in brew correctly here. I pushed a fix to cloudbiolinux to correctly write version manifests without revisions, so if you do a:
```
bcbio_nextgen.py upgrade --tools
```
you should then be able to run a data upgrade cleanly. Sorry about the problem and thanks again for the report.
