### ISSUE TITLE
polyphen is not available for this species or cache

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1092]
Hi,
I am running a whole-genome seq analysis for mouse samples and found the following error in bcbio-nextgen.log file. I used vep annotation in the yaml file. Could you help me with debugging?
Thanks!

[2015-10-31T01:23Z] *.edu: Finalizing variant calls: WT164, freebayes
[2015-10-31T01:23Z] *.edu: Calculating variation effects for WT164, freebayes
[2015-10-31T01:23Z] *.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PERL5LIB=./bcbio/lib/perl5:$PERL5LIB && ./bcbio/bin/variant_effect_predictor.pl --vcf -o stdout -i ./project/work/freebayes/WT164.vcf.gz --fork 16 --species mus_musculus --no_stats --cache --offline --dir ./bcbio/genomes/Mmusculus/mm10/vep --sift b --polyphen b --symbol --numbers --biotype --total_length --canonical --ccds --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE,CANONICAL,CCDS,LoF,LoF_filter,LoF_flags --plugin LoF,human_ancestor_fa:false | sed '/^#/! s/;;/;/g' | bgzip -c > ./project/work/freebayes/tx/tmpcvj8c3/WT164-vepeffects.vcf.gz
ERROR: --polyphen is not available for this species or cache at ./bcbio/bin/variant_effect_predictor.pl line 910.
' returned non-zero exit status 255
[2015-10-31T01:23Z] *.edu: Unexpected error
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 44, in _setup_logging
    yield config
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 181, in postprocess_variants
    return ipython.zip_args(apply(variation.postprocess_variants, *args))
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 18, in postprocess_variants
    ann_vrn_file, vrn_stats = effects.add_to_vcf(data["vrn_file"], data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 34, in add_to_vcf
    ann_vrn_file = run_vep(in_file, data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 156, in run_vep
    do.run(cmd, "Ensembl variant effect predictor", data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PERL5LIB=./bcbio/lib/perl5:$PERL5LIB && ./bcbio/bin/variant_effect_predictor.pl --vcf -o stdout -i ./project/work/freebayes/WT164.vcf.gz --fork 16 --species mus_musculus --no_stats --cache --offline --dir ./bcbio/genomes/Mmusculus/mm10/vep --sift b --polyphen b --symbol --numbers --biotype --total_length --canonical --ccds --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE,CANONICAL,CCDS,LoF,LoF_filter,LoF_flags --plugin LoF,human_ancestor_fa:false | sed '/^#/! s/;;/;/g' | bgzip -c > ./project/work/freebayes/tx/tmpcvj8c3/WT164-vepeffects.vcf.gz
ERROR: --polyphen is not available for this species or cache at ./bcbio/bin/variant_effect_predictor.pl line 910.

**Comment by chapmanb** [comment]
Sorry about the issues and thank you for the report. Apologies, we were adding human-only parameters to the command line which caused issues with VEP annotations on non-human runs. I pushed a fix to only add the human-specific parameters when running those analyses which should resolve the problem if you update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
Thank you again for reporting the problem.

**Comment by pengxiao78** [comment]
Thank you, Brad! Recently, I also put effects: vep in an exome-seq analysis for paired human tumor-normal samples. The running has been completed and I could not find any vep annotated vcf.gz in the final folder. However, I did find like batch*-ensemble-decompose-vepeffects.vcf.gz in work/gemini/. Are these final vep annotated vcf files? Thanks again.

**Comment by chapmanb** [comment]
Glad that helped. The variant call files in the `final` directory should have VEP annotations in them, but the files themselves won't have vep extensions. The final output file encompasses all the steps and tries to shorted the file names. If you look at the files themselves, do they have `CSQ` INFO tags with details from VEP? Hope this helps.
