### ISSUE TITLE
Missing readgroup ERROR

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1094]
I am attempting to run a gatk-haplotype-joint analysis. Each sample has been run across multiple hiseq lanes so I did the fastq alignment/add readgroups/merge bams prior to running bcbio_nextgen. Here is a portion of my yaml.
```  
- analysis: variant2
    description: E0040
    files: /home/bwubb/NGS/FAM-TGCT/bam_input/E0040/E0040.FAM-TGCT.5.bam
    genome_build: GRCh37
    metadata:
      batch: Batch1
    algorithm:
      aligner: false
      mark_duplicates: true
      recalibrate: gatk
      realign: gatk
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      variant_regions: /home/bwubb/BED/SureSelect.ExonV3_targets.bed
    upload:
      ../final
```

It begins chugging away and at some point things breaks, I believe during the dedup or base recalibrator. If it is going in order then it starts to break on the 11th sample of 25. The first few errors look like this.
```
[2015-10-30T03:25Z] Recalibrating ['', 'E0040'] with GATK
[2015-10-30T03:25Z] GATK: BaseRecalibrator
[2015-10-30T03:25Z] INFO  23:25:50,359 HelpFormatter - ---------------------------------------------------------------------------------
[2015-10-30T03:25Z] INFO  23:25:50,361 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.4-46-gbc02625, Compiled 2015/07/09 17:38:12
[2015-10-30T03:25Z] INFO  23:25:50,361 HelpFormatter - Copyright (c) 2010 The Broad Institute
[2015-10-30T03:25Z] INFO  23:25:50,361 HelpFormatter - For support and documentation go to http://www.broadinstitute.org/gatk
[2015-10-30T03:25Z] INFO  23:25:50,365 HelpFormatter - Program Args: -T BaseRecalibrator -o /home/bwubb/NGS/FAM-TGCT/data/work/prealign/E0040/tx/tmpW_qKxi/E0040.FAM-TGCT.5-dedup.grp -I /home/bwubb/NGS/FAM-TGCT/data/work/prealign/E0040/E0040.FAM-TGCT.5-dedup.bam -R /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --knownSites /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/variation/dbsnp_138.vcf.gz -L /home/bwubb/NGS/FAM-TGCT/data/work/bedprep/SureSelect.ExonV3_targets.bed --interval_set_rule INTERSECTION -nct 4 -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
[2015-10-30T03:25Z] INFO  23:25:50,371 HelpFormatter - Executing as bwubb@node136.hpc.local on Linux 2.6.32-504.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.7.0_71-mockbuild_2014_10_03_09_05-b00.
[2015-10-30T03:25Z] INFO  23:25:50,371 HelpFormatter - Date/Time: 2015/10/29 23:25:50
[2015-10-30T03:25Z] INFO  23:25:50,371 HelpFormatter - ---------------------------------------------------------------------------------
[2015-10-30T03:25Z] INFO  23:25:50,371 HelpFormatter - ---------------------------------------------------------------------------------
[2015-10-30T03:25Z] INFO  23:25:50,444 GenomeAnalysisEngine - Strictness is SILENT
[2015-10-30T03:25Z] INFO  23:25:50,535 GenomeAnalysisEngine - Downsampling Settings: No downsampling
[2015-10-30T03:25Z] INFO  23:25:50,543 SAMDataSource$SAMReaders - Initializing SAMRecords in serial
[2015-10-30T03:25Z] INFO  23:25:50,581 SAMDataSource$SAMReaders - Done initializing BAM readers: total time 0.04
[2015-10-30T03:25Z] Processing reference #20 (20)
[2015-10-30T03:26Z] INFO  23:26:00,750 IntervalUtils - Processing 51542852 bp from intervals
[2015-10-30T03:26Z] WARN  23:26:00,755 IndexDictionaryUtils - Track knownSites doesn't have a sequence dictionary built in, skipping dictionary validation
[2015-10-30T03:26Z] INFO  23:26:00,764 MicroScheduler - Running the GATK in parallel mode with 4 total threads, 4 CPU thread(s) for each of 1 data thread(s), of 32 processors available on this machine
[2015-10-30T03:26Z] INFO  23:26:00,823 GenomeAnalysisEngine - Preparing for traversal over 1 BAM files
[2015-10-30T03:26Z] INFO  23:26:01,229 GenomeAnalysisEngine - Done preparing for traversal
[2015-10-30T03:26Z] INFO  23:26:01,230 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING]
[2015-10-30T03:26Z] INFO  23:26:01,230 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining
[2015-10-30T03:26Z] INFO  23:26:01,230 ProgressMeter -        Location |     reads | elapsed |     reads | completed | runtime |   runtime
[2015-10-30T03:26Z] INFO  23:26:01,251 BaseRecalibrator - The covariates being used here:
[2015-10-30T03:26Z] INFO  23:26:01,251 BaseRecalibrator - 	ReadGroupCovariate
[2015-10-30T03:26Z] INFO  23:26:01,252 BaseRecalibrator - 	QualityScoreCovariate
[2015-10-30T03:26Z] INFO  23:26:01,252 BaseRecalibrator - 	ContextCovariate
[2015-10-30T03:26Z] INFO  23:26:01,252 ContextCovariate - 		Context sizes: base substitution model 2, indel substitution model 3
[2015-10-30T03:26Z] INFO  23:26:01,252 BaseRecalibrator - 	CycleCovariate
[2015-10-30T03:26Z] INFO  23:26:01,258 ReadShardBalancer$1 - Loading BAM index data
[2015-10-30T03:26Z] INFO  23:26:01,902 ReadShardBalancer$1 - Done loading BAM index data
[2015-10-30T03:26Z] INFO  23:26:03,036 GATKRunReport - Uploaded run statistics report to AWS S3
[2015-10-30T03:26Z] ##### ERROR ------------------------------------------------------------------------------------------
[2015-10-30T03:26Z] ##### ERROR A USER ERROR has occurred (version 3.4-46-gbc02625):
[2015-10-30T03:26Z] ##### ERROR
[2015-10-30T03:26Z] ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2015-10-30T03:26Z] ##### ERROR The error message below tells you what is the problem.
[2015-10-30T03:26Z] ##### ERROR
[2015-10-30T03:26Z] ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2015-10-30T03:26Z] ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2015-10-30T03:26Z] ##### ERROR
[2015-10-30T03:26Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2015-10-30T03:26Z] ##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
[2015-10-30T03:26Z] ##### ERROR
[2015-10-30T03:26Z] ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
[2015-10-30T03:26Z] ##### ERROR
[2015-10-30T03:26Z] ##### ERROR MESSAGE: SAM/BAM/CRAM file htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter@7eb37922 is malformed: Read HWI-ST1160:472:D230AACXX:4:1110:3876:23376 is missing the read group (RG) tag, which is required by the GATK.  Please use http://gatkforums.broadinstitute.org/discussion/59/companion-utilities-replacereadgroups to fix this problem
[2015-10-30T03:26Z] ##### ERROR ------------------------------------------------------------------------------------------
[2015-10-30T03:26Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
```

I notice this error for five more samples before I get a halt, (which I think is just the general run parallel crash)

```
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 149, in run
    samples = run_parallel("postprocess_alignment", samples)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```

Now I have started to look through my input bams for which I receive the errors. The reads referenced in the ERROR messages definitely have a RG tag. From what I can tell not a single read in any of the bams are lacking RG tags. Everything is as it should be.

In the interest of full disclosure this data older and has never behaved very kindly. I do not recall what previous issues were but it took some finesse to push it through previous GATK Best Practices for UnifiedGenotyper. I was hoping things would be smoother this time around. Since this appears to be a GATK error, and if more appropriate, I can try and run the commands individually and take issue up at the Broad. Thank you.

-Brad W

**Comment by chapmanb** [comment]
Brad;
Sorry about the issues. GATK doesn't like the way you specified your read groups, although it's tough to tell exactly why. Practically if you only want to get these processed, could you re-align these with bcbio and let it set the read groups? Or skip the BaseRecalibration step and see if any other commands error out on the input?

If you'd like to dig more, the best bet would be to start with the failing command try to reproduce outside of bcbio:
```
java -Xms1g -Xmx2g -jar /path/to/gatk.jar -T BaseRecalibrator -o E0040.FAM-TGCT.5-dedup.grp -I /home/bwubb/NGS/FAM-TGCT/data/work/prealign/E0040/E0040.FAM-TGCT.5-dedup.bam -R /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --knownSites /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/variation/dbsnp_138.vcf.gz -L /home/bwubb/NGS/FAM-TGCT/data/work/bedprep/SureSelect.ExonV3_targets.bed --interval_set_rule INTERSECTION -nct 4 -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
```
If you can isolate down to a small file that reproduces the problem, then I agree submitting to the GATK forum would be a good next bet to see if they have any ideas. Hope this helps.

**Comment by bwubb** [comment]
Ok I have done a bit more investigating. My input bam file has the Readgroup tag.

```
samtools view ../bam_input/E0040/E0040.FAM-TGCT.5.bam | grep "HWI-ST1160:472:D230AACXX:4:1110:3876:23376"
HWI-ST1160:472:D230AACXX:4:1110:3876:23376      163     1       14672   48      95M5S   =       14770   198     GGGGGGAAGGTGTCATGGAGCCCCCTACGATTCCCAGTCGTCCTCGTCCTCCTCTGCCTGTGGCTGCTGCGGTGGCGGCAGAGGAGGGATGGAGTTTGGC  ??<DDD@DBD5:?AA;CCCACDDDBDDDB@DDDEDDD8>:B?BBCBBB??AAC?CCCCCACCDB??################################## NM:i:0   MD:Z:95 AS:i:95 XS:i:90 XA:Z:9,+14783,95M5S,1;15,-102516399,5S95M,1;2,-114356247,5S95M,2;       RG:Z:FGC0472-4-GATCAG
HWI-ST1160:472:D230AACXX:4:1110:3876:23376      83      1       14770   40      100M    =       14672   -198    ACACGCGGGCAAAGGCTCCTCCGGGCCCCTCACCAGCCCCAGGTCCTTTCCCAGAGATGCCTGGAGGGAAAAGGCTGAGTGAGGGTGGTTGGTGGGAAAC  B@9BB@AAACCCC@BBBBBBBBBB?BBBCC>>?EEHFFEIIIGGGFDIHEGGIGGDBHGBIIIIIIIHFIGHGIG@IHGIHGHGBGIHHDAHDBDDD@@@ NM:i:0   MD:Z:100        AS:i:100        XS:i:100        RG:Z:FGC0472-4-GATCAG
```

It appears that the dedup bam created by bcbio has DROPPED the readgroup tag.

```
samtools view /home/bwubb/NGS/FAM-TGCT/data/work/prealign/E0040/E0040.FAM-TGCT.5-dedup.bam | grep "HWI-ST1160:472:D230AACXX:4:1110:3876:23376"
HWI-ST1160:472:D230AACXX:4:1110:3876:23376      163     1       14672   48      95M5S   =       14770   198     GGGGGGAAGGTGTCATGGAGCCCCCTACGATTCCCAGTCGTCCTCGTCCTCCTCTGCCTGTGGCTGCTGCGGTGGCGGCAGAGGAGGGATGGAGTTTGGC  ??<DDD@DBD5:?AA;CCCACDDDBDDDB@DDDEDDD8>:B?BBCBBB??AAC?CCCCCACCDB??################################## NM:i:0   MD:Z:95 AS:i:95 XS:i:90 XA:Z:9,+14783,95M5S,1;15,-102516399,5S95M,1;2,-114356247,5S95M,2;
HWI-ST1160:472:D230AACXX:4:1110:3876:23376      83      1       14770   40      100M    =       14672   -198    ACACGCGGGCAAAGGCTCCTCCGGGCCCCTCACCAGCCCCAGGTCCTTTCCCAGAGATGCCTGGAGGGAAAAGGCTGAGTGAGGGTGGTTGGTGGGAAAC  B@9BB@AAACCCC@BBBBBBBBBB?BBBCC>>?EEHFFEIIIGGGFDIHEGGIGGDBHGBIIIIIIIHFIGHGIG@IHGIHGHGBGIHHDAHDBDDD@@@ NM:i:0   MD:Z:100        AS:i:100        XS:i:100
```

As you suggested, GATK does not like this. I am hesitant to do a realign with bcbio. These input bams are the merging of multiple lanes from multiple sequencing runs. Each lane of each run gets its own readgroup. This is the practice that I have adaopted in case any one of those runs/lanes are trash I can remove them specifically.

**Comment by chapmanb** [comment]
Brad;
Thanks for the detective work. That's definitely unexpected and I'm confused as to what happened. bcbio uses bammarkduplicates from biobambam2 for marking duplicates for pre-aligned inputs, and I can't replicate the read group splitting so am not sure why it's happening here. If you could subset your file and send it to me:
```
samtools view ../bam_input/E0040/E0040.FAM-TGCT.5.bam 1:14672-14770 > subset.bam
```
I'd be happy to dig deeper. Alternatively you could try to find the equivalent bammarkduplicates command in your `log/bcbio-nextgen-commands.log` to see if you can replicate the behavior with a small subset. Hopefully this'll help us identify the underlying problem. Thanks for helping with debugging.
