### ISSUE TITLE
KeyboardInterrupt Error? Tumor/Normal pipeline

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1096]
I am full of errors today. For a different project with tumor/normal whole exome sequencing I see the following error type:

```
[2015-10-31T13:55Z] Resource requests: bamtools, bcbio_variation, fastqc, gatk, gemini, qsignature, samtools, snpeff; memory: 1.50, 0.62, 1.50, 6.25, 1.50, 0.50, 2.00, 6.25; cores: 1, 1, 1, 1, 1, 1, 4, 1
[2015-10-31T13:55Z] Configuring 3 jobs to run, using 4 cores each with 25.1g of memory reserved for each job
[2015-10-31T13:55Z] Timing: joint squaring off/backfilling
[2015-10-31T13:55Z] Timing: variant post-processing
[2015-10-31T13:55Z] multiprocessing: postprocess_variants
[2015-10-31T13:55Z] Finalizing variant calls: Brca1Br11-T, mutect
[2015-10-31T13:55Z] Calculating variation effects for Brca1Br11-T, mutect
[2015-10-31T13:55Z] Finalizing variant calls: Brca1Br11-T, freebayes
[2015-10-31T13:55Z] Calculating variation effects for Brca1Br11-T, freebayes
[2015-10-31T13:55Z] Finalizing variant calls: Brca1Br11-T, vardict
[2015-10-31T13:55Z] Calculating variation effects for Brca1Br11-T, vardict
[2015-10-31T13:55Z] snpEff effects : Brca1Br11-T
[2015-10-31T13:55Z] snpEff effects : Brca1Br11-T
[2015-10-31T13:55Z] snpEff effects : Brca1Br11-T
[2015-10-31T13:56Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 78, in _do_run
    line = s.stdout.readline()
KeyboardInterrupt
[2015-10-31T13:56Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 78, in _do_run
    line = s.stdout.readline()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 175, in run
    samples = run_parallel("postprocess_variants", samples)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 530, in retrieve
    raise exception
KeyboardInterrupt
```

I was wondering if maybe this simply had to do with memory allocation. I queue these bcbio runs with 16 available cores and 30G memory allocation. All of my java configurations specify Xmx25g, so there could not be 25.1g reserved for each job as the few lines preceeding the errors might suggest. Beyond that I am not quite sure what could be going on. Thank you.

-Brad W

**Comment by chapmanb** [comment]
Brad;
`KeyboardInterrupt` usually signals that a process was manually kiiled with Ctrl-C. Is it possible these were manually killed by someone?

Regarding memory, it looks like the configuration is asking for 4 cores and 6.25Gb of memory/core:
```
 1.50, 0.62, 1.50, 6.25, 1.50, 0.50, 2.00, 6.25; cores: 1, 1, 1, 1, 1, 1, 4, 1
```
then bcbio adds on a little extra to not completely fill up memory it's process, so 4 * 6.25 + 100Mb = 25.1. If you have 30Gb of memory that should be under the memory requirements.

Practically, on a re-run does it die at the same point or keep processing?

Hope this helps some with debugging.

**Comment by bwubb** [comment]
Hmm perhaps I did kill the jobs on our HPC cluster...? I reran a sample pair and it died somewhere else. I feel like this error is familiar... it looks like it is breaking at the very end, trying to upload to final dir?

```
[2015-11-04T18:09Z] multiprocessing: upload_samples
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 202, in run
    samples = run_parallel("upload_samples", samples)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 234, in upload_samples
    return upload.from_sample(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 30, in from_sample
    approach = _approaches[upload_config.get("method", "filesystem")]
AttributeError: 'str' object has no attribute 'get'
```

**Comment by chapmanb** [comment]
Brad;
Glad you got through the previous issue. The latest error looks like you have an incorrect `upload` specification in your input YAML file. It should be a dictionary with `dir` specifying the location of the output directory:

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/bcbio_sample.yaml#L12

The error reads like you might have `upload: ../your_dir` instead. Hope this helps get the analysis finished.

**Comment by bwubb** [comment]
What a simple mistake I have made.
