### ISSUE TITLE
varscan fail in tumor only bcbio 0.9.4

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1098]
Hi I am running varscan in tumor only mode and i get this error. if I run the outside bcbio it return no error and it return 

I have upload the partial bam in this folder 
https://drive.google.com/open?id=0B2qoICnODXDqV3hJQnUtaGpKd0E

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
chr13	5567958	N	0		
chr13	5567959	N	0		
chr13	5567960	N	0		
chr13	5567961	N	0		
chr13	5567962	N	0		
chr13	5567963	N	0		
chr13	5567964	N	0		
chr13	5567965	N	0		
chr13	5567966	N	0		
chr13	5567967	N	0		
chr13	5567968	N	0		
chr13	5567969	N	0		
chr13	5567970	N	0		
chr13	5567971	N	0		
chr13	5567972	N	0		
chr13	5567973	N	0		
chr13	5567974	N	0		
chr13	5567975	N	0		
chr13	5567976	N	0

Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/samtools mpileup -f /cbio/cslab/nobackup/pastore/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -d 1000 -L 1000 -r chr13:1-19020044 /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/SE_CLL/21626T-H3K27ac/work/bamprep/Ch1000-21626T-H3K27ac-136-150921-TS12-A12_CTTGTA_AHY7YCADXX_L001_001/chr13/1_2015-11-03_21626T-H3K27ac-sort-chr13_0_19020044-prep.bam | grep -v -P '	0		$' > /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/SE_CLL/21626T-H3K27ac/work/varscan/chr13/tx/tmpZdRB6w/tx/tmpVqIdj8/21626T-H3K27ac-chr13_0_19020044-raw.mpileup
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
' returned non-zero exit status 1
[2015-11-05T17:50Z] Genotyping with varscan: ('chr13', 97455914, 113141918) 1_2015-11-03_21626T-H3K27ac-sort-chr13_97455914_113141918-prep.bam
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/threading.py", line 763, in run
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/logbook/queues.py", line 265, in _target
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/logbook/base.py", line 239, in pop_thread
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/logbook/base.py", line 204, in pop_thread
  File "logbook/_speedups.pyx", line 233, in logbook._speedups.ContextStackManager.pop_thread (logbook/_speedups.c:5872)
  File "logbook/_speedups.pyx", line 236, in logbook._speedups.ContextStackManager.pop_thread (logbook/_speedups.c:5693)
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the report. Like you, I'm not able to reproduce this with that failing command line and the file you provided. If you re-run bcbio, does it fail in the same place? Practically, varscan in 0.9.4 is fairly disk intensive so it might have had one-off issues reading/writing to disk. If you're failing consistently we'd need to dig a bit more but I hope a re-run will solve it.

The latest development version also contains a re-working of VarScan to make it less disk intensive by doing piping instead of writing mpileup intermediates to disk. If you run into consistent problems you could upgrade to this (`bcbio_nextgen.py upgrade -u development`) to see if that helps. Hope one of the two fixes it for you.

**Comment by apastore** [comment]
Thanks Brad, i have rerun a couple of time but I got the same error... Only with this sample. I have remove varscan from the configuration. At the moment I am really happy with the 0.9.4 so I think I will stay there, but I will test the 0.9.5a for this sample. 
Thanks! 
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Thanks for the additional details. Could you try running in single core mode (`-n 1`) with the failing sample? That might give some additional details for debugging the underlying source of the error, since the command we got above doesn't seem to fail. The errors can get jumbled when running in parallel so the single core output can be informative. Hope this helps
