### ISSUE TITLE
ValueError: Processing failed on GEMINI chunk load

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1100]
With one sample pair out of 25 for tumor/normal I received a core dumped few errors that happen during gemini stuff, which I found a bit surprising. I have only ever received errors like that from java stuff when it needs a lot more memory than I tell it to use. Once again this process should have 30g available, although most of my settings in the bcbio_system.yaml are limited to 25g.

```
[2015-11-05T17:03Z] tabix index Batch1-ensemble-decompose-effects.vcf.gz
[2015-11-05T17:03Z] Create gemini database for /home/bwubb/NGS/BasserWES/bcbio/data/Brca2Ov1-T/work/gemini/Batch1-ensemble-decompose-effects.vcf.gz : Brca2Ov1-T
[2015-11-05T17:03Z] CADD scores are being loaded (to skip use:--skip-cadd).
[2015-11-05T17:03Z] /bin/sh: line 1: 15023 Done                    grabix grab /home/bwubb/NGS/BasserWES/bcbio/data/Brca2Ov1-T/work/gemini/Batch1-ensemble-decompose-effects.vcf.gz 51 75
[2015-11-05T17:03Z]      15024 Segmentation fault      (core dumped) | gemini load_chunk -v - -t snpEff --skip-gerp-bp --passonly --skip-info-string --tempdir /home/bwubb/NGS/BasserWES/bcbio/data/Brca2Ov1-T/work/gemini/tx/tmpFaaaGH -o 51 /home/bwubb/NGS/BasserWES/bcbio/data/Brca2Ov1-T/work/gemini/tx/tmpFaaaGH/Batch1-ensemble-decompose-effects.vcf.chunk2.db
```
It moves on after this, but a few more segmentation faults such as that one occur.

Final error is.
```
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1161, in main
    args.func(parser, args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 192, in load_fn
    gemini_load.load(parser, args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 48, in load
    load_multicore(args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 73, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 249, in load_chunks_multicore
    wait_until_finished(procs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 340, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load
' returned non-zero exit status 1
```
 
In my experience I am sometimes able to resolve segmentation faults with more memory, but I dont think I can even control gemini in that manner. Maybe I am completely wrong on what is going on though.

**Comment by chapmanb** [comment]
Brad;
Sorry about the issues. It's a bit tough to give long distance advice on seg faults, as they're pretty hard to debug even when you have one in hand. You're right that there really isn't a memory control mechanism know to tweak here, although in my experience GEMINI doesn't use a lot of memory for loading. My guess would be some kind of shared filesystem issue since this is IO intensive, but it's tough to guess without a core dump or more details.

Does a re-run segfault in the same place so you can put together something reproducible? Sorry to not have better ideas but hope this helps.
