### ISSUE TITLE
Load loc2keys DB

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1101]
I am really not sure what has happened. These samples worked the other day prior to me upgrading bcbio to get gemini 0.17.2. At first the issue looks like this.

```
...
[2015-11-06T02:06Z] INFO  21:06:38,923 GATKRunReport - Uploaded run statistics report to AWS S3
[2015-11-06T02:06Z] bgzip 1205-CRT-21Aplin-2_202131133_243199373-raw-mutect.vcf
[2015-11-06T02:06Z] tabix index 1205-CRT-21Aplin-2_202131133_243199373-raw-mutect.vcf.gz
[2015-11-06T02:06Z] ** 0 just got out of the pool [PID: 23232 | exit code: 0 | exit signal: 0 | core dump: 0]
[2015-11-06T02:06Z] Merge DBs...
[2015-11-06T02:06Z] Load reference coverage...
[2015-11-06T02:06Z] Load loc2keys DB...
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
joblib.my_exceptions.JoblibAssertionError: JoblibAssertionError
___________________________________________________________________________
Multiprocessing exception:
    ...........................................................................
/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py in <module>()
    221             if setup_info is None:  # no automated run after setup
    222                 sys.exit(0)
    223             workdir, new_kwargs = setup_info
    224             os.chdir(workdir)
    225             kwargs.update(new_kwargs)
--> 226         main(**kwargs)
    227 
    228 
    229 
    230 

...........................................................................
/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py in main(**kwargs={'config_file': 'bcbio_system.yaml', 'fc_dir': None, 'parallel': {'cores': 16, 'module': 'bcbio.distributed', 'queue': None, 'resources': [], 'retries': 0, 'run_local': False, 'scheduler': None, 'tag': '', 'timeout': 15, 'type': 'local'}, 'run_info_yaml': '/home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205-CRT-21Aplin/config/MelanomaTargeted.yaml', 'workdir': '/home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205-CRT-21Aplin/work', 'workflow': None})
     38 from bcbio.graph import graph
     39 from bcbio.provenance import programs
     40 from bcbio.pipeline import version
     41 
     42 def main(**kwargs):
---> 43     run_main(**kwargs)
        kwargs = {'config_file': 'bcbio_system.yaml', 'fc_dir': None, 'parallel': {'cores': 16, 'module': 'bcbio.distributed', 'queue': None, 'resources': [], 'retries': 0, 'run_local': False, 'scheduler': None, 'tag': '', 'timeout': 15, 'type': 'local'}, 'run_info_yaml': '/home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205-CRT-21Aplin/config/MelanomaTargeted.yaml', 'workdir': '/home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205-CRT-21Aplin/work', 'workflow': None}
     44 
     45 def parse_cl_args(in_args):
     46     """Parse input commandline arguments, handling multiple cases.
     47 
...
```
This continues for ~500 more lines. Last lines are
```
AssertionError: Input file /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205-CRT-21Aplin/work/mutect/1/1205-CRT-21Aplin-1_0_22381370-raw-somaticIndels-scalpel-work/variants.3x.indel.vcf not found
___________________________________________________________________________
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
```

Just to check I tried to run one without multiple cores (I only did -n 1 I did not edit the bcbio_system.yaml). It was a much shorted error message, but I dont know if it is any more informative.
```
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 138, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 252, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect.py", line 141, in mutect_caller
    region=region, out_file=out_file_indels)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/scalpel.py", line 114, in _run_scalpel_caller
    scalpel_tmp_file = bgzip_and_index(os.path.join(tmp_path, "variants." + min_cov + "x.indel.vcf"), config)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 441, in bgzip_and_index
    assert os.path.exists(in_file), "Input file %s not found" % in_file
AssertionError: Input file /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205-CRT-20Aplin/work/mutect/1/1205-CRT-20Aplin-1_0_22385208-raw-somaticIndels-scalpel-work/variants.3x.indel.vcf not found
```

Could any of this be related to recent update? I can not think of any other changes I made since 3 days ago. Sorry for dumping all these error messages. Thanks.

-Brad W

**Comment by chapmanb** [comment]
Brad;
Sorry about the problems. This looks like it died in the middle of running scalpel for some reason on the first run, and then left the output scalpel directory in an unhappy state. It would be worth removing the work directory:
```
rm -rf /home/bwubb/NGS/MelanomaTargeted/bcbio/data/1205-CRT-21Aplin/work/mutect/1/1205-CRT-21Aplin-1_0_22381370-raw-somaticIndels-scalpel-work/
```
and then re-running with `-n 1` to see if it fails again or can continue cleanly. If you could send along a `tree` of the failed directory I can also work on trying to detect this half-finished scalpel case and correctly restart in bcbio. Thanks much.

**Comment by bwubb** [comment]
https://gist.github.com/bwubb/095d3476efb830f29d8c#file-tree-gist

I hope this is the type of tree you were looking for. I will update if there are any issues with the rerun. Thank you.

**Comment by bwubb** [comment]
After clearing the entire work dir and running again with `-n 1` the same AssertionError: is raised.

**Comment by chapmanb** [comment]
Brad -- sorry about the continued problems. Is Scalpel still raising an error before this? If it's failing consistently, we could identify and write an empty VCF in the case of a missing indel.vcf output file. Longer term you could pull out the failing command and submit a bug upstream to the Scalpel folks to have a look at. The tree command you sent earlier was from a different directory (`1205-CRT-20Aplin` instead of `1205-CRT-21Aplin`) so looks okay, but if you send from this failing work directory that could help with understanding and working around as well. Thanks again for the help debugging.

**Comment by bwubb** [comment]
Ok time to return back to this issue. I am in the process of re-running some of the above samples. I do have a new error that appears to be scalpel or mutect related also appearing with some 'loc2key DB' text. This is smaller targeted capture data, but I can never get it to run with multiple cores. I think some of my previous issues with that was how I altered the system_config.yaml, setting memory usage too high and not providing enough when I queued the analysis. I since went back and reset to defaults, but then still ran bcbio_nextgen with -n 1. Sill something breaks, but this error looks new to me.

```
[2015-12-02T09:06Z] ***START ANALYSIS***
[2015-12-02T09:06Z] -- Print parameters to /home/bwubb/NGS/FionaOvarianTargeted/bcbio/data/JHOS2/work/mutect/1/JHOS2-1_0_27024059-raw-somaticIndels-scalpel-work/parameters.txt
[2015-12-02T09:06Z] Loading targets from BED file...77 targets (filtered 0 overlapping).
[2015-12-02T09:06Z] Assembly Exons
[2015-12-02T09:06Z] start assembly of 217 regions.
[2015-12-02T09:06Z] stepSize: 217
[2015-12-02T09:06Z] ** 0 started, pid: 6548
[2015-12-02T09:06Z] 1. [0..216]
[2015-12-02T09:06Z] ** 0 just got out of the pool [PID: 6548 | exit code: 0 | exit signal: 0 | core dump: 0]
[2015-12-02T09:06Z] Merge DBs...
[2015-12-02T09:06Z] Load reference coverage...
[2015-12-02T09:06Z] Load loc2keys DB...
[2015-12-02T09:06Z] Computing hom/het state...
[2015-12-02T09:06Z] Num. Homozygous: 4
[2015-12-02T09:06Z] Num. Heterozygous: 99
[2015-12-02T09:06Z] 
[2015-12-02T09:06Z] Dfs limit: 0
[2015-12-02T09:06Z] Partial alignments: 0
[2015-12-02T09:06Z] Cycles: 0
[2015-12-02T09:06Z] OK assemblies: 217
[2015-12-02T09:06Z] Exceptions: 0
[2015-12-02T09:06Z] Repeats: 0
[2015-12-02T09:06Z] 
[2015-12-02T09:06Z] Printing loc2key DB to file...
[2015-12-02T09:06Z] -- Exporting variants to file
[2015-12-02T09:06Z] Loading targets from BED file...77 targets (filtered 0 overlapping).
[2015-12-02T09:06Z] [#SNPs: 0 | #Ins: 0 | #Del: 4 | Tot: 4]
[2015-12-02T09:06Z] Export: elapsed time: 0 day(s) 0 hour(s) 0 minute(s) 0 second(s)
[2015-12-02T09:06Z] FindVariants elapsed time: 0 day(s) 0 hour(s) 0 minute(s) 28 second(s)
[2015-12-02T09:06Z] Discovery: elapsed time: 0 day(s) 0 hour(s) 0 minute(s) 28 second(s)
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 138, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 252, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect.py", line 141, in mutect_caller
    region=region, out_file=out_file_indels)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/scalpel.py", line 114, in _run_scalpel_caller
    scalpel_tmp_file = bgzip_and_index(os.path.join(tmp_path, "variants." + min_cov + "x.indel.vcf"), config)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 441, in bgzip_and_index
    assert os.path.exists(in_file), "Input file %s not found" % in_file
AssertionError: Input file /home/bwubb/NGS/FionaOvarianTargeted/bcbio/data/JHOS2/work/mutect/1/JHOS2-1_0_27024059-raw-somaticIndels-scalpel-work/variants.3x.indel.vcf not found
```
This happens universally across all samples. I do not think I can restart the analysis without completely removing the work dir. But I still need to test that our more. Any advice? Thank you.

-Brad

**Comment by chapmanb** [comment]
Brad -- sorry about the continued problems with this. I dug into it further and realized this was an issue with single sample calling support in scalpel. Apologies, the output file naming changed and we'd only tested with paired samples. I pushed a fix which should resolve this if you update to the latest development:
```
bcbio_nextgen upgrade -u development
```
You should then be able to restart in place and things will work cleanly. Sorry about the difficulty tracking this down and hope this fixes it for you.

**Comment by bwubb** [comment]
Hey that is great! Thank you very much!
