### ISSUE TITLE
GGD recipe: LCR failed

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1104]
My latest code update with hg38 gave this:

```
bcbio_nextgen.py upgrade -u development  --genomes hg38
...
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'rtg'], 'genomes': [{'rnaseq': True, 'name': 'Human (GRCh37)', 'dbsnp': True, 'validation': ['giab-NA12878', 'dream-syn3', 'dream-syn4'], 'annotations': ['battenberg', 'GA4GH_problem_regions', 'MIG'], 'dbkey': 'GRCh37'}, {'validation': ['platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap'], 'name': 'Human (hg38) full', 'dbkey': 'hg38', 'annotations': ['dbsnp', 'clinvar', 'mills_indels', '1000g_snps', '1000g_indels', '1000g_omni_snps', 'hapmap_snps', 'lcr']}], 'install_uniref': False}'): Human (GRCh37), Human (hg38) full
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'rtg'], 'genomes': [{'rnaseq': True, 'name': 'Human (GRCh37)', 'dbsnp': True, 'validation': ['giab-NA12878', 'dream-syn3', 'dream-syn4'], 'annotations': ['battenberg', 'GA4GH_problem_regions', 'MIG'], 'dbkey': 'GRCh37'}, {'validation': ['platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap'], 'name': 'Human (hg38) full', 'dbkey': 'hg38', 'annotations': ['dbsnp', 'clinvar', 'mills_indels', '1000g_snps', '1000g_indels', '1000g_omni_snps', 'hapmap_snps', 'lcr']}], 'install_uniref': False}'): Human (GRCh37), Human (hg38) full
Running GGD recipe: lcr
--2015-11-09 11:18:09--  https://github.com/lh3/varcmp/raw/bb5b616526c5c3ecb46abfd9877e1bd6d50d1802/scripts/LCR-hs38.bed.gz
Resolving github.com... 192.30.252.128
Connecting to github.com|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/lh3/varcmp/bb5b616526c5c3ecb46abfd9877e1bd6d50d1802/scripts/LCR-hs38.bed.gz [following]
--2015-11-09 11:18:10--  https://raw.githubusercontent.com/lh3/varcmp/bb5b616526c5c3ecb46abfd9877e1bd6d50d1802/scripts/LCR-hs38.bed.gz
Resolving raw.githubusercontent.com... 23.235.47.133
Connecting to raw.githubusercontent.com|23.235.47.133|:443... connected.
ERROR: certificate common name “www.github.com” doesn’t match requested host name “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’.
Traceback (most recent call last):
  File "/srv/gsfs0/projects/ashley/apps/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 100, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 259, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 477, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 767, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/srv/gsfs0/projects/ashley/apps/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/srv/gsfs0/projects/ashley/apps/bcbio/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 5
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issue. Older versions of wget complain about GitHubs certificates. I pushed a fix to the recipes to avoid this. If you remove the temporary directory with cloudbiolinux (`rm -rf tmpbcbio-install`) and re-run it should work cleanly now. Thanks much for reporting this.
