### ISSUE TITLE
numpy.dtype has the wrong size

### ISSUE THREAD

**Issue by lukeheo** [chapmanb/bcbio-nextgen#1106]
Dear all

I am a new user.
I installed bcbio on Centos 7 with below code.
I could not make it to work.
Please, have a look the below error message and help.

Thanks for your great work.
Luke Heo

--------------------------<installation code>----------------------------------
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --genomes GRCh37 --sudo --distribution centos
------------------------------------------------------------------------------------

------------------------------<test command>----------------
bcbio_nextgen.py -h"

------------------------------<output>--------------
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 35, in <module>
    from bcbio.distributed import runfn, clargs
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 11, in <module>
    from bcbio.distributed import multitasks
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 3, in <module>
    from bcbio import heterogeneity, structural, utils, chipseq, upload
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/__init__.py", line 10, in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 21, in <module>
    from bcbio.heterogeneity import chromhacks, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/theta.py", line 22, in <module>
    from bcbio.structural import cnvkit, convert
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 10, in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly,
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 23, in <module>
    from bcbio.structural import annotate, shared, regions, plot
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/plot.py", line 14, in <module>
    from bcbio.bam.coverage import plot_multiple_regions_coverage
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/coverage.py", line 12, in <module>
    import seaborn as sns
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/__init__.py", line 4, in <module>
    from .linearmodels import *
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/linearmodels.py", line 28, in <module>
    from .distributions import kdeplot
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/distributions.py", line 13, in <module>
    import statsmodels.nonparametric.api as smnp
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/statsmodels/nonparametric/api.py", line 1, in <module>
    from .kde import KDEUnivariate
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/statsmodels/nonparametric/kde.py", line 26, in <module>
    from .linbin import fast_linbin
  File "__init__.pxd", line 155, in init statsmodels.nonparametric.linbin (statsmodels/nonparametric/linbin.c:3947)
ValueError: numpy.dtype has the wrong size, try recompiling
[root@ewha22 lukeheo]# bcbio_nextgen.py
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 35, in <module>
    from bcbio.distributed import runfn, clargs
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 11, in <module>
    from bcbio.distributed import multitasks
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 3, in <module>
    from bcbio import heterogeneity, structural, utils, chipseq, upload
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/__init__.py", line 10, in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 21, in <module>
    from bcbio.heterogeneity import chromhacks, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/theta.py", line 22, in <module>
    from bcbio.structural import cnvkit, convert
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 10, in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly,
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 23, in <module>
    from bcbio.structural import annotate, shared, regions, plot
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/plot.py", line 14, in <module>
    from bcbio.bam.coverage import plot_multiple_regions_coverage
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/coverage.py", line 12, in <module>
    import seaborn as sns
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/__init__.py", line 4, in <module>
    from .linearmodels import *
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/linearmodels.py", line 28, in <module>
    from .distributions import kdeplot
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/distributions.py", line 13, in <module>
    import statsmodels.nonparametric.api as smnp
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/statsmodels/nonparametric/api.py", line 1, in <module>
    from .kde import KDEUnivariate
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/statsmodels/nonparametric/kde.py", line 26, in <module>
    from .linbin import fast_linbin
  File "__init__.pxd", line 155, in init statsmodels.nonparametric.linbin (statsmodels/nonparametric/linbin.c:3947)
ValueError: numpy.dtype has the wrong size, try recompiling
[root@ewha22 lukeheo]# in init statsmodels.nonparametric.linbin (statsmodels/nonparametric/linbin.c:3947)
bash: syntax error near unexpected token `in'
[root@ewha22 lukeheo]# ValueError: numpy.dtype has the wrong size, try recompiling
bash: ValueError:: command not found
[root@ewha22 lukeheo]# bcbio_nextgen.py -h
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 35, in <module>
    from bcbio.distributed import runfn, clargs
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 11, in <module>
    from bcbio.distributed import multitasks
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 3, in <module>
    from bcbio import heterogeneity, structural, utils, chipseq, upload
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/__init__.py", line 10, in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 21, in <module>
    from bcbio.heterogeneity import chromhacks, theta
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/theta.py", line 22, in <module>
    from bcbio.structural import cnvkit, convert
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 10, in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly,
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 23, in <module>
    from bcbio.structural import annotate, shared, regions, plot
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/plot.py", line 14, in <module>
    from bcbio.bam.coverage import plot_multiple_regions_coverage
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/coverage.py", line 12, in <module>
    import seaborn as sns
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/__init__.py", line 4, in <module>
    from .linearmodels import *
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/linearmodels.py", line 28, in <module>
    from .distributions import kdeplot
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/seaborn/distributions.py", line 13, in <module>
    import statsmodels.nonparametric.api as smnp
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/statsmodels/nonparametric/api.py", line 1, in <module>
    from .kde import KDEUnivariate
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/statsmodels/nonparametric/kde.py", line 26, in <module>
    from .linbin import fast_linbin
  File "__init__.pxd", line 155, in init statsmodels.nonparametric.linbin (statsmodels/nonparametric/linbin.c:3947)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by chapmanb** [comment]
Luke;
Apologies about the issues. This is caused by a rollout of packages for a new version of numpy (1.10) which causes inconsistencies with packages compiled against the old version (1.9). There are more details in #1105 but hopefully you can fix your broken installation with:
```
/usr/local/share/bcbio/anaconda/bin/conda install seaborn
```
Hope this fixes everything for you. Thanks again for the report and please feel free to re-open if you still have any issues at all.
