### ISSUE TITLE
Error in structural variation initial 

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1108]
Hi, I added svcaller: cnvkit in the human tumor-normal somatic mutation calling yaml file and found the following error. In the command, I don't understand why bcbio uses rnaseq ref-transcripts.bed since this is a exome-seq analysis. Could you help me to debug it?
Thanks!

[2015-11-07T08:17Z] *.edu: Timing: structural variation initial
[2015-11-07T08:17Z] *.edu: ipython: detect_sv
[2015-11-07T12:07Z] *.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; sort -V -k1,1 -k2,2n ./project/work/structural/9435tumor/cnvkit/raw/88_2015-11-05_project-merged-sort-call.bed | bedtools closest -d -t all -a - -b <(sort -V -k1,1 -k2,2n ./bcbio/genomes/Hsapiens/GRCh37/rnaseq/ref-transcripts.bed) | awk -F$'\t' -v OFS='\t' '{if ($NF > 10000) $9 = "."} {print}' | cut -f 1-10 | bedtools merge -i - -c 4,5,9 -o distinct,distinct,distinct -delim ',' > ./project/work/structural/9435tumor/cnvkit/raw/tx/tmpShRoaD/88_2015-11-05_project-merged-sort-call-annotated.bed
ERROR: Database file /dev/fd/63 contains chromosome 15, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
' returned non-zero exit status 1
[2015-11-07T12:07Z] *.edu: Unexpected error
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 44, in _setup_logging
    yield config
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 290, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 138, in detect_sv
    for svdata in caller_fn(items):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 29, in run
    return _cnvkit_by_type(items, background)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 41, in _cnvkit_by_type
    return _run_cnvkit_cancer(items, background)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 96, in _run_cnvkit_cancer
    tumor_data = _associate_cnvkit_out(ckouts, [paired.tumor_data])
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 56, in _associate_cnvkit_out
    ckout = _add_variantcalls_to_output(ckout, data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 378, in _add_variantcalls_to_output
    out["vrn_bed"] = annotate.add_genes(calls["bed"], data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/annotate.py", line 42, in add_genes
    do.run(cmd.format(**locals()), "Annotate BED file with gene info")
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; sort -V -k1,1 -k2,2n ./project/work/structural/9435tumor/cnvkit/raw/88_2015-11-05_project-merged-sort-call.bed | bedtools closest -d -t all -a - -b <(sort -V -k1,1 -k2,2n ./bcbio/genomes/Hsapiens/GRCh37/rnaseq/ref-transcripts.bed) | awk -F$'\t' -v OFS='\t' '{if ($NF > 10000) $9 = "."} {print}' | cut -f 1-10 | bedtools merge -i - -c 4,5,9 -o distinct,distinct,distinct -delim ',' > ./project/work/structural/9435tumor/cnvkit/raw/tx/tmpShRoaD/88_2015-11-05_project-merged-sort-call-annotated.bed
ERROR: Database file /dev/fd/63 contains chromosome 15, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the problem. This should be fixed in the latest release (0.9.4) if you can update:

https://github.com/chapmanb/bcbio-nextgen/commit/185401407230ccc8bd747d2effc896e320cce178#diff-1e0a8e19e1ecc0494e74c4ac555652ee

This is a post-calling step where bcbio annotates CNVkit calls with gene names, hence the use of the transcripts file. Hope upgrading helps resolve the issue for you.
