### ISSUE TITLE
install mm9 genome and rtg/mm9.sdf java heap error

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1109]
I would like to add a new genome to one bcbio installation and I never had problem but now if I open an session on the cluster with 

qsub -I -q active -l walltime=20:00:00 -l nodes=1:ppn=1,mem=20G,vmem=200G

and then I run :
bcbio_nextgen.py upgrade -u stable --tools --data --genomes mm9

I get a strange java heap error. If I just run java -version in the same session it run properly (both java 1.7 and 1.8)

do you have any Idea?

even rtg -h give the same error. 
~/nobackup/bcbio/bin/rtg
-bash-4.1$ rtg -h
Error occurred during initialization of VM
Could not reserve enough space for 238039040KB object heap

after requiring mem=60G,vmem=300G
it seams that rtg can be lauchend...

This is my initial error message
[localhost] local: wget --continue --no-check-certificate -O mm9-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/mm9-rtg.tar.xz'
--2015-11-10 11:56:07--  https://s3.amazonaws.com/biodata/genomes/mm9-rtg.tar.xz
Resolving s3.amazonaws.com... 54.231.82.108
Connecting to s3.amazonaws.com|54.231.82.108|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-11-10 11:56:08 ERROR 404: Not Found.

Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O mm9-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/mm9-rtg.tar.xz''

INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome mm9 with index rtg
[localhost] local: rtg format -o rtg/mm9.sdf /cbio/cslab/nobackup/pastore/bcbio/genomes/Mmusculus/mm9/seq/mm9.fa
Error occurred during initialization of VM
Could not reserve enough space for 238039040KB object heap

Fatal error: local() encountered an error (return code 1) while executing 'rtg format -o rtg/mm9.sdf /cbio/cslab/nobackup/pastore/bcbio/genomes/Mmusculus/mm9/seq/mm9.fa'

Aborting.
INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 98, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 257, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/cbio/cslab/home/pastore/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/cbio/cslab/home/pastore/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/cbio/cslab/home/pastore/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/cbio/cslab/home/pastore/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/cbio/cslab/home/pastore/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/cbio/cslab/home/pastore/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 489, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index rtg for mm9 by any method
-bash-4.1$ java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

**Comment by chapmanb** [comment]
Alessandro;
Sorry about the issues. It looks like `rtg` is trying to use too much memory/stack and causing issues on your machine. I added in JVM parameters to rtg to limit memory and stack usage which should hopefully avoid this. If you remove your cached cloudbiolinux from the install (`rm -rf tmpbcbio-install`) and re-run it should hopefully run cleanly now. Thanks much for the report and hope this fixes it for you.

**Comment by apastore** [comment]
Thanks! I have fixed on my installation
