### ISSUE TITLE
qsignature_summary  error

### ISSUE THREAD

**Issue by kuikuisven** [chapmanb/bcbio-nextgen#1113]
Hi, 

I'm running the RNA-seq pipeline on some samples, and the program crashes  when it's generating the final reports.... any clues?

here's the last output i got:

```bash
[2015-11-17T21:33Z] Generating summary files: ['', 'PreMegE_WT3']
[2015-11-17T21:52Z] Generating summary files: ['', 'PreMegE_KO1']
[2015-11-17T22:11Z] Generating summary files: ['', 'PreMegE_KO2']
[2015-11-17T22:30Z] Generating summary files: ['', 'PreMegE_otrhers']
[2015-11-17T22:50Z] copy qsignature
[2015-11-17T22:50Z] summarize fastqc
[2015-11-17T22:50Z] multiprocessing: coverage_report
[2015-11-17T22:50Z] summarize metrics
[2015-11-17T22:50Z] multiprocessing: qsignature_summary
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 328, in run
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 56, in generate_parallel
    summary_file = write_project_summary(samples_coverage, qsign_info)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 177, in write_project_summary
    default_flow_style=False, allow_unicode=False)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/__init__.py", line 218, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/representer.py", line 29, in represent
    self.serialize(node)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 98, in serialize_node
    self.serialize_node(item, node, index)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 109, in serialize_node
    self.emit(MappingEndEvent())
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/emitter.py", line 115, in emit
    self.state()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/emitter.py", line 413, in expect_block_mapping_simple_value
    self.expect_node(mapping=True)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/emitter.py", line 259, in expect_node
    raise EmitterError("expected NodeEvent, but got %s" % self.event)
yaml.emitter.EmitterError: expected NodeEvent, but got MappingEndEvent()
```

**Comment by lpantano** [comment]
Hi,

sorry about that. Is this happening because you turn on qsignature? so you have results inside qc folder and qsignature folder in your working directory?

**Comment by kuikuisven** [comment]
Hi, 
I have not turned on qsignature...

here's a sample from the config file:

```yaml

   304	  genome_build: mm10
   305	  metadata:
   306	    batch: batch1
   307	    genome: mm10
   308	- algorithm:
   309	    adapters:
   310	    - truseq
   311	    - polya
   312	    aligner: star
   313	    coverage_interval: genome
   314	    quality_format: Standard
   315	    strandedness: unstranded
   316	    trim_reads: read_through
   317	  analysis: RNA-seq
   318	  description: PreMegE_KO2
   319	  files:
  ```
ant of my working dir...
```bash

drwxrwxrwx 1 1026 users    0 Nov 18 14:32 align/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 checkpoints_parallel/
drwxrwxrwx 1 1026 users    0 Nov 18 12:30 cufflinks/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 dexseq/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 express/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 htseq-count/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 inputs/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 log/
-rwxrwxrwx 1 1026 users 2.3K Nov 18 12:46 project-summary.yaml*
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 provenance/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 qc/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 report/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 trimmed/
drwxrwxrwx 1 1026 users    0 Nov 18 12:46 tx/```

inside the qc folder, each sample has the following folders:
```bash
drwxrwxrwx 1 1026 users 0 Nov 18 12:46 bamtools/
drwxrwxrwx 1 1026 users 0 Nov 18 12:46 fastqc/
drwxrwxrwx 1 1026 users 0 Nov 18 12:46 qualimap/
drwxrwxrwx 1 1026 users 0 Nov 18 12:46 tx/ ```

hope this helps...

**Comment by lpantano** [comment]
Hi,

thanks so much, still not sure but I will try to reproduce. I didn't see before `coverage_interval` option int RNAseq so I will check if it is this or not.

sorry about this.

**Comment by kuikuisven** [comment]
hey, you’re welcome! no need to be sorry, thanks for looking into this .


On 18 Nov 2015, at 18:11, Lorena Pantano <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

thanks so much, still not sure but I will try to reproduce. I didn't see before coverage_interval option int RNAseq so I will check if it is this or not.

sorry about this.

**Comment by lpantano** [comment]
Can you post here all the files inside report (`ls report/*`). I am trying to see some problems during this step that is the one that modify the information for the samples.

**Comment by kuikuisven** [comment]
```bash
[nrapin@Probe 7] work > ls report/*
report/report-ready.Rmd*

report/coverage:

report/fastqc:
Per_base_N_content.tsv*           Per_base_sequence_quality.tsv*    Per_sequence_quality_scores.tsv*  Sequence_Length_Distribution.tsv*
Per_base_sequence_content.tsv*    Per_sequence_GC_content.tsv*      Per_tile_sequence_quality.tsv*

report/metrics:
metrics.tsv* tx/

report/variants:

**Comment by lpantano** [comment]
mm, confused :) did you try to run again to see if the error repeated in the same line of code?

**Comment by kuikuisven** [comment]
yeps… i did try that and i got the same error (tried in triplicate to be sure ;) )
in the end i modified this function in /bcbio/pipeline/qcsummary.py, so that the analysis could finish...

```python
def generate_parallel(samples, run_parallel):
    """Provide parallel preparation of summary information for alignment and variant calling.
    """
    ####  changed here! #######
    #return samples               ##
    ###############################
    sum_samples = run_parallel("pipeline_summary", samples)
    samples_coverage = report_summary(sum_samples, run_parallel)
    qsign_info = run_parallel("qsignature_summary", [sum_samples])
    summary_file = write_project_summary(samples_coverage, qsign_info)
    samples = []
    for data in sum_samples:
        if "summary" not in data[0]:
            data[0]["summary"] = {}
        data[0]["summary"]["project"] = summary_file
        if qsign_info:
            data[0]["summary"]["mixup_check"] = qsign_info[0]["out_dir"]
        samples.append(data)
    samples = _add_researcher_summary(samples, summary_file)
    return samples
```




On 18 Nov 2015, at 18:26, Lorena Pantano <notifications@github.com<mailto:notifications@github.com>> wrote:


mm, confused :) did you try to run again to see if the error repeated in the same line of code?

**Comment by lpantano** [comment]
oh, that's useful. Can you change only this line:

```
 summary_file = write_project_summary(samples_coverage, qsign_info)
```
to 
```
 summary_file = write_project_summary(sum_samples, qsign_info)
```

want to make sure samples_coverage is not wrong.

let me know what is the output of that when you have time.

**Comment by lpantano** [comment]
as well, you could try to remove `project-summary.yaml` (or move it) and retry again. Hope this help to point to the piece of code making this error.

**Comment by kuikuisven** [comment]
Hi again. 
So i did what you wanted, and got this error...

```bash

[2015-11-19T13:17Z] Generating summary files: ['', 'PreCFUE_KO1']
[2015-11-19T13:34Z] Generating summary files: ['', 'PreCFUE_KO2']
[2015-11-19T13:50Z] Generating summary files: ['', 'PreMegE_KO3']
[2015-11-19T14:07Z] Generating summary files: ['', 'PreMegE_WT1']
[2015-11-19T14:24Z] Generating summary files: ['', 'PreMegE_WT2']
[2015-11-19T14:41Z] Generating summary files: ['', 'PreMegE_WT3']
[2015-11-19T14:57Z] Generating summary files: ['', 'PreMegE_KO1']
[2015-11-19T15:14Z] Generating summary files: ['', 'PreMegE_KO2']
[2015-11-19T15:31Z] Generating summary files: ['', 'PreMegE_otrhers']
[2015-11-19T15:49Z] copy qsignature
[2015-11-19T15:49Z] summarize fastqc
[2015-11-19T15:49Z] multiprocessing: coverage_report
[2015-11-19T15:49Z] summarize metrics
[2015-11-19T15:50Z] multiprocessing: qsignature_summary
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 328, in run
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 59, in generate_parallel
    summary_file = write_project_summary(sum_samples, qsign_info)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 181, in write_project_summary
    default_flow_style=False, allow_unicode=False)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/__init__.py", line 218, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/representer.py", line 29, in represent
    self.serialize(node)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 98, in serialize_node
    self.serialize_node(item, node, index)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/serializer.py", line 109, in serialize_node
    self.emit(MappingEndEvent())
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/emitter.py", line 115, in emit
    self.state()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/emitter.py", line 413, in expect_block_mapping_simple_value
    self.expect_node(mapping=True)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/yaml/emitter.py", line 259, in expect_node
    raise EmitterError("expected NodeEvent, but got %s" % self.event)
yaml.emitter.EmitterError: expected NodeEvent, but got MappingEndEvent()
```

**Comment by lpantano** [comment]
hi, thanks for trying, some more questions:

1-the same error for both things I suggested: removing the current project-summary.yaml file and modifying the code?

2-is the last development bcbio version?

3-do you have other experiments with similar config files that works?

sorry, i am a little lost with this.

**Comment by kuikuisven** [comment]
1 - yes, both give the same
2 - not sure... i ll update to that (what's the exact command already?)
3 - yes, the only thing that changed this time is that i m using star instead of tophat ..

**Comment by lpantano** [comment]
hi,

to update it will be: `bcbio_nextgen.py upgrade -u development --tools`

you can try after that with the code.

If still you have problems, same error. Could you change this change:

`data["summary"] = _run_qc_tools(work_bam, data)` line 74 for `data["summary"] = {'metrics':{}}`

if all this fails, i can try to print to the log some information to look at your data structure.

thanks for all the effort.

**Comment by kuikuisven** [comment]
thanks, i ll let it run again now.

**Comment by kuikuisven** [comment]
Hi again,
I upgraded to the latest dev release, and all worked ... i m sorry for posting a non-issue :-( .
