### ISSUE TITLE
rtg resource not accessible

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1117]
Upon a fresh bcbio installation there is a `rtg` resource that is not available at the given location, resulting in a failed installation. The resource is `https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz` (producing a `NoSuchKey` error on S3).

**Comment by schelhorn** [comment]
Also, running the installer, I get another error with an incorrectly unpacked file, by cloudbiolinux (I can escalate it to there if you wish, Brad):

```shell
[localhost] local: wget --continue --no-check-certificate -O v0.953.tar.gz 'https://github.com/chapmanb/vcftools-cpan/archive/v0.953.tar.gz'
[localhost] local: mv v0.953.tar.gz /home/m223004/tmp/cloudbiolinux
[localhost] local: rm -rf /home/m223004/tmp/cloudbiolinux/b4628b29-3a58-3648-9699-9b0990d90e3d
[localhost] local: tar  -xzpf v0.953.tar.gz
[localhost] local: find * -type d -maxdepth 0
Traceback (most recent call last):
  File "/cluster/software/bcbio_dev/app/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 84, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 377, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 257, in configure_instance
    install_biolinux(options)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 281, in install_biolinux
    _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/fabfile.py", line 118, in _perform_install
    install_brew(flavor=flavor, automated=True)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/fabfile.py", line 311, in install_brew
    brew.install_packages(env, to_install=pkg_install)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 50, in install_packages
    _install_brew_baseline(env, brew_cmd, ipkgs, packages)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 380, in _install_brew_baseline
    cpan.install_packages(env)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/package/cpan.py", line 18, in install_packages
    _install_from_url(env, cpanm_cmd, package)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/package/cpan.py", line 67, in _install_from_url
    dl_dir = cshared._fetch_and_unpack(url)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/custom/shared.py", line 225, in _fetch_and_unpack
    return _safe_dir_name(dir_name, need_dir)
  File "/tmp/tmp.QjfePtNGhU/tmpbcbio-install/cloudbiolinux/cloudbio/custom/shared.py", line 172, in _safe_dir_name
    raise ValueError("Could not find directory %s" % dir_name)
ValueError: Could not find directory v0.953
```
Indeed, the file `https://github.com/chapmanb/vcftools-cpan/archive/v0.953.tar.gz` is somehow redirected to download a file `vcftools-cpan-0.953.tar.gz` instead, which may be at the root of the problem.

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the install problems. Breaking them down:

- We expect the rtg download to fail as we don't provide pre-built rtg indices. The install logic should recover from this and then proceed to create the index locally. Is it not doing that? Could you paste the full traceback where it fails.
- For the Perl install error, the logic that does this is crude. I hope to replace this soon with proper conda packages to avoid these type of issues. The problem is that you have some pre-existing directory in the cloudbiolinux temporary directory so it's not sure what to use. If you `rm -rf /home/USER/tmp/cloudbiolinux` and re-run it should hopefully work cleanly.

Hope this helps get you going.

**Comment by schelhorn** [comment]
Perfect, thanks a lot for the support.
