### ISSUE TITLE
"Input BAM file contains no valid alignments"

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1124]
Hi, 

I'm still having problems running RNA-seq using the bcbio-nextgen pipeline. I'm running bcbio-nextgen 0.9.5a0. Error seems to occur in the express step. I'm not sure what might be wrong, any help is greatly appreciated!

 I get this error:
```
2015-Nov-30 10:21:18 - Attempting to read '/home/zahra/rnaseq/151016_D00458_0118_AC7NCBANXX/calling/work/align/08-253/08-253_star/08-253.transcriptome.nsorted.bam' in BAM format...
2015-Nov-30 10:21:19 - Parsing BAM header...
2015-Nov-30 10:29:15 - SEVERE: Input BAM file contains no valid alignments.
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 317, in run
    samples = rnaseq.quantitate_expression_noparallel(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 58, in quantitate_expression_noparallel
    samples = run_parallel("run_express", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```

The configuration file looks like this: 

```
---
upload:
  dir: ../final
details:
  - files: [/home/zahra/rnaseq/151016_D00458_0118_AC7NCBANXX/Sample_08-253/08-253_S4_L001_R1_001.fastq.gz, /home/zahra/rnaseq/151016_D00458_0118_AC7NCBANXX/Sample_08-253/08-253_S4_L001_R2_001.fastq.gz]
    description: 08-253
    metadata:
      batch: batch1
    analysis: RNA-seq
    genome_build: GRCh37
    algorithm:
      aligner: star
      strandedness: firststrand
      quality_format: Standard
      adapters: [truseq]
      trim_reads: read_through
      expression_caller: express

[ etc ...]
```

**Comment by parlar** [comment]
dexseq seems to work ... so far.

**Comment by roryk** [comment]
Hi Par,

I'd drop express from expression_caller from your configuration, there isn't any reason to use it in my opinion. Sailfish will be run by default and it works great if you need transcript level quantification.

**Comment by chapmanb** [comment]
Rory;
Thanks, this helps me too. I've been moving over homebrew packages to conda and can skip swapping express over and stop installing it. Are there any other tools we could forgo with the swap over to Sailfish?

**Comment by roryk** [comment]
Looks like that is the only one still in the bcbio_nextgen list that is affected.

**Comment by parlar** [comment]
Okay, thanks! I have not done any RNAseq before so I'm not familliar with the tools. Just noted, btw, that the sailfish people released a new tool - "RapMap". Maybe something to take a look at? 

On a different note, qc's seem to be running sequentially. Any plans to make them run in parallel?

**Comment by roryk** [comment]
Hi Par,

The QC steps should be running in parallel-- we'd need some more information about how many cores you're running with and what not to determine why they aren't.

**Comment by parlar** [comment]
Im running:
```
$ bcbio_nextgen.py -t local -n 22 ../config/calling.yaml
```
It only seems to process one sample for qc at a time, as far as I can see. 

Most of the time it hovers on ~130% cpu, sambamba up to 4-500%, but never (from what I've noticed) near the capacity. Maybe by intention, due to disk performance limitations? 

```
[2015-11-30T16:15Z] Resource requests: fastqc, gatk, kraken, qualimap, samtools; memory: 2.00, 3.50, 2.00, 8.00, 2.00; cores: 16, 1, 4, 1, 16
[2015-11-30T16:15Z] Configuring 1 jobs to run, using 16 cores each with 128.1g of memory reserved for each job
[2015-11-30T16:15Z] Timing: quality control
[2015-11-30T16:15Z] multiprocessing: pipeline_summary
[2015-11-30T16:15Z] Generating summary files: ['', '08-253']
```

**Comment by roryk** [comment]
Hi Par,

It is trying to use 16 cores per job and only 22 cores are allocated so it will just run one job at a time with 16 cores. If you swapped in the bcbio_system.yaml file the number of cores for samtools to 8, and bumped -n up to 24 it would run 3 samples at a time with 8 cores each. Some of the programs are threaded and some aren't so the QC steps might use varying amounts of CPU.

**Comment by parlar** [comment]
Great, thanks!

**Comment by roryk** [comment]
Let us know if you spot anything else amiss. Thanks!
