### ISSUE TITLE
Joint HaplotypeCaller JoblibOSError

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1142]
Failed to complete HaplotypeCaller with 287 targeted capture samples. Error occurs after a PrintReads completes.

```
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    _setup_resources()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    tempfile.tempdir = tmpdir
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 160, in run
    out = tz.update_in(out, [nkey], lambda x: nval)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 127, in parallel_prep_region
    "piped_bamprep", _add_combine_info, file_key, ["config"])
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
joblib.my_exceptions.JoblibOSError: JoblibOSError
```

After this, it starts spitting chunks of python code. For brevity's sake I did not include it, but I can certainly provide them if it would aid troubleshooting.

Last line of the error file is:
OSError: [Errno 12] Cannot allocate memory

I checked the out file created with the exit status and job stats. For once I can claim that too little memory was not an issue (as far as I could tell).

Normally, I might try to run in single mode, but given the number of samples and how slow HaplotypeCaller is generally, I would prefer not to have to do that. In fact using 16 cores was far too slow; if I were to redo it I would use many more. Im aplogize if my errors and descriptions are not very informative. Thanks for your continued assistance and enduring patience!

**Comment by schelhorn** [comment]
I guess showing us the last two or three segments of the Python stack trace would help narrowing down the search since right now it is not entirely clear where it failed.

> For once I can claim that too little memory was not an issue (as far as I could tell).

May I ask why that is? Usually the OS is right about such error codes and processing many samples in parallel can generate quite some memory load.

**Comment by bwubb** [comment]
>May I ask why that is? Usually the OS is right about such error codes and processing many samples in parallel can generate quite some memory load.

Yeah I am probably very wrong. I *thought* I could make that claim because when I hit a memory ceiling I am told so by the LSF scheduler, where as this time it just reported Exit code1. The chunks of python in the error message threw me off as well. Upon digging into the job history it seems very likely this was a memory resource issue. I am rerunning with a 3x more RAM. If it works I will owe some apologies for time wasting.
