### ISSUE TITLE
Error running VarScan on yeast samples

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#1154]
Running bcbio-nextgen locally in parallel:
```
bcbio_nextgen.py ../config/CX5461_yeast.yaml -t local -n 50 --retries 3
```

I receive the following errors related to VarScan:
```
[2015-12-10T03:06Z] Genotyping with varscan: ('chrVII', 1084896, 1090940) 47_2015-12-05_CX5461_yeast-sort-chrVII_1084896_1090940-prep.bam
[2015-12-10T03:06Z] mpileup for Varscan
[2015-12-10T03:06Z] [mpileup] 1 samples in 1 input files
[2015-12-10T03:06Z] <mpileup> Set max per-file depth to 8000
[2015-12-10T03:06Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /shahlab/tfunnell/bcbio-nextgen/bin/samtools mpileup -f /shahlab/tfunnell/bcbio-nextgen/genomes/Scerevisiae/sacCer3/seq/sacCer3.fa -d 1000 -L 1000 -r chrVII:1084897-1090940 /shahlab/tfunnell/bcbio_work/CX5461_yeast/work/bamprep/SA779_A51801/chrVII/47_2015-12-05_CX5461_yeast-sort-chrVII_1084896_1090940-prep.bam | grep -v -P '      0               $' > /shahlab/tfunnell/bcbio_work/CX5461_yeast/work/varscan/chrVII/tx/tmp0mtxEk/tx/tmpquAJlC/SA779-chrVII_1084896_1090940-raw.mpileup
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
' returned non-zero exit status 1
[2015-12-10T03:06Z] Genotyping with varscan: ('chrM', 0, 85779) 47_2015-12-05_CX5461_yeast-sort-chrM_0_85779-prep.bam
[2015-12-10T03:06Z] mpileup for Varscan
Traceback (most recent call last):
  File "/shahlab/tfunnell/bcbio-nextgen/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/shahlab/tfunnell/bcbio-nextgen/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 164, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
```
Re-running the pipeline in serial mode results in the CalledProcessError above.

**Comment by chapmanb** [comment]
Tyler;
Sorry about the issues. It looks like samtools mpileup is failing for some reason on this region. If you run the failing command out of bcbio:
```
/shahlab/tfunnell/bcbio-nextgen/bin/samtools mpileup -f /shahlab/tfunnell/bcbio-nextgen/genomes/Scerevisiae/sacCer3/seq/sacCer3.fa -d 1000 -L 1000 -r chrVII:1084897-1090940 /shahlab/tfunnell/bcbio_work/CX5461_yeast/work/bamprep/SA779_A51801/chrVII/47_2015-12-05_CX5461_yeast-sort-chrVII_1084896_1090940-prep.bam > test.mpileup
```
does it give any useful error message?

Practically, a couple of thoughts:

- What motivated your choice of VarScan for this analysis? My suggestion would be to try a caller like FreeBayes on it, which should be more robust and give better results. I don't have direct experience with Yeast but VarScan is mostly optimized for somatic calling.
- The latest bcbio release (coming tomorrow) has a re-written VarScan approach that avoids writing to files. I'm not sure if this eliminates any bugs here but testing against the latest development version or new release tomorrow might help.

Hope this helps.

**Comment by funnell** [comment]
Thanks the help. The only output from that command is
```
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
```
and test.mpileup is empty.

I didn't have any particular motivation for running VarScan, so I can just not run it. I haven't tested on the new release yet.
