### ISSUE TITLE
upgrade fails (again)

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1156]
Running ``` bcbio_nextgen.py upgrade -u stable --tools --data --sudo ``` fails with the following error:

```
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/pip', 'install', '-r', 'https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt']' returned non-zero exit status 2
```
However, manually running ``` /usr/local/share/bcbio/anaconda/bin/pip install -r https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt ``` works. Probably same issue as https://github.com/chapmanb/bcbio-nextgen/issues/1143

Could it be that bcbio-nextgen/pip does not use certificates correctly? I'm behind a corporate firewall that filters traffic so I need to use certificates issued by my organization (university hospital of Umeå). These are installed on the system (centos 7.1). I guess I would need to make a global setting for pip used by bcbio-nextgen to use the system certificates but I'm not sure how. 

Complete traceback:

```
Exception:
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 291, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/req/req_file.py", line 77, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/download.py", line 404, in get_file_content
    resp = session.get(url)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 60, in upgrade_bcbio
    subprocess.check_call(sudo_cmd + [pip_bin, "install", "-r", REMOTES["requirements"]])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/pip', 'install', '-r', 'https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt']' returned non-zero exit status 2

**Comment by chapmanb** [comment]
Pär;
Sorry about the issue. bcbio sets a local SSL certificate before using pip to work around issues where the global certificate is broken. In this case, we're using the wrong certificate for your setup, causing issues.

I generalized the logic to first try an install with the global SSL, then fall back to using the local conda SSL certificate if this fails. You might need to do two upgrades to `-u development`, the first to get the fixed approach and the second to get the dependencies.

Hope this will make the install a bit cleaner for you. The plan is to move fully to conda package based installs before the next release so hopefully this is only a temporary workaround for a cleaner long term process. Thanks again for the patience debugging this.

**Comment by parlar** [comment]
Extremely quick update, much appreciated!
