### ISSUE TITLE
Manta: failed to open -: unknown file type

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#1159]
Running bcbio on some yeast samples like so:
```
bcbio_nextgen.py ../config/CX5461_yeast2.yaml -t local -n 50 --retries 3
```

Received several errors that look like this:
```
[2015-12-15T22:45Z] Failed to open -: unknown file type
[2015-12-15T22:45Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/shahlab/tfunnell/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /shahlab/tfunnell/bcbio_work/CX5461_yeast/work/structural/SA763_A51785/manta/results/variants/diploidSV.vcf.gz | sed 's/     SAMPLE/      SA763_A51785/' | bcftools view -s SA763_A51785 | bgzip -c > /shahlab/tfunnell/bcbio_work/CX5461_yeast/work/structural/SA763_A51785/manta/tx/tmprEweEG/diploidSV-SA763_A51785.vcf.gz
```

**Comment by chapmanb** [comment]
Tyler;
Sorry about the issues. I'm not sure how well Manta works on yeast data. It would be worth looking at the output file:
```
/shahlab/tfunnell/bcbio_work/CX5461_yeast/work/structural/SA763_A51785/manta/results/variants/diploidSV.vcf.gz
```
to see if it looks correct. The error appears to be bcftools being unable to recognize it as a valid VCF so maybe there are issues with the output there that you can identify. Hope this helps with debugging.

**Comment by lpantano** [comment]
Hi @funnell 

did you get this solved?

thanks!

**Comment by funnell** [comment]
Sorry, no. I think I gave up on running Manta.
