### ISSUE TITLE
manta error

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1167]
SV analysis run exits with the following error message.

```
[2015-12-18T08:18Z] Configure manta SV analysis
[2015-12-18T08:18Z] 
[2015-12-18T08:18Z] Successfully created workflow run script.
[2015-12-18T08:18Z] Run manta SV analysis
[2015-12-18T08:18Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command '/usr/local/share/bcbio/anaconda/bin/python /home/data_in/calling/haloplex/141231_stellans_research/calling/work/structural/R10-4006/manta/runWorkflow.py -m local -j 16 --quiet
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 253, in run
    samples = structural.run(samples, run_parallel, "standard")
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 122, in run
    for xs in to_process.values()))
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 158, in detect_sv
    return structural.detect_sv(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 141, in detect_sv
    for svdata in caller_fn(items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/manta.py", line 21, in run
    variant_file = _run_workflow(items, paired, workflow_file, work_dir)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/manta.py", line 49, in _run_workflow
    do.run(cmd, "Run manta SV analysis")
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/usr/local/share/bcbio/anaconda/bin/python /home/data_in/calling/haloplex/141231_stellans_research/calling/work/structural/R10-4006/manta/runWorkflow.py -m local -j 16 --quiet
' returned non-zero exit status 1
```

**Comment by parlar** [comment]
cont from https://github.com/chapmanb/bcbio-nextgen/issues/1165 : I have about 20 variants in ```R10-4006-sort-batch1-svs-prep-R13-1212-std.vcf.gz ``` and alignments were produced using bcbio.

Something that I should mention is, though, perhaps that runs are done using a haloplex panel comprising ~ 85 genes / 80 samples. So no full exome or whole genome, if this might influence what's going on? I'm doing this run as a test. What we're interested in is the possibility to detect CNV, I guess this means I could stick to cnvkit only and skip the other tools.

**Comment by schelhorn** [comment]
`manta` has its own logs in the working directory, perhaps you could have a look. I would expect, however, that SV calling on a panel of 85 genes just won't work. Calling CNVs alone on a deeply sequenced panel is difficult due to coverage variation and the lack of background CNV information. Real SV calling requiring reads spanning the breakpoint would be rather hopeless, in my opinion.

**Comment by chapmanb** [comment]
Pär;
Sorry about the issues.  If you'd like to debug more we'd need to run manta by hand without the quiet option:
```
/usr/local/share/bcbio/anaconda/bin/python /home/data_in/calling/haloplex/141231_stellans_research/calling/work/structural/R10-4006/manta/runWorkflow.py -m local -j 16
```
which should give more information about why it's failing. We could try to adjust and fix from that.

Practically, I agree with Sven-Eric. I don't think you're going to find anything useful with haloplex here -- it's a small panel and amplification will throw things off as well. We have found some interesting things with exome pulldowns so things don't fail in general, but it's definitely outside the average use case.

If these are very high depth, that would explain the slower genotyping you saw in #1165 since runtime depends on depth.

Hope this helps.

**Comment by ctsa** [comment]
Note without rerunning you can check error messages here:

    /home/data_in/calling/haloplex/141231_stellans_research/calling/work/structural/R10-4006/manta/workflow.error.log.txt

...or check:

    /home/data_in/calling/haloplex/141231_stellans_research/calling/work/structural/R10-4006/manta/workspace/pyflow.data/logs/pyflow.log.txt

...for the full log. The `--quiet` option just turns off the log duplication to tty (stderr), full logging is still being written to these files.

**Comment by chapmanb** [comment]
Chris -- Awesome, thanks for the debugging tip. That helps a ton. I'll definitely suggest that to folks in the future as well if we run into anything.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues.

cheers
