### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by MBeyens** [chapmanb/bcbio-nextgen#1168]
Dear

Can someone help me with the installation og bcbio. The installation keeps on failing on my cluster. 

I had some 'standard' errors, to solve them I did the following:
unset JAVA_HOME
export JAVA_HOME=/opt/software/sun-jre-7/
export PATH="$JAVA_HOME/bin:$PATH"
java -version  --> 1.7
unset PYTHONHOME
unset PYTHONPATH
export PYTHONNOUSERSITE=1

During the installation I get following errors:

  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/workflow/stormseq.py", line 12, in <module>
    from bcbio.upload import s3
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 9, in <module>
    from bcbio.upload import shared, filesystem, galaxy, s3
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/galaxy.py", line 14, in <module>
    from bcbio.pipeline import qcsummary
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 11, in <module>
    import pandas as pd
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 44, in <module>
    from pandas.core.api import *
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.groupby import Grouper
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 17, in <module>
    from pandas.core.frame import DataFrame
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 41, in <module>
    from pandas.core.series import Series
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/series.py", line 2909, in <module>
    import pandas.tools.plotting as _gfx
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/tools/plotting.py", line 28, in <module>
    import pandas.tseries.converter as conv
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/home/mbeyens/local/share/bcbio/anaconda/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 268, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/opt/software/python2.7.5/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/mbeyens/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=~/local', '--genomes', 'hg19', '--distribution', 'ubuntu']' returned non-zero exit status 1

With kind regards

**Comment by chapmanb** [comment]
Sorry about the install issue. It looks like you may have some of your localization variables set to UTF-8, which is not a valid encoding. You can fix with:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
There are more details here: http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8

Hope this gets things running smoothly. Please feel free to re-open if you're still stuck at any point.
