### ISSUE TITLE
Installation Error: MD5 Sums Mismatch

### ISSUE THREAD

**Issue by rb5000** [chapmanb/bcbio-nextgen#1180]
Hello,

I am trying to install Bc-Bio on a linux cluster, but keep running into this issue:

````
The following packages will be UPDATED:

singledispatch:                    3.4.0.3-py27_0 --> 3.4.0.3-py27_1         
Fetching packages ...
age-metasv-201 100% |##################################################################################| Time: 0:00:01 381.41 kB/s
atlas-3.8.4-0. 100% |##################################################################################| Time: 0:00:03 844.98 kB/s
bamtools-2.4.0 100% |##################################################################################| Time: 0:00:04 174.10 kB/s
bedtools-2.24. 100% |##################################################################################| Time: 0:00:03 206.67 kB/s
biobambam-2.0. 100% |##################################################################################| Time: 0:00:04   3.16 MB/s
bwa-0.7.12-1.t 100% |##################################################################################| Time: 0:00:01 415.33 kB/s
bwakit-0.7.12- 100% |##################################################################################| Time: 0:00:10   4.62 MB/s
cancerit-allel 100% |##################################################################################| Time: 0:00:03 182.80 kB/s
delly-0.7.2-1. 100% |##################################################################################| Time: 0:00:02 906.42 kB/s
freebayes-0.9. 100% |##################################################################################| Time: 0:00:03   1.61 MB/s
glpk-4.56-0.ta 100% |##################################################################################| Time: 0:00:03 970.22 kB/s
grabix-0.1.6-0 100% |##################################################################################| Time: 0:00:00  48.77 kB/s
gsl-1.16-1.tar 100% |##################################################################################| Time: 0:00:06 305.95 kB/s
gsl-1.16-1.tar 100% |##################################################################################| Time: 0:00:02 844.44 kB/s
gsl-1.16-1.tar 100% |##################################################################################| Time: 0:00:01   1.11 MB/s
gsl-1.16-1.tar 100% |##################################################################################| Time: 0:00:01   1.29 MB/s
Error: MD5 sums mismatch for download: https://conda.anaconda.org/bcbio/linux-64/gsl-1.16-1.tar.bz2 (f7645d2afe6c3ec007f65205f34ebfda != a96d8b07cea406b399cd13ca984c4942)

Fatal error: local() encountered an error (return code 1) while executing '/home/user/bcbio/anaconda/bin/conda install -y -c bcbio -c bioconda -c r age-metasv bamtools bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.24.0 bio-vcf biobambam bowtie2 bwa bwakit cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt delly fastqc freebayes=0.9.21.26 gatk-framework gemini glpk grabix hall-lab-svtools hisat2 hmmlearn htseq htslib kraken lofreq lumpy-sv macs2 manta metasv mirdeep2 moreutils novoalign oncofuse optitype parallel pbgzip phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap razers3 rtg-tools sailfish sambamba samblaster samtools scalpel seqbuster seqtk sickle-trim simple_sv_annotation snpeff spades star stringtie subread svtyper tdrmapper theta2 tophat ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig vardict vardict-java variant-effect-predictor varscan vawk vcflib viennarna vt wham awscli p7zip s3gof3r perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi'

Aborting.
Traceback (most recent call last):
  File "/home/user/downloads/bcbio_nextgen_install.py", line 241, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "/home/user/downloads/bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/opt/hpc/lib64/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/user/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/user/bcbio', '--isolate', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
````
I have tried deleting the tmp files and the bcbio folder and starting over, but get the same error. Any suggestions?

Thanks,

Robert

**Comment by chapmanb** [comment]
Robert;
Sorry about the issues. We've also seen similar issues in #1179 with other packages. It seems like anaconda.org is having some hiccups right now. I can cleanly install gsl and other packages here now so am confused as to what is going on.

My best guess is that this is a temporary issue that might be resolved if you wait a bit and re-run. You could also clear out the package cache of problem packages (`rm -f /home/user/bcbio/anaconda/pkgs/gsl*.tar.bz2`) before restarting but don't need to re-download everything from scratch. Sorry to not have a better idea but hopefully a restart will help.

**Comment by rb5000** [comment]
Thank you for your quick reply, will retry later.

Thanks,

Robert

**Comment by chapmanb** [comment]
Robert -- this is fixed upstream now and should be working cleanly if you retry. Thanks again for reporting the problem and hope the install works cleanly for you.
