### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1182]
Hi Brad,
I am running a WES project and I am always getting this error. After rerun it seems solved but later it appear on a different sample or region.

Do you have any suggestion?
Thanks!

[2016-01-12T23:12Z] tabix index F16-chr1_160582277_176526377-raw.vcf.gz
[2016-01-12T23:12Z] Annotate with dbSNP
[2016-01-12T23:12Z] WARN  18:12:06,382 HaplotypeScore - Annotation will not be calculated, must be called from UnifiedGenotyper, not org.broadinstitute.gatk.tools.walkers.annotator.VariantAnnotator
[2016-01-12T23:12Z] tabix index F16-chr1_240255409_249250621-raw.vcf.gz
[2016-01-12T23:12Z] Annotate with dbSNP
[2016-01-12T23:12Z] INFO  18:12:26,222 VariantAnnotator - Processed 747 loci.
[2016-01-12T23:12Z] 
[2016-01-12T23:12Z] INFO  18:12:26,334 ProgressMeter -            done      5033.0    21.0 s      70.7 m       99.9%    21.0 s       0.0 s
[2016-01-12T23:12Z] INFO  18:12:26,334 ProgressMeter - Total runtime 21.34 secs, 0.36 min, 0.01 hours
[2016-01-12T23:12Z] INFO  18:12:26,335 MicroScheduler - 9075 reads were filtered out during the traversal out of approximately 124306 total reads (7.30%)
[2016-01-12T23:12Z] INFO  18:12:26,335 MicroScheduler -   -> 0 reads (0.00% of total) failing BadCigarFilter
[2016-01-12T23:12Z] INFO  18:12:26,336 MicroScheduler -   -> 9065 reads (7.29% of total) failing DuplicateReadFilter
[2016-01-12T23:12Z] INFO  18:12:26,336 MicroScheduler -   -> 0 reads (0.00% of total) failing FailsVendorQualityCheckFilter
[2016-01-12T23:12Z] INFO  18:12:26,337 MicroScheduler -   -> 0 reads (0.00% of total) failing MalformedReadFilter
[2016-01-12T23:12Z] INFO  18:12:26,337 MicroScheduler -   -> 0 reads (0.00% of total) failing NotPrimaryAlignmentFilter
[2016-01-12T23:12Z] INFO  18:12:26,337 MicroScheduler -   -> 10 reads (0.01% of total) failing UnmappedReadFilter
[2016-01-12T23:12Z] INFO  18:12:27,329 GATKRunReport - Uploaded run statistics report to AWS S3
[2016-01-12T23:12Z] Genotyping with VarDict: Inference
[2016-01-12T23:12Z] tabix index F16-chr1_192316442_208041368-raw.vcf.gz
[2016-01-12T23:12Z] Annotate with dbSNP
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by chapmanb** [comment]
Alessandro;
Sorry about the issues. Unfortunately the `__init__() takes at least 3 arguments` error is a generic "something went wrong" error from the joblib parallelization engine and doesn't diagnose the underlying issue. The actual error would be somewhere earlier in your logs -- you might see it in `log/bcbio-nextgen.log`. My guess from your description of the issue is that you're running into memory or intermittent filesystem issues. It's possible your simultaneous runs use too many resources at some point. If you can dig up errors you might be able to isolate further, but trimming memory usage from some of the tools might help in the absence of this. Sorry to not have a more definite idea but hope this helps.

**Comment by apastore** [comment]
You are right, it's probably something with the filesystem.

[2016-01-13T00:20Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export VAR_DICT_OPTS='-Xms750m -Xmx3000m -XX:+UseSerialGC -Djava.io.tmpdir=/scratch/6811813.mskcc-fe1.local/bcbiotx/e68ae2db-5ea0-4820-b22e-08a49516f87c/tmpJiLm_X' && vardict-java -G /cbio/cslab/nobackup/pastore/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -f 0.1 -N s_F16 -b "/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/bamprep/s_F16/chr13/34_2015-12-04_PDX_PCNSL-sort.nsorted.disambiguatedSpeciesA.sorted-chr13_102106233_115169878-prep.bam|/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/bamprep/s_F16-Blood/chr13/33_2015-12-04_PDX_PCNSL-sort.nsorted.disambiguatedSpeciesA.sorted-chr13_102106233_115169878-prep.bam" -c 1 -S 2 -E 3 -g 4 /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/vardict/chr13/F16-chr13_102106233_115169878-raw-regions-regionlimit.bed | testsomatic.R | var2vcf_paired.pl -M -P 0.9 -m 4.25 -f 0.1  -N "s_F16|s_F16-Blood" | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null |  /cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "bwa")' | sed 's/\\.*Somatic\\/Somatic/' | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/' | /cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/vcfstreamsort | bgzip -c > /scratch/6811813.mskcc-fe1.local/bcbiotx/e68ae2db-5ea0-4820-b22e-08a49516f87c/tmpJiLm_X/F16-chr13_102106233_115169878-raw.vcf.gz
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
/bin/bash: line 1: 28506 Done                    vardict-java -G /cbio/cslab/nobackup/pastore/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -f 0.1 -N s_F16 -b "/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/bamprep/s_F16/chr13/34_2015-12-04_PDX_PCNSL-sort.nsorted.disambiguatedSpeciesA.sorted-chr13_102106233_115169878-prep.bam|/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/bamprep/s_F16-Blood/chr13/33_2015-12-04_PDX_PCNSL-sort.nsorted.disambiguatedSpeciesA.sorted-chr13_102106233_115169878-prep.bam" -c 1 -S 2 -E 3 -g 4 /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/vardict/chr13/F16-chr13_102106233_115169878-raw-regions-regionlimit.bed
     28507                       | testsomatic.R
     28508                       | var2vcf_paired.pl -M -P 0.9 -m 4.25 -f 0.1 -N "s_F16|s_F16-Blood"
     28509                       | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null
     28510 Segmentation fault      | /cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "bwa")'
     28511                       | sed 's/\\.*Somatic\\/Somatic/'
     28512                       | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/'
     28513                       | /cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)'
     28514                       | awk -F'	' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}'
     28515                       | awk -F'	' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}'
     28516 Aborted                 | /cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/vcfstreamsort
     28517                       | bgzip -c > /scratch/6811813.mskcc-fe1.local/bcbiotx/e68ae2db-5ea0-4820-b22e-08a49516f87c/tmpJiLm_X/F16-chr13_102106233_115169878-raw.vcf.gz
' returned non-zero exit status 134
