### ISSUE TITLE
upgrade gatk error

### ISSUE THREAD

**Issue by zengfengbo** [chapmanb/bcbio-nextgen#1187]
# CMD
```sh
bcbio_nextgen.py upgrade --tools --toolplus gatk=/mnt/ilustre/users/fengbo.zeng/gatk3.5/GenomeAnalysisTK.jar --tooldir=~/local
```
# ERROR
OSError: [Errno 13] Permission denied

# DETAILS
DBG [config.py]: Using config file /mnt/ilustre/users/fengbo.zeng/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/r-libs.yaml
Creating manifest of installed packages in /mnt/ilustre/users/fengbo.zeng/local/share/bcbio/manifest
Third party tools upgrade complete.
Installing additional tools
Traceback (most recent call last):
  File "/mnt/ilustre/users/fengbo.zeng/local/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/ilustre/users/fengbo.zeng/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 77, in upgrade_bcbio
    _install_toolplus(args)
  File "/mnt/ilustre/users/fengbo.zeng/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 397, in _install_toolplus
    _install_gatk_jar(tool.name, tool.fname, toolplus_manifest, system_config, toolplus_dir)
  File "/mnt/ilustre/users/fengbo.zeng/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 418, in _install_gatk_jar
    version = get_gatk_jar_version(name, fname)
  File "/mnt/ilustre/users/fengbo.zeng/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 407, in get_gatk_jar_version
    return broad.get_gatk_version(fname)
  File "/mnt/ilustre/users/fengbo.zeng/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 87, in get_gatk_version
    with closing(subprocess.Popen(cl, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).stdout) as stdout:
  File "/mnt/ilustre/users/fengbo.zeng/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/mnt/ilustre/users/fengbo.zeng/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by zengfengbo** [comment]
# solved
NO java installed.
