### ISSUE TITLE
picard command not found after install with --isolate flag

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1188]
I'm testing the recently installed bcbio pipeline, and when I set the `bam_clean: picard` option in the config yaml file, I get the following error:

<pre><code>
[2016-01-15T12:19Z] node8: Picard: ReorderSam
[2016-01-15T12:19Z] node8: Uncaught exception occurred
Traceback (most recent call last):
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2016-01-15T12:19Z] node8: Unexpected error
Traceback (most recent call last):
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 45, in _setup_logging
    yield config
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 128, in process_alignment
    return ipython.zip_args(apply(sample.process_alignment, *args))
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 115, in process_alignment
    data)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/cleanbam.py", line 28, in picard_prep
    reorder_bam = runner.run_fn("picard_reorder", in_bam, ref_file, reorder_bam)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 450, in run_fn
    return fn(self, *args, **kwds)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/picardrun.py", line 109, in picard_reorder
    picard.run("ReorderSam", opts)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 434, in run
    do.run(cmd, "Picard: %s" % subcmd)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2016-01-15T12:19Z] node8: Picard: ReorderSam
[2016-01-15T12:19Z] node8: Uncaught exception occurred
Traceback (most recent call last):
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2016-01-15T12:19Z] node8: Unexpected error
Traceback (most recent call last):
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 45, in _setup_logging
    yield config
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 128, in process_alignment
    return ipython.zip_args(apply(sample.process_alignment, *args))
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 115, in process_alignment
    data)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/cleanbam.py", line 28, in picard_prep
    reorder_bam = runner.run_fn("picard_reorder", in_bam, ref_file, reorder_bam)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 450, in run_fn
    return fn(self, *args, **kwds)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/picardrun.py", line 109, in picard_reorder
    picard.run("ReorderSam", opts)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 434, in run
    do.run(cmd, "Picard: %s" % subcmd)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
</code></pre>

It seems that the picard script is not found, after installing bcbio with the `--isolate` option. For other commands the `/data/t-tcga/esebesty/bcbio/data/anaconda/bin/` path is added correctly, but not for picard:

<pre><code>
[2016-01-15T12:19Z] node8: picard -Xms750m -Xmx3500m -XX:+UseSerialGC ReorderSam INPUT=/data/t-tcga/esebesty/bcbio_run/single-pair-noalign-test/input/G47088.TCGA-34-5240-01A-01D-1441-08.1.bam
 OUTPUT=/data/t-tcga/esebesty/bcbio_run/single-pair-noalign-test/work/bamclean/lusc-small-tumor/tx/tmp7BxhQy/G47088.TCGA-34-5240-01A-01D-1441-08.1-reorder.bam REFERENCE=/data/t-tcga/esebesty/
bcbio/data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa ALLOW_INCOMPLETE_DICT_CONCORDANCE=true TMP_DIR=/data/t-tcga/esebesty/bcbio_run/single-pair-noalign-test/work/tx/tmpY_Bfwo VALIDATION_STRINGENC
Y=SILENT
</code></pre>

**Comment by chapmanb** [comment]
Endre;
Sorry about the problems. Did you add $TOOLDIR/bin to your PATH, where TOOLDIR is the directory specified by `--tooldir` during the install? bcbio assumes that to be in your PATH when running. The `--isolate` option doesn't add it to your .bashrc assuming you'll inject the correct PATH to bcbio before running your analysis (and allows folks to do things like have multiple parallel versions of bcbio installed).

Hope this helps resolve the issue.

**Comment by razZ0r** [comment]
That should be the problem. I had the impression that all commands will be called with an absolute path, so I don't need to add  $TOOLDIR/bin to my PATH. 

sambamba was called during a test like `/data/t-tcga/esebesty/bcbio/data/anaconda/bin/sambamba`, bammarkduplicates with `/data/t-tcga/esebesty/bcbio/data/anaconda/bin/bammarkduplicates`, so I was expecting that picard will be called like `/data/t-tcga/esebesty/bcbio/tool/bin/picard`

**Comment by chapmanb** [comment]
Sorry for the confusion. Let us know if you we can update the docs in any way to make this more clear. We do reaching into the anaconda directory in some cases, but the all-conda installation we use now is new within the last month so haven't come to a decision about using this globally and avoiding needing to adjust PATHs at all. Hope updating gets things going cleanly for you.
