### ISSUE TITLE
key REJECT found in VariantContext field FILTER

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1191]
Hi Brad,
I am getting this error, I have tried to delete the vcf and rerun but i still get a vcf with REJECT filter for the chrY subsegment. Do you have any Ideas?

Thanks!

[2016-01-18T18:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-01-18T18:14Z] Concat variant files
[2016-01-18T18:14Z] INFO  13:14:08,449 HelpFormatter - -------------------------------------------------------
[2016-01-18T18:14Z] INFO  13:14:08,452 HelpFormatter - Program Name: org.broadinstitute.gatk.tools.CatVariants
[2016-01-18T18:14Z] INFO  13:14:08,456 HelpFormatter - Program Args: -R /cbio/cslab/nobackup/pastore/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -V /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/freebayes/F12-6-p12-files.list -out /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/freebayes/tx/tmpRJX_z0/F12-6-p12.vcf.gz -assumeSorted
[2016-01-18T18:14Z] INFO  13:14:08,469 HelpFormatter - Executing as pastore@cc03.local on Linux 2.6.32-504.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15.
[2016-01-18T18:14Z] INFO  13:14:08,469 HelpFormatter - Date/Time: 2016/01/18 13:14:08
[2016-01-18T18:14Z] INFO  13:14:08,470 HelpFormatter - -------------------------------------------------------
[2016-01-18T18:14Z] INFO  13:14:08,470 HelpFormatter - -------------------------------------------------------
[2016-01-18T18:14Z] .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100.........110.........120.........130.........140.........150.........160.........170.........180.........190.........200##### ERROR ------------------------------------------------------------------------------------------
[2016-01-18T18:14Z] ##### ERROR stack trace
[2016-01-18T18:14Z] java.lang.IllegalStateException: Key REJECT found in VariantContext field FILTER at chrY:21877584 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.
[2016-01-18T18:14Z] 	at htsjdk.variant.vcf.VCFEncoder.fieldIsMissingFromHeaderError(VCFEncoder.java:176)
[2016-01-18T18:14Z] 	at htsjdk.variant.vcf.VCFEncoder.getFilterString(VCFEncoder.java:158)
[2016-01-18T18:14Z] 	at htsjdk.variant.vcf.VCFEncoder.encode(VCFEncoder.java:110)
[2016-01-18T18:14Z] 	at htsjdk.variant.variantcontext.writer.VCFWriter.add(VCFWriter.java:222)
[2016-01-18T18:14Z] 	at org.broadinstitute.gatk.tools.CatVariants.execute(CatVariants.java:295)
[2016-01-18T18:14Z] 	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:248)
[2016-01-18T18:14Z] 	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:155)
[2016-01-18T18:14Z] 	at org.broadinstitute.gatk.tools.CatVariants.main(CatVariants.java:311)
[2016-01-18T18:14Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-01-18T18:14Z] ##### ERROR A GATK RUNTIME ERROR has occurred (version 3.4-65-g2434e49):
[2016-01-18T18:14Z] ##### ERROR
[2016-01-18T18:14Z] ##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
[2016-01-18T18:14Z] ##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
[2016-01-18T18:14Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2016-01-18T18:14Z] ##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
[2016-01-18T18:14Z] ##### ERROR
[2016-01-18T18:14Z] ##### ERROR MESSAGE: Key REJECT found in VariantContext field FILTER at chrY:21877584 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.
[2016-01-18T18:14Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-01-18T18:14Z] bcftools concat variants
[2016-01-18T18:14Z] Different number of samples in /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/freebayes/chrY/F12-6-p12-chrY_16734313_59373566.vcf.gz. Perhaps "bcftools merge" is what you are looking for?
[2016-01-18T18:14Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcftools concat --allow-overlaps -O z --file-list /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/freebayes/F12-6-p12-files.list -o /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/freebayes/tx/tmpBIoTg3/F12-6-p12.vcf.gz
Different number of samples in /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/PCNSL/PDX_PCNSL/work/freebayes/chrY/F12-6-p12-chrY_16734313_59373566.vcf.gz. Perhaps "bcftools merge" is what you are looking for?
' returned non-zero exit status 255
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
    parallel_fn(combine_name, combine_args)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 664, in __call__
    self.retrieve()
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 547, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by apastore** [comment]
I realized the sample configuration file was malformed
