### ISSUE TITLE
WES alignment with limited memory

### ISSUE THREAD

**Issue by rjsicko** [chapmanb/bcbio-nextgen#1192]
Hi,
I'm trying to use bcbio in a virtual machine where the windows host only has 8g of memory. The project is a 16 sample WES experiment. I've allocated 6g to the guest OS (biolinux 8). I left bcbio running for a few days and it was still aligning the first sample when I came back. I've used bwa-mem on this setup for a targeted sequencing project and ran into a similar problem if less than 5.5g was allocated to the guest. Any idea if this is a config issue or I simply need more memory for this task?

***bcbio-nextgen,0.9.5***

From ***bcbio-nextgen-debug.log***
```
[2016-01-15T14:16Z] Resource requests: bwa, sambamba, samtools; memory: 6.00, 1.00; cores: 8, 8, 6
[2016-01-15T14:16Z] Configuring 1 jobs to run, using 1 cores each with 6.00g of memory reserved for each job
[2016-01-15T14:16Z] Timing: organize samples
[2016-01-15T14:16Z] multiprocessing: organize_samples
[2016-01-15T14:16Z] Using input YAML configuration: /media/sf_BigShare/16014_wes_pilot/config/project-merged.yaml
[2016-01-15T14:16Z] Checking sample YAML configuration: /media/sf_BigShare/16014_wes_pilot/config/project-merged.yaml
[2016-01-15T14:16Z] Testing minimum versions of installed programs
[2016-01-15T14:16Z] Timing: alignment preparation
[2016-01-15T14:16Z] multiprocessing: prep_align_inputs
[2016-01-15T14:16Z] multiprocessing: disambiguate_split
[2016-01-15T14:16Z] Timing: alignment
[2016-01-15T14:16Z] multiprocessing: process_alignment
[2016-01-15T14:16Z] Aligning lane 1_2016-01-15_project-merged with bwa aligner
[2016-01-15T14:16Z] bwa mem alignment from fastq: A06551
[2016-01-15T14:16Z] samblaster: Version 0.1.22
[2016-01-15T14:16Z] samblaster: Inputting from stdin
[2016-01-15T14:16Z] samblaster: Outputting to stdout
[2016-01-15T14:16Z] samblaster: Opening /dev/fd/62 for write.
[2016-01-15T14:16Z] samblaster: Opening /dev/fd/63 for write.
```

From ***bcbio-nextgen-commands.log**
```
[2016-01-15T14:16Z] /usr/local/bin/bwa mem  -c 250 -M -t 1  -R '@RG\tID:1\tPL:illumina\tPU:1_2016-01-15_project-merged\tSM:A06551' -v 1 /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R1.fastq.gz /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R2.fastq.gz  | /usr/local/bin/samblaster --addMateTags -M --splitterFile >(/usr/local/bin/samtools sort -@ 1 -m 341M -T /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmpwfXxSF/1_2016-01-15_project-merged-sort-sorttmp-spl -o /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmpEFlShv/1_2016-01-15_project-merged-sort-sr.bam /dev/stdin) --discordantFile >(/usr/local/bin/samtools sort -@ 1 -m 341M -T /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmpwfXxSF/1_2016-01-15_project-merged-sort-sorttmp-disc -o /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmpR4j4CL/1_2016-01-15_project-merged-sort-disc.bam /dev/stdin) | samtools view -b -S -u - | sambamba sort  -t 1 -m 341M --tmpdir /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmpwfXxSF/1_2016-01-15_project-merged-sort-sorttmp-full -o /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmpwfXxSF/1_2016-01-15_project-merged-sort.bam /dev/stdin
```

From ***bcbio_system.yaml***
```
bwa:
    cmd: bwa
    cores: 8
 samtools:
    cores: 6
    memory: 1G
```

**Comment by chapmanb** [comment]
Thanks for the detailed reports and sorry for the slow processing speeds. It looks like what happens is that somewhere in your `bcbio_system.yaml` configuration you're asking for 6Gb of memory per core. Since you only have 6Gb, bcbio assigns a single core to run with this to avoid overscheduling memory. A single core bwa run is going to be slow.

Is it possible you have `memory: 6G` specified for `sambamba` or in the `default` section of your configuration? If so, changing this to 1G should let you run this step with 6 cores/6Gb of memory which should hopefully speed it up.

Hope this helps.

**Comment by rjsicko** [comment]
Thanks Brad. I had ```memory: 6G``` in the ```default``` section of ```bcbio_system.yaml``` I've changed it to 1G and will rerun bcbio tonight.

**Comment by rjsicko** [comment]
After letting bcbio run overnight it was still aligning the first sample this morning... a single sample exome shouldn't take that long to align right? I noticed the VM was using memory paging as it maxed out the 6g allocated to it, maybe that was really slowing things down. I am going to allocate 7g to the VM and rerun tonight. 

***bcbio-nextgen-debug.log***
```
[2016-01-19T19:47Z] Resource requests: bwa, sambamba, samtools; memory: 1.00, 1.00; cores: 8, 8, 6
[2016-01-19T19:47Z] Configuring 1 jobs to run, using 5 cores each with 5.6g of memory reserved for each job
[2016-01-19T19:47Z] Timing: organize samples
[2016-01-19T19:47Z] multiprocessing: organize_samples
[2016-01-19T19:47Z] Using input YAML configuration: /media/sf_BigShare/16014_wes_pilot/config/project-merged.yaml
[2016-01-19T19:47Z] Checking sample YAML configuration: /media/sf_BigShare/16014_wes_pilot/config/project-merged.yaml
[2016-01-19T19:47Z] Testing minimum versions of installed programs
[2016-01-19T19:47Z] Timing: alignment preparation
[2016-01-19T19:47Z] multiprocessing: prep_align_inputs
[2016-01-19T19:47Z] multiprocessing: disambiguate_split
[2016-01-19T19:47Z] Timing: alignment
[2016-01-19T19:47Z] multiprocessing: process_alignment
[2016-01-19T19:47Z] Aligning lane 1_2016-01-15_project-merged with bwa aligner
[2016-01-19T19:48Z] bwa mem alignment from fastq: A06551
[2016-01-19T19:48Z] samblaster: Version 0.1.22
[2016-01-19T19:48Z] samblaster: Inputting from stdin
[2016-01-19T19:48Z] samblaster: Outputting to stdout
[2016-01-19T19:48Z] samblaster: Opening /dev/fd/62 for write.
[2016-01-19T19:48Z] samblaster: Opening /dev/fd/63 for write.
[2016-01-19T20:00Z] [M::mem_pestat] analyzing insert size distribution for orientation FF...
[2016-01-19T20:00Z] [M::mem_pestat] (25, 50, 75) percentile: (184, 316, 934)
[2016-01-19T20:00Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 2434)
[2016-01-19T20:00Z] [M::mem_pestat] mean and std.dev: (437.36, 466.69)
[2016-01-19T20:00Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 3184)
[2016-01-19T20:00Z] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2016-01-19T20:00Z] [M::mem_pestat] (25, 50, 75) percentile: (171, 216, 279)
[2016-01-19T20:00Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 495)
[2016-01-19T20:00Z] [M::mem_pestat] mean and std.dev: (229.62, 80.49)
[2016-01-19T20:00Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 603)
[2016-01-19T20:00Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2016-01-19T20:00Z] [M::mem_pestat] skip orientation RR as there are not enough pairs
[2016-01-19T20:00Z] [M::mem_pestat] skip orientation FF
[2016-01-19T20:00Z] samblaster: Loaded 84 header sequence entries.
[2016-01-19T21:36Z] [M::mem_pestat] analyzing insert size distribution for orientation FF...
[2016-01-19T21:36Z] [M::mem_pestat] (25, 50, 75) percentile: (326, 660, 1273)
[2016-01-19T21:36Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 3167)
[2016-01-19T21:36Z] [M::mem_pestat] mean and std.dev: (863.80, 649.36)
[2016-01-19T21:36Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 4114)
[2016-01-19T21:36Z] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2016-01-19T21:36Z] [M::mem_pestat] (25, 50, 75) percentile: (170, 215, 280)
[2016-01-19T21:36Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 500)
[2016-01-19T21:36Z] [M::mem_pestat] mean and std.dev: (229.55, 80.93)
[2016-01-19T21:36Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 610)
[2016-01-19T21:36Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2016-01-19T21:36Z] [M::mem_pestat] analyzing insert size distribution for orientation RR...
[2016-01-19T21:37Z] [M::mem_pestat] (25, 50, 75) percentile: (333, 870, 2085)
[2016-01-19T21:37Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 5589)
[2016-01-19T21:37Z] [M::mem_pestat] mean and std.dev: (1283.58, 1273.86)
[2016-01-19T21:37Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 7341)
[2016-01-19T21:37Z] [M::mem_pestat] skip orientation FF
[2016-01-19T21:37Z] [M::mem_pestat] skip orientation RR
[2016-01-19T23:13Z] [M::mem_pestat] skip orientation FF as there are not enough pairs
[2016-01-19T23:14Z] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2016-01-19T23:14Z] [M::mem_pestat] (25, 50, 75) percentile: (170, 215, 279)
[2016-01-19T23:14Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 497)
[2016-01-19T23:14Z] [M::mem_pestat] mean and std.dev: (229.06, 80.63)
[2016-01-19T23:14Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 606)
[2016-01-19T23:14Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2016-01-19T23:14Z] [M::mem_pestat] skip orientation RR as there are not enough pairs
[2016-01-20T02:21Z] [M::mem_pestat] skip orientation FF as there are not enough pairs
[2016-01-20T02:21Z] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2016-01-20T02:21Z] [M::mem_pestat] (25, 50, 75) percentile: (170, 215, 279)
[2016-01-20T02:21Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 497)
[2016-01-20T02:21Z] [M::mem_pestat] mean and std.dev: (229.27, 80.75)
[2016-01-20T02:21Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 606)
[2016-01-20T02:21Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2016-01-20T02:21Z] [M::mem_pestat] analyzing insert size distribution for orientation RR...
[2016-01-20T02:21Z] [M::mem_pestat] (25, 50, 75) percentile: (263, 1005, 3277)
[2016-01-20T02:21Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 9305)
[2016-01-20T02:21Z] [M::mem_pestat] mean and std.dev: (1599.67, 1593.79)
[2016-01-20T02:21Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 12319)
[2016-01-20T02:21Z] [M::mem_pestat] skip orientation RR
[2016-01-20T06:28Z] [M::mem_pestat] analyzing insert size distribution for orientation FF...
[2016-01-20T06:28Z] [M::mem_pestat] (25, 50, 75) percentile: (343, 1281, 1447)
[2016-01-20T06:28Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 3655)
[2016-01-20T06:28Z] [M::mem_pestat] mean and std.dev: (1112.77, 744.71)
[2016-01-20T06:28Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 4759)
[2016-01-20T06:28Z] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2016-01-20T06:28Z] [M::mem_pestat] (25, 50, 75) percentile: (170, 215, 279)
[2016-01-20T06:28Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 497)
[2016-01-20T06:28Z] [M::mem_pestat] mean and std.dev: (229.01, 80.66)
[2016-01-20T06:28Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 606)
[2016-01-20T06:28Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2016-01-20T06:28Z] [M::mem_pestat] skip orientation RR as there are not enough pairs
[2016-01-20T06:28Z] [M::mem_pestat] skip orientation FF
[2016-01-20T11:22Z] [M::mem_pestat] analyzing insert size distribution for orientation FF...
[2016-01-20T11:23Z] [M::mem_pestat] (25, 50, 75) percentile: (251, 472, 658)
[2016-01-20T11:23Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1472)
[2016-01-20T11:23Z] [M::mem_pestat] mean and std.dev: (387.67, 187.15)
[2016-01-20T11:24Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 1879)
[2016-01-20T11:24Z] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2016-01-20T11:24Z] [M::mem_pestat] (25, 50, 75) percentile: (170, 214, 278)
[2016-01-20T11:24Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 494)
[2016-01-20T11:24Z] [M::mem_pestat] mean and std.dev: (228.40, 80.30)
[2016-01-20T11:24Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 602)
[2016-01-20T11:24Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2016-01-20T11:24Z] [M::mem_pestat] skip orientation RR as there are not enough pairs
[2016-01-20T11:24Z] [M::mem_pestat] skip orientation FF
```

**Comment by chapmanb** [comment]
Sorry about the problems. I haven't done much work in resource limited environments so am not sure about the lower limit at which you can reasonably fast alignment runs. It might be that this isn't enough memory to quickly run this without swapping and slowing things down. bwa does load genome indices into memory so might have a baseline memory usage beyond 6Gb for whole genome runs. I'd have interest in your experience but don't have a lot of good practical suggestions beyond trying to run on a cluster or AWS where you can assign more resources to the runs. Hope this helps some.

**Comment by rjsicko** [comment]
Hi Brad,
Heng Li previously advised me 5.5G was the minimum to load the human genome index (https://www.biostars.org/p/128977/#129017).

When bcbio says ```Configuring 1 jobs to run, using 5 cores each with 5.6g of memory reserved for each job``` is that 5.6G all available to bwa upfront to load the index? Even if it is, the command is piped bwa | samblaster | samtools | sambamba, so maybe the other tools are having to use the swap and it is slowing things down? Maybe I will try aligning with bwa mem outside of bcbio and then passing the aligned bam to bcbio. I'll also look into getting some more memory for my system. Thanks for all of your work!

**Comment by chapmanb** [comment]
Robert;
Thanks much for the link to bwa human memory requirements. You're right on -- since this does things as a pipe it will require additional memory for the sorting, de-duplication and conversion to BAM so 6 or 7Gb will be too little to squeeze it all in. We've tried to design bcbio around minimizing disk IO, which is the biggest bottleneck for these steps, but at the cost of a slightly bigger memory requirement here. Hopefully the updated memory will get things working cleanly. Thanks again.

**Comment by rjsicko** [comment]
Hi Brad,
The increased memory definitely helped! I now have 16G on the machine so I allocated 12G to the VM and the alignment was much faster... however I'm running into another problem and I'm not sure why.

From ````bcbio-nextgen-debug.log````
````
[2016-01-29T17:53Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2016-01-29T17:53Z] [M::mem_pestat] skip orientation RR as there are not enough pairs
[2016-01-29T17:53Z] samblaster: Output 243243 discordant read pairs to /dev/fd/62
[2016-01-29T17:53Z] samblaster: Output 110584 split reads to /dev/fd/63
[2016-01-29T17:53Z] samblaster: Marked 7319424 of 47727799 (15.34%) read ids as duplicates using 853228k memory in 3M49S(228.837S) CPU seconds and 1H48M8S(6488S) wall time.
[2016-01-29T17:53Z] [main] Version: 0.7.12-r1039
[2016-01-29T17:53Z] [main] CMD: /usr/local/bin/bwa mem -c 250 -M -t 8 -R @RG\tID:1\tPL:illumina\tPU:1_2016-01-15_project-merged\tSM:A06551 -v 1 /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R1.fastq.gz /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R2.fastq.gz
[2016-01-29T17:53Z] [main] Real time: 6488.511 sec; CPU: 34567.786 sec
[2016-01-29T18:52Z] sambamba-sort: Failed to remove file /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmp8JwAlK/1_2016-01-15_project-merged-sort-sorttmp-full/sambamba-pid13117-cbew/stdin.0: Text file busy
[2016-01-29T18:52Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/bin/bwa mem  -c 250 -M -t 8  -R '@RG\tID:1\tPL:illumina\tPU:1_2016-01-15_project-merged\tSM:A06551' -v 1 /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R1.fastq.gz /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R2.fastq.gz  | /usr/local/bin/samblaster --addMateTags -M --splitterFile >(/usr/local/bin/samtools sort -@ 8 -m 341M -T /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmp8JwAlK/1_2016-01-15_project-merged-sort-sorttmp-spl -o /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmpwJnBXv/1_2016-01-15_project-merged-sort-sr.bam /dev/stdin) --discordantFile >(/usr/local/bin/samtools sort -@ 8 -m 341M -T /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmp8JwAlK/1_2016-01-15_project-merged-sort-sorttmp-disc -o /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmpdPO_uk/1_2016-01-15_project-merged-sort-disc.bam /dev/stdin) | samtools view -b -S -u - | sambamba sort  -t 8 -m 341M --tmpdir /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmp8JwAlK/1_2016-01-15_project-merged-sort-sorttmp-full -o /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmp8JwAlK/1_2016-01-15_project-merged-sort.bam /dev/stdin
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (544, 1578, 3277)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 8743)
[M::mem_pestat] mean and std.dev: (1976.13, 1737.96)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 11476)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (170, 215, 279)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 497)
[M::mem_pestat] mean and std.dev: (229.23, 80.54)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 606)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (228, 483, 546)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1182)
[M::mem_pestat] mean and std.dev: (350.91, 136.35)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1500)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (282, 491, 2153)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 5895)
[M::mem_pestat] mean and std.dev: (1019.79, 1154.41)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 7766)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (170, 214, 279)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 497)
[M::mem_pestat] mean and std.dev: (228.88, 80.77)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 606)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (248, 806, 1729)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 4691)
[M::mem_pestat] mean and std.dev: (790.25, 627.55)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 6172)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (328, 781, 1378)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 3478)
[M::mem_pestat] mean and std.dev: (788.00, 547.18)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 4528)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (170, 215, 278)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 494)
[M::mem_pestat] mean and std.dev: (228.49, 80.23)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 602)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (345, 803, 1719)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 4467)
[M::mem_pestat] mean and std.dev: (868.50, 888.55)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 5841)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (354, 633, 1794)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 4674)
[M::mem_pestat] mean and std.dev: (1006.95, 1020.92)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 6114)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (169, 214, 277)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 493)
[M::mem_pestat] mean and std.dev: (228.01, 79.89)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 601)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation FF
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (338, 545, 1164)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 2816)
[M::mem_pestat] mean and std.dev: (588.25, 353.15)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 3642)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (169, 213, 276)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 490)
[M::mem_pestat] mean and std.dev: (227.20, 79.26)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 597)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (227, 596, 694)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1628)
[M::mem_pestat] mean and std.dev: (375.75, 226.89)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2095)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (169, 213, 276)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 490)
[M::mem_pestat] mean and std.dev: (226.96, 78.98)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 597)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
samblaster: Output 243243 discordant read pairs to /dev/fd/62
samblaster: Output 110584 split reads to /dev/fd/63
samblaster: Marked 7319424 of 47727799 (15.34%) read ids as duplicates using 853228k memory in 3M49S(228.837S) CPU seconds and 1H48M8S(6488S) wall time.
[main] Version: 0.7.12-r1039
[main] CMD: /usr/local/bin/bwa mem -c 250 -M -t 8 -R @RG\tID:1\tPL:illumina\tPU:1_2016-01-15_project-merged\tSM:A06551 -v 1 /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R1.fastq.gz /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R2.fastq.gz
[main] Real time: 6488.511 sec; CPU: 34567.786 sec
sambamba-sort: Failed to remove file /media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmp8JwAlK/1_2016-01-15_project-merged-sort-sorttmp-full/sambamba-pid13117-cbew/stdin.0: Text file busy
' returned non-zero exit status 1
````

**Comment by chapmanb** [comment]
Robert;
Glad the memory change helped with speed, but sorry you're stuck on another issue. It looks like there is some kind of file write problem to this temporary directory:
```
/media/sf_BigShare/16014_wes_pilot/work/align/A06551/tx/tmp8JwAlK
```
What kind of filesystem is `/media/sf_BigShare`? If it's some kind of shared filesystem it might be getting stressed by the read/writes and failing to respond. You might need to change your temporary directory to local disk. You can specify this for bcbio by adding a `resources` line to your sample YAML file:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#temporary-directory

Hope that helps work around the issue and keep your analysis going.

**Comment by rjsicko** [comment]
ok, it's still running but it looks like using a tmp dir on the VM is working.

````/media/sf_BigShare```` is an external NTFS drive attached to the host computer via USB3.0 and mounted to the VM as a shared folder. I know I've had trouble creating symlinks in a VM shared folder before. It's weird because the file the error code says couldn't be removed was actually gone from the folder.

Anyway, thank you for all of your help!
