### ISSUE TITLE
Gemini annotation file is missing

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1194]
Hi Brad,
In the currently bcbio development version, I found the following error in the tumor-normal var calling for exome-seq data. It seems that the geno2mp.variants.tidy.vcf.gz annotation file is missing. Could you please let me know how to install it in bcbio?
Thanks!

[2016-01-20T02:54Z] c2707.***.edu: ipython: prep_gemini_db
[2016-01-20T02:58Z] c2517.***.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /parallel/bcbio/anaconda/bin/gemini  load  --passonly --skip-gerp-bp  -v /lustre/project/work/gemini/batch05-ensemble-decompose-effects.vcf.gz -t snpEff --cores 16 --tempdir /lustre/project/work/gemini/tx/tmp63Eael /lustre/project/work/gemini/tx/tmp63Eael/batch05-ensemble.db
CADD scores are being loaded (to skip use:--skip-cadd).
Gemini cannot open this annotation file: /parallel/bcbio/gemini_data/geno2mp.variants.tidy.vcf.gz. 
Have you installed the annotation files?  If so, have they been moved or deleted? Exiting...

For more details:
	http://gemini.readthedocs.org/en/latest/content/#installation.html\#installing-annotation-files

**Comment by chapmanb** [comment]
Sorry about the issue. You also need to update bcbio data to get the latest gemini databases. You can either only upgrade gemini:
```
gemini update --dataonly
```
or upgrade everything:
```
bcbio_nextgen.py upgrade --data
```
Hope this helps get things running for you.

**Comment by pengxiao78** [comment]
Brad,
I used 

bcbio_nextgen.py upgrade --data

to upgrade everything. However, following error appeared

subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/parallel/bcbio/anaconda/bin:$PATH && export PERL5LIB=/parallel/bcbio/lib/perl5:$PERL5LIB && /parallel/bcbio/bin/vep_convert_cache.pl -species homo_sapiens -version 83_GRCh37 -d /parallel/bcbio/genomes/Hsapiens/GRCh37/vep
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2 /parallel/bcbio/lib/perl5 /parallel/bcbio/lib/perl5/site_perl /home/pxiao/.conda/envs/.pkgs/perl-5.22.0-8/lib/perl5/site_perl/5.22.0/x86_64-linux /home/pxiao/.conda/envs/.pkgs/perl-5.22.0-8/lib/perl5/site_perl/5.22.0 /home/pxiao/.conda/envs/.pkgs/perl-5.22.0-8/lib/perl5/5.22.0/x86_64-linux /home/pxiao/.conda/envs/.pkgs/perl-5.22.0-8/lib/perl5/5.22.0 .) at /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
BEGIN failed--compilation aborted at /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
Compilation failed in require at /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.
BEGIN failed--compilation aborted at /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.
Compilation failed in require at /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2/Bio/EnsEMBL/Registry.pm line 136.
BEGIN failed--compilation aborted at /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2/Bio/EnsEMBL/Registry.pm line 136.
Compilation failed in require at /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2/Bio/EnsEMBL/Variation/Utils/VEP.pm line 69.
BEGIN failed--compilation aborted at /home/pxiao/.conda/envs/.pkgs/variant-effect-predictor-83-pl5.22.0_2/share/variant-effect-predictor-83-2/Bio/EnsEMBL/Variation/Utils/VEP.pm line 69.
Compilation failed in require at /parallel/bcbio/bin/vep_convert_cache.pl line 42.
BEGIN failed--compilation aborted at /parallel/bcbio/bin/vep_convert_cache.pl line 42.
' returned non-zero exit status 2

I found that someone previously also had the similar problem.
I tried your previously provided solution

export PERL5LIB=/usr/local/lib/perl5:/usr/local/lib/perl5/site_perl:${PERL5LIB}
(It did not work)

and another one

bcbio_vm.py upgrade --wrapper

It was shown 

-bash: bcbio_vm.py: command not found

Could you please help me to solve it?

Thanks!

**Comment by chapmanb** [comment]
Sorry about the issues. bcbio should now install perl and all of the libraries, including DBI as part of the standard conda install. It seems like your install might not be fully up to date in some way. Could you try doing:
```
bcbio_nextgen.py upgrade -u development --tools --data
```
to get up to date with the latest code, tools and data. I hope this will resolve things for you. Sorry about all the back and forth.

**Comment by pengxiao78** [comment]
I used

bcbio_nextgen.py upgrade -u development --tools --data

The same error occurred. 
Can't locate DBI.pm in @INC (you may need to install the DBI module)

**Comment by chapmanb** [comment]
Sorry that didn't fix it. I'm a bit confused as to what is going on with the conda install here, but that seems to be causing the issues. From your traceback, it seems to be trying to inject from some other conda install in your home directory:
```
/home/pxiao/.conda/envs/.pkgs/perl-5.22.0-8/lib/perl5/site_perl/5.22.0/x86_64-linux
```
Where you want to get perl and libraries from:
```
/parallel/bcbio/anaconda/lib/perl5/site_perl/5.22.0/x86_64-linux/
```
The DBI module should be here:
```
ls -lh /parallel/bcbio/anaconda/lib/perl5/site_perl/5.22.0/x86_64-linux/DBI
```
Sorry I'm not totally sure how to replicate these results so I can suggest how to work around them. Do you have some anaconda variables set or something else happening with conda environments that might be leading to this? Hope this helps some.

**Comment by pengxiao78** [comment]
When I checked the DBI module by 

ls -lh /parallel/bcbio/anaconda/lib/perl5/site_perl/5.22.0/x86_64-linux/DBI

I find  all the pm files are short links such as

lrwxrwxrwx 1 pxiao 123 Jan 18 16:29 Changes.pm -> /home/pxiao/.conda/envs/.pkgs/perl-dbi-1.634-pl5.22.0_0/lib/perl5/site_perl/5.22.0/x86_64-linux/DBI/Changes.pm

**Comment by chapmanb** [comment]
Thanks for the details. I'm confused as to why the commands fail and also as to what is going on with your install. Do you have any insight into why you're getting installs into your home directory? If you do:
```
ls -lh /home/pxiao/.conda/envs/.pkgs/perl-dbi-1.634-pl5.22.0_0/lib/perl5/site_perl/5.22.0/x86_64-linux/DBI/
```
are the DBI files present there, or missing? if present, it seems like perl should find them since:
```
/home/pxiao/.conda/envs/.pkgs/perl-5.22.0-8/lib/perl5/site_perl/5.22.0/x86_64-linux
```
is in the perl `@INC` path. Sorry to not understand what happened with the install here, but hope this helps a little to untangle it.

**Comment by pengxiao78** [comment]
I checked 
/home/pxiao/.conda/envs/.pkgs/perl-5.22.0-8/lib/perl5/site_perl/5.22.0/x86_64-linux 
All DBI files are there. It is really weird.

**Comment by bwubb** [comment]
Was this resolved? I believe I am having similar issues. I received the OP error, and I am unable to successfully 'upgrade --data'.

```
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 261, in upgrade_bcbio_data
    _upgrade_vep_data(s["fabricrc_overrides"]["galaxy_home"], tooldir)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 297, in _upgrade_vep_data
    effects.prep_vep_cache(dbkey, ref_file, tooldir)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 102, in prep_vep_cache
    do.run("%s && %s" % (perl_exports, " ".join(cmd)), "Prepare VEP directory for %s" % ensembl_name)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/home/bwubb/bcbio-nextgen/anaconda/bin:$PATH && /home/bwubb/bcbio-tools/bin/vep_install.pl -a c -s mus_musculus_vep_83_GRCm38 -c /home/bwubb/bcbio-nextgen/genomes/Mmusculus/mm10/vep -u /home/bwubb/bcbio-nextgen/genomes/Mmusculus/mm10/vep/mus_musculus/txtmp
perl: symbol lookup error: /home/bwubb/bcbio-tools/lib/perl5/x86_64-linux-thread-multi/auto/Time/HiRes/HiRes.so: undefined symbol: Perl_Istack_sp_ptr
' returned non-zero exit status 127
```

**Comment by chapmanb** [comment]
Brad;
Sorry about the problem. Could you try doing: `unset PERL5LIB` before running the upgrade command? It looks like it's pulling in previously installed libraries compiled with a different perl rather than the ones we expect from in the anaconda directory. If this fixes it I can add it in as a default. Thanks much.

**Comment by bwubb** [comment]
I had to do the ```/home/bwubb/bcbio-nextgen/anaconda/bin/conda uninstall perl perl-threaded``` and ```upgrade --tools``` again first. The unset did not display that it did anything, but maybe that is normal. Afterwards I was able to ```upgrade -u development --tools --data``` successfully. I will now rerun analysis to see if this works out. Thank you for the help.

**Comment by bwubb** [comment]
What is that last comment?

I was just going to say I have another symbol lookup error with scalpel now?

```
[2016-02-23T21:00Z] perl: symbol lookup error: /home/bwubb/bcbio-tools/lib/perl5/x86_64-linux-thread-multi/auto/Compress/Raw/Zlib/Zlib.so: undefined symbol: Perl_Istack_sp_ptr
[2016-02-23T21:00Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/home/bwubb/bcbio-nextgen/anaconda/bin:$PATH && scalpel-discovery --somatic --format vcf --intarget --covthr 3 --lowcov 1 --pathlimit 10000 --bed /home/bwubb/NGS/BasserWES/data/Brca1Br10-T/work/mutect/1/Batch1-1_0_15541883-raw-somaticIndels-regions-nolcr-nolcr.bed --outratio 0.1 --ref /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --dir /home/bwubb/NGS/BasserWES/data/Brca1Br10-T/work/mutect/1/Batch1-1_0_15541883-raw-somaticIndels-scalpel-work --tumor /home/bwubb/NGS/BasserWES/data/Brca1Br10-T/work/bamprep/Brca1Br10-T/1/Brca1Br10-T-sort-1_0_15541883-prep.bam --normal /home/bwubb/NGS/BasserWES/data/Brca1Br10-T/work/bamprep/Brca1Br10-B/1/Brca1Br10-B-sort-1_0_15541883-prep.bam
perl: symbol lookup error: /home/bwubb/bcbio-tools/lib/perl5/x86_64-linux-thread-multi/auto/Compress/Raw/Zlib/Zlib.so: undefined symbol: Perl_Istack_sp_ptr
' returned non-zero exit status 127
```

**Comment by chapmanb** [comment]
Brad;
I believe you'll need to upgrade to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
so bcbio will unset PERL5LIB for you when running the scalpel commands, or permanently unset PERL5LIB to not include `/home/bwubb/bcbio-tools/lib/perl5/` to avoid pulling in the incorrect libraries. Hope this fixes it for you.

**Comment by bwubb** [comment]
Not at first.
```
[2016-02-24T12:57Z] ***MAIN ANALYSIS***
[2016-02-24T12:57Z] perl: symbol lookup error: /home/bwubb/bcbio-tools/lib/perl5/x86_64-linux-thread-multi/auto/Compress/Raw/Zlib/Zlib.so: undefined symbol: Perl_Istack_sp_ptr
[2016-02-24T12:57Z] Command failure: FindSomatic (/home/bwubb/bcbio-nextgen/anaconda/share/scalpel-0.5.1-3/FindSomatic.pl --normal /home/bwubb/NGS/BasserWES/data/Brca1Br10-T/work/bamprep/Brca1Br10-B/1/Brca1Br10-B-sort-1_0_15541883-prep.bam --tumor /home/bwubb/NGS/BasserWES/data/Brca1Br10-T/work/bamprep/Brca1Br10-T/1/Brca1Br10-T-sort-1_0_15541883-prep.bam --bed /home/bwubb/NGS/BasserWES/data/Brca1Br10-T/work/mutect/1/Batch1-1_0_15541883-raw-somaticIndels-regions-nolcr-nolcr.bed --ref /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --kmer 25 --covthr 3 --lowcov 1 --mincov 5 --covratio 0.01 --outratio 0.1 --radius 100 --window 400 --maxregcov 10000 --step 100 --mapscore 1 --mismatches 3 --pathlimit 10000 --dir /home/bwubb/NGS/BasserWES/data/Brca1Br10-T/work/mutect/1/Batch1-1_0_15541883-raw-somaticIndels-scalpel-work/main --numprocs 1 --format vcf --coords null --intarget)...
```
Which ultimately ended with an AssertionError for input file. As you suggested, I removed the export /home/bwubb/bcbio-tools/lib/perl5/ and things appear to be running properly for now. Thank you.

**Comment by phu5ion** [comment]
Hi Brad,

I have a similar problem and my bcbio version is at 1.0.5a0 which is one of the latest versions, so I'm not sure whether an upgrade will solve issues. Could you pls help me?

Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 191, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 35, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 182, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 67, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 137, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/qc/fastqc.py", line 49, in run
    do.run(cl, "FastQC: %s" % dd.get_sample_name(data))
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin:$PATH &&  /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/fastqc -d /mnt/projects/ngbhs/cirqseq/20170224_plasma/20170704_Set1456/bcbio/360_matchedN/work/qc/360_T/bcbiotx/tmpREJnNQ -t 16 --extract -o /mnt/projects/ngbhs/cirqseq/20170224_plasma/20170704_Set1456/bcbio/360_matchedN/work/qc/360_T/bcbiotx/tmpREJnNQ -f bam /mnt/projects/ngbhs/cirqseq/20170224_plasma/20170704_Set1456/bcbio/360_matchedN/work/qc/360_T/360_T-sort-downsample.bam
perl: symbol lookup error: /mnt/software/lib/perl5/5.10.1/auto/Cwd/Cwd.so: undefined symbol: Perl_Istack_sp_ptr
' returned non-zero exit status 127

**Comment by chapmanb** [comment]
Sorry about the issues, this looks like you have an incompatible Perl version in:
```
/mnt/software/lib/perl5/
```
injecting shared libraries and disrupting the perl version shipped with bcbio.

Is it possible you have `LD_LIBRARY_PATH` or other environmental tweaks as part of a module setup on your system? If so, could you try unloading those, as they're not needed with bcbio. Hope this helps resolve the problem.
