### ISSUE TITLE
mutect problem

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1196]
Hi! 

I'm having issues with mutect; a traceback below. I wonder if it might have something to do with mutect running under the systems java (v. 1.8) instead of java version 1.7 that is included with bcbio-nextgen? Apparently mutect requires java 1.7. 

That is, if I interpret things correctly from what google has given me.

//Pär

```
2016-01-21T12:00Z] multiprocessing: combine_sample_regions
[2016-01-21T12:00Z] Identified 18 parallel analysis blocks
Block sizes:
  min: 3119006
  5%: 14716894.75
  25%: 24449223.5
  median: 55115255.0
  75%: 107665416.25
  95%: 136408514.25
  99%: 138213897.25
  max: 138665243
Between block sizes:
  min: 789
  5%: 794.25
  25%: 1284.75
  median: 2273.5
  75%: 4487.75
  95%: 26178028.9
  99%: 37452135.38
  max: 40270662

[2016-01-21T12:00Z] Timing: structural variation initial
[2016-01-21T12:00Z] Timing: hla typing
[2016-01-21T12:00Z] Resource requests: freebayes, gatk, mutect, picard, vardict, varscan; memory: 2.00, 3.50, 2.50, 3.50, 3.00, 2.00; cores: 16, 1, 1, 1, 1, 1
[2016-01-21T12:00Z] Configuring 1 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2016-01-21T12:00Z] Timing: alignment post-processing
[2016-01-21T12:00Z] multiprocessing: piped_bamprep
[2016-01-21T12:00Z] Timing: variant calling
[2016-01-21T12:00Z] multiprocessing: variantcall_sample
[2016-01-21T12:00Z] MuTect: MuTect
[2016-01-21T12:00Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-01-21T12:00Z] ##### ERROR stack trace
[2016-01-21T12:00Z] java.lang.ExceptionInInitializerError
[2016-01-21T12:00Z] 	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:167)
[2016-01-21T12:00Z] 	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:57)
[2016-01-21T12:00Z] 	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:66)
[2016-01-21T12:00Z] 	at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:106)
[2016-01-21T12:00Z] Caused by: java.lang.NullPointerException
[2016-01-21T12:00Z] 	at org.reflections.Reflections.scan(Reflections.java:220)
[2016-01-21T12:00Z] 	at org.reflections.Reflections.scan(Reflections.java:166)
[2016-01-21T12:00Z] 	at org.reflections.Reflections.<init>(Reflections.java:94)
[2016-01-21T12:00Z] 	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:79)
[2016-01-21T12:00Z] 	... 4 more
[2016-01-21T12:00Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-01-21T12:00Z] ##### ERROR A GATK RUNTIME ERROR has occurred (version 3.1-0-g72492bb):
[2016-01-21T12:00Z] ##### ERROR
[2016-01-21T12:00Z] ##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
[2016-01-21T12:00Z] ##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
[2016-01-21T12:00Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2016-01-21T12:00Z] ##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
[2016-01-21T12:00Z] ##### ERROR
[2016-01-21T12:00Z] ##### ERROR MESSAGE: Code exception (see stack trace for error itself)
[2016-01-21T12:00Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-01-21T12:00Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'java -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/home/lindak/Data/LiquidBiopsies/TruSight15/160115/calling/work/tx/tmpSya1Vp -jar /usr/local/share/bcbio/toolplus/mutect/1.1.7/mutect-1.1.7.jar -R /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -T MuTect -U ALLOW_N_CIGAR_READS --read_filter NotPrimaryAlignment -I:tumor /home/lindak/Data/LiquidBiopsies/TruSight15/160115/calling/work/bamprep/CRC204-A_tumor/1/CRC204-A_tumor-sort-1_0_115252404-prep.bam --tumor_sample_name CRC204-A_tumor --dbsnp /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp_138.vcf.gz --cosmic /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation/cosmic-v68-GRCh37.vcf.gz -L /home/lindak/Data/LiquidBiopsies/TruSight15/160115/calling/work/mutect/1/CRC204-A-1_0_115252404-raw-mutect-regions.bed --interval_set_rule INTERSECTION --enable_qscore_output --vcf /home/lindak/Data/LiquidBiopsies/TruSight15/160115/calling/work/mutect/1/tx/tmpLcYj_z/CRC204-A-1_0_115252404-raw-mutect-orig.vcf.gz -o /dev/null
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR stack trace 
java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:167)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:57)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:66)
	at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:106)
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:79)
	... 4 more
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A GATK RUNTIME ERROR has occurred (version 3.1-0-g72492bb):
##### ERROR
##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
##### ERROR
##### ERROR MESSAGE: Code exception (see stack trace for error itself)
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 149, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 169, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 147, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 254, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect.py", line 129, in mutect_caller
    broad_runner.run_mutect(params)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 293, in run_mutect
    do.run(cl, "MuTect: {0}".format(prog), None)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'java -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/home/lindak/Data/LiquidBiopsies/TruSight15/160115/calling/work/tx/tmpSya1Vp -jar /usr/local/share/bcbio/toolplus/mutect/1.1.7/mutect-1.1.7.jar -R /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -T MuTect -U ALLOW_N_CIGAR_READS --read_filter NotPrimaryAlignment -I:tumor /home/lindak/Data/LiquidBiopsies/TruSight15/160115/calling/work/bamprep/CRC204-A_tumor/1/CRC204-A_tumor-sort-1_0_115252404-prep.bam --tumor_sample_name CRC204-A_tumor --dbsnp /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp_138.vcf.gz --cosmic /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation/cosmic-v68-GRCh37.vcf.gz -L /home/lindak/Data/LiquidBiopsies/TruSight15/160115/calling/work/mutect/1/CRC204-A-1_0_115252404-raw-mutect-regions.bed --interval_set_rule INTERSECTION --enable_qscore_output --vcf /home/lindak/Data/LiquidBiopsies/TruSight15/160115/calling/work/mutect/1/tx/tmpLcYj_z/CRC204-A-1_0_115252404-raw-mutect-orig.vcf.gz -o /dev/null
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR stack trace 
java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:167)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:57)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:66)
	at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:106)
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:79)
	... 4 more
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A GATK RUNTIME ERROR has occurred (version 3.1-0-g72492bb):
##### ERROR
##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
##### ERROR
##### ERROR MESSAGE: Code exception (see stack trace for error itself)
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Pär;
That's right, you need Java 1.7 for MuTect and GATK runs. We've just started shipping Java 1.7 with bcbio in the last week but haven't tested it at scale so don't use it by default for these parts yet. If you swap over to have java 1.7 in your path MuTect should work cleanly. Hope this helps

**Comment by pengxiao78** [comment]
Hi Brad,
I just met the same error as above although I have updated the vardict java by 

bcbio_conda install -c bioconda vardict-java

on my current bcbio-nextgen 0.9.6 development version.
Is there anyway to fix it?
Thanks.

**Comment by chapmanb** [comment]
Sorry I'm a bit confused. Is this the same problem as you've been discussing in #1225 with VarDict, or a different problem with MuTect?
