### ISSUE TITLE
bcbio python complain on non multithreading  samtools

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1197]
Hi Brad, after update bcbio to 0.9.5 I am running in an error every time I try to run bcbio ipython. 

basically it stop during Testing minimum versions of installed programs. If i run a local multi core run I do not have any problem ...
do you have a Hint?
Thanks!

2016-01-21 19:42:21.779 [IPClusterStart] {'BcbioTORQUEEngineSetLauncher': {'mem': '8.1', 'tag': '', 'cores': 4, 'resources': 'mem=22G;pmem=22G;pvmem=50G'}, 'IPClusterEngines': {'early_shutdown': 240}, 'Application': {'log_level': 10}, 'ProfileDir': {'location': u'/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Hemepact_PCNSL/Hempact_pair/Hempact_pair/work/log/ipython'}, 'BaseParallelApplication': {'log_to_file': True, 'cluster_id': u'a031e333-245a-4666-8e17-da0f313b61fc'}, 'TORQUELauncher': {'queue': 'batch'}, 'BcbioTORQUEControllerLauncher': {'mem': '', 'tag': '', 'cores': 1, 'resources': 'mem=22G;pmem=22G;pvmem=50G'}, 'IPClusterStart': {'controller_launcher_class': u'cluster_helper.cluster.BcbioTORQUEControllerLauncher', 'engine_launcher_class': u'cluster_helper.cluster.BcbioTORQUEEngineSetLauncher', 'n': 8, 'delay': 10, 'daemonize': True}}
8 Engines running
[2016-01-22T00:43Z] mskcc-ln1.local: Timing: organize samples
[2016-01-22T00:43Z] mskcc-ln1.local: ipython: organize_samples
[2016-01-22T00:43Z] gpu-3-9.local: Using input YAML configuration: /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Hemepact_PCNSL/Hempact_pair/Hempact_pair/config/Hempact_pair.yaml
[2016-01-22T00:43Z] gpu-3-9.local: Checking sample YAML configuration: /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Hemepact_PCNSL/Hempact_pair/Hempact_pair/config/Hempact_pair.yaml
[2016-01-22T00:43Z] gpu-3-9.local: Testing minimum versions of installed programs
[2016-01-22T00:43Z] gpu-3-9.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 45, in _setup_logging
    yield config
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 402, in organize_samples
    return ipython.zip_args(apply(run_info.organize, *args))
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 69, in organize
    out = _add_provenance(out, dirs, config, add_provenance)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 81, in _add_provenance
    versioncheck.testall(items)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/versioncheck.py", line 66, in testall
    "\n".join(msgs))
OSError: Program problems found. You can upgrade dependencies with:
bcbio_nextgen.py upgrade -u skip --tooldir=/usr/local

Installed version of samtools sort does not have support for multithreading (-@ option) required to support bwa piped alignment and BAM merging. Please upgrade to the latest version from http://samtools.sourceforge.net/
Sending a shutdown signal to the controller and engines.
2016-01-21 19:44:05.438 [IPClusterStop] Using existing profile dir: u'/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Hemepact_PCNSL/Hempact_pair/Hempact_pair/work/log/ipython'
2016-01-21 19:44:05.506 [IPClusterStop] Stopping cluster [pid=38495] with [signal=2]
2016-01-21 19:44:07.247 [IPClusterStop] Using existing profile dir: u'/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/Hemepact_PCNSL/Hempact_pair/Hempact_pair/work/log/ipython'
2016-01-21 19:44:07.258 [IPClusterStop] Stopping cluster [pid=38495] with [signal=2]
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6a0', 'bcbio_nextgen.py')
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/pkg_resources/__init__.py", line 1651, in run_script
    
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6a0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6a0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 47, in run_main
    fc_dir, run_info_yaml)
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 115, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 135, in run
    for data in view.map_sync(fn, items, track=False):
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-140>", line 2, in map
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-139>", line 2, in map
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<decorator-gen-119>", line 2, in __call__
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "/cbio/cslab/nobackup/pastore/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: organize_samples
[5:apply]: OSError: Program problems found. You can upgrade dependencies with:
bcbio_nextgen.py upgrade -u skip --tooldir=/usr/local

Installed version of samtools sort does not have support for multithreading (-@ option) required to support bwa piped alignment and BAM merging. Please upgrade to the latest version from http://samtools.sourceforge.net/

**Comment by lpantano** [comment]
Hi @apastore,

sorry about that. It is because of the new version of samtools and how it output the usage. @roryk fixed this here 81ca387d06b2d64701cbe63f3e68d196974c6f4f. It worked for one of the cluster we used. I think you will need to update to development version since this happened after 0.9.5 stable release.

hope this help.

**Comment by apastore** [comment]
Thanks!
