### ISSUE TITLE
Error When Preparing Bedfile

### ISSUE THREAD

**Issue by rb5000** [chapmanb/bcbio-nextgen#1217]
Hi,

I am trying to run an analysis on exome sequences from a quad. Everything works well up until the post process alignment step:
```
[2016-02-05T22:53Z] multiprocessing: prep_samples
[2016-02-05T22:53Z] Prepare cleaned BED file : Brother
[2016-02-05T22:53Z] Prepare merged BED file : Brother
[2016-02-05T22:53Z] Prepare cleaned BED file : Father
[2016-02-05T22:53Z] Prepare merged BED file : Father
[2016-02-05T22:53Z] Prepare cleaned BED file : Mother
[2016-02-05T22:53Z] Prepare merged BED file : Mother
[2016-02-05T22:53Z] Prepare cleaned BED file : Proband
[2016-02-05T22:54Z] Prepare merged BED file : Proband
[2016-02-05T22:54Z] multiprocessing: postprocess_alignment
[2016-02-05T22:54Z] Resource requests: ; memory: 1.00; cores: 1
[2016-02-05T22:54Z] Configuring 8 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
Traceback (most recent call last):
  File "/home/bcbio/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 130, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 43, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 182, in postprocess_alignment
    callable.block_regions(bam_file_ready, ref_file, data)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 332, in block_regions
    nblock_regions = _add_config_regions(nblock_regions, ref_regions, config)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 261, in _add_config_regions
    "in the BED file match your genome (chr1 vs 1)?" % input_regions_bed)
ValueError: Input variant_region file (home/bcbio_analysis/config/bedprep/BEDFILE.bed) excludes all genomic regions. Do the chromosome names in the BED file match your genome (chr1 vs 1)?
```

i tried rerunning the analysis with an identical bedfile, except I omitted the 'chr' from the first column (i.e chr1 --> 1), but got the same result. I also took a look at the bedprep directory, and noticed that most of the files are empty. Is that normal?

Thanks again for the continued support!

**Comment by chapmanb** [comment]
Sorry about the problems. Cleanup from having initial incorrect BED files can be a little tricky. This should be improved in the latest development version but the easiest way to re-run if you had incompatible chromosome naming is to remove temporary files created by bcbio and let it re-create them:
```
rm -rf bedprep
rm -rf align/*/*-callable*
```
Hopefully this will get your project running cleanly again.

**Comment by lpantano** [comment]
Closing this since it seems Brad's suggestion worked.

let us know if you find more issues.

thanks a lot
