### ISSUE TITLE
bcbio_setup_genome gff issue

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1220]
Hi again

Thanks for fixing https://github.com/chapmanb/bcbio-nextgen/issues/1218 . Running the bcbio_setup_genome without a gff3 file now works fine.  A new problem however emerged when adding the gff3, it complains about duplicate IDs. 

There may be a problem with the gff so I've emailed the NCBI about it:

"I'm having problems with gff file that does not seem to adhere to the gff3 specification (GCF_000008985.1_ASM898v1_genomic.gff).

The problem comes from that IDs are not unique. One case that I found is ID=cds2 but there might more.

This cds corresponds to a cds that undergoes programmed ribosomal frameshifting and is therefore added as two separate lines / reading frames in the gff but where the IDs are the same. Is this the correct way of representing this feature?"

So lets wait and see what they say.

Traceback:

```
$ bcbio_setup_genome.py -f GCF_000008985.1_ASM898v1_genomic.fna.gz --gff3 -g GCF_000008985.1_ASM898v1_genomic.gff -i bwa -n AJ749949.2 -b 2
Converting /home/parlar/Downloads/GCF_000008985.1_ASM898v1_genomic.gff to /home/parlar/Downloads/GCF_000008985.1_ASM898v1_genomic.gtf.
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_setup_genome.py", line 191, in <module>
    args.gtf = gff3_to_gtf(args.gtf)
  File "/usr/local/bin/bcbio_setup_genome.py", line 50, in gff3_to_gtf
    db = gffutils.create_db(gff3_file, ":memory:")
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 571, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 218, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID cds2
```

**Comment by druvus** [comment]
Hi Pär, 
We had the same general issus with NCBI's bacterial files so I have some "quick fix" scripts using gbk files to generate cleaned up files for a custom bacterial genome. You can find them in this github folder: https://github.com/druvus/hsph-scripts 

The files you need are: 
* gb2gtf_bacteria.py
* gb2ptt_bacteria.py
* gb2rnt_bacteria.py 

The scripts should be cleaned up and merged but it might help you get started with you bacterial  analysis.

**Comment by parlar** [comment]
Thanks, Andreas! Did you report the lack of adherence to the gff3 spec to the ncbi? Any comments from them?

**Comment by lpantano** [comment]
Hi,

I had to change a few lines in the code to get the files compatible, I 
was thinking to add it to bcbio scripts folder to make them available 
for all people. But I will add them this afternoon. We changed a little 
the code (mainly for QC figures) that affects GTF information.

All this thanks to @druvus.

**Comment by parlar** [comment]
Brilliant! Thanks @lpantano .

**Comment by lpantano** [comment]
Hi @parlar,

you can try this script and let me know if you get any error:
https://github.com/chapmanb/bcbio-nextgen/blob/master/scripts/utils/gb2genome.gtf

You can get the usage using `-h` flag, and you should use bcbio python to be sure all dependency are installed.

it should produce FASTA and GTF ready to pass to setup_genome script.

thanks @druvus for starting this.

cheers

**Comment by druvus** [comment]
Thanks @lpantano for fixing it.

**Comment by parlar** [comment]
Hi again,

I received this elaborate reply from Majda Valjavec-Gratian, NCBI:

------
Dear Colleague,

I have checked with the NCBI Reference Sequence staff and they stated that this is legal and expected for the GFF3 spec, which is documented here: 
http://www.sequenceontology.org/gff3.shtml
In particular:
ID – Indicates the ID of the feature. IDs for each feature must be unique within the scope of the GFF file. In the case of discontinuous features (i.e. a single feature that exists over multiple genomic locations) the same ID may appear on multiple lines. All lines that share an ID collectively represent a single feature.
That is, a multi-interval CDS (a discontinuous feature, represented in the flatfilie view by JOIN or ORDER), whether from splicing (multiple exons) or an event such as ribosomal slippage, is expected to have multiple CDS rows in the GFF3 file. The shared ID indicates that they are part of a single feature.
It is most common to see IDs shared across multiple rows for CDS features, and some software expects it to only be true for CDS features, but the GFF3 specification allows this type of markup for any feature. Within NCBI's GFF3 files, it is also seen on some gene and tRNA features (in particular those that are trans-spliced), and it is also used for alignments that appear in eukaryotic annotations.
You may also want to refer to the example in the GFF3 specification under "Programmed frameshift", which has two CDS rows with "ID=cds01".


Majda

Best regards,

Majda Valjavec-Gratian, Ph.D.
NCBI User Services

--------

So, distribution of features of multiple lines but with a single ID is in agreement with the gff3 specification. Should the setup_genome script itself be modified to handle this situation?

**Comment by roryk** [comment]
Thanks Pär and Andreas,

I'd like to be able to handle it if we can figure out a way to do it. Where did GCF_000008985.1_ASM898v1_genomic.gff come from so I can have something to look at?

**Comment by roryk** [comment]
The first example from the gffutils docs might be applicable: 
https://pythonhosted.org/gffutils/examples.html#mouse-extra-comma-gff3

**Comment by druvus** [comment]
Hi Rory, 
the file Pär is using can be downloaded from NCBI. 

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000008985.1_ASM898v1/GCF_000008985.1_ASM898v1_genomic.gff.gz 

It is the refseq version so it should be generic to all bacterial reference genomes.

**Comment by parlar** [comment]
Thanks @druvus, sorry about slow response

**Comment by roryk** [comment]
Oh sweet, I missed that you all fixed it already. Is running the separate script first workable or does it need to get integrated more?

**Comment by druvus** [comment]
The separate scripts works fine for RNA-seq but it is not optimal for WGS studies. It would be preferable to update the script to also use repeat information (rRNA copies and IS elements). I mainly use custom genomes in bcbio for RNA-seq studies so I haven't had time to look into how to improve conversion of  bacterial annotation in a more generic way.

**Comment by lpantano** [comment]
hum, you mean that the current genome.fa that comes from the script has 
not rRNA and repeat elements? Because I understand this happens when 
creating the GTF file, what confused for the FASTA file.

Let me know where I can improve that, and happy to update.

**Comment by druvus** [comment]
My mistake, getting late over here. Took a closer look at original and generated files. I didn't realise that they had individual locus names for all genes inside IS elements in the genbank file. The output files should be ok to use in bcbio as the difference is minimal to the outer borders of TEs. @parlar have better knowledge about bacterial genomes than me so he could probably fill in here. 

thanks @lpantano and @roryk

**Comment by lpantano** [comment]
Hi,

I think this has been solved in the latest version, let us know if it happens again.

Thanks!

**Comment by fgvieira** [comment]
Dear all,

I am trying to add a custom genome to `bcbio` and I am getting the same error as @parlar:
```
$ bcbio_setup_genome.py --cores 30 --fasta GCF_000003205.7_Btau_5.0.1_genomic.fna.gz --gff3 --gtf GCF_000003205.7_Btau_5.0.1_genomic.gff.gz --name Btaurus --build Btau --buildversion 5.0.1
[...]
ValueError: Duplicate ID ATP5J
```

The problem seems to be that in the GFF some genes have several annotations:
```
NC_007299.6     Gnomon  gene    10101475        10102134        .       +       .       ID=gene103;Dbxref=BGD:BT20338,GeneID:282690;Name=ATP5J;gbkey=Gene;gene=ATP5J;gene_biotype=protein_coding
NC_007299.6     Gnomon  mRNA    10101475        10102134        .       +       .       ID=rna100;Parent=gene103;Dbxref=GeneID:282690,Genbank:XM_015461927.1,BGD:BT20338;Name=XM_015461927.1;gbkey=mRNA;gene=ATP5J;
NC_007299.6     Gnomon  exon    10101475        10101720        .       +       .       ID=id643;Parent=rna100;Dbxref=GeneID:282690,Genbank:XM_015461927.1,BGD:BT20338;gbkey=mRNA;gene=ATP5J;product=ATP synthase%2
NC_007299.6     Gnomon  exon    10101821        10102134        .       +       .       ID=id644;Parent=rna100;Dbxref=GeneID:282690,Genbank:XM_015461927.1,BGD:BT20338;gbkey=mRNA;gene=ATP5J;product=ATP synthase%2
NC_007299.6     Gnomon  CDS     10101490        10101720        .       +       0       ID=cds74;Parent=rna100;Dbxref=GeneID:282690,Genbank:XP_015317413.1,BGD:BT20338;Name=XP_015317413.1;gbkey=CDS;gene=ATP5J;pro
NC_007299.6     Gnomon  CDS     10101821        10102030        .       +       0       ID=cds74;Parent=rna100;Dbxref=GeneID:282690,Genbank:XP_015317413.1,BGD:BT20338;Name=XP_015317413.1;gbkey=CDS;gene=ATP5J;pro
NC_007299.6     BestRefSeq      gene    10102198        10109514        .       +       .       ID=gene104;Dbxref=BGD:BT20338,GeneID:282690;Name=ATP5J;description=ATP synthase%2C H+ transporting%2C mitochondrial
NC_007299.6     BestRefSeq      mRNA    10102198        10109514        .       +       .       ID=rna101;Parent=gene104;Dbxref=GeneID:282690,Genbank:NM_174717.3,BGD:BT20338;Name=NM_174717.3;gbkey=mRNA;gene=ATP5
NC_007299.6     BestRefSeq      exon    10102198        10102241        .       +       .       ID=id645;Parent=rna101;Dbxref=GeneID:282690,Genbank:NM_174717.3,BGD:BT20338;gbkey=mRNA;gene=ATP5J;product=ATP synth
NC_007299.6     BestRefSeq      exon    10105723        10105893        .       +       .       ID=id646;Parent=rna101;Dbxref=GeneID:282690,Genbank:NM_174717.3,BGD:BT20338;gbkey=mRNA;gene=ATP5J;product=ATP synth
NC_007299.6     BestRefSeq      exon    10108609        10108733        .       +       .       ID=id647;Parent=rna101;Dbxref=GeneID:282690,Genbank:NM_174717.3,BGD:BT20338;gbkey=mRNA;gene=ATP5J;product=ATP synth
NC_007299.6     BestRefSeq      exon    10109338        10109514        .       +       .       ID=id648;Parent=rna101;Dbxref=GeneID:282690,Genbank:NM_174717.3,BGD:BT20338;gbkey=mRNA;gene=ATP5J;product=ATP synth
NC_007299.6     BestRefSeq      CDS     10105730        10105893        .       +       0       ID=cds75;Parent=rna101;Dbxref=GeneID:282690,Genbank:NP_777142.1,BGD:BT20338;Name=NP_777142.1;gbkey=CDS;gene=ATP5J;p
NC_007299.6     BestRefSeq      CDS     10108609        10108733        .       +       1       ID=cds75;Parent=rna101;Dbxref=GeneID:282690,Genbank:NP_777142.1,BGD:BT20338;Name=NP_777142.1;gbkey=CDS;gene=ATP5J;p
NC_007299.6     BestRefSeq      CDS     10109338        10109375        .       +       2       ID=cds75;Parent=rna101;Dbxref=GeneID:282690,Genbank:NP_777142.1,BGD:BT20338;Name=NP_777142.1;gbkey=CDS;gene=ATP5J;p
```
or, in the case of tRNA, there are several copies throughout the genome:
```
NC_007299.6     tRNAscan-SE     gene    962925  962996  .       +       .       ID=gene19;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    962925  962996  .       +       .       ID=rna15;Parent=gene19;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:962958..962960);gbkey=tRNA
NC_007299.6     tRNAscan-SE     exon    962925  962996  .       +       .       ID=id88;Parent=rna15;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:962958..962960);gbkey=tRNA;g
NC_007299.6     tRNAscan-SE     gene    16358699        16358770        .       -       .       ID=gene114;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    16358699        16358770        .       -       .       ID=rna108;Parent=gene114;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:compleme
NC_007299.6     tRNAscan-SE     exon    16358699        16358770        .       -       .       ID=id697;Parent=rna108;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complement
NC_007299.6     tRNAscan-SE     gene    29254475        29254547        .       +       .       ID=gene151;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    29254475        29254547        .       +       .       ID=rna149;Parent=gene151;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:29254508
NC_007299.6     tRNAscan-SE     exon    29254475        29254547        .       +       .       ID=id1146;Parent=rna149;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:29254508.
NC_007299.6     tRNAscan-SE     gene    54292519        54292590        .       +       .       ID=gene292;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    54292519        54292590        .       +       .       ID=rna327;Parent=gene292;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:54292552
NC_007299.6     tRNAscan-SE     exon    54292519        54292590        .       +       .       ID=id3895;Parent=rna327;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:54292552.
NC_007299.6     tRNAscan-SE     gene    57198824        57198895        .       -       .       ID=gene309;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    57198824        57198895        .       -       .       ID=rna341;Parent=gene309;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:compleme
NC_007299.6     tRNAscan-SE     exon    57198824        57198895        .       -       .       ID=id3986;Parent=rna341;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complemen
NC_007299.6     tRNAscan-SE     gene    62038577        62038648        .       -       .       ID=gene354;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    62038577        62038648        .       -       .       ID=rna416;Parent=gene354;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:compleme
NC_007299.6     tRNAscan-SE     exon    62038577        62038648        .       -       .       ID=id4728;Parent=rna416;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complemen
NC_007299.6     tRNAscan-SE     gene    78062025        78062096        .       +       .       ID=gene536;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    78062025        78062096        .       +       .       ID=rna642;Parent=gene536;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:78062058
NC_007299.6     tRNAscan-SE     exon    78062025        78062096        .       +       .       ID=id6836;Parent=rna642;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:78062058.
NC_007299.6     tRNAscan-SE     gene    114504033       114504104       .       -       .       ID=gene843;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    114504033       114504104       .       -       .       ID=rna1003;Parent=gene843;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complem
NC_007299.6     tRNAscan-SE     exon    114504033       114504104       .       -       .       ID=id10379;Parent=rna1003;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complem
NC_007299.6     tRNAscan-SE     gene    131426903       131426975       .       -       .       ID=gene983;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    131426903       131426975       .       -       .       ID=rna1165;Parent=gene983;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complem
NC_007299.6     tRNAscan-SE     exon    131426903       131426975       .       -       .       ID=id11583;Parent=rna1165;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complem
NC_007299.6     tRNAscan-SE     gene    132739512       132739583       .       +       .       ID=gene1013;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007299.6     tRNAscan-SE     tRNA    132739512       132739583       .       +       .       ID=rna1196;Parent=gene1013;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:132739
NC_007299.6     tRNAscan-SE     exon    132739512       132739583       .       +       .       ID=id11882;Parent=rna1196;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:1327395
NC_007300.6     tRNAscan-SE     gene    13453842        13453913        .       -       .       ID=gene1378;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007300.6     tRNAscan-SE     tRNA    13453842        13453913        .       -       .       ID=rna1657;Parent=gene1378;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:comple
NC_007300.6     tRNAscan-SE     exon    13453842        13453913        .       -       .       ID=id17310;Parent=rna1657;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complem
NC_007300.6     tRNAscan-SE     gene    15487091        15487162        .       +       .       ID=gene1396;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007300.6     tRNAscan-SE     tRNA    15487091        15487162        .       +       .       ID=rna1676;Parent=gene1396;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:154871
NC_007300.6     tRNAscan-SE     exon    15487091        15487162        .       +       .       ID=id17504;Parent=rna1676;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:1548712
NC_007300.6     tRNAscan-SE     gene    32900832        32900904        .       +       .       ID=gene1565;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007300.6     tRNAscan-SE     tRNA    32900832        32900904        .       +       .       ID=rna1886;Parent=gene1565;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:329008
NC_007300.6     tRNAscan-SE     exon    32900832        32900904        .       +       .       ID=id20201;Parent=rna1886;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:3290086
NC_007300.6     tRNAscan-SE     gene    37767686        37767757        .       -       .       ID=gene1600;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007300.6     tRNAscan-SE     tRNA    37767686        37767757        .       -       .       ID=rna1928;Parent=gene1600;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:comple
NC_007300.6     tRNAscan-SE     exon    37767686        37767757        .       -       .       ID=id20793;Parent=rna1928;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complem
NC_007300.6     tRNAscan-SE     gene    39204474        39204545        .       +       .       ID=gene1610;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007300.6     tRNAscan-SE     tRNA    39204474        39204545        .       +       .       ID=rna1937;Parent=gene1610;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:392045
NC_007300.6     tRNAscan-SE     exon    39204474        39204545        .       +       .       ID=id20874;Parent=rna1937;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:3920450
NC_007300.6     tRNAscan-SE     gene    56244673        56244744        .       -       .       ID=gene1692;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007300.6     tRNAscan-SE     tRNA    56244673        56244744        .       -       .       ID=rna2028;Parent=gene1692;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:comple
NC_007300.6     tRNAscan-SE     exon    56244673        56244744        .       -       .       ID=id21917;Parent=rna2028;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complem
NC_007300.6     tRNAscan-SE     gene    61262230        61262301        .       +       .       ID=gene1711;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007300.6     tRNAscan-SE     tRNA    61262230        61262301        .       +       .       ID=rna2047;Parent=gene1711;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:612622
NC_007300.6     tRNAscan-SE     exon    61262230        61262301        .       +       .       ID=id22076;Parent=rna2047;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:6126226
NC_007300.6     tRNAscan-SE     gene    72086669        72086740        .       -       .       ID=gene1775;Dbxref=GeneID:100170902;Name=TRNAC-GCA;gbkey=Gene;gene=TRNAC-GCA;gene_biotype=tRNA
NC_007300.6     tRNAscan-SE     tRNA    72086669        72086740        .       -       .       ID=rna2119;Parent=gene1775;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:comple
NC_007300.6     tRNAscan-SE     exon    72086669        72086740        .       -       .       ID=id22734;Parent=rna2119;Dbxref=GeneID:100170902;Note=transfer RNA cysteine (anticodon GCA);anticodon=(pos:complem
[...]
```

As I see it, and according to a previous reply from @parlar, it seems that none of them is in agreement with gff3 specifications.
How should I deal with these cases?

thanks,
