### ISSUE TITLE
wget no-check-certificate error

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1221]
Did wget issues come up before?

```
$ bcbio_nextgen.py upgrade -u development 
/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
--2016-02-10 10:56:02--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com... 199.27.79.133
Connecting to raw.githubusercontent.com|199.27.79.133|:443... connected.
ERROR: certificate common name “www.github.com” doesn’t match requested host name “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’.
Traceback (most recent call last):
  File "/srv/gsfs0/projects/ashley/apps/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 53, in upgrade_bcbio
    anaconda_dir = _update_conda_packages()
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 217, in _update_conda_packages
    subprocess.check_call(["wget", REMOTES["requirements"]])
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt']' returned non-zero exit status 5
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issue. This is fixed in the latest development version but of course that doesn't help too much if you can't upgrade to it. We'll plan to have a new release on Friday that should resolve this, but in the short term you could fix with:
```
/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/bin/pip install --upgrade --no-deps 'git+https://github.com/chapmanb/bcbio-nextgen.git#egg=bcbio-nextgen'
bcbio_nextgen.py upgrade -u development
```
Hope this gets you a clean upgrade.

**Comment by dwaggott** [comment]
Happiness!
