### ISSUE TITLE
Can't install with the Arabidopsis genome. 

### ISSUE THREAD

**Issue by tirohia** [chapmanb/bcbio-nextgen#1228]
bcbio appears to install fine when I use the --nodata option. When I attempt to install the TAIR10 genome however, the installer can't find it. How do I go about pointing bcbio in the right direction? 

`python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local   --genomes TAIR10 --aligners bwa --aligners bowtie2`

results in : 

```
Installing snpEff database athalianaTair10 in /usr/local/share/bcbio/genomes/Athaliana/TAIR10/snpeff
--2016-02-17 14:51:08--  http://downloads.sourceforge.net/project/snpeff/databases/v4_2/snpEff_v4_2_athalianaTair10.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-17 14:51:08 ERROR 404: Not Found.

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6', 'bcbio_nextgen.py')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 724, in run_script
    
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1649, in run_script
    
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 260, in upgrade_bcbio_data
    _upgrade_snpeff_data(s["fabricrc_overrides"]["galaxy_home"], args, remotes)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 320, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "-c", "-O", dl_file, dl_url])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '-c', '-O', 'snpEff_v4_2_athalianaTair10.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v4_2/snpEff_v4_2_athalianaTair10.zip']' returned non-zero exit status 8
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 241, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'TAIR10', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

```

Cheers
Ben.

**Comment by chapmanb** [comment]
Ben;
Apologies about the problem. We updated to a new version of snpEff for genome annotations and that changed the name of the download target. I updated the TAIR10 configuration file, so if you re-run your install command:
```
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --genomes TAIR10 --aligners bwa --aligners bowtie2
```
It should get the latest configuration file and install cleanly now. Please let us know if you run into any other problems.
