### ISSUE TITLE
STAR index error

### ISSUE THREAD

**Issue by druvus** [chapmanb/bcbio-nextgen#1231]
Hi,
I have problem with STAR indexing during a new installation of the lastest stable release. The index creation works if I set '--genomeSAindexNbases' manually to 14. 

Would it be an idea to implement to set the value according to 'min(14,log2(ReferenceLength)/2 - 1)' similar to how the 'genomeChrBinNbits' value is set ? This approach would probalby be preferable for smaller genomes. . 

Snippet from the error.
<pre>
INFO: Preparing genome GRCh37 with index star
[localhost] local: mkdir /scratch/andrsjod/bin/bcbio/data/genomes/Hsapiens/GRCh37/star
[localhost] local: STAR --genomeDir /scratch/andrsjod/bin/bcbio/data/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /scratch/andrsjod/bin/bcbio/data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --genomeChrBinNbits 14 --runMode genomeGenerate --genomeSAindexNbases 18
Feb 17 17:27:51 ..... Started STAR run
Feb 17 17:27:51 ... Starting to generate Genome files
Feb 17 17:29:10 ... starting to sort  Suffix Array. This may take a long time...
Feb 17 17:29:35 ... sorting Suffix Array chunks and saving them to disk...
Feb 17 22:29:13 ... loading chunks from disk, packing SA...
Feb 17 22:30:47 ... Finished generating suffix array
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Fatal error: local() encountered an error (return code 134) while executing 'STAR --genomeDir /scratch/andrsjod/bin/bcbio/data/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /scratch/andrsjod/bin/bcbio/data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --genomeChrBinNbits 14 --runMode genomeGenerate --genomeSAindexNbases 18'

Aborting.
INFO: Genome preparation method raw failed, trying next
INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "/scratch/andrsjod/bin/bcbio/data/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6', 'bcbio_nextgen.py')
  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 724, in run_script

  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1649, in run_script

  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 257, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/scratch/andrsjod/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/scratch/andrsjod/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/scratch/andrsjod/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/scratch/andrsjod/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/scratch/andrsjod/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 348, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/scratch/andrsjod/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 487, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index star for GRCh37 by any method
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 241, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/scratch/andrsjod/conda/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/scratch/andrsjod/bin/bcbio/data/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/scratch/andrsjod/bin/bcbio/tooldir/', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--aligners', 'star', '--data']' returned non-zero exit status 1
</pre>

**Comment by lpantano** [comment]
Hi @druvus,

thanks for the feedback. I can change that in cloudbiolinux, but if you want to do a pull request there so you appear as a contributor, go ahead. If not I can apply the fix

thanks so much!

**Comment by lpantano** [comment]
I set the minimum to 14. hope this fixes the issue. let me know if you find further problems.

thanks @druvus

**Comment by druvus** [comment]
thanks @lpantano !

**Comment by druvus** [comment]
@lpantano, the index builds nicely now but I get segmentation fault running STAR. It disappear if I lower the value to 10. I will keep this closed until I have done some more testing to confirm the issue.

**Comment by lpantano** [comment]
sorry about the issue, is this a bacterial genome? the size of the genome is getting 10 or 14 according to the formula? maybe there is some bug the way I calculate the size.

**Comment by druvus** [comment]
Your formula works when you have multiple contigs. For most bacterias you only have a sequence in the fasta file so I added another critera based on Alex's recommendation and sent a PR to cloudbiolinux.
