### ISSUE TITLE
Installing bcbio using --nodata breaks installation of custom genomes

### ISSUE THREAD

**Issue by druvus** [chapmanb/bcbio-nextgen#1233]
Hi, 
I just tried a clean installation of bcbio with the --nodata setting to avoid downloading unnecessary data for a project based on only non standard organisms. It seems that the installation scripts assumes the existence of some galaxy files in the missing tool-data folder. Confirmed it by installing the human genome first and then installing the custom genome. 

Guess those folders/files needs to be created either during the regular bcbio installation or create them if missing during custom genome installation.

<pre>
[2016-02-17 14:09:01] Run complete: 00:00:00 elapsed
Dumping genome resources to /scratch/andrsjod/bin/bcbio/data/genomes/Ftul/FSC200/seq/FSC200-resources.yaml.
Updating Galaxy .loc files.
Traceback (most recent call last):
  File "/scratch/andrsjod/bin/bcbio/tooldir/bin/bcbio_setup_genome.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6', 'bcbio_setup_genome.py')
  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 724, in run_script
  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1649, in run_script
  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6-py2.7.egg-info/scripts/bcbio_setup_genome.py", line 276, in <module>
    loc.update_loc_file(galaxy_base, index, args.build, index_file)
  File "/scratch/andrsjod/bin/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/galaxy/loc.py", line 87, in update_loc_file
    with open(loc_file, "a") as out_handle:
IOError: [Errno 2] No such file or directory: '/scratch/andrsjod/bin/bcbio/data/galaxy/tool-data/sam_fa_indices.loc'
</pre>

**Comment by chapmanb** [comment]
Andreas;
The non-standard organism support does assume an initial data install. Your best bet is to use the installer `--data` target but only install a small genome, say: `--genomes phix`. That should create all the necessary file structure without much overhead.

We're also working right now on making the install more configurable so you can easily skip some of the longer downloads if you don't need them, like VEP or the variation supporting files. Hope the small genome workaround solves your problem in the short term.

**Comment by druvus** [comment]
Thanks Brad, 
the phiX solution is a prefect workaround for me.
