### ISSUE TITLE
Error running lumpy - gawk is missing

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1236]
Hello,
I encountered the following error when running lumpy using aws cluster.
I checked and gawk is indeed missing in the docker image.

/usr/local/share/bcbio-nextgen/anaconda/bin/lumpyexpress: line 364: gawk: command not found
head: write error: Broken pipe
head: write error
sambamba-view:  (Broken pipe)
' returned non-zero exit status 127
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 173, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 121, in run
    for xs in to_process.values()))
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 187, in detect_sv
    return structural.detect_sv(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 140, in detect_sv
    for svdata in caller_fn(items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/structural/lumpy.py", line 125, in run
    lumpy_vcf, exclude_file = _run_lumpy(full_bams, sr_bams, disc_bams, work_dir, items)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/structural/lumpy.py", line 45, in _run_lumpy
    do.run(cmd.format(**locals()), "lumpyexpress", items[0])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/usr/local/share/bcbio-nextgen/anaconda/bin:$PATH && lumpyexpress -v -B /mnt/work/prealign/d7799_2_analysis/d7799_2_analysis-ready-dedup.bam -S /mnt/work/prealign/d7799_2_analysis/d7799_2_analysis-ready-sr.bam -D /mnt/work/prealign/d7799_2_analysis/d7799_2_analysis-ready-disc.bam -x /mnt/work/structural/d7799_2_analysis/lumpy/d7799_2_analysis-ready-d7799_2-svs-exclude.bed -T /mnt/work/tx/tmpVv8NL0 -o /mnt/work/structural/d7799_2_analysis/lumpy/tx/tmp0Bn7cW/d7799_2_analysis-ready-d7799_2-svs.vcf
Sourcing executables from /usr/local/share/bcbio-nextgen/anaconda/bin/lumpyexpress.config ...

Checking for required python modules (/usr/local/share/bcbio-nextgen/anaconda/bin/python)...

    create temporary directory
Calculating insert distributions... 
/usr/local/share/bcbio-nextgen/anaconda/bin/lumpyexpress: line 364: gawk: command not found
head: write error: Broken pipe
head: write error
sambamba-view:  (Broken pipe)
' returned non-zero exit status 127
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the heads up. I'm working on adding gawk as a conda dependency to lumpy and then will re-prepare the Docker container to resolve this. I'll post back when that's finished but as a short term fix you could install gawk in the container and save it and hopefully things will run cleanly for you. Thanks much.

**Comment by chapmanb** [comment]
I've re-built the docker container with gawk present, so if you do `docker pull bcbio/bcbio` it should find the conda installed version and lumpyexpress should work correctly. Thanks so much for reporting this and the patience while it got updated.

**Comment by mosheein** [comment]
Thank you Brad
