### ISSUE TITLE
Problem with GATK?

### ISSUE THREAD

**Issue by tombair** [chapmanb/bcbio-nextgen#1258]
This is probably a user error as I am very new to bcbio. For a couple of different projects I end up hitting this error

```
Traceback (most recent call last):
  File "/Shared/Bioinformatics/data/bcbio/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/Shared/Bioinformatics/data/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 147, in variant2pipeline
    samples = region.parallel_prep_region(samples, run_parallel)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 139, in parallel_prep_region
    "piped_bamprep", _add_combine_info, file_key, ["config"])
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 812, in __call__
    self.retrieve()
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 749, in retrieve
    exception = exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```

The last command run was a java -jar GenomeAnalysisTK.jar. I manually run that command and get no errors. 

Any ideas on how to debug?

Thanks

**Comment by chapmanb** [comment]
Tom;
Thanks much for the report. The `___init__() takes at least 3 arguments` is a bit confusing error as that's a general error message spit out during parallel runs and is not diagnostic of the actual problem. We can see from this something happened during the bamprep step but not the actual error which is somewhere higher up in the logs. Apologies, errors propegated on multicore runs can get messy.

The best ways to debug so we can help more are to run single core (`bcbio_nextgen -n 1 <your inputs>`) or look in `log/bcbio-nextgen.log` for a more diagnostic message. If you could post information from those here we could help more with debugging. Thanks much.

**Comment by tombair** [comment]
That was helpful, it was a user error, looking higher up in the logs showed a disk full error, which was the problem. Sorry, I was focused on the error message and didn't page up a couple to see the true source.
