### ISSUE TITLE
RNAseq pipeline example fails in QC step

### ISSUE THREAD

**Issue by lfaller** [chapmanb/bcbio-nextgen#1259]
Hi all,

I am just getting started with bcbio-nextgen, so please bear with me.

I followed the steps to run the example RNAseq pipeline and it seems to fail in the QC step:

```
...
[2016-03-03T17:11Z] 91100000 reads processed.
[2016-03-03T17:12Z] 91200000 reads processed.
[2016-03-03T17:20Z] Resource requests: gatk; memory: 3.50; cores: 1
[2016-03-03T17:20Z] Configuring 6 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2016-03-03T17:20Z] Timing: RNA-seq variant calling
[2016-03-03T17:20Z] multiprocessing: run_rnaseq_variant_calling
[2016-03-03T17:20Z] multiprocessing: run_rnaseq_joint_genotyping
[2016-03-03T17:20Z] Resource requests: fastqc, gatk, kraken, qualimap, samtools; memory: 2.00, 3.50, 2.00, 8.00, 2.00; cores: 16, 1, 4, 1, 16
[2016-03-03T17:20Z] Configuring 1 jobs to run, using 4 cores each with 34.4g of memory reserved for each job
[2016-03-03T17:20Z] Timing: quality control
[2016-03-03T17:20Z] multiprocessing: pipeline_summary
[2016-03-03T17:20Z] Generating summary files: UHRR_rep1
[2016-03-03T17:20Z] Downsample BAM file: UHRR_rep1.bam
[2016-03-03T17:22Z] FastQC: UHRR_rep1
[2016-03-03T17:22Z] Temp directory '/home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/tmpgLFAF8' doesn't exist, or can't be written to
[2016-03-03T17:22Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/lfaller/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/lfaller/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command '/home/lfaller/local/bin/fastqc -d /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/tmpgLFAF8 -t 4 --extract -o /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/tmpgLFAF8 -f bam /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/align/UHRR_rep1/1_2016-02-25_seqc_tophat/UHRR_rep1-downsample.bam
Temp directory '/home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/tmpgLFAF8' doesn't exist, or can't be written to
' returned non-zero exit status 2
```

I double-checked and this temp directory really doesn't exist, but the parent dir does:

``` bash
$ ls -la /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx
total 0
drwxrwxr-x 2 nobody nogroup  6 Mar  3 12:22 .
drwxrwxr-x 3 nobody nogroup 15 Mar  3 12:22 ..

```

I appreciate any suggestions on how to fix this!

Thanks,
~Lina

**Comment by roryk** [comment]
Hi Lina,

Sorry for the troubles. The `nobody` owner and `nogroup` group on the tx directory looks a little bit odd, is that expected on your system? 

This makes me think there was a hiccup with the filesystem somehow when it created the `tx` dir and now you don't have permission to write to it. We've seen troubles like this on some of the parallel filesystems like lustre, what filesystem is running on the machine? 

Do the other directories and files have those same `nobody` and `nogroup` owners?

If not I would try deleting the `tx` directory and restarting the run. Hopefully this was just a temporary problem with the filesystem and won't recur. Hope that helps some. Let us know what you find out.

**Comment by lfaller** [comment]
Hi Rory,

Thanks for the quick reply!

I think the `nobody` owner and `nogroup` group should be fine, the whole main directory has these permissions as well (see below) and the script seemed to get this far... but just in case, I ran `chmod 777 -R` on the `seqc-test/` directory.

If I restart the script, will it pick up where it left off or will it redo things?

Best,
~Lina

```
$ cd ~/bioinfohd1/playground/rna_seq_example/seqc-test/seqc
$ ls -la
total 4
drwxrwxrwx  5 nobody nogroup   42 Feb 25 07:55 .
drwxrwxrwx  4 nobody nogroup   52 Feb 25 07:52 ..
drwxrwxrwx  2 nobody nogroup   62 Feb 25 07:52 config
drwxrwxrwx  2 nobody nogroup    6 Feb 25 07:55 final
drwxrwxrwx 13 nobody nogroup 4096 Mar  3 12:20 work

$ ls -la work
total 24
drwxrwxrwx 13 nobody nogroup 4096 Mar  3 12:20 .
drwxrwxrwx  5 nobody nogroup   42 Feb 25 07:55 ..
drwxrwxrwx  8 nobody nogroup  102 Mar  1 13:46 align
drwxrwxrwx  2 nobody nogroup 4096 Mar  3 12:20 checkpoints_parallel
drwxrwxrwx  3 nobody nogroup 4096 Mar  3 12:12 dexseq
drwxrwxrwx  3 nobody nogroup 4096 Mar  3 12:20 htseq-count
drwxrwxrwx  3 nobody nogroup   17 Feb 25 07:55 inputs
drwxrwxrwx  2 nobody nogroup   93 Feb 25 07:55 log
drwxrwxrwx  2 nobody nogroup   25 Feb 25 07:55 provenance
drwxrwxrwx  3 nobody nogroup   22 Mar  3 12:20 qc
drwxrwxrwx  9 nobody nogroup 4096 Mar  2 19:15 sailfish
drwxrwxrwx  3 nobody nogroup 4096 Feb 25 17:01 trimmed
drwxrwxrwx  2 nobody nogroup    6 Mar  3 12:22 tx
```

**Comment by roryk** [comment]
Hi Lina,

Gotcha. Yup, it will pick up where it left off and you won't have any problems with half-completed files or anything like that.

**Comment by lfaller** [comment]
Unfortunately, it got caught at the same step:

```
...
[2016-03-06T16:31Z] run local -- checkpoint passed: rnaseq-variation
[2016-03-06T16:31Z] Timing: RNA-seq variant calling
[2016-03-06T16:31Z] multiprocessing: run_rnaseq_variant_calling
[2016-03-06T16:31Z] multiprocessing: run_rnaseq_joint_genotyping
[2016-03-06T16:31Z] Resource requests: fastqc, gatk, kraken, qualimap, samtools; memory: 2.00, 3.50, 2.00, 8.00, 2.00; cores: 16, 1, 4, 1, 16
[2016-03-06T16:31Z] Configuring 1 jobs to run, using 4 cores each with 34.4g of memory reserved for each job
[2016-03-06T16:31Z] Timing: quality control
[2016-03-06T16:31Z] multiprocessing: pipeline_summary
[2016-03-06T16:31Z] Generating summary files: UHRR_rep1
[2016-03-06T16:31Z] FastQC: UHRR_rep1
[2016-03-06T16:31Z] Temp directory '/home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/tmpfcdYX5' doesn't exist, or can't be written to
[2016-03-06T16:31Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/lfaller/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/lfaller/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command '/home/lfaller/local/bin/fastqc -d /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/tmpfcdYX5 -t 4 --extract -o /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/tmpfcdYX5 -f bam /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/align/UHRR_rep1/1_2016-02-25_seqc_tophat/UHRR_rep1-downsample.bam
Temp directory '/home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/tmpfcdYX5' doesn't exist, or can't be written to
' returned non-zero exit status 2
```

But this time, this directory should really be accessible to everyone:

```
$ ls -la /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/qc/UHRR_rep1/tx/
total 0
drwxrwxrwx 2 nobody nogroup  6 Mar  6 11:32 .
drwxrwxrwx 3 nobody nogroup 15 Mar  3 12:22 ..
```

I also noticed that the temp dir name is different now, so I can't manually create it and hope that it runs the next time.

Rory, if you have any other suggestions, I appreciate it!

**Comment by roryk** [comment]
Gotcha-- I don't get why this might be happening. @chapmanb do you have any ideas?

**Comment by lpantano** [comment]
Hi Lina, 

could you create a file there or directory? i guess yes, but just checking.

I would run in a single core locally, maybe in an interactive job. Like bcbio_nextgen.py config_file.yam and see what happens. Just trying to make sure this error reproduce always even in the simplest scenario.

**Comment by chapmanb** [comment]
Lina, Rory and Lorena;
Sorry about the issues and thanks for all the help debugging this. I'm also not sure what is going on -- that temporary directory gets created as part of the fastqc preparation process. It gets removed on errors or completion, so you won't see if afterward.

What type of filesystem are you running on that has nobody:nogroup for permissions? I wonder if we're running into some kind of depth issue with the filesystem. You could add a `resources` section to the top level of your sample YAML file to tell bcbio to create these temporary files in a different location:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#temporary-directory

That might help work around the problem. Hope one of these ideas helps.

**Comment by lfaller** [comment]
Hi all,

Brad's suggestion seems to work! Or at least the pipeline was able to move beyond the FastQC step. Explicitly adding a tmp directory under the resources section in ```seqc-test/seqc/config/seqc.yaml``` seems to have fixed it.

Thanks a bunch for helping out!

In case someone runs into this issue in the future, my Linux distro is Ubuntu 12.04.5 LTS (the biolinux version). I'm not sure why everything seems to run under nobody/nogroup stuff, but this has been the first issue I've had with this specific user/group.

Best,
~Lina
