### ISSUE TITLE
/scratch dir permission denied

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1262]
Hi!

We seem to have some issues when defining a scratch dir, as in the [docs](https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#temporary-directory).

I only get a permission denied error:

<pre>
Traceback (most recent call last):
  File "/data/t-tcga/esebesty/bcbio/tool/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/data/t-tcga/esebesty/bcbio/tool/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 47, in run_main
    fc_dir, run_info_yaml)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 79, in _run_toplevel
    with tx_tmpdir(config) as tmpdir:
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 39, in tx_tmpdir
    config_tmpdir = utils.safe_makedir(os.path.expandvars(config_tmpdir))
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 183, in safe_makedir
    os.makedirs(dname)
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/scratch'
</pre>

I have towo compute nodes with /scratch set up, but no /scratch on the submission node, where I'm running the bcbio_nextgen.py command. Can this be the problem?

**Comment by razZ0r** [comment]
Hmm, submitting from one of the compute nodes solves the problem. Some clarification in the docs would be nice about this.

**Comment by chapmanb** [comment]
Endre;
Thanks for the heads up on the issue. We should avoid trying to use the configured temporary directory at the top level for non-local runs to avoid this. I pushed a fix that I hope will resolve this and only use the configured temporary directory for compute work so you can specify compute-specific temporary directories. Hope this fixes it for you, and thanks again for the report.
