### ISSUE TITLE
File system error during squaring off/backfilling

### ISSUE THREAD

**Issue by rjsicko** [chapmanb/bcbio-nextgen#1265]
I've been using bcbio to get from fastq -> individual sample vcfs. I'm to the point in the bcbio pipeline of squaring off/backfilling and I'm getting the error below. I'm using a local tmp dir (/home/rsicko/tmp/bctemp) and an attached drive for storing all the project files. 

**Terminal output**
````
[2016-03-10T12:40Z] run local -- checkpoint passed: full
[2016-03-10T12:40Z] Timing: alignment post-processing
[2016-03-10T12:40Z] multiprocessing: piped_bamprep
[2016-03-10T12:41Z] Timing: variant calling
[2016-03-10T12:42Z] multiprocessing: variantcall_sample
[2016-03-10T12:43Z] multiprocessing: concat_variant_files
[2016-03-10T12:43Z] Resource requests: bamtools, bcbio-variation-recall, bcbio_variation, fastqc, gatk, gemini, qsignature, samtools; memory: 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00; cores: 8, 8, 1, 8, 1, 8, 8, 8
[2016-03-10T12:43Z] Configuring 1 jobs to run, using 7 cores each with 38.6g of memory reserved for each job
[2016-03-10T12:43Z] Timing: joint squaring off/backfilling
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 159, in variant2pipeline
    samples = joint.square_off(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 94, in square_off
    "vrn_file", ["region", "sam_ref", "config"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 31, in grouped_parallel_split_combine
    split_outfile_i)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 126, in _get_split_tasks
    out_final, out_parts = split_fn(data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 64, in _split_by_callable_region
    os.symlink(os.path.join(os.pardir, "inprep"), region_prep_dir)
OSError: [Errno 30] Read-only file system
````
**Portion of project.yaml**
````
details:
- algorithm:
    aligner: bwa
    effects: vep
    ensemble:
      classifier-params:
        type: svm
      classifiers:
        balance:
        - AD
        - FS
        - Entropy
        calling:
        - ReadPosEndDist
        - PL
        - PLratio
        - Entropy
        - NBQ
      format-filters:
      - DP < 4
      trusted-pct: 0.5
    jointcaller:
    - gatk-haplotype-joint
    - freebayes-joint
    - platypus-joint
    - samtools-joint
    mark_duplicates: true
    mixup_check: qsignature
    phasing: gatk
    realign: false
    recalibrate: gatk
    remove_lcr: true
    variant_regions: /media/sf_BigShare/Project_Tsai_Project_025/agilent_files/S04380219_Covered_noChr.bed
    variantcaller:
    - gatk-haplotype
    - freebayes
    - platypus
    - samtools
  analysis: variant2
  description: A06551
  files:
  - /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R1.fastq.gz
  - /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: batch1
    phenotype: affected
    sex: male
...
````

**Comment by chapmanb** [comment]
Sorry about the problems. It looks like bcbio is not allowed to make symlinks on your `/media/sf_BigShare` filesystem since Python is complaining about it being a read-only filesystem.

Practically, how many samples are you calling together? If you're doing less than 100 you don't need joint calling and can remove the `jointcaller` specification and use batch calling directly. I'm not sure if this will solve all the filesystem issues but will at least make your pipeline less complicated. Hope this helps.

**Comment by rjsicko** [comment]
Ah, I figured it was symlinks killing me again! I've run into issues before with symlinks on virtualbox shared folders, which is how I'm attaching the shared drive. Thanks for pointing out jointcalling isn't necessary, I'll remove that from the yaml and see if that gets me going again.

**Comment by rjsicko** [comment]
Hi Brad, 
Quick question. After removing the joint caller block from the yaml, bcbio is going again. However, gatk-haplotype is running a single interval at a time (with only 1 core processing). I'm wondering if I can process 8 intervals and use all cores? It doesn't seem like memory is limiting this since only 2G is being used by the single process. I specified ````-n 8```` in the command line and tried adding ````cores: 8```` to the gatk and gatk-haplotype sections of the system.yaml

**Comment by chapmanb** [comment]
For the rerun, try removing the `checkpoints_parallel` directory. That tells bcbio some blocks of work are complete so it doesn't try to parallelize them again. If you remove that and re-run it should hopefully work as expected. Hope this does it for you.

**Comment by rjsicko** [comment]
sorry, I should have thought of that! It worked, back to parallel processing, thank you
