### ISSUE TITLE
missing packages cannot be installed 

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1268]
Hi,
I tried the install bcbio with  the command below.

```
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local   --genomes GRCh37
```
My bcbio installation stuck at the step where it says there are specific packages are missing for osx-64 channels.

As I understood from the outputs these are the packages. Also after it prints the package names it prints a traceback error too. 

How can I solve this problem ? Also, I use pip for downloading python packages. however since bcbio requires anaconda most of my packages are duplicated right now. Would that cause a problem in my future ? 

Thanks in advance!

Best,

Tunc.

```
Fatal error: local() encountered an error (return code 1) while executing '/usr/local/share/bcbio/anaconda/bin/conda install -y -c bioconda -c r age-metasv bamtools bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.24.0 bio-vcf biobambam bowtie2 bwa bwakit cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt delly fastqc freebayes=1.0.2 gatk-framework gemini glpk grabix hall-lab-svtools hisat2 hmmlearn htseq htslib impute2 kraken lofreq lumpy-sv macs2 manta metasv mirdeep2 moreutils multiqc novoalign oncofuse optitype parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap razers3 rtg-tools sailfish sambamba samblaster samtools scalpel seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner snpeff spades star stringtie subread svtyper tdrmapper theta2 tophat ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig vardict vardict-java variant-effect-predictor variantbam varscan vawk vcflib viennarna vt wham awscli p7zip s3gof3r perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--data']' returned non-zero exit status 1
```

Edit : When I tried to rerun the install command I get the following error.
```
Tuncs-MacBook-Pro:bcbio morova$ python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local   --genomes GRCh37
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda)
  File "bcbio_nextgen_install.py", line 70, in install_conda_pkgs
    subprocess.check_call(["wget", "--no-check-certificate", REMOTES["requirements"]])
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', 'https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt']' returned non-zero exit status -5
```

**Comment by roryk** [comment]
Hi @mortunco,

Sorry-- we don't support installation on OSX; the code itself runs fine but there are a bunch of tools that don't build properly on OSX.

**Comment by mortunco** [comment]
Dear @roryk 
Thank you for fast your response. Since I can't get it working in macosx, Is there specific step that I should do for removing the packages and tools that installer downloaded? Will removing folders be enough ?

T.

**Comment by roryk** [comment]
Hi @mortunco,

Yup-- just removing the folders will be enough. The installation is walled off from everything else, so nuking what is in the tooldir and in /usr/share/bcbio will remove what was installed.

http://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html has a blurb about what to do if you want to run on OSX. Hope that helps get you going.
