### ISSUE TITLE
Python ImportError  (undefined symbol: PyFPE_jbuf)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1283]
Hi, there.

When I try to the test analysis using bcbio, I got the error in below.

please check this issue.

I think this issue related to this article (https://datastax-oss.atlassian.net/browse/PYTHON-410)

# Ubuntu 14.04.4 LTS \n \l
# Linux version 3.19.0-51-generic (buildd@lgw01-51) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #57~14.04.1-Ubuntu SMP Fri Feb 19 14:36:55 UTC 2016

```
$ bcbio_nextgen.py ../config/NA12878-illumina.yaml -n 48
Traceback (most recent call last):
  File "/BioTools/bcbio/usr/local/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6', 'bcbio_nextgen.py')
  File "/BioTools/bcbio/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/BioTools/bcbio/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script

  File "/BioTools/bcbio/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6-py2.7.egg-info/scripts/bcbio_nextgen.py", line 35, in <module>
    from bcbio.distributed import runfn, clargs
  File "/BioTools/bcbio/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 14, in <module>
    from bcbio.distributed import multitasks
  File "/BioTools/bcbio/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 11, in <module>
    from bcbio.pipeline import (archive, disambiguate, qcsummary, region, sample,
  File "/BioTools/bcbio/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 8, in <module>
    from bcbio.variation import effects, germline, prioritize
  File "/BioTools/bcbio/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/germline.py", line 10, in <module>
    import cyvcf2
  File "/home/brandon/.local/lib/python2.7/site-packages/cyvcf2/__init__.py", line 2, in <module>
    from .cyvcf2 import VCF, Variant, Writer, r_ as r_unphased
ImportError: /home/brandon/.local/lib/python2.7/site-packages/cyvcf2/cyvcf2.so: undefined symbol: PyFPE_jbuf
```

**Comment by chapmanb** [comment]
Hyunmin;
Sorry about the issue. It looks like there is an incompatible cyvcf2 installation in:
```
/home/brandon/.local/lib/python2.7/site-packages/cyvcf2
```
That is conflicting with the bcbio installation. `bcbio_nextgen.py` is supposed to ignore this local site library (it runs python with `-Es`) but does not seem to be doing so on your setup. You could remove the cyvcf2 directory above and that will hopefully resolve the issue. Hope this helps.

**Comment by hmkim** [comment]
Nice!  I solved this problem via your comment.

Thank you so much!

**Comment by kspham** [comment]
we got a similar problem, but not resolved yet... 

Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

Installing data and third party dependencies
Traceback (most recent call last):
  File "/raid/sp/haprin/bcbio/anaconda/bin/bcbio_nextgen.py", line 37, in <module>
    from bcbio import install, utils, workflow
  File "/raid/sp/haprin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/workflow/__init__.py", line 3, in <module>
    from bcbio.workflow import xprize, stormseq, template
  File "/raid/sp/haprin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/workflow/stormseq.py", line 11, in <module>
    from bcbio.upload import s3
  File "/raid/sp/haprin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 10, in <module>
    from bcbio.upload import shared, filesystem, galaxy, s3, irods
  File "/raid/sp/haprin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/galaxy.py", line 16, in <module>
    from bcbio.pipeline import qcsummary
  File "/raid/sp/haprin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 10, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 31, in <module>
    "extensions first.".format(module))
ImportError: C extension: /usr/local/lib/python2.7/dist-packages/pandas/hashtable.so: undefined symbol: PyFPE_jbuf not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 287, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/raid/sp/haprin/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/raid/sp/haprin/tool', '--genomes', 'hg38', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by roryk** [comment]
Hi Son, it looks like you have another version of the pandas library leaking into your path here:

```
/usr/local/lib/python2.7/dist-packages/pandas/
```

That is getting into your python path somehow. Often culprits are PYTHONPATH or PYTHONHOME being set.
