### ISSUE TITLE
GEMINI and CADD error

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1284]
I believe this issue is new, forgive me if it is not, I could not immediately find any issue matching some of the keywords I tried. And my title is probably a poor description, but Im not sure where to begin digesting the message. Also I apologize that it is quite long and I am just dumping the error messages here.

```
...
[2016-03-22T20:06Z] multiprocessing: finalize_sv
[2016-03-22T20:06Z] Timing: structural variation ensemble
[2016-03-22T20:06Z] Timing: structural variation validation
[2016-03-22T20:06Z] multiprocessing: validate_sv
[2016-03-22T20:06Z] Timing: heterogeneity
[2016-03-22T20:06Z] Timing: population database
[2016-03-22T20:06Z] multiprocessing: prep_gemini_db
[2016-03-22T20:06Z] Create gemini database for /home/bwubb/NGS/NCI_Exome/data/work/gemini/Batch3-gatk-haplotype-joint-decompose-effects.vcf.gz : TC-5196-1001-A
[2016-03-22T20:06Z] CADD scores are being loaded (to skip use:--skip-cadd).
[2016-03-22T20:08Z] Traceback (most recent call last):
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-tools/bin/gemini", line 6, in <module>
[2016-03-22T20:08Z]     gemini.gemini_main.main()
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
[2016-03-22T20:08Z]     args.func(parser, args)
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
[2016-03-22T20:08Z]     gemini_load.load(parser, args)
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
[2016-03-22T20:08Z]     load_singlecore(args)
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
[2016-03-22T20:08Z]     gemini_loader.populate_from_vcf()
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 203, in populate_from_vcf
[2016-03-22T20:08Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 466, in _prepare_variation
[2016-03-22T20:08Z]     top_impact = geneimpacts.Effect.top_severity(impacts)
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 295, in top_severity
[2016-03-22T20:08Z]     effects = sorted(effects)
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/functools.py", line 60, in <lambda>
[2016-03-22T20:08Z]     ('__lt__', lambda self, other: self <= other and not self == other),
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 262, in __le__
[2016-03-22T20:08Z]     if self.severity != other.severity:
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 345, in severity
[2016-03-22T20:08Z]     v = max(lookup[sev[csq]] for csq in self.consequences)
[2016-03-22T20:08Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 345, in <genexpr>
[2016-03-22T20:08Z]     v = max(lookup[sev[csq]] for csq in self.consequences)
[2016-03-22T20:08Z] KeyError: 'protein_protein_contact'
[2016-03-22T20:08Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/bwubb/bcbio-tools/bin/gemini  load  --passonly --skip-gerp-bp  -v /home/bwubb/NGS/NCI_Exome/data/work/gemini/Batch3-gatk-haplotype-joint-decompose-effects.vcf.gz -t snpEff --cores 1 --tempdir /home/bwubb/NGS/NCI_Exome/data/work/gemini/tx/tmpp7ERPz /home/bwubb/NGS/NCI_Exome/data/work/gemini/tx/tmpp7ERPz/Batch3-gatk-haplotype-joint.db
CADD scores are being loaded (to skip use:--skip-cadd).
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
    load_singlecore(args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
    gemini_loader.populate_from_vcf()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 203, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 466, in _prepare_variation
    top_impact = geneimpacts.Effect.top_severity(impacts)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 295, in top_severity
    effects = sorted(effects)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/functools.py", line 60, in <lambda>
    ('__lt__', lambda self, other: self <= other and not self == other),
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 262, in __le__
    if self.severity != other.severity:
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 345, in severity
    v = max(lookup[sev[csq]] for csq in self.consequences)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 345, in <genexpr>
    v = max(lookup[sev[csq]] for csq in self.consequences)
KeyError: 'protein_protein_contact'
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 181, in variant2pipeline
    samples = population.prep_db_parallel(samples, run_parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 281, in prep_db_parallel
    output = parallel_fn("prep_gemini_db", to_process)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 223, in prep_gemini_db
    return population.prep_gemini_db(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 36, in prep_gemini_db
    gemini_db = create_gemini_db(gemini_vcf, data, gemini_db, ped_file)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 79, in create_gemini_db
    do.run(cmd, "Create gemini database for %s" % gemini_vcf, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/bwubb/bcbio-tools/bin/gemini  load  --passonly --skip-gerp-bp  -v /home/bwubb/NGS/NCI_Exome/data/work/gemini/Batch3-gatk-haplotype-joint-decompose-effects.vcf.gz -t snpEff --cores 1 --tempdir /home/bwubb/NGS/NCI_Exome/data/work/gemini/tx/tmpp7ERPz /home/bwubb/NGS/NCI_Exome/data/work/gemini/tx/tmpp7ERPz/Batch3-gatk-haplotype-joint.db
CADD scores are being loaded (to skip use:--skip-cadd).
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
    load_singlecore(args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
    gemini_loader.populate_from_vcf()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 203, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 466, in _prepare_variation
    top_impact = geneimpacts.Effect.top_severity(impacts)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 295, in top_severity
    effects = sorted(effects)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/functools.py", line 60, in <lambda>
    ('__lt__', lambda self, other: self <= other and not self == other),
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 262, in __le__
    if self.severity != other.severity:
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 345, in severity
    v = max(lookup[sev[csq]] for csq in self.consequences)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 345, in <genexpr>
    v = max(lookup[sev[csq]] for csq in self.consequences)
KeyError: 'protein_protein_contact'
' returned non-zero exit status 1
```

Out of five sample batches for this project, only one of them has this error. bcbio should be up to date unless I need to update gemini and cadd specifically. Please advise. Thank you!

**Comment by chapmanb** [comment]
Brad;
Sorry about the issue. This is a bug we fixed a couple of weeks back in geneimpacts (which is part of GEMINI):

https://github.com/brentp/geneimpacts/commit/d31247da892643dc1c51874a98762c4750e8a9a0

It looks like you might need to update to get the fix. If you only want to get the fix to this you can do:
```
/home/bwubb/bcbio-nextgen/anaconda/bin/conda install -c bioconda geneimpacts
```
and you should get the fixed version. Then you can re-run in place and it should hopefully finish cleanly. Hope this gets your analysis finalized.
