### ISSUE TITLE
Could not find directory in config for gatk

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1288]
Running bcbio on the same cluster as before, and the base recalibration step dies with the following:

<pre>
[2016-03-24T09:40Z] Assigned coverage as 'genome' with 89.8% genome coverage and 0.0% offtarget coverage
[2016-03-24T09:40Z] Recalibrating ['', 'HCC1143_NORMAL'] with GATK
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/tool/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/tool/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 130, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 55, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 194, in postprocess_alignment
    data = _recal_no_markduplicates(data)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 200, in _recal_no_markduplicates
    data = recalibrate.prep_recal(data)[0][0]
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 41, in prep_recal
    broad_runner = broad.runner_from_config(config)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 411, in runner_from_config
    config_utils.get_program(program, config, "dir"),
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 186, in get_program
    return _get_program_dir(name, pconfig)
  File "/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 237, in _get_program_dir
    raise ValueError("Could not find directory in config for %s" % name)
ValueError: Could not find directory in config for gatk
</pre>

GATK is installed with the `--toolplus` option, is in my path, but still not found somehow.

<pre>
[esebesty@node012 ~/scratch/bcbio_run/single-pair-cineca/work]$ which gatk-framework
/pico/home/userexternal/esebesty/work/bcbio-20160314/bcbio/tool/bin/gatk-framework
</pre>

**Comment by chapmanb** [comment]
Endre;
Sorry for the problems and confusion with GATK. `gatk-framework` is the free tools in GATK that we package up to make them easier to use, so is separate from the custom installed GATK you need here with the academic-only tools like recalibration.

Practically, the GATK install you need happens through `--toolpus`, so something has apparently gone wrong there so that bcbio can't find the GATK jar. The jar should be present in:
```
/path/to/bcbio/toolplus/gatk
```
and the specification of this directory in:
```
/path/to/bcbio/galaxy/bcbio_system.yaml
```
Do those look correct? If not, re-running with `--toolplus` might be a good approach. Happy to help debug more if this doesn't resolve it.

**Comment by razZ0r** [comment]
Yes, these seem to be correct. `GenomeAnalysisTK.jar` is in 

<pre>
/pico/work/try16_EMUTPRED/bcbio-20160314/bcbio/data/toolplus/gatk/3.4-46-gbc02625
</pre>

and this path is present in the yaml file.

**Comment by razZ0r** [comment]
Turns out my yaml config was wrong. I used

<pre>
bcbio_nextgen.py resources.yaml samples.yaml -t local -n 8
</pre>

and in the `resources.yaml` file I only had 

<pre>
resources:
  default:
    cores: 8
</pre>

but this lead to all other config options being empty, so GATK was not found. I guess I need to specify everything myself in the `resources.yaml` file or modify the `bcbio_system.yaml` file.

**Comment by chapmanb** [comment]
Endre;
Thanks for following up on this and identifying the underlying problem. That's exactly right, if you use a different resources.yaml file is don't add to the system configuration but uses that instead. If you want to change certain parameters for a run you can add a resources block into your sample YAML file:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-or-run-specific-resources

Hope this gets things running cleanly for you.
