### ISSUE TITLE
bcbio vardict java error : Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1300]
Hi,

I have been running the process below for almost 3 days. It went without a problem until this step. I did not change anythin in the configuration related to mutation calling but I dont know why do I get this error?

```
[2016-04-02T01:59Z] Genotyping with VarDict: Inference
[2016-04-02T02:07Z] tabix index syn3-14_35012924_51408901-raw.vcf.gz
[2016-04-02T02:07Z] Annotate with dbSNP
[2016-04-02T02:12Z] Sort BED file : deneme1_tumor
[2016-04-02T02:12Z] Remove high depth regions
[2016-04-02T02:12Z] Genotyping with VarDict: Inference
[2016-04-02T02:13Z] tabix index syn3-15_0_20219201-raw.vcf.gz
[2016-04-02T02:13Z] Annotate with dbSNP
[2016-04-02T02:13Z] tabix index syn3-14_101336909_107349540-raw.vcf.gz
[2016-04-02T02:13Z] Annotate with dbSNP
[2016-04-02T02:14Z] Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[2016-04-02T02:14Z] 	at java.lang.String.charAt(String.java:658)
[2016-04-02T02:14Z] 	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1896)
[2016-04-02T02:14Z] 	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2552)
[2016-04-02T02:14Z] 	at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:354)
[2016-04-02T02:14Z] 	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:249)
[2016-04-02T02:14Z] 	at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
[2016-04-02T02:14Z] 	at com.astrazeneca.vardict.Main.run(Main.java:134)
[2016-04-02T02:14Z] 	at com.astrazeneca.vardict.Main.main(Main.java:25)
[2016-04-02T02:18Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/usr/local/share/bcbio/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3000m -XX:+UseSerialGC -Djava.io.tmpdir=/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/tx/tmpMW1qbw' && vardict-java -G /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N deneme1_tumor -b "/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/prealign/deneme1_tumor/tumor.bam|/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/prealign/denem1_normal/normal.bam" -c 1 -S 2 -E 3 -g 4 -Q 10 /home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/syn3-14_51409528_70891309-raw-regions-glimit-regionlimit.bed | testsomatic.R | var2vcf_paired.pl -P 0.9 -m 4.25 -f 0.1  -M  -N "deneme1_tumor|denem1_normal" | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null | /usr/local/share/bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "False")' | sed 's/\\.*Somatic\\/Somatic/' | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/' | /usr/local/share/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /usr/local/bin/vcfstreamsort | bgzip -c > /home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/tx/tmpMW1qbw/syn3-14_51409528_70891309-raw.vcf.gz
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1896)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2552)
	at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:354)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:249)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
' returned non-zero exit status 1
[2016-04-02T02:18Z] Sort BED file : deneme1_tumor
[2016-04-02T02:18Z] Remove high depth regions
[2016-04-02T02:18Z] Genotyping with VarDict: Inference
```

my configuration file

```
details:
- algorithm:
    #bam_sort: coordinate
    aligner: false
    mark_duplicates: false
    realign: false
    recalibrate: false
    variantcaller: [vardict, mutect, freebayes, varscan, mutect2]
    indelcaller: pindel
    ensemble:
        numpass: 2
  analysis: variant2
  description: denem1_normal
  files:
  - /home/ec2-user/puppey/icgc_data/try1/real_deneme/input/normal.bam
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: normal
- algorithm:
    #bam_sort: coordinate
    aligner: false
    mark_duplicates: false
    realign: false
    recalibrate: false
    variantcaller: [vardict, mutect, freebayes, varscan, mutect2]
    indelcaller: pindel
    ensemble:
        numpass: 2
  analysis: variant2
  description: deneme1_tumor
  files:
  - /home/ec2-user/puppey/icgc_data/try1/real_deneme/input/tumor.bam
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: tumor
fc_date: '2016-03-24'
fc_name: real_deneme
upload:
  dir: ../final
```

**Comment by chapmanb** [comment]
Tunc;
Sorry about the analysis problems. What version of `vardict-java` are you currently running with (it should be listed in `provenance/programs.txt`)? There were some issues like this in earlier versions that I believe are fixed with version 1.4.5. If you have an older version you can update with:
```
bcbio_nextgen.py upgrade --tools
```
hope this helps explain the problem.

**Comment by mortunco** [comment]
Brad;

I am afraid my vardict version is 1.4.5 but i will still update the system. Also, when i check the output, there were mutations called from chr 1 to 15. So it might have been failed somewhere. Should I also ask the same question to vardictjava github account?

Thank you very much,

Tunc.


```
[ec2-user@ip-172-31-57-166 provenance]$ cat programs.txt 
bamtools,2.4.0
bcbio-nextgen,0.9.6
bcbio-variation,0.2.6
bcftools,1.3
bedtools,2.24.0
biobambam,2.0.25
bioconductor-bubbletree,2.1.5
bowtie2,2.2.7
bwa,0.7.13
chanjo,
cnvkit,0.7.9
cufflinks,2.2.1
cutadapt,1.9.1
fastqc,0.11.4
featurecounts,1.4.4
freebayes,1.0.2
gatk,3.5-0-g36282e4
gatk-framework,3.4.46
gemini,0.18.3
grabix,0.1.6
htseq,0.6.1p1
lumpy-sv,0.2.12
manta,0.29.3
metasv,0.4.0
mutect,1.1.7
novoalign,3.03.02
novosort,V3.00.02
oncofuse,1.1.0
phylowgs,20150714
picard,1.141
platypus-variant,0.8.1
qualimap,2.1.3
rna-star,
rtg-tools,3.6
sambamba,0.5.9
samblaster,0.1.22
samtools,1.3
scalpel,0.5.1
snpeff,4.2
vardict,2016.02.19
vardict-java,1.4.5
variant-effect-predictor,83
varscan,2.4.0
vcflib,1.0.0_rc0
vt,2015.11.10
wham,1.7.0.162
```

**Comment by mjafin** [comment]
Hi @mortunco, did you align these files previously with bwa and perform any kind of Gatk realignment/recalibration? Gatk realignment often produces alignments with improper CIGAR strings that VarDict chokes on. It might be best to align the raw data with bwa for VarDict and not do any Gatk steps. 

Apologies for all the problems, looks like you're hitting all the edge cases.

**Comment by mortunco** [comment]
Dear @mjafin ;

I am using aligned file which came from ICGC. I dont think I have an access to raw fastq files though. To prove I don't do extra recalibration, you may want to check my configuration file. 

And I do think so that I am the unluckiest person alive. 

I am willing to do everything you say. Thank you for your help,

Best,

Tunc.

**Comment by mjafin** [comment]
@mortunco for testing purposes, could you do another run of bcbio on the sample that failed where you disable all the other variant callers except Vardict (to speed things up) and set
```
aligner: bwa
```
If these are whole genomes the alignment can take a long time unfortunately so you may want to throw all the cpu cores you can get at the alignment process.

If you still get the error then the next step (if you're still game) would be to narrow down to the exact region it's failing in and extracting the reads there with Samtools so we can take a look. In the above command
```
set -o pipefail; unset R_HOME && export PATH=/usr/local/share/bcbio/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3000m -XX:+UseSerialGC -Djava.io.tmpdir=/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/tx/tmpMW1qbw' && vardict-java -G /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N deneme1_tumor -b "/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/prealign/deneme1_tumor/tumor.bam|/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/prealign/denem1_normal/normal.bam" -c 1 -S 2 -E 3 -g 4 -Q 10 /home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/syn3-14_51409528_70891309-raw-regions-glimit-regionlimit.bed | testsomatic.R | var2vcf_paired.pl -P 0.9 -m 4.25 -f 0.1  -M  -N "deneme1_tumor|denem1_normal" | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null | /usr/local/share/bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "False")' | sed 's/\\.*Somatic\\/Somatic/' | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/' | /usr/local/share/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /usr/local/bin/vcfstreamsort | bgzip -c > /home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/tx/tmpMW1qbw/syn3-14_51409528_70891309-raw.vcf.gz
```
this file `/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/syn3-14_51409528_70891309-raw-regions-glimit-regionlimit.bed` controls the region and you could split it further to understand where the failure happens. I know this is asking a lot,

**Comment by mortunco** [comment]
@mjafin I will perform everything you say, I just need time. I will report you asap.

Thank you very much!

Tunc.

**Comment by mortunco** [comment]
@mjafin;

I got the same error during variant calling. Actually from the same exact region. I posted the bed file here so that we can go deeper.

So whats next ? :) 

Best,

Tunc.



```
[2016-04-05T18:03Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/usr/local/share/bcbio/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3000m -XX:+UseSerialGC -Djava.io.tmpdir=/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/tx/tmpl6DQlr' && vardict-java -G /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N deneme1_tumor -b "/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/prealign/deneme1_tumor/tumor.bam|/home/ec2-user/puppey/icgc_data/try1/real_deneme/work/prealign/denem1_normal/normal.bam" -c 1 -S 2 -E 3 -g 4 -Q 10 /home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/syn3-14_51409528_70891309-raw-regions-glimit-regionlimit.bed | testsomatic.R | var2vcf_paired.pl -P 0.9 -m 4.25 -f 0.1  -M  -N "deneme1_tumor|denem1_normal" | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null | /usr/local/share/bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "False")' | sed 's/\\.*Somatic\\/Somatic/' | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/' | /usr/local/share/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /usr/local/bin/vcfstreamsort | bgzip -c > /home/ec2-user/puppey/icgc_data/try1/real_deneme/work/vardict/14/tx/tmpl6DQlr/syn3-14_51409528_70891309-raw.vcf.gz
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1896)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2552)
	at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:354)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:249)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
' returned non-zero exit status 1
```
This is the content of the bed file.
```
[ec2-user@ip-172-31-57-166 14]$ cat syn3-14_51409528_70891309-raw-regions-glimit-regionlimit.bed
14	51409544	52409544
14	52409294	53409294
14	53409044	54409044
14	54408794	55408794
14	55408544	56408544
14	56408294	56909026
14	56909341	57909341
14	57909091	58909091
14	58908841	59429219
14	59429518	59545313
14	59545595	60545595
14	60545345	61079110
14	61079399	61525316
14	61525666	62525666
14	62525416	63525416
14	63525166	64525166
14	64524916	65360429
14	65360833	65361550
14	65361857	65363235
14	65363519	66363519
14	66363269	67363269
14	67363019	68363019
14	68362769	68603328
14	68603725	69603725
14	69603475	70603475
14	70603225	70891282
```
This is the configuration file that I used for this analysis. I shared just to be sure that we are on the same page.
```
details:
- algorithm:
    aligner: bwa
    aligner: false
    mark_duplicates: false
    realign: false
    recalibrate: false
    variantcaller: [vardict]
    indelcaller: #pindel
    ensemble:
        numpass: 2
  analysis: variant2
  description: denem1_normal
  files:
  - /home/ec2-user/puppey/icgc_data/try1/real_deneme/input/normal.bam
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: normal
- algorithm:
    aligner: bwa
    aligner: false
    mark_duplicates: false
    realign: false
    recalibrate: false
    variantcaller: [vardict]
    indelcaller: #pindel
    ensemble:
        numpass: 2
  analysis: variant2
  description: deneme1_tumor
  files:
  - /home/ec2-user/puppey/icgc_data/try1/real_deneme/input/tumor.bam
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: tumor
fc_date: '2016-03-24'
fc_name: real_deneme
upload:
  dir: ../final
```

**Comment by mjafin** [comment]
Hi @mortunco, you have now `aligner` set twice in your configuration file, with `false` as the last entry. Was the data aligned or did it skip right to variant calling? Could you remove the `aligner: false` line and retry once more. If after realigning the data you get this error then I would suggest splitting the bed file in half recursively until you identify the offending region and then extracting the reads there for us

**Comment by mortunco** [comment]
Oh my god that totally missed that one. I am sorry. I will inform you when its done.

**Comment by tfenne** [comment]
FWIW I'm seeing the same error running VarDict 1.4.5 outside of bcbio.  I modified the VarDict source to spit out the read name and cigar string of the read it was processing when the exception occurred, and in my case the read's cigar started with an insertion operator (e.g. `2I98M`).  That's technically valid SAM - it's just unusual, but VarDict seems to assume that that won't be the case.

I'm not sure how much flexibility you have in the `bcbio` workflow, but if you can avoid running GATK Indel Realigner _or_ soft-clip insertions at the starts of ends of reads in your BAM file before feeding it in, I believe it should work.

**Comment by mjafin** [comment]
Thanks for chiming in @tfenne, this points to Gatk Indel Realigner once again being the culprit here. As VarDict performs indel realignment intrinsically we'd recommend running it on non-Gatk modified BAM files where possible. @zhongwulai has implemented a lot of checking and fixing of improper and odd CIGARs as special cases in VarDict but clearly the `2I98M` case isn't there.

**Comment by chapmanb** [comment]
Miika, Tim and Tunc -- thanks for debugging this. It would be great to have a fix for this in VarDict and I'll continue the thread in AstraZeneca-NGS/VarDictJava#34
