### ISSUE TITLE
upload_samples_project fails: TypeError: coercing to Unicode: need string or buffer, dict found

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1303]
As the subject says.

The reason lies in 

```python
x["mtime"] = shared.get_file_timestamp(x["path"])
```
in `bcbio/upload/__init__.py`.  In such cases, ``x["path"]`` gives a dict:

```python
(Pdb) x["path"]
{'all': {}, 'problems': None}
```

I have no idea why this occurs, though.

**Comment by chapmanb** [comment]
Luca;
Sorry about the issue. Could you post the full traceback for this? It appears as if we've got an issue with detecting that we don't have coverage reporting, but I'm having trouble reproducing the issue. If we can figure out exactly where in the upload process it comes from it will hopefully be easier to track down. Thanks much.

**Comment by lbeltrame** [comment]
I'll try to rerun things in the next few days (the cluster is busy running other jobs) and report back.

**Comment by phu5ion** [comment]
Hi,

I'm having the same problem as Luca. The full traceback is as follows:
[2016-05-21T10:25Z] multiprocessing: upload_samples_project
Traceback (most recent call last):
  File "/home/hodl/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/hodl/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 191, in variant2pipeline
    run_parallel("upload_samples_project", [sample])
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 307, in upload_samples_project
    return upload.project_from_sample(*args)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 21, in project_from_sample
    for finfo in _get_files_project(sample, upload_config):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 528, in _get_files_project
    return _add_meta(out, config=upload_config)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 89, in _add_meta
    x["mtime"] = shared.get_file_timestamp(x["path"])
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/shared.py", line 9, in get_file_timestamp
    return datetime.datetime.fromtimestamp(os.path.getmtime(f))
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
TypeError: coercing to Unicode: need string or buffer, dict found


Thank you!

**Comment by chapmanb** [comment]
Sorry about the upload problems. I'm not exactly sure about the source of the project but tried to add in better debugging to help isolate it. If you update to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
and re-run, could you provide the error output? That might help us isolate the conditions causing the issue. Thanks much.

**Comment by phu5ion** [comment]
Hi Brad,

I don't know why, but after I updated bcbio with the command above and reran my run, the run completed without errors. Perhaps the problem has already been resolved in one of the bcbio updates. Anyway thanks for your help.

**Comment by chapmanb** [comment]
Great -- glad it's working for you. Thanks for following up. The traceback did look like an older version and we've had some fixes to resolve issues like this, so hopefully we've got them all. Luca, please feel free to re-open if you still have this problem and happy to debug more.
