### ISSUE TITLE
error running manta SV

### ISSUE THREAD

**Issue by rjsicko** [chapmanb/bcbio-nextgen#1308]
I'm trying to run SV calling on a project that I previously used bcbio on to perform ensemble variant calling. I'm using the same work dir from the previous project and the following yaml file. 
**project-merged_sv.yaml**
````
details:
- algorithm:
    aligner: bwa
    realign: false
    recalibrate: false
    remove_lcr: true
    variant_regions: /media/sf_BigShare/agilent_files/S04380219_Covered_noChr.bed
    variantcaller: false
    svcaller: [lumpy, manta, cnvkit]
    tools_on: [svplots]
  analysis: variant2
  description: A06551
  files:
  - /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R1.fastq.gz
  - /media/sf_BigShare/16014_wes_pilot/work/fastq/merged/A06551_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: batch1
    phenotype: affected
    sex: male
````
manta is throwing an error. The pyflow_log is attached below. In the bcbio_system.yaml I have a local tmp dir defined, but I'm not sure if manta is using it.

**pyflow_log.txt**
````
[2016-04-05T12:31:12.811222] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Initiating pyFlow run
[2016-04-05T12:31:12.811642] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] pyFlowClientWorkflowClass: MantaWorkflow
[2016-04-05T12:31:12.812084] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] pyFlowVersion: 1.1.10
[2016-04-05T12:31:12.812583] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] pythonVersion: 2.7.11.final.0
[2016-04-05T12:31:12.813070] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] WorkingDir: '/media/sf_BigShare/16014_wes_pilot/work'
[2016-04-05T12:31:12.813583] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] ProcessCmdLine: '/media/sf_BigShare/16014_wes_pilot/work/structural/A06551/manta/runWorkflow.py -m local -j 7 --quiet'
[2016-04-05T12:31:12.814082] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [RunParameters] mode: local
[2016-04-05T12:31:12.814595] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [RunParameters] nCores: 7
[2016-04-05T12:31:12.815152] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [RunParameters] memMb: 39599
[2016-04-05T12:31:12.815745] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [RunParameters] dataDir: /media/sf_BigShare/16014_wes_pilot/work/structural/A06551/manta/workspace/pyflow.data
[2016-04-05T12:31:12.816117] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [RunParameters] isDryRun: False
[2016-04-05T12:31:12.816614] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [RunParameters] isContinue: False
[2016-04-05T12:31:12.817145] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [RunParameters] isForceContinue: True
[2016-04-05T12:31:12.817772] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [RunParameters] mailTo: ''
[2016-04-05T12:31:12.819310] [bl8vbox.unassigned-domain] [19949_1] [TaskRunner:masterWorkflow] Starting task specification for master workflow
[2016-04-05T12:31:12.820343] [bl8vbox.unassigned-domain] [19949_1] [MantaWorkflow] Initiating Manta workflow version: 0.29.1
[2016-04-05T12:31:12.821524] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_makeTmpDir' to master workflow
[2016-04-05T12:31:12.847567] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_000' to master workflow
[2016-04-05T12:31:12.889976] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_001' to master workflow
[2016-04-05T12:31:12.907178] [bl8vbox.unassigned-domain] [19949_1] [TaskManager] Launching command task: 'getAlignmentStats_makeTmpDir' from master workflow
[2016-04-05T12:31:12.917970] [bl8vbox.unassigned-domain] [19949_1] [TaskRunner:getAlignmentStats_makeTmpDir] Task initiated on local node
[2016-04-05T12:31:12.920243] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_002' to master workflow
[2016-04-05T12:31:12.946924] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_003' to master workflow
[2016-04-05T12:31:12.973468] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_004' to master workflow
[2016-04-05T12:31:13.000898] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_005' to master workflow
[2016-04-05T12:31:13.028540] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_006' to master workflow
[2016-04-05T12:31:13.043110] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_007' to master workflow
[2016-04-05T12:31:13.052144] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_008' to master workflow
[2016-04-05T12:31:13.060035] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_009' to master workflow
[2016-04-05T12:31:13.067767] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_010' to master workflow
[2016-04-05T12:31:13.079811] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_011' to master workflow
[2016-04-05T12:31:13.090203] [bl8vbox.unassigned-domain] [19949_1] [TaskManager] Completed command task: 'getAlignmentStats_makeTmpDir' launched from master workflow
[2016-04-05T12:31:13.103698] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_012' to master workflow
[2016-04-05T12:31:13.119899] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_013' to master workflow
[2016-04-05T12:31:13.156780] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_014' to master workflow
[2016-04-05T12:31:13.158675] [bl8vbox.unassigned-domain] [19949_1] [TaskManager] Launching command task: 'getAlignmentStats_generateStats_000' from master workflow
[2016-04-05T12:31:13.169708] [bl8vbox.unassigned-domain] [19949_1] [TaskRunner:getAlignmentStats_generateStats_000] Task initiated on local node
[2016-04-05T12:31:13.179411] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_generateStats_015' to master workflow
[2016-04-05T12:31:13.195376] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_mergeStats' to master workflow
[2016-04-05T12:31:13.251821] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] Adding command task 'getAlignmentStats_rmTmpDir' to master workflow
[2016-04-05T12:31:13.261830] [bl8vbox.unassigned-domain] [19949_1] [TaskManager] Launching command task: 'getAlignmentStats_generateStats_007' from master workflow
[2016-04-05T12:31:13.287514] [bl8vbox.unassigned-domain] [19949_1] [TaskRunner:getAlignmentStats_generateStats_007] Task initiated on local node
[2016-04-05T12:31:33.356515] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR] Failed to complete master workflow, error code: 1
[2016-04-05T12:31:33.358103] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR] errorMessage:
[2016-04-05T12:31:33.358652] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR] Unhandled Exception in TaskRunner-Thread-masterWorkflow
[2016-04-05T12:31:33.361162] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR] Traceback (most recent call last):
[2016-04-05T12:31:33.362504] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 1034, in run
[2016-04-05T12:31:33.363336] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     (retval, retmsg) = self._run()
[2016-04-05T12:31:33.365983] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 1086, in _run
[2016-04-05T12:31:33.367057] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     self.workflow.workflow()
[2016-04-05T12:31:33.368039] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/mantaWorkflow.py", line 665, in workflow
[2016-04-05T12:31:33.368447] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     statsTasks = runStats(self,taskPrefix="getAlignmentStats")
[2016-04-05T12:31:33.368956] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/mantaWorkflow.py", line 138, in runStats
[2016-04-05T12:31:33.369854] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     rmTask=self.addTask(preJoin(taskPrefix,"rmTmpDir"),rmStatsTmpCmd,dependencies=mergeTask, isForceLocal=True)
[2016-04-05T12:31:33.370475] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 3384, in addTask
[2016-04-05T12:31:33.371148] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     self._addTaskCore(self._getNamespace(), label, payload, dependencies)
[2016-04-05T12:31:33.371480] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 3718, in _addTaskCore
[2016-04-05T12:31:33.371889] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     self._tdag.addTask(namespace, label, payload, dependencies)
[2016-04-05T12:31:33.372725] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 502, in wrapped
[2016-04-05T12:31:33.373443] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     return f(self, *args, **kw)
[2016-04-05T12:31:33.373922] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 2370, in addTask
[2016-04-05T12:31:33.374610] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     self.writeTaskStatus()
[2016-04-05T12:31:33.375455] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 502, in wrapped
[2016-04-05T12:31:33.375966] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     return f(self, *args, **kw)
[2016-04-05T12:31:33.376912] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 2444, in writeTaskStatus
[2016-04-05T12:31:33.377445] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     forceRename(tmpFile, self.taskStateFile)
[2016-04-05T12:31:33.378147] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]   File "/usr/local/share/bcbio/anaconda/share/manta-0.29.1-0/lib/python/pyflow/pyflow.py", line 161, in forceRename
[2016-04-05T12:31:33.378924] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR]     os.rename(src,dst)
[2016-04-05T12:31:33.379417] [bl8vbox.unassigned-domain] [19949_1] [WorkflowRunner] [ERROR] OSError: [Errno 26] Text file busy
````

**Comment by chapmanb** [comment]
Sorry about the issues. You're right that we don't use temporary directories for manta output, and instead write directly into the work directory. Manta has it's own internal workflow system and ability to restart, so this provides the ability to restart a partially finished manta job if it were to die.

It looks like your work directory is problematic for reading/writing directly. If I remember correctly, this filesystem had an unusual setup. Is it possible to run these on a different more standard filesystem? Sorry to not have a better answer but hope this would work.
