### ISSUE TITLE
tumor-only calling issue

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1322]
Hi, sorry to bother you again. I'm getting the following error (below). Indeed, the input vcf is lacking the ```#CHROM``` header, but I'm not sure what to do about it...

```
[2016-04-11T13:52Z] Timing: variant calling
[2016-04-11T13:52Z] multiprocessing: variantcall_sample
[2016-04-11T13:52Z] multiprocessing: concat_variant_files
[2016-04-11T13:52Z] Resource requests: ; memory: 1.00; cores: 1
[2016-04-11T13:52Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-04-11T13:52Z] Concat variant files
[2016-04-11T13:52Z] INFO  15:52:32,965 HelpFormatter - -------------------------------------------------------
[2016-04-11T13:52Z] INFO  15:52:32,967 HelpFormatter - Program Name: org.broadinstitute.gatk.tools.CatVariants
[2016-04-11T13:52Z] INFO  15:52:32,971 HelpFormatter - Program Args: -R /home/genetik/bcbio/share/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -V /home/genetik/irina/myeloid_fastq_run/calling/work/mutect/16-0206-files.list -out /home/genetik/irina/myeloid_fastq_run/calling/work/mutect/tx/tmpTYUPNX/16-0206.vcf.gz -assumeSorted
[2016-04-11T13:52Z] INFO  15:52:32,981 HelpFormatter - Executing as genetik@v01s979.vll.se on Linux 3.10.0-327.4.4.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.7.0_99-mockbuild_2016_03_25_01_00-b00.
[2016-04-11T13:52Z] INFO  15:52:32,982 HelpFormatter - Date/Time: 2016/04/11 15:52:32
[2016-04-11T13:52Z] INFO  15:52:32,982 HelpFormatter - -------------------------------------------------------
[2016-04-11T13:52Z] INFO  15:52:32,983 HelpFormatter - -------------------------------------------------------
[2016-04-11T13:52Z] .........10......##### ERROR ------------------------------------------------------------------------------------------
[2016-04-11T13:52Z] ##### ERROR stack trace
[2016-04-11T13:52Z] htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file, for input source: /home/genetik/irina/myeloid_fastq_run/calling/work/mutect/chr7/16-0206-chr7_50367205_101459534.vcf.gz
[2016-04-11T13:52Z] 	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:90)
[2016-04-11T13:52Z] 	at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:74)
[2016-04-11T13:52Z] 	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:85)
[2016-04-11T13:52Z] 	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:66)
[2016-04-11T13:52Z] 	at org.broadinstitute.gatk.tools.CatVariants.getFeatureReader(CatVariants.java:186)
[2016-04-11T13:52Z] 	at org.broadinstitute.gatk.tools.CatVariants.execute(CatVariants.java:279)
[2016-04-11T13:52Z] 	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:248)
[2016-04-11T13:52Z] 	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:155)
[2016-04-11T13:52Z] 	at org.broadinstitute.gatk.tools.CatVariants.main(CatVariants.java:311)
[2016-04-11T13:52Z] Caused by: htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file
[2016-04-11T13:52Z] 	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:119)
[2016-04-11T13:52Z] 	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
[2016-04-11T13:52Z] 	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:41)
[2016-04-11T13:52Z] 	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:88)
[2016-04-11T13:52Z] 	... 8 more
[2016-04-11T13:52Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-04-11T13:52Z] ##### ERROR A GATK RUNTIME ERROR has occurred (version 3.4-65-g2434e49):
[2016-04-11T13:52Z] ##### ERROR
[2016-04-11T13:52Z] ##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
[2016-04-11T13:52Z] ##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
[2016-04-11T13:52Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
```

**Comment by chapmanb** [comment]
Pär;
Sorry about the issue. You mentioned there is a problem with the input file, what does it look like?
```
zcat /home/genetik/irina/myeloid_fastq_run/calling/work/mutect/chr7/16-0206-chr7_50367205_101459534.vcf.gz
```
I'm not sure exactly what could have happened, but it might be worth removing that file if it's corrupted and running bcbio again with a single core on a local run to see if you can identify any problems or other issues with the mutect analysis that might lead to a problem output file. Hope this helps debug it.

**Comment by parlar** [comment]
Now it works. Not sure what changed, to be honest.

**Comment by chapmanb** [comment]
Thanks for following up. It sounds like potential shared filesystem issues but please re-open if you find a reproducible example. Hope your analysis finishes up cleanly.
