### ISSUE TITLE
small rna seq analysis using bcbio (bowtie path)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1324]
```
#Starting miRDeep2
/BiO/BioTools/bcbio/data/anaconda/bin/miRDeep2.pl /BiO/BioPeople/brandon/test_bcbio/smrna/mirqc_bcbio/work/mirdeep2/file_reads.fa /BiO/BioTools/bcbio/data/genomes/Hsapiens/hg19/seq/hg19.fa /BiO/BioPeople/brandon/test_bcbio/smrna/mirqc_bcbio/work/mirdeep2/align.bam /BiO/BioTools/bcbio/data/genomes/Hsapiens/hg19/srnaseq/mature.fa none /BiO/BioTools/bcbio/data/genomes/Hsapiens/hg19/srnaseq/hairpin.fa -f /BiO/BioTools/bcbio/data/genomes/Hsapiens/hg19/srnaseq/Rfam_for_miRDeep.fa -r simple -c -d -P -t hsa -z res

miRDeep2 started at 9:59:39


mkdir mirdeep_runs/run_res



#####################################
#                                   #
# miRDeep2.0.0.7                    #
#                                   #
# last change: 10/12/2014           #
#                                   #
#####################################

miRDeep2 started at 9:59:39


#Starting miRDeep2
Error:  bowtie not found
Check if bowtie is correctly installed and all Pathes were set correctly.

If you used the install.pl script make sure that you started a complete new shell window after installation.
If this did not help please restart youer workstation.

' returned non-zero exit status 127
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.7', 'bcbio_nextgen.py')
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script

  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 1483, in run_script

  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 321, in smallrnaseqpipeline
    samples = run_parallel("seqcluster_cluster", [samples])
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
```

How can I handle the bowtie path in bcbio?

**Comment by AurelieMLB** [comment]
Hello,
Just wanted to mention that I am getting the same error. The only bowtie that seems to be installed on the machines I have access to seems to be bowtie2. Any way I can tell miRDeep2 to use bowtie2 please?

Many thanks

**Comment by chapmanb** [comment]
Sorry about the problems. We accidentally left bowtie out of the tools bcbio installs so it was not included and available for this pipeline. I've updated it so it'll now get automatically installed with other tools. If you do:
```
bcbio_nextgen.py upgrade --tools
```
it will add bowtie and should work again. Thanks much for letting us know about the problem.

**Comment by mjafin** [comment]
@AurelieMLB I can pull these updates into our `latest-devel` installation sometime today, bear with me

**Comment by AurelieMLB** [comment]
Thank you so much to both !

**Comment by hmkim** [comment]
I solve the problem via updating tools (now, we can install the bowtie in bcbio)

Thanks!
