### ISSUE TITLE
cnvkit fails with "no such file or directory" when running Rscript

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1328]
Apparently it tries to load a script that's no longer there:

```python

[2016-04-13T06:40Z] uni03: No outlier bins
[2016-04-13T06:40Z] uni03: Traceback (most recent call last):
[2016-04-13T06:40Z] uni03:   File "/storage/rozo/bcbio/anaconda/bin/cnvkit.py", line 11, in <module>
[2016-04-13T06:40Z] uni03:     args.func(args)
[2016-04-13T06:40Z] uni03:   File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 666, in _cmd_se
gment
[2016-04-13T06:40Z] uni03:     rlibpath=args.rlibpath)
[2016-04-13T06:40Z] uni03:   File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 55
, in do_segmentation
[2016-04-13T06:40Z] uni03:     seg_out = ngfrills.call_quiet('Rscript', script_fname)
[2016-04-13T06:40Z] uni03:   File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/ngfrills/__init__.py", line 42, in
 call_quiet
[2016-04-13T06:40Z] uni03:     % (' '.join(args), err))
[2016-04-13T06:40Z] uni03: RuntimeError: Subprocess command failed:
[2016-04-13T06:40Z] uni03: $ Rscript /tmp/tmp5nsfEn
[2016-04-13T06:40Z] uni03: 
[2016-04-13T06:40Z] uni03: Rscript execution error: No such file or directory
[2016-04-13T06:40Z] uni03: 
[2016-04-13T06:40Z] uni03: Uncaught exception occurred
Traceback (most recent call last):
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/storage/rozo/bcbio/anaconda/bin:$PATH && /storage/rozo/bcb
io/anaconda/bin/cnvkit.py segment -o /storage/rozo/projects/OV-223/ov223/work/structural/LC0044-FAL/cnvkit/raw/tx/tmpgcblTH/LC0044-FA
L-sort.cns /storage/rozo/projects/OV-223/ov223/work/structural/LC0044-FAL/cnvkit/raw/LC0044-FAL-sort.cnr
No outlier bins
Traceback (most recent call last):
  File "/storage/rozo/bcbio/anaconda/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 666, in _cmd_segment
    rlibpath=args.rlibpath)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 55, in do_segmentation
    seg_out = ngfrills.call_quiet('Rscript', script_fname)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/ngfrills/__init__.py", line 42, in call_quiet
    % (' '.join(args), err))
RuntimeError: Subprocess command failed:
$ Rscript /tmp/tmp5nsfEn

Rscript execution error: No such file or directory
```

Latest master.

**Comment by lbeltrame** [comment]
Launching the script manually causes the same error, so I wonder if it's a bug in cnvkit instead? It's the first time I use it though, so I can't tell.

**Comment by lbeltrame** [comment]
It's a local installation error, seen after further investigation. Closing.
