### ISSUE TITLE
TypeError when starting detect_sv phase with lumpy

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1338]
This is with latest master:

```python
[2016-04-15T05:41Z] uni01: ipython: detect_sv
[2016-04-15T05:41Z] uni03: Unexpected error
Traceback (most recent call last):
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 45, in _setup_logging
    yield config
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 357, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 140, in detect_sv
    for svdata in caller_fn(items):
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/lumpy.py", line 144, in run
    gt_vcfs = _filter_by_background([paired.tumor_name], [paired.normal_name], gt_vcfs, paired.tumor_data)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/lumpy.py", line 78, in _filter_by_background
    for rec in inp:
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 583, in next
    samples = self._parse_samples(row[9:], fmt, record)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 448, in _parse_samples
    self.samples, samples, samp_fmt, samp_fmt._types, samp_fmt._nums, site)
  File "cparse.pyx", line 78, in vcf.cparse.parse_samples (vcf/cparse.c:1839)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/vcf/model.py", line 27, in __init__
    self.gt_alleles = [(al if al != '.' else None) for al in allele_delimiter.split(self.data.GT)]
TypeError: expected string or buffer
```

Configuration template:

```yaml
details:
  - analysis: variant2
    genome_build: hg19
    algorithm:
        aligner: bwa
        mark_duplicates: true
        recalibrate: false
        realign: false
        variantcaller:
            - mutect
            - vardict
            - freebayes
        platform: illumina
        svcaller:
            - lumpy
            - manta
            - cnvkit
        quality_format: Standard
        ensemble:
            numpass: 1
        remove_lcr: true
        trim_reads: false
        variant_regions: my_regions
        effects: snpeff
        clinical_reporting: true
        mixup_check: qsignature
        merge_bamprep: true
        coverage: my_regions
        tools_on: [qualimap_full, multiqc]
    metadata:
        sex: female
upload:
    dir: ../final/
globals:
    my_regions: /storage/rozo/projects/OV223/regions/targets.bed
```

**Comment by chapmanb** [comment]
Luca;
Sorry about the problems. Are you able to share (privately is fine) the lumpy file that's failing with this error? It looks like PyVCF is failing on the input file. If we can reproduce I can try to push a fix or workaround. Thanks much.

**Comment by lbeltrame** [comment]
I'll go through them and be sure to send one if possible.

**Comment by lbeltrame** [comment]
For the record I have sent an offending file generated by lumpy to Brad.

**Comment by chapmanb** [comment]
Luca;
Thanks for sending along the file. I'm trying to reproduce to debug but having trouble replicating with that input file. If I run this small script:
```
import sys
import gzip

import vcf

print vcf.VERSION

orig_vcf = sys.argv[1]
with gzip.open(orig_vcf) as in_handle:
    inp = vcf.Reader(in_handle, orig_vcf)
    for rec in inp:
        print [x.gt_alleles for x in rec.samples]
        print rec
```
With:
```
bcbio_python test.py the_input.vcf.gz
```
it works cleanly. Does this work with your local bcbio installation and PyVCF? What version of pyvcf do you have `bcbio_conda list pyvcf`? 

Thanks for the help debugging and getting to a reproducible test case.

**Comment by lbeltrame** [comment]
This is what I get:
```python
0.6.8.dev0
[['0', '0']]
Record(CHROM=chr1, POS=1588570, REF=N, ALT=[<DUP>])
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    for rec in inp:
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 583, in next
    samples = self._parse_samples(row[9:], fmt, record)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 448, in _parse_samples
    self.samples, samples, samp_fmt, samp_fmt._types, samp_fmt._nums, site)
  File "cparse.pyx", line 78, in vcf.cparse.parse_samples (vcf/cparse.c:1839)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/vcf/model.py", line 27, in __init__
    self.gt_alleles = [(al if al != '.' else None) for al in allele_delimiter.split(self.data.GT)]
TypeError: expected string or buffer
```

```
$ bcbio_conda list pyvcf
# packages in environment at /storage/rozo/bcbio/anaconda:
#
pyvcf                     0.6.8.dev0               py27_0    bioconda
```

**Comment by lbeltrame** [comment]
From what I can gather, `self.data.GT` is `None`, and that causes the behavior I'm seeing.

**Comment by chapmanb** [comment]
Could you try updating pyvcf to see if that fixes the issue?
```
bcbio_conda install pyvcf
```
I'm not sure why I'm not seeing this and thinking it might be the version installed. Sorry to not have better ideas but hope this does it.

**Comment by lbeltrame** [comment]
Apparently it's the same. I'll try removing, cleaning any residual "pyvcf" there, then reinstalling.

**Comment by lbeltrame** [comment]
OK, removing completely pyvcf and reinstalling it did the trick. It looks like conda did not upgrade the `cparse.so` extension from pyvcf, and I guess this was the result. In any case, it works fine now.
