### ISSUE TITLE
TypeError with qcsummary phase

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1339]
```python
[2016-04-15T14:37Z] uni34: parsing coverage: LC0044-ME
[2016-04-15T14:32Z] uni17: Unexpected error
Traceback (most recent call last):
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 45, in _setup_logging
    yield config
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 242, in coverage_report
    return ipython.zip_args(apply(qcsummary.coverage_report, *args))
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 1129, in coverage_report
    data = cov.variants(data)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 297, in variants
    _summary_variants(parse_file, qc_file)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 245, in _summary_variants
    q_d = np.percentile(dt['depth'], p_point)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3268, in percentile
    interpolation=interpolation)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2997, in _ureduce
    r = func(a, **kwargs)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3385, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by lbeltrame** [comment]
I've seen it occur after the GC calculation steps in qcsummary.

**Comment by lpantano** [comment]
Sorry about this.

Can you check the file that ends with _gc-depth-parse.tsv

It should parse the column with the header DEPTH, do you see some weird values there? I will check in my test if all were integers for this case.

thanks

**Comment by lbeltrame** [comment]
Depth is "." for some reason. I'm not sure how it's calculated, though.

**Comment by lbeltrame** [comment]
Example:

```
CG      depth   sample
68.32   .       LC0044-ME
```

**Comment by lpantano** [comment]
Thanks, will fix at least that. It would be only there if the VCF file has that field. I didn’t think in some case that was not the case.  Using this command

bcftools query -s {sample} -f '[%GC][\\t%DP][\\t%SAMPLE]\\n' -R

, after calculating the GC with VariantAnnotator

What tool did you use to call variant callings? or is this some join calling maybe has no depth there. Sorry, I am a little lost in the different output we can generate depending on tools, etc. But will fix this to avoid the error.

thanks

**Comment by lbeltrame** [comment]
I used 3 different tools there:

- MuTect 2
- FreeBayes
- VarDict

all in the tumor-normal calling modes.

**Comment by lpantano** [comment]
Thanks, I reproduced the issue and fixed. i will look next week how to normalize this since some callers don't produce the DP value. Probably the best is to add it to VariantAnnotation since I am already calculating the GC content.

thanks!

**Comment by lbeltrame** [comment]
I second the idea of using VariantAnnotator to add these information, as it's also causing issues for the QC report (see issue #1346).

**Comment by lpantano** [comment]
Hi @lbeltrame,

thanks for looking into that. Can you confirm is all the columns has `.` or only some of them.

I realized that I had changed the command to calculated the DP with VariantAnnotator, so I hope only some variants have this value and is maybe in tumor/normal samples analysis only when this happens.

I can only think that maybe is a variant in normal that has not coverage in tumor? Otherwise should have some value there. 

If you have time, it would be great if you can check one variant that has this value for DP in the VCF file.

I will fix the report meanwhile.

thanks
