### ISSUE TITLE
Upload_samples fails with TypeError

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1345]
Apparently in some cases `input` is a list, and not a dict. 

```python
[2016-04-18T09:05Z] multiprocessing: upload_samples
Traceback (most recent call last):
  File "/storage/rozo/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/storage/rozo/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 189, in variant2pipeline
    samples = run_parallel("upload_samples", samples)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 303, in upload_samples
    return upload.from_sample(*args)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 31, in from_sample
    for finfo in _get_files(sample):
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 45, in _get_files
    return _get_files_variantcall(sample)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 110, in _get_files_variantcall
    out = _maybe_add_summary(algorithm, sample, out)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 296, in _maybe_add_summary
    out.extend(_flatten_file_with_secondary(finfo, os.path.join("qc", program)))
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 276, in _flatten_file_with_secondary
    print(input["base"])
TypeError: list indices must be integers, not str
```

**Comment by lbeltrame** [comment]
For example, I get:

```
['/storage/rozo/projects/OV-223/ov223/work/qc/LC0044-VE/qsignature/LC0044-VE-sort-chr.qsig.vcf']
```

as `input`.

**Comment by chapmanb** [comment]
Luca -- thanks for the report and sorry about the problem. I believe this is the same underlying issue as #1344 so fixed and updated with more details there.
