### ISSUE TITLE
Possible locale-aware errors during the pipeline run (decimal point/comma)

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1348]
Does the pipeline set its own LANG and LC variables? IMO it should, otherwise we can get such records (seen in the ensemble output):

```
1/1:2:2:1,1:0,0:0,2:1,0:0,2:32,5:1:32,0:0:1:0:23,0:4,0:1,0:0:2,5
```

The penultimate record (`1,0`) is an `AF` field in an ensemble VCF. It should be `1.0`, but it isn't, and I suspect my own locale here.

Afterwards, when running `cnvkit loh`, a typical command line like

```
/storage/rozo/bcbio/anaconda/bin/cnvkit.py loh -t -s /storage/rozo/projects/OV-223/ov223/work/structural/LC0044-FAL/cnvkit/raw/LC0044-FAL-sort-chromfilter.cns -o /storage/rozo/projects/OV-223/ov223/work/structural/LC0044-FAL/cnvkit/raw/tx/tmp6xQ050/LC0044-FAL-sort-loh.pdf /storage/rozo/projects/OV-223/ov223/work/ensemble/LC0044-FAL_vs_normal/LC0044-FAL_vs_normal-ensemble.vcf.gz
```

Fails with

```
Traceback (most recent call last):
  File "/storage/rozo/bcbio/anaconda/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1177, in _cmd_loh
    args.min_depth, skip_hom=True, skip_somatic=True)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/vary.py", line 79, in read_vcf
    table = pd.DataFrame.from_records(rows, columns=columns)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 949, in from_records
    values += data
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/vary.py", line 220, in _parse_records
    for record in vcf_reader:
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 587, in next
    samples = self._parse_samples(row[9:], fmt, record)
  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 486, in _parse_samples
    sampdat[i] = float(vals)
ValueError: invalid literal for float(): 1,0
```

**Comment by lbeltrame** [comment]
Actually, this is not the right place where the error occurs. Investigatign further...

**Comment by lbeltrame** [comment]
Updated description with the actual field causing problems.

**Comment by lbeltrame** [comment]
Indeed it looks like a pipeline-wide issue. The YAML produced (`pipeline-summary`) has stuff like

```
Mapped reads_qualimap_1e7reads_est: 89.816.849
```

This is the thousands separator in my locale (it_IT).

**Comment by chapmanb** [comment]
Luca;
Thanks for the detailed description of the problem. I added fixes to bcbio to export `LC_ALL` and `LANG` to `C` so that the tool runs won't be dependent on locale settings. These exports also propagate to subprocess calls so should hopefully fix cnvkit invocations as well. Please let us know if this needs any more tweaking beyond this. Thanks again.
