### ISSUE TITLE
How to debug ipyparallel.error.CompositeError: [Engine Exception]SystemExit: 1 during organize_samples

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1358]
Hi, 

With a recent version of  bcbio 0.9.8a0  I get an error when trying to run a  pipeline using ipython.py/ipyparallel.  I do not get this error with my previous bcbio 0.9.6 installation. 

I installed the latest version using the  --isolate argument so first I load some paths that I found out with earlier bcbio versions that are needed. The paths go the latest bcbio install. 

```
export PATH=/data/Tools/bcbio-20160421/tooldir/bin:$PATH
export LD_LIBRARY_PATH=/data/Tools/bcbio-20160421/appdir/anaconda/lib:$LD_LIBRARY_PATH
export PERL5LIB=/data/Tools/bcbio-20160421/appdir/anaconda/lib/perl5:${PERL5LIB}
export PYTHONPATH=/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages
```

Then I try to run my analysis:
```
/data/Tools/bcbio-20160421/appdir/anaconda/bin/bcbio_nextgen.py ../config/Project-123_samples.yaml  -t ipython -n 45 -s sge -q main
```

The error that I get is not very descriptive
```
"ipyparallel.error.CompositeError: one or more exceptions from call to method: organize_samples
[Engine Exception]SystemExit: 1
```

Running the analysis with 1 cpu ( without the  -t ipython -n 45 -s sge -q main part)  proceeds without errors. 

Do you have any advice on how to debug / troubleshoot the ipyparallel.error.CompositeError further? Is there a way to have ipyparallel be more verbose for errors? Or to test if the ipython instalation / setup works. 

Thank you! 

The full error stack trace is:
```
[2016-04-24T09:57Z] headNode: Timing: organize samples
[2016-04-24T09:57Z] headNode: ipython: organize_samples
2016-04-24 11:57:03.167 [IPClusterStop] Using existing profile dir: u'/data/run/Projects/SPECIES/Project-123/rerun_variant_calling/Project-123_samples/work/log/ipython'
2016-04-24 11:57:03.172 [IPClusterStop] Stopping cluster [pid=8290] with [signal=2]
2016-04-24 11:57:03.803 [IPClusterStop] Using existing profile dir: u'/data/run/Projects/SPECIES/Project-123/rerun_variant_calling/Project-123_samples/work/log/ipython'
2016-04-24 11:57:03.808 [IPClusterStop] Stopping cluster [pid=8290] with [signal=2]
^M0 Engines running^M0 Engines running^M0 Engines running^M0 Engines running^M1 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/data/Tools/bcbio-20160421/appdir/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/data/Tools/bcbio-20160421/appdir/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
    fc_dir, run_info_yaml)
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 119, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 135, in run
    for data in view.map_sync(fn, items, track=False):
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 344, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-138>", line 2, in map
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 52, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-137>", line 2, in map
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 37, in save_ids
    ret = f(self, *args, **kwargs)
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1104, in map
    return pf.map(*sequences)
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 269, in map
    ret = self(*sequences)
  File "<decorator-gen-120>", line 2, in __call__
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 252, in __call__
    return r.get()
  File "/data/Tools/bcbio-20160421/appdir/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 160, in get
    raise self.exception()
ipyparallel.error.CompositeError: one or more exceptions from call to method: organize_samples
[Engine Exception]SystemExit: 1
```

**Comment by chapmanb** [comment]
Neill;
Sorry about the issues. It's a bit tricky to tell what is going on here as I don't see an informative error message in the logs you posted. As you mention, all the `one or more exceptions from call to method` error does is tell you one of the engines failed.

In cases like this, it might be that sge or one of the machines is terminating a process due to memory or other constraints. In that case, looking at the `bcbio-ipengine*` log files from the SGE process might provide some clue. Errors here come from SGE itself so bcbio doesn't have access to them to insert them into the `bcbio-nextgen-debug.log` file. Fingers crossed this will turn up something.

This is not related to the error, but for running bcbio all you need to do is set the `PATH`, you don't need to set `LD_LIBRARY_PATH, PERL5LIB or PYTHONPATH`. We've tried to simplify the setup a lot so everything is self-contained now.

Hope the SGE logs turn up something useful.

**Comment by NeillGibson** [comment]
Hi Brad, 

Thank you for the information.  It might very well be that there is some incompatibility  between the newer (?) Ipython/ipyparallel and our cluster. 

Were can I find the `bcbio-ipengine*` log files?

I can't find a log file named `bcbio-ipengine* `    or  `*ipengine*` in the work dir. 

```
find ./work/  -name *ipengine*
./work/log/ipython/ipengine_config.py
```

The log files that I can find in the work directory are:

```
find work/ -name *.log
work/log/bcbio-nextgen.log
work/log/bcbio-nextgen-debug.log
work/log/bcbio-nextgen-commands.log
work/log/ipython/log/ipcluster-e2e5e0ed-c7c2-4f5d-b838-a53223632ec9-21081.log
work/log/ipython/log/ipcontroller-e2e5e0ed-c7c2-4f5d-b838-a53223632ec9-29685.log
work/log/ipython/log/ipcluster-0abe9db9-4d87-4b41-b9c7-fc8572a0787e-4089.log
work/log/ipython/log/ipcontroller-0abe9db9-4d87-4b41-b9c7-fc8572a0787e-7769.log
work/log/ipython/log/ipcluster-54f64620-8269-4721-9f3e-37fa66eb91f3-30771.log
work/log/ipython/log/ipcontroller-54f64620-8269-4721-9f3e-37fa66eb91f3-22582.log
```

Thank you for the help again.

**Comment by chapmanb** [comment]
Neill;
Sorry, I think they might be called `bcbio-e.o*` on SGE although I'm not sure if this is always the exact same naming on different SGE systems. They should be in the main work directory and are the SGE log files from each of the engines. Hope this helps find them.

**Comment by NeillGibson** [comment]
This issue fixed itself. Combination of updated installation of SGE and bcbio 0.9.8 works.

**Comment by roryk** [comment]
Thanks for following up Neill.
