### ISSUE TITLE
 CHIP-seq workflow error

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1360]
```
[2016-04-25T07:58Z] Approx 85% complete for anaerobic_INPUT_DNA-sort.bam
[2016-04-25T07:58Z] Approx 90% complete for anaerobic_INPUT_DNA-sort.bam
[2016-04-25T07:58Z] Approx 95% complete for anaerobic_INPUT_DNA-sort.bam
[2016-04-25T07:58Z] Approx 100% complete for anaerobic_INPUT_DNA-sort.bam
[2016-04-25T07:58Z] Analysis complete for anaerobic_INPUT_DNA-sort.bam
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 363, in chipseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 43, in generate_parallel
    samples = run_parallel("pipeline_summary", samples)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 131, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 71, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, data)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 133, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 490, in _run_fastqc
    shutil.move("%s.zip" % tx_fastqc_out, os.path.join(fastqc_out, "%s.zip" % fastqc_clean_name))
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/BiO/BioPeople/brandon/test_bcbio/chip-seq/chip-seq-test/work/qc/GSM1010224_r1/anaerobic_INPUT_DNA/fastqc/GSM1010224_r1/anaerobic_INPUT_DNA.zip'
```

I ran the Chip-seq workflow but, bcbio could not recognize the fastqc result path.

I'm checking this issue.

Thanks!

**Comment by hmkim** [comment]
I found the cause of problem.

In my configuration, description name involve the '/' character.

so, align step is ok. but qcsummary script can't handle the situation when description have the '/' character. 

In my case, '/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py'

anyway, I'll continue the running of chip-seq workflow in bcbio. 

Thanks.

**Comment by chapmanb** [comment]
Thanks for the report and diagnosing the problem. I pushed a fix which will clean up these problem characters in sample descriptions to avoid the problem going forward. Hope your run finishes cleanly now.

**Comment by hmkim** [comment]
Thanks for your comment. I finished the work cleanly.
