### ISSUE TITLE
MuTect inconsistent references for the same position

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1362]
I am unsure if this is truly a bcbio error or just a mutect issue, but the GATK forum did not have and support regarding my specific use. I am running a several WGS tumor/normal analysis. All of the sample pairs fail for some reason, but a few report this type of error when running MuTect.

```
[2016-04-13T23:48Z] Resource requests: ; memory: 1.00; cores: 1
[2016-04-13T23:48Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-04-13T23:48Z] Combine variant files
[2016-04-13T23:48Z] INFO  19:48:13,245 HelpFormatter - ---------------------------------------------------------------------------------
[2016-04-13T23:48Z] INFO  19:48:13,249 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.4-65-g2434e49, Compiled 2015/10/09 18:46:40
[2016-04-13T23:48Z] INFO  19:48:13,249 HelpFormatter - Copyright (c) 2010 The Broad Institute
[2016-04-13T23:48Z] INFO  19:48:13,250 HelpFormatter - For support and documentation go to http://www.broadinstitute.org/gatk
[2016-04-13T23:48Z] INFO  19:48:13,254 HelpFormatter - Program Args: -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -T CombineVariants -R /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --out /home/bwubb/NGS/BasserWGS/data/Brca1Br16-T/work/mutect/MT/tx/tmpiTVaeM/Batch1-MT_0_16569.vcf.gz --variant:v0 /home/bwubb/NGS/BasserWGS/data/Brca1Br16-T/work/mutect/MT/Batch1-MT_0_16569-mutect.vcf.gz --variant:v1 /home/bwubb/NGS/BasserWGS/data/Brca1Br16-T/work/mutect/MT/Batch1-MT_0_16569-somaticIndels.vcf.gz --rod_priority_list v0,v1 --genotypemergeoption PRIORITIZE --suppressCommandLineHeader --setKey null -L /home/bwubb/NGS/BasserWGS/data/Brca1Br16-T/work/mutect/MT/Batch1-MT_0_16569-regions.bed --interval_set_rule INTERSECTION
[2016-04-13T23:48Z] INFO  19:48:13,282 HelpFormatter - Executing as bwubb@x385001.hpc.local on Linux 2.6.32-504.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.7.0_71-mockbuild_2014_10_03_09_05-b00.
[2016-04-13T23:48Z] INFO  19:48:13,283 HelpFormatter - Date/Time: 2016/04/13 19:48:13
[2016-04-13T23:48Z] INFO  19:48:13,284 HelpFormatter - ---------------------------------------------------------------------------------
[2016-04-13T23:48Z] INFO  19:48:13,284 HelpFormatter - ---------------------------------------------------------------------------------
[2016-04-13T23:48Z] INFO  19:48:13,401 GenomeAnalysisEngine - Strictness is SILENT
[2016-04-13T23:48Z] INFO  19:48:13,607 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 1000
[2016-04-13T23:48Z] INFO  19:48:13,703 IntervalUtils - Processing 16569 bp from intervals
[2016-04-13T23:48Z] WARN  19:48:13,704 IndexDictionaryUtils - Track v0 doesn't have a sequence dictionary built in, skipping dictionary validation
[2016-04-13T23:48Z] WARN  19:48:13,704 IndexDictionaryUtils - Track v1 doesn't have a sequence dictionary built in, skipping dictionary validation
[2016-04-13T23:48Z] INFO  19:48:13,797 GenomeAnalysisEngine - Preparing for traversal
[2016-04-13T23:48Z] INFO  19:48:13,798 GenomeAnalysisEngine - Done preparing for traversal
[2016-04-13T23:48Z] INFO  19:48:13,799 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING]
[2016-04-13T23:48Z] INFO  19:48:13,800 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining
[2016-04-13T23:48Z] INFO  19:48:13,800 ProgressMeter -        Location |     sites | elapsed |     sites | completed | runtime |   runtime
[2016-04-13T23:48Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-04-13T23:48Z] ##### ERROR A USER ERROR has occurred (version 3.4-65-g2434e49):
[2016-04-13T23:48Z] ##### ERROR
[2016-04-13T23:48Z] ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2016-04-13T23:48Z] ##### ERROR The error message below tells you what is the problem.
[2016-04-13T23:48Z] ##### ERROR
[2016-04-13T23:48Z] ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2016-04-13T23:48Z] ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2016-04-13T23:48Z] ##### ERROR
[2016-04-13T23:48Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2016-04-13T23:48Z] ##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
[2016-04-13T23:48Z] ##### ERROR
[2016-04-13T23:48Z] ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
[2016-04-13T23:48Z] ##### ERROR
[2016-04-13T23:48Z] ##### ERROR MESSAGE: The provided variant file(s) have inconsistent references for the same position(s) at MT:309, C* vs. T*
[2016-04-13T23:48Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-04-13T23:48Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command '/home/bwubb/bcbio-tools/bin/gatk-framework -Xms750m -Xmx2000m -XX:+UseSerialGC -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -T CombineVariants -R /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --out /home/bwubb/NGS/BasserWGS/data/Brca1Br16-T/work/mutect/MT/tx/tmpiTVaeM/Batch1-MT_0_16569.vcf.gz --variant:v0 /home/bwubb/NGS/BasserWGS/data/Brca1Br16-T/work/mutect/MT/Batch1-MT_0_16569-mutect.vcf.gz --variant:v1 /home/bwubb/NGS/BasserWGS/data/Brca1Br16-T/work/mutect/MT/Batch1-MT_0_16569-somaticIndels.vcf.gz --rod_priority_list v0,v1 --genotypemergeoption PRIORITIZE --suppressCommandLineHeader --setKey null -L /home/bwubb/NGS/BasserWGS/data/Brca1Br16-T/work/mutect/MT/Batch1-MT_0_16569-regions.bed --interval_set_rule INTERSECTION
```
This will be repeated maybe three times, before a final returned non-zero exit status 1. I dont understand why this comes up in some samples but not others. I am working to trouble shoot what the problems with the other sample pairs might be. Has anyone encountered this specific case before?

**Comment by chapmanb** [comment]
Brad;
Thanks for the report. This looks like a manifestation of #1237 where scalpel has some issues setting reference bases with index based loading. I pushed a fix to development to avoid running scalpel on the mitochondrial chromosomes to work around it. If you update to the latest development and re-run it should hopefully skip this and finish cleanly. Let us know if you run into any other issues.
