### ISSUE TITLE
calc_callable_loci & IOError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by mattingsdal** [chapmanb/bcbio-nextgen#1365]
Hi,

I am setting up bcbio on my non-model organism using version 0.9.7.
I have aligned the reads prior to bcbio, and my config files looks like this:

```
details:
  - analysis: variant2
    genome: corkwing
    genome_build: v1
    # to do multi-sample variant calling, assign samples the same metadata / batch
    metadata:
    batch: batch
    algorithm:
          aligner: false
          mark_duplicates: true
          bam_clean: picard
          realign: false
          recalibrate: false
          variantcaller: ['freebayes','platypus']
          svcaller: lumpy
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed

```

bcbio & GATK succesfully cleans my aligned bam files.  However the pipeline breaks when writing callable regions to tmp folder. I should mention that I have approx 50 000 contigs and writing to an external USB drive. Could this be related to the error below ? 

```
[2016-04-26T11:51Z] Resource requests: sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16
[2016-04-26T11:51Z] Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job
[2016-04-26T11:51Z] Timing: organize samples
[2016-04-26T11:51Z] multiprocessing: organize_samples
[2016-04-26T11:51Z] Using input YAML configuration: /home/mortenma/data/corkwing/config/corkwing.yaml
[2016-04-26T11:51Z] Checking sample YAML configuration: /home/mortenma/data/corkwing/config/corkwing.yaml
[2016-04-26T11:51Z] Testing minimum versions of installed programs
[2016-04-26T11:51Z] Timing: alignment preparation
[2016-04-26T11:51Z] multiprocessing: prep_align_inputs
[2016-04-26T11:51Z] multiprocessing: disambiguate_split
[2016-04-26T11:51Z] Timing: alignment
[2016-04-26T11:51Z] multiprocessing: process_alignment
[2016-04-26T11:52Z] Timing: callable regions
[2016-04-26T11:52Z] multiprocessing: prep_samples
[2016-04-26T11:52Z] multiprocessing: postprocess_alignment
[2016-04-26T11:52Z] Resource requests: ; memory: 1.00; cores: 1
[2016-04-26T11:52Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-04-26T11:52Z] multiprocessing: calc_callable_loci
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.7', 'bcbio_nextgen.py')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script

  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg/pkg_resources/__init__.py", line 1504, in run_script

  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 130, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 71, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 182, in postprocess_alignment
    callable.block_regions(bam_file_ready, ref_file, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 328, in block_regions
    callable_bed = parallel_callable_loci(in_bam, ref_file, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 47, in parallel_callable_loci
    "callable_bed", ["config"])[0]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 247, in calc_callable_loci
    return callable.calc_callable_loci(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 63, in wrapper
    out = f(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 59, in calc_callable_loci
    region_file, calc_callable = _regions_for_coverage(data, region, ref_file, out_file)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 125, in _regions_for_coverage
    custom_file = _write_all_chrom_file(coverage_str, custom_file, ref_file, region, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 144, in _write_all_chrom_file
    with open(tx_out_file, "w") as out_handle:
IOError: [Errno 1] Operation not permitted: '/home/mortenma/data/corkwing/work/align/TV66_TGACCA_L004_BWA_sorted_bam/TV66_TGACCA_L004.BWA.sorted.bam-reorder-fixrgs-gatkfilter-dedup-callable-split/tx/tmpppoeZ1/TV66_TGACCA_L004.BWA.sorted.bam-reorder-fixrgs-gatkfilter-dedup-scf7180002340798-callable-coverageregions.bed'
```

**Comment by mattingsdal** [comment]
NB Ive tried "sudo" without success

**Comment by chapmanb** [comment]
Sorry about the issues. I'm not sure what is going on, but as a first recommendation you should never need to run bcbio as root or sudo user.

Regarding the problem, is your `/home` directory a standard filesystem or any kind of shared or otherwise different filesystem. Do you have permissions to create a directory outside of bcbio:
```
mkdir -p /home/mortenma/data/corkwing/work/align/TV66_TGACCA_L004_BWA_sorted_bam/TV66_TGACCA_L004.BWA.sorted.bam-reorder-fixrgs-gatkfilter-dedup-callable-split/tx/tmpppoeZ1/
touch /home/mortenma/data/corkwing/work/align/TV66_TGACCA_L004_BWA_sorted_bam/TV66_TGACCA_L004.BWA.sorted.bam-reorder-fixrgs-gatkfilter-dedup-callable-split/tx/tmpppoeZ1/TV66_TGACCA_L004.BWA.sorted.bam-reorder-fixrgs-gatkfilter-dedup-scf7180002340798-callable-coverageregions.bed
```
bcbio shouldn't be doing anything special with permissions so hopefully this'll give some clue if something is wrong. Hope this helps.

**Comment by lpantano** [comment]
Hi @mattingsdal 

I am closing this because it seems you could work around somehow the issue.

cheers
