### ISSUE TITLE
gemini argument unknown

### ISSUE THREAD

**Issue by kspham** [chapmanb/bcbio-nextgen#1368]
Hi Brad, 
Somehow bcbio throws error on gemini stage...
[2016-04-26T17:12Z] Create gemini database for /media/proj3/snow/projectall/work/gemini/Batch1-gatk-haplotype-decompose-effects.vcf.gz : BloodDNA_1s_S1
[2016-04-26T17:12Z] usage: gemini [-h] [-v]
[2016-04-26T17:12Z]               {examples,load,amend,load_chunk,merge_chunks,query,dump,region,stats,annotate,windower,db_info,comp_hets,pathways,lof_sieve,burden,interactions,lof_interactions,autosomal_recessive,autosomal_dominant,de_novo,browser,set_somatic,actionable_mutations,update,roh}
[2016-04-26T17:12Z]               ...
[2016-04-26T17:12Z] gemini: error: unrecognized arguments: --tempdir /media/proj3/snow/projectall/work/gemini/tx/tmpiRRRBb/Batch1-gatk-haplotype.db
[2016-04-26T17:12Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/bin/gemini load  --passonly --skip-cadd --skip-gerp-bp  -v /media/proj3/snow/projectall/work/gemini/Batch1-gatk-haplotype-decompose-effects.vcf.gz -t snpEff --cores 16 --tempdir /media/proj3/snow/projectall/work/gemini/tx/tmpiRRRBb /media/proj3/snow/projectall/work/gemini/tx/tmpiRRRBb/Batch1-gatk-haplotype.db
usage: gemini [-h] [-v]
              {examples,load,amend,load_chunk,merge_chunks,query,dump,region,stats,annotate,windower,db_info,comp_hets,pathways,lof_sieve,burden,interactions,lof_interactions,autosomal_recessive,autosomal_dominant,de_novo,browser,set_somatic,actionable_mutations,update,roh}
              ...
gemini: error: unrecognized arguments: --tempdir /media/proj3/snow/projectall/work/gemini/tx/tmpiRRRBb/Batch1-gatk-haplotype.db
' returned non-zero exit status 2
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 190, in run
    samples = population.prep_db_parallel(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 283, in prep_db_parallel
    output = parallel_fn("prep_gemini_db", to_process)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 144, in prep_gemini_db
    return population.prep_gemini_db(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 36, in prep_gemini_db
    gemini_db = create_gemini_db(gemini_vcf, data, gemini_db, ped_file)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 76, in create_gemini_db
    do.run(cmd, "Create gemini database for %s" % gemini_vcf, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/bin/gemini load  --passonly --skip-cadd --skip-gerp-bp  -v /media/proj3/snow/projectall/work/gemini/Batch1-gatk-haplotype-decompose-effects.vcf.gz -t snpEff --cores 16 --tempdir /media/proj3/snow/projectall/work/gemini/tx/tmpiRRRBb /media/proj3/snow/projectall/work/gemini/tx/tmpiRRRBb/Batch1-gatk-haplotype.db
usage: gemini [-h] [-v]
              {examples,load,amend,load_chunk,merge_chunks,query,dump,region,stats,annotate,windower,db_info,comp_hets,pathways,lof_sieve,burden,interactions,lof_interactions,autosomal_recessive,autosomal_dominant,de_novo,browser,set_somatic,actionable_mutations,update,roh}
              ...
gemini: error: unrecognized arguments: --tempdir /media/proj3/snow/projectall/work/gemini/tx/tmpiRRRBb/Batch1-gatk-haplotype.db

**Comment by roryk** [comment]
Hi Son,

It looks like you might have an old version of GEMINI installed that is missing the tempdir option. If you run ` /usr/local/bin/gemini --version` does it return something recent?

**Comment by lpantano** [comment]
Hi Son,

It seems you got this right. Please, let us know if you still have issues.

thanks
