### ISSUE TITLE
Run multiqc with large number of samples

### ISSUE THREAD

**Issue by jefarrar** [chapmanb/bcbio-nextgen#1380]
I'm running the cancer/normal pipeline on ~700 tumor/normal pairs with single variant and structural callers (vardict and manta) for some targeted resequencing. The pipeline appears to be close to wrapping up before I hit an uncaught exception for too many arguments in the process of summarizing qc:

...
[2016-05-05T13:26Z] n001.cluster.com: Generating summary files: samplen
[2016-05-05T13:26Z] clusterhn.cluster.com: ipython: coverage_report
[2016-05-05T13:26Z] clusterhn.cluster.com: ipython: qsignature_summary
[2016-05-05T13:26Z] clusterhn.cluster.com: ipython: qc_report_summary
[2016-05-05T13:26Z] n003.cluster.com: copy qsignature
[2016-05-05T13:26Z] n003.cluster.com: summarize fastqc
[2016-05-05T13:27Z] n003.cluster.com: summarize metrics
[2016-05-05T13:27Z] clusterhn.cluster.com: ipython: multiqc_summary
[2016-05-05T13:27Z] n002.cluster.com: Run multiqc
[2016-05-05T13:27Z] n002.cluster.com: Uncaught exception occurred
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/opt/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
[2016-05-05T13:27Z] n002.cluster.com: Unexpected error
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 45, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 254, in multiqc_summary
    return ipython.zip_args(apply(qcsummary.multiqc_summary, _args))
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 927, in multiqc_summary
    do.run(cmd.format(_*locals()), "Run multiqc")
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/opt/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
Sending a shutdown signal to the controller and engines.
2016-05-05 09:27:52.513 [IPClusterStop] Using existing profile dir: u'/home/jfarrar/validation/VarDict/vardict-TN-pairs/work/log/ipython'
2016-05-05 09:27:52.516 [IPClusterStop] Stopping cluster [pid=7654] with [signal=2]
2016-05-05 09:27:53.036 [IPClusterStop] Using existing profile dir: u'/home/jfarrar/validation/VarDict/vardict-TN-pairs/work/log/ipython'
2016-05-05 09:27:53.039 [IPClusterStop] Stopping cluster [pid=7654] with [signal=2]
Traceback (most recent call last):
  File "/opt/bcbio/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/opt/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 47, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 184, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 48, in generate_parallel
    samples = run_parallel("multiqc_summary", [samples])
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 135, in run
    for data in view.map_sync(fn, items, track=False):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 344, in map_sync
    return self.map(f,_sequences,__kwargs)
  File "<decorator-gen-138>", line 2, in map
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 52, in sync_results
    ret = f(self, *args, *_kwargs)
  File "<decorator-gen-137>", line 2, in map
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 37, in save_ids
    ret = f(self, _args, *_kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1104, in map
    return pf.map(_sequences)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 269, in map
    ret = self(_sequences)
  File "<decorator-gen-120>", line 2, in __call__
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, _args, *_kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 252, in **call**
    return r.get()
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 160, in get
    raise self.exception()
ipyparallel.error.CompositeError: one or more exceptions from call to method: multiqc_summary
[Engine Exception]OSError: [Errno 7] Argument list too long

The final command in log is huge, with what looks like a reference to every remission sample--

fastqc /home/jfarrar/validation/VarDict/vardict-TN-pairs/work/qc/sample1/samtools [... /home/jfarrar/validation/VarDict/vardict-TN-pairs/work/qc/samplen/samtools] align   report/_/_bcbio\* -o /net/clusterhn.cluster.com/home/jfarrar/validation/VarDict/vardict-TN-pairs/work/tx/tmpy8naHY 

Any suggestions for a workaround?

**Comment by chapmanb** [comment]
Sorry about the problem with the new MultiQC support. We're going to work to make it easier to specify larger sample sizes via an input file rather than on the commandline. For an immediate workaround, we limited the number of directories passed to avoid the error. It'll probably take some work to make MultiQC output useful for larger sample sizes like this, so you won't lose much by not having it now. If you update to the latest development with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run your analysis in place it should pick up where it left off and hopefully create a reasonable command line. Thanks again for the report and hope this works for you.

**Comment by ewels** [comment]
On a general note, I'd love to see a MultiQC report generated for 700 samples. I would _hope_ that MultiQC can cope and that the reports are still useful (I've had these kinds of sample sizes in mind when writing code - for example with the recently added flat image plots), but I've not seen anything with more than about 200.

**Comment by lpantano** [comment]
sounds, good, we can add that flag in case samples are more than 100 or similar. Good idea!

**Comment by ohofmann** [comment]
I just explored it with ~100 samples. That worked, though some plots became less useful -- the barplots in particular are very crowded and it is tough to hover over one specific sample; the y axis labels are also of limited use as only every Nth sample has one. Still, it worked, so not complaining ;)

**Comment by jefarrar** [comment]
Thanks, this looks like it was an effective intermediate solution, at least in that worked in getting the run to completion. I haven't explored MultiQC enough to comment, but I'll be curious to check out the updates.

You guys are awesome, by the bye.

**Comment by ewels** [comment]
Thanks for the feedback @ohofmann! I added a new plot type (beeswarm / dot plot) in the last release to cope with large sample numbers in the General Statistics table at the top. I could look into replacing bar plots with this as well I guess. Otherwise, you can always drag the grey bar to make them taller, though I appreciate that this only works to a certain extent :) Feel free to add some issues over at https://github.com/ewels/MultiQC/issues if you have any further suggestions.

Phil

**Comment by ohofmann** [comment]
@ewels Thanks! Will keep testing it with different sample configurations; right now trying to figure out how to best display tumor/normal pairs which (still) are sequenced at different depths (hence @lpantano inquiry about using metadata for sample groups). More feature requests on your repo soon ;)

**Comment by lpantano** [comment]
Hi all,

thanks for the comment. I will close this since it is supposed to accept now all the samples since the code accepted file with the input files inside.

feel free to re-open any specific question for the current version.

cheers

**Comment by ewels** [comment]
Just a quick note to highlight the recent addition to MultiQC of "custom content" support - could be useful for you guys, for example an easy way to insert extra metadata into the General Statistics table and so on.

See the (crappy) documentation here: http://multiqc.info/docs/#custom-content (due to be rewritten when I get time). Example data that I've used to write the feature are [here](https://github.com/ewels/MultiQC_TestData/tree/master/data/custom_content).

**Comment by chapmanb** [comment]
Phil;
Thanks much for the cool new way to do things. So far we've been okay with using the custom bcbio module Lorena and Vlad put together but we'll definitely dig into this in the future if we need to add new things.

**Comment by ewels** [comment]
Great! Yes we're the same - most of this stuff we handle in our own [custom module](https://github.com/ewels/MultiQC_NGI). But I think it's nice to try to generalise where possible, means that people everywhere will get comparable results using the output from your tools. Also quicker to set up :)
