### ISSUE TITLE
bcbio_setup_genome.py bug?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1381]
Dear bcbio developers,

I'm trying to create a custom database for miRNA analysis on Solanum tuberosum with the next command: 

`bcbio_setup_genome.py -f GCF_000226075.1_SolTub_3.0_genomic.fna --gff3 -g GCF_000226075.1_SolTub_3.0_genomic.gff -n stuberosum -b soltub3 --mirbase stu -i star --srna_gtf GCF_000226075.1_SolTub_3.0_genomic.gtf -c 5`

(I've created gtf with cufflinks)

The first attempt failed almost at the end (after STAR index) because of the bug in the annotation. 
I've fixed the annotation, and re-run the command (without deleting files).
And it is doing something unexpected: bowtie2 index, tophat run.

Sure, I can re-run it from scratch, but is there any chance to continue after STAR index stage?

Thanks,
Sergey

**Comment by roryk** [comment]
Hi Sergey,

It will always make the Tophat index, but it should make the STAR index as well. Is it not working?

**Comment by naumenko-sa** [comment]
Unfortunately it crashes
`
/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/stuberosum/soltub3/rnaseq-2016-05-05/tx/
Traceback (most recent call last):
  File "/home/naumenko/work/tools/bin/bcbio_setup_genome.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.7', 'bcbio_setup_genome.py')
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 1483, in run_script
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_setup_genome.py", line 279, in <module>
    install_srna(args.mirbase, args.srna_gtf)
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_setup_genome.py", line 162, in install_srna
    shutil.copyfile(gtf, out_file)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'GCF_000226075.1_SolTub_3.0_genomic.gtf'
`

**Comment by roryk** [comment]
Hi Sergey,

Sorry about that-- in the code, it looks like we are maybe expecting a full path to that file. If you provide the full path on the command line, does it work? If it does I'll swap the code to fix that.

**Comment by naumenko-sa** [comment]
Hi Rory,
yes, with full path it works.
Fix please: from docs the usage of full path is not obvious.
Thanks,
Sergey
