### ISSUE TITLE
Consistent BWA reference files not found error upon re-installing genome files.

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1382]
Hi Brad;

I am keep getting a error related hg38 BWA genome files consistently. I have tried `bcbio_nextgen.py --upgrade hg38` 3 times and in all of them I get successful installation output. When I check the bwa hg38 reference directory. I also found some files about bwa which confused me. Could you help me out to get around with this issue ? Am I misssing a point ?

Thank you very much, 

Best regards,

T. 

**Error**

```
[tmorova15@lufer work]$ cat deneme1error 
[2016-05-05T20:57Z] Resource requests: bwa, sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16, 16
[2016-05-05T20:57Z] Configuring 1 jobs to run, using 16 cores each with 32.1g of memory reserved for each job
[2016-05-05T20:57Z] Timing: organize samples
[2016-05-05T20:57Z] multiprocessing: organize_samples
[2016-05-05T20:57Z] Using input YAML configuration: /mnt/scratch/tmorova15/run/cancer-syn3-chr6/config/cancer-syn3-chr6.yaml
[2016-05-05T20:57Z] Checking sample YAML configuration: /mnt/scratch/tmorova15/run/cancer-syn3-chr6/config/cancer-syn3-chr6.yaml
[2016-05-05T20:57Z] Downloading hg38 bwa from AWS
Traceback (most recent call last):
  File "/mnt/scratch/tmorova15/bcbio/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.7', 'bcbio_nextgen.py')
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script

  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg/pkg_resources/__init__.py", line 1504, in run_script

  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 115, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 295, in organize_samples
    return run_info.organize(*args)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 66, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 157, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 207, in get_refs
    galaxy_config, data)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 159, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 277, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file hg38 bwa

```

**BWA folder**

```
/mnt/scratch/tmorova15/bcbio/genomes/Hsapiens/hg38/bwa
[tmorova15@lufer bwa]$ ls
hg38.fa.alt  hg38.fa.amb  hg38.fa.ann  hg38.fa.bwt  hg38.fa.pac  hg38.fa.sa
```

**Comment by chapmanb** [comment]
Tunc;
Sorry about the problem. I'm not sure what exactly is going wrong with your installation, but it seems like it's having trouble finding the right configuration directory with file paths when running. My guess is that it might be picking up a different bcbio_system.yaml file when running that is not your installed one. I have a flag that helps debug this in the latest development. If you update to that:
```
bcbio_nextgen.py upgrade -u development
```
and then re-run there should be a logging line about the bcbio system YAML file used for the run. Is that the one in `/mnt/scratch/tmorova15/bcbio/galaxy/bcbio_system.yaml` or somewhere else? If somewhere else it might not be pointing at the installed reference data and thus be unable to find it. Hope this helps some with debugging and happy to try and provide more pointers with this information.

**Comment by mortunco** [comment]
```
[tmorova15@lufer galaxy]$ ls
bcbio_system.yaml  bcbio_system.yaml.bak20161804_1018  bcbio_system.yaml.bak20163304_1033  bcbio_system.yaml.bak20165303_2353  tool-data  tool_data_table_conf.xml

``` 
my current galaxy folder situation. I am aware that now there is conflicting bcbio_systems.yaml but not sure to remove which one. 

Unfortunetely, I might need your guidance  about running it. Because my hpc does not allow me to run from the terminal. We have our own queuing system therefore, could you help me to specify configuration ?


file that I use for the queuing
```
[tmorova15@lufer work]$ cat example 
#!/bin/bash
#$ -N deneme_lufer
#$ -S /bin/bash
#$ -q all.q
#$ -pe smp 1
#$ -cwd
#$ -o deneme1out
#$ -e deneme1error
#$ -M tmorova15@ku.edu.tr
#$ -m bea
#$ -j no
#$ -R y

/mnt/scratch/tmorova15/bcbio/bin/bcbio_nextgen.py -n 16 ../config/cancer-syn3-chr6.yaml
```

**Comment by mortunco** [comment]
```
[tmorova15@lufer work]$ bcbio_nextgen.py -n 1 /mnt/scratch/tmorova15/bcbio/galaxy/bcbio_system.yaml ../config/cancer-syn3-chr6.yaml 
[2016-05-06T12:09Z] System YAML configuration: /mnt/scratch/tmorova15/bcbio/galaxy/bcbio_system.yaml
[2016-05-06T12:09Z] Resource requests: bwa, sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16, 16
[2016-05-06T12:09Z] Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job
[2016-05-06T12:09Z] Timing: organize samples
[2016-05-06T12:09Z] multiprocessing: organize_samples
[2016-05-06T12:09Z] Using input YAML configuration: /mnt/scratch/tmorova15/run/cancer-syn3-chr6/config/cancer-syn3-chr6.yaml
[2016-05-06T12:09Z] Checking sample YAML configuration: /mnt/scratch/tmorova15/run/cancer-syn3-chr6/config/cancer-syn3-chr6.yaml
[2016-05-06T12:09Z] Downloading hg38 bwa from AWS
Traceback (most recent call last):
  File "/mnt/scratch/tmorova15/bcbio/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/mnt/scratch/tmorova15/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 120, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 295, in organize_samples
    return run_info.organize(*args)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 65, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 156, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 207, in get_refs
    galaxy_config, data)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 159, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 277, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file hg38 bwa
```

This is my output from running with bcbio_system.yaml ?

**Comment by chapmanb** [comment]
Tunc;
Thanks for the additional details and help debugging. It looks like it's finding the right bcbio_system file, which is good, so the next step is figuring out why it doesn't point to your installed data. Could you check the output of:
```
grep 'galaxy_config'  /mnt/scratch/tmorova15/bcbio/galaxy/bcbio_system.yaml
grep 'hg38' /mnt/scratch/tmorova15/bcbio/galaxy/tool-data/*.loc
```
The `galaxy_config` input should just be `universe_wsgi.ini` and the lines in the *.loc file should point to `/mnt/scratch/tmorova15/bcbio/genomes/Hsapiens/hg38`. If anything looks off happy to try and offer more advice.

**Comment by mortunco** [comment]
Hi Brad;

As I understood from the output of the commands that you sugessted, it was like you said. I also shared my .bashrc to be sure that I am not targeting a wrong folder or etc. 

Also, all of the bcbio_system.yaml s were same. I checked the content with ``` diff ``` and couldnt find anything.

Thank you very much for your help,

Best regards,

Tunc.


```
bcbio  bcbio_nextgen_install.py  bio  requirements-conda.txt  run
[tmorova15@lufer tmorova15]$ grep 'galaxy_config'  /mnt/scratch/tmorova15/bcbio/galaxy/bcbio_system.yaml
galaxy_config: universe_wsgi.ini
[tmorova15@lufer tmorova15]$ grep 'hg38' /mnt/scratch/tmorova15/bcbio/galaxy/tool-data/*.loc
/mnt/scratch/tmorova15/bcbio/galaxy/tool-data/gatk_sorted_picard_index.loc:hg38	hg38	Human (hg38) full	/mnt/scratch/tmorova15/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa
/mnt/scratch/tmorova15/bcbio/galaxy/tool-data/picard_index.loc:hg38	hg38	Human (hg38) full	/mnt/scratch/tmorova15/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa
/mnt/scratch/tmorova15/bcbio/galaxy/tool-data/sam_fa_indices.loc:index	hg38	/mnt/scratch/tmorova15/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa

```

Also, I would like to share my .bashrc to be sure about the problem is not related to system environments.
```

export PATH=/share/apps/java/jre1.8.0_91/bin:$PATH
export LD_LIBRARY_PATH=/share/apps/java/jre1.8.0_91/lib:$LD_LIBRARY_PATH

export PATH=/share/apps/python-2.7.2/bin:$PATH
export LD_LIBRARY_PATH=/share/apps/python-2.7.2/lib:$LD_LIBRARY_PATH

export PATH=/share/apps/gcc/gcc-4.6.2/bin:$PATH
export LD_LIBRARY_PATH=/share/apps/gcc/gcc-4.6.2/lib64:/share/apps/gcc/gcc-4.6.2/lib:/usr/lib:/usr/lib64:$LD_LIBRARY_PATH
export LC_ALL=en_US.UTF-8
export PYTHONPATH=/mnt/scratch/tmorova15/bcbio/anaconda/bin

#CloudBioLinux PATH updates
export PATH=/mnt/scratch/tmorova15/bcbio/bin:/mnt/scratch/tmorova15/bcbio/galaxy:$PATH
```

**Comment by chapmanb** [comment]
Tunc;
Thanks for the detailed output. It looks like your install is missing the `bwa_index.loc` file, which tells bcbio the location of the bwa index files. This is why it's not finding them. It is possible your install failed at some point during the run so they were downloaded but not indexed? You should be able to update in place to fix this:
```
bcbio_nextgen.py upgrade -u development
bcbio_nextgen.py upgrade --data --genomes hg38 --aligners bwa
```
Hope this resolves it for you.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
