### ISSUE TITLE
Verdict Error -> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/astrazeneca/vardict/Main : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1386]
Dear @mjafin and @chapmanb;

I am getting the followed error. As I experienced a little bit from my previously asked issues, I realised that it might be related with Java version. Am I missing something??

Thank you very much,

Best regards,

Tunc.

Java version.
```
[tmorova15@lufer log]$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```
My error.
```
[tmorova15@lufer log]$ cat bcbio-nextgen.log
[2016-05-09T11:55Z] System YAML configuration: /mnt/scratch/tmorova15/bcbio/galaxy/bcbio_system.yaml
[2016-05-09T11:55Z] Timing: organize samples
[2016-05-09T11:55Z] multiprocessing: organize_samples
[2016-05-09T11:55Z] Using input YAML configuration: /mnt/scratch/tmorova15/run/cancer-syn3-chr6/config/cancer-syn3-chr6.yaml
[2016-05-09T11:55Z] Checking sample YAML configuration: /mnt/scratch/tmorova15/run/cancer-syn3-chr6/config/cancer-syn3-chr6.yaml
[2016-05-09T11:55Z] Testing minimum versions of installed programs
[2016-05-09T11:55Z] Timing: alignment preparation
[2016-05-09T11:55Z] multiprocessing: prep_align_inputs
[2016-05-09T11:59Z] multiprocessing: disambiguate_split
[2016-05-09T11:59Z] Timing: alignment
[2016-05-09T11:59Z] multiprocessing: process_alignment
[2016-05-09T11:59Z] Aligning lane 1_2015-11-18_syn3-cshl with bwa aligner
[2016-05-09T12:26Z] Aligning lane 2_2015-11-18_syn3-cshl with bwa aligner
[2016-05-09T12:53Z] multiprocessing: delayed_bam_merge
[2016-05-09T13:06Z] multiprocessing: merge_split_alignments
[2016-05-09T13:06Z] Timing: callable regions
[2016-05-09T13:06Z] multiprocessing: prep_samples
[2016-05-09T13:06Z] multiprocessing: postprocess_alignment
[2016-05-09T13:06Z] multiprocessing: calc_callable_loci
[2016-05-09T13:07Z] multiprocessing: combine_bed
[2016-05-09T13:09Z] syn3-tumor: Assigned coverage as 'regional' with 0.2% genome coverage and 54.7% offtarget coverage
[2016-05-09T13:09Z] multiprocessing: calc_callable_loci
[2016-05-09T13:10Z] multiprocessing: combine_bed
[2016-05-09T13:11Z] syn3-normal: Assigned coverage as 'regional' with 0.2% genome coverage and 54.7% offtarget coverage
[2016-05-09T13:11Z] multiprocessing: combine_sample_regions
[2016-05-09T13:11Z] Identified 11 parallel analysis blocks
Block sizes:
  min: 5526195
  5%: 10807108.5
  25%: 16127507.5
  median: 16354210.0
  75%: 16738150.5
  95%: 17141083.0
  99%: 17198416.6
  max: 17212750
Between block sizes:
  min: 579
  5%: 603.3
  25%: 724.25
  median: 3046.5
  75%: 24949.5
  95%: 41942.1
  99%: 46435.62
  max: 47559

[2016-05-09T13:11Z] Timing: hla typing
[2016-05-09T13:11Z] multiprocessing: call_hla
[2016-05-09T13:13Z] Timing: alignment post-processing
[2016-05-09T13:13Z] multiprocessing: piped_bamprep
[2016-05-09T13:13Z] Timing: variant calling
[2016-05-09T13:13Z] multiprocessing: variantcall_sample
[2016-05-09T13:13Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/mnt/scratch/tmorova15/bcbio/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3000m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/vardict/chr6/tx/tmphb5rVv' && vardict-java -G /mnt/scratch/tmorova15/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa -f 0.02 -N syn3-tumor -b "/mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/align/syn3-tumor/syn3-tumor-sort.bam|/mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/align/syn3-normal/syn3-normal-sort.bam" -c 1 -S 2 -E 3 -g 4 -Q 10 /mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/vardict/chr6/syn3-chr6_0_16129694-regions-regionlimit.bed | testsomatic.R | var2vcf_paired.pl -P 0.9 -m 4.25 -f 0.02  -M  -N "syn3-tumor|syn3-normal" | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null | /mnt/scratch/tmorova15/bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "bwa")' | sed 's/\\.*Somatic\\/Somatic/' | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/' | /mnt/scratch/tmorova15/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /mnt/scratch/tmorova15/bcbio/anaconda/bin/vcfstreamsort | bgzip -c > /mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/vardict/chr6/tx/tmphb5rVv/syn3-chr6_0_16129694.vcf.gz
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/astrazeneca/vardict/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
Could not find the main class: com.astrazeneca.vardict.Main.  Program will exit.
Use of uninitialized value $sample in concatenation (.) or string at /mnt/scratch/tmorova15/bcbio/anaconda/bin/var2vcf_paired.pl line 35.
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Tunc;
You're exactly right. You need Java 1.7 to run VarDict and several other tools in bcbio like GATK derived Java programs. If you use that version it should avoid this error. Hope this helps.

**Comment by mortunco** [comment]
Brad;

I tried the same process with Java 1.7. However, same error came up again. I am willing to do everything you may suggest. 

Thank you for your help,

Best regards,

Tunc.

```
[tmorova15@lufer log]$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

```

[2016-05-10T05:55Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/scratch/tmorova15/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/mnt/scratch/tmorova15/bcbio/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx3000m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/vardict/chr6/tx/tmpBpjOm8' && vardict-java -G /mnt/scratch/tmorova15/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa -f 0.02 -N syn3-tumor -b "/mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/align/syn3-tumor/syn3-tumor-sort.bam|/mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/align/syn3-normal/syn3-normal-sort.bam" -c 1 -S 2 -E 3 -g 4 -Q 10 /mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/vardict/chr6/syn3-chr6_0_16129694-regions-regionlimit.bed | testsomatic.R | var2vcf_paired.pl -P 0.9 -m 4.25 -f 0.02  -M  -N "syn3-tumor|syn3-normal" | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null | /mnt/scratch/tmorova15/bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "bwa")' | sed 's/\\.*Somatic\\/Somatic/' | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/' | /mnt/scratch/tmorova15/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /mnt/scratch/tmorova15/bcbio/anaconda/bin/vcfstreamsort | bgzip -c > /mnt/scratch/tmorova15/run/cancer-syn3-chr6/work/vardict/chr6/tx/tmpBpjOm8/syn3-chr6_0_16129694.vcf.gz
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/astrazeneca/vardict/Main : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
Could not find the main class: com.astrazeneca.vardict.Main.  Program will exit.
Use of uninitialized value $sample in concatenation (.) or string at /mnt/scratch/tmorova15/bcbio/anaconda/bin/var2vcf_paired.pl line 35.
' returned non-zero exit status 1

```

**Comment by chapmanb** [comment]
Tunc;
Sorry about the continued problems. Do you have `JAVA_HOME` set:
```
echo JAVA_HOME
```
If that points to a non-1.7 version of Java the wrapper scripts will pick it up first and use it. Hope that explains it.

**Comment by mortunco** [comment]
You were right, it was soft linked to 1.6. I changed the path and it worked!.

Thank you very much !!
