### ISSUE TITLE
RADAR-GRCh37

### ISSUE THREAD

**Issue by sib-bcf** [chapmanb/bcbio-nextgen#1388]
Hello,
I've seen that there is already a close issue on the subject (https://github.com/chapmanb/bcbio-nextgen/issues/1260), but I'm opening it again since I got stuck in the apparently the same problem.

I've done a fresh install in a docker container, building from the docker file https://github.com/chapmanb/bcbio-nextgen/blob/master/Dockerfile#L5
Everything went fine.

Then, I've tried to add the reference genome with the command line:
bcbio_nextgen.py upgrade --data --genomes GRCh37 --aligners bwa --aligners star

which stopped with the following message:

Running GGD recipe: RADAR-GRCh37
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 282, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 474, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 796, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/bcbio-data/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/bcbio-data/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 8

Thank you in advance for your help,
Paolo

**Comment by chapmanb** [comment]
Paolo;
Sorry about the problems. It looks like the database we download from Stanford for RNA-editing events is down right now. I dropped it from the install to work around the problems and will work with @roryk to update the install recipes to a cached version. So if you remove your cached CloudBioLinux:
```
rm -rf tmpbcbio-install
```
and re-run it should skip this step and hopefully finish cleanly now. Thanks much for the report.

**Comment by sib-bcf** [comment]
Thank you Brad.

It worked like a charm.
