### ISSUE TITLE
Merge samples: IndexError: list index out of range

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1399]
Hi,
Using bcbio-nextgen 0.9.7 development version, I ran

bcbio_prepare_samples.py --out merged --csv samples.csv

to merge multiple files per sample, which I had never found any error previously.

However, I found the following error this time after 65 merged files had been successfully generated (it should have 112 merged  files)

Traceback (most recent call last):
  File "/user/parallel/bcbio/anaconda/bin/bcbio_prepare_samples.py", line 136, in <module>
    samples = run_parallel("prepare_bcbio_samples", samples)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 55, in prepare_bcbio_samples
    return sample.prepare_bcbio_samples(*args)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 323, in prepare_bcbio_samples
    out_file = fq_merge(sample['files'], sample['out_file'], sample['config'])
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/fastq.py", line 115, in merge
    pair2 = [fastq_file[1] for fastq_file in files]
IndexError: list index out of range

**Comment by lpantano** [comment]
Hi,

sorry about this. Any chance you can update to last development and run with a single core to know at least one sample that is giving problems? I added some more info that may help to understand better. Is like not getting the paired file for some reason.

thanks

**Comment by pengxiao78** [comment]
Thank you! I have found that one file was missing. 
Thanks again!

**Comment by lpantano** [comment]
nice, let me know if you have further issues.

**Comment by leiendeckerlu** [comment]
I can add to this error, that it is also thrown if the filename includes dots, like Foo.bar_R2.fastq . It might be useful if you add this to the manual, took me some time to debug this.

**Comment by lpantano** [comment]
oh, sorry about this. I added. I'll try to add a warning as well.
