### ISSUE TITLE
Upgraded to latest dev version of BCBIO but now automated sample configuration no longer works

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1408]
Hi
I upgraded to the latest dev version of BCBIO (0.9.9a) and now when I try to generate the sample yaml using the automatic template generation function I get the following Traceback error:
``` python
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 5, in <module>
    pkg_resources.run_script('bcbio-nextgen==0.9.9a', 'bcbio_nextgen.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/bcbio_nextgen-0.9.9a-py2.7.egg/EGG-INFO/scripts/bcbio_nextgen.py", line 33, in <module>
    from bcbio import install, utils, workflow
  File "/usr/local/lib/python2.7/dist-packages/bcbio_nextgen-0.9.9a-py2.7.egg/bcbio/install.py", line 19, in <module>
    from fabric.api import env
ImportError: No module named fabric.api
```
Any advice/help appreciated.

**Comment by chapmanb** [comment]
Kevin;
It looks like something is a bit strange about your bcbio install. It's pulling bcbio from the `/usr/local/bin/python` instead of the isolated `/path/to/bcbio/anaconda/bin/python` it should use. As a result, it's not finding some of the dependencies, like fabric, which should be installed inside the `anaconda` directory.

I'm not positive how it got into this state but your best bet might be to remove the broken install in `/usrl/local/bin` and try to upgrade directly from `/path/to/bcbio/anaconda/bin/bcbio_nextgen.py` and then restore the `/usr/local/bin` symlink to here. Sorry about the issues and hope this gets it sorted out.

**Comment by kevjp** [comment]
Thanks Brad;
Not exactly sure what happened but I re-installed from scratch and it seemed to be running fine. However I am now experiencing another issue with providing enough memory to run:

``` bash
 java -Xms681m -Xmx1g -XX:+UseSerialGC -Djava.io.tmpdir=/home/kevin/Documents/NGS_Pipeline/INDELanalysis/AmpliconIndel20x-100x160527/validation/work/tx/tmp78ZE5G -jar /usr/local/share/bcbio/toolplus/gatk/3.5-0-g36282e4/GenomeAnalysisTK.jar -T IndelRealigner -I /home/kevin/Documents/NGS_Pipeline/INDELanalysis/AmpliconIndel20x-100x160527/validation/work/bamprep/Pool3_indel_sort_x1000Total_GATK_HC/X/Pool3_indel_sort_x1000Total-reorder-fixrgs-gatkfilter-X_93113273_108631036-prep-prealign.bam -R /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -targetIntervals /home/kevin/Documents/NGS_Pipeline/INDELanalysis/AmpliconIndel20x-100x160527/validation/work/bamprep/Pool3_indel_sort_x1000Total_GATK_HC/X/Pool3_indel_sort_x1000Total-reorder-fixrgs-gatkfilter-X_93113273_108631036-prep-prealign-realign.intervals -L X:93113274-108631036 --knownAlleles /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation/Mills_and_1000G_gold_standard.indels.vcf.gz -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -o /home/kevin/Documents/NGS_Pipeline/INDELanalysis/AmpliconIndel20x-100x160527/validation/work/bamprep/Pool3_indel_sort_x1000Total_GATK_HC/X/tx/tmpM_qqKV/Pool3_indel_sort_x1000Total-reorder-fixrgs-gatkfilter-X_93113273_108631036-prep.bam```

I have raised it as a separate issue
