### ISSUE TITLE
rnaseq adapters false

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1417]
I have explicit set adapters: false in the yaml file, and I get this error.
(I have remove the line and is working as expected... just want to report)
Thanks 

[2016-06-02T16:14Z] cpu-6-1.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 450, in organize_samples
    return ipython.zip_args(apply(run_info.organize, *args))
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 47, in organize
    run_details = _run_info_from_yaml(dirs, run_info_yaml, config, sample_names)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 742, in _run_info_from_yaml
    _check_sample_config(run_details, run_info_yaml, config)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 571, in _check_sample_config
    [_check_algorithm_values(x) for x in items]
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 440, in _check_algorithm_values
    % (item["description"], "\n".join(problems), ALG_DOC_URL))
ValueError: Incorrect settings in 'algorithm' section for cll_10126_rnaseq:
adapters set as false
See configuration documentation for supported options:
https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#algorithm-parameters

**Comment by chapmanb** [comment]
The error comes from the initial lint step where it checks if things in the YAML are valid. It's indicating that `false` is not a valid input for `adapters`, which I believe is right. You should just leave off adapters if you don't want to include them, as you did. Hope this helps explain it.

**Comment by apastore** [comment]
Sure you are right but in the manual the adapter: false option is listed. (I was just point out this small discrepancy)

I am also wondering if it would not make sense to check the attribute of the yaml file when it get generated. (Sometime is frustrated to (wait the ) start a large cluster just to figure out the yaml file is not ok.

Thanks!

**Comment by chapmanb** [comment]
We'd definitely like to fix the documentation if it's incorrect. I don't see false listed as an option here but maybe there is another location I'm missing:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

Where did you notice it? Thanks again.

**Comment by apastore** [comment]
sorry! I mixed up adapter and trim_reads options ( I was searching for adapter and is first nominated in the trim_reads parameters, at the begin of the line )
