### ISSUE TITLE
Oncofuse and java

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1418]
Running Oncofuse I get this error... I am wondering if oncofuse has to be call by java.

[2016-06-02T22:31Z] gpu-2-10.local: Error: Invalid or corrupt jarfile /cbio/cslab/nobackup/pastore/bcbio/galaxy/../anaconda/bin/oncofuse
[2016-06-02T22:31Z] gpu-2-10.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; java -Xms750m -Xmx2000m -jar /cbio/cslab/nobackup/pastore/bcbio/galaxy/../anaconda/bin/oncofuse /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/rnaseq/rnaseq/work/align/cll_129_rnaseq/56_2016-06-02_rnaseqChimeric.out.junction.hg19 rnastar-2-4 AVG /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/rnaseq/rnaseq/work/align/cll_129_rnaseq/tx/tmpkY1GEM/oncofuse_out.txt
Error: Invalid or corrupt jarfile /cbio/cslab/nobackup/pastore/bcbio/galaxy/../anaconda/bin/oncofuse
' returned non-zero exit status 1
[2016-06-02T22:31Z] gpu-2-10.local: oncofuse failed : cll_129_rnaseq

**Comment by roryk** [comment]
Hi @apastore,

This works fine on the tests for me for some reason, but I agree we shouldn't be calling it like that. I pushed a change to use the wrapper properly-- does it fix the issue for you?

**Comment by apastore** [comment]
Thanks! now is running clean also on my data

**Comment by roryk** [comment]
Awesome-- thanks for following up.
