### ISSUE TITLE
GATK 3.6 doesn't work with the pipeline

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1420]
```
ValueError: Problem getting version for GATK. This often indicates you're not running Java 1.7:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/gatk/engine/CommandLineGATK : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by lbeltrame** [comment]
It seems that the new GATK version doesn't like openJDK 1.7.

**Comment by chapmanb** [comment]
Luca -- thanks for the heads up. We haven't tested and started migration to 3.6 yet but if you want to run it immediately it looks like you'll need java 1.8 installed and first on your PATH instead of 1.7. For bcbio we're planning to start using the bioconda install java going forward, and will upgrade gatk-framework to 3.6 to use Java 1.8 as well. I'll plan to track progress in this thread. Thanks again.

**Comment by chapmanb** [comment]
Luca -- thanks again for pushing on 3.6 compatibility. bcbio supports GATK 3.6 (and older versions) with the new 0.9.9 release. We now ship Java 8 with bcbio so will use the internal version and there is no need for an external Java. You do still need an external Java 1.7 if you want to run older versions of GATK but otherwise everything is now self-contained. There is a current known problem with 3.6 on some samples that is now fixed in nightlies if you start testing with this:

http://gatkforums.broadinstitute.org/gatk/discussion/7756/hashmap-iterator-problem-with-gatk-3-6-on-na12878-validations

Thanks again and hope the new version gets GATK 3.6 running for your analyses.

**Comment by yangming** [comment]
gatk doesn't work with openjdk, that's a shame!

**Comment by chapmanb** [comment]
Thanks for the message. Are you running in practical issues running GATK with openjdk and bcbio? I don't believe the GATK team officially supports openjdk but we run with it regularly and haven't encountered any issues. Hope this helps.
