### ISSUE TITLE
Alignment or Samblaster issue?

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1422]
I am having an issue with one sample out of many. This is older data that has worked in the past, being rerun through bcbio. Something is happening during alignment; a few errors spaced out and then a crash.

```
[2016-06-07T15:28Z] [mem_sam_pe] paired reads have different names: "HWI-ST965:305:C0MR9ACXX:6:1209:6490:3773", "HWI-ST965:305:C0MR9ACXX:6:1303:2738:37310"
[2016-06-07T15:28Z] 
[2016-06-07T15:28Z] samblaster: Output 380511 discordant read pairs to /dev/fd/62
[2016-06-07T15:28Z] samblaster: Output 109494 split reads to /dev/fd/63
[2016-06-07T15:28Z] samblaster: Marked 158903 of 10000000 (1.59%) read ids as duplicates using 193312k memory in 29.314S CPU seconds and 2H51M26S(10286S) wall time.
[2016-06-07T15:46Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/bwa mem  -c 250 -M -t 1  -R '@RG\tID:2936\tPL:illumina\tPU:2936\tSM:2936' -v 1 /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(grabix grab /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align_prep/2936_FGC0305_6_1_GTGAAA.fastq.gz 1 80000000) <(grabix grab /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align_prep/2936_FGC0305_6_2_GTGAAA.fastq.gz 1 80000000)  | /home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/samblaster --addMateTags -M --splitterFile >(/home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/samtools sort -@ 1 -m 682M -T /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpM6jIyt/2936-sort-1_80000000-sorttmp-spl -o /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpJlA2f_/2936-sort-1_80000000-sr.bam /dev/stdin) --discordantFile >(/home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/samtools sort -@ 1 -m 682M -T /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpM6jIyt/2936-sort-1_80000000-sorttmp-disc -o /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpNHnD0T/2936-sort-1_80000000-disc.bam /dev/stdin) | /home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/samtools view -b -S -u - | /home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/sambamba sort -N -t 1 -m 682M --tmpdir /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpM6jIyt/2936-sort-1_80000000-sorttmp-full -o /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpM6jIyt/2936-sort-1_80000000.bam /dev/stdin
[M::mem_pestat] low and high boundaries for proper pairs: (113, 295)
```

That is repeated later on, plus extra.

```
[mem_sam_pe] paired reads have different names: "HWI-ST965:305:C0MR9ACXX:6:1209:6490:3773", "HWI-ST965:305:C0MR9ACXX:6:1303:2738:37310"

samblaster: Output 380511 discordant read pairs to /dev/fd/62
samblaster: Output 109494 split reads to /dev/fd/63
samblaster: Marked 158903 of 10000000 (1.59%) read ids as duplicates using 193312k memory in 29.314S CPU seconds and 2H51M26S(10286S) wall time.
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bwubb/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 128, in variant2pipeline
    samples = run_parallel("process_alignment", samples)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 68, in process_alignment
    return sample.process_alignment(*args)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 112, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
    names, align_dir, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 117, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 147, in align_pipe
    names, rg_info, data)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 157, in _align_mem
    [do.file_nonempty(tx_out_file), do.file_reasonable_size(tx_out_file, fastq_file)])
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/bwa mem  -c 250 -M -t 1  -R '@RG\tID:2936\tPL:illumina\tPU:2936\tSM:2936' -v 1 /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(grabix grab /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align_prep/2936_FGC0305_6_1_GTGAAA.fastq.gz 1 80000000) <(grabix grab /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align_prep/2936_FGC0305_6_2_GTGAAA.fastq.gz 1 80000000)  | /home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/samblaster --addMateTags -M --splitterFile >(/home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/samtools sort -@ 1 -m 682M -T /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpM6jIyt/2936-sort-1_80000000-sorttmp-spl -o /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpJlA2f_/2936-sort-1_80000000-sr.bam /dev/stdin) --discordantFile >(/home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/samtools sort -@ 1 -m 682M -T /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpM6jIyt/2936-sort-1_80000000-sorttmp-disc -o /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpNHnD0T/2936-sort-1_80000000-disc.bam /dev/stdin) | /home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/samtools view -b -S -u - | /home/bwubb/bcbio-nextgen/galaxy/../anaconda/bin/sambamba sort -N -t 1 -m 682M --tmpdir /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpM6jIyt/2936-sort-1_80000000-sorttmp-full -o /home/bwubb/NGS/BRCATargeted/bcbio/data/2936/work/align/2936/split/tx/tmpM6jIyt/2936-sort-1_80000000.bam /dev/stdin
[M::mem_pestat] low and high boundaries for proper pairs: (113, 295)
```

Finally.
```
[mem_sam_pe] paired reads have different names: "HWI-ST965:305:C0MR9ACXX:6:1209:6490:3773", "HWI-ST965:305:C0MR9ACXX:6:1303:2738:37310"

samblaster: Output 380511 discordant read pairs to /dev/fd/62
samblaster: Output 109494 split reads to /dev/fd/63
samblaster: Marked 158903 of 10000000 (1.59%) read ids as duplicates using 193312k memory in 29.314S CPU seconds and 2H51M26S(10286S) wall time.
' returned non-zero exit status 1
```

Any suggestions? Apologies for the Error text dump.

-bwubb

**Comment by chapmanb** [comment]
Brad;
Sorry about the problems. Is this error reproducible on re-runs? If you're sure the input fastq files are okay, errors like this are typically indicative of filesystem problems where is has problems pulling from one file and then things get out of sync. I wish I knew of a buffering or other mechanism to work around it, but if I've ever seen it on flaky shared filesystems restarting fixed it. Hope this helps some.

**Comment by bwubb** [comment]
I tried to run it twice. I will try a third time, but first Ill double check the fastq files. Would it help to try and just run a simple bwa mem on the pairs?

**Comment by chapmanb** [comment]
Brad -- thanks for the help debugging. On the replicated failures, is it failing at the same point (same set of mismatched pairs) or do you get different messages? That could help determine if there is something wrong with the input file versus intermittent filesystem issues.

You could definitely try debugging with bwa only to determine if it's something with piping/memory/filesystems versus a problem input fastq. Hope this helps.

**Comment by bwubb** [comment]
Apologies for the issue report. This appears to be a fastq issue. It is failing on the same set of mismatched pairs
```
[mem_sam_pe] [mem_sam_pe] paired reads have different names: "HWI-ST965:305:C0MR9ACXX:6:1209:6387:3795", "HWI-ST965:305:C0MR9ACXX:6:1303:2654:37326"
paired reads have different names: "HWI-ST965:305:C0MR9ACXX:6:1209:6312:3791", "HWI-ST965:305:C0MR9ACXX:6:1303:2722:37325"


[mem_sam_pe] paired reads have different names: "HWI-ST965:305:C0MR9ACXX:6:1209:6490:3773", "HWI-ST965:305:C0MR9ACXX:6:1303:2738:37310"

[mem_sam_pe] paired reads have different names: "HWI-ST965:305:C0MR9ACXX:6:1209:6460:3796", "HWI-ST965:305:C0MR9ACXX:6:1303:2509:37338"
```

Although Im surprised it exits code 1, well maybe not that surprised. I am not sure how the mates are out of order. Im pulling the archived files from tape to recheck. Any recommendation for fastq sorting tools? Surprisingly, I have never had to resort fastqs before. Otherwise Im sure I can script something up.

Thanks.

**Comment by chapmanb** [comment]
Thanks for following up. I haven't had to directly sort fastqs like this before (normally only when extracting from BAM files) but it looks like some tools exist:

http://homes.cs.washington.edu/~dcjones/fastq-tools/

Hope this helps.
