### ISSUE TITLE
IPClusterStop fails

### ISSUE THREAD

**Issue by gberriz** [chapmanb/bcbio-nextgen#1427]
The error reported here occurs only sporadically, and is independent of the inputs to the pipeline.  (IOW, given two runs with identical inputs, the error may occur in one, and not in the other.)

At the end of this message I copy the relevant section of the diagnostic output.

Please let me know what other information would be useful to you.

    [2016-06-09T00:32Z] node2071: Combining count files into /path-to-basedir/work/sailfish/co\
    mbined.sf.
    2016-06-08 20:37:13.339 [IPClusterStop] Using existing profile dir: u'/path-to-basedir/wor\
    k/log/ipython'
    2016-06-08 20:37:13.356 [IPClusterStop] Stopping cluster [pid=13555] with [signal=2]
    2016-06-08 20:37:16.601 [IPClusterStop] Using existing profile dir: u'/path-to-basedir/wor\
    k/log/ipython'
    2016-06-08 20:37:16.613 [IPClusterStop] CRITICAL | Could not read pid file, cluster is pro\
    bably not running.
    [2016-06-09T00:37Z] node2071: Did not stop IPython cluster correctly
    Traceback (most recent call last):
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py",\
     line 91, in stop
        ipython_cluster.stop_from_view(view)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", li\
    ne 849, in stop_from_view
        _stop(view.clusterhelper["profile"], view.clusterhelper["cluster_id"])
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", li\
    ne 855, in _stop
        subprocess.check_call(args)
      File "/path-to-bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command '['/path-to-bcbio/anaconda/bin/python', '-E', '-c', 'import re\
    source; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(\
    max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (ma\
    x(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimit(resource.RLI\
    MIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resource.setrl\
    imit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from ipyparallel.app\
    s.ipclusterapp import launch_new_instance; launch_new_instance()', 'stop', '--cluster-id=c\
    93d0aeb-1705-4518-ab68-70da05ad235d', '--profile-dir=/path-to-basedir/work/log/ipython']' \
    returned non-zero exit status 11

    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    2 Engines running
    Sending a shutdown signal to the controller and engines.

    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    18 Engines running
    Sending a shutdown signal to the controller and engines.

    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    3 Engines running
    Sending a shutdown signal to the controller and engines.

    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    0 Engines running
    10 Engines running
    Sending a shutdown signal to the controller and engines.
    Traceback (most recent call last):
      File "/opt/bcbio/centos/bin/bcbio_nextgen.py", line 226, in <module>
        main(**kwargs)
      File "/opt/bcbio/centos/bin/bcbio_nextgen.py", line 43, in main
        run_main(**kwargs)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line \
    51, in run_main
        fc_dir, run_info_yaml)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line \
    87, in _run_toplevel
        for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line \
    250, in rnaseqpipeline
        samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", lin\
    e 76, in quantitate_expression_parallel
        samples = sailfish.combine_sailfish(samples)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", lin\
    e 192, in combine_sailfish
        df.pivot("id", "sample", "tpm").to_csv(tx_out_file, sep="\t")
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 13\
    43, in to_csv
        formatter.save()
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/format.py", line 1\
    550, in save
        self._save()
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/format.py", line 1\
    651, in _save
        self._save_chunk(start_i, end_i)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/format.py", line 1\
    665, in _save_chunk
        quoting=self.quoting)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", lin\
    e 1403, in to_native_types
        return formatter.get_result_as_array()
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/format.py", line 2\
    170, in get_result_as_array
        formatted_values = format_values_with(float_format)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/format.py", line 2\
    156, in format_values_with
        for val in values.ravel()[imask]])
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/format.py", line 2\
    107, in base_formatter
        return str(v) if notnull(v) else self.na_rep
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/common.py", line 3\
    35, in notnull
        res = isnull(obj)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/common.py", line 1\
    76, in isnull
        return _isnull(obj)
      File "/path-to-bcbio/anaconda/lib/python2.7/site-packages/pandas/core/common.py", line 1\
    81, in _isnull_new
        return lib.checknull(obj)
    KeyboardInterrupt

**Comment by roryk** [comment]
Hi Gabriel,

The last error looks like the job was manually interrupted via the keyboard. For the first error, it looks like sometimes the job is getting killed before we manually try to shut it down. We could definitely fix that to emit a warning by catching the CalledProcessError exception there.

**Comment by roryk** [comment]
I pushed a fix to catch the exception and emit a message rather than fail when we try to stop an already-stopped cluster. Thanks!

**Comment by gberriz** [comment]
This job was running in the background as part of a bsub (LSF) submission, so I think it is unlikely that it was killed manually via the keyboard.  (I was the user who submitted the job, and I certainly did not kill it.)  Such jobs are usually killed through the bkill utility, but, again, I did not issue that command.  It is possible that a sysadmin issued a bkill for this job, but, again I find this possibility unlikely, because: 1) whenever such a job gets killed by a sysadmin (as opposed to being killed automatically, e.g. by LSF), I receive an email written by the sysadmin responsible for killing the job explaining his/her rationale; and 2) as I said in my original email, the error occurs sporadically, therefore it would be odd that a sysadmin would decide to kill only some of these jobs and not others, and offer no explanation for doing so.

Therefore, the `KeyboardInterrupt` message notwithstanding, I very much doubt that the job was killed manually.  That said, I will submit a ticket to the sysadmins inquiring whether this job was indeed killed manually.  I will report the answer I get either way.

My suggestion would be to instrument the code around the place responsible for the diagnostic

    CRITICAL | Could not read pid file, cluster is probably not running

as follows:

1. Put the attempt to read the pid file in a loop for multiple attempts (say 5), with a 1-second sleep between attempts; fail only after all attempts have been exhausted;
2. Include more information about why it was not possible to read the pid file; in particular, is the file missing altogether, or does it exist but is unreadable?
3. If possible, confirm that the cluster is not running by some other means.

Also it would be very helpful if the process that is supposed to be killed by IPClusterStop caught the signal that killed it, and logged it before exiting.

Lastly, I would suggest using a special-purpose signal (SIGUSR1 or SIGUSR2) rather than SIGINT to kill the cluster.  The code for the target process would probably need to be instrumented to respond appropriately to such a signal.  If, before exiting, the target process logs the signal (as suggested above), then it becomes straightforward to distinguish between internally- and externally-initiated kills.

**Comment by roryk** [comment]
Hi Gabriel,

Thanks for the nice suggestions. We're not actually generating the signal to kill the cluster, just calling out to `ipython cluster stop` which does everything else. The error messages and what not are generated there too-- the IPython folks might have some reasoning about why they chose the signal they sent to kill the cluster, we're just wrapping what they did so your good ideas might be better shifted there. Thanks!
