### ISSUE TITLE
Java memory

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1428]
Hi Brad,

When I ran bcbio tumor-normal somatic variant calling pipeline, I found the following error even after I upgrade the bcbio version from 0.9.7 development to 0.9.8. Could you help me to debug it?
Thanks!

INFO  13:13:19,205 ProgressMeter -     1:121485435   4300077.0    87.8 m      20.4 m        4.4%    33.1 h      31.7 h 
INFO  13:13:57,509 GATKRunReport - Uploaded run statistics report to AWS S3 
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
[2016-06-10T18:13Z] ica1: Unexpected error
Traceback (most recent call last):
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 187, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 197, in postprocess_alignment
    data = _recal_no_markduplicates(data)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 203, in _recal_no_markduplicates
    data = recalibrate.prep_recal(data)[0][0]
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 44, in prep_recal
    platform, dbsnp_file, intervals, data)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 89, in _gatk_base_recalibrator
    broad_runner.run_gatk(params, tmp_dir)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 285, in run_gatk
    log_error=log_error)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'java -Xms681m -Xmx1g -XX:+UseSerialGC -Djava.io.tmpdir=/user/project/work/tx/tmpQJnSAR -jar /user/parallel/bcbio/toolplus/gatk/3.5-0-g36282e4/GenomeAnalysisTK.jar -T BaseRecalibrator -o /user/project/work/align/11349FFPE/tx/tmpps4Xug/11349FFPE-sort.grp -I /user/project/work/align/11349FFPE/11349FFPE-sort.bam -R /user/parallel/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --downsample_to_fraction 0.617578154176 --downsampling_type ALL_READS --knownSites /user/parallel/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp_138.vcf.gz -L /user/project/work/bedprep/11349FFPE-sort-callable-callableblocks.bed --interval_set_rule INTERSECTION -nct 16 -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment

**Comment by chapmanb** [comment]
Sorry about the issue, it looks like you're not providing enough memory to GATK to make BaseRecalibrator happy. You can adjust this by increasing the memory per core specified in the `gatk` section of your `bcbio_system.yaml` file. More details are here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html?highlight=Xmx#tuning-core-and-memory-usage

Hope this helps, feel free to reopen if you aren't able to get things working and happy to help more.

**Comment by deber1980** [comment]
Hello Brad,

Thanks for the answer. As far as I saw, BaseRecalibrator is not parallelizing the work to cores while other parts which are using GATK do. So, what I wanted to ask is if there is an option to control specifically the memory used for BaseRecalibrator.

Many thanks

**Comment by chapmanb** [comment]
Thanks for following up. I dug a little deeper and realized that the latest code was not correctly scaling up cores along with memory. BaseRecalibrator cannot be scaled by machines, but does use multiple cores -- you can see this with the `--nct 16` option in the commandline above, where it uses GATK multithreading to get 16 cores. It should also scale up the memory but there was a bug preventing that, which is now fixed in the latest development version (`bcbio_nextgen.py upgrade -u development`).

There isn't a specific memory option for BaseRecalibrator, but setting `gatk` to something higher than 1g/core will probably also help with this. Apologies again about the problem, hope that gets it working for you.

**Comment by deber1980** [comment]
Thanks Brad
