### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1436]
Hi,
I found the following error when I was running the germline variant calling pipeline. Could you help me to debug it?
Thanks!

[2016-06-16T14:32Z] ica3: Germline extraction for info-100bp-HumanGenomic1, freebayes
[2016-06-16T14:32Z] ica1: ipython: split_variants_by_sample
[2016-06-16T14:32Z] ica1: Timing: prepped BAM merging
[2016-06-16T14:32Z] ica1: ipython: delayed_bam_merge
[2016-06-16T14:32Z] ica1: Timing: validation
[2016-06-16T14:32Z] ica1: ipython: compare_to_rm
[2016-06-16T14:32Z] ica1: Timing: ensemble calling
[2016-06-16T14:32Z] ica1: ipython: combine_calls
[2016-06-16T14:32Z] ica3: Ensemble consensus calls for None: freebayes,gatk-haplotype,samtools
[2016-06-16T14:32Z] ica3: Unexpected error
Traceback (most recent call last):
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 380, in combine_calls
    return ipython.zip_args(apply(ensemble.combine_calls, *args))
  File "/user/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/ensemble.py", line 30, in combine_calls
    base_dir = utils.safe_makedir(os.path.join(edata["dirs"]["work"], "ensemble", batch_id))
  File "/user/parallel/bcbio/anaconda/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by chapmanb** [comment]
Sorry about the issue. This is a problem with ensemble methods when a sample doesn't have a `metadata: batch`. There is a fix in the latest development version so if you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-start your analysis in place it should work cleanly. Thanks much for the report.
