### ISSUE TITLE
Zv9 reference genome

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1447]
```
Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O Danio_rerio.Zv9.dna.toplevel.fa.gz 'ftp://ftp.ensembl.org/pub/release-80/fasta/danio_rerio/dna/Danio_rerio.Zv9.dna.toplevel.fa.gz''

INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/BiO/BioTools/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/BiO/BioTools/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/BiO/BioTools/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/BiO/BioTools/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/BiO/BioTools/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/BiO/BioTools/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 486, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index seq for Zv9 by any method
```

I think this URL is changed.

ftp://ftp.ensembl.org//pub/release-80/fasta/danio_rerio/dna/Danio_rerio.GRCz10.dna.toplevel.fa.gz

so, GRCz10 is ok. but Zv9 genome in bcbio must be convert the correct address on ensembl.

**Comment by chapmanb** [comment]
Hyumin;
Sorry about the issue and thanks for the report. Do you need to specifically use the older zebrafish genome, or can you use the recent build? If the later, then you should be able to install with:
```
bcbio_nextgen.py upgrade --genomes GRCz10
```
We could remove/deprecate Zv9 if Ensembl downloads are no longer supporting this. Hope this helps.

**Comment by hmkim** [comment]
Yeah,  I tried older genome. it solved with GRCz10
Thanks.
