### ISSUE TITLE
reference build error

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1448]
```
Error: No unambiguous stretches of characters in the input.  Aborting...
  Time reading reference sizes: 00:00:00
Total time for call to driver() for forward index: 00:00:00
Command: bowtie-build --wrapper basic-0 -f /BiO/BioTools/bcbio/data/genomes/Ecoli/MG1655/seq/MG1655.fa /BiO/BioTools/bcbio/data/genomes/Ecoli/MG1655/seq/../bowtie/MG1655
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_setup_genome.py", line 270, in <module>
    indexed[index] = index_fn(fasta_file)
  File "/BiO/BioPeople/brandon/test_bcbio/make_genome/cloudbiolinux/cloudbio/biodata/genomes.py", line 633, in _index_bowtie
    return _index_w_command(dir_name, cmd, ref_file)
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_setup_genome.py", line 116, in _index_w_command
    index_name=index_path), shell=True)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bowtie-build -f /BiO/BioTools/bcbio/data/genomes/Ecoli/MG1655/seq/MG1655.fa /BiO/BioTools/bcbio/data/genomes/Ecoli/MG1655/seq/../bowtie/MG1655' returned non-zero exit status 1

```

```
grep ">" Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.31.dna.toplevel.fa
>Chromosome dna:chromosome chromosome:ASM584v2:Chromosome:1:4641652:1

```
I think this error from this file. (https://github.com/chapmanb/bcbio-nextgen/blob/882547b5db9f3678c5ecdcc997f3a0994b1fac9b/bcbio/pipeline/run_info.py)

> 29 ALLOWED_CONTIG_NAME_CHARS = set(list(string.digits) + list(string.ascii_letters) + ["-", "_", "*", ":", "."])

how can I handle this problem?

Thanks

**Comment by hmkim** [comment]
no issue. I remove the 0 byte fasta file and re run is ok
