### ISSUE TITLE
TypeError: Expected bytes, got unicode

### ISSUE THREAD

**Issue by tetron** [chapmanb/bcbio-nextgen#1449]
```
[2016-06-29T15:11Z] 9ed8b9305dd7: Finalizing variant calls: HG01977, freebayes
[2016-06-29T15:11Z] 9ed8b9305dd7: Calculating variation effects for HG01977, freebayes
[2016-06-29T15:11Z] 9ed8b9305dd7: Annotate VCF file: HG01977, freebayes
[2016-06-29T15:11Z] 9ed8b9305dd7: Filtering for HG01977, freebayes
[2016-06-29T15:11Z] 9ed8b9305dd7: Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 50, in process
    out = fn(fnargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 128, in postprocess_variants
    return variation.postprocess_variants(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 37, in postprocess_variants
    data, orig_items)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 27, in variant_filtration
    return vfilter.freebayes(call_file, ref_file, vrn_files, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vfilter.py", line 95, in freebayes
    out_file = _freebayes_hard(in_file, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vfilter.py", line 146, in _freebayes_hard
    stats = _calc_vcf_stats(in_file)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vfilter.py", line 173, in _calc_vcf_stats
    stats = {"avg_depth": _average_called_depth(in_file)}
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vfilter.py", line 187, in _average_called_depth
    for rec in cyvcf2.VCF(in_file):
  File "cyvcf2/cyvcf2.pyx", line 155, in cyvcf2.cyvcf2.VCF.__init__ (cyvcf2/cyvcf2.c:7106)
    self.fname = fname
TypeError: Expected bytes, got unicode
```

**Comment by chapmanb** [comment]
Peter -- thanks for the report and sorry about the problem. It looks like the most recent cyvcf2 release (0.4.0) complains if passed unicode file names. I worked around this by converting into a string which should avoid the issue. I'm rebuilding the bcbio Docker image now so that should be available in an hour or so with the fix. I'll update in the e-mail thread when that finished. Sorry about the issue and thanks again for letting me know.
