### ISSUE TITLE
'NoneType' object has no attribute 'group' in _merge_hla_fastq_input

### ISSUE THREAD

**Issue by tetron** [chapmanb/bcbio-nextgen#1450]
```
2016/06/29 20:29:14 Running [bcbio_nextgen.py runfn merge_split_alignments cwl sentinel-runtime={"cores": 8, "outdir": "/tmp/crunch-job-task-work/compute0.1/outdir", "outdirSize": 1024, "ram": 24192, "tmpdir": "/tmp/crunch-job-task-work/compute0.1/tmpdir", "tmpdirSize": 1024} sentinel-parallel=single-merge sentinel-outputs=["align_bam","work_bam-plus__disc","work_bam-plus__sr","hla__fastq"] work_bam=/keep/e4ff2d7a81aa3c78515746e963eef758+495/align/HG01977/split/HG01977-sort-1_1000000.bam align_bam=/keep/e4ff2d7a81aa3c78515746e963eef758+495/align/HG01977/split/HG01977-sort-1_1000000.bam work_bam-plus__disc=/keep/e4ff2d7a81aa3c78515746e963eef758+495/align/HG01977/split/HG01977-sort-1_1000000-disc.bam work_bam-plus__sr=/keep/e4ff2d7a81aa3c78515746e963eef758+495/align/HG01977/split/HG01977-sort-1_1000000-sr.bam hla__fastq=None genome_resources={"version":24} rgnames={"lane":"HG01977","lb":null,"pl":"illumina","pu":"HG01977","rg":"HG01977","sample":"HG01977"} config__algorithm={"align_split_size":10000000,"aligner":"bwa","archive":[],"effects":false,"nomap_split_targets":10,"realign":false,"recalibrate":false,"tools_off":["gemini"],"tools_on":[],"variantcaller":["freebayes"]} metadata={"phenotype":"normal","sex":"male"} description=HG01977 genome_resources__aliases={"ensembl":"homo_sapiens_vep_83_GRCh37","human":true,"snpeff":"GRCh37.75"} genome_build=GRCh37 genome_resources__rnaseq__transcriptome_index={"tophat":"../rnaseq/tophat/GRCh37_transcriptome.ver"} genome_resources__coverage={"coverage_problem_dir":"../coverage/problem_regions"} analysis=variant2]
[2016-06-29T20:29Z] 4a4bcf5b23b7: Merge bam files to HG01977-sort.bam
[2016-06-29T20:29Z] 4a4bcf5b23b7: WARNING: SAM header designates more than one PG tree root by PP tags.
[2016-06-29T20:29Z] 4a4bcf5b23b7: WARNING: SAM header designates more than one PG tree root by PP tags.
[2016-06-29T20:29Z] 4a4bcf5b23b7: [W] PG lines do not form a linear chain
crunchstat: keepcalls 0 put 312 get -- interval 10.0000 seconds 0 put 312 get
crunchstat: net:keep0 0 tx 55652687 rx -- interval 10.0000 seconds 0 tx 55652687 rx
crunchstat: keepcache 311 hit 1 miss -- interval 10.0000 seconds 311 hit 1 miss
crunchstat: fuseops 0 write 312 read -- interval 10.0000 seconds 0 write 312 read
crunchstat: blkio:0:0 0 write 40649315 read -- interval 10.0000 seconds 0 write 40649315 read
crunchstat: mem 49016832 cache 0 pgmajfault 247721984 rss
crunchstat: cpu 2.6700 user 0.6200 sys 8 cpus -- interval 10.0003 seconds 2.6300 user 0.6100 sys
crunchstat: net:eth0 6448 tx 181022 rx -- interval 10.0006 seconds 6358 tx 180932 rx
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] 500463
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] finished MemUsage(size=56.7891,rss=9.39062,peak=57.1055)
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] 500463\01101:73213099\011MemUsage(size=2766.66,rss=218.719,peak=2766.92)\011AutoArrayMemUsage(memusage=2129.98,peakmemusage=2129.98,maxmem=1.75922e+13)\011final
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] flushing read ends lists...done.
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] merging read ends lists/computing duplicates...done, time 01:10794499
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] num dups 546
[2016-06-29T20:29Z] 4a4bcf5b23b7: # bamsormadup
[2016-06-29T20:29Z] 4a4bcf5b23b7: 
[2016-06-29T20:29Z] 4a4bcf5b23b7: ##METRICS
[2016-06-29T20:29Z] 4a4bcf5b23b7: LIBRARY\011UNPAIRED_READS_EXAMINED\011READ_PAIRS_EXAMINED\011UNMAPPED_READS\011UNPAIRED_READ_DUPLICATES\011READ_PAIR_DUPLICATES\011READ_PAIR_OPTICAL_DUPLICATES\011PERCENT_DUPLICATION\011ESTIMATED_LIBRARY_SIZE
[2016-06-29T20:29Z] 4a4bcf5b23b7: Unknown Library\011652\011249269\011810\0118\011269\0110\0110.00109377\011115409524
[2016-06-29T20:29Z] 4a4bcf5b23b7: 
[2016-06-29T20:29Z] 4a4bcf5b23b7: ## HISTOGRAM
[2016-06-29T20:29Z] 4a4bcf5b23b7: BIN\011VALUE
[2016-06-29T20:29Z] 4a4bcf5b23b7: 1\0111
...
[2016-06-29T20:29Z] 4a4bcf5b23b7: 100\01190.0351
[2016-06-29T20:29Z] 4a4bcf5b23b7: WARNING: SAM header designates more than one PG tree root by PP tags.
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] blocks generated in time 06:23892700
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] number of blocks to be merged is 1 using 8 blocks per input with block size 1048576
[2016-06-29T20:29Z] 4a4bcf5b23b7: [W] PG lines do not form a linear chain
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] 500463
[2016-06-29T20:29Z] 4a4bcf5b23b7: [D]\011md5\0116ce2f6877a7b466e196276ebcdeaaab6
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] checksum ok
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] blocks merged in time 03:02822699
[2016-06-29T20:29Z] 4a4bcf5b23b7: [V] run time 09:26818800 (9.26819 s)\011MemUsage(size=1137.01,rss=44.7461,peak=3313.15)
[2016-06-29T20:29Z] 4a4bcf5b23b7: Index BAM file: HG01977-sort.bam
[2016-06-29T20:29Z] 4a4bcf5b23b7: Index BAM file: HG01977-sort-disc.bam
[2016-06-29T20:29Z] 4a4bcf5b23b7: Index BAM file: HG01977-sort-sr.bam
[2016-06-29T20:29Z] 4a4bcf5b23b7: Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 50, in process
    out = fn(fnargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 112, in merge_split_alignments
    return sample.merge_split_alignments(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 275, in merge_split_alignments
    data = _merge_hla_fastq_inputs(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 305, in _merge_hla_fastq_inputs
    hlatype = re.search(".hla.(?P<hlatype>[\w-]+).fq", hla_file).group("hlatype")
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by chapmanb** [comment]
Peter;
Is it possible you're using an older version of bcbio or the Docker container? This was was fixed a few weeks back:

https://github.com/chapmanb/bcbio-nextgen/commit/28064c5acfc881c932aaa2a2eb5fab144fd8044b#diff-0443ee0b10bd75b8a46979f9ce403500

Hopefully a fresh container will get things running smoothly.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
