### ISSUE TITLE
tophat fusion-mode fail with KeyError: 'rg'

### ISSUE THREAD

**Issue by csardas** [chapmanb/bcbio-nextgen#1451]
I enabled fusion-mode to find gene-fusion event by tophat
tophat try to use bowtie1 to align reads but ended up with a KeyError: 'rg'
the veriosn of bcbio-nextgen is 0.9.9a-877e448

[2016-06-30T07:20Z] Aligning lane 525N_tophat2_fusion with tophat aligner
Traceback (most recent call last):
  File "/opt/tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/opt/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 244, in rnaseqpipeline
    samples = run_parallel("process_alignment", samples)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 68, in process_alignment
    return sample.process_alignment(*args)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 112, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
    names, align_dir, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 117, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 244, in align
    align_dir, data, names)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 133, in tophat_align
    tx_out_dir, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 254, in _estimate_paired_innerdist
    out_base, out_dir, data, True)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 274, in _bowtie_for_innerdist
    work_dir, data, extra_args)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bowtie.py", line 68, in align
    fix_rg_cmd = r"samtools addreplacerg -r '%s' -" % novoalign.get_rg_info(names)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/novoalign.py", line 20, in get_rg_info
    out = r"@RG\tID:{rg}\tPL:{pl}\tPU:{pu}\tSM:{sample}".format(**names)
KeyError: 'rg'

**Comment by roryk** [comment]
Thanks @csardas,

We don't do much fusion calling and we don't run Tophat2 much, so we missed this one. I pushed a fix to the development version so this should be all set now.

**Comment by csardas** [comment]
hi Rory,
thks for fast response.
the process now stop at another unexpected crash


  File
"/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bowtie.py",
line 73, in align
    do.run(cmd, "Running Bowtie on %s and %s." % (fastq_file, pair_file),
data)
  File
"/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py",
line 21, in run
    _do_run(cmd, checks, log_stdout)
  File
"/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py",
line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail;
/opt/bcbio/galaxy/../anaconda/bin/bowtie -p 6 -M 1 -s 100000 -u 250000 -q
-v 2 -k 1 -X 2000 --best --strata --sam
/opt/bcbio/genomes/Hsapiens/GRCh37/bowtie/GRCh37 -1 <(gunzip -c
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/trimmed/525N_S99_L999_R1_001.clean_525N_tophat2_fusion.trimmed.fastq.gz)
-2 <(gunzip -c
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/trimmed/525N_S99_L999_R2_001.clean_525N_tophat2_fusion.trimmed.fastq.gz)
| samtools addreplacerg -r
'@RG\tID:525N_tophat2_fusion\tPL:illumina\tPU:525N_tophat2_fusion\tSM:525N_tophat2_fusion'
- | /opt/bcbio/galaxy/../anaconda/bin/samblaster --addMateTags -M
--splitterFile >(/opt/bcbio/galaxy/../anaconda/bin/samtools sort -@ 6 -m
682M -T
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/align/525N_tophat2_fusion/tx/tmpV0RFAn/525N_tophat2_fusion_tophat/innerdist_estimate/tx/tmp1SOVXY/525N_tophat2_fusion-sort-sorttmp-spl
-o
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/align/525N_tophat2_fusion/tx/tmpV0RFAn/525N_tophat2_fusion_tophat/innerdist_estimate/tx/tmpS5vmHG/525N_tophat2_fusion-sort-sr.bam
/dev/stdin) --discordantFile >(/opt/bcbio/galaxy/../anaconda/bin/samtools
sort -@ 6 -m 682M -T
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/align/525N_tophat2_fusion/tx/tmpV0RFAn/525N_tophat2_fusion_tophat/innerdist_estimate/tx/tmp1SOVXY/525N_tophat2_fusion-sort-sorttmp-disc
-o
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/align/525N_tophat2_fusion/tx/tmpV0RFAn/525N_tophat2_fusion_tophat/innerdist_estimate/tx/tmpYzu7UC/525N_tophat2_fusion-sort-disc.bam
/dev/stdin) | /opt/bcbio/galaxy/../anaconda/bin/samtools view -b -S -u - |
/opt/bcbio/galaxy/../anaconda/bin/sambamba sort  -t 6 -m 682M --tmpdir
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/align/525N_tophat2_fusion/tx/tmpV0RFAn/525N_tophat2_fusion_tophat/innerdist_estimate/tx/tmp1SOVXY/525N_tophat2_fusion-sort-sorttmp-full
-o
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/align/525N_tophat2_fusion/tx/tmpV0RFAn/525N_tophat2_fusion_tophat/innerdist_estimate/tx/tmp1SOVXY/525N_tophat2_fusion-sort.bam
/dev/stdin
samblaster: Version 0.1.22
samblaster: Inputting from stdin
samblaster: Outputting to stdout
samblaster: Opening /dev/fd/62 for write.
samblaster: Opening /dev/fd/63 for write.
samblaster: Loaded 84 header sequence entries.
samblaster: Can't find first and/or second of pair in sam block of length 1
for id: NS500238:65:HCHC2BGXX:1:11106:11696:7911
samblaster: Are you sure the input is sorted by read ids?

samtools addreplacerg: [readgroupise] Could not write read to output file:
Broken pipe
Error while flushing and closing output
terminate called after throwing an instance of 'int'

**Comment by roryk** [comment]
If you run the alignment from the command line like this:

```
/opt/bcbio/galaxy/../anaconda/bin/bowtie -p 6 -M 1 -s 100000 -u 250000 -q
-v 2 -k 1 -X 2000 --best --strata --sam
/opt/bcbio/genomes/Hsapiens/GRCh37/bowtie/GRCh37 -1 <(gunzip -c
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/trimmed/525N_S99_L999_R1_001.clean_525N_tophat2_fusion.trimmed.fastq.gz)
-2 <(gunzip -c
/home/csardas/RNAseq_test/test_bcbio_run9_berlin_tophat-fusion/trimmed/525N_S99_L999_R2_001.clean_525N_tophat2_fusion.trimmed.fastq.gz)
```

Does it work properly?

**Comment by csardas** [comment]
​
 debug.sam
<https://drive.google.com/file/d/0B24b7lXrBu-1MmhCTm5lNU0yYWs/view?usp=drive_web>
​
the command worked and output a sam format to stdout

stderr output

  # reads processed: 254257
  # reads with at least one reported alignment: 46827 (18.42%)
  # reads that failed to align: 203173 (79.91%)
  # reads with alignments sampled due to -M: 4257 (1.67%)
  Reported 46827 paired-end alignments to 1 output stream(s)
