### ISSUE TITLE
BCBIO updgrade issue

### ISSUE THREAD

**Issue by rohandavidg** [chapmanb/bcbio-nextgen#1454]
Hi,

i was trying to upgrade BCBIO using the command
bcbio_nextgen.py upgrade -u stable --tools --data
but i seem to have run into an error. 

Running GGD recipe: giab-NA12878
--2016-07-01 10:42:09--  ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/NISTv3.2.2/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.vcf.gz
           => “validation/giab-NA12878/truth_small_variants.vcf.gz”
Resolving ftp-trace.ncbi.nlm.nih.gov... 130.14.250.11, 2607:f220:41e:250::13
Connecting to ftp-trace.ncbi.nlm.nih.gov|130.14.250.11|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /giab/ftp/release/NA12878_HG001/NISTv3.2.2 ...
No such directory “giab/ftp/release/NA12878_HG001/NISTv3.2.2”.

Traceback (most recent call last):
  File "/data5/bsi/epibreast/m087494.couch/Scripts/Progams/bin/bcbio_nextgen.py", line 207, in <module>

  File "/data5/bsi/epibreast/m087494.couch/Scripts/Progams/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/data5/bsi/epibreast/m087494.couch/Scripts/Progams/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 474, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 809, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/data5/bsi/epibreast/m087494.couch/Couch/Huge_Breast_VCF/CARRIERS/SubProjects/BCBIO/working/BCBIO/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/data5/bsi/epibreast/m087494.couch/Scripts/Progams/bcbio/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    cmd = popenargs[0]
subprocess.CalledProcessError: Command '['bash', '/data5/bsi/epibreast/m087494.couch/Scripts/Progams/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 8

it seems like it's failing to download something.

**Comment by chapmanb** [comment]
Rohan;
Sorry about the issue, this was a temporary problem with file availability on the Genome in a Bottle website:

https://groups.google.com/forum/#!msg/giab-analysis-team/mkEpJEgihK0/XMBiGxFpCAAJ

It should hopefully be working now if you re-try your upgrade. Feel free to reopen this issue if you run into any other problems.

**Comment by rohandavidg** [comment]
thank you.. it worked now
