### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1458]
There was an initial problem with numpy/pandas requiring a reinstall. Not sure about this one.

```
$ bcbio_nextgen.py upgrade -u development 
Upgrading bcbio
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /share/PI/euan/apps/bcbio/anaconda:
#
bcbio-nextgen             0.9.9a0                  py27_4    bioconda
Upgrading bcbio-nextgen to latest development version
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9a0', 'bcbio_nextgen.py')
  File "/home/dwaggott/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9a0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 60, in upgrade_bcbio
    "git+%s#egg=bcbio-nextgen" % REMOTES["gitrepo"]]], anaconda_dir)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 109, in _pip_safe_ssl
    subprocess.check_call(cmd)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the problems. It looks like your install is missing pip for some
reason. I'm not sure how that would happen but you could do:
```
/share/PI/euan/apps/bcbio/anaconda/bin/conda install pip
```
and then re-try and hopefully that'll fix your install and get the upgrade complete.

**Comment by dwaggott** [comment]
Yup pip disappeared. Fixed. Thanks!
