### ISSUE TITLE
Zv9 reference genome issue

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1461]
```
INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome Zv9 with index seq
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: wget --continue --no-check-certificate -O Danio_rerio.Zv9.dna.toplevel.fa.gz 'ftp://ftp.ensembl.org/pub/release-80/fasta/danio_rerio/dna/Danio_rerio.Zv9.dna.toplevel.fa.gz'
--2016-07-07 16:48:55--  ftp://ftp.ensembl.org/pub/release-80/fasta/danio_rerio/dna/Danio_rerio.Zv9.dna.toplevel.fa.gz
           => `Danio_rerio.Zv9.dna.toplevel.fa.gz'
Resolving ftp.ensembl.org (ftp.ensembl.org)... 193.62.203.85
Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.203.85|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/release-80/fasta/danio_rerio/dna ... done.
==> SIZE Danio_rerio.Zv9.dna.toplevel.fa.gz ... done.
==> PASV ... done.    ==> RETR Danio_rerio.Zv9.dna.toplevel.fa.gz ...
No such file `Danio_rerio.Zv9.dna.toplevel.fa.gz'.


Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O Danio_rerio.Zv9.dna.toplevel.fa.gz 'ftp://ftp.ensembl.org/pub/release-80/fasta/danio_rerio/dna/Danio_rerio.Zv9.dna.toplevel.fa.gz''

INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/BiO/BioTools/bcbio/data/genomes/Scerevisiae/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/BiO/BioTools/bcbio/data/genomes/Scerevisiae/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/BiO/BioTools/bcbio/data/genomes/Scerevisiae/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/BiO/BioTools/bcbio/data/genomes/Scerevisiae/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/BiO/BioTools/bcbio/data/genomes/Scerevisiae/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/BiO/BioTools/bcbio/data/genomes/Scerevisiae/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 486, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index seq for Zv9 by any method
```

ensembl reference genome address is changed.
ftp://ftp.ensembl.org//pub/release-80/fasta/danio_rerio/dna/Danio_rerio.GRCz10.dna_rm.toplevel.fa.gz

Please check this. 

Thanks!

**Comment by chapmanb** [comment]
Hyunmin;
Thanks for the report. I believe this is a duplicate of #1447 where we discussed this last week. Zv9 is outdated and GRCz10 is the right version to use for Zebrafish. I've removed the old version to avoid any confusion going forward. Thanks again.
