### ISSUE TITLE
GTF file (ValueError: Duplicate ID YDL248W)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1462]
Error

```
    ebwtTotLen: 4052416
    ebwtTotSz: 4052416
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:00:14
Creating gffutils database for /BiO/BioTools/bcbio/data/genomes/Scerevisiae/R64-1-1/tmpcbl/ref-transcripts.gtf.
Traceback (most recent call last):
  File "/BiO/BioPeople/brandon/cloudbiolinux/utils/prepare_tx_gff.py", line 821, in <module>
    main(args.org_build, args.gtf, args.fasta, genome_dir, args.cores)
  File "/BiO/BioPeople/brandon/cloudbiolinux/utils/prepare_tx_gff.py", line 286, in main
    db = _get_gtf_db(gtf_file)
  File "/BiO/BioPeople/brandon/cloudbiolinux/utils/prepare_tx_gff.py", line 757, in _get_gtf_db
    disable_infer_transcripts, disable_infer_genes = guess_disable_infer_extent(gtf)
  File "/BiO/BioPeople/brandon/cloudbiolinux/utils/prepare_tx_gff.py", line 729, in guess_disable_infer_extent
    db = _create_tiny_gffutils_db(gtf_file)
  File "/BiO/BioPeople/brandon/cloudbiolinux/utils/prepare_tx_gff.py", line 700, in _create_tiny_gffutils_db
    disable_infer_transcripts=True)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 734, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 218, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID YDL248W
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_setup_genome.py", line 277, in <module>
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/BiO/BioTools/bcbio/data/anaconda/bin/python /BiO/BioPeople/brandon/cloudbiolinux/utils/prepare_tx_gff.py --cores 1 --genome-dir /BiO/BioTools/bcbio/data/genomes --gtf /BiO/BioTools/bcbio/data/genomes/Scerevisiae/R64-1-1/rnaseq/ref-transcripts.gtf Scerevisiae R64-1-1' returned non-zero exit status 1
```

GTF file contents (YDL248W)

```
IV      ensembl gene    1802    2953    .       +       .       gene_id "YDL248W"; gene_name "COS7"; gene_source "ensembl"; gene_biotype "protein_coding";
IV      ensembl transcript      1802    2953    .       +       .       gene_id "YDL248W"; transcript_id "YDL248W"; gene_name "COS7"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "COS7"; transcript_source "ensembl"; transcript_biotype "protein_cod
IV      ensembl exon    1802    2953    .       +       .       gene_id "YDL248W"; transcript_id "YDL248W"; exon_number "1"; gene_name "COS7"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "COS7"; transcript_source "ensembl"; transcript_biotype "pr
IV      ensembl CDS     1802    2950    .       +       0       gene_id "YDL248W"; transcript_id "YDL248W"; exon_number "1"; gene_name "COS7"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "COS7"; transcript_source "ensembl"; transcript_biotype "pr
IV      ensembl start_codon     1802    1804    .       +       0       gene_id "YDL248W"; transcript_id "YDL248W"; exon_number "1"; gene_name "COS7"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "COS7"; transcript_source "ensembl"; transcript_bio
IV      ensembl stop_codon      2951    2953    .       +       0       gene_id "YDL248W"; transcript_id "YDL248W"; exon_number "1"; gene_name "COS7"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "COS7"; transcript_source "ensembl"; transcript_bio
```

Do I need an modifing the GTF file for bcbio? (raw GTF from Ensembl)

**Comment by lpantano** [comment]
Hi,

sometimes I see this error for certain organisms. What species is? If there is a genebank format, you can use this script (https://github.com/chapmanb/bcbio-nextgen/blob/master/scripts/utils/gb2genome.py) to get FASTA  and GTF that will be compatible with prepare_genome script.

Normally his is for small genomes, so if it is big, then maybe you will need to fix this as a quick solution. Maybe @roryk  has some idea how to fix this on the fly.

sorry about the problem.

**Comment by hmkim** [comment]
HI, @lpantano 

I download the GTF file from Ensembl. (http://www.ensembl.org/Saccharomyces_cerevisiae/Info/Index)

For use the 'gb2genomes.py', do I need a downloading the GenBank format from Ensembl (not NCBI)?
(http://asia.ensembl.org/info/data/ftp/index.html)

**Comment by lpantano** [comment]
yes, you need to download and then give the parameters the script asks for. Just the prefix and the gene bank file, I think. you can get help if use `-h`.

hope this fixes the problem, let us know.

**Comment by hmkim** [comment]
I got the same error in below.

```
Creating gffutils database for /BiO/BioTools/bcbio/data/genomes/Scerevisiae/R64-1-1/tmpcbl/ref-transcripts.gtf.
Traceback (most recent call last):
  File "/BiO/BioPeople/brandon/Saccharomyces_cerevisiae.R64-1-1/ftp.ensembl.org/pub/release-84/genbank/saccharomyces_cerevisiae/cloudbiolinux/utils/prepare_tx_gff.py", line 821, in <module>
    main(args.org_build, args.gtf, args.fasta, genome_dir, args.cores)
  File "/BiO/BioPeople/brandon/Saccharomyces_cerevisiae.R64-1-1/ftp.ensembl.org/pub/release-84/genbank/saccharomyces_cerevisiae/cloudbiolinux/utils/prepare_tx_gff.py", line 286, in main
    db = _get_gtf_db(gtf_file)
  File "/BiO/BioPeople/brandon/Saccharomyces_cerevisiae.R64-1-1/ftp.ensembl.org/pub/release-84/genbank/saccharomyces_cerevisiae/cloudbiolinux/utils/prepare_tx_gff.py", line 757, in _get_gtf_db
    disable_infer_transcripts, disable_infer_genes = guess_disable_infer_extent(gtf)
  File "/BiO/BioPeople/brandon/Saccharomyces_cerevisiae.R64-1-1/ftp.ensembl.org/pub/release-84/genbank/saccharomyces_cerevisiae/cloudbiolinux/utils/prepare_tx_gff.py", line 729, in guess_disable_infer_extent
    db = _create_tiny_gffutils_db(gtf_file)
  File "/BiO/BioPeople/brandon/Saccharomyces_cerevisiae.R64-1-1/ftp.ensembl.org/pub/release-84/genbank/saccharomyces_cerevisiae/cloudbiolinux/utils/prepare_tx_gff.py", line 700, in _create_tiny_gffutils_db
    disable_infer_transcripts=True)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 734, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 218, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID YDL248W
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/tools/bin/bcbio_setup_genome.py", line 277, in <module>
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/BiO/BioTools/bcbio/data/anaconda/bin/python /BiO/BioPeople/brandon/Saccharomyces_cerevisiae.R64-1-1/ftp.ensembl.org/pub/release-84/genbank/saccharomyces_cerevisiae/cloudbiolinux/utils/prepare_tx_gff.py --cores 1 --genome-dir /BiO/BioTools/bcbio/data/genomes --gtf /BiO/BioTools/bcbio/data/genomes/Scerevisiae/R64-1-1/rnaseq/ref-transcripts.gtf Scerevisiae R64-1-1' returned non-zero exit status 1
```

$ wget -r ftp://ftp.ensembl.org//pub/release-84/genbank/saccharomyces_cerevisiae
$ cd ftp.ensembl.org/pub/release-84/genbank/saccharomyces_cerevisiae/
$ cat *.dat  > merged.dat
$ python gb2genome.py --gbk merged.dat --prefix Saccharomyces_cerevisiae.R64-1-1.84.chromosome
$ bcbio_setup_genome.py -f Saccharomyces_cerevisiae.R64-1-1.84.chromosome.fa -g Saccharomyces_cerevisiae.R64-1-1.84.chromosome.gtf -n S
cerevisiae -b R64-1-1 -i bowtie

Can you check this ?

**Comment by lpantano** [comment]
Hi @hmkim 

sorry about this. I missed this error. Did you work around this?

**Comment by lpantano** [comment]
Hi @hmkim 

I guess that you could go forward with that. Please let us know if you have other issues.

cheers
