### ISSUE TITLE
installation aborted 

### ISSUE THREAD

**Issue by KanduriC** [chapmanb/bcbio-nextgen#1465]
Hello!

I am new to bcbio, trying to install it on a linux cluster. The installation gets aborted (in several attempts) here:

[localhost] local: /cluster/home/skanduri/bcbio/anaconda/bin/conda update -y -c r ncurses
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /cluster/home/skanduri/bcbio/anaconda:

The following packages will be UPDATED:

    ncurses: 5.9-0 --> 5.9-4 r (soft-link)

Extracting packages ...
An unexpected error has occurred, please consider sending the             |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/cluster/home/skanduri/bcbio/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/conda/install.py", line 852, in extract
    t.extractall(path=temp_path)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/tarfile.py", line 2200, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/tarfile.py", line 2284, in makelink
    os.link(tarinfo._link_target, targetpath)
OSError: [Errno 1] Operation not permitted

Fatal error: local() encountered an error (return code 1) while executing '/cluster/home/skanduri/bcbio/anaconda/bin/conda update -y -c r ncurses'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/cluster/home/skanduri/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=./bcbio_tools/', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

Could you please suggest a turnaround? Thanks.

**Comment by chapmanb** [comment]
Chakravarthi;
Sorry about the issues. What type of filesystem is `/cluster/home/`? It looks like it doesn't allow creation of hard links, which the anaconda installer tries to do when installing this package. Your thread on the conda repo here:

https://github.com/conda/conda/issues/3030

looks like it's in the right direction. Hopefully you can either try an alternative install location where the filesystem accepts hard links, or they can rebuild the ncurses package with softlinks. Sorry to not have better ideas immediately but hopefully the alternative filesystem location works in the short term.

**Comment by KanduriC** [comment]
Thanks a lot for the quick response;

Installing 'ncurses' from conda-forge as suggested here at [conda/issues/3030](https://github.com/conda/conda/issues/3030) helped. The installation crossed that phase but stuck again with IOError. Could you please pointout a fix? Thanks.

stdout:

INFO: Genome preparation method s3 failed, trying next
INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome GRCh37 with index rtg
INFO: Preparing genome GRCh37 with index rtg
[localhost] local: export PATH=/cluster/home/skanduri/bcbio_tools/bin:$PATH && export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=2g && rtg format -o rtg/GRCh37.sdf /cluster/home/skanduri/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
Unable to read /opt/anaconda1anaconda2anaconda3/share/rtg-tools-3.6-0/RTG.jar

Fatal error: local() encountered an error (return code 1) while executing 'export PATH=/cluster/home/skanduri/bcbio_tools/bin:$PATH && export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=2g && rtg format -o rtg/GRCh37.sdf /cluster/home/skanduri/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa'

Aborting.
INFO: Genome preparation method raw failed, trying next
INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "/cluster/home/skanduri/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.8', 'bcbio_nextgen.py')
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.8-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 486, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index rtg for GRCh37 by any method
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/cluster/home/skanduri/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=./bcbio_tools/', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Glad you were able to work around the ncurses hardlink issue. For the current problem, I'm not sure what happened as the internal path conda uses (`/opt/anaconda1anaconda2anaconda3/`) should be converted into the correct path to the conda install during installation. Could we try re-installing to see if that fixes whatever happened:
```
bcbio_conda install conda
bcbio_conda uninstall rtg-tools
bcbio_conda install rtg-tools
```
and then re-run the `upgrade`. Fingers crossed that will fix the problems and get bcbio installed cleanly.

**Comment by KanduriC** [comment]
Thanks once again. I uninstalled rtg-tools and tried to install it again. It says that rtg-tools is not currently available for linux-64 channels. To test an alternative, I installed rtg-tools directly from bioconda as shown below. But the installation aborts at the same step as described in my previous message with identical error messages.  

stdout:

-bash-4.1$ ~/bcbio_tools/bin/bcbio_conda install rtg-tools
Fetching package metadata .......
Solving package specifications: .
Error: Package missing in current linux-64 channels: 
  - rtg-tools

Close matches found; did you mean one of these?

    rtg-tools: r-gtools, r-catools, r-devtools

You can search for packages on anaconda.org with

    anaconda search -t conda rtg-tools

You may need to install the anaconda-client command line client with

    conda install anaconda-client

-bash-4.1$ ~/bcbio/anaconda/bin/conda install -c bioconda rtg-tools=3.6
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /cluster/home/skanduri/bcbio/anaconda:

The following NEW packages will be INSTALLED:

    rtg-tools: 3.6-0 bioconda (soft-link)

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%

**Comment by chapmanb** [comment]
Thanks for trying this out and for the followup. Apologies about overlooking the need to specify `-c bioconda`, that's exactly right.

I'm confused as to why your conda is not resolving the internal links to the path. I can't replicate this myself with conda 4.1.8 and am unsure why you're seeing it. Can you try being a bit more aggressive with the removal:
```
bcbio_conda install conda
bcbio_conda uninstall -y rtg-tools
rm -rf  /cluster/home/skanduri/bcbio/anaconda/pkgs/rtg-tools*
bcbio_conda install -c bioconda rtg-tools
```
Fingers crossed that will fix it. If not, I might need more information about your conda version and filesystem in case there is some weird code path going on different than what I see locally.

**Comment by KanduriC** [comment]
Thanks for your patient support. I tried your suggestions, but the same error recurred. I checked the conda version, it is 4.1.8. I do not know if this was what you were referring to; but I used `stat -f -c %T .` to check the filesystem and it says `fhgfs`, the paraller cluster file system.

**Comment by chapmanb** [comment]
Sorry I wish I had more suggestions but I don't know what to do beyond trying to install on a different filesystem to see if you see the same behavior. I don't have any experience that filesystem (https://en.wikipedia.org/wiki/BeeGFS) so have nothing practical to guess about it's behavior here. If you just want to get it working you could manually change the problem file: `/cluster/home/skanduri/bcbio/anaconda/share/rtg-tools-3.6-0/rtg.cfg` so `/opt/anaconda1anaconda2anaconda3` is `/cluster/home/skanduri/bcbio/anaconda/`. That's all the conda installer should be doing. If this is a persistent problem you may have to change it in other tools as well since it uses this templating trick regularly, but this could at least get you further along. Hope this helps.

**Comment by KanduriC** [comment]
The rtg configuration file at `/cluster/home/skanduri/bcbio/anaconda/share/rtg-tools-3.6-0/rtg.cfg` contain `/cluster/home/skanduri/bcbio/anaconda/` but not `/opt/anaconda1anaconda2anaconda3`. Could this problem be similar to an issue you had earlier [here?](https://github.com/ContinuumIO/anaconda-issues/issues/228)

**Comment by chapmanb** [comment]
Could you post the error message you're seeing now? If that file has the right configuration after the update we might be running into a different problem and need to diagnose that. Thanks much.

**Comment by KanduriC** [comment]
Thanks for the support once again. The rtg configuration file at `/cluster/home/skanduri/bcbio/anaconda/share/rtg-tools-3.6-0/rtg.cfg` contained `/cluster/home/skanduri/bcbio/anaconda/`, but the rtg configuration file at `bcbio/anaconda/pkgs/rtg-tools-3.6-0/share/rtg-tools-3.6-0/` contained `/opt/anaconda1anaconda2anaconda3`. Changing this as per your suggestion above helped the installation to move forward. But now it got stuck with a new error as shown below. 

stdout:

--2016-07-21 13:40:56--  https://github.com/lh3/varcmp/raw/master/scripts/LCR-hs37d5.bed.gz
Resolving github.com... 192.30.253.112
Connecting to github.com|192.30.253.112|:443... connected.
bgzip: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/lh3/varcmp/master/scripts/LCR-hs37d5.bed.gz [following]
--2016-07-21 13:40:57--  https://raw.githubusercontent.com/lh3/varcmp/master/scripts/LCR-hs37d5.bed.gz
Resolving raw.githubusercontent.com... 151.101.12.133
Connecting to raw.githubusercontent.com|151.101.12.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9915051 (9.5M) [application/octet-stream]
Saving to: “STDOUT”

 0% [                                       ] 0           --.-K/s              
gzip: stdout: Broken pipe
 0% [                                       ] 64,759      --.-K/s   in 0.1s    


Cannot write to “-” (Success).
Traceback (most recent call last):
  File "/cluster/home/skanduri/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 474, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 809, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/cluster/home/skanduri/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/cluster/home/skanduri/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 127
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/cluster/home/skanduri/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=./bcbio_tools/', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the problem. It looks like you have a broken bgzip in your PATH:
```
 bgzip: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```
Is this the bcbio installed bgzip or another one? You should have able to tell using `which bgzip`. If it's installed a different way you can add the bcbio installed directory first on your path to ensure you get that one. The one installed with bcbio should link to a local anaconda libcrypto to avoid this type of library problem:
```
$ ldd /path/to/bcbio/anaconda/bin/bgzip | grep crypto
        libcrypto.so.1.0.0 => /usr/local/share/bcbio_nextgen/anaconda/bin/../lib/libcrypto.so.1.0.0 (0x00007f7d0bba0000)
```
Hope that helps.

**Comment by KanduriC** [comment]
Thanks a lot. Exporting the path as you suggested helped the installation progress and now its installed. Thanks once again. 
`export LD_LIBRARY_PATH=/usit/abel/u1/skanduri/bcbio/anaconda/lib:$LD_LIBRARY_PATH`
