### ISSUE TITLE
error on install -> update

### ISSUE THREAD

**Issue by brentp** [chapmanb/bcbio-nextgen#1473]
I get through most of the install and then the command
```
./anaconda/bin/bcbio_nextgen.py upgrade --tooldir=~/bcbio --genomes GRCh37 --aligners bwa --isolate --data
```
gives the error:
```
Traceback (most recent call last):
  File "./anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.8', 'bcbio_nextgen.py')
  File "/uufs/chpc.utah.edu/common/home/u6000771/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/uufs/chpc.utah.edu/common/home/u6000771/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.8-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 285, in upgrade_bcbio_data
    remotes["genome_resources"])
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 305, in _upgrade_genome_resources
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'disable_warnings'
```

when I look in `/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py` I can see that disable_warnings() is there.

Any ideas?

**Comment by roryk** [comment]
Hi Brent,

It looks like `/uufs/chpc.utah.edu/common/home/u6000771/.local/lib/python2.7/site-packages` is sneaking into the path somehow, maybe it is picking up the requests from there by accident? Is that in your PYTHONPATH?

**Comment by brentp** [comment]
Hi Rory, thanks for the quick reply. I didn't see that.
my PYTHONPATH is not set, so not sure what was happening. I deleted my entire ~/.local/lib/python2.7/ dir and I'see what happens.

**Comment by brentp** [comment]
that did it. thanks again.

**Comment by roryk** [comment]
Score!
