### ISSUE TITLE
convert sex 1 or 2 to male or female

### ISSUE THREAD

**Issue by brentp** [chapmanb/bcbio-nextgen#1482]
I'm getting an error (see below) that I think is because I have sex: 1 or sex: 2 in my .yaml, instead of sex: male and sex: female. This is because I created the yaml from my ped file where it's reasonable to use that encoding. 

If that is the cause of the error, it'd be nice to add checks for that on load (it got pretty far into the processing before I saw the error) or to convert or handle 1 or 2 as encoding sex.

Here is the full traceback:
```
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u6000771/bcbio/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.8', 'bcbio_nextgen.py')
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script

  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.8-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <mo
dule>
    main(**kwargs)
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.8-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
    fc_dir, run_info_yaml)
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 175, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 119, in run
    for xs in to_process.values()))
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 135, in run
    for data in view.map_sync(fn, items, track=False):
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 342, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-136>", line 2, in map
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 50, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-135>", line 2, in map
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 35, in save_ids
    ret = f(self, *args, **kwargs)
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1109, in map
    return pf.map(*sequences)
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 269, in map
    ret = self(*sequences)
  File "<decorator-gen-118>", line 2, in __call__
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 252, in __call__
    return r.get()
  File "/scratch/ucgd/lustre/u6000771/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 166, in get
    raise self.exception()
ipyparallel.error.CompositeError: one or more exceptions from call to method: detect_sv
[Engine Exception]AttributeError: 'int' object has no attribute 'lower'
[Engine Exception]AttributeError: 'int' object has no attribute 'lower'
[Engine Exception]AttributeError: 'int' object has no attribute 'lower'
[Engine Exception]AttributeError: 'int' object has no attribute 'lower'
.... 7 more exceptions ...
```

**Comment by chapmanb** [comment]
Brent -- sorry about the problem, we hadn't run into PED based gender specifications before so weren't correctly handling them. I pushed a fix to resolve this so if you update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
it should do the right thing if you restart your analysis. Thanks much for the heads up on the problem.

**Comment by brentp** [comment]
thanks brad! if affected status is used anywhere, might be nice to have the same for that.

I saw there is a section in the docs about a ped in the metdata section but didn't see how to use it.

**Comment by ohofmann** [comment]
The PED support probably hasn't been tested that much. Would be good to clarify the priorities, e.g., what happens when PED and sample CSV disagree on gender specification, or what trumps when it comes to affected/unaffected. Batch information would always come from the CSV, afaik.

**Comment by chapmanb** [comment]
Brent and Oliver -- thanks for pushing the PED usage forward. We haven't done a lot with it so happy to have suggestions about how it can be easier. I added support for 1/2 style specifications in phenotype and also improved the documentation about how the PED files are used. Oliver, for template creation the PED file supplements what is in the CSV so will only fill in values if they're not already present. We assume that the information in the custom bcbio CSV is more correct/current than the PED file. Alternatively if the PED file already has everything for gender, phenotype and batching you don't need anything in your CSV for these and it'll pull them in. Hope this helps.
