### ISSUE TITLE
[seqbuster] ValueError("Same isomir %s from different sequence")

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1484]
```
[2016-07-21T00:48Z] Create seqbuster count data at /BiO/BioPeople/brandon/test_bcbio/smrna/mirqc_bcbio/work/mirbase.
Traceback (most recent call last):
  File "/BiO/BioTools/bcbio/data/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 325, in smallrnaseqpipeline
    samples = run_parallel("seqcluster_cluster", [samples])
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 92, in seqcluster_cluster
    return seqcluster.run_cluster(*args)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/srna/group.py", line 96, in run_cluster
    out_mirna = _make_isomir_counts(data, out_dir=op.join(work_dir, "mirbase"))
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/srna/group.py", line 201, in _make_isomir_counts
    out_file, dt, dt_pre = _tab_output(reads, miraligner_fn + ".back", dd.get_sample_name(sample[0]))
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/seqcluster/seqbuster/__init__.py", line 382, in _tab_output
    raise ValueError("Same isomir %s from different sequence: \n%s and \n%s" % (annotation, res, seen_ann[annotation]))
ValueError: Same isomir hsa-miR-92a-3p:0:I-TT:0:0 from different sequence:
TATTGCACTTGTCCCGGCCTGTGTT       seq_58497_x4    4       hsa-miR-92a-3p  NA      NA      0       I-TT    0       0       NA      NA      miRNA   hsa-mir-92a-2   1 and
TATTGCACTTGTCCCGGCCTGTTTT       seq_136330_x111 111     hsa-miR-92a-3p  NA      NA      0       I-TT    0       0       NA      NA      miRNA   hsa-mir-92a-1   1
```

Can you check this ?

**Comment by lpantano** [comment]
Hi,

sorry about this. Java  8 migration was not that smoothly. I updated the tool in bioconda, you will need to update `--tools` at least, and remove `mirbase` folder in your working directory.

let me know if that fixes this error.

(actually using mirqc data to test it and I saw the same error. miraligner 3.1 should work again)

thanks for helping with the bugs.

**Comment by hmkim** [comment]
After I update the bcbio, there is no error in small rna workflow.

Thanks for your support.
