### ISSUE TITLE
Java/GATK incompatibility problem

### ISSUE THREAD

**Issue by ycl6** [chapmanb/bcbio-nextgen#1494]
It seems the `anaconda/bin/gatk-framework` is using Java installed in `/usr/bin` instead of that in `anaconda/bin`

Error message:
```
[2016-07-29T03:11Z] Combine variant files
[2016-07-29T03:11Z] Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/gatk/engine/CommandLineGATK : Unsupported major.minor version 52.0
[2016-07-29T03:11Z]     at java.lang.ClassLoader.defineClass1(Native Method)
[2016-07-29T03:11Z]     at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[2016-07-29T03:11Z]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[2016-07-29T03:11Z]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[2016-07-29T03:11Z]     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[2016-07-29T03:11Z]     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[2016-07-29T03:11Z]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[2016-07-29T03:11Z]     at java.security.AccessController.doPrivileged(Native Method)
[2016-07-29T03:11Z]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[2016-07-29T03:11Z]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[2016-07-29T03:11Z]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[2016-07-29T03:11Z]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[2016-07-29T03:11Z]     at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
[2016-07-29T03:11Z] Uncaught exception occurred
```

```
$ bcbio_nextgen.py -v
0.9.9
```

I commented off the `if` block to stop the script from using `/usr/bin/java` for it to work. Shouldn't the script always use Java 1.8.0 in the `anaconda/bin` to avoid incompatibility?
```
JAR_DIR=$DIR
ENV_PREFIX="$(dirname $(dirname $DIR))"
# Use Java installed with Anaconda to ensure correct version
java="$ENV_PREFIX/bin/java"

if [ -e "$JAVA_HOME/bin/java" ]
then
java="$JAVA_HOME/bin/java"
fi
```

**Comment by chapmanb** [comment]
Sorry about the issue. Since this is the first release using the anaconda installed java. the `JAVA_HOME` checks are left intentionally to allow people to override the use of that java if they run into issues and have a local Java 1.8 install they prefer. Currently you need to do:
```
unset JAVA_HOME
```
if you have it enabled which will avoid using a global java installation. Hope this helps.

**Comment by chapmanb** [comment]
Thanks again for the feedback, I hope that workaround helped. After more feedback, we've changed the development version of bcbio to unset JAVA_HOME automatically (https://github.com/chapmanb/bcbio-nextgen/commit/6bbbc7c0f6772969ccf5ef9f51e8b570b9022142) which will hopefully fix this problem going forward. Hope your analysis finished cleanly.
