### ISSUE TITLE
Split Alignments

### ISSUE THREAD

**Issue by lsturm1** [chapmanb/bcbio-nextgen#1496]
Hello,

I am running an alignment of FASTQ files using bwa. It works fine for most of the individuals, but on some of them bcbio creates a split folder and then creates two copies of the BAM files. Do you know what the issue might be?

All the best,
Luke

**Comment by lsturm1** [comment]
Hi,

Also I have two more questions. I also got an error during the alignment:

[2016-07-27T15:11Z] sh-17-10.local: [mem_sam_pe] paired reads have different names: "HISEQ557:333:H2KC5ADXY:1:1101:1262:2068", "HISEQ557:332:H2MFWADXY:1:1101:1272:2162"
[2016-07-27T15:11Z] sh-17-10.local:
[2016-07-27T15:11Z] sh-17-10.local: samblaster: Loaded 84 header sequence entries.
[2016-07-27T15:11Z] sh-17-10.local: Uncaught exception occurred
Traceback (most recent call last):
 File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
   _do_run(cmd, checks, log_stdout)
 File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
   raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; 

Do you have any idea why this might be? 


Also one last thing... I have successfully run jobs using bcbio-nextgen, but right now I am trying to run a job and it starting up and then not doing anything. If I go to the log/ipython/log directory there is an ipcontroller log file. In that, it looks something like this: 

2016-07-29 18:58:09.113 [VMFixIPControllerApp] Hub listening on tcp://*:60269 for registration.
2016-07-29 18:58:09.116 [VMFixIPControllerApp] Hub using DB backend: 'NoDB'
2016-07-29 18:58:09.369 [VMFixIPControllerApp] hub::created hub
2016-07-29 18:58:09.370 [VMFixIPControllerApp] writing connection info to /scratch/PI/euan/projects/elite/bcbio/projects/pro\
ject_n101_align/work/log/ipython/security/ipcontroller-7d62d450-667e-4779-80b6-7f04f98bec31-client.json
2016-07-29 18:58:09.373 [VMFixIPControllerApp] writing connection info to /scratch/PI/euan/projects/elite/bcbio/projects/pro\
ject_n101_align/work/log/ipython/security/ipcontroller-7d62d450-667e-4779-80b6-7f04f98bec31-engine.json
2016-07-29 18:58:09.375 [VMFixIPControllerApp] task::using Python leastload Task scheduler
2016-07-29 18:58:09.375 [VMFixIPControllerApp] Heartmonitor started
2016-07-29 18:58:09.388 [VMFixIPControllerApp] Creating pid file: /scratch/PI/euan/projects/elite/bcbio/projects/project_n10\
1_align/work/log/ipython/pid/ipcontroller-7d62d450-667e-4779-80b6-7f04f98bec31.pid
2016-07-29 18:58:09.398 [VMFixIPControllerApp] client::client '\x00k\x8bEg' requested 'connection_request'
2016-07-29 18:58:09.398 [VMFixIPControllerApp] client::client ['\x00k\x8bEg'] connected
2016-07-29 18:58:11.701 [VMFixIPControllerApp] client::client '\x00k\x8bEh' requested 'connection_request'
2016-07-29 18:58:11.701 [VMFixIPControllerApp] client::client ['\x00k\x8bEh'] connected
2016-07-29 18:58:16.717 [VMFixIPControllerApp] client::client '\x00k\x8bEi' requested 'connection_request'
2016-07-29 18:58:16.717 [VMFixIPControllerApp] client::client ['\x00k\x8bEi'] connected
2016-07-29 18:58:21.731 [VMFixIPControllerApp] client::client '\x00k\x8bEj' requested 'connection_request'


This patter of requested, connected just keeps repeating. On jobs that successfully ran, the next step is that the engine would be successfully registered, but this never seems to happen. Do you have any insight into this?

Thank you in advance for any help,
Luke

**Comment by chapmanb** [comment]
Luke;
Thanks for all the questions and sorry about the issues. Answering them in order:

- bcbio will automatically split up alignments for larger fastq inputs, so will prepare the input files for indexing then align chunks of the fastq and merge back into the final BAM. If this is causing problems or you don't want it, you can set `align_split_size: false` in your configuration:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

- The `paired reads have different names` error could indicate a problem with your paired input files (the original fastqs are not properly paired) or it could be an indication of an I/O error reading files from disk. Is this a persistent problem with your inputs if you re-run?

- The controller/engine problem does look like the engines fail to connect to the controller. Did they successfully start? Can you see them running in your batch system? Is it a persistent issue if you restart? It could be you're waiting for resources in the scheduler system or there is some kind of communication error but there is not enough information to know how to debug further. As a next step we'd probably need to understand the differences between when bcbio works and does not in your setup.

Hope this helps with getting your analyses run.

**Comment by lsturm1** [comment]
Hi Brad! Thank you so much! There is no need to apologize, as I am new to bioinformatics and greatly appreciate all of your help and being able to use your wonderful tool! Thank you for the answer to the first question! 

To answer your questions about the paired reads have different names error, I suppose I need to figure out the third issue about connecting, so I can actually rerun the tests to see if the error was a one off or a consistent problem haha. 

For the connection issue: I was able to run a couple jobs with bcbio-nextgen, but since then I have consistently not been able to run any jobs with bcbio-nextgen because of the engine connection issues. In our SLURM system, it shows that the main job is running. The main job launches the helper jobs, such as the engine and the controller. The main job and the controller are running (seen by it trying to connect), but while the engine job appears on our batch system it is stuck in the pending state. Is there any advise you could give to me to help debug or any other information that might be helpful to know in order to advise me? 

Luke

**Comment by chapmanb** [comment]
Luke;
Thanks for following up. I'm not sure why the engines and controllers would have problems connecting, especially if this worked on your system setup previously. That indicates there are no blocked ports or other issues, so hopefully it is just a resource allocation issue on the cluster. Hopefully it works cleanly when the cluster is less busy and let us know if we can help. Thanks again.

**Comment by lpantano** [comment]
Hi,

I am closing this, because it seems resolve. 

thanks!
