### ISSUE TITLE
gatk bcbio error

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1497]
Hi! I'm having problems with the latest dev version of bcbio. The error message is found below. Any ideas?

//Pär

```
CalledProcessError: Command 'set -o pipefail; export PATH=/home/genetik/bcbio/share/bcbio/anaconda/bin:$PATH && /home/genetik/bcbio/share/bcbio/anaconda/bin/gatk-framework -Xms750m -Xmx2000m -XX:+UseSerialGC -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment realign recal -o /home/genetik/calling/haloplex/160708_M00568_0174_000000000-ARHBP/calling/work/bamprep/16-4623/chr1/tx/tmp0dMrI7/16-4623-sort-chr1_0_25870287-prep-prealign.bam
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.6-24-g59fd391): 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Invalid argument value 'realign' at position 6.
##### ERROR Invalid argument value 'recal' at position 7.
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1

**Comment by parlar** [comment]
I'm pasting a little bit more of the output, if necessary.

```
 max: 127595531
Between block sizes:
  min: 287
  5%: 344.75
  25%: 1003.25
  median: 2365.5
  75%: 15080.5
  95%: 142929.25
  99%: 24990570.5
  max: 43839113

[2016-08-03T10:00Z] Timing: hla typing
[2016-08-03T10:00Z] Resource requests: freebayes, gatk, gatk-haplotype, picard, platypus, samtools; memory: 2.00, 3.50, 3.50, 3.50, 2.00, 2.00; cores: 16, 1, 1, 1, 16, 16
[2016-08-03T10:00Z] Configuring 16 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2016-08-03T10:00Z] Timing: alignment post-processing
[2016-08-03T10:00Z] multiprocessing: piped_bamprep
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 0, 25870287) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 25880402, 55505727) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 55509505, 78381828) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 78383240, 116244057) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 116245531, 156085075) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 156095984, 201328393) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 201328740, 218520399) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 218536665, 236850109) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr1', 236881147, 249250621) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr2', 0, 21226216) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr2', 21227130, 105977901) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr2', 105979731, 179392485) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr2', 179392990, 220283772) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr2', 220284806, 243199373) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr3', 30664680, 46899961) : 16-4623
[2016-08-03T10:00Z] GATK pre-alignment ('chr3', 0, 30648479) : 16-4623
[2016-08-03T10:00Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-08-03T10:00Z] ##### ERROR A USER ERROR has occurred (version 3.6-24-g59fd391):
[2016-08-03T10:00Z] ##### ERROR
[2016-08-03T10:00Z] ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2016-08-03T10:00Z] ##### ERROR The error message below tells you what is the problem.
[2016-08-03T10:00Z] ##### ERROR
[2016-08-03T10:00Z] ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2016-08-03T10:00Z] ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2016-08-03T10:00Z] ##### ERROR
[2016-08-03T10:00Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2016-08-03T10:00Z] ##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
[2016-08-03T10:00Z] ##### ERROR
[2016-08-03T10:00Z] ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
[2016-08-03T10:00Z] ##### ERROR
[2016-08-03T10:00Z] ##### ERROR MESSAGE: Invalid argument value 'realign' at position 6.
[2016-08-03T10:00Z] ##### ERROR Invalid argument value 'recal' at position 7.
[2016-08-03T10:00Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-08-03T10:00Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/home/genetik/bcbio/share/bcbio/anaconda/bin:$PATH && /home/genetik/bcbio/share/bcbio/anaconda/bin/gatk-framework -Xms750m -Xmx2000m -XX:+UseSerialGC -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment realign recal -o /home/genetik/calling/haloplex/160708_M00568_0174_000000000-ARHBP/calling/work/bamprep/16-4623/chr1/tx/tmpxQ5oLh/16-4623-sort-chr1_25880402_55505727-prep-prealign.bam

**Comment by chapmanb** [comment]
Pär;
Sorry about the issue, I'm confused as to what happened here. It looks like the command lines are completely messed up, you're getting `realign recal` instead of the expected  parameters. I'm not sure what would cause this. Would you be able to run this with a single core (`-n 1`) so we can see exactly where it fails? Would you also be able to share your configuration so I can try to reproduce here? Thanks much for the help debugging.

**Comment by parlar** [comment]
Hi!

Please find attached, the complete output from a run using the ```-n 16``` (bcbio_output.txt) and the output from  ```-n 1```. There are gzip: Broken path warnings. I've checked the input fastq files using ```gzip -t``` and they seem ok. Also, I upgraded from gatk 3.5 to gatk 3.6, maybe this could have something to do with it?

It appears to me that the error has to do with the realignment step (?) . I do this because I use the alignment when assessing found variants, and using realignment has not been an issue before.

cheers,

Pär

complete -n 16 output:
[bcbio_output.txt](https://github.com/chapmanb/bcbio-nextgen/files/403631/bcbio_output.txt)

-n 1 output:
```
[2016-08-05T11:12Z] System YAML configuration: /home/genetik/bcbio/share/bcbio/galaxy/bcbio_system.yaml
[2016-08-05T11:12Z] Resource requests: bwa, sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16, 16
[2016-08-05T11:12Z] Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job
[2016-08-05T11:12Z] run local -- checkpoint passed: multicore
[2016-08-05T11:12Z] Timing: organize samples
[2016-08-05T11:12Z] multiprocessing: organize_samples
[2016-08-05T11:12Z] Using input YAML configuration: /home/genetik/calling/haloplex/160708_M00568_0174_000000000-ARHBP/calling/config/calling.yaml
[2016-08-05T11:12Z] Checking sample YAML configuration: /home/genetik/calling/haloplex/160708_M00568_0174_000000000-ARHBP/calling/config/calling.yaml
[2016-08-05T11:12Z] Testing minimum versions of installed programs
[2016-08-05T11:13Z] Timing: alignment preparation
[2016-08-05T11:13Z] multiprocessing: prep_align_inputs
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] multiprocessing: disambiguate_split
[2016-08-05T11:13Z] Timing: alignment
[2016-08-05T11:13Z] multiprocessing: process_alignment
[2016-08-05T11:13Z] Aligning lane 16-4623 with bwa aligner
[2016-08-05T11:13Z] Aligning lane 16-4653 with bwa aligner
[2016-08-05T11:13Z] Aligning lane 16-4669 with bwa aligner
[2016-08-05T11:13Z] Aligning lane 16-4670 with bwa aligner
[2016-08-05T11:13Z] Aligning lane 16-4672 with bwa aligner
[2016-08-05T11:13Z] Aligning lane 16-4884 with bwa aligner
[2016-08-05T11:13Z] Timing: callable regions
[2016-08-05T11:13Z] multiprocessing: prep_samples
[2016-08-05T11:13Z] multiprocessing: postprocess_alignment
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-05T11:13Z] multiprocessing: combine_sample_regions
[2016-08-05T11:13Z] Identified 66 parallel analysis blocks
Block sizes:
  min: 1661458
  5%: 9448122.5
  25%: 19335508.25
  median: 30527962.0
  75%: 51787653.75
  95%: 97588388.25
  99%: 121930600.3
  max: 127595531
Between block sizes:
  min: 287
  5%: 344.75
  25%: 1003.25
  median: 2365.5
  75%: 15080.5
  95%: 142929.25
  99%: 24990570.5
  max: 43839113

[2016-08-05T11:13Z] Timing: hla typing
[2016-08-05T11:13Z] Resource requests: freebayes, gatk, gatk-haplotype, picard, platypus, samtools; memory: 2.00, 3.50, 3.50, 3.50, 2.00, 2.00; cores: 16, 1, 1, 1, 16, 16
[2016-08-05T11:13Z] Configuring 1 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2016-08-05T11:13Z] Timing: alignment post-processing
[2016-08-05T11:13Z] multiprocessing: piped_bamprep
[2016-08-05T11:13Z] GATK pre-alignment ('chr1', 0, 25870287) : 16-4623
[2016-08-05T11:13Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-08-05T11:13Z] ##### ERROR A USER ERROR has occurred (version 3.6-24-g59fd391):
[2016-08-05T11:13Z] ##### ERROR
[2016-08-05T11:13Z] ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2016-08-05T11:13Z] ##### ERROR The error message below tells you what is the problem.
[2016-08-05T11:13Z] ##### ERROR
[2016-08-05T11:13Z] ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2016-08-05T11:13Z] ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2016-08-05T11:13Z] ##### ERROR
[2016-08-05T11:13Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2016-08-05T11:13Z] ##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
[2016-08-05T11:13Z] ##### ERROR
[2016-08-05T11:13Z] ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
[2016-08-05T11:13Z] ##### ERROR
[2016-08-05T11:13Z] ##### ERROR MESSAGE: Invalid argument value 'realign' at position 6.
[2016-08-05T11:13Z] ##### ERROR Invalid argument value 'recal' at position 7.
[2016-08-05T11:13Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-08-05T11:13Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/home/genetik/bcbio/share/bcbio/anaconda/bin:$PATH && /home/genetik/bcbio/share/bcbio/anaconda/bin/gatk-framework -Xms750m -Xmx2000m -XX:+UseSerialGC -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment realign recal -o /home/genetik/calling/haloplex/160708_M00568_0174_000000000-ARHBP/calling/work/bamprep/16-4623/chr1/tx/tmp8gCxnZ/16-4623-sort-chr1_0_25870287-prep-prealign.bam
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.6-24-g59fd391): 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Invalid argument value 'realign' at position 6.
##### ERROR Invalid argument value 'recal' at position 7.
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/genetik/bcbio/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/genetik/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 148, in variant2pipeline
    samples = region.parallel_prep_region(samples, run_parallel)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 138, in parallel_prep_region
    "piped_bamprep", _add_combine_info, file_key, ["config"])
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 120, in piped_bamprep
    return bamprep.piped_bamprep(*args)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bamprep.py", line 142, in piped_bamprep
    _piped_bamprep_region(data, region, out_file, tmp_dir)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bamprep.py", line 120, in _piped_bamprep_region
    _piped_bamprep_region_gatk(data, region, prep_params, out_file, tmp_dir)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bamprep.py", line 89, in _piped_bamprep_region_gatk
    prep_params)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bamprep.py", line 62, in _piped_realign_gatk
    do.run(cmd, "GATK pre-alignment {0}".format(region), data)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/genetik/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/home/genetik/bcbio/share/bcbio/anaconda/bin:$PATH && /home/genetik/bcbio/share/bcbio/anaconda/bin/gatk-framework -Xms750m -Xmx2000m -XX:+UseSerialGC -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment realign recal -o /home/genetik/calling/haloplex/160708_M00568_0174_000000000-ARHBP/calling/work/bamprep/16-4623/chr1/tx/tmp8gCxnZ/16-4623-sort-chr1_0_25870287-prep-prealign.bam
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.6-24-g59fd391): 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Invalid argument value 'realign' at position 6.
##### ERROR Invalid argument value 'recal' at position 7.
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Pär -- thanks for the additional details, this helps a lot to identify the bug. This was a problem with the transition to using GATK 3.6 (which has realignment in the freely available version). There was a bug in the code that used realignment but not recalibration. If you update to the latest development version it should work cleanly for you now. Sorry about the problem and thank you for the help tracking it down.

**Comment by parlar** [comment]
Great, thanks!
