### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by lsturm1** [chapmanb/bcbio-nextgen#1498]
Hi,

I was running a job to align and also to do variant calling (freebayes), but very close to the end all of the engines got cancelled due to a memory error. In the bcbio-ipengine.err file it said:

slurmstepd: error: **\* JOB 9203180 ON sh-5-26 CANCELLED AT 2016-08-02T16:40:40 ***
slurmstepd: error: **\* JOB 9200008 ON sh-17-9 CANCELLED AT 2016-08-02T16:40:40 ***
slurmstepd: error: **\* JOB 9200091 ON sh-17-11 CANCELLED AT 2016-08-02T16:40:40 ***
slurmstepd: error: **\* JOB 9200007 ON sh-17-9 CANCELLED AT 2016-08-02T16:40:40 ***
slurmstepd: error: **\* JOB 9200090 ON sh-17-11 CANCELLED AT 2016-08-02T16:40:40 ***
slurmstepd: error: Exceeded step memory limit slurmstepd: error: Exceeded step memory limitat some point.
 at some point.
slurmstepd: error: Exceeded job memory limit at some point.
slurmstepd: error: Exceeded step memory limit at some point.
slurmstepd: error: Exceeded step memory limit at some point.

In the bcbio-nextgen-debug.log, the last thing it tried to do was: 

[2016-08-02T23:14Z] sh-17-10.local: ipython: concat_variant_files
[2016-08-02T23:14Z] sh-17-9.local: Resource requests: ; memory: 1.00; cores: 1
[2016-08-02T23:14Z] sh-17-9.local: Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-02T23:40Z] sh-17-10.local: Resource requests: bcbio_variation, fastqc, gatk, gemini, qsignature, samtools, snpeff; \
memory: 2.50, 4.00, 0.12, 2.00, 10.00; cores: 1, 1, 1, 16, 1, 16, 1
[2016-08-02T23:40Z] sh-17-10.local: Configuring 1 jobs to run, using 6 cores each with 62.4g of memory reserved for each job

Do you know what step and why this is failing?

Also as a kind of a side question: is there a difference between the bam-sort that gets produced in the work directory and the bam-ready that gets produced in the final directory? 

All the best,
Luke

**Comment by lsturm1** [comment]
Hi Brad,

In addition to the above two questions, I tried to rerun a similar job, but with less intense memory requirements, but now I am getting an error just trying to start up the ipcontroller... in the ipcontroller log file:

2016-08-03 15:40:10.593 [IPClusterStart] Starting ipcluster with [daemon=True]
2016-08-03 15:40:10.599 [IPClusterStart] Creating pid file: /scratch/PI/euan/projects/elite/bcbio/projects/project_n101_alig\
n_no_var/work/log/ipython/pid/ipcluster-5e3cf830-5af5-4a4f-973e-93f351181915.pid
2016-08-03 15:40:10.600 [IPClusterStart] Starting Controller with cluster_helper.cluster.BcbioSLURMControllerLauncher
2016-08-03 15:40:10.600 [IPClusterStart] Starting BcbioSLURMControllerLauncher: ['sbatch', u'./SLURM_controller3fdac455-0a7b\
-4bf1-96ca-9916e7fcd6d3']
2016-08-03 15:40:10.600 [IPClusterStart] adding PBS queue settings to batch script
2016-08-03 15:40:10.600 [IPClusterStart] Writing batch script: ./SLURM_controller3fdac455-0a7b-4bf1-96ca-9916e7fcd6d3
2016-08-03 15:40:10.617 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 506, in start\
_controller
    self.controller_launcher.start()
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 510, in start
    return super(BcbioSLURMControllerLauncher, self).start(1)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1151, in start
    output = check_output(self.args, env=os.environ)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['sbatch', u'./SLURM_controller3fdac455-0a7b-4bf1-96ca-9916e7fcd6d3']' returned non-zero exit s\
tatus 1


Any thoughts?

**Comment by chapmanb** [comment]
Luke;
Sorry about the issues, happy to try and help with debugging. For memory issues the best way to debug is to look in `log/bcbio-nextgen-commands.log` to see if you can identify the command that ran on the machine that was killed by SLURM. This could help us isolate the memory usage and potentially assign less cores/more memory to that process. If it's hard to pick out the failing process you can try re-running in parallel (or on a single core with `-n 1`) to see if you can replicate. Happy to provide more specific pointers with additional details about where it fails.

Regarding the BAM file, the `*-ready.bam` file in the final directory is the same aligned and sorted bam file as in the work directory.

Hope this helps.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
