### ISSUE TITLE
Failed to check paired status of BAM file; sambamba not found

### ISSUE THREAD

**Issue by KanduriC** [chapmanb/bcbio-nextgen#1501]
Hello,

I was trying to test run bcbio with the provided RNA-seq example pipeline. The analysis aborted raising a valueerror stating that it could not found sambamba tool. I was checking in bcbio location that sambamba tool was installed. Could you please suggest a turnaround. Thanks.

Stdout:  

```
[2016-08-05T13:22Z] Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2016-08-05T13:22Z] Timing: disambiguation
[2016-08-05T13:22Z] Timing: transcript assembly
[2016-08-05T13:22Z] Timing: estimate expression (threaded)
[2016-08-05T13:22Z] multiprocessing: generate_transcript_counts
[2016-08-05T13:22Z] Sort BAM file (multi core, queryname): rna_seq_example_run.bam to rna_seq_example_run.nsorted.bam
Traceback (most recent call last):
  File "/usit/abel/u1/skanduri/bcbio_tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usit/abel/u1/skanduri/bcbio_tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 251, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 81, in quantitate_expression_parallel
    samples = run_parallel("generate_transcript_counts", samples)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 148, in generate_transcript_counts
    return rnaseq.generate_transcript_counts(*args)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 102, in generate_transcript_counts
    data["count_file"] = featureCounts.count(data)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/featureCounts.py", line 33, in count
    paired_flag = _paired_flag(in_bam)
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/featureCounts.py", line 102, in _paired_flag
    if is_paired(bam_file):
  File "/cluster/home/skanduri/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 40, in is_paired
    raise ValueError("Failed to check paired status of BAM file: %s" % str(stderr))
ValueError: Failed to check paired status of BAM file: /bin/bash: sambamba: command not found
/bin/bash: sambamba: command not found
```

**Comment by roryk** [comment]
Hi Chakravarthi,

Sorry about that-- this is looking for sambamba in your path and isn't finding it. Is `/usit/abel/u1/skanduri/bcbio_tools/bin` in your path? I pushed a fix for this in the development version. If you upgrade with `bcbio_nextgen.py upgrade -u development` you'll get the fix pulled in. You could also add `/usit/abel/u1/skanduri/bcbio_tools/bin` to your path without upgrading and it should fix it.

**Comment by lpantano** [comment]
Hi @KanduriC 

I am closing this because it seems is not a problem anymore, please feel free to open an issue if you find again the problem.

thanks!
