### ISSUE TITLE
Java Version Error

### ISSUE THREAD

**Issue by lsturm1** [chapmanb/bcbio-nextgen#1509]
Hi,

I have been running tests fine in the past, but right now bcbio will stop a job right after it starts do to the java version we have. 

"java version 1.7 required for running MuTect and GATK < 3.6. Found version 1.8.0_92"

Do I need to have an older version of java in my path or is there some update to bcbio that will fix this?

Thanks,
Luke

**Comment by roryk** [comment]
Hi Luke,

Sorry about that-- GATK 3.6+ and Mutect2 both need java 1.8. Mutect1 and GATK < 3.6+ need 1.7. We've swapped to using the bioconda installed java by default. You can override the Java that is being detected by setting your JAVA_HOME to wherever you all have 1.7 installed if you want to keep using 1.7. You could also grab GATK 3.6 and install it following these instructions and move onto using 1.8: http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2

Hope that gets you going again.

**Comment by roryk** [comment]
(via @chapmanb) A less nuclear way than JAVA_HOME would be to just stick the path to your java 1.7 installation somewhere in your PATH which should also work.

**Comment by lsturm1** [comment]
Thank you! I got the new GATK up and running. I am doing a joint call using gatk haplotype for variant calling, but there is a new issue... Here is the traceback:

[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR --
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR stack trace
[2016-08-11T13:39Z] sh-18-20.local: java.util.NoSuchElementException
[2016-08-11T13:39Z] sh-18-20.local:     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1439)
[2016-08-11T13:39Z] sh-18-20.local:     at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.redu\
ceNumberOfAlternativeAllelesBasedOnLikelihoods(HaplotypeCallerGenotypingEngine.java:336)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.assi\
gnGenotypeLikelihoods(HaplotypeCallerGenotypingEngine.java:264)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCaller.map(HaplotypeCaller.\
java:964)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.tools.walkers.haplotypecaller.HaplotypeCaller.map(HaplotypeCaller.\
java:251)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.engine.traversals.TraverseActiveRegions$TraverseActiveRegionMap.ap\
ply(TraverseActiveRegions.java:709)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.engine.traversals.TraverseActiveRegions$TraverseActiveRegionMap.ap\
ply(TraverseActiveRegions.java:705)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.utils.nanoScheduler.NanoScheduler.executeSingleThreaded(NanoSchedu\
ler.java:274)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.utils.nanoScheduler.NanoScheduler.execute(NanoScheduler.java:245)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.engine.traversals.TraverseActiveRegions.traverse(TraverseActiveReg\
ions.java:274)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.engine.traversals.TraverseActiveRegions.traverse(TraverseActiveReg\
ions.java:78)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.engine.executive.LinearMicroScheduler.execute(LinearMicroScheduler\
.java:99)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.engine.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:311)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.engine.CommandLineExecutable.execute(CommandLineExecutable.java:11\
3)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java\
:255)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java\
:157)
[2016-08-11T13:39Z] sh-18-20.local:     at org.broadinstitute.gatk.engine.CommandLineGATK.main(CommandLineGATK.java:108)
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR -------------------------------------------------------------------------------------\
-----
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR A GATK RUNTIME ERROR has occurred (version 3.6-0-g89b7209):
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR This might be a bug. Please check the documentation guide to see if this is a known p\
roblem.
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR Visit our website and forum for extensive documentation and answers to
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR
[2016-08-11T13:39Z] sh-18-20.local: ##### ERROR MESSAGE: Code exception (see stack trace for error itself)


How should I go about fixing this?

Thank you,
Luke

**Comment by chapmanb** [comment]
Luke;
Sorry about the problem, this is a bug in GATK 3.6 that I reported and is fixed:

http://gatkforums.broadinstitute.org/gatk/discussion/7756/hashmap-iterator-problem-with-gatk-3-6-on-na12878-validations#latest

but is not yet in a release, so you have to install a nightly version:

https://software.broadinstitute.org/gatk/download/nightly

with 
```
gatk-register GenomeAnalysisTK-nightly-*.tar.bz2 --noversioncheck
```

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
