### ISSUE TITLE
Running Cancer tumor normal

### ISSUE THREAD

**Issue by ScarecrowFu** [chapmanb/bcbio-nextgen#1514]
hi, i am alan.

I ran  Cancer tumor normal got this problem:

`(root) [root@anchordxR730 work]# bcbio_nextgen.py ../config/cancer-dream-syn3.yaml -n 8
[2016-08-15T01:03Z] System YAML configuration: /iron/bioinfo/share/bcbio/galaxy/bcbio_system.yaml
[2016-08-15T01:03Z] Resource requests: bwa, sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16, 16
[2016-08-15T01:03Z] Configuring 1 jobs to run, using 8 cores each with 16.1g of memory reserved for each job
[2016-08-15T01:03Z] Timing: organize samples
[2016-08-15T01:03Z] multiprocessing: organize_samples
[2016-08-15T01:03Z] Using input YAML configuration: /iron/bioinfo/src/bcbio-nextgen/tests/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2016-08-15T01:03Z] Checking sample YAML configuration: /iron/bioinfo/src/bcbio-nextgen/tests/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2016-08-15T01:03Z] Downloading GRCh37 samtools from AWS
Traceback (most recent call last):
  File "/iron/bioinfo/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 120, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 300, in organize_samples
    return run_info.organize(*args)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 66, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 158, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 207, in get_refs
    galaxy_config, data)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 159, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/iron/bioinfo/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 280, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file GRCh37 samtools
`

**Comment by chapmanb** [comment]
Alan;
Sorry about the problem. It looks like your installation is missing the GRCh37 reference genome. How did you install bcbio? Ideally you should use the automated installer and add `--genomes GRCh37`:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

If you have bcbio installed via the automated installer but without the genome data you can add this in using `bcbio_nextgen.py upgrade`. Hope this helps get your installation working.
