### ISSUE TITLE
BCbio bioconda for managing GATK (3.6) 

### ISSUE THREAD

**Issue by tkoomar** [chapmanb/bcbio-nextgen#1518]
Changes to permissions on my group's HPC recently made a fresh install of bcbio necessary. I opted to install GATK with the awesome new `gatk-register`, rather than `upgrade --tools --toolsplus`. However, when trying to use call variants with haplotype-caller, an error is now thrown, which *appears* to  reference a missing path to the GATK directory in the the `bcbio_system.yaml` file (traceback from `run_test.sh` for the sake of reproduceability):
```
Traceback (most recent call last):
  File "/Dedicated/jmichaelson-wdata/bcbio/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 151, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 177, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 200, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 330, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/gatk.py", line 99, in haplotype_caller
    region, out_file)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/gatk.py", line 43, in _shared_gatk_call_prep
    for a in annotation.get_gatk_annotations(config):
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/annotation.py", line 20, in get_gatk_annotations
    broad_runner = broad.runner_from_config(config)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 430, in runner_from_config
    config_utils.get_program(program, config, "dir"),
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 188, in get_program
    return _get_program_dir(name, pconfig)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 240, in _get_program_dir
    raise ValueError("Could not find directory in config for %s" % name)
ValueError: Could not find directory in config for gatk
ERROR
```
Adding in the appropriate `dir: /path/to/gatk/GenomeAnalysisTK.jar` under `gatk:` in  `bcbio_system.yaml` instead results in a similar, but more puzzling error:

```
Traceback (most recent call last):
  File "/Dedicated/jmichaelson-wdata/bcbio/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 151, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 177, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 200, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 330, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/gatk.py", line 101, in haplotype_caller
    "Require full version of GATK 2.4+ for haplotype calling"
AssertionError: Require full version of GATK 2.4+ for haplotype calling
ERROR
```
I suspect there may be an underlying problem, perhaps with java versions -- but I assumed the biconda managing of GATK should prevent such issues...

**Comment by chapmanb** [comment]
Sorry about the issue, could you try updating bcbio to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
This has some fixes to help better deal with the new GATK 3.6 and Java 8 based on feedback from folks testing 0.9.9. I hope that upgrading will correctly recognize the version in `gatk-register` and avoid the problem. If it doesn't it would be helpful to know if:
```
gatk --version
```
works correctly to ensure there were no problems with registering or other issues. Thanks for the help debugging and patience as we move over to the new approach.

**Comment by tkoomar** [comment]
I tried an upgrade, but forgot to include `-u development`! The test runs clean now, so I assume the issue with the pipeline proper will be resolved as well.

**Comment by Smeds** [comment]
When will this fix be included in a release of bcbio?

**Comment by chapmanb** [comment]
We're working on finalizing a new release now so hopefully in the next week. Hope running the development version will work for you in the interim. Thanks much.

**Comment by Smeds** [comment]
Thanks for the fast answer! Is there a GATK version that works with 0.9.9 release of bcbio, or do we need to wait for a new release of bcbio( or use the development version)?

**Comment by chapmanb** [comment]
I'd suggest using the development version as it has fixes to manage the Java 7/8 transition with any version of GATK. It's pretty stable and will be the one we create the new release from. Let us know if you run into any issues.
