### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ScarecrowFu** [chapmanb/bcbio-nextgen#1520]
HI, I am Alan.

I have installed bcbio-nextgen in another machine

`python bcbio_nextgen_install.py /opt/local/share/bcbio --tooldir=/opt/local/share/bcbio/tools  --genomes GRCh37 --aligners bwa --aligners bowtie2 
`

but it got that errors:

Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O GRCh37-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz''

INFO: Genome preparation method s3 failed, trying next
INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome GRCh37 with index rtg
INFO: Preparing genome GRCh37 with index rtg
[localhost] local: export PATH=/opt/local/share/bcbio/tools/bin:$PATH && export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=2g && rtg format -o rtg/GRCh37.sdf /opt/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
Unable to read /opt/local/share/bcbio/anaconda/bin/RTG.jar

Fatal error: local() encountered an error (return code 1) while executing 'export PATH=/opt/local/share/bcbio/tools/bin:$PATH && export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=2g && rtg format -o rtg/GRCh37.sdf /opt/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa'

Aborting.
INFO: Genome preparation method raw failed, trying next
INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "/opt/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
    
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg/pkg_resources/__init__.py", line 1505, in run_script
    
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/opt/local/src/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/opt/local/src/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/opt/local/src/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/opt/local/src/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/opt/local/src/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/opt/local/src/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 486, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index rtg for GRCh37 by any method
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/opt/local/share/bcbio/tools', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by ScarecrowFu** [comment]
I downloaded the https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz got 404 error

```
[alan@anchordx0 ~]$ wget https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz
--2016-08-18 10:57:25--  https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz
.......
2016-08-18 10:57:28 error  404：Not Found。
```

and then in the broswer,it got this:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>genomes/GRCh37-rtg.tar.xz</Key><RequestId>19F9930E736860EE</RequestId><HostId>xoEZHDX/tqXKlTmp/bcKSEy1BUXf/V5GnoY1cyKktEDgCDD0ZkAheTGhHY4K4SSxeAP21dq/BiU=</HostId></Error>
```

**Comment by ScarecrowFu** [comment]
I have found the solutions at the https://github.com/chapmanb/bcbio-nextgen/issues/1465

```
`bcbio_conda install conda
bcbio_conda uninstall -y rtg-tools
rm -rf  /cluster/home/skanduri/bcbio/anaconda/pkgs/rtg-tools*
bcbio_conda install -c bioconda rtg-tools`
```

**Comment by chapmanb** [comment]
Thanks for following up on your own question and sorry about the problem. I'm still not sure how the rtg-tools installation gets messed up in some cases but glad the refresh worked for you. Hope everything else installs cleanly.
