### ISSUE TITLE
error for gemini

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#1531]
Hi Brad,

Could you please help me check the error when running bcbio:

Loading chunk 0.
Loading chunk 1.
Loading chunk 2.
Loading chunk 3.
Loading chunk 4.
Loading chunk 5.
Loading chunk 6.
Traceback (most recent call last):
  File "/data/bcbio_install/anaconda/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
    args.func(parser, args)
  File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
  File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 48, in load
    load_multicore(args)
  File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 92, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 258, in load_chunks_multicore
    wait_until_finished(procs)
  File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 349, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")

The version of bcbio is
0.9.9 
The version of gemini is 
gemini 0.19.1

Thanks so much !

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. Unfortunately this traceback doesn't provide enough information to diagnose the problem. It tells us that GEMINI failed but not why. There may be a more useful error message for the failed loading chunk earlier in the log file, or you can look at `log/bcbio-commands.log` and find the gemini command that's failing and re-run it separately from bcbio with a single core. This should provide a more useful message to determine what is happening.

As a general suggestion, it might be worth trying:
```
bcbio_conda install -c bioconda geneimpacts
```
so you have version 0.1.4. I recently fixed an issue with snpEff 4.3 output where the GEMINI geneimpacts tool was missing some new fields.

Hope one of these options will fix it for you.

**Comment by junchend** [comment]
Hi Brad,

I updated bcbio, but the error is still:

[2016-08-26T02:20Z] Create gemini database for /data/moyamoya/work/gemini/MOYA-gatk-haplotype-decompose-effects.vcf.gz : S10000015369
[2016-08-26T02:20Z] CADD scores are being loaded (to skip use:--skip-cadd).
[2016-08-26T02:21Z] Traceback (most recent call last):
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/bin/gemini", line 6, in <module>
[2016-08-26T02:21Z]     gemini.gemini_main.main()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-26T02:21Z]     args.func(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 298, in loadchunk_fn
[2016-08-26T02:21Z]     gemini_load_chunk.load(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 843, in load
[2016-08-26T02:21Z]     gemini_loader.populate_from_vcf()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
[2016-08-26T02:21Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 398, in _prepare_variation
[2016-08-26T02:21Z]     Exac = annotations.get_exac_info(var)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
[2016-08-26T02:21Z]     num_hets = int(info_map.get("AC_Het", -1))
[2016-08-26T02:21Z] ValueError: invalid literal for int() with base 10: '9125,1,0'
[2016-08-26T02:21Z] Traceback (most recent call last):
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/bin/gemini", line 6, in <module>
[2016-08-26T02:21Z]     gemini.gemini_main.main()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-26T02:21Z]     args.func(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 298, in loadchunk_fn
[2016-08-26T02:21Z]     gemini_load_chunk.load(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 843, in load
[2016-08-26T02:21Z]     gemini_loader.populate_from_vcf()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
[2016-08-26T02:21Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 398, in _prepare_variation
[2016-08-26T02:21Z]     Exac = annotations.get_exac_info(var)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
[2016-08-26T02:21Z]     num_hets = int(info_map.get("AC_Het", -1))
[2016-08-26T02:21Z] ValueError: invalid literal for int() with base 10: '13019,4,0'
[2016-08-26T02:21Z] Traceback (most recent call last):
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/bin/gemini", line 6, in <module>
[2016-08-26T02:21Z]     gemini.gemini_main.main()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-26T02:21Z]     args.func(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 298, in loadchunk_fn
[2016-08-26T02:21Z]     gemini_load_chunk.load(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 843, in load
[2016-08-26T02:21Z]     gemini_loader.populate_from_vcf()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
[2016-08-26T02:21Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 398, in _prepare_variation
[2016-08-26T02:21Z]     Exac = annotations.get_exac_info(var)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
[2016-08-26T02:21Z]     num_hets = int(info_map.get("AC_Het", -1))
[2016-08-26T02:21Z] ValueError: invalid literal for int() with base 10: '24256,2,0'
[2016-08-26T02:21Z] Traceback (most recent call last):
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/bin/gemini", line 6, in <module>
[2016-08-26T02:21Z]     gemini.gemini_main.main()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-26T02:21Z]     args.func(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 298, in loadchunk_fn
[2016-08-26T02:21Z]     gemini_load_chunk.load(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 843, in load
[2016-08-26T02:21Z]     gemini_loader.populate_from_vcf()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
[2016-08-26T02:21Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 398, in _prepare_variation
[2016-08-26T02:21Z]     Exac = annotations.get_exac_info(var)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
[2016-08-26T02:21Z]     num_hets = int(info_map.get("AC_Het", -1))
[2016-08-26T02:21Z] ValueError: invalid literal for int() with base 10: '21557,1,0'
[2016-08-26T02:21Z] Traceback (most recent call last):
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/bin/gemini", line 6, in <module>
[2016-08-26T02:21Z]     gemini.gemini_main.main()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-26T02:21Z]     args.func(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 298, in loadchunk_fn
[2016-08-26T02:21Z]     gemini_load_chunk.load(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 843, in load
[2016-08-26T02:21Z]     gemini_loader.populate_from_vcf()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
[2016-08-26T02:21Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 398, in _prepare_variation
[2016-08-26T02:21Z]     Exac = annotations.get_exac_info(var)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
[2016-08-26T02:21Z]     num_hets = int(info_map.get("AC_Het", -1))
[2016-08-26T02:21Z] ValueError: invalid literal for int() with base 10: '2953,100,4'
[2016-08-26T02:21Z] Traceback (most recent call last):
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/bin/gemini", line 6, in <module>
[2016-08-26T02:21Z]     gemini.gemini_main.main()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-26T02:21Z]     args.func(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 298, in loadchunk_fn
[2016-08-26T02:21Z]     gemini_load_chunk.load(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 843, in load
[2016-08-26T02:21Z]     gemini_loader.populate_from_vcf()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
[2016-08-26T02:21Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 398, in _prepare_variation
[2016-08-26T02:21Z]     Exac = annotations.get_exac_info(var)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
[2016-08-26T02:21Z]     num_hets = int(info_map.get("AC_Het", -1))
[2016-08-26T02:21Z] ValueError: invalid literal for int() with base 10: '17298,3,1,4,0,0'
[2016-08-26T02:21Z] Traceback (most recent call last):
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/bin/gemini", line 6, in <module>
[2016-08-26T02:21Z]     gemini.gemini_main.main()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-26T02:21Z]     args.func(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 298, in loadchunk_fn
[2016-08-26T02:21Z]     gemini_load_chunk.load(parser, args)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 843, in load
[2016-08-26T02:21Z]     gemini_loader.populate_from_vcf()
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
[2016-08-26T02:21Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 398, in _prepare_variation
[2016-08-26T02:21Z]     Exac = annotations.get_exac_info(var)
[2016-08-26T02:21Z]   File "/data/bcbio_install/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 809, in get_exac_info
[2016-08-26T02:21Z]     num_hets = int(info_map.get("AC_Het", -1))
[2016-08-26T02:21Z] ValueError: invalid literal for int() with base 10: '151,0,15'

Could you please check it?

Thanks !

**Comment by roryk** [comment]
Hi @junchend,

This is due to an old version of ExAc. I'm not sure why some folks are not getting the updated data. This thread has the solution: https://github.com/arq5x/gemini/issues/758

**Comment by junchend** [comment]
Hi roryk,

Thanks so much, it's worked!

Great!

**Comment by roryk** [comment]
Great!
