### ISSUE TITLE
ensemble calling error

### ISSUE THREAD

**Issue by rjsicko** [chapmanb/bcbio-nextgen#1535]
Hi Brad, 
I'm getting errors when bcbio gets to the ensemble calling portion of the pipeline. It may be related to symlinks on the attached drive, but I've tried using a local tmp directory and it did not help.

**debug.log**
````
2016-08-29T11:28Z] System YAML configuration: /usr/local/share/bcbio/galaxy/bcbio_system.yaml
[2016-08-29T11:28Z] Resource requests: bwa, sambamba, samtools; memory: 5.00, 5.00; cores: 8, 8, 8
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 5 cores each with 29.5g of memory reserved for each job
[2016-08-29T11:28Z] run local -- checkpoint passed: multicore
[2016-08-29T11:28Z] Timing: organize samples
[2016-08-29T11:28Z] multiprocessing: organize_samples
[2016-08-29T11:28Z] Using input YAML configuration: /media/sf_BigShare/SCID_recall/batch3/config/batch3.yaml
[2016-08-29T11:28Z] Checking sample YAML configuration: /media/sf_BigShare/SCID_recall/batch3/config/batch3.yaml
[2016-08-29T11:28Z] Testing minimum versions of installed programs
[2016-08-29T11:28Z] Timing: alignment preparation
[2016-08-29T11:28Z] multiprocessing: prep_align_inputs
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] multiprocessing: disambiguate_split
[2016-08-29T11:28Z] Timing: alignment
[2016-08-29T11:28Z] multiprocessing: process_alignment
[2016-08-29T11:28Z] Aligning lane 1_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 2_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 3_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 4_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 5_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 6_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 7_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 8_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 9_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 10_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 11_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 12_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Aligning lane 13_2016-08-25_batch3 with bwa aligner
[2016-08-29T11:28Z] Timing: callable regions
[2016-08-29T11:28Z] multiprocessing: prep_samples
[2016-08-29T11:28Z] multiprocessing: postprocess_alignment
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S10: Assigned coverage as 'regional' with 0.0% genome coverage and 11.8% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S10 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S11: Assigned coverage as 'regional' with 0.0% genome coverage and 12.0% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S11 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] NA12878: Assigned coverage as 'regional' with 0.0% genome coverage and 12.8% offtarget coverage
[2016-08-29T11:28Z] Recalibrating NA12878 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S1: Assigned coverage as 'regional' with 0.0% genome coverage and 12.3% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S1 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S2: Assigned coverage as 'regional' with 0.0% genome coverage and 13.1% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S2 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S3: Assigned coverage as 'regional' with 0.0% genome coverage and 12.4% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S3 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S4: Assigned coverage as 'regional' with 0.0% genome coverage and 10.5% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S4 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S5: Assigned coverage as 'regional' with 0.0% genome coverage and 11.5% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S5 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S6: Assigned coverage as 'regional' with 0.0% genome coverage and 11.6% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S6 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S7: Assigned coverage as 'regional' with 0.0% genome coverage and 12.2% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S7 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S8: Assigned coverage as 'regional' with 0.0% genome coverage and 14.2% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S8 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] S9: Assigned coverage as 'regional' with 0.0% genome coverage and 11.2% offtarget coverage
[2016-08-29T11:28Z] Recalibrating S9 with GATK
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:28Z] NTC: Assigned coverage as 'regional' with 0.0% genome coverage and 46.7% offtarget coverage
[2016-08-29T11:28Z] Recalibrating NTC with GATK
[2016-08-29T11:28Z] multiprocessing: combine_sample_regions
[2016-08-29T11:28Z] Identified 44 parallel analysis blocks
Block sizes:
  min: 1277436
  5%: 11901409.0
  25%: 21572955.25
  median: 36223042.5
  75%: 54704430.0
  95%: 127210291.55
  99%: 133615001.51
  max: 133922298
Between block sizes:
  min: 305
  5%: 369.15
  25%: 967.25
  median: 2545.0
  75%: 4820.25
  95%: 40365.15
  99%: 180867.06
  max: 228177

[2016-08-29T11:28Z] Timing: hla typing
[2016-08-29T11:28Z] Resource requests: freebayes, gatk, gatk-haplotype, picard, platypus; memory: 5.00, 5.00, 5.00, 5.00, 5.00; cores: 8, 8, 8, 1, 8
[2016-08-29T11:28Z] Configuring 5 jobs to run, using 1 cores each with 5.00g of memory reserved for each job
[2016-08-29T11:28Z] run local -- checkpoint passed: full
[2016-08-29T11:28Z] Timing: alignment post-processing
[2016-08-29T11:28Z] multiprocessing: piped_bamprep
[2016-08-29T11:28Z] Timing: variant calling
[2016-08-29T11:28Z] multiprocessing: variantcall_sample
[2016-08-29T11:28Z] multiprocessing: concat_variant_files
[2016-08-29T11:28Z] Resource requests: bcbio_variation, fastqc, gatk, gemini, qsignature, samtools; memory: 5.00, 5.00, 5.00, 5.00, 5.00, 5.00; cores: 1, 8, 8, 8, 8, 8
[2016-08-29T11:28Z] Configuring 1 jobs to run, using 5 cores each with 29.5g of memory reserved for each job
[2016-08-29T11:28Z] Timing: joint squaring off/backfilling
[2016-08-29T11:28Z] Timing: variant post-processing
[2016-08-29T11:28Z] multiprocessing: postprocess_variants
[2016-08-29T11:28Z] Finalizing variant calls: S2, freebayes
[2016-08-29T11:28Z] Calculating variation effects for S2, freebayes
[2016-08-29T11:28Z] Annotate VCF file: S2, freebayes
[2016-08-29T11:28Z] Filtering for S2, freebayes
[2016-08-29T11:28Z] Prioritization for S2, freebayes
[2016-08-29T11:28Z] Germline extraction for S2, freebayes
[2016-08-29T11:28Z] Finalizing variant calls: S2, platypus
[2016-08-29T11:28Z] Calculating variation effects for S2, platypus
[2016-08-29T11:28Z] Annotate VCF file: S2, platypus
[2016-08-29T11:28Z] Filtering for S2, platypus
[2016-08-29T11:28Z] Prioritization for S2, platypus
[2016-08-29T11:28Z] Germline extraction for S2, platypus
[2016-08-29T11:28Z] Finalizing variant calls: S2, gatk-haplotype
[2016-08-29T11:28Z] Calculating variation effects for S2, gatk-haplotype
[2016-08-29T11:28Z] Annotate VCF file: S2, gatk-haplotype
[2016-08-29T11:28Z] Filtering for S2, gatk-haplotype
[2016-08-29T11:28Z] Prioritization for S2, gatk-haplotype
[2016-08-29T11:28Z] Germline extraction for S2, gatk-haplotype
[2016-08-29T11:28Z] multiprocessing: split_variants_by_sample
[2016-08-29T11:28Z] Timing: prepped BAM merging
[2016-08-29T11:28Z] multiprocessing: delayed_bam_merge
[2016-08-29T11:29Z] Timing: validation
[2016-08-29T11:29Z] multiprocessing: compare_to_rm
[2016-08-29T11:29Z] Timing: ensemble calling
[2016-08-29T11:29Z] multiprocessing: combine_calls
[2016-08-29T11:29Z] Ensemble consensus calls for batch3: gatk-haplotype,freebayes,platypus
[2016-08-29T11:29Z] Resource requests: ; memory: 1.00; cores: 1
[2016-08-29T11:29Z] Configuring 5 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2016-08-29T11:29Z] Ensemble calling: batch3
[2016-08-29T11:29Z] Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: For input string: "R", for input source: /media/sf_BigShare/SCID_recall/batch3/work/gemini/batch3-gatk-haplotype.vcf.gz
[2016-08-29T11:29Z] 	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:75)
[2016-08-29T11:29Z] 	at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:59)
[2016-08-29T11:29Z] 	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:85)
[2016-08-29T11:29Z] 	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:66)
[2016-08-29T11:29Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2016-08-29T11:29Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2016-08-29T11:29Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2016-08-29T11:29Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2016-08-29T11:29Z] 	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
[2016-08-29T11:29Z] 	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
[2016-08-29T11:29Z] 	at bcbio.variation.variantcontext$get_vcf_header.invoke(variantcontext.clj:144)
[2016-08-29T11:29Z] 	at bcbio.variation.variantcontext$get_samples.invoke(variantcontext.clj:150)
[2016-08-29T11:29Z] 	at bcbio.variation.vcfsample$consistent_order.invoke(vcfsample.clj:108)
[2016-08-29T11:29Z] 	at bcbio.variation.ensemble$consensus_calls.invoke(ensemble.clj:109)
[2016-08-29T11:29Z] 	at bcbio.variation.ensemble$_main.doInvoke(ensemble.clj:132)
[2016-08-29T11:29Z] 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
[2016-08-29T11:29Z] 	at clojure.core$apply.invoke(core.clj:630)
[2016-08-29T11:29Z] 	at bcbio.variation.core$_main.doInvoke(core.clj:35)
[2016-08-29T11:29Z] 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
[2016-08-29T11:29Z] 	at bcbio.variation.core.main(Unknown Source)
[2016-08-29T11:29Z] Caused by: java.lang.NumberFormatException: For input string: "R"
[2016-08-29T11:29Z] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[2016-08-29T11:29Z] 	at java.lang.Integer.parseInt(Integer.java:580)
[2016-08-29T11:29Z] 	at java.lang.Integer.valueOf(Integer.java:766)
[2016-08-29T11:29Z] 	at htsjdk.variant.vcf.VCFCompoundHeaderLine.<init>(VCFCompoundHeaderLine.java:171)
[2016-08-29T11:29Z] 	at htsjdk.variant.vcf.VCFFormatHeaderLine.<init>(VCFFormatHeaderLine.java:49)
[2016-08-29T11:29Z] 	at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:211)
[2016-08-29T11:29Z] 	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
[2016-08-29T11:29Z] 	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
[2016-08-29T11:29Z] 	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:41)
[2016-08-29T11:29Z] 	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:73)
[2016-08-29T11:29Z] 	... 19 more
[2016-08-29T11:29Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/usr/local/share/bcbio/anaconda/bin:$PATH &&  bcbio-variation -Xms1g -Xmx5g -Djava.io.tmpdir=/media/sf_BigShare/SCID_recall/batch3/work/ensemble/batch3/tmp variant-ensemble /media/sf_BigShare/SCID_recall/batch3/work/ensemble/batch3/config/batch3-ensemble.yaml /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /media/sf_BigShare/SCID_recall/batch3/work/ensemble/batch3/batch3-ensemble.vcf /media/sf_BigShare/SCID_recall/batch3/work/gemini/batch3-gatk-haplotype.vcf.gz /media/sf_BigShare/SCID_recall/batch3/work/gemini/batch3-freebayes.vcf.gz /media/sf_BigShare/SCID_recall/batch3/work/gemini/batch3-platypus.vcf.gz
Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: For input string: "R", for input source: /media/sf_BigShare/SCID_recall/batch3/work/gemini/batch3-gatk-haplotype.vcf.gz
	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:75)
	at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:59)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:85)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at bcbio.variation.variantcontext$get_vcf_header.invoke(variantcontext.clj:144)
	at bcbio.variation.variantcontext$get_samples.invoke(variantcontext.clj:150)
	at bcbio.variation.vcfsample$consistent_order.invoke(vcfsample.clj:108)
	at bcbio.variation.ensemble$consensus_calls.invoke(ensemble.clj:109)
	at bcbio.variation.ensemble$_main.doInvoke(ensemble.clj:132)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:630)
	at bcbio.variation.core$_main.doInvoke(core.clj:35)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at bcbio.variation.core.main(Unknown Source)
Caused by: java.lang.NumberFormatException: For input string: "R"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at htsjdk.variant.vcf.VCFCompoundHeaderLine.<init>(VCFCompoundHeaderLine.java:171)
	at htsjdk.variant.vcf.VCFFormatHeaderLine.<init>(VCFFormatHeaderLine.java:49)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:211)
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:41)
	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:73)
	... 19 more
' returned non-zero exit status 1
````

**Comment by chapmanb** [comment]
Thanks much for the report, it looks like there is something problematic about the GATK HaplotypeCaller output that the VCF parser doesn't like:
```
/media/sf_BigShare/SCID_recall/batch3/work/gemini/batch3-gatk-haplotype.vcf.gz
```
It might be worth checking if this file is valid:
```
gatk-framework -T ValidateVariants -R /path/to/ref.fa -V /media/sf_BigShare/SCID_recall/batch3/work/gemini/batch3-gatk-haplotype.vcf.gz
```
If so, it could be that bcbio-variation can't handle some new feature of recent GATK variant callers. You could switch over to use the new ensemble method (http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#ensemble-variant-calling) with:
```
ensemble:
  numpass: 2
```
Hope this helps.

**Comment by rjsicko** [comment]
Ah, I didn't notice the updated ensemble method, sorry. I used the new method and it's going again. Thanks!

I did check the file and It looks like the file was valid. Here's the output of ValidateVariants:
````
INFO  07:39:12,806 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.6-24-g59fd391, Compiled 2016/06/06 17:53:29 
INFO  07:39:12,806 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute 
INFO  07:39:12,807 HelpFormatter - For support and documentation go to https://www.broadinstitute.org/gatk 
INFO  07:39:12,807 HelpFormatter - [Wed Aug 31 07:39:12 EDT 2016] Executing on Linux 4.4.0-31-generic amd64 
INFO  07:39:12,808 HelpFormatter - OpenJDK 64-Bit Server VM 1.8.0_92-b15 JdkDeflater 
INFO  07:39:12,813 HelpFormatter - Program Args: -T ValidateVariants -R /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -V /media/sf_BigShare/SCID_recall/batch3/work/gemini/batch3-gatk-haplotype.vcf.gz 
INFO  07:39:12,823 HelpFormatter - Executing as rsicko@bl8vbox on Linux 4.4.0-31-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_92-b15. 
INFO  07:39:12,823 HelpFormatter - Date/Time: 2016/08/31 07:39:12 
INFO  07:39:12,824 HelpFormatter - --------------------------------------------------------------------------------- 
INFO  07:39:12,824 HelpFormatter - --------------------------------------------------------------------------------- 
INFO  07:39:12,897 GenomeAnalysisEngine - Strictness is SILENT 
INFO  07:39:13,229 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 1000 
WARN  07:39:14,115 IndexDictionaryUtils - Track variant doesn't have a sequence dictionary built in, skipping dictionary validation 
INFO  07:39:14,537 GenomeAnalysisEngine - Preparing for traversal 
INFO  07:39:14,558 GenomeAnalysisEngine - Done preparing for traversal 
INFO  07:39:14,562 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING] 
INFO  07:39:14,562 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining 
INFO  07:39:14,563 ProgressMeter -        Location |     sites | elapsed |     sites | completed | runtime |   runtime 
Successfully validated the input file.  Checked 547 records with no failures.
INFO  07:39:17,071 ProgressMeter -            done       547.0     2.0 s      75.9 m       97.8%     2.0 s       0.0 s 
INFO  07:39:17,074 ProgressMeter - Total runtime 2.51 secs, 0.04 min, 0.00 hours 
------------------------------------------------------------------------------------------
Done. There were 1 WARN messages, the first 1 are repeated below.
WARN  07:39:14,115 IndexDictionaryUtils - Track variant doesn't have a sequence dictionary built in, skipping dictionary validation 
------------------------------------------------------------------------------------------
````

**Comment by chapmanb** [comment]
Glad this worked and thanks for following up. It sounds like there is something new in GATK 3.6 output that the older bcbio.variation GATK code does not handle. Since we've primarily replaced this functionality with the new ensemble method and validation using rtg vcfeval hopefully we can move forward with these. Thanks again.
