### ISSUE TITLE
bidirectional_gene_fusion

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1536]
Greetings,

  This is a new one for me. Running joint-haplotype caller on maybe 10 WES samples.
```
[2016-08-29T12:20Z] Create gemini database for /home/bwubb/NGS/NCI_Exome/data/work/gemini/FollowUp-gatk-haplotype-joint-decompose-effects.vcf.gz : TC-T0120-KT36201-A
[2016-08-29T12:20Z] CADD scores are being loaded (to skip use:--skip-cadd).
[2016-08-29T12:23Z] pid 31469: 9999 variants processed.
[2016-08-29T12:27Z] pid 31469: 19999 variants processed.
[2016-08-29T12:30Z] pid 31469: 29999 variants processed.
[2016-08-29T12:33Z] pid 31469: 39999 variants processed.
[2016-08-29T12:37Z] pid 31469: 49999 variants processed.
[2016-08-29T12:40Z] pid 31469: 59999 variants processed.
[2016-08-29T12:43Z] pid 31469: 69999 variants processed.
[2016-08-29T12:46Z] pid 31469: 79999 variants processed.
[2016-08-29T12:50Z] pid 31469: 89999 variants processed.
[2016-08-29T12:53Z] pid 31469: 99999 variants processed.
[2016-08-29T12:56Z] pid 31469: 109999 variants processed.
[2016-08-29T12:57Z] Traceback (most recent call last):
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/bin/gemini", line 6, in <module>
[2016-08-29T12:57Z]     gemini.gemini_main.main()
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-29T12:57Z]     args.func(parser, args)
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
[2016-08-29T12:57Z]     gemini_load.load(parser, args)
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 50, in load
[2016-08-29T12:57Z]     l = load_singlecore(args)
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 85, in load_singlecore
[2016-08-29T12:57Z]     l.populate_from_vcf()
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 201, in populate_from_vcf
[2016-08-29T12:57Z]     (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 525, in _prepare_variation
[2016-08-29T12:57Z]     impact_so=impact.so, impact_severity=impact.effect_severity,
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 330, in effect_severity
[2016-08-29T12:57Z]     return self.impact_severity
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 364, in impact_severity
[2016-08-29T12:57Z]     return ['xxx', 'LOW', 'MED', 'HIGH'][self.severity]
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 355, in severity
[2016-08-29T12:57Z]     v = max(lookup[sev[csq]] for csq in self.consequences)
[2016-08-29T12:57Z]   File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 355, in <genexpr>
[2016-08-29T12:57Z]     v = max(lookup[sev[csq]] for csq in self.consequences)
[2016-08-29T12:57Z] KeyError: 'bidirectional_gene_fusion'
[2016-08-29T12:57Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/bwubb/bcbio-nextgen/anaconda/bin/gemini  load  --passonly --skip-gerp-bp  -v /home/bwubb/NGS/NCI_Exome/data/work/gemini/FollowUp-gatk-haplotype-joint-decompose-effects.vcf.gz -t snpEff --cores 1 --tempdir /home/bwubb/NGS/NCI_Exome/data/work/gemini/tx/tmp1iuKOn /home/bwubb/NGS/NCI_Exome/data/work/gemini/tx/tmp1iuKOn/FollowUp-gatk-haplotype-joint.db
...
```

I see maybe 3 blocks of those before an exit status of 1. It has been awhile since I have done a joint-haplotypecaller, perhaps something has changed? Unless this is unrelated to the caller and more about gemini? Thanks.

-bwubb

**Comment by chapmanb** [comment]
Brad;
Sorry about the issues. Can you try running:

bcbio_conda install -c bioconda geneimpacts

This should give you version 0.1.4_1 which has a fix for this problem. It's an
issue with new annotations added to snpEff 4.3 that needed integration into
GEMINI via geneimpacts.

Hope this fixes it for you.

**Comment by bwubb** [comment]
Thank you! The run completed successfully.
