### ISSUE TITLE
gemini importerror pysam

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1537]
Hi Brad,

We're having some issues with gemini as the last step of our analysis.
We're getting the following error

```
2016-08-31T14:02Z] pbsnode-1: ipython: prep_gemini_db
[2016-08-31T14:02Z] pbsnode-1: Create gemini database for /home/tsante/demultiplex/160714_J00178_0006_AHFKCCBBXX_allow1error/samples-merged/work/gemini/D1415149-gatk-haplotype-decompose-vepeffects.vcf.gz : D1415149
[2016-08-31T14:02Z] pbsnode-1: Create gemini database for /home/tsante/demultiplex/160714_J00178_0006_AHFKCCBBXX_allow1error/samples-merged/work/gemini/D1608292-gatk-haplotype-decompose-vepeffects.vcf.gz : D1608292
[2016-08-31T14:02Z] pbsnode-1: Create gemini database for /home/tsante/demultiplex/160714_J00178_0006_AHFKCCBBXX_allow1error/samples-merged/work/gemini/D1509515-gatk-haplotype-decompose-vepeffects.vcf.gz : D1509515
[2016-08-31T14:03Z] pbsnode-1: CADD scores are being loaded (to skip use:--skip-cadd).
[2016-08-31T14:03Z] pbsnode-1: CADD scores are being loaded (to skip use:--skip-cadd).
[2016-08-31T14:03Z] pbsnode-1: CADD scores are being loaded (to skip use:--skip-cadd).
[2016-08-31T14:03Z] pbsnode-1: Traceback (most recent call last):
[2016-08-31T14:03Z] pbsnode-1:   File "/Shared/Software/bin/gemini", line 6, in <module>
[2016-08-31T14:03Z] pbsnode-1:     gemini.gemini_main.main()
[2016-08-31T14:03Z] pbsnode-1:   File "/Shared/Software/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
[2016-08-31T14:03Z] pbsnode-1:     args.func(parser, args)
[2016-08-31T14:03Z] pbsnode-1:   File "/Shared/Software/lib/python2.7/site-packages/gemini/gemini_main.py", line 297, in loadchunk_fn
[2016-08-31T14:03Z] pbsnode-1:     import gemini_load_chunk
[2016-08-31T14:03Z] pbsnode-1:   File "/Shared/Software/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 22, in <module>
[2016-08-31T14:03Z] pbsnode-1:     import annotations
[2016-08-31T14:03Z] pbsnode-1:   File "/Shared/Software/lib/python2.7/site-packages/gemini/annotations.py", line 2, in <module>
[2016-08-31T14:03Z] pbsnode-1:     import pysam
[2016-08-31T14:03Z] pbsnode-1: ImportError: No module named pysam
```

It seems the pysam module is missing for some reason, while I'm certain it's installed (I've checked)

Any ideas what could be the cause?

Thanks!
M

**Comment by chapmanb** [comment]
This looks like the PATH is setup to run a different installed gemini, from `/Shared/Software/bin` with python libraries in `/Shared/Software/lib/python2.7/site-packages/`. It seems like that installation/python is missing pysam. If you adjust your PATH so the gemini installed with bcbio is picked up first hopefully that'll give you a working version and fix the problem. Hope this helps.

**Comment by matthdsm** [comment]
Hi Brad, 

sorry for the dumb question, I totally missed that, closing the issue!

M
