### ISSUE TITLE
AWS S3 upload error for non-standard regions

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1540]
I set up a run configured to retrive files from S3, process them and upload the results to S3. The first part works so far (download, processing). Unfortunately, I receive an error message at the end of the run when result files should be uploaded back to the S3 bucket:

>  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/boto/s3/connection.py", line 625, in create_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message><RequestId>233BC74673DB268B</RequestId><HostId>wEQl4FFZ8FPYtal+x05q8e4ovQnHFonkst9mX3jpYlda5INsY7xwjjG6E7Y3tzDtarzUc+7fmBM=</HostId></Error>

Some info about my configuration:

- Single AWS instance with local installation of bcbio
- AWS access keys of an IAM user are made available as environment variables
- `AWS_DEFAULT_REGION` is also set to `eu-west-1` as environment variable
- In addition, I set the `region` option in the `Upload` section to `eu-west-1` (not sure how this relates to the environment variable)
- Looking at the CloudTrail log on AWS it seems that bcbio tries to "create" a bucket with the specified name in the region `eu-west-1`. The bucket already exists in the specified region. I am not sure if that makes a difference.
- I had to restart the run a number of times after unrelated error messages. I would like to avoid to re-run it.

Is there anybody successfully using S3 buckets in AWS regions other than the default `us-east-1`?

Regards,
Ben

**Comment by gabeng** [comment]
Now that I look at the API call in CloudTrail more closely, I see that there is an `IllegalLocationConstraintException`. 
The resource (my bucket) is correctly identified. The region does not seem to be the issue. The error message from boto may be misleading. However there seems to be an issue with creating a bucket that already exists. Could it be that re-starting the run is the issue? The data has already been downloaded, so bcbio assumes that it has to create a bucket for upload?

**Comment by gabeng** [comment]
This is the raw event in CloudTrail:

{

    "eventVersion": "1.04",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "...",
        "arn": "arn:aws:iam::...",
        "accountId": "...",
        "accessKeyId": "...",
        "userName": "bcbio-test"
    },
    "eventTime": "2016-09-03T11:06:12Z",
    "eventSource": "s3.amazonaws.com",
    "eventName": "CreateBucket",
    "awsRegion": "eu-west-1",
    "sourceIPAddress": "...",
    "userAgent": "[Boto/2.40.0 Python/2.7.12 Linux/3.13.0-92-generic]",
    "errorCode": "IllegalLocationConstraintException",
    "errorMessage": "The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.",
    "requestParameters": {
        "bucketName": "..."
    },
    "responseElements": null,
    "requestID": "233BC74673DB268B",
    "eventID": "bd4b721c-5883-4280-842c-6053a26cefbb",
    "eventType": "AwsApiCall",
    "recipientAccountId": "..."
}

**Comment by chapmanb** [comment]
Ben;
Sorry about the issue. I pushed a fix to the latest bcbio development version (`bcbio_nextgen.py upgrade -u development`) that I hope will resolve the problem. I think we need to pass the bucket region to create_bucket as well as to the connection. I'm not 100% sure this will resolve everything since bcbio shouldn't be creating the bucket if it already exists since it performs a lookup prior to this. If it's still failing happy to try and debug more. It would help to have a full traceback to be sure I'm changing the right parts of bcbio. Sorry I'm not very familiar with S3 buckets in non us-east so hopefully this helps sort out the problem.

**Comment by gabeng** [comment]
Brad,
Thanks for addressing this so quickly. 
I performed the update with the development branch. Now I get a different error:

````python
 Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 194, in variant2pipeline
    samples = run_parallel("upload_samples", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 316, in upload_samples
    return upload.from_sample(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 32, in from_sample
    approach.update_file(finfo, sample, upload_config)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/s3.py", line 24, in update_file
    if os.path.isdir(ffinal):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

This is the upload part of the sample config:
```python
upload:
  bucket: bioinf-pipeline-limbus-medtec-com
  folder: trusightmyeloid/final
  method: s3
  region: eu-west-1

**Comment by chapmanb** [comment]
Ben -- sorry about the issue. Right now you need a `dir` parameter in your upload section as well since bcbio stages the files in a local directory before upload:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#upload

The general idea was to have final directories both locally and on s3 so folks could work with either. This might be worth revisiting if it ends up being a problem with disk space. I pushed a fix to have a more useful error message here. Hope this gets things working for you.

**Comment by gabeng** [comment]
Brad,
I erroneously removed the `dir` paramter in one of my various tries. Added it back now.
Now I get another S3error. I do not see any API call in CloudTrail. It does not even get so far.
I am puzzled why there appears `us-east-1` in the log. I set the env variable correctly. The `region` tag in the sample config is correct as well.

```python
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 194, in variant2pipeline
    samples = run_parallel("upload_samples", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 316, in upload_samples
    return upload.from_sample(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 32, in from_sample
    approach.update_file(finfo, sample, upload_config)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/s3.py", line 40, in update_file
    bucket = conn.create_bucket(config["bucket"], location=config.get("region", "us-east-1"))
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/boto/s3/connection.py", line 625, in create_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>49436828E0B6CC95</RequestId><HostId>xjsJ+RX+FwK5ssK+art2fTIBBzQeqF9qpEHZ5CDyUrf9EYjUN5kpZbPMtGWCxecb1w4ZlKSvQKU=</HostId></Error>

**Comment by chapmanb** [comment]
Ben;
This looks like a straight up permission error that the IAM user you're running as does not have permission to try and create the bucket. Typically we use IAM instance profiles that allow s3 access to the resources we need, so if you're taking that approach maybe it's missing a permission setting?

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html

The `us-east-1` in the traceback is from the code, bcbio defaults to that if "region" is not set so it's not a reflection of the call being made.

Hope this helps.

**Comment by gabeng** [comment]
Hi Brad,
well that's the thing: the bucket already exists. It is the same bucket that bcbio retrieved the fastq from. I guess, I will terminate this instance and try another one with an IAM instance profile instead.

**Comment by chapmanb** [comment]
Ben -- sorry I wish I had a better clue of what is going on here. It should be finding the bucket, not creating it, in the first place and should also have access based on the download. Maybe permissions are setup so the user can get files but not list or do other operations so it's having trouble identifying the bucket exists? I tend to use pretty broad-based S3 permissions because the structure is a bit complex.
