### ISSUE TITLE
using bcbio-nextgen with torque pbs

### ISSUE THREAD

**Issue by ScarecrowFu** [chapmanb/bcbio-nextgen#1541]
i was running bcbio-nextgen with torque pbs,is it the command right?

`[alan@gzjz_manager_node work]$ bcbio_nextgen.py ../config/cancer-dream-syn3.yaml -n 8 -t ipython  -s torque -q batch -r nodes='gzjz_compute_node1:ppn=9+gzjz_compute_node2:ppn=2' `

it got IOError.

```

[2016-09-06T06:44Z] gzjz_manager_node: System YAML configuration: /opt/local/share/bcbio/galaxy/bcbio_system.yaml
[2016-09-06T06:44Z] gzjz_manager_node: Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2016-09-06T06:44Z] gzjz_manager_node: Configuring 1 jobs to run, using 8 cores each with 24.1g of memory reserved for each job
2016-09-06 14:44:31.750 [IPClusterStart] Using existing profile dir: u'/home/alan/cancer-dream-syn3/work/log/ipython'
2016-09-06 14:44:31.750 [IPClusterStart] Searching path [u'/home/alan/cancer-dream-syn3/work', u'/home/alan/cancer-dream-syn3/work/log/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2016-09-06 14:44:31.750 [IPClusterStart] Attempting to load config file: ipython_config.py
2016-09-06 14:44:31.750 [IPClusterStart] Looking for ipython_config in /etc/ipython
2016-09-06 14:44:31.751 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2016-09-06 14:44:31.751 [IPClusterStart] Looking for ipython_config in /home/alan/cancer-dream-syn3/work/log/ipython
2016-09-06 14:44:31.751 [IPClusterStart] Loaded config file: /home/alan/cancer-dream-syn3/work/log/ipython/ipython_config.py
2016-09-06 14:44:31.751 [IPClusterStart] Looking for ipython_config in /home/alan/cancer-dream-syn3/work
2016-09-06 14:44:31.752 [IPClusterStart] Attempting to load config file: ipcluster_94aa14f1_f2ed_455c_ba7f_e6c6f9b1fc46_config.py
2016-09-06 14:44:31.752 [IPClusterStart] Looking for ipcontroller_config in /etc/ipython
2016-09-06 14:44:31.752 [IPClusterStart] Looking for ipcontroller_config in /usr/local/etc/ipython
2016-09-06 14:44:31.752 [IPClusterStart] Looking for ipcontroller_config in /home/alan/cancer-dream-syn3/work/log/ipython
2016-09-06 14:44:31.752 [IPClusterStart] Loaded config file: /home/alan/cancer-dream-syn3/work/log/ipython/ipcontroller_config.py
2016-09-06 14:44:31.752 [IPClusterStart] Looking for ipcontroller_config in /home/alan/cancer-dream-syn3/work
2016-09-06 14:44:31.752 [IPClusterStart] Attempting to load config file: ipcluster_94aa14f1_f2ed_455c_ba7f_e6c6f9b1fc46_config.py
2016-09-06 14:44:31.753 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2016-09-06 14:44:31.753 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2016-09-06 14:44:31.753 [IPClusterStart] Looking for ipengine_config in /home/alan/cancer-dream-syn3/work/log/ipython
2016-09-06 14:44:31.753 [IPClusterStart] Loaded config file: /home/alan/cancer-dream-syn3/work/log/ipython/ipengine_config.py
2016-09-06 14:44:31.753 [IPClusterStart] Looking for ipengine_config in /home/alan/cancer-dream-syn3/work
2016-09-06 14:44:31.753 [IPClusterStart] Attempting to load config file: ipcluster_94aa14f1_f2ed_455c_ba7f_e6c6f9b1fc46_config.py
2016-09-06 14:44:31.753 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2016-09-06 14:44:31.753 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2016-09-06 14:44:31.754 [IPClusterStart] Looking for ipcluster_config in /home/alan/cancer-dream-syn3/work/log/ipython
2016-09-06 14:44:31.754 [IPClusterStart] Loaded config file: /home/alan/cancer-dream-syn3/work/log/ipython/ipcluster_config.py
2016-09-06 14:44:31.754 [IPClusterStart] Looking for ipcluster_config in /home/alan/cancer-dream-syn3/work
0 Engines r2016-09-06 14:59:38.849 [IPClusterStop] Using existing profile dir: u'/home/alan/cancer-dream-syn3/work/log/ipython'
2016-09-06 14:59:38.852 [IPClusterStop] Stopping cluster [pid=192692] with [signal=2]
0 Engines runningTraceback (most recent call last):
  File "/opt/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
    fc_dir, run_info_yaml)
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 117, in variant2pipeline
    multiplier=alignprep.parallel_multiplier(samples)) as run_parallel:
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 53, in start
    with ipython.create(parallel, dirs, config) as view:
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 1022, in cluster_view
    wait_for_all_engines=wait_for_all_engines)
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 974, in __init__
    """)
IOError: 

        The cluster startup timed out. This could be for a couple of reasons. The
        most common reason is that the queue you are submitting jobs to is
        oversubscribed. You can check if this is what is happening by trying again,
        and watching to see if jobs are in a pending state or a running state when
        the startup times out. If they are in the pending state, that means we just
        need to wait longer for them to start, which you can specify by passing
        the --timeout parameter, in minutes.

        The second reason is that there is a problem with the controller and engine
        jobs being submitted to the scheduler. In the directory you ran from,
        you should see files that are named YourScheduler_enginesABunchOfNumbers and
        YourScheduler_controllerABunchOfNumbers. If you submit one of those files
        manually to your scheduler (for example bsub < YourScheduler_controllerABunchOfNumbers)
        You will get a more helpful error message that might help you figure out what
        is going wrong.

        The third reason is that you need to submit your bcbio_nextgen.py job itself as a job;
        bcbio-nextgen needs to run on a compute node, not the login node. So the
        command you use to run bcbio-nextgen should be submitted as a job to
        the scheduler. You can diagnose this because the controller and engine
        jobs will be in the running state, but the cluster will still timeout.

        Finally, it may be an issue with how the cluster is configured-- the controller
        and engine jobs are unable to talk to each other. They need to be able to open
        ports on the machines each of them are running on in order to work. You
        can diagnose this as the possible issue by if you have submitted the bcbio-nextgen
        job to the scheduler, the bcbio-nextgen main job and the controller and
        engine jobs are all in a running state and the cluster still times out. This will
        likely to be something that you'll have to talk to the administrators of the cluster
        you are using about.

        If you need help debugging, please post an issue here and we'll try to help you
        with the detective work:

        https://github.com/roryk/ipython-cluster-helper/issues

```

i think i am not really understand how to use bcbio-nextgen with torque pbs.

in my Clusters，i have one manger_node and three Compute nodes.

in my other scripts , i use my Clusters like this:

#!/bin/bash
#PBS -l nodes=gzjz_compute_node1:ppn=9+gzjz_compute_node2:ppn=2
#PBS -q batch
#PBS -j oe
#PBS -N test_task
#PBS -o log
cd /home/gzjz
module load fastqc
mkdir results
fastqc -o results /home/gzjz/source_data/*.fq

can i run bcbio-nextgen with torque pbs like this>:
```

#!/bin/bash
##PBS -l nodes=gzjz_compute_node1:ppn=9+gzjz_compute_node2:ppn=2
##PBS -q batch
##PBS -j oe
##PBS -N test_helloworld
##PBS -o log
cd /home/alan/cancer-dream-syn3/work
module load bcbio/1.0.0a0
bcbio_nextgen.py ../config/cancer-dream-syn3.yaml -n 8

```

**Comment by roryk** [comment]
Hi @ScarecrowFu,

Your command isn't using the Torque scheduler, it is just passing on the bcbio-nextgen command and running it locally: http://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#ipython-parallel has some more information about how to run it on schedulers like Torque.
