### ISSUE TITLE
RNASeq Picard Java Error

### ISSUE THREAD

**Issue by firatuyulur** [chapmanb/bcbio-nextgen#1545]
Hi Brad,
I am running the example dataset for RNASeq analysis(https://bcbio-nextgen.readthedocs.io/en/latest/contents/testing.html#rnaseq-example). Just to clarify; I installed bcbio with the automated installation script. then I installed GATK 3.6 and mutect 1.7 according to bcbio manuel.

At picard step, I come across an error. the log file is as;

2016-09-06T17:00Z] Index BAM file: merged.bam
[2016-09-06T17:02Z] Picard: AddOrReplaceReadGroups
[2016-09-06T17:02Z] Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine : Unsupported major.minor version 52.0
[2016-09-06T17:02Z] 	at java.lang.ClassLoader.defineClass1(Native Method)
[2016-09-06T17:02Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/scratch/tmorova15/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/scratch/tmorova15/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/mnt/scratch/tmorova15/bcbio_ku/share/bcbio/anaconda/bin:$PATH && picard -Xms750m -Xmx3500m -XX:+UseSerialGC AddOrReplaceReadGroups INPUT=/mnt/scratch/tmorova15/seqc-test/seqc/work/align/UHRR_rep2/1_2016-09-02_seqc_tophat/merged.bam OUTPUT=/mnt/scratch/tmorova15/seqc-test/seqc/work/align/UHRR_rep2/1_2016-09-02_seqc_tophat/tx/tmpk8Lk30/merged-fixrgs.bam SORT_ORDER=coordinate RGID=UHRR_rep2 RGLB=None RGPL=illumina RGPU=1_2016-09-02_seqc RGSM=UHRR_rep2 TMP_DIR=/mnt/scratch/tmorova15/seqc-test/seqc/work/tx/tmp1RQ60y VALIDATION_STRINGENCY=SILENT
Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
' returned non-zero exit status 1

I googled the error. As our java version is 1.7, I switched it to 1.8 for fixing the error. re-ran the analysis; it continued from picard step again. here is the error;

[2016-09-07T07:40Z] Aligning lane 1_2016-09-02_seqc with tophat2 aligner
[2016-09-07T07:40Z] Picard: AddOrReplaceReadGroups
[2016-09-07T07:40Z] Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine : Unsupported major.minor version 52.0
[2016-09-07T07:40Z] 	at java.lang.ClassLoader.defineClass1(Native Method)
[2016-09-07T07:40Z] 	at java.lang.ClassLoader.defineClass(Unknown Source)
[2016-09-07T07:40Z] 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[2016-09-07T07:40Z] 	at java.net.URLClassLoader.defineClass(Unknown Source)
[2016-09-07T07:40Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/scratch/tmorova15/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/scratch/tmorova15/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/mnt/scratch/tmorova15/bcbio_ku/share/bcbio/anaconda/bin:$PATH && picard -Xms750m -Xmx3500m -XX:+UseSerialGC AddOrReplaceReadGroups INPUT=/mnt/scratch/tmorova15/seqc-test/seqc/work/align/UHRR_rep2/1_2016-09-02_seqc_tophat/merged.bam OUTPUT=/mnt/scratch/tmorova15/seqc-test/seqc/work/align/UHRR_rep2/1_2016-09-02_seqc_tophat/tx/tmpSIq_IM/merged-fixrgs.bam SORT_ORDER=coordinate RGID=UHRR_rep2 RGLB=None RGPL=illumina RGPU=1_2016-09-02_seqc RGSM=UHRR_rep2 TMP_DIR=/mnt/scratch/tmorova15/seqc-test/seqc/work/tx/tmp04Ssm4 VALIDATION_STRINGENCY=SILENT
Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
' returned non-zero exit status 1

What should I do to fix this? Thanks a lot.
Fırat

**Comment by roryk** [comment]
Hi Firat,

It looks like Java 1.8 isn't getting picked up so you're still getting the version mismatch-- if you type:

`/mnt/scratch/tmorova15/bcbio_ku/share/bcbio/anaconda/bin/java -version` does it report 1.8?

Does `java -version` report something different?

**Comment by firatuyulur** [comment]
Hi Rory,
Thanks for reply.

[tmorova15@lufer ~]$ /mnt/scratch/tmorova15/bcbio_ku/share/bcbio/anaconda/bin/java -version
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (Zulu 8.15.0.1-linux64) (build 1.8.0_92-b15)
OpenJDK 64-Bit Server VM (Zulu 8.15.0.1-linux64) (build 25.92-b15, mixed mode)

when I type java -version, it is again 1.8

**Comment by roryk** [comment]
Is your JAVA_HOME set?

**Comment by firatuyulur** [comment]
Yes, i believe it is: ```JAVA_HOME=/mnt/scratch/tmorova15/java18/jdk1.8.0_101```

**Comment by roryk** [comment]
Gotcha-- are you loading any modules or anything like that in your job submission script for bcbio that end up pointing $JAVA_HOME to 1.7? Somehow java 1.7 is getting picked up. The picard script checks for JAVA_HOME and uses $JAVA_HOME/bin/java, if it is set, else it uses the java 1.8 installed via anaconda. Unseting JAVA_HOME explicitly in the job submission script prior to running might also fix this.

**Comment by firatuyulur** [comment]
```details:
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    strandedness: unstranded
    trim_reads: read_through
  analysis: RNA-seq
  description: UHRR_rep2
  files:
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950080_1.fastq.gz
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950080_2.fastq.gz
  genome_build: GRCh37
  metadata:
    panel: UHRR
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    strandedness: unstranded
    trim_reads: read_through
  analysis: RNA-seq
  description: HBRR_rep2
  files:
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950081_1.fastq.gz
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950081_2.fastq.gz
  genome_build: GRCh37
  metadata:
    panel: HBRR
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    strandedness: unstranded
    trim_reads: read_through
  analysis: RNA-seq
  description: UHRR_rep1
  files:
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950078_1.fastq.gz
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950078_2.fastq.gz
  genome_build: GRCh37
  metadata:
    panel: UHRR
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    strandedness: unstranded
    trim_reads: read_through
  analysis: RNA-seq
  description: HBRR_rep1
  files:
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950079_1.fastq.gz
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950079_2.fastq.gz
  genome_build: GRCh37
  metadata:
    panel: HBRR
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    strandedness: unstranded
    trim_reads: read_through
  analysis: RNA-seq
  description: UHRR_rep3
  files:
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950082_1.fastq.gz
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950082_2.fastq.gz
  genome_build: GRCh37
  metadata:
    panel: UHRR
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    strandedness: unstranded
    trim_reads: read_through
  analysis: RNA-seq
  description: HBRR_rep3
  files:
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950083_1.fastq.gz
  - /mnt/scratch/tmorova15/seqc-test/input/SRR950083_2.fastq.gz
  genome_build: GRCh37
  metadata:
    panel: HBRR
fc_date: '2016-09-02'
fc_name: seqc
upload:
  dir: ../final```

Here is my .yaml file. I dont think I am doing something without noticing.

**Comment by roryk** [comment]
Are you running `bcbio-nextgen` locally?

**Comment by firatuyulur** [comment]
no, via ssh, sun grid engine.

**Comment by roryk** [comment]
What does your job submission script for SGE look like? When you ssh into the machine, prior to submitting the script, is JAVA_HOME set to something different?

**Comment by firatuyulur** [comment]
Rory thanks a lot. I am using a file "example_final" with qsub. apparently I forgot to change the java part inside "example_final" although I changed all the others... I believe this will fix it. thanks already:)

**Comment by roryk** [comment]
Great!

**Comment by roryk** [comment]
If you have the memory for it, running STAR as the aligner will be much, much faster. You need a machine with at least 40 G of memory though.
