### ISSUE TITLE
MemoryError 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1548]
Hi Brad, 
Hi am running a WXS project and but iphyton have this strange MemoryError I have tried to increase the memory in python-cluster-helper but It does not work at all.

do you have any suggestion? 

2016-09-08 17:15:20.038 [IPClusterStart] Attempting to load config file: ipcluster_7e6ab525_1755_45f2_ab4f_910ebc7aa8ff_config.py
2016-09-08 17:15:20.039 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2016-09-08 17:15:20.039 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2016-09-08 17:15:20.039 [IPClusterStart] Looking for ipengine_config in /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/wxs/wxs/work/log/ipython
2016-09-08 17:15:20.040 [IPClusterStart] Loaded config file: /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/wxs/wxs/work/log/ipython/ipengine_config.py
2016-09-08 17:15:20.041 [IPClusterStart] Looking for ipengine_config in /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/wxs/wxs/work
2016-09-08 17:15:20.041 [IPClusterStart] Attempting to load config file: ipcluster_7e6ab525_1755_45f2_ab4f_910ebc7aa8ff_config.py
2016-09-08 17:15:20.041 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2016-09-08 17:15:20.042 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2016-09-08 17:15:20.042 [IPClusterStart] Looking for ipcluster_config in /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/wxs/wxs/work/log/ipython
2016-09-08 17:15:20.043 [IPClusterStart] Loaded config file: /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/wxs/wxs/work/log/ipython/ipcluster_config.py
2016-09-08 17:15:20.044 [IPClusterStart] Looking for ipcluster_config in /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/wxs/wxs/work
2016-09-08 17:15:20.046 [IPClusterStart] Config changed:
2016-09-08 17:15:20.046 [IPClusterStart] {'BcbioTORQUEEngineSetLauncher': {'mem': '6.00', 'tag': 'wxg', 'cores': 1, 'numengines': 4, 'resources': ''}, 'IPClusterEngines': {'early_shutdown': 240}, 'Application': {'log_level': 10}, 'ProfileDir': {'location': u'/cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/CLL/epigenomic/wxs/wxs/work/log/ipython'}, 'BaseParallelApplication': {'log_to_file': True, 'cluster_id': u'7e6ab525-1755-45f2-ab4f-910ebc7aa8ff'}, 'TORQUELauncher': {'queue': 'batch'}, 'BcbioTORQUEControllerLauncher': {'mem': '', 'tag': 'wxg', 'cores': 1, 'resources': ''}, 'IPClusterStart': {'controller_launcher_class': u'cluster_helper.cluster.BcbioTORQUEControllerLauncher', 'engine_launcher_class': u'cluster_helper.cluster.BcbioTORQUEEngineSetLauncher', 'n': 16, 'delay': 10, 'daemonize': True}}
64 Engines running
[2016-09-08T21:16Z] mskcc-ln1.local: Timing: alignment post-processing
Exception MemoryError: MemoryError() in  ignored
Exception MemoryError: MemoryError() in  ignored
Exception MemoryError: MemoryError() in  ignored
Exception MemoryError: MemoryError() in  ignored
Exception MemoryError: MemoryError() in  ignored
Exception MemoryError: MemoryError() in  ignored
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
    fc_dir, run_info_yaml)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 58, in parallel_split_combine
    split_outfile_i)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 128, in _get_split_tasks
    split_args.append([utils.deepish_copy(data)] + list(parts))
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 457, in deepish_copy
    out[k] = deepish_copy(v)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 457, in deepish_copy
    out[k] = deepish_copy(v)
  File "/cbio/cslab/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 460, in deepish_copy
    out[k] = v.copy()   # dicts, sets
MemoryError

**Comment by chapmanb** [comment]
Sorry about the issue -- this looks like a memory issue with the main bcbio_nextgen.py process, not the actual IPython processing runs. The main process needs to have sufficient memory to manage distributing tasks over the cluster, and it looks like it runs out when preparing a parallel step. My suggestion would be to run the main process on the cluster with a top level submission script and ensure that it is on a machine with additional memory. Hopefully this will resolve the problem.

**Comment by apastore** [comment]
Thanks a lot! I am rerunning everything from inside a qsub session. I will let you know If it solve!
Alessandro

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
