### ISSUE TITLE
Support for fastq.bz2 input files seems broken

### ISSUE THREAD

**Issue by pfpjs** [chapmanb/bcbio-nextgen#1554]
Hi,

I recently got a bunch of sequencing results in fastq.bz2 format and bcbio seems to think they are in text format and tries to gzip them, with pbgzip failing:

```
[2016-09-13T11:06Z] Timing: alignment preparation
[2016-09-13T11:06Z] multiprocessing: prep_align_inputs
[2016-09-13T11:06Z] bgzip input file
[2016-09-13T11:06Z] Error: remaining bytes (1024 = 65536 - 64512) in consumer_deflate_block_gz
[2016-09-13T11:06Z] This can happen when the input does not compress enough (a known bug).
[2016-09-13T11:06Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail;  /home/paulosilva/bcbio/galaxy/../anaconda/bin/pbgzip -n 31  -c /path/to/input/28115_1.fastq.bz2 > /path/to/workdir/work/align_prep/tx/tmpMQxFgo/28115_1.fastq.bz2.gz
Error: remaining bytes (1024 = 65536 - 64512) in consumer_deflate_block_gz
This can happen when the input does not compress enough (a known bug).
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/paulosilva/bcbio-tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/paulosilva/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 123, in variant2pipeline
    samples = run_parallel("prep_align_inputs", samples)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 104, in prep_align_inputs
    return alignprep.create_inputs(*args)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 44, in create_inputs
    data["files"] = _prep_grabix_indexes(data["files"], data["dirs"], data)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 269, in _prep_grabix_indexes
    out = [_bgzip_from_fastq(d) for d in inputs]
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 497, in _bgzip_from_fastq
    needs_bgzip, needs_gunzip, needs_convert)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 523, in _bgzip_file
    "bgzip input file")
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/paulosilva/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail;  /home/paulosilva/bcbio/galaxy/../anaconda/bin/pbgzip -n 31  -c /path/to/input/28115_1.fastq.bz2 > /path/to/workdir/work/align_prep/tx/tmpMQxFgo/28115_1.fastq.bz2.gz
Error: remaining bytes (1024 = 65536 - 64512) in consumer_deflate_block_gz
This can happen when the input does not compress enough (a known bug).
' returned non-zero exit status 1
```
Besides the error with pbgzip (which I think is because the input file is compressed and the output is bigger than the input), bcbio should recognize the bz2 extension. I looked over a bit of bcbio code and there seems to be support for bzip2, but it's not being triggered for some reason.

I'm currently running the latest bcbio development version, updated as of yesterday.

Thanks for the continued awesome work!

**Comment by chapmanb** [comment]
Paolo;
Thanks for the suggestions and detailed report. I added support for bzip2 input fastqs to the latest development version so if you update this will hopefully work cleanly on a re-run by correctly running bunzip2 prior to bgzipping. Please let us know if you run into any other problems. Thanks again.

**Comment by pfpjs** [comment]
Thank you for the quick response and patch, I confirm it's working with fastq.bz2 input files. Thank you again!
