### ISSUE TITLE
svc issue

### ISSUE THREAD

**Issue by lsturm1** [chapmanb/bcbio-nextgen#1561]
Hi,

I am trying to use svc on a cohort of samples. When I run it I get the following error message... does this mean I need to update something or is there some other fix? Thank you

Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup\
_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 362, in detec\
t_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 144, in detect_sv
    for svdata in caller_fn(items):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 29, in run
    return _cnvkit_by_type(items, background)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 43, in _cnvkit_by_ty\
pe
    return _run_cnvkit_population(items, background)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 113, in _run_cnvkit_\
population
    out.extend(_associate_cnvkit_out(ckouts, [cur_input]))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 57, in _associate_cn\
vkit_out
    ckout = _add_variantcalls_to_output(ckout, data, is_somatic)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 404, in _add_variant\
calls_to_output
    effects_vcf, _ = effects.add_to_vcf(calls["vcf"], data, "snpeff")
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 30, in add_to_vcf
    ann_vrn_file, stats_file = snpeff_effects(in_file, data)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 216, in snpeff_effec\
ts
    return _run_snpeff(vcf_in, "vcf", data)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 304, in _run_snpeff
    do.run(cmd.format(**locals()), "snpEff effects", data)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/share/PI/euan/apps/bcbio/anaconda/bin:$PATH &&  /share/PI/euan/app\
s/bcbio/anaconda/bin/snpEff -Xms4g -Xmx10g -Djava.io.tmpdir=/local-scratch/lsturm/9838413/bcbiotx/79ba2811-1ba3-4039-9513-a54\
6d7ac9b5b/tmpHX7S0A/tmp eff -dataDir /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/snpeff -noHgvs -noLog -i vcf -o vcf -s\
 /scratch/PI/euan/projects/elite/bcbio/projects/project_n268_svc_v1/work/structural/01_02/cnvkit/raw/01_02-dedup-call-effects\
-stats.html GRCh37.75 /scratch/PI/euan/projects/elite/bcbio/projects/project_n268_svc_v1/work/structural/01_02/cnvkit/raw/01_\
02-dedup-call.vcf  > /local-scratch/lsturm/9838413/bcbiotx/79ba2811-1ba3-4039-9513-a546d7ac9b5b/tmpHX7S0A/01_02-dedup-call-ef\
fects.vcf
java.lang.RuntimeException: Database file '/share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/snpeff/GRCh37.75/snpEffectPredic\
tor.bin' is not compatible with this program version:
        Database version : '4.2'
        Program version  : '4.3'
Try installing the appropriate database.
        at org.snpeff.serializer.MarkerSerializer.load(MarkerSerializer.java:158)
        at org.snpeff.snpEffect.SnpEffectPredictor.load(SnpEffectPredictor.java:66)
        at org.snpeff.snpEffect.Config.loadSnpEffectPredictor(Config.java:555)
        at org.snpeff.SnpEff.loadDb(SnpEff.java:360)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:964)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:947)
        at org.snpeff.SnpEff.run(SnpEff.java:1009)
        at org.snpeff.SnpEff.main(SnpEff.java:155)
' returned non-zero exit status 255
[2016-09-16T20:38Z] sh-7-30.local: snpEff effects : 01_02
[2016-09-16T20:38Z] sh-7-30.local: java.lang.RuntimeException: Database file '/share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh\
37/snpeff/GRCh37.75/snpEffectPredictor.bin' is not compatible with this program version:
[2016-09-16T20:38Z] sh-7-30.local:      Database version : '4.2'
[2016-09-16T20:38Z] sh-7-30.local:      Program version  : '4.3'
[2016-09-16T20:38Z] sh-7-30.local: Try installing the appropriate database.
[2016-09-16T20:38Z] sh-7-30.local:      at org.snpeff.serializer.MarkerSerializer.load(MarkerSerializer.java:158)
[2016-09-16T20:38Z] sh-7-30.local:      at org.snpeff.snpEffect.SnpEffectPredictor.load(SnpEffectPredictor.java:66)
[2016-09-16T20:38Z] sh-7-30.local:      at org.snpeff.snpEffect.Config.loadSnpEffectPredictor(Config.java:555)
[2016-09-16T20:38Z] sh-7-30.local:      at org.snpeff.SnpEff.loadDb(SnpEff.java:360)
[2016-09-16T20:38Z] sh-7-30.local:      at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:964)
[2016-09-16T20:38Z] sh-7-30.local:      at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:947)
[2016-09-16T20:38Z] sh-7-30.local:      at org.snpeff.SnpEff.run(SnpEff.java:1009)
[2016-09-16T20:38Z] sh-7-30.local:      at org.snpeff.SnpEff.main(SnpEff.java:155)
[2016-09-16T20:38Z] sh-7-30.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/share/PI/euan/apps/bcbio/anaconda/bin:$PATH &&  /share/PI/euan/app\
s/bcbio/anaconda/bin/snpEff -Xms4g -Xmx10g -Djava.io.tmpdir=/local-scratch/lsturm/9838408/bcbiotx/3d0ab058-bceb-4b2c-8f2d-81d\
dc2622868/tmpAUqOOG/tmp eff -dataDir /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/snpeff -noHgvs -noLog -i vcf -o vcf -s\
 /scratch/PI/euan/projects/elite/bcbio/projects/project_n268_svc_v1/work/structural/01_02/cnvkit/raw/01_02-dedup-call-effects\
-stats.html GRCh37.75 /scratch/PI/euan/projects/elite/bcbio/projects/project_n268_svc_v1/work/structural/01_02/cnvkit/raw/01_\
02-dedup-call.vcf  > /local-scratch/lsturm/9838408/bcbiotx/3d0ab058-bceb-4b2c-8f2d-81ddc2622868/tmpAUqOOG/01_02-dedup-call-ef\
fects.vcf
java.lang.RuntimeException: Database file '/share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/snpeff/GRCh37.75/snpEffectPredic\
tor.bin' is not compatible with this program version:
        Database version : '4.2'
        Program version  : '4.3'
Try installing the appropriate database.
        at org.snpeff.serializer.MarkerSerializer.load(MarkerSerializer.java:158)
        at org.snpeff.snpEffect.SnpEffectPredictor.load(SnpEffectPredictor.java:66)
        at org.snpeff.snpEffect.Config.loadSnpEffectPredictor(Config.java:555)
        at org.snpeff.SnpEff.loadDb(SnpEff.java:360)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:964)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:947)
        at org.snpeff.SnpEff.run(SnpEff.java:1009)
        at org.snpeff.SnpEff.main(SnpEff.java:155)
' returned non-zero exit status 255

**Comment by chapmanb** [comment]
Thanks for the report, it looks like you updated snpEff to version 4.3 but not the databases. You can do this with:
```
bcbio_nextgen.py upgrade --data
```
Hope this helps, feel free to re-open this issue if you run into other problems.

**Comment by lsturm1** [comment]
Hi Brad, 

I successfully updated using bcbio_nextgen.py upgrade --data. However, after rerunning the test, I still get the same error. The update seemed to update a bunch of gemini_data, but I don't believe it updated bcbio/genomes/Hsapiens/GRCh37/snpeff/GRCh37.75/snpEffectPredictor.bin. How can I update the snpEff database? 

Thank you,
Luke

**Comment by chapmanb** [comment]
Luke;
Sorry about the issue, I'm not positive why it wouldn't upgrade snpEff as well. If you look at `/path/to/bcbio/manifest/python-packages.yaml` and search for `snpeff`, what version is listed? It should have been updated with 4.3 which is where the installers pulls from to know it needs an update. If this is an older installation I pushed a fix to avoid pulling old versions from `brew` installs which might also help. Hope one of these two ideas helps resolve the problem.

**Comment by lsturm1** [comment]
Hi,

I checked the python-packages.yaml and weirdly, there is no entry for snpeff listed at all. What should I do?

Luke

**Comment by chapmanb** [comment]
Luke;
That's strange it should get updated and reported there on any successful run of an install/upgrade, if you run:
```
bcbio_nextgen.py upgrade -u development --tools
```
does it finish cleanly and update the manifest file? Hopefully that fixes it and you can then run the data update command afterwards.

**Comment by lsturm1** [comment]
I wasn't able to do that update do to a previous issue. I somehow got into a state where conda wasn't in the right place. Specifically bcbio/anaconda/bin/conda doesn't exist. I tried to reinstall conda, but that path still doesn't exist. Any thoughts on how to fix that?

**Comment by chapmanb** [comment]
Luke;
You'll probably need to remove the broken anaconda directory (`rm -rf /path/to/bcbio/anaconda`) and re-run the installer to recreate conda and the installed packages:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

You should use the same tool and data directories as previously to avoid re-downloading the data. Hopefully this will get your installation working cleanly again.

**Comment by lsturm1** [comment]
Thank you! That worked!
