### ISSUE TITLE
sailfish treat input as fastq file while ReRun RNAseq analysis from bam file

### ISSUE THREAD

**Issue by csardas** [chapmanb/bcbio-nextgen#1562]
hi, 

I want to re-run RNAseq pipeline with different variant caller
I tried to use pre-mapping bam file as input and skip alignment step

and I got following error message:
-----------------------------------------------------------------------------------------------------
 [2016-09-19T08:16Z] multiprocessing: run_sailfish
Traceback (most recent call last):
  File "/peterhouse/tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/peterhouse/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 251, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 82, in quantitate_expression_parallel
    samples = run_parallel("run_sailfish", samples)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 48, in run_sailfish
    return sailfish.run_sailfish(*args)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", line 28, in run_sailfish
    out_file = sailfish(fq1, fq2, sailfish_dir, gtf_file, fasta_file, stranded, data)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", line 40, in sailfish
    kmer_size = int(fastq.estimate_read_length(fq1))
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/fastq.py", line 242, in estimate_read_length
    read = in_handle.next()
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 597, in parse
    for r in i:
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1031, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 920, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
ValueError: Sequence and quality captions differ.
--------------------------------------------------------------------------------------

seems sailfish treat input file as fastq format

I only want to try different variant caller here (from GATK to vardict)
is it possible to skip sailfish process during RNAseq analysis?

**Comment by mjafin** [comment]
+1, got this same exact error on Friday on `0.9.9`

**Comment by roryk** [comment]
Thanks everyone. I added a couple checks to skip steps using prealigned files during the RNA-seq pipeline which fixes this problem. In the future we'll replace Sailfish with Salmon and we can use pre-aligned files for that without converting to FASTQ.

**Comment by mjafin** [comment]
Cheers Rory, look forward to the testing Salmon

**Comment by mjafin** [comment]
Rory, following these I get a further error downstream:
```
[2016-09-20T11:41Z] QC: 243_351 qualimap_rnaseq
Traceback (most recent call last):
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/bin/bcbio_nextgen.py", line 230, in <module>
    main(**kwargs)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line
43, in run_main
    fc_dir, run_info_yaml)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line
87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line
268, in rnaseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py",
line 27, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", l
ine 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", l
ine 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804,
 in __call__
    while self.dispatch_one_batch(iterator):
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662,
 in dispatch_one_batch
    self._dispatch(tasks)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570,
 in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183,
 in __init__
    self.results = batch()
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 136, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 56, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, data)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 115, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 281, in run_rnaseq
    metrics.update(_detect_rRNA(data))
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 222, in _detect_rRNA
    count_table = pd.read_csv(tidy_file, sep="\t")
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 315, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 645, in __init__
    self._make_engine(self.engine)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 799, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 1213, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 358, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3427)
  File "pandas/parser.pyx", line 645, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:7038)
IOError: Expected file path name or file-like object, got <type 'NoneType'> type
```
The BAM files are the disambiguated mm10 bams (i.e. kind of leftovers)

**Comment by roryk** [comment]
Thanks Miika,

In our tests, we skip running the rRNA calculation for other reasons, so I didn't catch this error. I added a check to skip if Sailfish wasn't run.

**Comment by amizeranschi** [comment]
Hello,

I am getting the same error as the thread opener, using the latest development version of Bcbio. I used BAM files as input (created previously from Bcbio, using star as an aligner) for an RNA-seq protocol, using the following template:

details:
  - analysis: RNA-seq
    description: 'RNA-seq_BY-4742'
    metadata:
        batch:
        panel:
    genome_build: sacCer3_RNA
    resources:
        default:
            memory: 5G
            cores: 8
    jvm_opts: ["-Xms8000m", "-Xmx10000m"]
    algorithm:
        mark_duplicates: false
        variant_regions: ../config/variant_regions.bed
        variantcaller: gatk-haplotype
        quality_format: Standard
        strandedness: firststrand


I am getting the following error:

**[2017-07-20T11:40Z] multiprocessing: run_salmon_index**
[2017-07-20T11:40Z] Extracting genomic sequences of /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/genomes/Scerevisiae/sacCer3_RNA/rnaseq/ref-transcripts.gtf.
[2017-07-20T11:40Z] Reading the annotation file: /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/genomes/Scerevisiae/sacCer3_RNA/rnaseq/ref-transcripts.gtf
Traceback (most recent call last):
  File "/storage/brno3-cerit/home/amizeranschi/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/storage/brno3-cerit/home/amizeranschi/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 255, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 112, in quantitate_expression_parallel
    samples = run_parallel("run_salmon_index", [samples])
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 57, in run_salmon_index
    return salmon.run_salmon_index(*args)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 121, in run_salmon_index
    salmon_index(gtf_file, fasta_file, data, salmon_dir)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 140, in salmon_index
    readlength = bam.fastq.estimate_read_length(files[0])
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/fastq.py", line 250, in estimate_read_length
    read = in_handle.next()
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1031, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 920, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
**ValueError: Sequence and quality captions differ.**
