### ISSUE TITLE
Bcbio unable to find GATK

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1574]
Hi Brad,

Bcbio is not able to detect GATK although I have installed the most recent version using the recommended method via the gatk bioconda wrapper. This is a new issue I met ever since installing the newest version of the bcbio pipeline. Hoping for your assistance!

Traceback:
[2016-09-27T02:26Z] Recalibrating 6217_N with GATK
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script

  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 135, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 76, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 199, in postprocess_alignment
    data = _recal_no_markduplicates(data)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 205, in _recal_no_markduplicates
    data = recalibrate.prep_recal(data)[0][0]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 42, in prep_recal
    broad_runner = broad.runner_from_config(config)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 430, in runner_from_config
    config_utils.get_program(program, config, "dir"),
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 188, in get_program
    return _get_program_dir(name, pconfig)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 240, in _get_program_dir
    raise ValueError("Could not find directory in config for %s" % name)
ValueError: Could not find directory in config for gatk

This is the output for installing GATK - looks fine
[dlho@n067 work]$ gatk-register ~/software/gatk-3.6/GenomeAnalysisTK-3.6.tar.bz2
ENV_PREFIX /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda
Processing GenomeAnalysisTK-3.6.tar.bz2 as *.tar.bz2
Extracting GenomeAnalysisTK-3.6.tar.bz2
GenomeAnalysisTK.jar
resources/exampleFASTA.dict
resources/exampleFASTA.fasta
resources/exampleBAM.bam
resources/exampleBAM.bam.bai
resources/exampleFASTA.fasta.fai
Picked up _JAVA_OPTIONS: -XX:+UseSerialGC
jar file specified matches expected version
Moving GenomeAnalysisTK-3.6.tar.bz2 to /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/opt/gatk-3.6

**Comment by chapmanb** [comment]
Sorry about the issue with GATK. Could you try updating to the latest development version?
```
bcbio_nextgen.py upgrade -u development
```
This has a few fixes for GATK detection which I hope will resolve your problem. We hope to have a new release soon with these updates. Hope this gets it working for you.

**Comment by phu5ion** [comment]
Yes it's working, thanks!
