### ISSUE TITLE
archive_to_cram std::bad_alloc

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1578]
Hi,

I'm using the `archive: cram` option in the pipeline and getting the following error when trying to do the bam to cram compression. Am I running out of memory or something else is happening?

<pre>
[2016-09-25T04:22Z] node002: Timing: archive
[2016-09-25T04:22Z] node002: ipython: archive_to_cram
[2016-09-25T04:22Z] node020: Compress BAM to CRAM
[2016-09-25T04:22Z] node003: Compress BAM to CRAM
[2016-09-25T09:42Z] node020: terminate called after throwing an instance of 'std::bad_alloc'
[2016-09-25T09:42Z] node020:   what():  std::bad_alloc
[2016-09-25T09:52Z] node003: terminate called after throwing an instance of 'std::bad_alloc'
[2016-09-25T09:52Z] node003:   what():  std::bad_alloc
[2016-09-25T09:52Z] node020: [main_samview] truncated file.
[2016-09-25T09:52Z] node020: Uncaught exception occurred
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /pico/home/userexternal/esebesty/work/bcbio/data/anaconda/bin/bam squeeze --in /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch2659/work
/bamprep/LUAD_2659_10A_NB/LUAD_2659_10A_NB-sort-prep.bam --out -.ubam --keepDups --readName --binQualS=2,10,20,25,30,35,70 --binMid | /pico/home/userexternal/esebesty/work/bcbio/data/anacond
a/bin/samtools view -T /pico/work/ELIX_prj6/esebesty/bcbio/data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -@ 20 -C -x BD -x BI -o /pico/home/userexternal/esebesty/scratch/tmp/bcbiotx/0313ff2f-4f
cb-4be3-ad79-cb4ad8612172/tmpFnOYl4/LUAD_2659_10A_NB-sort-prep.cram
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[main_samview] truncated file.
' returned non-zero exit status 1
[2016-09-25T09:52Z] node020: Unexpected error
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 420, in archive_to_cram
    return ipython.zip_args(apply(archive.to_cram, *args))
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/archive.py", line 12, in to_cram
    cram_file = cram.compress(data["work_bam"], data)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/bam/cram.py", line 33, in compress
    do.run(cmd.format(**locals()), "Compress BAM to CRAM")
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /pico/home/userexternal/esebesty/work/bcbio/data/anaconda/bin/bam squeeze --in /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch2659/work/bamprep/LUAD_2659_10A_NB/LUAD_2659_10A_NB-sort-prep.bam --out -.ubam --keepDups --readName --binQualS=2,10,20,25,30,35,70 --binMid | /pico/home/userexternal/esebesty/work/bcbio/data/anaconda/bin/samtools view -T /pico/work/ELIX_prj6/esebesty/bcbio/data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -@ 20 -C -x BD -x BI -o /pico/home/userexternal/esebesty/scratch/tmp/bcbiotx/0313ff2f-4fcb-4be3-ad79-cb4ad8612172/tmpFnOYl4/LUAD_2659_10A_NB-sort-prep.cram
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[main_samview] truncated file.
' returned non-zero exit status 1

</pre>

**Comment by chapmanb** [comment]
Endre;
Sorry about the issues, it looks like either bamUtil or samtools is somehow unhappy with your input BAM. Could you try running:
```
samtools view -T /pico/work/ELIX_prj6/esebesty/bcbio/data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -@ 20 -C -x BD -x BI -o LUAD_2659_10A_NB-sort-prep.cram /userexternal/esebesty/bcbio_run/uuid_batch2659/work/bamprep/LUAD_2659_10A_NB/LUAD_2659_10A_NB-sort-prep.bam
```
to see if that work cleanly? That might help us distinguish if bamUtil or samtools is failing. If the former, then we could have a backup option here to skip the quality binning and name removal in the case of failures. Thanks for the help debugging.

**Comment by razZ0r** [comment]
samtools converts it just fine, no error there. I had to start it with `-@ 1` however, as there aren't many free nodes at the moment.

**Comment by chapmanb** [comment]
Endre -- thanks for following up. I pushed a fix which will retry cram compression only without quality binning if the initial attempt fails. This should hopefully catch your problem case and proceed cleanly. Hopefully this will work until we get quality binning implemented directly in samtools. Hope this gets everything working cleanly for you.
