### ISSUE TITLE
Error compiling/installing bcbio on RHEL 5.4 using Python 2.7.9

### ISSUE THREAD

**Issue by Amjadhpc** [chapmanb/bcbio-nextgen#1594]
Hello,
I am trying to install bcbio  on RHEL 5.4 using python  2.7.9. I am using the automated installer  

The command i execute is as follows:
python bcbio_nextgen_install.py /usr/local/data --tooldir=/usr/local/data --genomes GRCh37 --aligners bwa --aligners bowtie2 
 from pysam.cutils import *

etching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /work/alturkisa/bcbbio/data/anaconda:
#
bcbio-nextgen             0.9.9                    py27_0    bioconda

The error i get  is

ImportError: /usr/local/data/anaconda/lib/python2.7/site-packages/pysam/cutils.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

Any reason why this error and how to solve it ?

**Comment by chapmanb** [comment]
Sorry about the issue. It looks like you have bcbio installed at `/work/alturkisa/bcbbio/data/anaconda`, is that right? If so, it appears as if incompatible libraries from `/usr/local/data/anaconda/lib` get pulled in to your environment. This may be due to `LD_LIBRARY_PATH` so cleaning that up to avoid injecting these libraries will hopefully help. If you have python modules like pysam loaded on the system (assuming you're using modules) that's a good place to start debugging. Hope this helps.

**Comment by Amjadhpc** [comment]
yes bcbio in installed in /work/alturkisa/bcbbio/data/anaconda.
I have cleaned up all LD_LIBRARY_PATH
When it tries to download pysam using the script it gives following error. 

Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /work/alturkisa/bcbbio/data/anaconda:

The following NEW packages will be INSTALLED:

    bcbio-nextgen: 0.9.9-py27_0   bioconda
    pybedtools:    0.7.8-py27_1   bioconda
    pysam:         0.9.1.4-py27_0 bioconda
    seqcluster:    1.2.3-py27_0   bioconda

Installing data and third party dependencies
Traceback (most recent call last):
  File "/work/alturkisa/bcbbio/data/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 33, in <module>
    from bcbio import install, utils, workflow
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 24, in <module>
    from bcbio import broad, utils
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 16, in <module>
    from bcbio.broad import picardrun
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/picardrun.py", line 6, in <module>
    import pysam
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 6, in <module>
    from pysam.cutils import *
IFetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /work/alturkisa/bcbbio/data/anaconda:

The following NEW packages will be INSTALLED:

    bcbio-nextgen: 0.9.9-py27_0   bioconda
    pybedtools:    0.7.8-py27_1   bioconda
    pysam:         0.9.1.4-py27_0 bioconda
    seqcluster:    1.2.3-py27_0   bioconda

Installing data and third party dependencies
Traceback (most recent call last):
  File "/work/alturkisa/bcbbio/data/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 33, in <module>
    from bcbio import install, utils, workflow
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 24, in <module>
    from bcbio import broad, utils
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 16, in <module>
    from bcbio.broad import picardrun
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/broad/picardrun.py", line 6, in <module>
    import pysam
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 6, in <module>
    from pysam.cutils import *
**ImportError: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/pysam/cutils.so)**

GLIBC 2.5 is available on RHEL 5.4 . Updating to GLIBC 2.7  means updating the os t o RHEL 6.x. ?
Is there anyway that this script will work with old versions of pysam(RHEL 5.x) instead of taking the latest version of pysam?

**Comment by chapmanb** [comment]
Apologies, unfortunately the upstream package management we use for bcbio no longer supports CentOS/RedHat 5 and packages are now compiled on CentOS 6. Both bioconda and conda, which we use for building packages, are transitioning in this direction to avoid issues they were running into with compiling on these older systems. The argument is that CentOS 5 is 10 years old and support expires next year so most sytems have upgraded.

Sorry to not have a solution with bcbio for CentOS/RedHat 5. If upgrading is an option happy to help with any issues on a newer OS.

**Comment by Amjadhpc** [comment]
Thank you Brad.

I got the packages recompiled  from source on RHEL 5.x and copied  the binaries and libraries to bcbio environment. I have passed the rna sequencing test  w. 

However when i run all test by issuing ./runtest.sh , i get 2 errors as follows:

 File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 434, in _check_algor ithm_keys
    **% (problem_keys, ALG_DOC_URL))
ValueError: Unexpected configuration keyword in 'algorithm' section: ['save_diskspace']
See configuration documentation for supported options:
https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#algorithm-parameters**

ERROR
Create a project template from input files and metadata configuration. ... Traceback (most recent call last):
  File "/work/alturkisa/bcbbio/data/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py" , line 744, in run_script

  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py" , line 1499, in run_script

  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextg en.py", line 220, in <module>
    setup_info = workflow.setup(kwargs["workflow"], kwargs.pop("inputs"))
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/workflow/__init__.py", line 12, in setup
    return workflow.setup(args)
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/workflow/template.py", line 423, in setup
    template, template_txt = name_to_config(args.template)
  File "/work/alturkisa/bcbbio/data/anaconda/lib/python2.7/site-packages/bcbio/workflow/template.py", line 148, in name_to_conf ig
    % template)
**ValueError: Could not find template 'freebayes-variant' locally or in standard templates on GitHub
ERROR**

I did check freebayes-variant  on github and did not find it there. IS there something i am missing here.

**Comment by chapmanb** [comment]
Glad to hear you were able to get things running on CentOS 5. Thanks for the patience working through that.

Your first error is due to running a release version, as the `save_diskspace` option is new in the development. You could upgrade to the latest development (`bcbio_nextgen.py upgrade -u development`) to fix the issue or not worry about it until we have another release, which will hopefully be soon.

The second error looks like you might not have internet access (or it failed during the test) for retrieving the template from GitHub:

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/templates/freebayes-variant.yaml

If you don't need this functionality you can again disregard the error. Hope this helps.

**Comment by Amjadhpc** [comment]
Thank you for  reply.
Yes i have updated the  bcbio_nextgen.py  and fixed the internet issue.

Now all the tests have ran successfully.

Thank you for the help.
Closing the issue
