### ISSUE TITLE
ERROR: Allow BAM files as input to pipeline.

### ISSUE THREAD

**Issue by csardas** [chapmanb/bcbio-nextgen#1597]
I tried to run variant2 analysis from bam files and got an error like https://github.com/chapmanb/bcbio-nextgen/issues/1419

after I follow the command
bcbio_conda install pybedtools gemini metasv bcbio-nextgen -c bioconda
bcbio_conda install -f bedtools -c bioconda
bcbio_nextgen.py upgrade -u development --tools

there is another error like
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 76, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 186, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 37, in sample_callable_bed
    coverage_file, callable_bed, highdepth_bed, median_cov = coverage.calculate(bam_file, data)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 105, in calculate
    do.run(cmd, "Calculate coverage: %s" % dd.get_sample_name(data))
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

and after I run test script

======================================================================
ERROR: Allow BAM files as input to pipeline.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/peterhouse/lchen/csardas/test_suite/bcbio-nextgen/tests/test_automated_analysis.py", line 312, in test_5_bam
    subprocess.check_call(cl)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['bcbio_nextgen.py', '/peterhouse/lchen/csardas/test_suite/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', '/peterhouse/lchen/csardas/test_suite/bcbio-nextgen/tests/data/automated/run_info-bam.yaml']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 12 tests in 110.706s

FAILED (errors=2)

How can I fix this bug?

**Comment by chapmanb** [comment]
Sorry about the issue, it looks like your installation does not have `goleft` in the PATH, leading to the error. A couple of things to check:

- Is `/peterhouse/tools/bcbio/anaconda/bin/goleft` present? If not, then something was problematic about your install/upgrade and you might need to re-run. It should install this as part of `bcbio_nextgen.py upgrade`.
- If it is present, have you set your PATH to include the directory containing `bcbio_nextgen.py`? This is the bin directory in the path you specified as `--tooldir` during the initial install. You should be able to type `goleft` on the command line and find the executable.

Hope updating or fixing your path resolves the issue.

**Comment by csardas** [comment]
hi,

goleft is at the place
```
$ /peterhouse/tools/bcbio/anaconda/bin/goleft
goleft Version: 0.1.6
depth : parallelize calls to samtools in user-defined windows
```

and PATH setting is correct
```
$ which bcbio_nextgen.py
/peterhouse/tools/bin/bcbio_nextgen.py

$ which goleft
/peterhouse/tools/bin/goleft
```

**Comment by chapmanb** [comment]
Thanks for following up. It looks like everything is correct so I'm confused as to why it's not finding goleft on the PATH when running. There is nothing fancy going on inside bcbio here. Is it possible the environment you're running the tests is different than when you're checking it on the command line? Sorry to not have better ideas but hope retrying with the setup PATH as above will work.

**Comment by csardas** [comment]
My colleague was tried to upgrade system python from 2.6.6 to 2.7.3 last week and the work was not success. (well.....). Now I tried to restore original version by reinstall the rpm. (provided by CentOS 6.4)

bcbio process is now hanged on such point:
is it possible to fix? or any clue about which package/library may broken and I should take a look to restore original one
I did try re-install bcbio, that's not work.

```
  File "/peterhouse/tools/bin/bcbio_nextgen.py", line 230, in <module>
    main(**kwargs)
  File "/peterhouse/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 134, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 76, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 186, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 37, in sample_callable_bed
    coverage_file, callable_bed, highdepth_bed, median_cov = coverage.calculate(bam_file, data)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 105, in calculate
    do.run(cmd, "Calculate coverage: %s" % dd.get_sample_name(data))
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
    stderr=subprocess.STDOUT, close_fds=True)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by roryk** [comment]
Hi @csardas, 

bcbio should be totally independent of the system python, it uses its own version of python. This error looks like `goleft` didn't get installed with your installation, if you do a tools update it should fix this error.

**Comment by csardas** [comment]
hi, the problem is solved. Thanks for suggestions.

I made two mistakes on this issue.
I tested with an old test script that use older version database (https://github.com/chapmanb/bcbio-nextgen/commit/07f492cf149635dda755c655397de09fdba53903)
and some users do use different PATH setting
