### ISSUE TITLE
Reference data S3 source broken?

### ISSUE THREAD

**Issue by vinogradovs** [chapmanb/bcbio-nextgen#1605]
Fresh installation with genome data fails, but succedes without data installation, besides the same errors appear on running test examples:

[2016-10-22T20:01Z] Downloading hg19 samtools from AWS
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script

  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 120, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 300, in organize_samples
    return run_info.organize(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 66, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 158, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 207, in get_refs
    galaxy_config, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 159, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 280, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file hg19 samtools

**Comment by naumenko-sa** [comment]
Hello! 
Maybe try to install with 
--datatarget --genomes GRCh37
and use GRCh37 as reference?
SN

**Comment by vinogradovs** [comment]
Hi, 
I also tried GRCh37 with upgrade command and errors still also happen:
Running GGD recipe: srnaseq
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script

  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 344, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 473, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 812, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/home/adminlocal/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 4

**Comment by vinogradovs** [comment]
Hi, I localized the cause of issue,  removed -q from wget in /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh 
and got 
wget -N -c -O hsa.gff3 ftp://mirbase.org/pub/mirbase/20/genomes/hsa.gff3
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2016-10-23 15:04:40--  ftp://mirbase.org/pub/mirbase/20/genomes/hsa.gff3
           => ‘hsa.gff3’
Resolving mirbase.org (mirbase.org)... 130.88.90.12
Connecting to mirbase.org (mirbase.org)|130.88.90.12|:21... failed: Connection timed out.
Retrying.

--2016-10-23 15:06:49--  ftp://mirbase.org/pub/mirbase/20/genomes/hsa.gff3
  (try: 2) => ‘hsa.gff3’
Connecting to mirbase.org (mirbase.org)|130.88.90.12|:21... failed: Connection timed out.
Retrying.

--2016-10-23 15:08:58--  ftp://mirbase.org/pub/mirbase/20/genomes/hsa.gff3
  (try: 3) => ‘hsa.gff3’
Connecting to mirbase.org (mirbase.org)|130.88.90.12|:21... failed: Connection timed out.
Retrying.

--2016-10-23 15:11:08--  ftp://mirbase.org/pub/mirbase/20/genomes/hsa.gff3
  (try: 4) => ‘hsa.gff3’
Connecting to mirbase.org (mirbase.org)|130.88.90.12|:21... failed: Connection timed out.
Retrying.

So, is there fast fix for this?

**Comment by chapmanb** [comment]
Sorry about the issue. It looks like the mirbase.org server is down due to hardware issues:

https://twitter.com/mirbase/status/789406368901980165

I temporarily removed the small RNA data download from the recipes so if you don't need this workflow immediately, you can get the remaining data by removing the cached cloudbiolinux (`rm -rf tmpbcbio-install`) and re-running your upgrade command. Thanks much for the report and hope this gets your installation finished cleanly.
