### ISSUE TITLE
bcbio upgrade error

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1610]
Hi,
I found the following error during bcbio-nextgen upgrade. Can you help me to solve it?
Thanks.

Creating manifest of installed packages in ./bcbio/manifest
Third party tools upgrade complete.
Installing additional tools
Installing gatk
Upgrading bcbio-nextgen data files
Setting up virtual machine
[localhost] local: echo $HOME
[localhost] local: uname -m
Running GGD recipe: dbnsfp
Traceback (most recent call last):
  File "./bcbio/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 344, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 473, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 812, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "./bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', './bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 1

**Comment by pengxiao78** [comment]
Can anybody help me to solve the problem? Thanks!

**Comment by roryk** [comment]
Thanks, it looks like the dbnsfp recipe isn't working; sometimes external dependencies are down which causes errors like these. If you rerun it does it give the same error? If so is there more information in the error output anywhere?

**Comment by chapmanb** [comment]
Sorry about the issue. This is a problem with dbNSFP and I believe is the problem described here:

https://github.com/chapmanb/cloudbiolinux/issues/231#issuecomment-256566663

This is due to some fixes we tried to put in for the new version on hg19. I'm trying to fix that now and will report back as soon as we've resolved the issue.

**Comment by pengxiao78** [comment]
Hi Brad,
Should I get the older version dbNSFPv2.9.1 or wait for your fixing? If I need to get the older version dbNSFPv2.9.1, what are the specific steps to get the upgrade successful. 
Thanks!

**Comment by chapmanb** [comment]
Thanks for the patience and sorry again about the issue. I pushed a fix that I hope will resolve this. If you `rm -rf tmpbcbio-install` and re-run it should get the latest recipe and hopefully work cleanly for you.

**Comment by pengxiao78** [comment]
Brad,
I ran rm -rf tmpbcbio-install and the folder and files are removed but when I ran the upgrade command as follows, 

bcbio_nextgen.py upgrade -u stable --tools --data --datatarget gemini --datatarget cadd --datatarget vep --datatarget dbnsfp --datatarget battenberg --toolplus gatk=/user/GenomeAnalysisTK-3.6.tar/GenomeAnalysisTK.jar

I found the same error. Any suggestion?
Thanks.

Running GGD recipe: dbnsfp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   383    0   383    0     0     71      0 --:--:--  0:00:05 --:--:--  1040
100 12.4G    0 12.4G    0     0  31.6M      0 --:--:--  0:06:43 --:--:-- 50.0M
[E::hts_idx_push] unsorted positions
tbx_index_build failed: dbNSFP.txt.gz

**Comment by chapmanb** [comment]
Sorry about the issue, you probably need to remove the older problematic build from the temporary directory. You could do with: `rm /path/to/bcbio/genomes/Hsapiens/GRCh37/txtmp/variation/dbNSFP.txt.gz` which should allow it to be rebuilt with the new version. Hope this fixes it for you.
