### ISSUE TITLE
Cufflinks error

### ISSUE THREAD

**Issue by MBeyens** [chapmanb/bcbio-nextgen#1612]
Dear

I'm was running the RNAseq DE pipeline on some samples. After aligning with tophat, the cufflinks command gave next error:
`[2016-10-27T11:22Z] Assembling transcripts with Cufflinks using /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/align/CELL_R_DMSO/1_2016-10-11_CELL_SampleInfo-merged_tophat/CELL_R_DMSO.bam.
[2016-10-27T11:22Z] Assembling transcripts with Cufflinks using /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/align/CELL_R_EVER/2_2016-10-11_CELL_SampleInfo-merged_tophat/CELL_R_EVER.bam.
[2016-10-27T11:22Z] Assembling transcripts with Cufflinks using /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/align/CELL_S_DMSO/3_2016-10-11_CELL_SampleInfo-merged_tophat/CELL_S_DMSO.bam.
[2016-10-27T11:22Z] You are using Cufflinks v2.2.1, which is the most recent release.
[2016-10-27T11:22Z] You are using Cufflinks v2.2.1, which is the most recent release.
[2016-10-27T11:22Z] You are using Cufflinks v2.2.1, which is the most recent release.
[2016-10-27T11:22Z] Error: sort order of reads in BAMs must be the same
[2016-10-27T11:22Z] Error: sort order of reads in BAMs must be the same
[2016-10-27T11:22Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/myNAME/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/myNAME/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cufflinks --output-dir /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/assembly/tx/tmpMu06ph/CELL_R_DMSO --num-threads 16 --frag-bias-correct /mnt/home_nfs3/myNAME/local/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --library-type fr-firststrand --multi-read-correct --upper-quartile-norm /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/align/CELL_R_DMSO/1_2016-10-11_CELL_SampleInfo-merged_tophat/CELL_R_DMSO.bam
You are using Cufflinks v2.2.1, which is the most recent release.
Error: sort order of reads in BAMs must be the same
' returned non-zero exit status 1
[2016-10-27T11:22Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/myNAME/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/myNAME/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cufflinks --output-dir /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/assembly/tx/tmpj0FMtY/CELL_R_EVER --num-threads 16 --frag-bias-correct /mnt/home_nfs3/myNAME/local/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --library-type fr-firststrand --multi-read-correct --upper-quartile-norm /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/align/CELL_R_EVER/2_2016-10-11_CELL_SampleInfo-merged_tophat/CELL_R_EVER.bam
You are using Cufflinks v2.2.1, which is the most recent release.
Error: sort order of reads in BAMs must be the same
' returned non-zero exit status 1
[2016-10-27T11:22Z] Error: sort order of reads in BAMs must be the same
[2016-10-27T11:22Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/myNAME/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/myNAME/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cufflinks --output-dir /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/assembly/tx/tmpEWqxRC/CELL_S_DMSO --num-threads 16 --frag-bias-correct /mnt/home_nfs3/myNAME/local/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --library-type fr-firststrand --multi-read-correct --upper-quartile-norm /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/align/CELL_S_DMSO/3_2016-10-11_CELL_SampleInfo-merged_tophat/CELL_S_DMSO.bam
You are using Cufflinks v2.2.1, which is the most recent release.
Error: sort order of reads in BAMs must be the same
' returned non-zero exit status 1
[2016-10-27T11:22Z] Assembling transcripts with Cufflinks using /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/align/CELL_S_EVER/4_2016-10-11_CELL_SampleInfo-merged_tophat/CELL_S_EVER.bam.
[2016-10-27T11:22Z] You are using Cufflinks v2.2.1, which is the most recent release.
[2016-10-27T11:22Z] Error: sort order of reads in BAMs must be the same
[2016-10-27T11:22Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/myNAME/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/myNAME/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cufflinks --output-dir /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/assembly/tx/tmpoKZPpg/CELL_S_EVER --num-threads 16 --frag-bias-correct /mnt/home_nfs3/myNAME/local/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --library-type fr-firststrand --multi-read-correct --upper-quartile-norm /mnt/home_nfs3/myNAME/RNAseq/CELLdata/FastQs/CELL_SampleInfo-merged/config/align/CELL_S_EVER/4_2016-10-11_CELL_SampleInfo-merged_tophat/CELL_S_EVER.bam
You are using Cufflinks v2.2.1, which is the most recent release.
Error: sort order of reads in BAMs must be the same
' returned non-zero exit status 1`

What's going wrong here?

Thank you in advance.

**Comment by roryk** [comment]
Hi MBeyens,

Thanks-- it looks like this is a problem with transcriptome assembly with Cufflinks. Do you need to do assembly for your DE project? If not you can turn that off and it should work fine. In the meantime I'll see if I can reproduce.

For doing DE calls with hg38 you'll want to use an aligner that is aware of the alt alleles, hisat2 should work great. I'd also recommend when you do the downstream analysis to not use the count tables and instead use the sailfish quantitated counts instead.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
