### ISSUE TITLE
bcbio_prepare_samples.py from docker

### ISSUE THREAD

**Issue by silvanopiazza** [chapmanb/bcbio-nextgen#1625]
Problem: can not use bcbio_prepare_samples.py from docker

Hi to all. 
I use BCBIO from docker official container.
I notice that in the guide there was not suggesttion to create the soft link to bcbio_prepare_samples.py, so I did. 
_ln -s ~/install/bcbio-vm/anaconda/bin/bcbio_prepare_samples.py /usr/local/bin/ bcbio_prepare_samples.py

But if I call the script It was not able to find the config file., so I create a copy of it.

_docker run bcbio/bcbio cat  /usr/local/share/bcbio-nextgen/config/bcbio_system.yaml > /media/silvano/Disk1/install/bcbio-vm/galaxy/bcbio_system.yaml_

then again if I try to launch the script I encounter a parse error, even if I use the csv structure from the guide.

_$bcbio_prepare_samples.py --out merged --csv batch1.csv
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_prepare_samples.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.0a0', 'bcbio_prepare_samples.py')
  File "/local-storage/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/local-storage/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/media/silvano/Disk1/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0a0-py2.7.egg-info/scripts/bcbio_prepare_samples.py", line 131, in <module>
    samples = _get_samples_to_process(args.csv, out_dir, config)
  File "/media/silvano/Disk1/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0a0-py2.7.egg-info/scripts/bcbio_prepare_samples.py", line 48, in _get_samples_to_process
    raise ValueError("Line needs 2 values: file and name.")
**ValueError: Line needs 2 values: file and name._**

and
cat batch1.csv
/media/silvano/Disk1/data/batch_001/data/1PR20-M_S26_L001_R2_001.fastq.gz,ERR256785,batch1,normal,male,/media/silvano/Disk1/install/bcbio-vm/data/bed/MODY_6_FINAL_1_Regions_Export_cleanfile.bed
/media/silvano/Disk1/data/batch_001/data/1PR20-M_S26_L001_R1_001.fastq.gz,ERR256786,batch1,normal,male,/media/silvano/Disk1/install/bcbio-vm/data/bed/MODY_6_FINAL_1_Regions_Export_cleanfile.bed

any ideas?

thank for any help
Silvano

**Comment by chapmanb** [comment]
Silvano;
Sorry about the issue. This looks like the script might be complaining about an empty line in your input CSV file. The snippet you posted looks fine so I'd guess there are also some blank lines in there causing it to complain. If you remove those it should hopefully work correctly. I also pushed a fix to check for empty lines and fix this in the future. Hopefully it resolves the problem for you and gets things running cleanly.
