### ISSUE TITLE
cannot upgrade bcbio --genomes mm10

### ISSUE THREAD

**Issue by firatuyulur** [chapmanb/bcbio-nextgen#1645]
Hi,
I was trying to get mm10 reference genome to my bcbio using,
```bcbio_nextgen.py upgrade --genomes mm10```
It worked perfectly until the point ```Running GGD recipe: srnaseq```. Here is the error I get.
```
Running GGD recipe: srnaseq
Traceback (most recent call last):
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 344, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 473, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 812, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/genomes/Mmusculus/mm10/txtmp/ggd-run.sh']' returned non-zero exit status 8
```

As I read in another issue, you were recommending
```bash /mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/genomes/Mmusculus/mm10/txtmp/ggd-run.sh``` and I did it too. It works without an error. I also did ```bcbio_nextgen.py upgrade -u stable --tools --data``` just to be updated but still had the same error. 

What would you recommend?
Thanks already

**Comment by lpantano** [comment]
Hi,

sorry about this. I saw this when I was getting some problems with one of the place it downloads the data. 

do you need the small RNAseq data?

I am trying to reproduce the error as well.

I will let you know what I can find.

**Comment by firatuyulur** [comment]
Hi again,
I will use it for ChIPseq, if that helps.
Thanks a lot

**Comment by lpantano** [comment]
HI,

if you will only use chipseq maybe you can remove —data option since you don’t need any associated file for that just the indexes. 

I will continue trying to debug this.

cheers

**Comment by firatuyulur** [comment]
Hi again,
I tried mm9 with ``` bcbio_nextgen.py upgrade --genomes mm9``` and it is successfully upgraded. Right after that, I tried mm10 again but got the same errors. Any suggestion would be helpful.
Thanks

**Comment by lpantano** [comment]
Hi,

I could reproduce so I am trying to fix it for today.

sorry about the issue.

**Comment by lpantano** [comment]
Hi, can you remove any temporal folder created during the update and try again, I just push a new version of the annotation that should work.

Let me know.

**Comment by firatuyulur** [comment]
Hi again,
It worked successfully with your update. Thank you so much
Cheers
