### ISSUE TITLE
chip-seq pipeline error: No script named 'macs2'

### ISSUE THREAD

**Issue by atbest** [chapmanb/bcbio-nextgen#1646]
I installed stable bcbio-nextgen according the documentations and started chip-seq pipeline with the following config file:
```
details:
- algorithm:
    adapters:
    - truseq
    aligner: bowtie2
    peakcaller:
    - macs2
    trim_reads: read_through
  analysis: chip-seq
  description: H3K27Ac-ctr-A
  files:
  - /mnt/data/raw/H3K27Ac-ctr-A.fastq.gz
  genome_build: GRCz10
  metadata:
    batch: your-batch-name
    phenotype: chip
  resources:
    macs2:
      options:
      - --broad
      - -q 0.05
- algorithm:
    adapters:
    - truseq
    aligner: bowtie2
    peakcaller:
    - macs2
    trim_reads: read_through
  analysis: chip-seq 
  description: H3K27Ac-ctr-B
  files:
  - /mnt/data/raw/H3K27Ac-ctr-B.fastq.gz
  genome_build: GRCz10
  metadata:
    batch: your-batch-name
    phenotype: chip
  resources:
    macs2:
      options:
      - --broad
      - -q 0.05
- algorithm:
    adapters:
    - truseq
    aligner: bowtie2
    peakcaller:
    - macs2
    trim_reads: read_through
  analysis: chip-seq
  description: H3K27Ac-treated-A
  files:
  - /mnt/data/raw/H3K27Ac-treated-A.fastq.gz
  genome_build: GRCz10
  metadata:
    batch: your-batch-name
    phenotype: chip
  resources:
    macs2:
      options:
      - --broad
      - -q 0.05
- algorithm:
    adapters:
    - truseq
    aligner: bowtie2
    peakcaller:
    - macs2
    trim_reads: read_through
  analysis: chip-seq
  description: H3K27Ac-treated-B
  files:
  - /mnt/data/raw/H3K27Ac-treated-B.fastq.gz
  genome_build: GRCz10
  metadata:
    batch: your-batch-name
    phenotype: chip
  resources:
    macs2:
      options:
      - --broad
      - -q 0.05
fc_date: '2016-11-14'
fc_name: samples
upload:
  dir: ../final 
```

Everything worked well until `run local -- checkpoint passed: peakcalling`. The pipeline could not  go through peak calling process. Below is the debug information.

```
[2016-11-15T07:44Z] [bam_sort_core] merging from 4 files...
[2016-11-15T07:46Z] Index BAM file: H3K27Ac-treated-B-sort.bam
[2016-11-15T07:46Z] Timing: disambiguation
[2016-11-15T07:46Z] multiprocessing: clean_chipseq_alignment
[2016-11-15T07:46Z] Removing multimapped reads from /mnt/data/bcbio/samples/work/align/H3K27Ac-ctr-A/H3K27Ac-ctr-A-sort.bam.
[2016-11-15T07:49Z] Index BAM file: H3K27Ac-ctr-A-sort.unique.bam
[2016-11-15T07:49Z] Removing multimapped reads from /mnt/data/bcbio/samples/work/align/H3K27Ac-ctr-B/H3K27Ac-ctr-B-sort.bam.
[2016-11-15T07:53Z] Index BAM file: H3K27Ac-ctr-B-sort.unique.bam
[2016-11-15T07:53Z] Removing multimapped reads from /mnt/data/bcbio/samples/work/align/H3K27Ac-treated-A/H3K27Ac-treated-A-sort.bam.
[2016-11-15T07:56Z] Index BAM file: H3K27Ac-treated-A-sort.unique.bam
[2016-11-15T07:57Z] Removing multimapped reads from /mnt/data/bcbio/samples/work/align/H3K27Ac-treated-B/H3K27Ac-treated-B-sort.bam.
[2016-11-15T07:59Z] Index BAM file: H3K27Ac-treated-B-sort.unique.bam
[2016-11-15T07:59Z] Resource requests: macs2; memory: 8.00; cores: 1
[2016-11-15T07:59Z] Configuring 3 jobs to run, using 1 cores each with 8.00g of memory reserved for each job
[2016-11-15T07:59Z] run local -- checkpoint passed: peakcalling
[2016-11-15T07:59Z] Timing: peakcalling
[2016-11-15T07:59Z] Skipping peak calling. No input sample for H3K27Ac-ctr-A
[2016-11-15T07:59Z] Skipping peak calling. No input sample for H3K27Ac-ctr-B
[2016-11-15T07:59Z] Skipping peak calling. No input sample for H3K27Ac-treated-A
[2016-11-15T07:59Z] Skipping peak calling. No input sample for H3K27Ac-treated-B
[2016-11-15T07:59Z] Resource requests: fastqc, picard; memory: 3.00, 3.00; cores: 16, 16
[2016-11-15T07:59Z] Configuring 1 jobs to run, using 6 cores each with 18.1g of memory reserved for each job
[2016-11-15T07:59Z] Timing: quality control
[2016-11-15T07:59Z] multiprocessing: pipeline_summary
[2016-11-15T07:59Z] QC: H3K27Ac-ctr-A fastqc
[2016-11-15T07:59Z] Downsample BAM file: H3K27Ac-ctr-A-sort.bam
[2016-11-15T08:00Z] FastQC: H3K27Ac-ctr-A
[2016-11-15T08:00Z] Started analysis of H3K27Ac-ctr-A-sort-downsample.bam 
```

Next, I upgraded bcbio to development branch with `bcbio_nextgen.py upgrade -u development` and used the output bam files in `samples/final` folder to run bcbio_nextgen.py with the following config file:

```
details:
- algorithm:
    peakcaller:
    - macs2
  analysis: chip-seq
  description: H3K27Ac-ctr-A
  files:
  - /mnt/data/bcbio/bam/H3K27Ac-ctr-A-ready.bam
  genome_build: GRCz10
  metadata:
    batch: your-batch-name
    phenotype: chip
  resources:
    macs2:
      options:
      - --broad
      - -q 0.05
      - -g '1371719383'
- algorithm:
    peakcaller:
    - macs2
  analysis: chip-seq
  description: H3K27Ac-ctr-B
  files:
  - /mnt/data/bcbio/bam/H3K27Ac-ctr-B-ready.bam
  genome_build: GRCz10
  metadata:
    batch: your-batch-name
    phenotype: chip
  resources:
    macs2:
      options:
      - --broad
      - -q 0.05
      - -g '1371719383'
- algorithm:
    peakcaller:
    - macs2
  analysis: chip-seq
  description: H3K27Ac-treated-A
  files:
  - /mnt/data/bcbio/bam/H3K27Ac-treated-A-ready.bam
  genome_build: GRCz10
  metadata:
    batch: your-batch-name
    phenotype: chip
  resources:
    macs2:
      options:
      - --broad
      - -q 0.05
      - -g '1371719383'
- algorithm:
    peakcaller:
    - macs2
  analysis: chip-seq
  description: H3K27Ac-treated-B
  files:
  - /mnt/data/bcbio/bam/H3K27Ac-treated-B-ready.bam
  genome_build: GRCz10
  metadata:
    batch: your-batch-name
    phenotype: chip
  resources:
    macs2:
      options:
      - --broad
      - -q 0.05
      - -g '1371719383'
fc_date: '2016-11-15'
fc_name: samples
upload:
  dir: ../final 
```
Now I got the following error `pkg_resources.ResolutionError: No script named 'macs2'`. It looks like anaconda cannot load macs2 correctly.

```
[2016-11-15T22:35Z] run local -- checkpoint passed: peakcalling
[2016-11-15T22:35Z] Timing: peakcalling
[2016-11-15T22:35Z] multiprocessing: peakcalling
[2016-11-15T22:35Z] macs2 for H3K27Ac-ctr-A
[2016-11-15T22:35Z] Traceback (most recent call last):
[2016-11-15T22:35Z]   File "/opt/bin/galaxy/../anaconda/bin/macs2", line 4, in <module>
[2016-11-15T22:35Z]     __import__('pkg_resources').run_script('MACS2==2.1.1.20160309', 'macs2')
[2016-11-15T22:35Z]   File "/opt/bin/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
[2016-11-15T22:35Z]   File "/opt/bin/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1476, in run_script
[2016-11-15T22:35Z] pkg_resources.ResolutionError: No script named 'macs2'
[2016-11-15T22:35Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/opt/bin/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/opt/bin/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /opt/bin/galaxy/../anaconda/bin/macs2 callpeak -t /mnt/data/bcbio/samples/work/prealign/H3K27Ac-ctr-A/H3K27Ac-ctr-A-ready-dedup.bam -c None  -n H3K27Ac-ctr-A -B --broad -q 0.05 -g '1371719383'
Traceback (most recent call last):
  File "/opt/bin/galaxy/../anaconda/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.1.20160309', 'macs2')
  File "/opt/bin/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/opt/bin/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1476, in run_script
pkg_resources.ResolutionError: No script named 'macs2'
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. It looks like something is wrong with your macs2 installation on this system. I'm not sure exactly what is going on but it might be worth trying to uninstall and re-install macs2:
```
bcbio_pip uninstall macs2
bcbio_conda uninstall macs2
bcbio_conda install -c bioconda macs2
```
Then hopefully running `macs2` from the commandline will work cleanly and a restart of the pipeline in place will work. Hope this helps resolve the issue.

**Comment by lpantano** [comment]
Hi,

sorry about the issue. 

As well, for the first error you need to define your input. So I think that for H3K27Ac-ctr-A you should have phenotype: input if you want to use this as input. As well, batch should be A or B for the two groups.

For now we only support macs2 when using controls.

Let me know if that helps to get peak calling working.

cheers

**Comment by atbest** [comment]
Hi, Thanks for your help. I reinstalled macs2 and now it works well. But for the sample batch, I don't think it is a good idea to assign ctr-A to treated-A and ctr-B to treated-B, because they are biological duplicates. There's no direct correlation among them.

**Comment by lpantano** [comment]
Hi,

Can you explain me the experimental design? Normally we use macs with two samples, one input and un chip. Otherwise it will not run because chipseq analysis without input to control for background noise will generate mainly false positive.

Cheers

sent not from my computer

**Comment by lpantano** [comment]
Hi @atbest 

I will close this guessing it worked at the end. Let us know if you find more issues.
