### ISSUE TITLE
CNVkit error - invalid value encountered in median

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1647]
Hi Brad,

I met a problem with running CNVkit using the bcbio pipeline. Looks to me like it's due to one of the helper scripts. Would you mind taking a look at it please? Thank you!

[2016-11-15T16:24Z] /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:3569: RuntimeWarning: Invalid value encountered in median
[2016-11-15T16:24Z]   RuntimeWarning)
[2016-11-15T16:24Z] Segmented on allele freqs in 1:20502212-20880734
[2016-11-15T16:24Z] Segmented on allele freqs in 1:152101138-152329094
[2016-11-15T16:24Z] Segmented on allele freqs in 6:31948398-32053950
[2016-11-15T16:24Z] Segmented on allele freqs in 9:14748-21165524
[2016-11-15T16:24Z] Segmented on allele freqs in 9:33817744-34723732
[2016-11-15T16:24Z] Segmented on allele freqs in 9:71079943-84527890
[2016-11-15T16:24Z] Segmented on allele freqs in 11:65265219-65293234
[2016-11-15T16:24Z] Segmented on allele freqs in 12:9590547-9728325
[2016-11-15T16:24Z] Segmented on allele freqs in 12:52947518-133841395
[2016-11-15T16:24Z] Segmented on allele freqs in 16:2147288-2165682
[2016-11-15T16:24Z] Segmented on allele freqs in 19:11594210-11915395
[2016-11-15T16:24Z] Segmented on allele freqs in 19:19716614-24631282
[2016-11-15T16:24Z] Traceback (most recent call last):
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/cnvkit.py", line 13, in <module>
[2016-11-15T16:24Z]     args.func(args)
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 726, in _cmd_segment
[2016-11-15T16:24Z]     processes=args.processes)
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 34, in do_segmentation
[2016-11-15T16:24Z]     save_dataframe, rlibpath)
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 130, in _do_segmentation
[2016-11-15T16:24Z]     transfer_fields(segarr, cnarr)
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 179, in transfer_fields
[2016-11-15T16:24Z]     segweights[i] = subprobes['weight'].sum()
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/gary.py", line 130, in __getitem__
[2016-11-15T16:24Z]     return self.data[index]
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
[2016-11-15T16:24Z]     return self._getitem_column(key)
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
[2016-11-15T16:24Z]     return self._get_item_cache(key)
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
[2016-11-15T16:24Z]     values = self._data.get(item)
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 3290, in get
[2016-11-15T16:24Z]     loc = self.items.get_loc(item)
[2016-11-15T16:24Z]   File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/indexes/base.py", line 1947, in get_loc
[2016-11-15T16:24Z]     return self._engine.get_loc(self._maybe_cast_indexer(key))
[2016-11-15T16:24Z]   File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
[2016-11-15T16:24Z]   File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
[2016-11-15T16:24Z]   File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
[2016-11-15T16:24Z]   File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
[2016-11-15T16:24Z] KeyError: 'weight'
[2016-11-15T16:24Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin:$PATH && /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/cnvkit.py segment -o /mnt/projects/dlho/tancrc/Plasma_exome/analysis/work/structural/T180_baseline/cnvkit/raw/tx/tmp6P3yTH/T180_baseline-sort.cns /mnt/projects/dlho/tancrc/Plasma_exome/analysis/work/structural/T180_baseline/cnvkit/raw/T180_baseline-sort.cnr -v /mnt/projects/dlho/tancrc/Plasma_exome/analysis/work/freebayes/T0-vepeffects-annotated-filter.vcf.gz
Loaded 69466 records; skipped: 1170 somatic, 0 depth
Selected test sample T180_baseline and control sample N180_WBC
Dropped 33 outlier bins:
   chromosome      start        end                      gene     log2  depth  \
0           1   47799580   47799822                     CMPK1 -23.4239    0.0
1           1   94374574   94374776                      GCLM -23.3657    0.0
2           2   88926422   88926637                   EIF2AK3 -23.5664    0.0
3           2   99439265   99439513                 KIAA1211L -23.3389    0.0
4           2  174828462  174828664                       SP3 -23.5508    0.0
5           2  220313475  220313739                      SPEG -23.1710    0.0
6           2  239229242  239229455                  TRAF3IP1 -23.3195    0.0
7           3    9439106    9439397           SETD5,SETD5-AS1 -23.0782    0.0
8           3   50313698   50313931                    SEMA3B -23.3550    0.0
9           3  195163447  195163649                     ACAP2 -23.5964    0.0
10          7   73498296   73498432                     LIMK1 -23.4877    0.0
11         11   67071067   67071189                      SSH3 -23.3575    0.0
12         12    9067292    9067423                      PHC1 -23.3060    0.0
13         13   37393394   37393639                     RFXAP -23.4086    0.0
14         15   38856749   38856871                   RASGRP1 -23.6216    0.0
15         16     718319     718441                     RHOT2 -23.5570    0.0
16         16     730482     730694                     STUB1 -23.4402    0.0
17         16   15005072   15005174  MIR3180-1,hsa-mir-3180-3 -23.7579    0.0
18         16   89642270   89642512                     CPNE7 -23.3488    0.0
19         16   89989786   89989928                     TUBB3 -23.3175    0.0

      weight
0   0.157922
1   0.163452
2   0.287465
3   0.144785
4   0.276951
5   0.145293
6   0.131580
7   0.124337
8   0.155783
9   0.290737
10  0.187469
11  0.122643
12  0.082347
13  0.257050
14  0.271211
15  0.272108
16  0.213426
17  0.318241
18  0.136248
19  0.101492
...
/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:3569: RuntimeWarning: Invalid value encountered in median
  RuntimeWarning)
Segmented on allele freqs in 1:20502212-20880734
Segmented on allele freqs in 1:152101138-152329094
Segmented on allele freqs in 6:31948398-32053950
Segmented on allele freqs in 9:14748-21165524
Segmented on allele freqs in 9:33817744-34723732
Segmented on allele freqs in 9:71079943-84527890
Segmented on allele freqs in 11:65265219-65293234
Segmented on allele freqs in 12:9590547-9728325
Segmented on allele freqs in 12:52947518-133841395
Segmented on allele freqs in 16:2147288-2165682
Segmented on allele freqs in 19:11594210-11915395
Segmented on allele freqs in 19:19716614-24631282
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 726, in _cmd_segment
    processes=args.processes)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 34, in do_segmentation
    save_dataframe, rlibpath)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 130, in _do_segmentation
    transfer_fields(segarr, cnarr)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 179, in transfer_fields
    segweights[i] = subprobes['weight'].sum()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/gary.py", line 130, in __getitem__
    return self.data[index]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'weight'
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 230, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 176, in variant2pipeline
    samples = structural.run(samples, run_parallel, "initial")
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 146, in run
    for xs in to_process.values()))
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 228, in detect_sv
    return structural.detect_sv(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 165, in detect_sv
    for svdata in caller_fn(items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 29, in run
    return _cnvkit_by_type(items, background)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 41, in _cnvkit_by_type
    return _run_cnvkit_cancer(items, background)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 85, in _run_cnvkit_cancer
    ckouts = _run_cnvkit_shared([paired.tumor_data], normal_data)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 167, in _run_cnvkit_shared
    inputs[0]["config"], parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 63, in wrapper
    out = f(*args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 201, in _cnvkit_segment
    do.run(export_cmd + " ".join(cmd), "CNVkit segment")
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin:$PATH && /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/cnvkit.py segment -o /mnt/projects/dlho/tancrc/Plasma_exome/analysis/work/structural/T180_baseline/cnvkit/raw/tx/tmp6P3yTH/T180_baseline-sort.cns /mnt/projects/dlho/tancrc/Plasma_exome/analysis/work/structural/T180_baseline/cnvkit/raw/T180_baseline-sort.cnr -v /mnt/projects/dlho/tancrc/Plasma_exome/analysis/work/freebayes/T0-vepeffects-annotated-filter.vcf.gz
Loaded 69466 records; skipped: 1170 somatic, 0 depth
Selected test sample T180_baseline and control sample N180_WBC
Dropped 33 outlier bins:
   chromosome      start        end                      gene     log2  depth  \
0           1   47799580   47799822                     CMPK1 -23.4239    0.0
1           1   94374574   94374776                      GCLM -23.3657    0.0
2           2   88926422   88926637                   EIF2AK3 -23.5664    0.0
3           2   99439265   99439513                 KIAA1211L -23.3389    0.0
4           2  174828462  174828664                       SP3 -23.5508    0.0
5           2  220313475  220313739                      SPEG -23.1710    0.0
6           2  239229242  239229455                  TRAF3IP1 -23.3195    0.0
7           3    9439106    9439397           SETD5,SETD5-AS1 -23.0782    0.0
8           3   50313698   50313931                    SEMA3B -23.3550    0.0
9           3  195163447  195163649                     ACAP2 -23.5964    0.0
10          7   73498296   73498432                     LIMK1 -23.4877    0.0
11         11   67071067   67071189                      SSH3 -23.3575    0.0
12         12    9067292    9067423                      PHC1 -23.3060    0.0
13         13   37393394   37393639                     RFXAP -23.4086    0.0
14         15   38856749   38856871                   RASGRP1 -23.6216    0.0
15         16     718319     718441                     RHOT2 -23.5570    0.0
16         16     730482     730694                     STUB1 -23.4402    0.0
17         16   15005072   15005174  MIR3180-1,hsa-mir-3180-3 -23.7579    0.0
18         16   89642270   89642512                     CPNE7 -23.3488    0.0
19         16   89989786   89989928                     TUBB3 -23.3175    0.0

      weight
0   0.157922
1   0.163452
2   0.287465
3   0.144785
4   0.276951
5   0.145293
6   0.131580
7   0.124337
8   0.155783
9   0.290737
10  0.187469
11  0.122643
12  0.082347
13  0.257050
14  0.271211
15  0.272108
16  0.213426
17  0.318241
18  0.136248
19  0.101492
...
/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:3569: RuntimeWarning: Invalid value encountered in median
  RuntimeWarning)
Segmented on allele freqs in 1:20502212-20880734
Segmented on allele freqs in 1:152101138-152329094
Segmented on allele freqs in 6:31948398-32053950
Segmented on allele freqs in 9:14748-21165524
Segmented on allele freqs in 9:33817744-34723732
Segmented on allele freqs in 9:71079943-84527890
Segmented on allele freqs in 11:65265219-65293234
Segmented on allele freqs in 12:9590547-9728325
Segmented on allele freqs in 12:52947518-133841395
Segmented on allele freqs in 16:2147288-2165682
Segmented on allele freqs in 19:11594210-11915395
Segmented on allele freqs in 19:19716614-24631282
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 726, in _cmd_segment
    processes=args.processes)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 34, in do_segmentation
    save_dataframe, rlibpath)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 130, in _do_segmentation
    transfer_fields(segarr, cnarr)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 179, in transfer_fields
    segweights[i] = subprobes['weight'].sum()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/cnvlib/gary.py", line 130, in __getitem__
    return self.data[index]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'weight'
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. This looks like the same problem as #1590 and I believe @etal pushed a fix in CNVkit 0.8.1. Could you try updating to ensure you have the latest?
```
bcbio_conda install -c bioconda cnvkit
```
and see if that resolves the problem? Thanks for helping debug and hope this gets your analysis completed.

**Comment by phu5ion** [comment]
Thanks a lot, Brad! Seems to be resolved!
