### ISSUE TITLE
plink_to_vcf key error 2/2

### ISSUE THREAD

**Issue by naymikm** [chapmanb/bcbio-nextgen#1661]
I am getting a key error when running plink_to_vcf:

Traceback (most recent call last):
  File "/home/mnaymik/TOOLS/plink_to_vcf.py", line 161, in <module>
    main(*sys.argv[1:])
  File "/home/mnaymik/TOOLS/plink_to_vcf.py", line 32, in main
    fix_nonref_positions(vcf_file, ref_file)
  File "/home/mnaymik/TOOLS/plink_to_vcf.py", line 151, in fix_nonref_positions
    parts = fix_vcf_line(parts, ref_base)
  File "/home/mnaymik/TOOLS/plink_to_vcf.py", line 98, in fix_vcf_line
    genotypes = [swap[x] for x in genotypes]
KeyError: '2/2'

I see that 2/2 is not part of the swap dictionary which is an easy fix, what would be the correct value for the 2/2 key in the swap dictionary?

**Comment by lpantano** [comment]
Hi @naymikm 

We missed this. Is this still a problem? Is related to some bcbio pipeline? 

please, re-open the issue if you still have issues.

thanks
