### ISSUE TITLE
dbNSFP GGD recipe fails on build (hg38)

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1692]
Hi Brad,

I'm trying to install the latest dev version and I get the following error on build:
```
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'rtg'], 'genomes': [{'annotations': ['dbnsfp', 'coverage', 'prioritize', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'qsignature', 'genesplicer', 'effects_transcripts'], 'validation': ['giab-NA12878', 'platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap', 'dream-syn3-crossmap'], 'name': 'Human (hg38) full', 'dbkey': 'hg38'}], 'install_uniref': False}'): Human (hg38) full
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'rtg'], 'genomes': [{'annotations': ['dbnsfp', 'coverage', 'prioritize', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'qsignature', 'genesplicer', 'effects_transcripts'], 'validation': ['giab-NA12878', 'platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap', 'dream-syn3-crossmap'], 'name': 'Human (hg38) full', 'dbkey': 'hg38'}], 'install_uniref': False}'): Human (hg38) full
Running GGD recipe: dbnsfp
Traceback (most recent call last):
  File "./anaconda/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 291, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 339, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 468, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 807, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/home/galaxy/bcbio-dev/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/home/galaxy/bcbio-dev/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 1
```

Upgrade cmd:
`bcbio_nextgen.py upgrade -u development --datatarget vep --datatarget dbnsfp `

Any ideas?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the report. I ran a hg38 dbNSFP upgrade with the new recipes and it worked cleanly for me, so it appears as if the recipe itself is correct. Is it possible you ran into an intermittent issue due to network connectivity, or ran out of disk space during the preparation? Unfortunately the traceback doesn't have an informative error about the problem but hopefully a re-run will download and prepare this correctly. Hope this helps.

**Comment by matthdsm** [comment]
Hi Brad, 
Already several re-run laters, still no succes. I've made some small modifications to my environment and am currently giving it another go. I'll get back to you if I know more

M

**Comment by matthdsm** [comment]
Hi Brad, 
Another try, another failure. I tried running the specified bash script manually, and that just seems to fail without any output. I'm going to edit the generated script to see where it goes wrong.
M

**Comment by matthdsm** [comment]
found the issue!
fixed in chapmanb/cloudbiolinux#239

Apparently there's an issue with the CA certificates, which made curl fail, which in turn made the script exit due to the pipefail.

Should work cleanly now!
M

**Comment by chapmanb** [comment]
Thanks for the debugging and fixing the issue. Much appreciated.

**Comment by matthdsm** [comment]
No problem! Starting the tests immediatly!
