### ISSUE TITLE
CNVkit problem

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1696]
Hi Brad,

Ever since I upgraded CNVkit to the latest (0.8.2), I have been having problems running it. Would appreciate if you could take a look at the traceback!
[2016-12-16T08:33Z] Wrote /media/storage3/hodl/Projects/2016_breast_cancer/cnvkit/batch1_cnvkit/work/structural/BC031-13112014_T/cnvkit/raw/tx/tmpJqq5tW/77_gene_panel_GrCh37-merged-annotated.target.bed with 1764 regions
[2016-12-16T08:33Z] CNVkit antitarget
[2016-12-16T08:33Z] Detected file format: bed
[2016-12-16T08:33Z] Detected file format: bed
[2016-12-16T08:33Z]  1:27023394-27023531 : Subtracting 4 excluded regions
[2016-12-16T08:33Z]  1:27106013-27106747 : Subtracting 7 excluded regions
[2016-12-16T08:33Z]  1:114225333-114226136 : Subtracting 7 excluded regions
[2016-12-16T08:33Z]  3:142169807-142171575 : Subtracting 10 excluded regions
[2016-12-16T08:33Z]  5:56177896-56178193 : Subtracting 5 excluded regions
[2016-12-16T08:33Z]  5:112173749-112179323 : Subtracting 25 excluded regions
[2016-12-16T08:33Z]  7:116339624-116339838 : Subtracting 5 excluded regions
[2016-12-16T08:33Z]  7:140419633-140425816 : Subtracting 27 excluded regions
[2016-12-16T08:33Z]  7:151845617-151845737 : Subtracting 4 excluded regions
[2016-12-16T08:33Z]  7:151859701-151860411 : Subtracting 6 excluded regions
[2016-12-16T08:33Z]  7:151873775-151874595 : Subtracting 7 excluded regions
[2016-12-16T08:33Z]  7:151878295-151879179 : Subtracting 7 excluded regions
[2016-12-16T08:33Z]  9:133759855-133760570 : Subtracting 6 excluded regions
[2016-12-16T08:33Z]  9:139391022-139391510 : Subtracting 6 excluded regions
[2016-12-16T08:33Z]  13:32906908-32907024 : Subtracting 4 excluded regions
[2016-12-16T08:33Z]  13:32910901-32914833 : Subtracting 18 excluded regions
[2016-12-16T08:33Z]  17:41243951-41246377 : Subtracting 13 excluded regions
[2016-12-16T08:33Z]  17:56435328-56435684 : Subtracting 5 excluded regions
[2016-12-16T08:33Z]  19:1224136-1225945 : Subtracting 11 excluded regions
[2016-12-16T08:33Z]  19:2228235-2229291 : Subtracting 8 excluded regions
[2016-12-16T08:33Z]  20:57428535-57429888 : Subtracting 9 excluded regions
[2016-12-16T08:33Z]  22:29445684-29446436 : Subtracting 7 excluded regions
[2016-12-16T08:33Z] Traceback (most recent call last):
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
[2016-12-16T08:33Z]     args.func(args)
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 465, in _cmd_antitarget
[2016-12-16T08:33Z]     out_arr = do_antitarget(targets, access, args.avg_size, args.min_size)
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 479, in do_antitarget
[2016-12-16T08:33Z]     min_bin_size)
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/antitarget.py", line 56, in get_background
[2016-12-16T08:33Z]     .subdivide(avg_bin_size, min_bin_size))
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/gary.py", line 577, in subdivide
[2016-12-16T08:33Z]     verbose))
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/subdivide.py", line 22, in subdivide
[2016-12-16T08:33Z]     columns=table.columns)
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 939, in from_records
[2016-12-16T08:33Z]     first_row = next(data)
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/subdivide.py", line 43, in _split_targets
[2016-12-16T08:33Z]     for row in merge(regions).itertuples(index=False):
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/merge.py", line 107, in merge
[2016-12-16T08:33Z]     return out.reindex(out.chromosome.apply(sorter_chrom)
[2016-12-16T08:33Z]   File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 2672, in __getattr__
[2016-12-16T08:33Z]     return object.__getattribute__(self, name)
[2016-12-16T08:33Z] AttributeError: 'DataFrame' object has no attribute 'chromosome'
[2016-12-16T08:33Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command '/home/hodl/local/share/bcbio/anaconda/bin/cnvkit.py antitarget -g /media/storage3/hodl/Projects/2016_breast_cancer/cnvkit/batch1_cnvkit/work/structural/BC031-13112014_T/cnvkit/77_gene_panel_GrCh37-merged.bed /media/storage3/hodl/Projects/2016_breast_cancer/cnvkit/batch1_cnvkit/work/structural/BC031-13112014_T/cnvkit/raw/77_gene_panel_GrCh37-merged-annotated.target.bed -o /media/storage3/hodl/Projects/2016_breast_cancer/cnvkit/batch1_cnvkit/work/structural/BC031-13112014_T/cnvkit/raw/tx/tmp2RwXaT/77_gene_panel_GrCh37-merged-annotated.antitarget.bed
Detected file format: bed
Detected file format: bed
 1:27023394-27023531 : Subtracting 4 excluded regions
 1:27106013-27106747 : Subtracting 7 excluded regions
 1:114225333-114226136 : Subtracting 7 excluded regions
 3:142169807-142171575 : Subtracting 10 excluded regions
 5:56177896-56178193 : Subtracting 5 excluded regions
 5:112173749-112179323 : Subtracting 25 excluded regions
 7:116339624-116339838 : Subtracting 5 excluded regions
 7:140419633-140425816 : Subtracting 27 excluded regions
 7:151845617-151845737 : Subtracting 4 excluded regions
 7:151859701-151860411 : Subtracting 6 excluded regions
 7:151873775-151874595 : Subtracting 7 excluded regions
 7:151878295-151879179 : Subtracting 7 excluded regions
 9:133759855-133760570 : Subtracting 6 excluded regions
 9:139391022-139391510 : Subtracting 6 excluded regions
 13:32906908-32907024 : Subtracting 4 excluded regions
 13:32910901-32914833 : Subtracting 18 excluded regions
 17:41243951-41246377 : Subtracting 13 excluded regions
 17:56435328-56435684 : Subtracting 5 excluded regions
 19:1224136-1225945 : Subtracting 11 excluded regions
 19:2228235-2229291 : Subtracting 8 excluded regions
 20:57428535-57429888 : Subtracting 9 excluded regions
 22:29445684-29446436 : Subtracting 7 excluded regions
Traceback (most recent call last):
  File "/home/hodl/local/share/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 465, in _cmd_antitarget
    out_arr = do_antitarget(targets, access, args.avg_size, args.min_size)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 479, in do_antitarget
    min_bin_size)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/antitarget.py", line 56, in get_background
    .subdivide(avg_bin_size, min_bin_size))
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/gary.py", line 577, in subdivide
    verbose))
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/subdivide.py", line 22, in subdivide
    columns=table.columns)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 939, in from_records
    first_row = next(data)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/subdivide.py", line 43, in _split_targets
    for row in merge(regions).itertuples(index=False):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/merge.py", line 107, in merge
    return out.reindex(out.chromosome.apply(sorter_chrom)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 2672, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'chromosome'
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/hodl/local/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script

  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 177, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 125, in run
    for xs in to_process.values()))
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 220, in detect_sv
    return structural.detect_sv(*args)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 144, in detect_sv
    for svdata in caller_fn(items):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 29, in run
    return _cnvkit_by_type(items, background)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 41, in _cnvkit_by_type
    return _run_cnvkit_cancer(items, background)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 93, in _run_cnvkit_cancer
    work_dir, background_name=paired.normal_name)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 146, in _run_cnvkit_shared
    target_bed, antitarget_bed = _cnvkit_targets(raw_target_bed, access_bed, cov_interval, raw_work_dir, data)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 293, in _cnvkit_targets
    do.run(cmd, "CNVkit antitarget")
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/home/hodl/local/share/bcbio/anaconda/bin/cnvkit.py antitarget -g /media/storage3/hodl/Projects/2016_breast_cancer/cnvkit/batch1_cnvkit/work/structural/BC031-13112014_T/cnvkit/77_gene_panel_GrCh37-merged.bed /media/storage3/hodl/Projects/2016_breast_cancer/cnvkit/batch1_cnvkit/work/structural/BC031-13112014_T/cnvkit/raw/77_gene_panel_GrCh37-merged-annotated.target.bed -o /media/storage3/hodl/Projects/2016_breast_cancer/cnvkit/batch1_cnvkit/work/structural/BC031-13112014_T/cnvkit/raw/tx/tmp2RwXaT/77_gene_panel_GrCh37-merged-annotated.antitarget.bed
Detected file format: bed
Detected file format: bed
 1:27023394-27023531 : Subtracting 4 excluded regions
 1:27106013-27106747 : Subtracting 7 excluded regions
 1:114225333-114226136 : Subtracting 7 excluded regions
 3:142169807-142171575 : Subtracting 10 excluded regions
 5:56177896-56178193 : Subtracting 5 excluded regions
 5:112173749-112179323 : Subtracting 25 excluded regions
 7:116339624-116339838 : Subtracting 5 excluded regions
 7:140419633-140425816 : Subtracting 27 excluded regions
 7:151845617-151845737 : Subtracting 4 excluded regions
 7:151859701-151860411 : Subtracting 6 excluded regions
 7:151873775-151874595 : Subtracting 7 excluded regions
 7:151878295-151879179 : Subtracting 7 excluded regions
 9:133759855-133760570 : Subtracting 6 excluded regions
 9:139391022-139391510 : Subtracting 6 excluded regions
 13:32906908-32907024 : Subtracting 4 excluded regions
 13:32910901-32914833 : Subtracting 18 excluded regions
 17:41243951-41246377 : Subtracting 13 excluded regions
 17:56435328-56435684 : Subtracting 5 excluded regions
 19:1224136-1225945 : Subtracting 11 excluded regions
 19:2228235-2229291 : Subtracting 8 excluded regions
 20:57428535-57429888 : Subtracting 9 excluded regions
 22:29445684-29446436 : Subtracting 7 excluded regions
Traceback (most recent call last):
  File "/home/hodl/local/share/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 465, in _cmd_antitarget
    out_arr = do_antitarget(targets, access, args.avg_size, args.min_size)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 479, in do_antitarget
    min_bin_size)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/antitarget.py", line 56, in get_background
    .subdivide(avg_bin_size, min_bin_size))
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/gary.py", line 577, in subdivide
    verbose))
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/subdivide.py", line 22, in subdivide
    columns=table.columns)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 939, in from_records
    first_row = next(data)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/subdivide.py", line 43, in _split_targets
    for row in merge(regions).itertuples(index=False):
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/merge.py", line 107, in merge
    return out.reindex(out.chromosome.apply(sorter_chrom)
  File "/home/hodl/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 2672, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'chromosome'
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry I'm not sure what is happening here and can't seem to replicate with a small test case. I'll work on replicating but also will call for help from @etal if this might be something obvious we missed needing to change for 0.8.2

**Comment by etal** [comment]
Sorry for the trouble. I haven't seen this either, but the pandas error message tends to happen when a slice of data is unexpectedly empty.

Is this a hybrid capture sequencing setup, or targeted amplicon capture? Are all of the targeted chromosomes/contigs in your reference genome and/or "access" BED file? Is there anything else unusual about your panel? Could you attach your target BED file or e-mail it to me so I can debug and test?

**Comment by phu5ion** [comment]
Hi Brad,

Thanks for taking the time to help me troubleshoot this issue.
It's a target capture for only a small number of genes that we are
interested in. The targeted contigs /should be/ all in the reference genome
(I can't think of why they're not). This problem doesn't affect all samples
since in the first few samples in the pipeline there wasn't any error
message.

Both 1) the original bed file that I use to specify target region; and 2)
the sorted bed file after bcbio's pipeline of sorting and reannotation, as
found in the cnvkit folder for the problematic sample, is as attached,
thanks!

**Comment by chapmanb** [comment]
Thanks for the help debugging. I don't believe you can attach files to GitHub e-mails, but if you post them as gists (https://gist.github.com/) Eric can hopefully grab them from there. Thanks again.

**Comment by phu5ion** [comment]
Hi Brad,

I posted the original bed file, it can be accessed at this link: https://gist.github.com/phu5ion/9f5571c14150da600100f63aec0c3c85

Thanks!

**Comment by chapmanb** [comment]
Thanks for the example file. I was also able to reproduce this on a WGS test run with 0.8.2 and here is a reproducible example:

https://s3.amazonaws.com/chapmanb/testcases/cnvkit_debug_antitarget.tar.gz

I haven't had time yet to dig further for a fix but thought it would be useful to post this directly in case bcbio is doing something unexpected in preparing the targets/antitargets that Eric might flag.

**Comment by etal** [comment]
Thanks, it looks like this is a slicing/iteration issue in CNVkit's deeper machinery. If I add 10kbp to the end coordinate of the last region in access.bed, the command succeeds and creates an antitarget.bed with 0 rows, which is expected for WGS. I can fix that bug in the next release, but bcbio can also just skip creating antitargets in WGS mode; an empty file is fine.

It also might be worthwhile to add a few bins' worth of padding to each "access" transcript region in WGS mode, leaving some room to detect segments that overlap the start or end of a gene.

**Comment by chapmanb** [comment]
Eric -- thanks so much for the fix. To get this working I pushed a new bioconda package with the development version of CNVkit, and will do more testing on my end. Hopefully an update with:
```
bcbio_conda -c bioconda cnvkit
```
will resolve the original issue as well. Please let us know if you run into anything else at all.
