### ISSUE TITLE
Malformed VarDict VCF file crashes GATK and pipeline

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1704]
GATK crashes with the following error:

<pre>
[2016-12-15T00:40Z] ##### ERROR stack trace
[2016-12-15T00:40Z] htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 54693: BUG: log10PError cannot be > 0 : 1.0, for input source: /pico/scra
tch/userexternal/esebesty/bcbio_run/uuid_batch5932/work/vardict/21/LUAD_5932-21_0_41399576.vcf.gz
[2016-12-15T00:40Z]     at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:779)
[2016-12-15T00:40Z]     at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:356)
[2016-12-15T00:40Z]     at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:279)
[2016-12-15T00:40Z]     at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:257)
[2016-12-15T00:40Z]     at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:60)
[2016-12-15T00:40Z]     at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:161)
[2016-12-15T00:40Z]     at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:194)
[2016-12-15T00:40Z]     at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:136)
[2016-12-15T00:40Z]     at org.broadinstitute.gatk.tools.CatVariants.execute(CatVariants.java:295)
[2016-12-15T00:40Z]     at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:255)
[2016-12-15T00:40Z]     at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:157)
[2016-12-15T00:40Z]     at org.broadinstitute.gatk.tools.CatVariants.main(CatVariants.java:312)
[2016-12-15T00:40Z] ##### ERROR ------------------------------------------------------------------------------------------
[2016-12-15T00:40Z] ##### ERROR A GATK RUNTIME ERROR has occurred (version 3.6-24-g59fd391):
[2016-12-15T00:40Z] ##### ERROR
[2016-12-15T00:40Z] ##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
[2016-12-15T00:40Z] ##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
[2016-12-15T00:40Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2016-12-15T00:40Z] ##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
[2016-12-15T00:40Z] ##### ERROR
[2016-12-15T00:40Z] ##### ERROR MESSAGE: The provided VCF file is malformed at approximately line number 54693: BUG: log10PError cannot be > 0 : 1.0, for input source: /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch5932/work/vardict/21/LUAD_5932-21_0_41399576.vcf.gz
[2016-12-15T00:40Z] ##### ERROR ------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio/tool/bin/bcbio_nextgen.py", line 230, in <module>
    main(**kwargs)
  File "/pico/home/userexternal/esebesty/work/bcbio/tool/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 150, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 178, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
    parallel_fn(combine_name, combine_args)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 810, in __call__
    self.retrieve()
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 757, in retrieve
    raise exception
joblib.my_exceptions.JoblibCalledProcessError: JoblibCalledProcessError
___________________________________________________________________________
</pre>

The offending line seems to be:

<pre>
21	39129455	.	AATCCAGCTTGGAGTGAGCACTCCCTCACAGTGTGATGGTACCAGCCTTGGTGAGCTGTCTCTCACAGT	C	-2	d5;v3;P0.9;REJECT;LowAlleleDepth;REJECT	STATUS=Germline;SAMPLE=LUAD_5932_01A_TP;TYPE=Complex;SHIFT3=0;MSI=1;MSILEN=1;SSF=1;SOR=0;LSEQ=GAGTGAGCACTCCCTCACAG;RSEQ=GTGATGATTCCAGCCTGGAG	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	1/1:2:2:1,1:0,0:0,2:1:0,2:45:1:32.5:1:1:0:13:4:1:1:2.5	1/1:2:2:1,1:0,0:0,2:1:0,2:42:1:-2.5:1:1:0:33:4:1:1:4
</pre>

**Comment by chapmanb** [comment]
Endre;
Thanks for the report and sorry about the issue. The best next step here would be to build a reproducible test case and fix upstream in VarDict. To confirm, are you running with the latest 1.4.8 version of vardict-java:
```
$ bcbio_conda list | grep vardict-java
vardict-java              1.4.8                         0    bioconda
```
If so, it is possible to share a slice of the BAM(s) in this region only so we can provide a reproducible output case for debugging? That should help us try and identify the underlying issue and get a fix in VarDict. Thanks much.

**Comment by razZ0r** [comment]
Seems like I'm using 1.4.6

<pre>
Using Anaconda API: https://api.anaconda.org
vardict-java              1.4.6                         0    bioconda
</pre>

I can update bcbio, rerun the sample and see if it fixes the problem.

**Comment by razZ0r** [comment]
I updated to vardict-java 1.4.8 from bioconda, but getting exactly the same error. Unfortunately, I can't share the data as it is a controlled access sample pair from TCGA. Any suggestions on what to do next?

**Comment by chapmanb** [comment]
Endre;
Thanks for following up. It seems like the best approach at this point is to remove these calls with QUAL < 0 to avoid the illegal VCF and downstream errors. I pushed a fix to do this in VarDict. For your sample you'll have to remove the existing problem VCF and re-run and things should hopefully work cleanly now. Thanks again for the work tracking down the issue.
