### ISSUE TITLE
small RNAseq: write_output

### ISSUE THREAD

**Issue by ramaniak** [chapmanb/bcbio-nextgen#1712]
Hello,

I am trying to run the smallRNA-seq pipeline and have created the attached yaml file for the sample and execute it as:

```
bcbio_nextgen.py ../config/bcbio.mirna.test.yaml 

```
It is running through the trimming step and throws the following errir

```
  File "/work/tools/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/work/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 311, in smallrnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 398, in rnaseq_prep_samples
    samples = run_parallel("trim_srna_sample", samples)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 76, in trim_srna_sample
    return srna.trim_srna_sample(*args)
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 64, in trim_srna_sample
    data["collapse"] = _collapse(data["clean_fastq"])
  File "/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 110, in _collapse
    write_output(out_file, seqs, minimum=1, size=16)
```
I am pretty sure I am doing something wrong, can't figure out what it is

[bcbio.mirna.test.yaml.gz](https://github.com/chapmanb/bcbio-nextgen/files/670144/bcbio.mirna.test.yaml.gz)

**Comment by lpantano** [comment]
Hi,

sorry about the issue. Can you send me the full bcbio-nextgen-debug.log file? I think I am missing the real error in this part of the text you pasted.

The config file seems ok.

cheers

**Comment by ramaniak** [comment]
Hello,
Thanks for your quick response. Here are the log files that were generated.

thanks
Arun
[bcbio-nextgen-commands.log.gz](https://github.com/chapmanb/bcbio-nextgen/files/671025/bcbio-nextgen-commands.log.gz)
[bcbio-nextgen-debug.log.gz](https://github.com/chapmanb/bcbio-nextgen/files/671024/bcbio-nextgen-debug.log.gz)
[bcbio-nextgen.log.gz](https://github.com/chapmanb/bcbio-nextgen/files/671026/bcbio-nextgen.log.gz)

**Comment by lpantano** [comment]
Hi,

the debug file should have the error but for some reason isn't there. Any chance you can retrieve the full error? It should be something else beside what you paste in your first email. Like containing the exact number line when the error occurs. Normally this is inside the debug file, but don't know why is missing here.

If you can not find it, try re-start and the error should appear again. Then send me every line that you get until the process stops.

thanks!

**Comment by ramaniak** [comment]
Here is the full stdout when re-running
```
[2016-12-23T15:36Z] System YAML configuration: /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/galaxy/bcbio_system.yaml
[2016-12-23T15:36Z] Created tmp dir /hpf/largeprojects/ccmbio/arun/DIPG/microRNA/work/bcbiotx/tmpfiUvAL 
[2016-12-23T15:36Z] Resource requests: cutadapt, picard; memory: 2.00, 3.50; cores: 16, 1
[2016-12-23T15:36Z] Configuring 1 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2016-12-23T15:36Z] Timing: organize samples
[2016-12-23T15:36Z] multiprocessing: organize_samples
[2016-12-23T15:36Z] Using input YAML configuration: /hpf/largeprojects/ccmbio/arun/DIPG/microRNA/config/bcbio.mirna.test.yaml
[2016-12-23T15:36Z] Checking sample YAML configuration: /hpf/largeprojects/ccmbio/arun/DIPG/microRNA/config/bcbio.mirna.test.yaml
[2016-12-23T15:36Z] Testing minimum versions of installed programs
[2016-12-23T15:36Z] multiprocessing: prepare_sample
[2016-12-23T15:36Z] Preparing DIPG100T
[2016-12-23T15:36Z] Timing: adapter trimming
[2016-12-23T15:36Z] multiprocessing: trim_srna_sample
Traceback (most recent call last):
  File "/home/naumenko/work/tools/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/home/naumenko/work/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 311, in smallrnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 398, in rnaseq_prep_samples
    samples = run_parallel("trim_srna_sample", samples)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 76, in trim_srna_sample
    return srna.trim_srna_sample(*args)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 64, in trim_srna_sample
    data["collapse"] = _collapse(data["clean_fastq"])
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 110, in _collapse
    write_output(out_file, seqs, minimum=1, size=16)
TypeError: write_output() got an unexpected keyword argument 'size'
```

**Comment by lpantano** [comment]
Nice, that helps.

Can you try to do `bcbio_nextgen.py update -u skip --tools` ? I think `seqcluster` is not uptodate.

You can use `development` or `stable` instead of `skip`, whatever suits you better.

As well you can update to last version doing `PATH_BCBIO_ANACONDA_IS/conda update seqcluster` 

let me know if that fixes the problem.

cheers

**Comment by ramaniak** [comment]
Great! will try that out and let you know.

Cheers
Arun

**Comment by ramaniak** [comment]
I am still getting the same error :(. Is the version below the most up-to-date version?

conda update seqcluster
Fetching package metadata .......
# All requested packages already installed.
# packages in environment at /home/naumenko/work/tools/bcbio/anaconda:
#
seqcluster                1.2.0                    py27_0    bioconda

**Comment by lpantano** [comment]
Nop, the last version should be: 1.2.4a:

```
 /groups/bcbio/bcbio/anaconda/bin/conda update seqcluster
Fetching package metadata .......
# All requested packages already installed.
# packages in environment at /groups/bcbio/bcbio/anaconda:
#
seqcluster                1.2.4a                   py27_0    bioconda
```

you can try maybe to remove and install again?

```
conda remove seqcluster -c bioconda
conda install seqcluster -c bioconda -f
```

**Comment by naumenko-sa** [comment]
Hi Lorena and Arun!

Lorena, the first command also removed bcbio-nextgen.
The seqcluster is updated to 1.2.4a
I also installed bcbio-nextgen again with conda.

Arun, try if this is now running.

Lorena, something is wrong with the update system of seqcluster. I'm updating almost every week
with --tools, and still had an old version.

Sergey

**Comment by ramaniak** [comment]
Hello Sergey,
that update seems to have fixed it and it is not proceeding beyond that step.

thanks
Arun

**Comment by lpantano** [comment]
nice, let me know if you find more issues. 

happy holidays
