### ISSUE TITLE
error upgrading hg19

### ISSUE THREAD

**Issue by firatuyulur** [chapmanb/bcbio-nextgen#1714]
Hi,
I am trying to upgrade my bcbio with using `bcbio_nextgen.py upgrade --genomes hg19`. here is the error I get;

`...
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /bundle/2.8/hg19 ... 
No such directory “bundle/2.8/hg19”.

gzip: stdin: unexpected end of file
Traceback (most recent call last):
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.0', 'bcbio_nextgen.py')
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 211, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 95, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 286, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 344, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 473, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 812, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/mnt/kufs/scratch/fiuyulur/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/mnt/kufs/scratch/fiuyulur/bcbio_ku/share/bcbio/genomes/Hsapiens/hg19/txtmp/ggd-run.sh']' returned non-zero exit status 1`

Have you ever come across with such error?
Many thanks

**Comment by chapmanb** [comment]
Sorry about the issue, the GATK FTP recently changed the directory structure causing this problem. It should be fixed in the latest CloudBioLinux install:

https://github.com/chapmanb/cloudbiolinux/commit/9f935cfb2aa352e398584ae1eef0c2e760f1efb8

I wonder if it's possible that you have an older cached version. Could you try removing the current cloudbiolinux download:
```
rm -rf /mnt/kufs/scratch/fiuyulur/tmpbcbio-install
```
and re-running the update command to see if that fixes the issue? If not, would you be able to post the full log from the command so we can identify what recipe it's failing in. Hope this helps.

**Comment by PatrickJReed** [comment]
Im getting a similar error when trying to install upgrade on a fresh amazon instance.

running  sudo bcbio_nextgen.py upgrade -u development finishes clean but..

running:
sudo bcbio_nextgen.py upgrade -u development --tools --data --datatarget gemini --datatarget cadd --datatarget vep --datatarget dbnsfp
Upgrading bcbio
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /usr/local/share/bcbio/anaconda:

...

Creating manifest of installed packages in /usr/local/share/bcbio/manifest
Third party tools upgrade complete.
Upgrading bcbio-nextgen data files
--2017-02-04 06:49:44--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2017-02-04 06:49:44--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5159928 (4.9M) [application/x-gzip]
Saving to: ‘STDOUT’

100%[===============================================================================================================>] 5,159,928   7.15MB/s   in 0.7s   

2017-02-04 06:49:45 (7.15 MB/s) - written to stdout [5159928/5159928]

mv: cannot stat ‘master’: No such file or directory
Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x7fa16bc8ecb0>
INFO: <cloudbio.flavor.Flavor instance at 0x7fa16bc8ecb0>
INFO: This is a ngs_pipeline_minimal flavor
INFO: This is a ngs_pipeline_minimal flavor
INFO: Distribution __auto__
INFO: Distribution __auto__
INFO: Get local environment
INFO: Get local environment
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
INFO: Ubuntu setup
INFO: Ubuntu setup
DBG [distribution.py]: Debian-shared setup
DBG [distribution.py]: Debian-shared setup
DBG [distribution.py]: Source=trusty
DBG [distribution.py]: Source=trusty
DBG [distribution.py]: NixPkgs: Ignored
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'rtg'], 'genomes': [{'annotations': ['dbnsfp', 'GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'transcripts', 'RADAR', 'mirbase'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4'], 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}], 'install_uniref': False}'): Human (GRCh37)
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'rtg'], 'genomes': [{'annotations': ['dbnsfp', 'GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'transcripts', 'RADAR', 'mirbase'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4'], 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}], 'install_uniref': False}'): Human (GRCh37)
Running GGD recipe: GRCh37 dbnsfp 3.3a
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   383    0   383    0     0   2750      0 --:--:-- --:--:-- --:--:--  2755
  0     0    0 13.2G    0     0   141M      0 --:--:--  0:01:36 --:--:--  157M
[tabix] the index file exists. Please use '-f' to overwrite.
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 95, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 290, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 339, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 467, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 814, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file, gid)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 31, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 63, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Patrick;
Apologies about the issue, this looks like a different problem during the dbNSFP recipe where there is a pre-existing tabix index file from a previous upgrade attempt for the prepared output file. I added a fix to automatically remake this instead of failing. If you remove the temporary cached set of ggd-recipes (`rm -rf tmpbcbio-install`) and re-run it should hopefully pick up where it left off and run cleanly now. Thanks much for the report.
