### ISSUE TITLE
"Running GGD recipe" failed 

### ISSUE THREAD

**Issue by MIAOKUI** [chapmanb/bcbio-nextgen#1716]
Hi Chapmanb, 

I try to install bcbio, I got the error when running, INFO: Connection to host appears to work!
INFO: Connection to host appears to work!

DBG [utils.py]: Expand paths
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bowtie2', 'bwa', 'novoalign', 'rtg'], 'genomes': [{'name': 'phiX174', 'dbkey': 'phix', 'annotations': []}, {'annotations': ['GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'transcripts', 'RADAR', 'mirbase'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4'], 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}, {'annotations': ['coverage', 'prioritize', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'qsignature', 'genesplicer', 'effects_transcripts', 'transcripts'], 'validation': ['giab-NA12878', 'platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap', 'dream-syn3-crossmap'], 'name': 'Human (hg38) full', 'dbkey': 'hg38'}, {'annotations': ['coverage', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'transcripts'], 'name': 'Human (hg38) without alternative alleles', 'dbkey': 'hg38-noalt'}], 'install_uniref': False}'): phiX174, Human (GRCh37), Human (hg38) full, Human (hg38) without alternative alleles
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bowtie2', 'bwa', 'novoalign', 'rtg'], 'genomes': [{'name': 'phiX174', 'dbkey': 'phix', 'annotations': []}, {'annotations': ['GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'transcripts', 'RADAR', 'mirbase'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4'], 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}, {'annotations': ['coverage', 'prioritize', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'qsignature', 'genesplicer', 'effects_transcripts', 'transcripts'], 'validation': ['giab-NA12878', 'platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap', 'dream-syn3-crossmap'], 'name': 'Human (hg38) full', 'dbkey': 'hg38'}, {'annotations': ['coverage', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'transcripts'], 'name': 'Human (hg38) without alternative alleles', 'dbkey': 'hg38-noalt'}], 'install_uniref': False}'): phiX174, Human (GRCh37), Human (hg38) full, Human (hg38) without alternative alleles
Running GGD recipe: srnaseq

I check the internal script, it is basically running ggd-run.sh script to download some srnaseq-related stuff.  wget -q -N -c -O hsa.gff3 ftp://mirbase.org/pub/mirbase/20/genomes/hsa.gff3
When I check this link, I found this ftp link is dead. The official website is down. I wonder is there any way to skip this step. Actually we don't need to do srna analysis for the moment. 

Thank you for your help .
Emmanuel

**Comment by MIAOKUI** [comment]
Running GGD recipe: srnaseq
Traceback (most recent call last):
  File "/gpfs/software/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.1a0', 'bcbio_nextgen.py')
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 211, in <module>
    
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 95, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 286, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 339, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 467, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 814, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/gpfs/software/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/gpfs/software/bcbio/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 4

**Comment by lpantano** [comment]
Hi,

sorry about this. It seems the web is down for now. If you dont need the srnaseq data you can follow this link: https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#datatarget-install to install only what you want. 

At some point mirbase should be up again.

I will keep an eye.

thanks

sent not from my computer

**Comment by chapmanb** [comment]
Thanks much for reporting this. To avoid needing Lorena's suggested workaround, I've temporarily disabled mirbase downloads until it comes back online to avoid this problem. Maybe longer term we should look into hosting mirbase tarballs on S3; they've had a couple of extended downtimes recently. Hope this fixes any remaining issues.
