### ISSUE TITLE
installation on centos 6.8 quits after long wait at "Running GGD recipe: srnaseq"

### ISSUE THREAD

**Issue by anchizhang** [chapmanb/bcbio-nextgen#1718]
The installation process below errors out the same way with python 2.7.10 or 3.4:

python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local   --genomes GRCh37 --aligners bwa --aligners bowtie2

Running GGD recipe: srnaseq
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.0', 'bcbio_nextgen.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 726, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 211, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 95, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 286, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 339, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 467, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 814, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/opt/ngs/pkg/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 4
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 246, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the issue. The mirbase.org site is down and has been non-responsive for a couple of days so the downloads stall on this install recipe.

I temporarily disabled this until mirbase comes back online. This means you won't be able to do small RNA analysis on an initial install but all other pipeline data will be available. If you remove your temporary folder:
```
rm -rf tmpbcbio-install
```
and re-run the install command it'll pick up where it left off and hopefully finish cleanly. Thanks for reporting the problem.

**Comment by elmobile** [comment]
To address ad-hoc settings at various hosts treating wget download differently,
could wget include the following options:
--random-wait 
and/or
--retry-connrefused
?
The automatic installation was interrupted by "Connection reset by peer" in a DHCP/WiFi environment.
