### ISSUE TITLE
Issue with 3-column bed file

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1722]
I seem to have a problem using a 3-column `bed` file. `sort_merge` in `bedutils.py` requires a `bed` file with four columns and throws an error. 
I am using a fairly current bcbio development version from Monday: `bcbio-nextgen,1.0.1a0-021ba76.`

I have used these `bed` files before with bcbio 1.0.0. Not sure why `sort_merge` is only called now. Still debugging this, but the issue above is quite obvious.

**Comment by gabeng** [comment]
The reason could be that I am running cnvkit now with the development version. See this commit: https://github.com/chapmanb/bcbio-nextgen/commit/051e9de318203944ee710f505e8aa338d578ba22

**Comment by gabeng** [comment]
This may be related: With the same workflow/template but different `bed` file (now 4-column) I get an error that the `bed` file is not sorted. The file is indeed not sorted, but I did not get this error with `bcbio 1.0.0`. So some things have changed how you prep `bed` files, I guess.

```[2017-01-02T22:36Z] multiprocessing: finalize_sv
[2017-01-02T22:36Z] Timing: structural variation
[2017-01-02T22:36Z] Timing: structural variation ensemble
[2017-01-02T22:36Z] Timing: structural variation validation
[2017-01-02T22:36Z] multiprocessing: validate_sv
[2017-01-02T22:36Z] Timing: heterogeneity
[2017-01-02T22:36Z] Timing: population database
[2017-01-02T22:36Z] Timing: quality control
[2017-01-02T22:36Z] multiprocessing: pipeline_summary
[2017-01-02T22:36Z] QC: M0492_S3 fastqc
[2017-01-02T22:36Z] QC: M0492_S3 qualimap
[2017-01-02T22:36Z] QC: M0492_S3 samtools
[2017-01-02T22:36Z] QC: M0492_S3 gemini
[2017-01-02T22:36Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/ubuntu/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/ubuntu/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/ubuntu/local/share/bcbio/anaconda/bin/bedtools merge  -i /bioinf-data/10112-cnv-input/validation-1/trusight_cancer_manifest_a_remap.bed > /bioinf-data/10112-cnv-validation-1/work/bcbiotx/tmp2jLC2G/trusight_cancer_manifest_a_remap-merged.bed
Error: Sorted input specified, but the file /bioinf-data/10112-cnv-input/validation-1/trusight_cancer_manifest_a_remap.bed has the following out of order record
chr10	72357808	72358938	PRF1.chr10.72357808.72358938
' returned non-zero exit status 1
[2017-01-02T22:36Z] QC: M0492_S3 qsignature
[2017-01-02T22:36Z] QC: M0492_S3 coverage
[2017-01-02T22:36Z] QC: M0492_S3 variants
[2017-01-02T22:36Z] QC: M0492_S3 picard
[2017-01-02T22:36Z] QC: M0199_S1 fastqc
[2017-01-02T22:36Z] QC: M0199_S1 qualimap
[2017-01-02T22:36Z] Uncaught exception occurred```

**Comment by chapmanb** [comment]
Ben;
Thank you for the report and detailed examples. I was able to reproduce the first problem and pushed a fix for it so you can now provide 3 column BED files to CNVkit as well.

I couldn't figure out exactly where the second issue comes from. Would you be able to re-run that problem sample with the latest development version using a single core (`bcbio_nextgen.py your_config.yaml -n 1`) and post the traceback so we can see exactly where it happens?

Sorry about the issues and thank you for the help debugging these.

**Comment by gabeng** [comment]
Brad,
the second issue stems from an unsorted bed file and the use of qualimap. I think bcbio sorts bed files prior to feeding them to the various tools - probably with the exception of qualimap? When I sort the bedfile with bedtools and restart the task (removing bedprep) the run is finished without errors. Should I open a separate issue?

**Comment by chapmanb** [comment]
Ben;
Thanks for following up with the pointer to Qualimap. This helped me identify the issue and push a fix for it. Hopefully everything will now run cleanly going forward even with unsorted BED files. Thanks again for the help debugging.
