### ISSUE TITLE
Installation failure - broad institute ftp login component?

### ISSUE THREAD

**Issue by dbrami** [chapmanb/bcbio-nextgen#1725]
Hi,
I've been trying to install bcbio for a few days now.
The first few times it failed was because of connection timeout. I resolved this by installing using 'nohup'.
But now it crashed for some other reason (please see tail of std.err below).
Is there any way to pick up just past the last properly installed component?

```
2017-01-05 04:22:30 (1.76 MB/s) - ‘variation/dbsnp-147-orig.vcf.gz’ saved [3489630146]

--2017-01-05 04:35:38--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/b37/hapmap_3.3.b37.vcf.gz
           => ‘-’
Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.80.251
Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... 
Login incorrect.

gzip: stdin: unexpected end of file
Traceback (most recent call last):
  File "/mnt/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.0', 'bcbio_nextgen.py')
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 211, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 95, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 286, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 339, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 467, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 814, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/mnt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/bcbio/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/mnt/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./bcbio_nextgen_install.py", line 246, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "./bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/mnt/bcbio/tools', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

**Comment by dbrami** [comment]
The odd thing is that the following command does indeed work:
wget ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/b37/hapmap_3.3.b37.vcf.gz

**Comment by chapmanb** [comment]
Daniel;
Sorry about the issue. This is probably an intermittent ftp error from the broad servers. They can often get overloaded leading to these failures.

If you re-run the same install command it'll pick up where it left off and hopefully get through this point. In general the installer restarts at the same place so you any one-off connection errors hopefully aren't too painful. Hope this gets the installation finished for you.

**Comment by dbrami** [comment]
It did! Thank you Brad 👍
