### ISSUE TITLE
SNPEff errors while running exome validation example

### ISSUE THREAD

**Issue by dbrami** [chapmanb/bcbio-nextgen#1730]
Hi folks,
I tried running the exome validation example on a pretty beefy machine (56 CPUs, 256 GB RAM) but the process errored out. I believe it was at the SNPEff stage perhaps running out of memory? I looked at other issues that seemed to be similar and the solution was to allocate more memory in the YAML file but I did not find the appropriate field to modify.
Any suggestions would be great.
Also will re-running the command just pick up at the right point in process or are there any files I should delete manually?
Here's the tail end of my error log:
```
...........................................................................
/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py in _do_run(cmd='set -o pipefail; export PATH=/mnt/bcbio/anaconda...k/freebayes/tx/tmpl7_Zi7/NA12878-2-effects.vcf.gz', checks=None, log_stdout=False)
     90                 error_msg = " ".join(cmd) if not isinstance(cmd, basestring) else cmd
     91                 error_msg += "\n"
     92                 error_msg += "".join(debug_stdout)
     93                 s.communicate()
     94                 s.stdout.close()
---> 95                 raise subprocess.CalledProcessError(exitcode, error_msg)
        exitcode = 255
        error_msg = 'set -o pipefail; export PATH=/mnt/bcbio/anaconda...040)\n\tat org.snpeff.SnpEff.main(SnpEff.java:158)\n'
     96             else:
     97                 break
     98     s.communicate()
     99     s.stdout.close()

CalledProcessError: Command 'set -o pipefail; export PATH=/mnt/bcbio/anaconda/bin:$PATH &&  /mnt/bcbio/anaconda/bin/snpEff -Xms750m -Xmx3g -Djava.io.tmpdir=/mnt/bcbio/dbrami/validation/NA12878-exome-eval/work/freebayes/tx/tmpl7_Zi7/tmp eff -dataDir /mnt/bcbio/genomes/Hsapiens/GRCh37/snpeff  -noLog -i vcf -o vcf -s /mnt/bcbio/dbrami/validation/NA12878-exome-eval/work/freebayes/NA12878-2-effects-stats.html GRCh37.75 /mnt/bcbio/dbrami/validation/NA12878-exome-eval/work/freebayes/NA12878-2.vcf.gz | /mnt/bcbio/anaconda/bin/pbgzip -n 16  -c > /mnt/bcbio/dbrami/validation/NA12878-exome-eval/work/freebayes/tx/tmpl7_Zi7/NA12878-2-effects.vcf.gz
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at org.snpeff.interval.Transcript.cds(Transcript.java:531)
        at org.snpeff.interval.Gene.canonical(Gene.java:115)
        at org.snpeff.snpEffect.SnpEffectPredictor.canonical(SnpEffectPredictor.java:193)
        at org.snpeff.snpEffect.SnpEffectPredictor.buildForest(SnpEffectPredictor.java:170)
        at org.snpeff.SnpEff.loadDb(SnpEff.java:480)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:998)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:981)
        at org.snpeff.SnpEff.run(SnpEff.java:1040)
        at org.snpeff.SnpEff.main(SnpEff.java:158)
' returned non-zero exit status 255
___________________________________________________________________________
295718.44user 17342.20system 3:22:32elapsed 2576%CPU (0avgtext+0avgdata 15049080maxresident)k
13819272inputs+223930912outputs (1640major+3265902859minor)pagefaults 0swaps
```

**Comment by chapmanb** [comment]
Daniel;
Sorry about the issue, could you try updating to the latest development version (`bcbio_nextgen.py upgrade -u development`) and re-running. We recently changed snpEff behavior to have less memory per core but to scale up memory on multi-core runs. However, this leaves memory slightly below what you need for human genome runs on single core runs. The fix scales up to 2 cores memory by default to avoid this, so you don't need to manually adjust from the defaults. Hope this fixes things for you.
