### ISSUE TITLE
CNVkit error: too many values to unpack

### ISSUE THREAD

**Issue by MIAOKUI** [chapmanb/bcbio-nextgen#1744]
Hi Chapmanb, 

With you guys'  great assistance I finally deploy bcbio framework on our cluster. When I try to test it with demo cancer project, I uncomment cnv part of yaml config like follows:     
....
svcaller: [cnvkit, lumpy, delly]
    coverage_interval: amplicon
  analysis: variant2
  description: syn3-normal
...
svcaller: [cnvkit, lumpy, delly]
    coverage_interval: amplicon
    svvalidate:
      DEL: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DEL.bed
      DUP: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DUP.bed
      INS: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INS.bed
      INV: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INV.bed
  analysis: variant2
  description: syn3-tumor

I got the following error:
[2017-01-12T15:10Z] node2: Annotate BED file with gene info
[2017-01-12T15:10Z] node2: CNVkit coverage bin estimation
[2017-01-12T15:10Z] node2: Sequencing-accessible regions will be ignored: /gpfs/software/cancer_pipeline_test/project/work/structural/syn3-tumor/cnvkit/NGv3-sortmerge.bed
[2017-01-12T15:10Z] node2: Estimated read length 101.0
[2017-01-12T15:10Z] node2: Unexpected error
Traceback (most recent call last):
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 380, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 165, in detect_sv
    for svdata in caller_fn(items):
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 31, in run
    return _cnvkit_by_type(items, background)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 43, in _cnvkit_by_type
    return _run_cnvkit_cancer(items, background)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 87, in _run_cnvkit_cancer
    ckouts = _run_cnvkit_shared([paired.tumor_data], normal_data)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 156, in _run_cnvkit_shared
    raw_work_dir, inputs[0])
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 320, in _cnvkit_targets
    bin_estimates = _cnvkit_coverage_bin_estimate(raw_target_bed, access_bed, cov_interval, work_dir, data)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 355, in _cnvkit_coverage_bin_estimate
    name, depth, bin_size = line.strip().split()
ValueError: too many values to unpack

It looks like a python error when unpack values. 

Attachment is the running log and config files. 
[log.zip](https://github.com/chapmanb/bcbio-nextgen/files/703231/log.zip)
[cancer-dream-syn3.yaml.zip](https://github.com/chapmanb/bcbio-nextgen/files/703232/cancer-dream-syn3.yaml.zip)

**Comment by etal** [comment]
``line.strip().split('\t')`` might do it. The row names in amplicon mode have spaces in them.

**Comment by MIAOKUI** [comment]
How to fix it then ?

**Comment by MIAOKUI** [comment]
I made some change on cnvkit.py script like follow:352     with open(out_file) as in_handle:
353         for line in in_handle:
354             if line.startswith(tuple(estimate_map.keys())):
355                 #name, depth, bin_size = line.strip().split()
356                 **name, depth, bin_size = line.strip().split('\t')**
357                 #name = estimate_map[name.replace(":", "")]
358                 **name = estimate_map[name.replace(":", "").strip()]**
359                 try:
360                     bin_size = int(bin_size)
361                 except ValueError:
362                     bin_size = None
363                 if bin_size and bin_size > 0:
364                     cur_min, cur_max = range_map[(cov_interval, name)]
365                     avg_bin_sizes[name] = max(min(bin_size, cur_max), cur_min)
366     return avg_bin_sizes

It seems work, I am not sure if their some side effect.

**Comment by chapmanb** [comment]
Thank you for the report and diagnosing the fix so quickly. I added this change to the development version so it should hopefully work correctly for amplicon data as well. Much appreciated.
