### ISSUE TITLE
delly error: Unrecognized command -t 

### ISSUE THREAD

**Issue by MIAOKUI** [chapmanb/bcbio-nextgen#1745]
Hi  Chanpmanb 

When run cancer-tumor pipeline with SV analysis. I got an error on lumpy part. The error as follows:[2017-01-13T06:31Z] node1: delly structural variant
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: delly structural variant
[2017-01-13T06:31Z] node1: delly structural variant
[2017-01-13T06:31Z] node1: delly structural variant
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: Unrecognized command -t
[2017-01-13T06:31Z] node1: Uncaught exception occurred
Traceback (most recent call last):
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export OMP_NUM_THREADS=1 && export LC_ALL=C && delly -t DEL -g /gpfs/software/bcbio/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -o /gpfs/software/cancer_pipeline_test/project/work/bcbiotx/tmpedzpc5/syn3-tumor-sort-syn3-svs-7-DEL.vcf -x /gpfs/software/cancer_pipeline_test/project/work/structural/syn3-tumor/delly/syn3-tumor-sort-syn3-svs-7-DEL-exclude-7-delly.bed /gpfs/software/cancer_pipeline_test/project/work/align/syn3-tumor/syn3-tumor-sort.bam /gpfs/software/cancer_pipeline_test/project/work/align/syn3-normal/syn3-normal-sort.bam
Unrecognized command -t
' returned non-zero exit status 1
[2017-01-13T06:31Z] node1: Uncaught exception occurred
Traceback (most recent call last):
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export OMP_NUM_THREADS=1 && export LC_ALL=C && delly -t DEL -g /gpfs/software/bcbio/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -o /gpfs/software/cancer_pipeline_test/project/work/bcbiotx/tmpKZmFEP/syn3-tumor-sort-syn3-svs-1-DEL.vcf -x /gpfs/software/cancer_pipeline_test/project/work/structural/syn3-tumor/delly/syn3-tumor-sort-syn3-svs-1-DEL-exclude-1-delly.bed /gpfs/software/cancer_pipeline_test/project/work/align/syn3-tumor/syn3-tumor-sort.bam /gpfs/software/cancer_pipeline_test/project/work/align/syn3-normal/syn3-normal-sort.bam
Unrecognized command -t
' returned non-zero exit status 1

I think this is the cmd in-compatible problem. 

The detail logs on the attachment 

[log.zip](https://github.com/chapmanb/bcbio-nextgen/files/703709/log.zip)

**Comment by MIAOKUI** [comment]
I know what happened, delly 0.7.6 cmd structure becomes like this delly <cmd> [options] , and on cmd is "call" which call SV. Even I add "call" into the delly.py, here still problem. The new version delly produce bcf result instead of vcf, then all the following manipulation is not compatible. I cannot figure out how to fix every steps. Do you have any better idea about this  ?

**Comment by chapmanb** [comment]
Thanks for the report. Apologies, we haven't been using delly, so it looks like support for it is not up to date. We'll have to do some work to synchronize with the latest changes. In the short term, we have support for 3 other comparable structural variant callers: manta, lumpy and wham. Would using those work for your use case?

**Comment by MIAOKUI** [comment]
Hi Chapmanb, 

Thank you for your reply, we will try three other SV callers then. 
bcbio is good project, I like it !

**Comment by chapmanb** [comment]
Thank you again for the report. The latest bcbio development version is now updated to run with delly version, so should now be working cleanly again. Please let us know if you run into any issues at all with the updated integration.
