### ISSUE TITLE
Lumpy analysis doesn't proceed with no error message

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1753]
Hi Brad,

Lumpy runs halfway on the bcbio pipeline for one of my samples and doesn't proceed:

[2017-01-16T04:37Z] HLA-C*17:01:01:03   1000000
[2017-01-16T04:37Z] HLA-C*17:03 1000000
[2017-01-16T04:37Z] HLA-DQA1*06:01:01   1000000
[2017-01-16T04:37Z] HLA-DQB1*03:01:01:01        1000000
[2017-01-16T04:37Z] HLA-DQB1*03:01:01:03        1000000
[2017-01-16T04:38Z] LUMPY Express done
[2017-01-16T04:38Z] Sort VCF by reference
[2017-01-16T04:38Z] tabix index 1477_220416_T-sort-T1477_220416-svs-prep.vcf.gz
[2017-01-16T04:38Z] Select sample: 1477_220416_T
[2017-01-16T04:38Z] tabix index 1477_220416_T-sort-T1477_220416-svs-prep-1477_22
0416_T.vcf.gz
[2017-01-16T04:38Z] Select Lumpy breakends
[2017-01-16T04:38Z] tabix index 1477_220416_T-sort-T1477_220416-svs-prep-1477_22
0416_T-bnd.vcf.gz
[2017-01-16T04:38Z] Select Lumpy non-breakends
[2017-01-16T04:38Z] tabix index 1477_220416_T-sort-T1477_220416-svs-prep-1477_22
0416_T-std.vcf.gz
[2017-01-16T04:38Z] SV genotyping with svtyper
[2017-01-16T07:09Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 78, in _do_run
    line = s.stdout.readline()
KeyboardInterrupt

I have repeated the run again but it still hangs at the same sample.
When comparing the files in the lumpy directory for this sample, it is lesser than the other samples:
[dlho@n009 ~/tancrc/MUX4393/MUX4393/work/log]ls ../structural/1477_220416_T/lumpy/
1477_220416_T-sort-dels.bedpe
1477_220416_T-sort-dups.bedpe
1477_220416_T-sort-T1477_220416-svs-exclude.bed
1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-bnd.vcf.gz
1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-bnd.vcf.gz.tbi
1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-std.vcf.gz
1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-std.vcf.gz.tbi
1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T.vcf.gz
1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T.vcf.gz.tbi
1477_220416_T-sort-T1477_220416-svs-prep.vcf.gz
1477_220416_T-sort-T1477_220416-svs-prep.vcf.gz.tbi
1477_220416_T-sort-T1477_220416-svs.vcf
tx

The last command in the log file is below:
[2017-01-16T07:15Z] bcftools view /mnt/projects/dlho/tancrc/MUX4393/MUX4393/work/structural/1477_220416_T/lumpy/1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-std.vcf.gz -T ^/mnt/projects/dlho/tancrc/MUX4393/MUX4393/work/structural/1477_220416_T/lumpy/1477_220416_T-sort-T1477_220416-svs-exclude.bed | /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/python /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/svtyper -M -B /mnt/projects/dlho/tancrc/MUX4393/MUX4393/work/align/1477_220416_T/1477_220416_T-sort.bam -S /mnt/projects/dlho/tancrc/MUX4393/MUX4393/work/align/1477_220416_T/1477_220416_T-sort-sr.bam | bcftools annotate -h /mnt/projects/dlho/tancrc/MUX4393/MUX4393/work/structural/1477_220416_T/lumpy/tx/tmp4elal4/1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-std-wgts-header.txt | bgzip -c > /mnt/projects/dlho/tancrc/MUX4393/MUX4393/work/structural/1477_220416_T/lumpy/tx/tmp4elal4/1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-std-wgts.vcf.gz

When I checked the files in the tx directory, the last file that was created seemed to be empty, perhaps something went wrong there?
[dlho@n009 ~/tancrc/MUX4393/MUX4393/work/log]ls -l ../structural/1477_220416_T/lumpy/tx/tmp4elal4/
total 588
-rw-r--r-- 1 dlho cts07s1 167723 Jan 16 15:15 1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-std-wgts-header.txt
-rw-r--r-- 1 dlho cts07s1      0 Jan 16 15:15 1477_220416_T-sort-T1477_220416-svs-prep-1477_220416_T-std-wgts.vcf.gz

Can you help me pls? Thank you!

**Comment by ohofmann** [comment]
I've seen Lumpy hang at that stage for at least one sample of mine as well. Just haven't had the time to reproduce it. Will give this another try, but give runtime and CPU availability we're talking weeks.

**Comment by phu5ion** [comment]
Hi,

I left the pipeline running overnight and this morning the analysis seems to have gotten past the roadblock. Perhaps the sample just requires more time - I estimate more than 3hrs? I won't close the issue for now in case this is problematic for anyone else.

**Comment by chapmanb** [comment]
Thanks for the report and for following up. Most of the svtyper issues we've found are due to slow speeds rather than hangs. To try and improve this, I added support for the latest svtyper release in the bcbio development version so we can test. You can update with:
```
bcbio_nextgen.py upgrade -u development
bcbio_conda install -c bioconda svtyper=0.1.1
```
and then re-run Lumpy. I'll also test on my side but it would be great to know if this provides speed improvements on the problematic cases. Thanks much.

**Comment by phu5ion** [comment]
Hi Brad,

Sure, I can't run it now due to the resource requirements in running my analysis again, but I'll run it on new samples when the same error occurs, and let you know how it turns out!

**Comment by phu5ion** [comment]
Hi Brad,

Although I did not rerun lumpy, the same problematic sample met with the same speed problems during the prioritization step. Upgrading svtyper provided speed improvements for prioritization, and I believe it will work for lumpy too. Thanks a lot for your help!
