### ISSUE TITLE
cnvkit error: sid, nid = pairs[0] ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by MIAOKUI** [chapmanb/bcbio-nextgen#1754]
Hi Chapmanb, 

I try to go thought cancer somatic mutation pipeline, with tumor only mode. yaml config as follows:
Which is sample yaml file after delete normal part. 

# https://www.synapse.org/#!Synapse:syn312572/wiki/62018
---
details:
- algorithm:
    aligner: bwa
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: true
    recalibrate: true
    realign: true
    remove_lcr: true
    platform: illumina
    quality_format: standard
    variantcaller: [mutect2, freebayes, vardict, varscan]
    indelcaller: false
    ensemble:
      numpass: 2
    variant_regions: ../input/NGv3.bed
    validate: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth.vcf.gz
    validate_regions: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_regions.bed
    #svcaller: [cnvkit, lumpy, delly]
    svcaller: [cnvkit, lumpy, manta]
    coverage_interval: amplicon
    svvalidate:
      DEL: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DEL.bed
      DUP: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DUP.bed
      INS: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INS.bed
      INV: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INV.bed
  analysis: variant2
  description: syn3-tumor
  #files: ../input/synthetic.challenge.set3.tumor.bam
  files:
    - ../input/synthetic_challenge_set3_tumor_NGv3_1.fq.gz
    - ../input/synthetic_challenge_set3_tumor_NGv3_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: syn3
    phenotype: tumor
fc_date: '2014-08-13'
fc_name: dream-syn3
upload:
  dir: ../final

I got the error as follows: 
[2017-01-16T05:02Z] mgt: ipython: compare_to_rm
[2017-01-16T05:05Z] mgt: Timing: ensemble calling
[2017-01-16T05:05Z] mgt: ipython: combine_calls
[2017-01-16T05:05Z] node1: Ensemble consensus calls for syn3: mutect2,freebayes,vardict,varscan
[2017-01-16T05:06Z] mgt: Timing: validation summary
[2017-01-16T05:06Z] mgt: Timing: structural variation precall
[2017-01-16T05:06Z] mgt: ipython: detect_sv
[2017-01-16T05:06Z] mgt: Timing: structural variation
[2017-01-16T05:06Z] mgt: ipython: detect_sv
[2017-01-16T05:10Z] node1: Uncaught exception occurred
Traceback (most recent call last):
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/gpfs/software/bcbio/bcbio/anaconda/bin:$PATH && export 
TMPDIR=/gpfs/software/cancer_pipeline_test/project_tumor_only/work/bcbiotx/tmp8jojxo && /gpfs/software/bcbio/bcbio/anaconda/bin/cn
vkit.py segment -p 16 -o /gpfs/software/cancer_pipeline_test/project_tumor_only/work/bcbiotx/tmp8jojxo/syn3-tumor-sort-flatbackgro
und.cns /gpfs/software/cancer_pipeline_test/project_tumor_only/work/structural/syn3-tumor/cnvkit/raw/syn3-tumor-sort-flatbackgroun
d.cnr -v /gpfs/software/cancer_pipeline_test/project_tumor_only/work/mutect2/syn3-effects-annotated-priority.vcf.gz
Traceback (most recent call last):
  File "/gpfs/software/bcbio/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 779, in _cmd_segment
    args.min_variant_depth, args.zygosity_freq)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 2134, in load_het_snps
    skip_somatic=True)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/__init__.py", line 80, in read
    dframe = reader(infile, **kwargs)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 40, in read_vcf
    sid, nid = _choose_samples(vcf_reader, sample_id, normal_id)
  File "/gpfs/software/bcbio/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 121, in _choose_samples
    sid, nid = pairs[0]
ValueError: need more than 1 value to unpack
' returned non-zero exit status 1

It looks like cnvkit problem. Which cannot recognise tumor only mode.  How can I fix it ?

**Comment by chapmanb** [comment]
Sorry about the issue, I'm not positive what is wrong here but can dig further after @etal has a chance to weigh in on it. Thanks for reporting the problem.

**Comment by etal** [comment]
Sorry, I did not realize Mutect2 could run in tumor-only mode; the VCF parser assumes there would be two samples in a Mutect2 VCF. I'll fix it in the CNVkit development version now.

**Comment by chapmanb** [comment]
Eric -- thanks so much for the quick fix in CNVkit.

@MIAOKUI -- MuTect2 will run with tumor-only samples but the Broad doesn't recommend using it for this. My validations with it have shown it performs pretty badly in this setup, so I'd suggest leaving it out of this run and only using it when you have paired normals.

Hope this helps.
