### ISSUE TITLE
Prioritization error "this version only supports 100 named groups"

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1756]
Hi Brad,

Sorry to trouble you again! I have met into an error while trying out the SV prioritisation:
[2017-01-16T13:15Z] Prioritize: simplified annotation output
[2017-01-16T13:15Z] Sort VCF by reference
[2017-01-16T13:15Z] tabix index 1258_290816_M-sort-call-effects-simple-prep.vcf.gz
[2017-01-16T13:15Z] Prioritize: convert to tab delimited
[2017-01-16T13:15Z] SV genotyping with svtyper
[2017-01-16T14:05Z] Sort VCF by reference
[2017-01-16T14:05Z] tabix index 1258_290816_M-sort-M1258_290816-svs-prep-1258_290816_M-std-wgts-prep-combined-filter-backfilter-effects-wgts-prep.vcf.gz
[2017-01-16T14:05Z] Prioritize: simplified annotation output
[2017-01-16T14:06Z] Sort VCF by reference
[2017-01-16T14:06Z] tabix index 1258_290816_M-sort-M1258_290816-svs-prep-1258_290816_M-std-wgts-prep-combined-filter-backfilter-effects-wgts-prep-simple-prep.vcf.gz
[2017-01-16T14:06Z] Prioritize: convert to tab delimited
[2017-01-16T14:06Z] Prioritize: simplified annotation output
[2017-01-16T14:06Z] Sort VCF by reference
[2017-01-16T14:06Z] tabix index somaticSV-1258_290816_M-simple-prep.vcf.gz
[2017-01-16T14:06Z] Prioritize: convert to tab delimited
[2017-01-16T14:06Z] Combine prioritized from multiple callers
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 230, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 180, in variant2pipeline
    samples = structural.run(samples, run_parallel, "ensemble")
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 146, in run
    for xs in to_process.values()))
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 228, in detect_sv
    return structural.detect_sv(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 165, in detect_sv
    for svdata in caller_fn(items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/prioritize.py", line 41, in run
    data = _cnv_prioritize(data)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/prioritize.py", line 189, in _cnv_prioritize
    df = supported[pcall["variantcaller"]]["fn"](*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/structural/prioritize.py", line 152, in _cnvkit_prioritize
    mdf = mdf[mdf["gene"].str.contains("|".join(genes))]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/strings.py", line 1471, in contains
    regex=regex)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/pandas/core/strings.py", line 231, in str_contains
    regex = re.compile(pat, flags=flags)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/sre_compile.py", line 583, in compile
    "sorry, but this version only supports 100 named groups"
AssertionError: sorry, but this version only supports 100 named groups

I am using lumpy, manta, and CNVkit callers.
Thanks for looking into this for me!

**Comment by chapmanb** [comment]
Thank you for the report. I've been trying to reproduce this and am unable to. Would you be able to share the file you're using for `svprioritize`? There is something about it that's triggering this error in the underlying regular expression machinery used to subset the CNVkit call file by genes of interest. Thanks much for the help debugging.

**Comment by phu5ion** [comment]
Hi Brad,

Sorry for the delay in reply as I have been away. I'm actually not sure which files you are referring too, so I have attached all the prioritize files. 
[prioritize.zip](https://github.com/chapmanb/bcbio-nextgen/files/722533/prioritize.zip)

Hope you can access it.

**Comment by chapmanb** [comment]
Thanks much for following up and helping with debugging. The file I was hoping to get for debugging is the one in your sample YAML file under `algorithm: svprioritize:`:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#structural-variant-calling

That should specify the gene list you're prioritizing with and hopefully let me reproduce the too many regular expressions error you're seeing.

**Comment by phu5ion** [comment]
Hi Brad,

I have used the same bed file for svprioritise as what I have used to specify variant_region. It can be found in https://gist.github.com/phu5ion/be9a2ea4c52f0a7c0aae105c7a36756a.
Perhaps I understand what is the issue now. It could be that either it does not accept a 5-col bed file or the gene_name is not in the correct format.
Could you advise whether I am able to specify a list of custom genes such as the one I attach here? Thanks!
[101.txt](https://github.com/chapmanb/bcbio-nextgen/files/728451/101.txt)

**Comment by chapmanb** [comment]
Thanks for following up so quickly. The issue looks like the gene names in the BED file you provided, it's confusing the regular expression engine. The latter list of custom genes is the preferred input for prioritization, so if it works for your analysis switching over to that should hopefully avoid this issue. Hope this works for what you need.

**Comment by phu5ion** [comment]
Hi Brad,

Thanks a lot! Seems like it's working now!
