### ISSUE TITLE
Java and Vardict issue

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1759]
Hi Brad,

I found the following error during variant calling. It seems that there is a conflict of Java and Vardict. However, the system Java is version 1.7 in my cluster computer. But the following command shows the bcbio Java is 1.8.

$ /path/to/bcbio/anaconda/bin/java -version
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (Zulu 8.15.0.1-linux64) (build 1.8.0_92-b15)
OpenJDK 64-Bit Server VM (Zulu 8.15.0.1-linux64) (build 25.92-b15, mixed mode)

Is that the reason? But previously, the same situation did not cause this error. Could you please help me with the debugging?

Thanks!

[2017-01-14T04:58Z] ica1: ipython: variantcall_sample
[2017-01-14T06:05Z] ica2: Uncaught exception occurred
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && export PATH=/path/to/bcbio/anaconda/bin:$PATH && export VAR_DICT_OPTS='-Xms750m -Xmx6000m -XX:+UseSerialGC -Djava.io.tmpdir=/path/to/work/vardict/1/tx/tmpSdMLUA' && vardict-java -G /path/to/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 12413T -b "/path/to/work/bamprep/12413T/1/12413T-sort-1_0_249250621-prep.bam|/path/to/work/bamprep/12413N/1/12413N-sort-1_0_249250621-prep.bam" -c 1 -S 2 -E 3 -g 4 -Q 10 /path/to/work/vardict/1/12413-1_0_249250621-regions-regionlimit.bed | testsomatic.R | var2vcf_paired.pl -P 0.9 -m 4.25 -f 0.1  -M  -N "12413T|12413N" | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null | /path/to/bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "bwa")' | sed 's/\\.*Somatic\\/Somatic/' | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/' | /path/to/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $5) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | /path/to/bcbio/anaconda/bin/vcfstreamsort | bgzip -c > /path/to/work/vardict/1/tx/tmpSdMLUA/12413-1_0_249250621.vcf.gz
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/astrazeneca/vardict/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Use of uninitialized value $sample in concatenation (.) or string at /path/to/bcbio/anaconda/bin/var2vcf_paired.pl line 35.
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the issue, the latest VarDict requires Java 8 and the underlying issue is likely that your JAVA_HOME points to Java 7 instead. You could either `unset JAVA_HOME` or upgrade to the latest development or stable version of bcbio, both of which have fixes for this:
```
bcbio_nextgen.py upgrade -u development
```
Hope that gets it working for you.
