### ISSUE TITLE
multiqc fails with: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1769]
Hi,

multiqc fails with a No such file or directory error, and indeed, the temp directory seems to be missing. The error happened with 2 different samples and I'm using the development version of bcbio. Can it be a filesystem error or is it a problem with bcbio?

<pre>
[2017-01-19T00:54Z] Run multiqc
[2017-01-19T00:54Z] Traceback (most recent call last):
[2017-01-19T00:54Z]   File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/bin/multiqc", line 4, in <module>
[2017-01-19T00:54Z]     __import__('pkg_resources').run_script('multiqc==1.0.dev0', 'multiqc')
[2017-01-19T00:54Z]   File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
[2017-01-19T00:54Z]   File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
[2017-01-19T00:54Z]   File "/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 31, in <module>
[2017-01-19T00:54Z]     from multiqc import __version__
[2017-01-19T00:54Z]   File "/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/__init__.py", line 2, in <module>
[2017-01-19T00:54Z]     from multiqc.utils import config
[2017-01-19T00:54Z]   File "/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/utils/config.py", line 31, in <module>
[2017-01-19T00:54Z]     git_hash = subprocess.check_output(['git', 'rev-parse', 'HEAD'], stderr=subprocess.STDOUT)
[2017-01-19T00:54Z]   File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
[2017-01-19T00:54Z]     process = Popen(stdout=PIPE, *popenargs, **kwargs)
[2017-01-19T00:54Z]   File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
[2017-01-19T00:54Z]     errread, errwrite)
[2017-01-19T00:54Z]   File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
[2017-01-19T00:54Z]     raise child_exception
[2017-01-19T00:54Z] OSError: [Errno 2] No such file or directory
[2017-01-19T00:54Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export TMPDIR=/pico/home/userexternal/esebesty/scratch/tmp && /pico/home/userexternal/esebesty/work/bcbio/data/anaconda/bin/multiqc -f -l /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch6597/work/qc/multiqc/list_files.txt -o /pico/home/userexternal/esebesty/scratch/tmp/tmp6rgRE7
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==1.0.dev0', 'multiqc')
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 31, in <module>
    from multiqc import __version__
  File "/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/__init__.py", line 2, in <module>
    from multiqc.utils import config
  File "/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/utils/config.py", line 31, in <module>
    git_hash = subprocess.check_output(['git', 'rev-parse', 'HEAD'], stderr=subprocess.STDOUT)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
' returned non-zero exit status 1
</pre>

**Comment by chapmanb** [comment]
Endre;
Apologies about the issue and thank you for the report. MultiQC requires git, and the error message is from not having it in your PATH. bcbio installs this into the anaconda directory and I pushed a fix to the latest development that will inject this into the PATH automatically. If you upgrade to the latest development version and re-run it should work cleanly now. Thanks again.
