### ISSUE TITLE
Error during postprocess alignment

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1798]
Hi Brad, 

I'm trying to test cnvkit on hg38, but I'm getting the following error:
```
[2017-01-30T10:35Z] Timing: callable regions
[2017-01-30T10:35Z] multiprocessing: prep_samples
[2017-01-30T10:35Z] multiprocessing: postprocess_alignment
[2017-01-30T10:35Z] Counting not unmapped and not mate_is_unmapped and not secondary_alignment and not failed_quality_control and not duplicate for /home/projects/bcbio_annotation/test_runs/cnvseq/work/align/D1402628/D1402628-sort.bam
[2017-01-30T10:36Z] Calculate coverage: D1402628
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:01:01:01:1-3503
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:01:01:01:1-3503
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:01:01:02N:1-3291
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:01:38L:1-3374
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:02:1-3374
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:01:01:02N:1-3291
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:01:38L:1-3374
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:02:1-3374
[2017-01-30T10:44Z] ERROR with command: Command('echo HLA-A*01:01:01:01:1-3503; samtools depth -Q 1 -d 2500 -r HLA-A*01:01:01:01:...', stdout: '', exit-code: 1, error: exit status 1, run-time: 22.343542ms)
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:03:1-3503
[2017-01-30T10:44Z] 2017/01/30 11:44:44 echo HLA-A*01:01:01:01:1-3503; samtools depth -Q 1 -d 2500 -r HLA-A*01:01:01:01:1-3503 /home/projects/bcbio_annotation/test_runs/cnvseq/work/align/D1402628/D1402628-sort.bam EOF exit status 1
[2017-01-30T10:44Z] 2017/01/30 11:44:44 sent empty file-name to xopen.Ropen
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:04N:1-3136
[2017-01-30T10:44Z] zsh:1: no matches found: HLA-A*01:09:1-3105
[2017-01-30T10:44Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'goleft depth --q 1 --mincov 4 --reference /home/galaxy/bcbio-dev/genomes/Hsapiens/hg38/seq/hg38.fa --processes 5 --ordered --prefix /tmp/bcbio/tmpsWbKtd/D1402628-coverage /home/projects/bcbio_annotation/test_runs/cnvseq/work/align/D1402628/D1402628-sort.bam
zsh:1: no matches found: HLA-A*01:01:01:01:1-3503
zsh:1: no matches found: HLA-A*01:01:01:01:1-3503
zsh:1: no matches found: HLA-A*01:01:01:02N:1-3291
zsh:1: no matches found: HLA-A*01:01:38L:1-3374
zsh:1: no matches found: HLA-A*01:02:1-3374
zsh:1: no matches found: HLA-A*01:01:01:02N:1-3291
zsh:1: no matches found: HLA-A*01:01:38L:1-3374
zsh:1: no matches found: HLA-A*01:02:1-3374
ERROR with command: Command('echo HLA-A*01:01:01:01:1-3503; samtools depth -Q 1 -d 2500 -r HLA-A*01:01:01:01:...', stdout: '', exit-code: 1, error: exit status 1, run-time: 22.343542ms)
zsh:1: no matches found: HLA-A*01:03:1-3503
2017/01/30 11:44:44 echo HLA-A*01:01:01:01:1-3503; samtools depth -Q 1 -d 2500 -r HLA-A*01:01:01:01:1-3503 /home/projects/bcbio_annotation/test_runs/cnvseq/work/align/D1402628/D1402628-sort.bam EOF exit status 1
2017/01/30 11:44:44 sent empty file-name to xopen.Ropen
zsh:1: no matches found: HLA-A*01:04N:1-3136
zsh:1: no matches found: HLA-A*01:09:1-3105
zsh:1: no matches found: HLA-A*01:11N:1-3374
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/galaxy/bcbio-dev/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml) 
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 133, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)  
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch() 
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 88, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 224, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 36, in sample_callable_bed
    depth_bed, callable_bed, highdepth_bed, variant_regions_avg_cov = coverage.calculate(bam_file, data)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 101, in calculate
    do.run(cmd, msg, env=bcbio_env)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'goleft depth --q 1 --mincov 4 --reference /home/galaxy/bcbio-dev/genomes/Hsapiens/hg38/seq/hg38.fa --processes 5 --ordered --prefix /tmp/bcbio/tmpsWbKtd/D1402628-coverage /home/projects/bcbio_annotation/test_runs/cnvseq/work/align/D1402628/D1402628-sort.bam
zsh:1: no matches found: HLA-A*01:01:01:01:1-3503
zsh:1: no matches found: HLA-A*01:01:01:01:1-3503
zsh:1: no matches found: HLA-A*01:01:01:02N:1-3291
zsh:1: no matches found: HLA-A*01:01:38L:1-3374
zsh:1: no matches found: HLA-A*01:02:1-3374
zsh:1: no matches found: HLA-A*01:01:01:02N:1-3291
zsh:1: no matches found: HLA-A*01:01:38L:1-3374
zsh:1: no matches found: HLA-A*01:02:1-3374
ERROR with command: Command('echo HLA-A*01:01:01:01:1-3503; samtools depth -Q 1 -d 2500 -r HLA-A*01:01:01:01:...', stdout: '', exit-code: 1, error: exit status 1, run-time: 22.343542ms)
zsh:1: no matches found: HLA-A*01:03:1-3503
2017/01/30 11:44:44 echo HLA-A*01:01:01:01:1-3503; samtools depth -Q 1 -d 2500 -r HLA-A*01:01:01:01:1-3503 /home/projects/bcbio_annotation/test_runs/cnvseq/work/align/D1402628/D1402628-sort.bam EOF exit status 1
2017/01/30 11:44:44 sent empty file-name to xopen.Ropen
zsh:1: no matches found: HLA-A*01:04N:1-3136
zsh:1: no matches found: HLA-A*01:09:1-3105
zsh:1: no matches found: HLA-A*01:11N:1-3374
' returned non-zero exit status 1
```

I'm on the latest development version, using the following config:
```
fc_name: cnvseq-test
upload:
  dir: ../final
globals:
  analysis_regions: /home/projects/bcbio_annotation/ref/variant_regions/RefSeq_allexons_20bp.sorted.merged.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: D1402628
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      svcaller: cnvkit
      #variant_regions: analysis_regions
      effects: vep
      effects_transcripts: canonical
      tools_on:
        - vcf2db_expand
        - vep_splicesite_annotations
    files: /home/projects/bcbio_annotation/test_runs/cnvseq/input/NSQ_Run197-31779770/D1402628-38511650/D1402628.fastq.gz
```

as you can see, I'm using single end data. Could that have something to do with it?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks much for the report. It looks like the issue is during `goleft depth` calculation of region coverage. It's echoing the poorly named HLA contigs like `HLA-A*01:01:01:01:1-3503` and the wildcard characters in the name are getting picked up by your zsh shell.

@brentp is it possible to quote those commands, like:
```
echo HLA-A*01:01:01:01:1-3503; samtools depth -Q 1 -d 2500 -r HLA-A*01:01:01:01
```
within goleft to avoid this problem? This looks like it cropped up after moving over to not using a `--bed` file after our discussion in #1731. Thanks so much.

**Comment by brentp** [comment]
Hi guys, I was able to make a test for this and make a fix. Please try the new release of goleft.

**Comment by matthdsm** [comment]
Hi Brad, Brent

Thanks for the fix! I updated the bioconda recipe for goleft to the latest release, so it can be tested more easily. I'll get back to you as soon as the recipe's merged.

Thanks again.
M

**Comment by matthdsm** [comment]
Hi,

The new version of goleft fixed the issue. Thanks for the quick response!

M

**Comment by brentp** [comment]
great! thanks for following up.
