### ISSUE TITLE
Error with CNVkit

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1799]
Hi Brad,

I'm experiencing the following error when trying cnvkit:
```
[2017-01-31T14:30Z] CNVkit coverage bin estimation
[2017-01-31T14:30Z] Estimated read length 76.0
[2017-01-31T14:31Z] Traceback (most recent call last):
[2017-01-31T14:31Z]   File "/home/galaxy/bcbio-dev/anaconda/bin/coverage_bin_size.py", line 158, in <module>
[2017-01-31T14:31Z]     fields = hybrid(rc_table, read_len, args.bam, targets, access)
[2017-01-31T14:31Z]   File "/home/galaxy/bcbio-dev/anaconda/bin/coverage_bin_size.py", line 58, in hybrid
[2017-01-31T14:31Z]     anti_table = anti_table.assign(mapped=anti_table.mapped - target_reads)
[2017-01-31T14:31Z]   File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 715, in wrapper
[2017-01-31T14:31Z]     result = wrap_results(safe_na_op(lvalues, rvalues))
[2017-01-31T14:31Z]   File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 676, in safe_na_op
[2017-01-31T14:31Z]     return na_op(lvalues, rvalues)
[2017-01-31T14:31Z]   File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 652, in na_op
[2017-01-31T14:31Z]     raise_on_error=True, **eval_kwargs)
[2017-01-31T14:31Z]   File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 210, in evaluate
[2017-01-31T14:31Z]     **eval_kwargs)
[2017-01-31T14:31Z]   File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 121, in _evaluate_numexpr
[2017-01-31T14:31Z]     result = _evaluate_standard(op, op_str, a, b, raise_on_error)
[2017-01-31T14:31Z]   File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 63, in _evaluate_standard
[2017-01-31T14:31Z]     return op(a, b)
[2017-01-31T14:31Z] ValueError: operands could not be broadcast together with shapes (124,) (166,)
[2017-01-31T14:31Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export TMPDIR=/tmp/bcbio/tmpaYGlVa && /home/galaxy/bcbio-dev/anaconda/bin/coverage_bin_size.py /home/projects/bcbio_annotation/test_runs/cnvseq/work/align/t
Estimated read length 76.0
Traceback (most recent call last):
  File "/home/galaxy/bcbio-dev/anaconda/bin/coverage_bin_size.py", line 158, in <module>
    fields = hybrid(rc_table, read_len, args.bam, targets, access)
  File "/home/galaxy/bcbio-dev/anaconda/bin/coverage_bin_size.py", line 58, in hybrid
    anti_table = anti_table.assign(mapped=anti_table.mapped - target_reads)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 715, in wrapper
    result = wrap_results(safe_na_op(lvalues, rvalues))
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 676, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 652, in na_op
    raise_on_error=True, **eval_kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 210, in evaluate
    **eval_kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 121, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b, raise_on_error)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 63, in _evaluate_standard
    return op(a, b)
ValueError: operands could not be broadcast together with shapes (124,) (166,)
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/galaxy/bcbio-dev/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
File "/home/galaxy/bcbio-dev/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)   
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 175, in variant2pipeline
    samples = structural.run(samples, run_parallel, "initial")
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 146, in run
    for xs in to_process.values()))
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 244, in detect_sv
    return structural.detect_sv(*args)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 165, in detect_sv
    for svdata in caller_fn(items):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 31, in run
    return _cnvkit_by_type(items, background)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 41, in _cnvkit_by_type
    return _run_cnvkit_single(items[0])
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 75, in _run_cnvkit_single
    ckouts = _run_cnvkit_shared([data], background)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 156, in _run_cnvkit_shared
    raw_work_dir, inputs[0])
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 320, in _cnvkit_targets
    bin_estimates = _cnvkit_coverage_bin_estimate(raw_target_bed, access_bed, cov_interval, work_dir, data)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 345, in _cnvkit_coverage_bin_estimate
    do.run(_prep_cmd(cmd, tx_out_file), "CNVkit coverage bin estimation")
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export TMPDIR=/tmp/bcbio/tmpaYGlVa && /home/galaxy/bcbio-dev/anaconda/bin/coverage_bin_size.py /home/projects/bcbio_annotation/test_runs/cnvseq/t
Estimated read length 76.0
Traceback (most recent call last):
  File "/home/galaxy/bcbio-dev/anaconda/bin/coverage_bin_size.py", line 158, in <module>
    fields = hybrid(rc_table, read_len, args.bam, targets, access)
  File "/home/galaxy/bcbio-dev/anaconda/bin/coverage_bin_size.py", line 58, in hybrid
    anti_table = anti_table.assign(mapped=anti_table.mapped - target_reads)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 715, in wrapper
    result = wrap_results(safe_na_op(lvalues, rvalues))
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 676, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/core/ops.py", line 652, in na_op
    raise_on_error=True, **eval_kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 210, in evaluate
    **eval_kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 121, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b, raise_on_error)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/pandas/computation/expressions.py", line 63, in _evaluate_standard
    return op(a, b)
ValueError: operands could not be broadcast together with shapes (124,) (166,)
' returned non-zero exit status 1
```

As always, I'm on the latest dev release.
Any idea what could be wrong?

Thanks!
M

**Comment by etal** [comment]
I think this error is occurring where the set of chromosomes/contigs in the list of targets (your panel) is compared to the chromosomes/contigs in the reference genome (the FASTA file of sequences, via the "access" BED file calculated on the fly within bcbio). If these two sets of contig names are different, the script does try to extract the shared subset to ensure they match, but it looks like I didn't cover every possibility.

Is there anything unusual about either of those files in your setup? Is this the human reference genome?

**Comment by matthdsm** [comment]
Hi @etal,

Thanks for chiming in. We're not doing anything out of the ordinary here, just testing a single end fastq mapped to hg38, everything default, no frills. I'm not really familiar with the inner workings of CNVkit, so I probably won't be of much help. I would be nice to get it to work though.

Thanks again
M

**Comment by etal** [comment]
So, the workaround here is to trim the target BED file to just the 24 canonical chromosomes -- it looks like you have either 124 or 166 targeted contigs in the BED file you used here.

I'll look into fixing the script to handle the original case.

**Comment by matthdsm** [comment]
Hi Eric, 

Thanks for following up on this! I'll give it a shot using an alternate bed file. Based of your comment, I suppose the issue is caused by the hg38 build, which has a lot of alternate contigs.
Looking forward to the fix!
Cheers,
M

**Comment by etal** [comment]
I've reproduced this issue and I'm working on a fix now.

**Comment by matthdsm** [comment]
Allright! Nice, thanks a lot!

M

**Comment by etal** [comment]
This fix is released with CNVkit version 0.8.5 now. The script `coverage_bin_size.py` will work as before, but with these bugs fixed. The new `autobin` command is a superset of that functionality, and will also generate target and antitarget BED files, so bcbio-nextgen probably won't need to parse the output table once the new command is adopted. No need to transition immediately to the new command, but the script is now deprecated and will be removed in the 0.9 release.

**Comment by matthdsm** [comment]
Hi @etal 

Great to hear, thanks!
@chapmanb how would you feel about about adopting the new command?

Thanks again,
M

**Comment by matthdsm** [comment]
CNVkit seems to work great since updating to the latest version. Thanks a lot @etal!

Cheers 
M
