### ISSUE TITLE
IOError: Failed to check fastq file sizes with: cat <(grabix grab

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1803]
Hi Brad,
I found the following error during alignment. Could you help me with the debugging?
Thanks!

[2017-02-03T22:03Z] ica1: Aligning lane 3_2017-02-03_7926_s-merged with bwa aligner
[2017-02-03T22:03Z] ica1: Unexpected error
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 199, in process_alignment
    return ipython.zip_args(apply(sample.process_alignment, *args))
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 116, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
    names, align_dir, data)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 118, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 142, in align_pipe
    ("bwa-mem" in dd.get_tools_off(data) or not _can_use_mem(fastq_file, data, min_size))):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 108, in _can_use_mem
    raise IOError("Failed to check fastq file sizes with: %s" % cmd.format(**locals()))
IOError: Failed to check fastq file sizes with: cat <(grabix grab /path/to/7926/work/align_prep/path.txt.gz 1 64) | head -n 8000000 | /path/to/bcbio/galaxy/../anaconda/bin/seqtk sample -s42 - 5000 | awk '{if(NR%4==2) print length($1)}' | sort | uniq -c

**Comment by chapmanb** [comment]
Sorry about the issue. If you run that command outside of bcbio:
```
cat <(grabix grab /path/to/7926/work/align_prep/path.txt.gz 1 64) | head -n 8000000 | /path/to/bcbio/galaxy/../anaconda/bin/seqtk sample -s42 - 5000 | awk '{if(NR%4==2) print length($1)}' | sort | uniq -c
```
what output do you see? bcbio is complaining because the output is empty but it's not clear why. You may have to deconstruct the command line to try and identify the root cause. Hope this helps to debug.
