### ISSUE TITLE
Merged Fastq.gz compression error

### ISSUE THREAD

**Issue by PatrickJReed** [chapmanb/bcbio-nextgen#1805]
I'm getting an error  right at the beginning of a run, when sequence files are being indexed i think.  Sample files were merged prior to run per documentation.  Since the merging step ran fine, could it be a compresson issue of the original file?

Here is error output from run:

[2017-02-07T03:55Z] System YAML configuration: /usr/local/share/bcbio/galaxy/bcbio_system.yaml
[2017-02-07T03:55Z] Resource requests: bwa, sambamba, samtools; memory: 4.00, 4.00, 4.00; cores: 64, 64, 64
[2017-02-07T03:55Z] Configuring 1 jobs to run, using 62 cores each with 251.8g of memory reserved for each job
[2017-02-07T03:55Z] Timing: organize samples
[2017-02-07T03:55Z] multiprocessing: organize_samples
[2017-02-07T03:55Z] Using input YAML configuration: /efs/SZ_Twins_Raw/SZ_Twins_SampleInfo-merged/config/SZ_Twins_SampleInfo-merged.yaml
[2017-02-07T03:55Z] Checking sample YAML configuration: /efs/SZ_Twins_Raw/SZ_Twins_SampleInfo-merged/config/SZ_Twins_SampleInfo-merged.yaml
[2017-02-07T03:55Z] Testing minimum versions of installed programs
[2017-02-07T03:55Z] Timing: alignment preparation
[2017-02-07T03:55Z] multiprocessing: prep_align_inputs
[2017-02-07T03:55Z] bgzip input file
[2017-02-07T04:08Z] bgzip input file
[2017-02-07T04:19Z] Resource requests: ; memory: 1.00; cores: 1
[2017-02-07T04:19Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-02-07T04:19Z] Index input with grabix: 1_NS_Blood_R1.fastq.gz
[2017-02-07T04:19Z] Index input with grabix: 1_NS_Blood_R2.fastq.gz
[2017-02-07T04:24Z] bgzip input file
[2017-02-07T04:48Z] bgzip input file
[2017-02-07T05:12Z] Resource requests: ; memory: 1.00; cores: 1
[2017-02-07T05:12Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-02-07T05:12Z] Index input with grabix: 1_NS_Fibro_R1.fastq.gz
[2017-02-07T05:12Z] Index input with grabix: 1_NS_Fibro_R2.fastq.gz
[2017-02-07T05:24Z] bgzip input file
[2017-02-07T05:35Z] bgzip input file
[2017-02-07T05:46Z] Resource requests: ; memory: 1.00; cores: 1
[2017-02-07T05:46Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-02-07T05:46Z] Index input with grabix: 1_SZ_Blood_R1.fastq.gz
[2017-02-07T05:46Z] Index input with grabix: 1_SZ_Blood_R2.fastq.gz
[2017-02-07T05:51Z] bgzip input file
[2017-02-07T06:16Z] bgzip input file
[2017-02-07T06:41Z] Resource requests: ; memory: 1.00; cores: 1
[2017-02-07T06:41Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-02-07T06:41Z] Index input with grabix: 1_SZ_Fibro_R1.fastq.gz
[2017-02-07T06:41Z] Index input with grabix: 1_SZ_Fibro_R2.fastq.gz
[2017-02-07T06:54Z] bgzip input file
[2017-02-07T07:06Z] bgzip input file
[2017-02-07T07:18Z] Resource requests: ; memory: 1.00; cores: 1
[2017-02-07T07:18Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-02-07T07:18Z] Index input with grabix: 2_NS_Blood_R1.fastq.gz
[2017-02-07T07:18Z] Index input with grabix: 2_NS_Blood_R2.fastq.gz
[2017-02-07T07:24Z] bgzip input file
[2017-02-07T07:32Z] 
[2017-02-07T07:32Z] gzip: /efs/SZ_Twins_Raw/merged/2_NS_Fibro_R1.fastq.gz: invalid compressed data--format violated
[2017-02-07T07:32Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; gunzip -c /efs/SZ_Twins_Raw/merged/2_NS_Fibro_R1.fastq.gz | /usr/local/share/bcbio/galaxy/../anaconda/bin/pbgzip -n 62  -c /dev/stdin > /efs/SZ_Twins_Raw/SZ_Twins_SampleInfo-merged/work/bcbiotx/tmpDNjHYy/2_NS_Fibro_R1.fastq.gz

gzip: /efs/SZ_Twins_Raw/merged/2_NS_Fibro_R1.fastq.gz: invalid compressed data--format violated
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 122, in variant2pipeline
    samples = run_parallel("prep_align_inputs", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 116, in prep_align_inputs
    return alignprep.create_inputs(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 45, in create_inputs
    data["files"] = _prep_grabix_indexes(data["files"], data["dirs"], data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 280, in _prep_grabix_indexes
    out = [_bgzip_from_fastq(d) for d in inputs]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 510, in _bgzip_from_fastq
    needs_bgzip, needs_gunzip, needs_convert)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 539, in _bgzip_file
    "bgzip input file")
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; gunzip -c /efs/SZ_Twins_Raw/merged/2_NS_Fibro_R1.fastq.gz | /usr/local/share/bcbio/galaxy/../anaconda/bin/pbgzip -n 62  -c /dev/stdin > /efs/SZ_Twins_Raw/SZ_Twins_SampleInfo-merged/work/bcbiotx/tmpDNjHYy/2_NS_Fibro_R1.fastq.gz

gzip: /efs/SZ_Twins_Raw/merged/2_NS_Fibro_R1.fastq.gz: invalid compressed data--format violated
' returned non-zero exit status 1

Here is output from sample merge:

[2017-02-06T21:09Z] skipping samplename, File doesn't exist.
[2017-02-06T21:09Z] Resource requests: sambamba, samtools; memory: 1.00; cores: 1, 1
[2017-02-06T21:09Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-02-06T21:09Z] Resource requests: sambamba, samtools; memory: 1.00; cores: 1, 1
[2017-02-06T21:09Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-02-06T21:09Z] Timing: prepare bcbio samples
[2017-02-06T21:09Z] multiprocessing: prepare_bcbio_samples
[2017-02-06T21:09Z] Preparing 3_NS_Blood files [['/efs/SZ_Twins_Raw/BloodDNA_3ns_S4_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/BloodDNA_3ns_S4_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/3_NS_Blood.fastq.gz.
[2017-02-06T21:09Z] Preparing 3_SZ_Fibro files [['/efs/SZ_Twins_Raw/LID115264_NoIndex_L001_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115264_NoIndex_L001_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115264_NoIndex_L002_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115264_NoIndex_L002_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38974_NoIndex_L005_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38974_NoIndex_L005_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/3_SZ_Fibro.fastq.gz.
[2017-02-06T21:09Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115264_NoIndex_L001_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115264_NoIndex_L002_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38974_NoIndex_L005_R1_001.fastq.gz']
[2017-02-06T21:17Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115264_NoIndex_L001_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115264_NoIndex_L002_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38974_NoIndex_L005_R2_001.fastq.gz']
[2017-02-06T21:25Z] Preparing 1_NS_Blood files [['/efs/SZ_Twins_Raw/BloodDNA_1ns_S2_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/BloodDNA_1ns_S2_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/1_NS_Blood.fastq.gz.
[2017-02-06T21:25Z] Preparing 6_NT1_Fibro files [['/efs/SZ_Twins_Raw/LID115266_NoIndex_L005_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115266_NoIndex_L005_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115266_NoIndex_L006_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115266_NoIndex_L006_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38976_NoIndex_L007_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38976_NoIndex_L007_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/6_NT1_Fibro.fastq.gz.
[2017-02-06T21:25Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115266_NoIndex_L005_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115266_NoIndex_L006_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38976_NoIndex_L007_R1_001.fastq.gz']
[2017-02-06T21:31Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115266_NoIndex_L005_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115266_NoIndex_L006_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38976_NoIndex_L007_R2_001.fastq.gz']
[2017-02-06T21:37Z] Preparing 2_NS_Fibro files [['/efs/SZ_Twins_Raw/LID115263_NoIndex_L007_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115263_NoIndex_L007_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115263_NoIndex_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115263_NoIndex_L008_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38973_NoIndex_L004_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38973_NoIndex_L004_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/2_NS_Fibro.fastq.gz.
[2017-02-06T21:37Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115263_NoIndex_L007_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115263_NoIndex_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38973_NoIndex_L004_R1_001.fastq.gz']
[2017-02-06T21:45Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115263_NoIndex_L007_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115263_NoIndex_L008_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38973_NoIndex_L004_R2_001.fastq.gz']
[2017-02-06T21:53Z] Preparing 3_SZ_Blood files [['/efs/SZ_Twins_Raw/BloodDNA_3s_S3_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/BloodDNA_3s_S3_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/3_SZ_Blood.fastq.gz.
[2017-02-06T21:53Z] Preparing 9_NT1_Fibro files [['/efs/SZ_Twins_Raw/LID115271_NoIndex_L005_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115271_NoIndex_L005_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115271_NoIndex_L006_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115271_NoIndex_L006_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38980_NoIndex_L003_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38980_NoIndex_L003_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/9_NT1_Fibro.fastq.gz.
[2017-02-06T21:53Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115271_NoIndex_L005_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115271_NoIndex_L006_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38980_NoIndex_L003_R1_001.fastq.gz']
[2017-02-06T22:01Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115271_NoIndex_L005_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115271_NoIndex_L006_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38980_NoIndex_L003_R2_001.fastq.gz']
[2017-02-06T22:11Z] Preparing 1_SZ_Blood files [['/efs/SZ_Twins_Raw/BloodDNA_1s_S1_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/BloodDNA_1s_S1_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/1_SZ_Blood.fastq.gz.
[2017-02-06T22:11Z] Preparing 9_NT2_Fibro files [['/efs/SZ_Twins_Raw/LID115272_NoIndex_L007_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115272_NoIndex_L007_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115272_NoIndex_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115272_NoIndex_L008_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38981_NoIndex_L004_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38981_NoIndex_L004_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/9_NT2_Fibro.fastq.gz.
[2017-02-06T22:11Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115272_NoIndex_L007_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115272_NoIndex_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38981_NoIndex_L004_R1_001.fastq.gz']
[2017-02-06T22:19Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115272_NoIndex_L007_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115272_NoIndex_L008_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38981_NoIndex_L004_R2_001.fastq.gz']
[2017-02-06T22:27Z] Preparing 1_SZ_Fibro files [['/efs/SZ_Twins_Raw/LID115260_NoIndex_L001_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115260_NoIndex_L001_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115260_NoIndex_L002_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115260_NoIndex_L002_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38970_NoIndex_L001_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38970_NoIndex_L001_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/1_SZ_Fibro.fastq.gz.
[2017-02-06T22:27Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115260_NoIndex_L001_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115260_NoIndex_L002_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38970_NoIndex_L001_R1_001.fastq.gz']
[2017-02-06T22:35Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115260_NoIndex_L001_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115260_NoIndex_L002_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38970_NoIndex_L001_R2_001.fastq.gz']
[2017-02-06T22:42Z] Preparing 8_NT2_Fibro files [['/efs/SZ_Twins_Raw/LID115269_NoIndex_L003_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115269_NoIndex_L003_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115269_NoIndex_L004_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115269_NoIndex_L004_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38979_NoIndex_L002_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38979_NoIndex_L002_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/8_NT2_Fibro.fastq.gz.
[2017-02-06T22:42Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115269_NoIndex_L003_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115269_NoIndex_L004_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38979_NoIndex_L002_R1_001.fastq.gz']
[2017-02-06T22:51Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115269_NoIndex_L003_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115269_NoIndex_L004_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38979_NoIndex_L002_R2_001.fastq.gz']
[2017-02-06T22:59Z] Preparing 6_NT1_Blood files [['/efs/SZ_Twins_Raw/BloodDNA_ctrl61_L007_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/BloodDNA_ctrl61_L007_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/6_NT1_Blood.fastq.gz.
[2017-02-06T22:59Z] Preparing 2_NS_Blood files [['/efs/SZ_Twins_Raw/BloodDNA_2nSCZ_L006_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/BloodDNA_2nSCZ_L006_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/2_NS_Blood.fastq.gz.
[2017-02-06T22:59Z] Preparing 3_NS_Fibro files [['/efs/SZ_Twins_Raw/LID115265_NoIndex_L003_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115265_NoIndex_L003_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115265_NoIndex_L004_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115265_NoIndex_L004_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38975_NoIndex_L006_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38975_NoIndex_L006_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/3_NS_Fibro.fastq.gz.
[2017-02-06T22:59Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115265_NoIndex_L003_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115265_NoIndex_L004_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38975_NoIndex_L006_R1_001.fastq.gz']
[2017-02-06T23:07Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115265_NoIndex_L003_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115265_NoIndex_L004_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38975_NoIndex_L006_R2_001.fastq.gz']
[2017-02-06T23:16Z] Preparing 6_NT2_Blood files [['/efs/SZ_Twins_Raw/BloodDNA_ctrl62_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/BloodDNA_ctrl62_L008_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/6_NT2_Blood.fastq.gz.
[2017-02-06T23:16Z] Preparing 2_SZ_Fibro files [['/efs/SZ_Twins_Raw/LID115262_NoIndex_L005_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115262_NoIndex_L005_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115262_NoIndex_L006_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115262_NoIndex_L006_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38972_NoIndex_L003_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38972_NoIndex_L003_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/2_SZ_Fibro.fastq.gz.
[2017-02-06T23:16Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115262_NoIndex_L005_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115262_NoIndex_L006_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38972_NoIndex_L003_R1_001.fastq.gz']
[2017-02-06T23:24Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115262_NoIndex_L005_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115262_NoIndex_L006_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38972_NoIndex_L003_R2_001.fastq.gz']
[2017-02-06T23:31Z] Preparing 1_NS_Fibro files [['/efs/SZ_Twins_Raw/LID115261_NoIndex_L003_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115261_NoIndex_L003_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115261_NoIndex_L004_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115261_NoIndex_L004_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38971_NoIndex_L002_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38971_NoIndex_L002_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/1_NS_Fibro.fastq.gz.
[2017-02-06T23:31Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115261_NoIndex_L003_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115261_NoIndex_L004_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38971_NoIndex_L002_R1_001.fastq.gz']
[2017-02-06T23:39Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115261_NoIndex_L003_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115261_NoIndex_L004_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38971_NoIndex_L002_R2_001.fastq.gz']
[2017-02-06T23:46Z] Preparing 2_SZ_Blood files [['/efs/SZ_Twins_Raw/HD1-3-8-TTAGGC_TTAGGC_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/HD1-3-8-TTAGGC_TTAGGC_L008_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/2_SZ_Blood.fastq.gz.
[2017-02-06T23:46Z] Preparing 8_NT1_Fibro files [['/efs/SZ_Twins_Raw/LID115268_NoIndex_L001_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115268_NoIndex_L001_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115268_NoIndex_L002_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115268_NoIndex_L002_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38978_NoIndex_L001_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38978_NoIndex_L001_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/8_NT1_Fibro.fastq.gz.
[2017-02-06T23:46Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115268_NoIndex_L001_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115268_NoIndex_L002_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38978_NoIndex_L001_R1_001.fastq.gz']
[2017-02-06T23:55Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115268_NoIndex_L001_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115268_NoIndex_L002_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38978_NoIndex_L001_R2_001.fastq.gz']
[2017-02-07T00:03Z] Preparing 6_NT2_Fibro files [['/efs/SZ_Twins_Raw/LID115267_NoIndex_L007_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115267_NoIndex_L007_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/LID115267_NoIndex_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115267_NoIndex_L008_R2_001.fastq.gz'], ['/efs/SZ_Twins_Raw/SID38977_NoIndex_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38977_NoIndex_L008_R2_001.fastq.gz']] to merge into /efs/SZ_Twins_Raw/merged/6_NT2_Fibro.fastq.gz.
[2017-02-07T00:03Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115267_NoIndex_L007_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115267_NoIndex_L008_R1_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38977_NoIndex_L008_R1_001.fastq.gz']
[2017-02-07T00:12Z] merge fastq files ['/efs/SZ_Twins_Raw/LID115267_NoIndex_L007_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/LID115267_NoIndex_L008_R2_001.fastq.gz', '/efs/SZ_Twins_Raw/SID38977_NoIndex_L008_R2_001.fastq.gz']
[2017-02-07T00:21Z] Preparing new csv: SZ_Twins_SampleInfo-merged.csv

**Comment by lpantano** [comment]
Hi @PatrickJReed 

sorry about this. Can you send me the logs files that should be inside the folder where you ran bcbio_prepare_samples.py?

something like this:

```
```

**Comment by PatrickJReed** [comment]
[bcbio-nextgen.log.txt](https://github.com/chapmanb/bcbio-nextgen/files/761272/bcbio-nextgen.log.txt)
[bcbio-nextgen-debug.log.txt](https://github.com/chapmanb/bcbio-nextgen/files/761270/bcbio-nextgen-debug.log.txt)
[bcbio-nextgen-commands.log.txt](https://github.com/chapmanb/bcbio-nextgen/files/761271/bcbio-nextgen-commands.log.txt)

**Comment by lpantano** [comment]
Thanks,

I don't see anything wrong in the merging step. 

I  would check the input of one sample that fails: `2_NS_Fibro_R1.fastq.gz`, so I would try to de-compress the files that were merged into this one: 

```
cat /efs/SZ_Twins_Raw/LID115263_NoIndex_L007_R1_001.fastq.gz /efs/SZ_Twins_Raw/LID115263_NoIndex_L008_R1_001.fastq.gz /efs/SZ_Twins_Raw/SID38973_NoIndex_L004_R1_001.fastq.gz > /efs/SZ_Twins_Raw/bcbiotx/tmpUGTluj/2_NS_Fibro_R1.fastq.gz
```

So you can check one by one, and if any gives an error then the culprits are the original files. If not, I would try to do the same with `2_NS_Fibro_R1.fastq.gz`, if that fails, but not the originals, we can try to see why `cat` is not working properly. If it doesn't fail, then something is happening with `bgzip`.

let me know what you get.

thanks!

**Comment by PatrickJReed** [comment]
Found it.  One of the input files was corrupted.
