### ISSUE TITLE
No --Dual_index option in fastqtransform 

### ISSUE THREAD

**Issue by asnavel2** [chapmanb/bcbio-nextgen#1810]
Hello,

I am trying to use the scRNA-seq pipeline to process data from a Harvard-inDrops-v3 run, but I have been getting an error from the fastqtransform process saying there is no --Dual_index option (full log below). To my knowledge, this is not an option specified in the yaml file, so I was wondering if it was a bug in the pipeline.

Thank you,
Andrew

[2017-02-09T05:21Z] System YAML configuration: /n/data2/bch/nrlgy/woolf/bcbio/galaxy/bcbio_system.yaml
[2017-02-09T05:21Z] Resource requests: picard; memory: 3.00; cores: 16
[2017-02-09T05:21Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2017-02-09T05:21Z] run local -- checkpoint passed: trimming
[2017-02-09T05:21Z] Timing: organize samples
[2017-02-09T05:21Z] multiprocessing: organize_samples
[2017-02-09T05:21Z] Using input YAML configuration: /n/data2/bch/nrlgy/woolf/inDrops/config/project1-templatev2.yaml
[2017-02-09T05:21Z] Checking sample YAML configuration: /n/data2/bch/nrlgy/woolf/inDrops/config/project1-templatev2.yaml
[2017-02-09T05:21Z] Testing minimum versions of installed programs
[2017-02-09T05:21Z] multiprocessing: prepare_sample
[2017-02-09T05:21Z] Preparing ARS23
[2017-02-09T05:21Z] Resource requests: samtools; memory: 3.00; cores: 16
[2017-02-09T05:21Z] Configuring 1 jobs to run, using 12 cores each with 36.1g of memory reserved for each job
[2017-02-09T05:21Z] Timing: singlecell-rnaseq
[2017-02-09T05:21Z] multiprocessing: run_umi_transform
[2017-02-09T05:21Z] Inserting UMI and barcode information into the read name of /n/data2/bch/nrlgy/woolf/22798808/Data/Intensities/BaseCalls/Undetermined_S0_L001_R1_001.fastq.gz
[2017-02-09T05:21Z] Error: no such option: --dual_index
[2017-02-09T05:21Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /n/data2/bch/nrlgy/woolf/bcbio/galaxy/../anaconda/bin/umis fastqtransform --dual_index  /n/data2/bch/nrlgy/woolf/inDrops/work/umis/harvard-indrop.json /n/data2/bch/nrlgy/woolf/22798808/Data/Intensities/BaseCalls/Undetermined_S0_L001_R1_001.fastq.gz /n/data2/bch/nrlgy/woolf/22798808/Data/Intensities/BaseCalls/Undetermined_S0_L001_R2_001.fastq.gz | seqtk seq -L 20 - | gzip > /n/data2/bch/nrlgy/woolf/inDrops/work/umis/tx/tmpZU9mgt/ARS23.umitransformed.fq.gz
Error: no such option: --dual_index
' returned non-zero exit status 2
Traceback (most recent call last):
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.0', 'bcbio_nextgen.py')
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 230, in <module>
    main(**kwargs)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 299, in singlecellrnaseqpipeline
    samples = rnaseq.singlecell_rnaseq(samples, run_parallel)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 21, in singlecell_rnaseq
    samples = run_parallel("run_umi_transform", samples)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 32, in run_umi_transform
    return umi.umi_transform(*args)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/umi.py", line 88, in umi_transform
    do.run(cmd.format(**locals()), message)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/n/data2/bch/nrlgy/woolf/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /n/data2/bch/nrlgy/woolf/bcbio/galaxy/../anaconda/bin/umis fastqtransform --dual_index  /n/data2/bch/nrlgy/woolf/inDrops/work/umis/harvard-indrop.json /n/data2/bch/nrlgy/woolf/22798808/Data/Intensities/BaseCalls/Undetermined_S0_L001_R1_001.fastq.gz /n/data2/bch/nrlgy/woolf/22798808/Data/Intensities/BaseCalls/Undetermined_S0_L001_R2_001.fastq.gz | seqtk seq -L 20 - | gzip > /n/data2/bch/nrlgy/woolf/inDrops/work/umis/tx/tmpZU9mgt/ARS23.umitransformed.fq.gz
Error: no such option: --dual_index
' returned non-zero exit status 2

**Comment by roryk** [comment]
Hi @asnavel2,

Sorry about the troubles. It looks like you have an older version of bcbio-nextgen, if you could upgrade the bcbio installation to the current version, this issue should go away.  Let us know if that does the trick.

**Comment by asnavel2** [comment]
Thank you for the quick response @roryk! Upgrading to the most recent stable version did not solve the issue, but switching to the development build did.

**Comment by roryk** [comment]
Great, glad that fixed it. Thanks for following up! Do you have the proper cellular barcode files for v3 along with the sample indexes? Having those is necessary to get v3 working.

**Comment by asnavel2** [comment]
I don't believe I do. I was trying to work out the V3 pipeline based off of a test yaml you posted about three weeks ago. So far it's just been trial and error. If you have any documentation for the inDrops-V3 pipeline I would greatly appreciate your help.

**Comment by roryk** [comment]
I attached the cellular barcode files you need, with an example sample configuration YAML file. If you can ask whoever made the libraries if they could tell you the indexes that go with your samples, if you take the reverse complement of those indexes that is what the sample-rc.txt file is; that sample-rc.txt file will only work with our particular sample. bcbio needs those so it knows which sample barcodes are valid.

There are two cellular barcode files, one is the reverse complement of the other. That is the pool of barcodes indrop v3 uses (I typo named the file v2).

[v2-example.zip](https://github.com/chapmanb/bcbio-nextgen/files/764976/v2-example.zip)

Hope that helps a bit.

**Comment by asnavel2** [comment]
Thank you for the files, they were a huge help. It looks like everything is running smoothly now.

Thanks again!
Andrew

**Comment by roryk** [comment]
Hi Andrew,

Score! Let me know if we can do anything else to get you going once you get to the downstream analysis.
