### ISSUE TITLE
Error with novoalign

### ISSUE THREAD

**Issue by rjsicko** [chapmanb/bcbio-nextgen#1819]
I got the following error when I tried running a variant calling pipeline with novoalign. I successfully ran the same sample with almost identical directory structure and yaml with bwa.

**Terminal**
````[2017-02-16T17:09Z] Testing minimum versions of installed programs
[2017-02-16T17:09Z] Timing: alignment preparation
[2017-02-16T17:09Z] multiprocessing: prep_align_inputs
[2017-02-16T17:09Z] bgzip input file
[2017-02-16T17:10Z] bgzip input file
[2017-02-16T17:10Z] Resource requests: ; memory: 1.00; cores: 1
[2017-02-16T17:10Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-02-16T17:10Z] Index input with grabix: 12_S12_L001_R1_001.fastq.gz
[2017-02-16T17:10Z] Index input with grabix: 12_S12_L001_R2_001.fastq.gz
[2017-02-16T17:11Z] multiprocessing: disambiguate_split
[2017-02-16T17:11Z] Timing: alignment
[2017-02-16T17:11Z] multiprocessing: process_alignment
[2017-02-16T17:11Z] Aligning lane NA12878-1 with novoalign aligner
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.1', 'bcbio_nextgen.py')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 1483, in run_script
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.1-py2.7.egg-info/scripts/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.1-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 127, in variant2pipeline
    samples = run_parallel("process_alignment", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 84, in process_alignment
    return sample.process_alignment(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 116, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
    names, align_dir, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 118, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/novoalign.py", line 61, in align_pipe
    out_file = os.path.join(align_dir, "{0}-sort.bam".format(dd.get_sample_name(data)))
````

**YAML**
````upload:
  dir: ../final
details:
  - files: [../input/12_S12_L001_R1_001.fastq.gz, ../input/12_S12_L001_R2_001.fastq.gz]
    description: NA12878-1
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: novoalign
      variantcaller: [freebayes, gatk-haplotype, samtools]
      mark_duplicates: false
      recalibrate: false
      realign: false
      coverage_interval: amplicon
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: ../input/v2-2_targets_sorted_no_chr.bed
      coverage: ../input/v2Exons_w_20bp_Padding.sorted.b37.bed
      svcaller: [cnvkit, seq2c]
      ensemble:
        numpass: 2
````

**Comment by chapmanb** [comment]
Thank you for the report and sorry about the issue. We were missing an import, triggering the error. I pushed a fix for this so if you update to the latest development version (`bcbio_nextgen.py upgrade -u development`) it should work cleanly. Thanks again.
