### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1834]
Hi,

I got an error processing fastq files with '(' or ')' in their filenames. I was running through a scheduler but I suspect the same error will occur if it's run local as well. The traceback is below.

[2017-02-27T04:44Z] bgzip input file
[2017-02-27T04:44Z] /bin/bash: -c: line 0: syntax error near unexpected token `('
[2017-02-27T04:44Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail;  /mnt/projects/dlho/tancrc/bcbio_pipeline/galaxy/../anaconda/bin/bgzip -c /mnt/projects/ngbhs/cirqseq/20170222_demuxumi/fastqfiles/CHB1461_095_(6050)_N.R1.fq > /mnt/projects/ngbhs/cirqseq/20170224_plasma/CHB1461_CHC1126/work/bcbiotx/tmpxUMZI6/CHB1461_095_(6050)_N.R1.fq.gz
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `set -o pipefail;  /mnt/projects/dlho/tancrc/bcbio_pipeline/galaxy/../anaconda/bin/bgzip -c /mnt/projects/ngbhs/cirqseq/20170222_demuxumi/fastqfiles/CHB1461_095_(6050)_N.R1.fq > /mnt/projects/ngbhs/cirqseq/20170224_plasma/CHB1461_CHC1126/work/bcbiotx/tmpxUMZI6/CHB1461_095_(6050)_N.R1.fq.gz'
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 122, in variant2pipeline
    samples = run_parallel("prep_align_inputs", samples)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 120, in prep_align_inputs
    return alignprep.create_inputs(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 45, in create_inputs
    data["files"] = _prep_grabix_indexes(data["files"], data["dirs"], data)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 280, in _prep_grabix_indexes
    out = [_bgzip_from_fastq(d) for d in inputs]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 510, in _bgzip_from_fastq
    needs_bgzip, needs_gunzip, needs_convert)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 539, in _bgzip_file
    "bgzip input file")
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail;  /mnt/projects/dlho/tancrc/bcbio_pipeline/galaxy/../anaconda/bin/bgzip -c /mnt/projects/ngbhs/cirqseq/20170222_demuxumi/fastqfiles/CHB1461_095_(6050)_N.R1.fq > /mnt/projects/ngbhs/cirqseq/20170224_plasma/CHB1461_CHC1126/work/bcbiotx/tmpxUMZI6/CHB1461_095_(6050)_N.R1.fq.gz
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `set -o pipefail;  /mnt/projects/dlho/tancrc/bcbio_pipeline/galaxy/../anaconda/bin/bgzip -c /mnt/projects/ngbhs/cirqseq/20170222_demuxumi/fastqfiles/CHB1461_095_(6050)_N.R1.fq > /mnt/projects/ngbhs/cirqseq/20170224_plasma/CHB1461_CHC1126/work/bcbiotx/tmpxUMZI6/CHB1461_095_(6050)_N.R1.fq.gz'
' returned non-zero exit status 1

While I can always rename the files, I thought I'll reflect this issue to you. Thanks!

**Comment by lpantano** [comment]
Hi @phu5ion 

If we change the name automatically, would it be that a problem? or you need to maintain that format? We can substitute `(` by `_` for instance.

thanks

**Comment by phu5ion** [comment]
Hi @lpantano ,

It's not a problem usually. Just happens in this case the fastq files didn't belong to me and I didn't have the liability to change them. I solved the problem through symlinks and changing the symlink filenames. Although I suspect this isn't a frequent issue just thought of highlighting it in case anyone has the same problem.
