### ISSUE TITLE
Differing types in somatic: and germline: configuration trigger exceptions

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1846]
Example:

```yaml
somatic: [mutect2, vardict]
germline: gatk-haplotype
```

The net result is that `run` in `resources.py` tries to do

```python
vcs = reduce(operator.add, vcs.values())
```

which means attempted concatenation  of `str` and `list`, at which point the interpreter complains loudly:

```python
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 145, in variant2pipeline
    multiplier=region.get_max_counts(samples), max_multicore=1) as run_parallel:
  File "/opt/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 43, in start
    max_multicore=max_multicore)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/resources.py", line 178, in calculate
    progs = _get_resource_programs(parallel.get("progs", []), algs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/resources.py", line 31, in _get_resource_programs
    if fn(algs):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/resources.py", line 59, in run
    vcs = reduce(operator.add, vcs.values())
TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by chapmanb** [comment]
Luca -- thanks for reporting this. I pushed a fix that will handle this case. You can work around it in the short term by specifying both as lists but the latest development version will handle it cleanly if you prefer to update.
