### ISSUE TITLE
bcbio_nextgen.py error after upgrade

### ISSUE THREAD

**Issue by eyalbenda** [chapmanb/bcbio-nextgen#1884]
I've upgrade to the latest stable version (1.0.2) and now can't run bcbio_nextgen.py without getting the following error:
ImportError: /usr/lib/liblapack.so.3: undefined symbol: gotoblas

Please see below a more complete log.

Any help would be greatly appreciated!

```

> multivac@multivac:~$ bcbio_nextgen.py upgrade -u stable --tools --dataTraceback (most recent call last):
>   File "/home/multivac/bcbio/tool/bin/bcbio_nextgen.py", line 4, in <module>
>     __import__('pkg_resources').run_script('bcbio-nextgen==1.0.2', 'bcbio_nextgen.py')
>   File "/home/multivac/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
>   File "/home/multivac/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
>   File "/home/multivac/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.2-py2.7.egg-info/scripts/bcbio_nextgen.py", line 35, in <module>
>     from bcbio.distributed import runfn, clargs
>   File "/home/multivac/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 15, in <module>
>     from bcbio.distributed import multitasks
>   File "/home/multivac/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 9, in <module>
>     from bcbio.rnaseq import (sailfish, rapmap, salmon, umi, kallisto)
>   File "/home/multivac/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/umi.py", line 8, in <module>
>     import scipy.io
>   File "/home/multivac/.local/lib/python2.7/site-packages/scipy/io/__init__.py", line 97, in <module>
>     from .matlab import loadmat, savemat, whosmat, byteordercodes
>   File "/home/multivac/.local/lib/python2.7/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
>     from .mio import loadmat, savemat, whosmat
>   File "/home/multivac/.local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 12, in <module>
>     from .miobase import get_matfile_version, docfiller
>   File "/home/multivac/.local/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 22, in <module>
>     from scipy.misc import doccer
>   File "/home/multivac/.local/lib/python2.7/site-packages/scipy/misc/__init__.py", line 51, in <module>
>     from scipy.special import comb, factorial, factorial2, factorialk
>   File "/home/multivac/.local/lib/python2.7/site-packages/scipy/special/__init__.py", line 627, in <module>
>     from ._ufuncs import *
> ImportError: /usr/lib/liblapack.so.3: undefined symbol: gotoblas
> 

```

**Comment by chapmanb** [comment]
Eyal;
It looks like you have a `.local` directory injecting incompatible python libraries in with bcbio:
```
/home/multivac/.local
```
Sorry we don't have a way to exclude python from looking into that directory but if you remove it that should avoid the incompatibilities and get things running again. Hope this helps.

**Comment by eyalbenda** [comment]
Thanks! wonder why it started acting up only after the update. I'll try and let you know

**Comment by eyalbenda** [comment]
Ok, deleted the .local directory and it fixed the issue. I thought bcbio used it's own python distribution to circumvent such issues. Anyway, thanks for the fast help!
