### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jich-MCTP** [chapmanb/bcbio-nextgen#1893]
When I install bcbio-nextgen, 
python /bcbio/bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --genomes hg38-noalt --aligners bwa --aligners bowtie2
I get the error message:
...
[localhost] local: ln -sf ../seq/hg38-noalt.fa /usr/local/share/bcbio/genomes/Hsapiens/hg38-noalt/bowtie2/hg38-noalt.fa
[localhost] local: mkdir -p /usr/local/share/bcbio/galaxy/tool-data
[localhost] local: touch sam_fa_indices.loc
[localhost] local: echo 'index  hg38-noalt      /usr/local/share/bcbio/genomes/Hsapiens/hg38-noalt/seq/hg38-noalt.fa' >> "$(echo sam_fa_indices.loc)"
[localhost] local: touch picard_index.loc
[localhost] local: echo 'hg38-noalt     hg38-noalt      Human (hg38) without alternative alleles        /usr/local/share/bcbio/genomes/Hsapiens/hg38-noalt/seq/hg38-noalt.fa' >> "$(echo picard_index.loc)"
[localhost] local: touch gatk_sorted_picard_index.loc
[localhost] local: echo 'hg38-noalt     hg38-noalt      Human (hg38) without alternative alleles        /usr/local/share/bcbio/genomes/Hsapiens/hg38-noalt/seq/hg38-noalt.fa' >> "$(echo gatk_sorted_picard_index.loc)"
[localhost] local: touch bowtie2_indices.loc
[localhost] local: echo 'hg38-noalt     hg38-noalt      Human (hg38) without alternative alleles        /usr/local/share/bcbio/genomes/Hsapiens/hg38-noalt/bowtie2/hg38-noalt' >> "$(echo bowtie2_indices.loc)"
[localhost] local: touch bwa_index.loc
[localhost] local: echo 'hg38-noalt     hg38-noalt      Human (hg38) without alternative alleles        /usr/local/share/bcbio/genomes/Hsapiens/hg38-noalt/bwa/hg38-noalt.fa' >> "$(echo bwa_index.loc)"
[localhost] local: ln -sf ../seq/hg38-noalt.fa.fai
Updating hg38-noalt genome resources configuration
Installing snpEff database GRCh38.86 in /usr/local/share/bcbio/genomes/Hsapiens/hg38-noalt/snpeff
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.2', 'bcbio_nextgen.py')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.2-py2.7.egg-info/scripts/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 95, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
    _upgrade_snpeff_data(s["fabricrc_overrides"]["galaxy_home"], args, remotes)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 359, in _upgrade_snpeff_data
    subprocess.check_call(["unzip", dl_file])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
Installing data and third party dependencies
Traceback (most recent call last):
  File "/bcbio/bcbio_nextgen_install.py", line 248, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "/bcbio/bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/local/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'hg38-noalt', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Jin;
Thanks much for the report, it looks from the traceback like your machine is missing `unzip`:
```
subprocess.check_call(["unzip", dl_file])
[...]
OSError: [Errno 2] No such file or directory
```
bcbio installs most tools but not some standard filesystem utilities like unzip. We list the required external system requirements here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

Unrelated to your error, we don't recommend using hg38-noalt and instead prefer using hg38. We were planning to remove the hg38-noalt option soon. Is there a reason you prefer this over the full hg38?

Hopefully after installing unzip things will work cleanly for you.

**Comment by jich-MCTP** [comment]
It works. 
Thank you for the help!
