### ISSUE TITLE
run "ggd-run.sh" error when upgrade new genome

### ISSUE THREAD

**Issue by jich-MCTP** [chapmanb/bcbio-nextgen#1901]
Hi, 
When I want to add one new genome reference with the command line:
bcbio_nextgen.py upgrade  --data --genome hg38 --aligners bwa --aligners bowtie2

I get the error:
tar: cancer/az-cancer-panel.bed.gz.tbi: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: cancer/az300.bed.gz.tbi: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: cancer/az-cancer-panel.bed.gz: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: cancer/az300.bed.gz: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: cancer/az300-with-fusion.bed.gz: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: cancer/civic-2016-02-15.bed.gz.tbi: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: cancer/az300-with-fusion.bed.gz.tbi: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: cancer/civic-2016-02-15.bed.gz: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: cancer: Cannot change ownership to uid 1001, gid 1001: Operation not permitted
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 95, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 290, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 339, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 467, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 814, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file, gid)
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 31, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 63, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 2

I re-run "bash /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/txtmp/ggd-run.sh". There is no any problem. But when re-run "bcbio_nextgen.py upgrade" get the same error again. 

No matter I deleted "tmpbcbio-install", the same error comes.

Could you please help me to find where is wrong?

Thanks!

**Comment by chapmanb** [comment]
Jin;
Sorry about the issues and thanks for the detailed report. What type of environment are you trying to install bcbio in? Is this a VM or Docker container? I suspect that there is some kind of issue where the mounted filesystem permissions appear to be incompatible with your privileges inside the container/VM or there is some kind of user UID incompatibility.

Practically, my best recommendation is to not run bcbio installations as the root user, and instead as an unprivileged user. If you manually chmod/chown the directory you're installing bcbio into prior to running, then there is no need to run the install/upgrade process as root. That should prevent tar trying to do any user ID switching (`--same-owner` behavior in tar) and avoid the underlying issue. Hope this fixes it for you.

**Comment by jich-MCTP** [comment]
Thank you for quick reply!! I am running bcbio in the Docker container which is created from Dockerfile in github source codes. 
I will try your recommendation today and will let you know the result!

Thanks!

**Comment by jich-MCTP** [comment]
I run with an unprivileged user and it works. Thank your for the help!!
I will close this issue!.
