### ISSUE TITLE
Setup of custom genome fails

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#1904]
Hi,

I want to install a custom genome into bcbio and try to set it up like this:

`bcbio_setup_genome.py --cores 24 --fasta Virus.fa --gff3 Virus.gff3 --index star --name VirusA --build VirA`

However, this command as well as any possible variation thereof only results in the output of the help text of the bcbio_setup_genome.py command (equivalent to bcbio_setup_genome.py -h) on the command line without any additional error messages.
Am I missing something here?

Thanks a lot!

**Comment by chapmanb** [comment]
Thanks for using bcbio and sorry about the confusing messages. I believe the issue is that `--gff3` is a flag, so the `Virus.gff3` argument then ends up as a bare argument. If you add `-g` (or `--gtf`) before it that should fix the problem:
```
bcbio_setup_genome.py --cores 24 --fasta Virus.fa --gff3 -g Virus.gff3 --index star --name VirusA --build VirA
```
Hope this helps.

**Comment by luckylynx** [comment]
That worked!

However, now I get the following error:

```
Creating the star index.
Traceback (most recent call last):
  File "/bioinformatics/tooldir/bin/bcbio_setup_genome.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.2', 'bcbio_setup_genome.py')
  File "/bioinformatics/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/bioinformatics/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/bioinformatics/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.2-py2.7.egg-info/scripts/bcbio_setup_genome.py", line 279, in <module>
    indexed[index] = index_fn(fasta_file)
  File "/bioinformatics/additionaltools/cloudbiolinux/cloudbio/biodata/genomes.py", line 426, in decorator
    return func(*args, **kwargs)
  File "/bioinformatics/additionaltools/cloudbiolinux/cloudbio/biodata/genomes.py", line 689, in _index_star
    Nbases = int(round(min(14, log(GenomeLength, 2)/2 - 2), 0))
ValueError: math domain error
```

**Comment by lpantano** [comment]
Hi @luckylynx 

This is a problem when guessing the right value depending on genome size. How long is the that genome? Maybe you can try another aligner since it's a small genome, like bowtie2, meanwhile we try to solve this. Can you share the virus sequence or how big the file is?

**Comment by leiendeckerlu** [comment]
Ah, I see. The genome is about 5.5 kbp, a polyomavirus, so quite small.

I will try to use another aligner. 
Another solution might be to create a custom genome consisting of a fusion of e.g. hg19 and the viral genome and align my reads against this, should probably also work...?!

**Comment by lpantano** [comment]
yes, that last option should work as well if there is human genome in your samples as well.
