### ISSUE TITLE
[E::bwa_idx_load_from_disk] fail to locate the index files

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1906]
Hi Brad, I am getting this new error. It seems bwa index are not found. bwa look for bcbio/genomes/Dmelanogaster/dm3/seq/dm3  instead of bcbio/genomes/Dmelanogaster/dm3/seq/dm3.fa

do you have any suggestion on what is wrong?
I have add the sam_fa_indices.loc  and my dm3/seq folder
Thanks!
```
[2017-04-20T21:53Z] bwa mem alignment from fastq: H2AK119Ub
[2017-04-20T21:53Z] [E::bwa_idx_load_from_disk] fail to locate the index files
[2017-04-20T21:53Z] [V] 0	02381299	MemUsage(size=469.824,rss=7.51562,peak=469.824)	AutoArrayMemUsage(memusage=337.775,peakmemusage=337.775,maxmem=1.75922e+13)	final
[2017-04-20T21:53Z] [V] flushing read ends lists...done.
[2017-04-20T21:53Z] [V] merging read ends lists/computing duplicates...done, time 01:00103300
[2017-04-20T21:53Z] [V] num dups 0
[2017-04-20T21:53Z] # bamsormadup
[2017-04-20T21:53Z] 
[2017-04-20T21:53Z] ##METRICS
[2017-04-20T21:53Z] LIBRARY	UNPAIRED_READS_EXAMINED	READ_PAIRS_EXAMINED	UNMAPPED_READS	UNPAIRED_READ_DUPLICATES	READ_PAIR_DUPLICATES	READ_PAIR_OPTICAL_DUPLICATES	PERCENT_DUPLICATION	ESTIMATED_LIBRARY_SIZE
[2017-04-20T21:53Z] [V] blocks generated in time 03:02835600
[2017-04-20T21:53Z] [V] number of blocks to be merged is 1 using 8 blocks per input with block size 1048576
[2017-04-20T21:53Z] [V] 0
[2017-04-20T21:53Z] [D]	md5	d0ca9d0e2a7dcff612aa107f704ad5cd
[2017-04-20T21:53Z] [V] checksum ok
[2017-04-20T21:53Z] [V] blocks merged in time 01:02554400
[2017-04-20T21:53Z] [V] run time 04:05429300 (4.05429 s)	MemUsage(size=164.703,rss=23.2578,peak=1188.72)
[2017-04-20T21:53Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /bcbio/galaxy/../anaconda/bin/bwa mem -p -c 250 -M -t 1  -R '@RG\tID:K562-K700E_H2AK119Ub\tPL:illumina\tPU:1_2017-04-19_spike_in\tSM:K562-K700E_H2AK119Ub' -v 1 /cbio/ski/abdelwao/nobackup/pastore/bcbio/genomes/Dmelanogaster/dm3/seq/dm3 /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Daichi_Inoue/H2AK119Ub/h2ak119ub/final/K562-K700E_H2AK119Ub/spike_in/work/trimmed/3_01H1_004UMSKCC_K562-K700E_H2AK119Ub_hs-dm_i80_K562-K700E_H2AK119Ub.trimmed.fastq.gz   | bamsormadup inputformat=sam threads=1 tmpfile=/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Daichi_Inoue/H2AK119Ub/h2ak119ub/final/K562-K700E_H2AK119Ub/spike_in/work/bcbiotx/tmpYwJ_FU/K562-K700E_H2AK119Ub-sort-sorttmp-markdup SO=coordinate indexfilename=/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Daichi_Inoue/H2AK119Ub/h2ak119ub/final/K562-K700E_H2AK119Ub/spike_in/work/bcbiotx/tmpYwJ_FU/K562-K700E_H2AK119Ub-sort.bam.bai > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Daichi_Inoue/H2AK119Ub/h2ak119ub/final/K562-K700E_H2AK119Ub/spike_in/work/bcbiotx/tmpYwJ_FU/K562-K700E_H2AK119Ub-sort.bam
[E::bwa_idx_load_from_disk] fail to locate the index files
```

```
ls bcbio/genomes/Dmelanogaster/dm3/seq
chromFa.tar.gz  dm3.dict  dm3.fa  dm3.fa.amb  dm3.fa.ann  dm3.fa.bwt  dm3.fa.fai  dm3.fa.pac  dm3.fa.sa  dm3-resources.yaml
```
```
cat bcbio/galaxy/tool-data/sam_fa_indices.loc 
index	GRCh37	/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
index	hg19	/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa
index	mm9	/bcbio/genomes/Mmusculus/mm9/seq/mm9.fa
index	mm10	/bcbio/genomes/Mmusculus/mm10/seq/mm10.fa
index	dm3	/bcbio/genomes/Dmelanogaster/dm3/seq/dm3.fa
```

**Comment by chapmanb** [comment]
Alessandro;
Sorry about the issues and thank you for the detailed report. It's a bit strange that bcbio is looking in the `seq` directory and the bwa indices are there rather than in a separate `bwa` directory, which is how this is normally setup. Is this a custom install, or how did you add `dm3`?

bcbio gets the bwa location from `galaxy/tool-data/bwa_index.loc`, not `sam_fa_indices.loc` so independent of how the install happened, you can manually adjust the references there to point at the right place to where they actually exist. Hopefully changing it there will get things working for you.

**Comment by apastore** [comment]
thanks!
no idea why my bwa_index.loc was missing !
fix it
