### ISSUE TITLE
CNVkit fails when asking to call SVs in a region

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1909]
Hello, bcbio developers and users!

Thanks for the excellent framework!

I'm trying to calculate SVs in the linkage region for WGS.

config file:
```
details:
- algorithm:
    aligner: false
    effects: false
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - svplots
    - qualimap
    variantcaller: false
    variant_regions: /hpf/largeprojects/ccmbio/naumenko/project_muscular/62_AF_S5_SV/config/region.bed
    coverage_interval: /hpf/largeprojects/ccmbio/naumenko/project_muscular/62_AF_S5_SV/config/region.bed
    svcaller:
    - cnvkit
    - seq2c
    - delly
    - battenberg
  analysis: variant2
  description: 62_AF_S5
  files:
  - /hpf/largeprojects/ccmbio/naumenko/project_muscular/62_AF_S5_SV/input/62_AF_S5-ready.bam
  genome_build: GRCh37
fc_date: '2017-01-25'
fc_name: muscle2_62-AF
resources:
  default:
    cores: 5
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final
```

bed file:
```
19	1400000	9100000
```

I've gotten an error:
```
[2017-04-21T07:05Z] Annotate BED file with gene info
[2017-04-21T07:05Z] sort: write failed: standard output: Broken pipe
[2017-04-21T07:05Z] sort: write error
Traceback (most recent call last):
  File "/home/naumenko/work/tools/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/home/naumenko/work/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 177, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 169, in run
    for xs in to_process.values()))
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 278, in detect_sv
    return structural.detect_sv(*args)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 188, in detect_sv
    for svdata in caller_fn(items):
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 33, in run
    return _cnvkit_by_type(items, background)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 43, in _cnvkit_by_type
    return _run_cnvkit_single(items[0])
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 77, in _run_cnvkit_single
    ckouts = _run_cnvkit_shared([data], background)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 182, in _run_cnvkit_shared
    raw_work_dir, inputs[0])
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 356, in _cnvkit_targets
    bin_estimates = _cnvkit_coverage_bin_estimate(raw_target_bed, access_bed, cov_interval, work_dir, data)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 384, in _cnvkit_coverage_bin_estimate
    "-m", method_map[cov_interval], "-t", raw_target_bed,
KeyError: '/hpf/largeprojects/ccmbio/naumenko/project_muscular/62_AF_S5_SV/config/region.bed'
END:  Fri Apr 21 03:05:58 EDT 2017
```

Could you please help to figure out, what is wrong?

Sergey

**Comment by chapmanb** [comment]
Sergey;
`coverage_interval` in your YAML file should be either `genome`, `amplicon` or `regional`, not a BED file:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#coverage-information

Generally, bcbio can calculate this for you automatically and you don't need to specify it. You might have meant to specify `coverage` with this BED file:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#analysis-regions

Hope this helps.
