### ISSUE TITLE
ipython issue

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1925]
Hi, when I ran bcbio with ipython parallel, I found that the program just stuck in the following log stage,

[2017-05-08T15:25Z] ica1: System YAML configuration: /path/to/bcbio/galaxy/bcbio_system.yaml
[2017-05-08T15:25Z] ica1: Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2017-05-08T15:25Z] ica1: Configuring 13 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[ProfileCreate] Generating default config file: u'/path/to/work/log/ipython/ipython_config.py'
[ProfileCreate] Generating default config file: u'/path/to/work/log/ipython/ipython_kernel_config.py'
[ProfileCreate] Generating default config file: u'/path/to/work/log/ipython/ipcontroller_config.py'
[ProfileCreate] Generating default config file: u'/path/to/work/log/ipython/ipengine_config.py'
[ProfileCreate] Generating default config file: u'/path/to/work/log/ipython/ipcluster_config.py'
2017-05-08 10:25:35.862 [IPClusterStart] Using existing profile dir: u'/path/to/work/log/ipython'
2017-05-08 10:25:35.862 [IPClusterStart] Searching path [u'/path/to/work', u'/path/to/work/log/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2017-05-08 10:25:35.862 [IPClusterStart] Attempting to load config file: ipython_config.py
2017-05-08 10:25:35.862 [IPClusterStart] Looking for ipython_config in /etc/ipython
2017-05-08 10:25:35.863 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2017-05-08 10:25:35.863 [IPClusterStart] Looking for ipython_config in /path/to/work/log/ipython
2017-05-08 10:25:35.863 [IPClusterStart] Loaded config file: /path/to/log/ipython/ipython_config.py
2017-05-08 10:25:35.863 [IPClusterStart] Looking for ipython_config in /path/to/work
2017-05-08 10:25:35.864 [IPClusterStart] Attempting to load config file: ipcluster_9181c4bb_63a3_4420_9882_dc45721b936a_config.py
2017-05-08 10:25:35.864 [IPClusterStart] Looking for ipcontroller_config in /etc/ipython
2017-05-08 10:25:35.864 [IPClusterStart] Looking for ipcontroller_config in /usr/local/etc/ipython
2017-05-08 10:25:35.864 [IPClusterStart] Looking for ipcontroller_config in /path/to/work/log/ipython
2017-05-08 10:25:35.865 [IPClusterStart] Loaded config file: /path/to/work/log/ipython/ipcontroller_config.py
2017-05-08 10:25:35.865 [IPClusterStart] Looking for ipcontroller_config in /path/to/work
2017-05-08 10:25:35.865 [IPClusterStart] Attempting to load config file: ipcluster_9181c4bb_63a3_4420_9882_dc45721b936a_config.py
2017-05-08 10:25:35.866 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2017-05-08 10:25:35.866 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2017-05-08 10:25:35.866 [IPClusterStart] Looking for ipengine_config in /path/to/work/log/ipython
2017-05-08 10:25:35.866 [IPClusterStart] Loaded config file: /path/to/log/ipython/ipengine_config.py
2017-05-08 10:25:35.866 [IPClusterStart] Looking for ipengine_config in /path/to/work
2017-05-08 10:25:35.867 [IPClusterStart] Attempting to load config file: ipcluster_9181c4bb_63a3_4420_9882_dc45721b936a_config.py
2017-05-08 10:25:35.867 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2017-05-08 10:25:35.867 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2017-05-08 10:25:35.867 [IPClusterStart] Looking for ipcluster_config in /path/to/work/log/ipython
2017-05-08 10:25:35.868 [IPClusterStart] Loaded config file: /path/to/work/log/ipython/ipcluster_config.py
2017-05-08 10:25:35.868 [IPClusterStart] Looking for ipcluster_config in /path/to/work

After further checking, I found the following error in /path/to/work/log/ipython/log/ipcluster-9337b06d-1b2d-4fd9-b7fb-14c0833bca12-23613.log,

2017-05-08 12:48:13.941 [IPClusterStart] Starting ipcluster with [daemon=True]
2017-05-08 12:48:13.946 [IPClusterStart] Creating pid file: /path/to/work/log/ipython/pid/ipcluster-9337b06d-1b2d-4fd9-b7fb-14c0833bca12.pid
2017-05-08 12:48:13.947 [IPClusterStart] Starting Controller with cluster_helper.cluster.BcbioSLURMControllerLauncher
2017-05-08 12:48:13.947 [IPClusterStart] Starting BcbioSLURMControllerLauncher: ['sbatch', u'./SLURM_controller29aef5c8-bd49-4137-b6bd-3d8b4100ed59']
2017-05-08 12:48:13.948 [IPClusterStart] adding PBS queue settings to batch script
2017-05-08 12:48:13.948 [IPClusterStart] Writing batch script: ./SLURM_controller29aef5c8-bd49-4137-b6bd-3d8b4100ed59
2017-05-08 12:48:13.959 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 503, in start_controller
    self.controller_launcher.start()
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 506, in start
    return super(BcbioSLURMControllerLauncher, self).start(1)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1151, in start
    output = check_output(self.args, env=os.environ)
  File "/path/to/bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['sbatch', u'./SLURM_controller29aef5c8-bd49-4137-b6bd-3d8b4100ed59']' returned non-zero exit status 1

From the strace, it seems that it’s trying to open up configuration file that doesn’t exist:
stat("/path/to/work/log/ipython/security/ipcontroller-9181c4bb-63a3-4420-9882-dc45721b936a-client.json", 0x7ffd41900600) = -1 ENOENT (No such file or directory)
The program is looping through the same section again and again

Could you help me with debugging? 

Thanks!

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the detailed report. It appears as if the created batch script is not working on your cluster for some reason. My suggestion would be to run:
```
sbatch ./SLURM_controller29aef5c8-bd49-4137-b6bd-3d8b4100ed5
```
outside of bcbio and it'll hopefully give a useful message about what it's failing. If you're still stuck after seeing this error happy to provide more specific information about what might be happening. Hope this helps.

**Comment by pengxiao78** [comment]
It's still stuck and I found the following info in /nebraska/inbre/home/peng.xiao/cowan/26th_s/work/log/ipython/log/ipcontroller-c399aec8-9400-4acb-9382-fb5a96843a88-35115.log, and it keeps going.

Thanks!

2017-05-10 09:27:36.272 [VMFixIPControllerApp] Hub listening on tcp://*:53766 for registration.
2017-05-10 09:27:36.274 [VMFixIPControllerApp] Hub using DB backend: 'NoDB'
2017-05-10 09:27:36.531 [VMFixIPControllerApp] hub::created hub
2017-05-10 09:27:36.534 [VMFixIPControllerApp] writing connection info to /path/to/work/log/ipython/security/ipcontroller-c399aec8-9400-4acb-9382-fb5a96843a88-client.json
2017-05-10 09:27:36.540 [VMFixIPControllerApp] writing connection info to /path/to/work/log/ipython/security/ipcontroller-c399aec8-9400-4acb-9382-fb5a96843a88-engine.json
2017-05-10 09:27:36.542 [VMFixIPControllerApp] task::using Python leastload Task scheduler
2017-05-10 09:27:36.542 [VMFixIPControllerApp] Heartmonitor started
2017-05-10 09:27:36.551 [VMFixIPControllerApp] Creating pid file: /path/to/work/log/ipython/pid/ipcontroller-c399aec8-9400-4acb-9382-fb5a96843a88.pid
2017-05-10 09:27:36.568 [VMFixIPControllerApp] client::client '\x00k\x8bEg' requested 'connection_request'
2017-05-10 09:27:36.568 [VMFixIPControllerApp] client::client ['\x00k\x8bEg'] connected
2017-05-10 09:27:37.585 [VMFixIPControllerApp] client::client '\x00k\x8bEh' requested 'connection_request'
2017-05-10 09:27:37.585 [VMFixIPControllerApp] client::client ['\x00k\x8bEh'] connected
2017-05-10 09:27:42.608 [VMFixIPControllerApp] client::client '\x00k\x8bEi' requested 'connection_request'
2017-05-10 09:27:42.608 [VMFixIPControllerApp] client::client ['\x00k\x8bEi'] connected
2017-05-10 09:27:47.625 [VMFixIPControllerApp] client::client '\x00k\x8bEj' requested 'connection_request'
2017-05-10 09:27:47.625 [VMFixIPControllerApp] client::client ['\x00k\x8bEj'] connected
2017-05-10 09:27:52.642 [VMFixIPControllerApp] client::client '\x00k\x8bEk' requested 'connection_request'
2017-05-10 09:27:52.642 [VMFixIPControllerApp] client::client ['\x00k\x8bEk'] connected
2017-05-10 09:27:57.653 [VMFixIPControllerApp] client::client '\x00k\x8bEl' requested 'connection_request'
2017-05-10 09:27:57.653 [VMFixIPControllerApp] client::client ['\x00k\x8bEl'] connected
2017-05-10 09:28:02.667 [VMFixIPControllerApp] client::client '\x00k\x8bEm' requested 'connection_request'
2017-05-10 09:28:02.667 [VMFixIPControllerApp] client::client ['\x00k\x8bEm'] connected
2017-05-10 09:28:07.681 [VMFixIPControllerApp] client::client '\x00k\x8bEn' requested 'connection_request'
2017-05-10 09:28:07.681 [VMFixIPControllerApp] client::client ['\x00k\x8bEn'] connected
2017-05-10 09:28:12.698 [VMFixIPControllerApp] client::client '\x00k\x8bEo' requested 'connection_request'
2017-05-10 09:28:12.698 [VMFixIPControllerApp] client::client ['\x00k\x8bEo'] connected
2017-05-10 09:28:17.711 [VMFixIPControllerApp] client::client '\x00k\x8bEp' requested 'connection_request'
2017-05-10 09:28:17.711 [VMFixIPControllerApp] client::client ['\x00k\x8bEp'] connected
2017-05-10 09:28:22.726 [VMFixIPControllerApp] client::client '\x00k\x8bEq' requested 'connection_request'
2017-05-10 09:28:22.726 [VMFixIPControllerApp] client::client ['\x00k\x8bEq'] connected
2017-05-10 09:28:27.740 [VMFixIPControllerApp] client::client '\x00k\x8bEr' requested 'connection_request'
2017-05-10 09:28:27.740 [VMFixIPControllerApp] client::client ['\x00k\x8bEr'] connected
2017-05-10 09:28:32.754 [VMFixIPControllerApp] client::client '\x00k\x8bEs' requested 'connection_request'
2017-05-10 09:28:32.754 [VMFixIPControllerApp] client::client ['\x00k\x8bEs'] connected
2017-05-10 09:28:37.769 [VMFixIPControllerApp] client::client '\x00k\x8bEt' requested 'connection_request'
2017-05-10 09:28:37.769 [VMFixIPControllerApp] client::client ['\x00k\x8bEt'] connected
2017-05-10 09:28:42.786 [VMFixIPControllerApp] client::client '\x00k\x8bEu' requested 'connection_request'
2017-05-10 09:28:42.786 [VMFixIPControllerApp] client::client ['\x00k\x8bEu'] connected
2017-05-10 09:28:47.799 [VMFixIPControllerApp] client::client '\x00k\x8bEv' requested 'connection_request'
2017-05-10 09:28:47.799 [VMFixIPControllerApp] client::client ['\x00k\x8bEv'] connected
2017-05-10 09:28:52.815 [VMFixIPControllerApp] client::client '\x00k\x8bEw' requested 'connection_request'
2017-05-10 09:28:52.815 [VMFixIPControllerApp] client::client ['\x00k\x8bEw'] connected
2017-05-10 09:28:57.827 [VMFixIPControllerApp] client::client '\x00k\x8bEx' requested 'connection_request'
2017-05-10 09:28:57.828 [VMFixIPControllerApp] client::client ['\x00k\x8bEx'] connected
2017-05-10 09:29:02.844 [VMFixIPControllerApp] client::client '\x00k\x8bEy' requested 'connection_request'
2017-05-10 09:29:02.845 [VMFixIPControllerApp] client::client ['\x00k\x8bEy'] connected
2017-05-10 09:29:07.858 [VMFixIPControllerApp] client::client '\x00k\x8bEz' requested 'connection_request'
2017-05-10 09:29:07.858 [VMFixIPControllerApp] client::client ['\x00k\x8bEz'] connected
2017-05-10 09:29:12.872 [VMFixIPControllerApp] client::client '\x00k\x8bE{' requested 'connection_request'
2017-05-10 09:29:12.872 [VMFixIPControllerApp] client::client ['\x00k\x8bE{'] connected
2017-05-10 09:29:17.887 [VMFixIPControllerApp] client::client '\x00k\x8bE|' requested 'connection_request'
2017-05-10 09:29:17.887 [VMFixIPControllerApp] client::client ['\x00k\x8bE|'] connected
2017-05-10 09:29:22.902 [VMFixIPControllerApp] client::client '\x00k\x8bE}' requested 'connection_request'
2017-05-10 09:29:22.902 [VMFixIPControllerApp] client::client ['\x00k\x8bE}'] connected
2017-05-10 09:29:27.915 [VMFixIPControllerApp] client::client '\x00k\x8bE~' requested 'connection_request'
2017-05-10 09:29:27.915 [VMFixIPControllerApp] client::client ['\x00k\x8bE~'] connected
2017-05-10 09:29:32.930 [VMFixIPControllerApp] client::client '\x00k\x8bE\x7f' requested 'connection_request'
2017-05-10 09:29:32.930 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x7f'] connected
2017-05-10 09:29:37.944 [VMFixIPControllerApp] client::client '\x00k\x8bE\x80' requested 'connection_request'
2017-05-10 09:29:37.945 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x80'] connected
2017-05-10 09:29:42.962 [VMFixIPControllerApp] client::client '\x00k\x8bE\x81' requested 'connection_request'
2017-05-10 09:29:42.962 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x81'] connected
2017-05-10 09:29:47.974 [VMFixIPControllerApp] client::client '\x00k\x8bE\x82' requested 'connection_request'
2017-05-10 09:29:47.974 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x82'] connected
2017-05-10 09:29:52.991 [VMFixIPControllerApp] client::client '\x00k\x8bE\x83' requested 'connection_request'
2017-05-10 09:29:52.991 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x83'] connected
2017-05-10 09:29:58.003 [VMFixIPControllerApp] client::client '\x00k\x8bE\x84' requested 'connection_request'
2017-05-10 09:29:58.003 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x84'] connected
2017-05-10 09:30:03.020 [VMFixIPControllerApp] client::client '\x00k\x8bE\x85' requested 'connection_request'
2017-05-10 09:30:03.020 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x85'] connected
2017-05-10 09:30:08.033 [VMFixIPControllerApp] client::client '\x00k\x8bE\x86' requested 'connection_request'
2017-05-10 09:30:08.034 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x86'] connected
2017-05-10 09:30:13.048 [VMFixIPControllerApp] client::client '\x00k\x8bE\x87' requested 'connection_request'
2017-05-10 09:30:13.048 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x87'] connected
2017-05-10 09:30:18.063 [VMFixIPControllerApp] client::client '\x00k\x8bE\x88' requested 'connection_request'
2017-05-10 09:30:18.063 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x88'] connected
2017-05-10 09:30:23.078 [VMFixIPControllerApp] client::client '\x00k\x8bE\x89' requested 'connection_request'
2017-05-10 09:30:23.078 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x89'] connected
2017-05-10 09:30:28.092 [VMFixIPControllerApp] client::client '\x00k\x8bE\x8a' requested 'connection_request'
2017-05-10 09:30:28.092 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x8a'] connected
2017-05-10 09:30:33.106 [VMFixIPControllerApp] client::client '\x00k\x8bE\x8b' requested 'connection_request'
2017-05-10 09:30:33.107 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x8b'] connected
2017-05-10 09:30:38.121 [VMFixIPControllerApp] client::client '\x00k\x8bE\x8c' requested 'connection_request'
2017-05-10 09:30:38.121 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x8c'] connected
2017-05-10 09:30:43.138 [VMFixIPControllerApp] client::client '\x00k\x8bE\x8d' requested 'connection_request'
2017-05-10 09:30:43.138 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x8d'] connected
2017-05-10 09:30:48.151 [VMFixIPControllerApp] client::client '\x00k\x8bE\x8e' requested 'connection_request'
2017-05-10 09:30:48.151 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x8e'] connected
2017-05-10 09:30:53.168 [VMFixIPControllerApp] client::client '\x00k\x8bE\x8f' requested 'connection_request'
2017-05-10 09:30:53.168 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x8f'] connected
2017-05-10 09:30:58.179 [VMFixIPControllerApp] client::client '\x00k\x8bE\x90' requested 'connection_request'
2017-05-10 09:30:58.180 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x90'] connected
2017-05-10 09:31:03.197 [VMFixIPControllerApp] client::client '\x00k\x8bE\x91' requested 'connection_request'
2017-05-10 09:31:03.197 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x91'] connected
2017-05-10 09:31:08.210 [VMFixIPControllerApp] client::client '\x00k\x8bE\x92' requested 'connection_request'
2017-05-10 09:31:08.210 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x92'] connected
2017-05-10 09:31:13.225 [VMFixIPControllerApp] client::client '\x00k\x8bE\x93' requested 'connection_request'
2017-05-10 09:31:13.225 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x93'] connected
2017-05-10 09:31:18.239 [VMFixIPControllerApp] client::client '\x00k\x8bE\x94' requested 'connection_request'
2017-05-10 09:31:18.239 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x94'] connected
2017-05-10 09:31:23.255 [VMFixIPControllerApp] client::client '\x00k\x8bE\x95' requested 'connection_request'
2017-05-10 09:31:23.255 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x95'] connected
2017-05-10 09:31:28.268 [VMFixIPControllerApp] client::client '\x00k\x8bE\x96' requested 'connection_request'
2017-05-10 09:31:28.269 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x96'] connected
2017-05-10 09:31:33.283 [VMFixIPControllerApp] client::client '\x00k\x8bE\x97' requested 'connection_request'
2017-05-10 09:31:33.283 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x97'] connected
2017-05-10 09:31:38.298 [VMFixIPControllerApp] client::client '\x00k\x8bE\x98' requested 'connection_request'
2017-05-10 09:31:38.298 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x98'] connected
2017-05-10 09:31:43.320 [VMFixIPControllerApp] client::client '\x00k\x8bE\x99' requested 'connection_request'
2017-05-10 09:31:43.320 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x99'] connected
2017-05-10 09:31:48.336 [VMFixIPControllerApp] client::client '\x00k\x8bE\x9a' requested 'connection_request'
2017-05-10 09:31:48.336 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x9a'] connected
2017-05-10 09:31:53.355 [VMFixIPControllerApp] client::client '\x00k\x8bE\x9b' requested 'connection_request'
2017-05-10 09:31:53.355 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x9b'] connected
2017-05-10 09:31:58.371 [VMFixIPControllerApp] client::client '\x00k\x8bE\x9c' requested 'connection_request'
2017-05-10 09:31:58.371 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x9c'] connected
2017-05-10 09:32:03.389 [VMFixIPControllerApp] client::client '\x00k\x8bE\x9d' requested 'connection_request'
2017-05-10 09:32:03.389 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x9d'] connected
2017-05-10 09:32:08.405 [VMFixIPControllerApp] client::client '\x00k\x8bE\x9e' requested 'connection_request'
2017-05-10 09:32:08.405 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x9e'] connected
2017-05-10 09:32:13.420 [VMFixIPControllerApp] client::client '\x00k\x8bE\x9f' requested 'connection_request'
2017-05-10 09:32:13.421 [VMFixIPControllerApp] client::client ['\x00k\x8bE\x9f'] connected
2017-05-10 09:32:18.436 [VMFixIPControllerApp] client::client '\x00k\x8bE\xa0' requested 'connection_request'
2017-05-10 09:32:18.436 [VMFixIPControllerApp] client::client ['\x00k\x8bE\xa0'] connected
2017-05-10 09:32:23.453 [VMFixIPControllerApp] client::client '\x00k\x8bE\xa1' requested 'connection_request'
2017-05-10 09:32:23.453 [VMFixIPControllerApp] client::client ['\x00k\x8bE\xa1'] connected
2017-05-10 09:32:28.468 [VMFixIPControllerApp] client::client '\x00k\x8bE\xa2' requested 'connection_request'
2017-05-10 09:32:28.469 [VMFixIPControllerApp] client::client ['\x00k\x8bE\xa2'] connected

**Comment by chapmanb** [comment]
Thanks for following up. What did the `sbatch` command above report when you submitted it outside of bcbio? That should be the diagnostic error to help debug what is going wrong. Thanks much.

**Comment by pengxiao78** [comment]
Hi Brad,
What do you mean to submit the sbatch outside of bcbio? All the slurms were submitted under work folder, which is different from the bcbio folder. First, in work folder, I submitted

sbatch myjob.slurm

The running was stuck without showing any error in bcbio-nextgen*.log files but found the following error in /path/to/work/log/ipython/log/ipcluster-c399aec8-9400-4acb-9382-fb5a96843a88-35040.log,

2017-05-10 09:26:52.476 [IPClusterStart] Starting ipcluster with [daemon=True]
2017-05-10 09:26:52.481 [IPClusterStart] Creating pid file: /path/to/work/log/ipython/pid/ipcluster-c399aec8-9400-4acb-9382-fb5a96843a88.pid
2017-05-10 09:26:52.482 [IPClusterStart] Starting Controller with cluster_helper.cluster.BcbioSLURMControllerLauncher
2017-05-10 09:26:52.482 [IPClusterStart] Starting BcbioSLURMControllerLauncher: ['sbatch', u'./SLURM_controller8bc7e8ee-7cc8-49d0-b91c-324341a04969']
2017-05-10 09:26:52.483 [IPClusterStart] adding PBS queue settings to batch script
2017-05-10 09:26:52.483 [IPClusterStart] Writing batch script: ./SLURM_controller8bc7e8ee-7cc8-49d0-b91c-324341a04969
2017-05-10 09:26:52.495 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 503, in start_controller
    self.controller_launcher.start()
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 506, in start
    return super(BcbioSLURMControllerLauncher, self).start(1)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1151, in start
    output = check_output(self.args, env=os.environ)
  File "/path/to/bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['sbatch', u'./SLURM_controller8bc7e8ee-7cc8-49d0-b91c-324341a04969']' returned non-zero exit status 1

Then under the work same folder, I submitted

sbatch SLURM_controller8bc7e8ee-7cc8-49d0-b91c-324341a04969

The running is still stuck and no errors in error in bcbio-nextgen*.log files but I found a new /path/to/work/log/ipython/log/ipcontroller-c399aec8-9400-4acb-9382-fb5a96843a88-35115.log, which showed the info that I showed in the previous message and is stilling adding with stopping.

Thanks!

**Comment by chapmanb** [comment]
Sorry for the confusion, I meant what does the command:
```
sbatch SLURM_controller8bc7e8ee-7cc8-49d0-b91c-324341a04969
```
show? Is there an error? Does the bcbio controller job get started correctly if you look at the SLURM queue? To be clear, I don't expect this will rescue your previous job, just that this command returned an error previously so we need to figure out what it is. Generally, I suspect there is something in the `SLURM_controller*` file that your cluster doesn't like that is causing it to error out.

If it works cleanly, which it seems like it might based on the log file, maybe there is something wrong with your PATH that sbatch is not available when running with bcbio? Are you submitting the main `bcbio_nextgen.py` to a worker node which perhaps has a different path or permissions to run `sbatch`? Hope this helps some.

**Comment by pengxiao78** [comment]
the slurm queue shows the status RUNNING. 

JOBID  PARTITION                                NAME CPUS       START_TIME         USER    STATE       TIME TIME_LIMIT  NODES NODELIST(REASON)
            7834      inbre                      project_s-c 2          2017-05-10    peng.xiao  RUNNING       5:25 7-00:00:00      1 ica1
            7833      inbre                        project_s 2          2017-05-10    peng.xiao  RUNNING       6:38 7-00:00:00      1 ica1


No error showed except the content that I showed previously.

**Comment by chapmanb** [comment]
Thanks for confirming, it sounds like the batch script is okay but something is going wrong with the submission based on the host where it gets submitted from. Is the machine you're testing the manual `sbatch` on the same as the machine where bcbio submits it during the run? Is it possible there are machine specific differences causing it to work in one place and not the other. Sorry to not have a definite answer but hope this helps some for debugging.

**Comment by pengxiao78** [comment]
Thank you Brad! You provided important clues and the problem has been solved.
