### ISSUE TITLE
qstat -Qf queue fail from inside a running torque job

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1939]
Hi Brad, I am not able to submit a bcbio parallel run o torque from inside of a running job. I do not believe is a configuration issues on the cluster since qstat -Qf queue run clean if I use the test.sh script attached. do you have any suggestion ?

Thanks a lot for your help!

$ bcbio_nextgen.py ../config/Project_4998.yaml -t ipython -n 256 -s torque -q batch --timeout 999 --retries 
3 -p Project_4998
[2017-05-19T01:02Z] gpu-1-15.local: System YAML configuration: /cbio/ski/abdelwao/nobackup/pastore/bcbio/galaxy/bcbio_system.yaml
socket_connect_unix failed: 15137
socket_connect_unix failed: 15137
socket_connect_unix failed: 15137
qstat: cannot connect to server (null) (errno=15137) could not connect to trqauthd

[2017-05-19T01:03Z] gpu-1-15.local: Couldn't get machine information from resource query function for queue 'batch' on scheduler "torque"; submitting job to queue
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/system.py", line 48, in _get_machine_info
    return sched_info_dict[parallel["scheduler"].lower()](parallel.get("queue", ""))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/system.py", line 85, in _torque_info
    nodes = _torque_queue_nodes(queue)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/system.py", line 107, in _torque_queue_nodes
    qstat_out = subprocess.check_output(["qstat", "-Qf", queue])
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['qstat', '-Qf', 'batch']' returned non-zero exit status 33
[2017-05-19T01:03Z] gpu-1-15.local: Resource requests: ; memory: 1.00; cores: 1
[2017-05-19T01:03Z] gpu-1-15.local: Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[ProfileCreate] Generating default config file: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/log/ipython/ipython_config.py'
[ProfileCreate] Generating default config file: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/log/ipython/ipython_kernel_config.py'
[ProfileCreate] Generating default config file: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/log/ipython/ipcontroller_config.py'
[ProfileCreate] Generating default config file: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/log/ipython/ipengine_config.py'
[ProfileCreate] Generating default config file: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/log/ipython/ipcluster_config.py'

[test.sh.zip](https://github.com/chapmanb/bcbio-nextgen/files/1012844/test.sh.zip)

**Comment by roryk** [comment]
Hi @apastore,

I googled around a little bit and it looks like that error is caused by the trqauthd daemon not running on that machine. Are you running the bcbio-nextgen.py command you posted from the head node? For the test.sh script you posted, are you submitting that to the cluster as a job to run?

**Comment by apastore** [comment]
Sorry It was a cluster issue! it just restart the normal behavior. 
my apologies

**Comment by roryk** [comment]
Great, trying it again and having it work is the best kind of problem. :)
