### ISSUE TITLE
error on tumor pipeline

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [chapmanb/bcbio-nextgen#1946]
I have this error.

` gzip: /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz: invalid compressed data--format violated
`

````
bcbio_nextgen.py configuration/tumor.test.yaml  -n 2 &
[1] 19488
[centos@pol-produ 411]$ [2017-05-24T08:09Z] System YAML configuration: /usr/local/share/bcbio/galaxy/bcbio_system.yaml
[2017-05-24T08:09Z] Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2017-05-24T08:09Z] Configuring 1 jobs to run, using 2 cores each with 6.1g of memory reserved for each job
[2017-05-24T08:09Z] Timing: organize samples
[2017-05-24T08:09Z] multiprocessing: organize_samples
[2017-05-24T08:09Z] Using input YAML configuration: /home/centos/Calling/411/configuration/tumor.test.yaml
[2017-05-24T08:09Z] Checking sample YAML configuration: /home/centos/Calling/411/configuration/tumor.test.yaml
[2017-05-24T08:09Z] Testing minimum versions of installed programs
[2017-05-24T08:09Z] Timing: alignment preparation
[2017-05-24T08:09Z] multiprocessing: prep_align_inputs
[2017-05-24T08:09Z] Resource requests: ; memory: 1.00; cores: 1
[2017-05-24T08:09Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-05-24T08:09Z] Resource requests: ; memory: 1.00; cores: 1
[2017-05-24T08:09Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-05-24T08:09Z] Resource requests: ; memory: 1.00; cores: 1
[2017-05-24T08:09Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-05-24T08:09Z] bgzip input file
[2017-05-24T08:09Z] bgzip input file
[centos@pol-produ 411]$ 
[centos@pol-produ 411]$ 
[centos@pol-produ 411]$ htop
[1]+  Exit 1                  bcbio_nextgen.py configuration/tumor.test.yaml -n 2
[centos@pol-produ 411]$ bcbio_nextgen.py configuration/tumor.test.yaml  -n 2 &
[1] 25373
[centos@pol-produ 411]$ ^C
[centos@pol-produ 411]$ [2017-05-24T08:42Z] System YAML configuration: /usr/local/share/bcbio/galaxy/bcbio_system.yaml
[2017-05-24T08:42Z] Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2017-05-24T08:42Z] Configuring 1 jobs to run, using 2 cores each with 6.1g of memory reserved for each job
[2017-05-24T08:42Z] Timing: organize samples
[2017-05-24T08:42Z] multiprocessing: organize_samples
[2017-05-24T08:42Z] Using input YAML configuration: /home/centos/Calling/411/configuration/tumor.test.yaml
[2017-05-24T08:42Z] Checking sample YAML configuration: /home/centos/Calling/411/configuration/tumor.test.yaml
[2017-05-24T08:42Z] Testing minimum versions of installed programs
[2017-05-24T08:42Z] Timing: alignment preparation
[2017-05-24T08:42Z] multiprocessing: prep_align_inputs
[2017-05-24T08:42Z] Resource requests: ; memory: 1.00; cores: 1
[2017-05-24T08:42Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-05-24T08:42Z] Resource requests: ; memory: 1.00; cores: 1
[2017-05-24T08:42Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-05-24T08:42Z] Resource requests: ; memory: 1.00; cores: 1
[2017-05-24T08:42Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-05-24T08:42Z] bgzip input file
[2017-05-24T08:42Z] bgzip input file
[2017-05-24T08:49Z] 
[2017-05-24T08:49Z] gzip: /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz: invalid compressed data--format violated
[2017-05-24T08:49Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; gunzip -c /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz | /usr/local/share/bcbio/galaxy/../anaconda/bin/bgzip -c /dev/stdin > /home/centos/Calling/411/bcbiotx/tmpO3rnGd/411_GCCAAT_L001_R1_001.fastq.gz

gzip: /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz: invalid compressed data--format violated
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 122, in variant2pipeline
    samples = run_parallel("prep_align_inputs", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 150, in prep_align_inputs
    return alignprep.create_inputs(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 47, in create_inputs
    data["files"] = _prep_grabix_indexes(data["files"], data["dirs"], data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 284, in _prep_grabix_indexes
    out = run_multicore(_bgzip_from_fastq_parallel, [[d] for d in inputs], data["config"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 812, in __call__
    self.retrieve()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 749, in retrieve
    exception = exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)

[1]+  Exit 1                  bcbio_nextgen.py configuration/tumor.test.yaml -n 2
[centos@pol-produ 411]$ gzip /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz:
gzip: /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz:: No such file or directory
[centos@pol-produ 411]$ gzip /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz 
gzip: /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz already has .gz suffix -- unchanged
[centos@pol-produ 411]$ zcat  /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz |head
@B0P8DQ1:83:H5WKGBCXY:1:1101:1205:2061 1:N:0:GCCAAT
NAGGTGAACAGGAACTTTGATCCCCTGTTTCTTCCAAAGGCAGTAATGACAATAAATACATATATCACTTGAAGCTTGGAGTATTTGCACTTTGCAGCAGT
+
#<<GGIIIIIGGGGGGGGGGGGGGGIIIIIIIIIGIGGIGIIIIIIIGIIIGGGGIIIGGGGGIIIGIGGIGGGGGGGGGGGGGGGIGGGGIGIIGIGGGG
@B0P8DQ1:83:H5WKGBCXY:1:1101:1170:2093 1:N:0:GCCAAT
GCATTTAAAGGGTTTCTCACCAGTGTGTACCCGCTGATGTTCAGTAAGGAATGAATTAAGTCTAAAGGCCTTCCCGCATTCCTTACATTCAAAAGGTTTCT
+
GGAGGIIGIIIIIIIIIGIIIIIIGIGIIIII..GGGIIIIIIIIIIIIIIIIIIIIGIGIGIIIIIGIIIIGIIIIIIIGGGIIIGAGGGAGIIIGGIII
@B0P8DQ1:83:H5WKGBCXY:1:1101:1224:2147 1:N:0:GCCAAT
CAGAGAGCAAGTAGGAAGGTCACATCACCTGAGTGGGTGCTTGTCCAGTGAGGTGTCTCAATCCTTCCTGTGGGCAGGACCCTGGAAGAAGAGTCACAGAA
```
`

**Comment by chapmanb** [comment]
This error indicates there is something wrong with your gzipped input file (`/home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz`). gzip problems are often truncated files so you won't see the issue by looking at the `head` of the file. You'll probably see a similar error if you do:
```
zcat /home/centos/Calling/411/RAW/411_GCCAAT_L001_R1_001.fastq.gz > /dev/null
```
Hope this helps.

**Comment by bioinfo-dirty-jobs** [comment]
` zcat  RAW/411_GCCAAT_L001_R1_001.fastq.gz  > /dev/null`
I don't see any message of error

**Comment by chapmanb** [comment]
Sorry I'm not sure what is going on but all bcbio is doing in gunzipping and bgzipping the file so it's something gunzip didn't like when reading it. If this is a shared filesystem it's also possible you were having intermittent filesystem errors and re-running the command will work cleanly. Sorry to not know exactly what is happening and hope this helps.
