### ISSUE TITLE
Cnvkit UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0'

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1951]
Hi Brad, I am getting this UnicodeEncodeError from cnvkit plot. I guess is generate by  out_handle.write(str(r)). 

Thanks!

[2017-05-24T22:12Z] gpu-2-5.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 386, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 191, in detect_sv
    for svdata in caller_fn(items):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 33, in run
    return _cnvkit_by_type(items, background)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 43, in _cnvkit_by_type
    return _run_cnvkit_single(items[0])
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 82, in _run_cnvkit_single
    return _associate_cnvkit_out(ckouts, [data])
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 65, in _associate_cnvkit_out
    ckout = _add_plots_to_output(ckout, data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 576, in _add_plots_to_output
    scatter = _add_scatter_plot(out, data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 640, in _add_scatter_plot
    priority_bed = plot._prioritize_plot_regions(pybedtools.BedTool(priority_bed), data, os.path.dirname(out_file))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/plot.py", line 95, in _prioritize_plot_regions
    out_handle.write(str(r))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 188: ordinal not in range(128)

**Comment by chapmanb** [comment]
Thanks much for the heads up and sorry about the issue. I pushed a fix to the latest development version I hope will avoid the issue by explicitly only writing the chrom/start/end into a BED file since that's what we're using for the downstream plots. I'm guessing there are unicode characters in one of the gene names in your file. Hope this gets it working cleanly for you.
