### ISSUE TITLE
upgrade  gatk fail

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [chapmanb/bcbio-nextgen#1952]
I have this error:

`sudo /usr/local/bin/bcbio_nextgen.py upgrade --tools --toolplus gatk=$PWD/GenomeAnalysisTK.jar`

`Creating manifest of installed packages in /usr/local/share/bcbio/manifest
Third party tools upgrade complete.
Installing additional tools
Installing gatk
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 84, in upgrade_bcbio
    _install_toolplus(args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 458, in _install_toolplus
    _install_gatk_jar(tool.name, tool.fname, toolplus_manifest, system_config, toolplus_dir)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 475, in _install_gatk_jar
    version = get_gatk_jar_version(name, fname)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 464, in get_gatk_jar_version
    return broad.get_gatk_version(fname)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 108, in get_gatk_version
    _check_for_bad_version(version, "GATK")
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 87, in _check_for_bad_version
    % (program, version))
ValueError: Problem getting version for GATK. This often indicates you're not running the correct Java version:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/gatk/engine/CommandLineGATK : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
`

**Comment by chapmanb** [comment]
The recommended way to install GATK is using `gatk-register`:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2

instead of this older method of directly adding the jar to bcbio. The `gatk-register` method takes care of using Java 1.8 and avoids the problem here (where your system Java is 1.7). Hope this helps.
