### ISSUE TITLE
CNVkit did not find normal

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1962]
Hi Brad, 
I am so sorry I am keep reporting issues (i do not understand) with CNV calling.

now I see this coming out. when I use cnvkit as the only caller. The normal is shared between multiple tumor samples. they all run fine but this one. 

If you need I can share my yaml files (but is basically the same I have already send, just cnvkit is the only caller now, since when lumpy and metaSV was present cnvkit was simply skipped)

Thanks a lot!

[2017-05-29T18:31Z] cpu-6-2.local: ipython: detect_sv
[2017-05-29T18:31Z] gpu-2-9.local: CNVkit segment
[2017-05-29T18:31Z] gpu-2-9.local: Traceback (most recent call last):
[2017-05-29T18:31Z] gpu-2-9.local:   File "/cbio/ski/abdelwao/nobackup/pastore/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
[2017-05-29T18:31Z] gpu-2-9.local:     args.func(args)
[2017-05-29T18:31Z] gpu-2-9.local:   File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 590, in _cmd_segment
[2017-05-29T18:31Z] gpu-2-9.local:     args.min_variant_depth, args.zygosity_freq)
[2017-05-29T18:31Z] gpu-2-9.local:   File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1658, in load_het_snps
[2017-05-29T18:31Z] gpu-2-9.local:     skip_somatic=True)
[2017-05-29T18:31Z] gpu-2-9.local:   File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/__init__.py", line 80, in read
[2017-05-29T18:31Z] gpu-2-9.local:     dframe = reader(infile, **kwargs)
[2017-05-29T18:31Z] gpu-2-9.local:   File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 29, in read_vcf
[2017-05-29T18:31Z] gpu-2-9.local:     sid, nid = _choose_samples(vcf_reader, sample_id, normal_id)
[2017-05-29T18:31Z] gpu-2-9.local:   File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 111, in _choose_samples
[2017-05-29T18:31Z] gpu-2-9.local:     _confirm_unique(sid, vcf_samples)
[2017-05-29T18:31Z] gpu-2-9.local:   File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 173, in _confirm_unique
[2017-05-29T18:31Z] gpu-2-9.local:     % (sample_id, samples))
[2017-05-29T18:31Z] gpu-2-9.local: IndexError: Did not find a single sample ID 'FFPEPOOLEDNORMAL' in: ['AY-testly-011-P']
[2017-05-29T18:31Z] gpu-2-9.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && unset R_LIBS && export PATH=/cbio/ski/abdelwao/nobackup/pastore/bcbio/anaconda/bin:$PATH && export TMPDIR=/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/bcbiotx/tmpq7ZBNb && /cbio/ski/abdelwao/nobackup/pastore/bcbio/anaconda/bin/cnvkit.py segment -p 16 -o /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/bcbiotx/tmpq7ZBNb/AY-testly-011-P-sort-AY-testly-011-flatbackground.cns /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/AY-testly-011-P/cnvkit/raw/AY-testly-011-P-sort-AY-testly-011-flatbackground.cnr -v /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/vardict/AY-testly-011-effects-annotated.vcf.gz
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/nobackup/pastore/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 590, in _cmd_segment
    args.min_variant_depth, args.zygosity_freq)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1658, in load_het_snps
    skip_somatic=True)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/__init__.py", line 80, in read
    dframe = reader(infile, **kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 29, in read_vcf
    sid, nid = _choose_samples(vcf_reader, sample_id, normal_id)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 111, in _choose_samples
    _confirm_unique(sid, vcf_samples)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 173, in _confirm_unique
    % (sample_id, samples))
IndexError: Did not find a single sample ID 'FFPEPOOLEDNORMAL' in: ['AY-testly-011-P']
' returned non-zero exit status 1
[2017-05-29T18:31Z] gpu-2-9.local: Unexpected error

**Comment by chapmanb** [comment]
Sorry about all of the issues, it looks like they're all deriving from a problem with resolving your shared normals case. Apologies but I didn't get the configuration you sent earlier to help try and replicate and debug this. From our discussion in #1954, I thought you were still putting it together. Would you be able to post as a gist so I can dig into it?

Also is your seq2c issue in #1957 with the same setup, or a different configuration? I can definitely try to dig and figure out the batching issues with more details. Thanks again.
