### ISSUE TITLE
Race condition for grabix index - ipython run fails

### ISSUE THREAD

**Issue by andreyto** [chapmanb/bcbio-nextgen#1964]
I was routinely getting runs under ipython cluster mode failing with messages about, essentially, empty BAM files. That was generated by BCBio benchmarking YAML sample configs like the one copied at the bottom of this message. It looks like I identified a race condition that was triggered when these configs had two `- files` sections that referenced the same files across sections.

That was after updating to 'devel' on May 25, as well as back in March 2017.

The messages were typically like a traceback below (I removed absolute path prefixes from the output), and at other times errors from parsing grabix index files.

```
Traceback (most recent call last):
  File "bcb/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "bcb/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 217, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "bcb/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 230, in postprocess_alignment
    callable.block_regions(covinfo.raw_callable, bam_file_ready, ref_file, data)
  File "bcb/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 189, in block_regions
    "not overlap with regions found in your `variant_regions` BED: %s" % in_bam)
ValueError: No callable regions found from BAM file. Alignment regions might not overlap with regions found in your `variant_regions` BED: work/align/NA12878-2/NA12878-2-sort.bam
```

Upstream of the hard error, there were warnings and ignored errors:

```
[2017-05-25T22:35Z] : bwa mem alignment from fastq: NA12878-2
[2017-05-25T22:35Z] : [grabix] requested lines exceed the number of lines in the file.
[2017-05-25T22:35Z] : bwa mem alignment from fastq: NA12878-1
[2017-05-25T22:35Z] : [grabix] requested lines exceed the number of lines in the file.
[2017-05-25T22:35Z] : bwa mem alignment from fastq: NA12878-2
[2017-05-25T22:35Z] : [grabix] requested lines exceed the number of lines in the file.
[2017-05-25T22:35Z] : bwa mem alignment from fastq: NA12878-2
[2017-05-25T22:35Z] : [grabix] requested lines exceed the number of lines in the file.
[2017-05-25T22:35Z] : bwa mem alignment from fastq: NA12878-1
[2017-05-25T22:35Z] : [grabix] requested lines exceed the number of lines in the file.
[2017-05-25T22:35Z] : bwa mem alignment from fastq: NA12878-1
[2017-05-25T22:35Z] : [grabix] requested lines exceed the number of lines in the file.
[2017-05-25T22:35Z] : [W::bseq_read] the 2nd file has fewer sequences.
[2017-05-25T22:35Z] : [W::bseq_read] the 2nd file has fewer sequences.
```

The apparent race condition is in the concurrent grabix calls:

```
[2017-05-25T22:34Z] : grabix index work/align_prep/NA12878-NGv3-LAB1360-A_2.fastq.gz
[2017-05-25T22:34Z] : grabix index work/align_prep/NA12878-NGv3-LAB1360-A_1.fastq.gz
[2017-05-25T22:34Z] : grabix index work/align_prep/NA12878-NGv3-LAB1360-A_1.fastq.gz
```

What happens is that grabix is called in the same directory twice for the same fastq file if that file appears more than once in the sample YAML. That results in a truncated grabix index file.  The previous steps that create those fastq files each run in their own unique temporary directory (and then probably overwrite the same file twice in `align_prep`). After I removed one analysis batch from YAML, so that each input file is mentioned only once, the ipython run completed OK.

## This triggers the errors and warnings

```
# Configuration comparing alignment methods, preparation approaches
# and variant callers for an NA12878 exome dataset from EdgeBio.
#
# See the bcbio-nextgen documentation for full instructions to
# run this analysis:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
---
upload:
  dir: ../final
details:
  - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
    description: NA12878-1
    metadata:
      sex: female
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      variantcaller: [freebayes, gatk-haplotype, samtools]
      recalibrate: gatk
      realign: gatk
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: ../input/NGv3.bed
      ensemble:
        numpass: 2
#      tools_off: [gemini, vcfanno]
  - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
    description: NA12878-2
    metadata:
      sex: female
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: [freebayes, gatk-haplotype, samtools]
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: ../input/NGv3.bed
      ensemble:
        numpass: 2
#      tools_off: [gemini, vcfanno]

```

## This completes OK

```
# Configuration comparing alignment methods, preparation approaches
# and variant callers for an NA12878 exome dataset from EdgeBio.
#
# See the bcbio-nextgen documentation for full instructions to
# run this analysis:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
---
upload:
  dir: ../final
details:
  - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
    description: NA12878-2
    metadata:
      sex: female
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: [freebayes, gatk-haplotype, samtools]
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: ../input/NGv3.bed
      ensemble:
        numpass: 2
#      tools_off: [gemini, vcfanno]

```

**Comment by chapmanb** [comment]
Andrey;
Thanks much for the detailed report and apologies about the issue. I swapped over grabix index to correctly use a transactional directory, which will avoid this problem. grabix is a little tricky since it doesn't allow you to specify the output file name but we have a way to work around that by symlinking the initial file. Apologies, we should have used this approach earlier to avoid this potential issue. Thanks again for reporting it and please let us know if you run into any other problems.
