### ISSUE TITLE
KeyboardInterrupt Error with Somatic Variant Calling

### ISSUE THREAD

**Issue by aadamk** [chapmanb/bcbio-nextgen#1976]
Hi,
I cannot understand a recurring KeyboardInterrupt Error that is generated (without hitting ctrl+C) when attempting to call tumor somatic variants.  I queue it with 6 available cores with 18G memory allocation.  I built my sample.yaml file from the existing synthetic DREAM cancer variant calling .yaml in the bcbio docs.   Do you know what may be happening?  I have a snapshot of the error recorded in my log file. 

![virtualbox_ubuntu_12_06_2017_13_33_06](https://user-images.githubusercontent.com/20973091/27047038-a75fa330-4f74-11e7-8324-47c8acc91a25.png)

**Comment by chapmanb** [comment]
Glad this got sorted out because I wasn't sure what to suggest with unexpected KeyboardInterrupts. Hope all is now working cleanly for you.

**Comment by aadamk** [comment]
Hi,
The issue appeared to be resolved, but now is occurring further down the pipeline.  I am doing consensus somatic variant calling with vardict and mutect2.  I allocated one core as previously there was an issue with parallelization and I wanted to simplify things.  Now, keyboardinterrupt re-emerges during the final stages of variant calling.  VCFs have been generated by both callers in their respected folders, so does it matter?  Here are the final lines of my log file:

[2017-06-15T22:44Z] tabix index mel_case-GL000192.1_0_547496.vcf.gz
[2017-06-15T22:44Z] multiprocessing: concat_variant_files
[2017-06-15T22:44Z] Resource requests: ; memory: 1.00; cores: 1
[2017-06-15T22:44Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-06-15T22:44Z] bcftools concat variants
[2017-06-15T22:44Z] tabix index mel_case.vcf.gz
[2017-06-15T22:44Z] Resource requests: ; memory: 1.00; cores: 1
[2017-06-15T22:44Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2017-06-15T22:44Z] bcftools concat variants
[2017-06-15T22:44Z] tabix index mel_case.vcf.gz
[2017-06-15T22:44Z] Resource requests: bcbio_variation, fastqc, gatk, gemini, qsignature, sambamba, samtools, snpeff; memory: 3.00, 3.00, 3.50, 3.00, 3.00, 3.00, 3.00, 3.00; cores: 16, 16, 1, 16, 16, 16, 16, 1
[2017-06-15T22:44Z] Configuring 1 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2017-06-15T22:44Z] Timing: joint squaring off/backfilling
[2017-06-15T22:44Z] Timing: variant post-processing
[2017-06-15T22:44Z] multiprocessing: postprocess_variants
[2017-06-15T22:44Z] Finalizing variant calls: 98__1_25_17_, vardict
[2017-06-15T22:44Z] Calculating variation effects for 98__1_25_17_, vardict
[2017-06-15T22:44Z] snpEff effects : 98__1_25_17_
[2017-06-15T22:53Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/aadam/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/aadam/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 85, in _do_run
    line = s.stdout.readline()
KeyboardInterrupt

**Comment by chapmanb** [comment]
Sorry about the new problems, I'm still not sure what best to suggestion with unknown KeyboardInterrupts. My best guess is that the system shuts down the bcbio process due to memory usage constraints. Is there a chance you ran your tests on a cluster head node or somewhere else that might have approaches to shut down processes using too many resources?

**Comment by aadamk** [comment]
I actually ran this within an interactive session (not on cluster head node), and mutect2+vardict variant calling completed successfully.  snpEff annotation fails with standard node resources (6GB 1 core) - maybe I could attempt to first request more node memory and then allocate more resources for variant annotation in the sample .yaml file?

**Comment by chapmanb** [comment]
Thanks for the details on your setup. I'm still not positive about the source of the interrupt but it's possible your scheduler kills jobs when they go beyond the allocated memory/cores. It would be worth checking with your system administrators to see if they have any processes in place that might explain that.

Practically, you're right on with a good solution -- increasing memory should hopefully help. 6Gb is right on the edge of snpEff's standard usage for human samples so you might have been slightly going beyond the memory allocation in your interactive job. Hope this helps.

**Comment by aadamk** [comment]
thank you
