### ISSUE TITLE
File not found due to unexpected prefix in directory names

### ISSUE THREAD

**Issue by Han-Ying** [chapmanb/bcbio-nextgen#1996]
Hi folks,

I was running rnaseq but got error message file not found as following:

[2017-07-04T22:57Z] piccolo002-181: Unexpected error
Traceback (most recent call last):
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 295, in generate_transcript_counts
    return ipython.zip_args(apply(rnaseq.generate_transcript_counts, *args))
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 129, in generate_transcript_counts
    data["count_file"] = featureCounts.count(data)
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/featureCounts.py", line 22, in count
    sorted_bam = bam.sort(in_bam, dd.get_config(data), order="queryname")
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 377, in sort
    if bam_already_sorted(in_bam, config, order):
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 447, in bam_already_sorted
    return order == _get_sort_order(in_bam, config)
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 451, in _get_sort_order
    with open_samfile(in_bam) as bam_handle:
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 231, in open_samfile
    return pysam.Samfile(in_file, "rb")
  File "pysam/libcalignmentfile.pyx", line 397, in pysam.libcalignmentfile.AlignmentFile.__cinit__ (pysam/libcalignmentfile.c:5831)
  File "pysam/libcalignmentfile.pyx", line 558, in pysam.libcalignmentfile.AlignmentFile._open (pysam/libcalignmentfile.c:7556)
IOError: file `/groups/springer/han/CDK46_response_201701/MCF7/work/align/6_hours_0_3_Abemaciclib/1_2017-07-04_MCF7_star/6_hours_0_3_Abemaciclib.bam` not found
[2017-07-04T22:57Z] piccolo002-192: Unexpected error

However, I found the file under a folder with a similar but different name:

./MCF7/work/align/6_hours_0_3_Abemaciclib/16_2017-07-04_MCF7_star:
total 3219218
-rw-rw-r-- 1 hj84 springer 996431246 Jul  4 18:39 6_hours_0_3_Abemaciclib.transcriptome.bam
-rw-rw-r-- 1 hj84 springer 441385052 Jul  4 18:40 6_hours_0_3_Abemaciclib.bam
-rw-rw-r-- 1 hj84 springer   3911856 Jul  4 18:40 6_hours_0_3_Abemaciclib.bam.bai
-rw-rw-r-- 1 hj84 springer 689346155 Jul  4 19:02 6_hours_0_3_Abemaciclib.nsorted.bam
-rw-rw-r-- 1 hj84 springer 633874059 Jul  4 19:03 6_hours_0_3_Abemaciclib.nsorted.primary.bam

Apparently, the prefix of the directories differed but I have no clue what caused that. Could anyone help me out?
Thanks in advance!

[MCF7.zip](https://github.com/chapmanb/bcbio-nextgen/files/1124991/MCF7.zip)

**Comment by roryk** [comment]
We generate a lane number here:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/run_info.py#L765

and it depends on the ordering of the run details in the YAML file. Did the ordering get swapped in the YAML file that is in the config directory between reruns? That would definitely cause this issue.

**Comment by Han-Ying** [comment]
The ordering in the generated YAML file did get swapped. Do you have an idea what I should deal with that?

**Comment by roryk** [comment]
Thanks, sorry about that we weren't really anticipating this happening. Did files get added in between the runs? It kind of looks like that.  I think for future runs adding files to the bottom of the CSV file should work okay, because the rest of the files will maintain their ordering. As it is, now I think the easiest path forward to is nuke the work directory and start over. If that is super painful to do then we could try to fix it but that would involve figuring out the original order, rearranging the CSV file and putting the new samples at the end, deleting all the files related to the new files and then restarting. From the logs it looks like these samples aren't particularly deep so I think its probably easier to start over.

**Comment by Han-Ying** [comment]
I started over, didn't get the '[file] not found' message. However, I got another one, as follows:

[2017-07-06T00:19Z] piccolo002-182: Converting Sailfish to Sleuth format.
[2017-07-06T00:19Z] piccolo002-182: Loading required package: methods
[2017-07-06T00:19Z] piccolo002-188: ^[[00m^[[1m[2017-07-05 20:19:15.284] [jointLog] [info] wrote 24 bootstraps
[2017-07-06T00:19Z] piccolo002-182: Error in setnames(quant, c("target_id", "length", "tpm", "est_counts")) :
[2017-07-06T00:19Z] piccolo002-182:   Can't assign 4 names to a 5 column data.table
[2017-07-06T00:19Z] piccolo002-182: Calls: prepare_fish_for_sleuth -> sapply -> lapply -> FUN -> setnames
[2017-07-06T00:19Z] piccolo002-182: Execution halted
[2017-07-06T00:19Z] piccolo002-178: ^[[00m^[[1m[2017-07-05 20:19:15.450] [jointLog] [info] wrote 29 bootstraps
[2017-07-06T00:19Z] piccolo002-182: Uncaught exception occurred
Traceback (most recent call last):
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/groups/bcbio/bcbio_dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /groups/bcbio/bcbio_dev/anaconda/bin/Rscript -e 'library("wasabi"); prepare_fish_f$
Loading required package: methods
Error in setnames(quant, c("target_id", "length", "tpm", "est_counts")) :
  Can't assign 4 names to a 5 column data.table
Calls: prepare_fish_for_sleuth -> sapply -> lapply -> FUN -> setnames
Execution halted
' returned non-zero exit status 1

It seems like the numbers of columns didn't match, but I have no idea where were the columns from and how to solve it. Could you please help me again? Thanks!

**Comment by roryk** [comment]
Great, glad that helped. This error is due to having an outdated version of wasabi, I'm not sure why this old version is persisting. I disabled this conversion so if you update to the development version with:


```
bcbio_nesxtgen.py upgrade -u development
```

this should be disabled. Alternatively, updating wasabi should work, you can do that by opening up the R that comes with bcbio with:

```
/groups/bcbio/bcbio_dev/anaconda/bin/R
```

and updating to the current version of wasabi:

```
devtools::install_github("COMBINE-lab/wasabi")
```
Hope one of those gets you going.

**Comment by Han-Ying** [comment]
Unfortunately, I don't have the permission to execute either of them (orchestra.med.harvard.edu). Are there other ways I can do?

**Comment by lpantano** [comment]
Hi,

I am updating the code in orchestra. you can try in a one of hour again.

Let us know if you find further issues there.

cheers

**Comment by chapmanb** [comment]
Han-Ying, Lorena and Rory;
I pushed fixes to the bcbio install process which will force an upgrade to the latest R which should include the up to date wasabi. A standard upgrade should now do it but let me know if you run into any issues at all.

**Comment by Han-Ying** [comment]
The work has been properly done. That really helps! Thanks a lot!

**Comment by roryk** [comment]
Thanks Brad!
