### ISSUE TITLE
Missing All_20170403.vcf.gz while upgrading

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#2002]
Hi Brad,

I met with an issue while trying to upgrade vep to the latest version using this command line.
bcbio_nextgen.py upgrade --datatarget vep

It seems that a required file is missing?
Running GGD recipe: GRCh37 dbsnp 150-20170403
--2017-07-13 10:03:32--  ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/All_20170403.vcf.gz
           => “variation/dbsnp-150-orig.vcf.gz”
Resolving ftp.ncbi.nih.gov... 130.14.250.11, 2607:f220:41e:250::10
Connecting to ftp.ncbi.nih.gov|130.14.250.11|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /snp/organisms/human_9606_b150_GRCh37p13/VCF ... done.
==> SIZE All_20170403.vcf.gz ... done.
==> PASV ... done.    ==> RETR All_20170403.vcf.gz ...
No such file “All_20170403.vcf.gz”.

Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 338, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 467, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 812, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file, gid)
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 31, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/home/dlho/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 63, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 8

**Comment by chapmanb** [comment]
Sorry about the issue, this was fixed yesterday but you might have an old cached cloudbiolinux without the fix. Could you try doing:
```
rm -rf /home/dlho/tmpbcbio-install
```
and then re-running? Hopefully this will fix it for you, please let us know if you run into any other issues and we can re-open.

**Comment by phu5ion** [comment]
Hi Brad, 

I removed the tmpbcbio-install directory but it still didn't work - the same error occurred.
Could it be because I'm using a developmental version of bcbio - bcbio-nextgen,1.0.5a0-68b68f7
Btw, I also can't upgrade to the latest developmental version - see #2001
