### ISSUE TITLE
Failure using VarScan for tumour only variant calling

### ISSUE THREAD

**Issue by mshadbolt** [chapmanb/bcbio-nextgen#2009]
Hi, thanks for the awesome tool and for the great support you give to your users.

I am trying to use the bcbio pipeline to call variants on a batch of all tumour samples. However when I try to use VarScan as one of the variant callers the pipeline fails. It proceeds to the end if I use FreeBayes and VarDict, but I get several errors in the vcfanno step which are similar to the below code block, not sure if they are a serious issue or not:

```
[2017-07-20T00:03Z] =============================================
[2017-07-20T00:03Z] vcfanno version 0.2.6 [built with go1.8]
[2017-07-20T00:03Z] see: https://github.com/brentp/vcfanno
[2017-07-20T00:03Z] =============================================
[2017-07-20T00:03Z] vcfanno.go:115: found 1 sources from 1 files
[2017-07-20T00:03Z] vcfanno.go:143: using 2 worker threads to decompress query file
[2017-07-20T00:03Z] vcfanno.go:241: annotated 4 variants in 0.10 seconds (40.9 / second)
[2017-07-20T00:03Z] [W::vcf_parse] Contig '16' is not defined in the header. (Quick workaround: index the file with tabix.)
[2017-07-20T00:03Z] Encountered error, cannot proceed. Please check the error output above.
[2017-07-20T00:03Z] Uncaught exception occurred
Traceback (most recent call last):
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; vcfanno ~/BCBIO_VarscanDebug/work/BCBIO_VarscanDebug/work/bcbiotx/tmpd73AN4/dbsnp.conf ~/BCBIO_VarscanDebug/work/BCBIO_VarscanDebug/work/varscan/16/sample1-16_0_68771366.vcf.gz | bcftools annotate --set-id +'%INFO/rs_ids' -o ~/BCBIO_VarscanDebug/work/BCBIO_VarscanDebug/work/bcbiotx/tmpd73AN4/sample1-16_0_68771366-wdbsnp.vcf.gz -O z
```

If I include VarScan as one of the variant callers, the script stops running when it hits the following error:

```
=============================================
vcfanno version 0.2.6 [built with go1.8]
see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:115: found 1 sources from 1 files
vcfanno.go:143: using 2 worker threads to decompress query file
[W::vcf_parse] Contig '2' is not defined in the header. (Quick workaround: index the file with tabix.)
Encountered error, cannot proceed. Please check the error output above.
vcfanno.go:241: annotated 16 variants in 0.15 seconds (105.1 / second)
' returned non-zero exit status 255
[2017-07-20T00:04Z] Varscan
[2017-07-20T00:04Z] [mpileup] 1 samples in 1 input files
[2017-07-20T00:04Z] <mpileup> Set max per-file depth to 8000
[2017-07-20T00:04Z] Varscan
[2017-07-20T00:04Z] [mpileup] 1 samples in 1 input files
[2017-07-20T00:04Z] <mpileup> Set max per-file depth to 8000
[2017-07-20T00:04Z] Genotyping with varscan: ('15', 66694200, 102531392) sample1-sort.bam
[2017-07-20T00:04Z] Varscan
[2017-07-20T00:04Z] [mpileup] 1 samples in 1 input files
[2017-07-20T00:04Z] <mpileup> Set max per-file depth to 8000
[2017-07-20T00:04Z] Varscan
[2017-07-20T00:04Z] Got the following sample list:
[2017-07-20T00:04Z] sample1
[2017-07-20T00:04Z] Only variants will be reported
[2017-07-20T00:04Z] Min coverage:	5
[2017-07-20T00:04Z] Min reads2:	2
[2017-07-20T00:04Z] Min var freq:	0.01
[2017-07-20T00:04Z] Min avg qual:	15
[2017-07-20T00:04Z] P-value thresh:	0.98
[2017-07-20T00:04Z] [mpileup] 1 samples in 1 input files
[2017-07-20T00:04Z] <mpileup> Set max per-file depth to 8000
[2017-07-20T00:04Z] Varscan
[2017-07-20T00:04Z] [mpileup] 1 samples in 1 input files
[2017-07-20T00:04Z] <mpileup> Set max per-file depth to 8000
[2017-07-20T00:04Z] Varscan
[2017-07-20T00:04Z] [mpileup] 1 samples in 1 input files
[2017-07-20T00:04Z] <mpileup> Set max per-file depth to 8000
[2017-07-20T00:04Z] Varscan
[2017-07-20T00:04Z] [mpileup] 1 samples in 1 input files
[2017-07-20T00:04Z] <mpileup> Set max per-file depth to 8000
Traceback (most recent call last):
  File "~/software/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "~/software/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 152, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 193, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 812, in __call__
    self.retrieve()
  File "~/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 749, in retrieve
    exception = exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```
In the above case I ran the pipeline with only VarScan as a variant caller

Let me know if you need any further information from the log files, need my .yaml config file or have any ideas for a work around. We would like to use VarScan in our workflow as we already use it for other pipelines we currently run.

Thanks!

**Comment by chapmanb** [comment]
Marion;
Thanks much for the report and apologies about the problem. I'm a bit confused about the underlying cause of the issue since I don't believe VarScan currently gets these dbSNP annotations via vcfanno/bcftools but I may be misreading some of the code. As a speculative fix, I pushed an update to VarScan to ensure that reference contigs are available so it won't complain. If you upgrade with:
```
bcbio_nextgen.py upgrade -u development
```
remove the current VarScan directory (sorry) and re-run, it should hopefully work cleanly. If you still have issues could you post a traceback from running in single core mode (`-n 1`) and I could trace the source of the error more closely. Hope this gets it working for you.

**Comment by mshadbolt** [comment]
Hi, the pipeline ran perfectly with the updated code, thanks for the super speedy fix!
