### ISSUE TITLE
GATK4 GenotypeGVCFs output argument should be --output  or  -O not -o

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2010]
Hi, 

I think there is a small bug in the specifying the GATK4 output argument for the GenotypeGVCFs tool. 

```
***********************************************************************

A USER ERROR has occurred: o is not a recognized option

***********************************************************************
Use -DGATK_STACKTRACE_ON_USER_EXCEPTIONto print the stack trace.
' returned non-zero exit status 1
[2017-07-20T08:04Z] node23: Unexpected error
Traceback (most recent call last):
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 450, in square_batch_region
    return ipython.zip_args(apply(joint.square_batch_region, *args))
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 126, in square_batch_region
    gatkjoint.run_region(data, region, vrn_files, out_file)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/variation/gatkjoint.py", line 18, in run_region
    return _run_genotype_gvcfs(data, region, vrn_files, dd.get_ref_file(data), out_file)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/variation/gatkjoint.py", line 52, in _run_genotype_gvcfs
    broad_runner.run_gatk(params, memscale=memscale)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 325, in run_gatk
    log_error=log_error)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
```

See also the bcbio code that constructs the GenotypeGVCFs  call:
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/gatkjoint.py#L31

And the GATK4 GenotypeGVCFs   description page:
https://software.broadinstitute.org/gatk/documentation/tooldocs/4.beta.1/org_broadinstitute_hellbender_tools_walkers_GenotypeGVCFs.php

Thank you.

**Comment by NeillGibson** [comment]
The GATK 3.7  GenotypeGVCFs tool has --output or -o as the output argument for the tool. So they switched from -o to -O between version 3.7 and 4 beta1. 

Specifying --output should work for GATK3.7 and 4 beta 1. 

https://software.broadinstitute.org/gatk/documentation/tooldocs/3.7-0/org_broadinstitute_gatk_tools_walkers_variantutils_GenotypeGVCFs.php

**Comment by chapmanb** [comment]
Thanks Neill and sorry about the issues. I'll follow up on this in  #2012
