### ISSUE TITLE
Error while running vcfanno

### ISSUE THREAD

**Issue by apurwamishra** [chapmanb/bcbio-nextgen#2014]
Hi, 
Thanks so much for creating such a great pipeline. I'm currently running the bcbio pipeline on exam fastq files of a tumor/normal sample pair. While running the pipeline, it runs into an error in the vcfanno section. The error is shown below: 
```
[2017-07-20T05:00Z] vcfanno.go:112: [Flatten] unable to open file: /scratch/bcbio/genomes/Hsapiens/hg38//scratch/bcbio/genomes/Hsapiens/hg38/variation/exac.vcf.gz in /scratch/bcbio/genomes/Hsapiens/hg38

[2017-07-20T05:00Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /scratch/bcbio/anaconda/bin/vcfanno -p 8 -lua /scratch/bcbio/genomes/Hsapiens/hg38/config/vcfanno/gemini.lua -base-path /scratch/bcbio/genomes/Hsapiens/hg38 /scratch/bcbio/genomes/Hsapiens/hg38/config/vcfanno/gemini.conf /scratch/bcbio/work/gemini/1-mutect2-decompose-effects.vcf.gz | sed -e 's/Number=A/Number=1/g' | bgzip -c > /scratch/bcbio/work/bcbiotx/tmp_yYpvR/1-mutect2-decompose-effects-annotated-gemini.vcf.gz
=============================================
vcfanno version 0.2.6 [built with go1.8]
see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:112: [Flatten] unable to open file: /scratch/bcbio/genomes/Hsapiens/hg38//scratch/bcbio/genomes/Hsapiens/hg38/variation/exac.vcf.gz in /scratch/bcbio/genomes/Hsapiens/hg38
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/scratch/bcbio/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/scratch/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 188, in variant2pipeline
    samples = population.prep_db_parallel(samples, run_parallel)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 321, in prep_db_parallel
    output = parallel_fn("prep_gemini_db", to_process)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 298, in prep_gemini_db
    return population.prep_gemini_db(*args)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 30, in prep_gemini_db
    gemini_vcf = _run_vcfanno(gemini_vcf, data, use_gemini)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 50, in _run_vcfanno
    return vcfanno.run_vcfanno(gemini_vcf, conf_files, data, data_basepath)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfanno.py", line 84, in run_vcfanno
    out_file = vcfanno(vcf, out_file, conf_fns, data, data_basepath or basepath, lua_fns)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfanno.py", line 26, in vcfanno
    do.run(cmd.format(**locals()), message)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /scratch/bcbio/anaconda/bin/vcfanno -p 8 -lua /scratch/bcbio/genomes/Hsapiens/hg38/config/vcfanno/gemini.lua -base-path /scratch/bcbio/genomes/Hsapiens/hg38 /scratch/bcbio/genomes/Hsapiens/hg38/config/vcfanno/gemini.conf /scratch/bcbio/work/gemini/1-mutect2-decompose-effects.vcf.gz | sed -e 's/Number=A/Number=1/g' | bgzip -c > /scratch/bcbio/work/bcbiotx/tmp_yYpvR/1-mutect2-decompose-effects-annotated-gemini.vcf.gz
```

Has anyone else ran into such a problem? I'm not sure if this is an issue with the pipeline or because of an error from my end. If anyone could please help me out, I would very much appreciate it. 
Thanks in advance!

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. It appears as if we're accidentally specifying the path to the data files twice somewhere. I've been trying to dig into the code to figure out why this is but don't see an obvious reason why this would happen. If you look at your hg38 gemini configuration file:
```
/scratch/bcbio/genomes/Hsapiens/hg38/config/vcfanno/gemini.conf
```
Does it have relative paths, like the original configuration file:

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/vcfanno/hg38-gemini.conf

or absolute paths? If absolute paths, you could replace this with the correct version and see if that fixes the problem. I'm not sure how it could get absolutes there, but that seems like the easiest explanation for the error. Thanks for the help debugging and hope this helps.

**Comment by apurwamishra** [comment]
Hi Brad, 
Thanks for your prompt response. When I compared my hg38 gemini configuration file to the original configuration file, I see that the two files are the same in that my configuration file also has relative paths. But I also noticed one more thing while debugging. The file exact.vcf.gz is not found in /scratch/bcbio/genomes/Hsapiens/hg38/variation/. I have already tried downloading the hg38 genome again already with no avail. Is there no exact.vcf.gz file available for hg38 or is this an installation problem?

Just as a background, I am running this pipeline on exome fastq files and thus for the coverage_interval field in the sample file, I entered in regional for this field to indicate the exome analyses.

**Comment by apurwamishra** [comment]
Hi Brad, 
I think I was able to debug and figure out the error. I was missing the exact.vcf.gz file in /scratch/bcbio/genomes/Hsapiens/hg38/variation/ because I forgot to install the gemini tool. Once I did that, the pipeline finished up the analysis.
Thanks again for your help.

**Comment by chapmanb** [comment]
Thanks much for following up on this. Apologies for missing this obvious pointer and thanks for debugging and providing the necessary update for any future folks hitting this problem. Much appreciated.
