### ISSUE TITLE
Could not prepare index star for hg38-noalt by any method

### ISSUE THREAD

**Issue by drj11** [chapmanb/bcbio-nextgen#2019]
I have a problem when trying to install the `STAR` aligner with `hg38-noalt`.

Log ends with `Could not prepare index star for hg38-noalt by any method`.

```
ubuntu@ip-172-31-22-80:/mnt/f/2017-07-19/bcbio-2017-07-19$ tool/bin/bcbio_nextgen.py upgrade --aligners star
Upgrading bcbio
Upgrading bcbio-nextgen data files
Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x7feee804cd88>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /mnt/f/2017-07-19/bcbio-2017-07-19/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
INFO: Ubuntu setup
DBG [distribution.py]: Debian-shared setup
DBG [distribution.py]: Source=xenial
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['star', 'bwa', 'bowtie2', 'rtg'], 'genomes': [{'name': 'Human (GRCh37)', 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4'], 'annotations': ['GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase'], 'dbkey': 'GRCh37', 'indexes': ['seq']}, {'annotations': ['coverage', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'transcripts'], 'name': 'Human (hg38) without alternative alleles', 'dbkey': 'hg38-noalt'}], 'install_uniref': False}'): Human (GRCh37), Human (hg38) without alternative alleles
INFO: Genome preparation method ggd failed, trying next
INFO: Downloading genome from s3: hg38-noalt star
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: mkdir -p '/home/ubuntu/tmp/cloudbiolinux/7ffee5ab-c534-3ba2-9ec6-c15a8fb9a53c'
[localhost] local: wget --continue --no-check-certificate -O hg38-noalt-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg38-noalt-star.tar.xz'
--2017-07-25 10:07:12--  https://s3.amazonaws.com/biodata/genomes/hg38-noalt-star.tar.xz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.82.140
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.82.140|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-07-25 10:07:12 ERROR 404: Not Found.


Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O hg38-noalt-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg38-noalt-star.tar.xz''

INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome hg38-noalt with index star
[localhost] local: mkdir /mnt/f/2017-07-19/bcbio-2017-07-19/bcbio/genomes/Hsapiens/hg38-noalt/star
[localhost] local: export PATH=/mnt/f/2017-07-19/bcbio-2017-07-19/tool/bin:$PATH && STAR --genomeDir /mnt/f/2017-07-19/bcbio-2017-07-19/bcbio/genomes/Hsapiens/hg38-noalt/star --genomeFastaFiles /mnt/f/2017-07-19/bcbio-2017-07-19/bcbio/genomes/Hsapiens/hg38-noalt/seq/hg38-noalt.fa --runThreadN 1 --limitGenomeGenerateRAM 30000000000 --genomeChrBinNbits 14 --runMode genomeGenerate --genomeSAindexNbases 14
Jul 25 10:07:45 ..... started STAR run
Jul 25 10:07:45 ... starting to generate Genome files
Jul 25 10:08:56 ... starting to sort Suffix Array. This may take a long time...
Jul 25 10:09:13 ... sorting Suffix Array chunks and saving them to disk...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Fatal error: local() encountered an error (return code 134) while executing 'export PATH=/mnt/f/2017-07-19/bcbio-2017-07-19/tool/bin:$PATH && STAR --genomeDir /mnt/f/2017-07-19/bcbio-2017-07-19/bcbio/genomes/Hsapiens/hg38-noalt/star --genomeFastaFiles /mnt/f/2017-07-19/bcbio-2017-07-19/bcbio/genomes/Hsapiens/hg38-noalt/seq/hg38-noalt.fa --runThreadN 1 --limitGenomeGenerateRAM 30000000000 --genomeChrBinNbits 14 --runMode genomeGenerate --genomeSAindexNbases 14'

Aborting.
INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "tool/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/f/2017-07-19/bcbio-2017-07-19/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/f/2017-07-19/bcbio-2017-07-19/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/mnt/f/2017-07-19/bcbio-2017-07-19/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/mnt/f/2017-07-19/bcbio-2017-07-19/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/mnt/f/2017-07-19/bcbio-2017-07-19/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/mnt/f/2017-07-19/bcbio-2017-07-19/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/mnt/f/2017-07-19/bcbio-2017-07-19/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 338, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/mnt/f/2017-07-19/bcbio-2017-07-19/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 479, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index star for hg38-noalt by any method
```

**Comment by drj11** [comment]
Following advice on, I re-ran with `--cores 4` (4 core AWS instance):

`tool/bin/bcbio_nextgen.py upgrade --aligners star --cores 4`

That appeared to work, but was far too quick to convince me. What is a good test to test using the `STAR` aligner?

**Comment by roryk** [comment]
Hi David,

I think you'll need to delete /mnt/f/2017-07-19/bcbio-2017-07-19/bcbio/genomes/Hsapiens/hg38-noalt/star and rerun the 

```
tool/bin/bcbio_nextgen.py upgrade --aligners star --cores 4
```

command. I think that should fail as well, though. The original error is due to STAR not having enough memory; it needs somewhere around 40 GB to make the index. Is there that much available on the machine you are on?

**Comment by drj11** [comment]
ah, cool. thanks.

I will delete that, and re-run it.

I have less than 40 GB at the moment; I will buy a bigger instance...

Is this just a well known fact about STAR? Is there a handy table somewhere of how much RAM/CPU you will roughly need? Can we make one?

**Comment by roryk** [comment]
Hi David,

Yeah, it's just a well known fact about STAR-- the genome generation takes a huge amount of RAM, and results in a file that is pretty big so we can't really distribute it.

**Comment by roryk** [comment]
Thanks! Feel free to reopen if that doesn't fix it, I'm pretty sure it should be all set though.
