### ISSUE TITLE
Check for invalid values in the aligner: section of the configuration

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2024]
By mistake, an `aligner:` section was set to `true` instead of `bowtie2`, and this caused bcbio to fail with a strange traceback:

```python
Traceback (most recent call last):  File "/storage/rozo/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>    main(**kwargs)  File "/storage/rozo/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main    run_main(**kwargs)  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main    fc_dir, run_info_yaml)  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 349, in chipseqpipeline    multiplier=alignprep.parallel_multiplier(samples)) as run_parallel:  File "/storage/rozo/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__    return self.gen.next()  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 43, in start    max_multicore=max_multicore)  File "/storage/rozo/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/resources.py", line 203, in calculate    progs=", ".join(progs), memory=", ".join("%.2f" % x for x in all_memory),TypeError: sequence item 0: expected string, bool found
```

The reason is that `algs` in that same file contained a `True` value for the aligner, which caused the error down the road.

**Comment by chapmanb** [comment]
Luca;
Thanks much for the heads up on the problem. I pushed a fix to avoid this confusing error message, allowing bcbio to proceed on to the algorithm linting and raise a problem error about this incorrect specification. Please let us know if you run into any other problems at all and thanks again.
