### ISSUE TITLE
samblaster: Unable to write to output file. [fputs] Broken pipe

### ISSUE THREAD

**Issue by egorrevkov** [chapmanb/bcbio-nextgen#2032]
Hi,

I've been running the analysis with bcbio installed on EBS volume connected to a single c4.2xlarge AWS instance, here's the config file: 
```
details:
-  algorithm:
     platform: illumina
     quality_format: standard
     aligner: bwa
     save_diskspace: true
     tools_off: fastqc
     bam_clean: false
     bam_sort: false
     mark_duplicates: true
     recalibrate: false
     realign: gatk
     variant_regions: /mnt/work/test_1/data/SeqCap_target_1000genome.bed
     remove_lcr: false
     variantcaller: [mutect2,freebayes,vardict,varscan]
     svcaller: [lumpy,manta,cnvkit]
     indelcaller: false
     ensemble:
       numpass: 2
   analysis: variant2
   description: GIS-A144-T-S32-E-N
   files: /mnt/work/test_1/data/HS004-PE-R00121_BC6KTUANXX.human_g1k_v37.CHL506_reAligned_reCal.bam
   genome_build: GRCh37
   metadata:
     batch: GIS-A144-T-S32-E
     phenotype: normal
-  algorithm:
     platform: illumina
     quality_format: standard
     aligner: bwa
     save_diskspace: true
     tools_off: fastqc
     bam_clean: false
     bam_sort: false
     mark_duplicates: true
     recalibrate: false
     realign: gatk
     variant_regions: /mnt/work/test_1/data/SeqCap_target_1000genome.bed
     remove_lcr: false
     variantcaller: [mutect2,freebayes,vardict,varscan]
     svcaller: [lumpy,manta,cnvkit]
     indelcaller: false
     ensemble:
       numpass: 2
   analysis: variant2
   description: GIS-A144-T-S32-E-T
   files: /mnt/work/test_1/data/HS004-PE-R00121_BC6KTUANXX.human_g1k_v37.CHL481_reAligned_reCal.bam
   genome_build: GRCh37
   metadata:
     batch: GIS-A144-T-S32-E
     phenotype: tumor
fc_date: '2015-07-31'
fc_name: GIS-A144-T-S32-E
upload:
 dir: /mnt/work/test_2/bcbio_final
```
and I keep getting the error, which looks like this in bcbio-nextgen-debug.log:
```
[2017-08-04T08:12Z] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2017-08-04T08:12Z] [M::mem_pestat] (25, 50, 75) percentile: (159, 199, 251)
[2017-08-04T08:12Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 435)
[2017-08-04T08:12Z] [M::mem_pestat] mean and std.dev: (208.86, 66.35)
[2017-08-04T08:12Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 527)
[2017-08-04T08:12Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2017-08-04T08:12Z] [M::mem_pestat] skip orientation RR as there are not enough pairs
[2017-08-04T08:12Z] samblaster: Unable to write to output file.
[2017-08-04T08:12Z] [fputs] Broken pipe
[2017-08-04T08:12Z] /bin/bash: line 1: 12125 Exit 1                  /mnt/work/bcbio/galaxy/../anaconda/bin/bwa mem $
[2017-08-04T08:12Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /mnt/work/bcbio/galaxy/../anaconda/bin/bwa mem   -c$
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (98, 8237, 8281)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 24647)
[M::mem_pestat] mean and std.dev: (5304.03, 3837.17)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 32830)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation FF as there are not enough pairs

...(several more [M::mem_pestat] entries)...

[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (159, 199, 251)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 435)
[M::mem_pestat] mean and std.dev: (208.86, 66.35)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 527)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
samblaster: Unable to write to output file.
[fputs] Broken pipe
/bin/bash: line 1: 12125 Exit 1                  /mnt/work/bcbio/galaxy/../anaconda/bin/bwa mem -c 250 -M -t 7 -R '@$
     12126                       | /mnt/work/bcbio/galaxy/../anaconda/bin/samblaster --addMateTags -M --splitterFile$
     12127 Killed                  | /mnt/work/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 7 -m 1G -T /mnt/work$
' returned non-zero exit status 137
```
Here's my bcbio_system.yaml (since the instance has 15GiB and 8 vCPUs):
```
galaxy_config: universe_wsgi.ini
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx3500m
    memory: 2G
  dexseq:
    memory: 10g
  express:
    memory: 8g
  gatk:
    dir: /mnt/work/bcbio/toolplus/gatk/3.6-0-g89b7209
    jvm_opts:
    - -Xms500m
    - -Xmx3500m
  macs2:
    memory: 8g
  qualimap:
    memory: 4g
  seqcluster:
    memory: 8g
  snpeff:
    jvm_opts:
    - -Xms750m
    - -Xmx3g
```
and I run this command to start it 
```
bcbio_nextgen.py ../config/test_2.yaml -n 7
```

Also, if I change the config to **mark_duplicates: false** and delete **lumpy** from **svcaller** (in hopes to avoid using samblaster) the analysis proceeds and finishes just fine.
I've looked at similar issues but nothing really seem to help in my case. I thought that there may be something wrong with the memory setup, but I can't really figure what exactly.
 
Could you please provide some advice? 

Thanks in advance,
Egor

**Comment by chapmanb** [comment]
Egor;
Thanks for the detailed report and sorry about the problem. The 'Killed' message in the output indicates the operating system is stopping one or more of the processes in the pipe, likely due to memory issues. The memory on c4 instances is pretty tight at 2Gb/core and memory usage on both bwa and sambamba is not bounded so we can't set how much they'll use.

If you need to use this instance type you can either:

- unset lumpy, in which case bcbio will use bamsormadup which does have memory bounds.
- Increase the memory/core allocation in your bcbio_system.yaml file so bcbio uses less cores per process (and thus less memory for sorting).

If you want lumpy output, then I'd suggest moving to a m4 instance type which has more memory/core and should work better.

Hope this helps

**Comment by egorrevkov** [comment]
Brad,

Thank you for the comment, switching instances did help to proceed further. Unfortunately, I've encountered another error with the same setup (different instance though, m4.x2large, 8 cores x 4 GiB) 
```
[2017-08-07T12:09Z] Index BAM file with sambamba: GIS-A144-T-S32-E-T-sort-Y_15526581_59222328-prep-prealign.bam
[2017-08-07T12:09Z] GATK RealignerTargetCreator: GIS-A144-T-S32-E-T-sort-Y_15526581_59222328-prep-prealign.bam Y:15526582-59222328
[2017-08-07T12:09Z] GATK: RealignerTargetCreator
[2017-08-07T12:09Z] INFO  12:09:18,984 Walker - [REDUCE RESULT] Traversal result is: org.broadinstitute.gatk.engine.io.stubs.SAMFileWriterStub@6cc8da1c
[2017-08-07T12:09Z] INFO  12:09:18,995 ProgressMeter -            done    818861.0    26.0 s      32.0 s      100.0%    26.0 s       0.0 s
[2017-08-07T12:09Z] INFO  12:09:18,996 ProgressMeter - Total runtime 26.76 secs, 0.45 min, 0.01 hours
[2017-08-07T12:09Z] INFO  12:09:18,998 MicroScheduler - 930 reads were filtered out during the traversal out of approximately 819791 total reads (0.11%)
[2017-08-07T12:09Z] INFO  12:09:18,999 MicroScheduler -   -> 0 reads (0.00% of total) failing BadCigarFilter
[2017-08-07T12:09Z] INFO  12:09:18,999 MicroScheduler -   -> 0 reads (0.00% of total) failing MalformedReadFilter
[2017-08-07T12:09Z] INFO  12:09:18,999 MicroScheduler -   -> 930 reads (0.11% of total) failing NotPrimaryAlignmentFilter
[2017-08-07T12:09Z] ------------------------------------------------------------------------------------------
[2017-08-07T12:09Z] Done. There were no warn messages.
[2017-08-07T12:09Z] ------------------------------------------------------------------------------------------
[2017-08-07T12:09Z] Index BAM file with sambamba: GIS-A144-T-S32-E-T-sort-1_108853084_142653859-prep-prealign.bam
[2017-08-07T12:09Z] ##### ERROR ------------------------------------------------------------------------------------------
[2017-08-07T12:09Z] ##### ERROR A USER ERROR has occurred (version 3.6-0-g89b7209):
[2017-08-07T12:09Z] ##### ERROR
[2017-08-07T12:09Z] ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2017-08-07T12:09Z] ##### ERROR The error message below tells you what is the problem.
[2017-08-07T12:09Z] ##### ERROR
[2017-08-07T12:09Z] ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2017-08-07T12:09Z] ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2017-08-07T12:09Z] ##### ERROR
[2017-08-07T12:09Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2017-08-07T12:09Z] ##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
[2017-08-07T12:09Z] ##### ERROR
[2017-08-07T12:09Z] ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
[2017-08-07T12:09Z] ##### ERROR
[2017-08-07T12:09Z] ##### ERROR MESSAGE: Invalid command line: Malformed walker argument: Could not find walker with name: RealignerTargetCreator
[2017-08-07T12:09Z] ##### ERROR ------------------------------------------------------------------------------------------
[2017-08-07T12:09Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; java -Xms250m -Xmx1750m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/work/test_2/tmp/bcbiotx/tmptdhEOw -jar /mnt/work/bcbio/toolplus/gatk/3.6-0-g89b7209/GenomeAnalysisTK.jar -T RealignerTargetCreator -I /mnt/work/test_2/tmp/bamprep/GIS-A144-T-S32-E-T/Y/GIS-A144-T-S32-E-T-sort-Y_15526581_59222328-prep-prealign.bam -R /mnt/work/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -o /mnt/work/test_2/tmp/bcbiotx/tmpGwO_zc/GIS-A144-T-S32-E-T-sort-Y_15526581_59222328-prep-prealign-realign.intervals -l INFO -L Y:15526582-59222328 --interval_set_rule INTERSECTION --known /mnt/work/bcbio/genomes/Hsapiens/GRCh37/variation/Mills_and_1000G_gold_standard.indels.vcf.gz -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.6-0-g89b7209):
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to
##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Invalid command line: Malformed walker argument: Could not find walker with name: RealignerTargetCreator
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
[2017-08-07T12:09Z] GATK re-alignment ('15', 0, 20084290) : GIS-A144-T-S32-E-T
Traceback (most recent call last):
  File "/mnt/work/bcbio/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/mnt/work/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 150, in variant2pipeline
    samples = region.parallel_prep_region(samples, run_parallel)
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 146, in parallel_prep_region
    "piped_bamprep", _add_combine_info, file_key, ["config"])
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 812, in __call__
    self.retrieve()
  File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 749, in retrieve
    exception = exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```
Couldn't really find a working solution on GATK forums. What surprises me is that GATK actually uses RealignerTargetCreator walker for some parts of data at first (at the beginning of the log above), but then complains that it can't find it for something else. I've thought that that may be a memory per core issue again, but changing that did not help. 

Could you please assist me with this one?

Thank you for your time,
Egor

**Comment by egorrevkov** [comment]
Brad;

Thanks a lot, the pipeline seems to be working fine now!

-Egor

**Comment by egorrevkov** [comment]
I'm sorry to reopen the issue, but I think my question is sort of related to the previous ones and I couldn't find a solution anywhere else.
Could you suggest an automated way to profile memory/cpu usage for the bcbio pipeline running on a single AWS instance (to compare the performances between different instances / cluster setup)? I've been thinking of using Amazon's CloudWatch, but maybe you can suggest something better.

Thanks in advance,
Egor

**Comment by ohofmann** [comment]
Ping @brainstorm

**Comment by brainstorm** [comment]
Hi @egorrevkov, I've been meaning to revisit this in the near future but still have not come to it fully, but our options lined up for testing on the commercial side right now are:

https://www.datadoghq.com/
https://signalfx.com/

Which provide brief trial periods to assess their functionality and ease the heavy lifting/maintenance of deploying custom monitoring solutions such as:

https://aws.amazon.com/blogs/aws/new-cloudwatch-plugin-for-collectd/
https://prometheus.io/

We'll see which comes up first for us since sooner or later we do need to put some "eagles eye view" monitoring in place.

Hope that helps!

**Comment by egorrevkov** [comment]
Thanks, @brainstorm, this is helpful, will take a look at these.
