### ISSUE TITLE
Freebayes UnboundLocalError: local variable 'ann_file' referenced before assignment

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#2035]
Hello Brad,

Sorry to trouble you again. I met with a weird issue that I didn't see before previously although I've ran the upgraded pipeline twice already. The traceback is as follows:
[2017-08-08T03:15Z] multiprocessing: variantcall_sample
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 152, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 193, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 254, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 329, in variantcall_sample
    call_file = caller_fn(align_bams, items, ref_file, assoc_files, region, call_file)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 96, in run_freebayes
    ref_file, assoc_files, region, out_file)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 207, in _run_freebayes_paired
    return ann_file
UnboundLocalError: local variable 'ann_file' referenced before assignment

By the way, I already have dbsnp-150.vcf.gz and the .tbi in my variations folder. So I don't get why I'm seeing this error.

Edit:
Just a wild guess here but the gemini annotations directory seem to only have dbsnp147, maybe that's causing the issue?
annotation_dir: /mnt/projects/dlho/tancrc/bcbio_pipeline/gemini_data
versions:
  ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.sites.tidy.vcf.gz: 4
  ESP6500SI.all.snps_indels.tidy.v2.vcf.gz: 2
  ExAC.r0.3.sites.vep.tidy.vcf.gz: 4
  GRCh37-gms-mappability.vcf.gz: 2
  clinvar_20170130.tidy.vcf.gz: 5
  cosmic-v68-GRCh37.tidy.vcf.gz: 3
  dbsnp.b147.20160601.tidy.vcf.gz: 1
  detailed_gene_table_v75: 2
  geno2mp.variants.tidy.vcf.gz: 1
  hg19.rmsk.bed.gz: 2
  summary_gene_table_v75: 2
  whole_genome_SNVs.tsv.compressed.gz: 2

**Comment by chapmanb** [comment]
Thank you for the report and apologies about the problem. This is a bug from refactoring FreeBayes handling of annotation files -- we didn't correctly rename a variable after annotation moved into a different scope resulting in this error on re-runs of FreeBayes. I pushed a fix to the latest development version so if you update with `bcbio_nextgen.py upgrade -u development` it should hopefully work cleanly. Thanks again for reporting this.

**Comment by phu5ion** [comment]
Thanks Brad. Sorry to report an unrelated issue here but I didn't want to open up a new one. Since upgrading I realised GATK also upgraded to 3.8. While installing I met with the following issue:
[dlho@n006 /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170727_set2PDX_newell_steph/bcbio]gatk-register ~/software/gatk-3.8/GenomeAnalysisTK-3.8-0.tar.bz2
ENV_PREFIX /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda
Processing GenomeAnalysisTK-3.8-0.tar.bz2 as *.tar.bz2
Extracting GenomeAnalysisTK-3.8-0.tar.bz2
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
GenomeAnalysisTK-3.8-0-ge9d806836/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar
Error: Unable to access jarfile ./GenomeAnalysisTK.jar
The version of the jar specified, , does not match the version expected by conda: 3.8

**Comment by chapmanb** [comment]
Sorry about the problem, you can run:
```
gatk-register --noversioncheck ~/software/gatk-3.8/GenomeAnalysisTK-3.8-0.tar.bz2
```
and it will register the jar correctly, skipping the versioning check. I'll update the bioconda package to 3.8 as well so you won't have this problem in the future.

bcbio should be compatible with 3.8, please let me know if you run into any issues. We've been working hard on GATK4 compatibility but leaving the 3.x support in place.

**Comment by phu5ion** [comment]
Hi Brad,

I tried the --noversioncheck already, there's still a problem (btw --noversioncheck has to come right at the end for the command to work):
[dlho@n006 ~]gatk-register /home/dlho/software/gatk-3.8/GenomeAnalysisTK-3.8-0.tar.bz2 --noversioncheck
ENV_PREFIX /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda
Processing GenomeAnalysisTK-3.8-0.tar.bz2 as *.tar.bz2
Extracting GenomeAnalysisTK-3.8-0.tar.bz2
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
GenomeAnalysisTK-3.8-0-ge9d806836/
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar
Moving GenomeAnalysisTK-3.8-0.tar.bz2 to /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/opt/gatk-3.8
mv: cannot stat `./GenomeAnalysisTK.jar': No such file or directory

**Comment by chapmanb** [comment]
Sorry about the bad advice, it looks like `gatk-register` with `--noversioncheck` only works if you pass a jar file so if you untar that file and pass in the jar instead of the `.tar.bz2` it'll work. Alternatively, gatk was updated three days ago so if you do:
```
bcbio_conda install -c conda-forge -c bioconda gatk
```
it'll get the 3.8 version then you can run with the `.tar.bz2` directly. Hope this fixes it for you.
