### ISSUE TITLE
Somatic variant call with GATK4 mutect2

### ISSUE THREAD

**Issue by hh1985** [chapmanb/bcbio-nextgen#2037]
Hi 
I turned on the gatk4 switch, and use mutect2 for cancer-dream-syn3 dataset.  The pipeline stopped at BaseRecalibrator step.  The error is as follows:

```
[2017-08-09T09:53Z] Running:
[2017-08-09T09:53Z]     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsnappy.disable=true -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.t
mpdir=/mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/bcbiotx/tmpOBs3zG -jar /usr/local/share/bcbio/anaconda/share/gatk4-4.0b3-0/gatk-package-4.beta.3-local.jar BaseRecalibratorSpark -I /mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/ali
gn/syn3-tumor/syn3-tumor-sort.bam --sparkMaster local[16] --output /mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/bcbiotx/tmpOBs3zG/syn3-tumor-sort-recal.grp --reference None --knownSites /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation
/dbsnp-150.vcf.gz -L /mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/bedprep/NGv3.bed --interval_set_rule INTERSECTION
[2017-08-09T09:53Z] 09:53:51.710 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/bcbio/anaconda/share/gatk4-4.0b3-0/gatk-package-4.beta.3-local.jar!/com/intel/gkl/native/libgkl_compression.so
[2017-08-09T09:53Z] [August 9, 2017 9:53:51 AM UTC] BaseRecalibratorSpark  --knownSites /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp-150.vcf.gz --output /mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/bcbiotx/tmpOBs3zG/syn3-tum
or-sort-recal.grp --reference None --input /mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/align/syn3-tumor/syn3-tumor-sort.bam --intervals /mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/bedprep/NGv3.bed --interval_set_rule INTERSECTION
 --sparkMaster local[16]  --joinStrategy BROADCAST --mismatches_context_size 2 --indels_context_size 3 --maximum_cycle_value 500 --mismatches_default_quality -1 --insertions_default_quality 45 --deletions_default_quality 45 --low_quality_tail 2 --quanti
zing_levels 16 --bqsrBAQGapOpenPenalty 40.0 --preserve_qscores_less_than 6 --enableBAQ false --computeIndelBQSRTables false --useOriginalQualities false --defaultBaseQualities -1 --readShardSize 10000 --readShardPadding 1000 --readValidationStringency S
ILENT --interval_padding 0 --interval_exclusion_padding 0 --bamPartitionSize 0 --disableSequenceDictionaryValidation false --shardedOutput false --numReducers 0 --help false --version false --showHidden false --verbosity INFO --QUIET false --use_jdk_def
later false --use_jdk_inflater false --disableToolDefaultReadFilters false
[2017-08-09T09:53Z] [August 9, 2017 9:53:51 AM UTC] Executing as root@cpuserver on Linux 4.4.0-81-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Version: 4.beta.3
[2017-08-09T09:53Z] 09:53:51.838 INFO  BaseRecalibratorSpark - HTSJDK Defaults.COMPRESSION_LEVEL : 1
[2017-08-09T09:53Z] 09:53:51.838 INFO  BaseRecalibratorSpark - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
[2017-08-09T09:53Z] 09:53:51.839 INFO  BaseRecalibratorSpark - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
[2017-08-09T09:53Z] 09:53:51.839 INFO  BaseRecalibratorSpark - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
[2017-08-09T09:53Z] 09:53:51.839 INFO  BaseRecalibratorSpark - Deflater: IntelDeflater
[2017-08-09T09:53Z] 09:53:51.839 INFO  BaseRecalibratorSpark - Inflater: IntelInflater
[2017-08-09T09:53Z] 09:53:51.839 INFO  BaseRecalibratorSpark - GCS max retries/reopens: 20
[2017-08-09T09:53Z] 09:53:51.839 INFO  BaseRecalibratorSpark - Using google-cloud-java patch 317951be3c2e898e3916a4b1abf5a9c220d84df8
[2017-08-09T09:53Z] 09:53:51.839 INFO  BaseRecalibratorSpark - Initializing engine
[2017-08-09T09:53Z] 09:53:51.839 INFO  BaseRecalibratorSpark - Done initializing engine
[2017-08-09T09:53Z] Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SparkContext: Running Spark version 2.0.2
[2017-08-09T09:53Z] 17/08/09 09:53:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2017-08-09T09:53Z] 17/08/09 09:53:52 WARN Utils: Your hostname, cpuserver resolves to a loopback address: 127.0.1.1; using 10.10.10.13 instead (on interface eno1)
[2017-08-09T09:53Z] 17/08/09 09:53:52 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SecurityManager: Changing view acls to: root
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SecurityManager: Changing modify acls to: root
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SecurityManager: Changing view acls groups to:
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SecurityManager: Changing modify acls groups to:
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with
modify permissions: Set()
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO Utils: Successfully started service 'sparkDriver' on port 34259.
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SparkEnv: Registering MapOutputTracker
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SparkEnv: Registering BlockManagerMaster
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO DiskBlockManager: Created local directory at /mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/bcbiotx/tmpOBs3zG/root/blockmgr-d08e9d96-65d5-475d-8cde-bd39da57a501
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO MemoryStore: MemoryStore started with capacity 1665.6 MB
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SparkEnv: Registering OutputCommitCoordinator
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.10.10.13:4040
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO Executor: Starting executor ID driver on host localhost
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 43091.
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO NettyBlockTransferService: Server created on 10.10.10.13:43091
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.10.10.13, 43091)
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO BlockManagerMasterEndpoint: Registering block manager 10.10.10.13:43091 with 1665.6 MB RAM, BlockManagerId(driver, 10.10.10.13, 43091)
[2017-08-09T09:53Z] 17/08/09 09:53:52 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.10.10.13, 43091)
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO SparkUI: Stopped Spark web UI at http://10.10.10.13:4040
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO MemoryStore: MemoryStore cleared
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO BlockManager: BlockManager stopped
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO BlockManagerMaster: BlockManagerMaster stopped
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO SparkContext: Successfully stopped SparkContext
[2017-08-09T09:53Z] 09:53:53.159 INFO  BaseRecalibratorSpark - Shutting down engine
[2017-08-09T09:53Z] [August 9, 2017 9:53:53 AM UTC] org.broadinstitute.hellbender.tools.spark.BaseRecalibratorSpark done. Elapsed time: 0.02 minutes.
[2017-08-09T09:53Z] Runtime.totalMemory()=460259328
[2017-08-09T09:53Z] java.lang.IllegalArgumentException: Null object is not allowed here.
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:554)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:542)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.engine.datasources.ReferenceAPISource.<init>(ReferenceAPISource.java:73)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.engine.datasources.ReferenceMultiSource.<init>(ReferenceMultiSource.java:52)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReference(GATKSparkTool.java:393)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:360)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:351)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:173)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:192)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
[2017-08-09T09:53Z]     at org.broadinstitute.hellbender.Main.main(Main.java:233)
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO ShutdownHookManager: Shutdown hook called
[2017-08-09T09:53Z] 17/08/09 09:53:53 INFO ShutdownHookManager: Deleting directory /mnt/data/Datasets/benchmarking/cancer-dream-syn3/work2/bcbiotx/tmpOBs3zG/root/spark-98ecbaa6-d225-495f-b997-f68d42ed9f43
[2017-08-09T09:53Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)

```

I use bcbio_nextgen inside a docker container to keep the environment clean.  The host server is behind firewall which requires VPN to access. Not sure if this has anything to do with the firewall. It would be nice if I can use the local version of GATK4 directly...

**Comment by chapmanb** [comment]
Thanks for the detailed report and apologies for the problem. It looks like the failure is due to not finding ucsc 2bit references in your install (see the `--reference None` argument in your command line).

GATK4 BQSR requires a 2bit indexed genome which was only added to bcbio installs in the past couple of weeks. If you do:
```
bcbio_nextgen.py upgrade --data
```
it should hopefully pull them in so things will work on a retry. Hope this helps.

**Comment by hh1985** [comment]
@chapmanb By upgrading the data, the GATK4 BaseRecalibrator step was successfully finished.  Thanks a lot!

During the test, I found two more issues:
1) When I set -n as 8, each job was assigned 31g memory.   However, our server only has 128G memory in total. This caused the ApplyBQSR step to fail.  When I set -n to 4, each job was assigned 16g memory. After that, the ApplyBQSR step can be finished.
2) RealignerTargetCreator do not exist in GATK4.  The pipeline failed in this step.  My understanding is that indel realignment is no longer necessary for pipeline with mutect2 and haplotypcaller.  I can turn off the realign switch in yaml file.  But this also means tools like vardict and freebayes cannot benefit from realignment step.  A possible workaround is to skip the realignment step for GATK4 even when the realign switch is on.

**Comment by chapmanb** [comment]
Thanks much for following up. I'm happy that BQSR finished sucessfully. For your issues:

1. How much memory did you want bcbio to allocate? It sounds like your machine has 4Gb/core and bcbio allocated just under this for an 8 core job. Were there other processes running causing the memory problems?
2. Realignment is not supported in GATK4 and is generally not needed. I've added in a linting check and useful error message if specified with GATK4. I'd rather folks know that it's not running instead of silently skipping it. FreeBayes and VarDict both do local realignment so don't require a separate step and in general realignment does not contribute a lot to most modern callers.

Thanks again for the feedback and testing.

**Comment by hh1985** [comment]
@chapmanb Thanks a lot! That's really very helpful!
1) Now I understand the allocation way.  That makes sense. The error I received was page allocation error. It sounds like a Spark thing. Is it possible to use the local version of gatk4 directly instead of single-machine Spark?
2) Thanks a lot for the quick update and information of indel realignment.

I successfully finished the whole pipeline after a few rerunning.  There was once a Java core dump error in the snpeff step, but the error seems not reproducible.  I will try more clean run of the pipeline later.

**Comment by chapmanb** [comment]
It sounds like you're hitting inconsistent Java memory errors. Unfortunately openjdk seems to intermittently run into these on some systems, but I don't have a good idea about how best to debug/improve them other than restarting the pipeline.

For BQSR, the reason we use Spark here is that it provides a multicore implementation. We could use the local version but that uses a single thread so will be quite slow. If you can't make BQSR work at all with multiple threads happy to explore less memory usage or falling back to the single thread approach. If it's all intermittent java memory and core dump errors though, that probably won't help too much.

Thanks again for helping with debugging.

**Comment by hh1985** [comment]
@chapmanb Thanks for the explanation!  There's uncertainty here... When I set up environment and tools, I usually install Java-based tools manually instead of using bioconda to avoid potential instability problem.  Is it possible to configure the JAVA version in bcbio-nextgen?  I remember that GATK only officially supports oracle java.

**Comment by chapmanb** [comment]
We don't have a way to override the Java version right now. We did but it caused all kinds of issues with accidentally using the system Java (which is often Java 7) instead of the bcbio installed one, so we backed it out and now ensure use of the bcbio installed one. You're right that GATK does not officially support openjdk but that has always been the case and we've gotten by using openjdk for quite a long time. The snpEff issues you saw also indicate it might be something related to the system and openjdk rather than GATK itself. If you're able to identify what is going on I'm happy to think about ways to fix the java we ship or otherwise improve behavior. Thanks again.

**Comment by chapmanb** [comment]
Thanks for the thoughts and apologies for being slow in implementing a work around. The latest development version (`bcbio_nextgen.py upgrade -u development`) now allows setting `BCBIO_JAVA_HOME` (docs here: http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated) with a specific java version to use. bcbio will then use this in place of the local version (for GATK and snpEff right now).

Hopefully this will let you test with the system installed Oracle Java 8 to see if it improves stability. Thanks again for all the discussion.

**Comment by hh1985** [comment]
@chapmanb Thank you so much!
