### ISSUE TITLE
ValueError: Processing failed on GEMINI chunk load

### ISSUE THREAD

**Issue by rpauly** [chapmanb/bcbio-nextgen#2038]
Hi,
I am running gemini v 0.20.1
when I try to run:
gemini load -v sample13_snpeff.vcf -t snpEff --cores 270 sample13.vcf.db, I get 

CADD scores are not being loaded because the annotation file could not be found.
`Run gemini update --dataonly --extra cadd_score` to install the annotation file.
GERP per bp is not being loaded because the annotation file could not be found.
    Run `gemini update --dataonly --extra gerp_bp` to install the annotation file.

/bin/sh: gemini: command not found
/bin/sh: gemini: command not found
/bin/sh: gemini: command not found
/bin/sh: gemini: command not found
/bin/sh: gemini: command not found
/bin/sh: gemini: command not found

Traceback (most recent call last):
  File "/zfs/aksggc/rpauly/gemini-master/exes/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/zfs/aksggc/rpauly/gemini-master/TPDs/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1248, in main
    args.func(parser, args)
  File "/zfs/aksggc/rpauly/gemini-master/TPDs/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 204, in load_fn
    gemini_load.load(parser, args)
  File "/zfs/aksggc/rpauly/gemini-master/TPDs/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 49, in load
    load_multicore(args)
  File "/zfs/aksggc/rpauly/gemini-master/TPDs/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 93, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/zfs/aksggc/rpauly/gemini-master/TPDs/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 264, in load_chunks_multicore
    wait_until_finished(procs)
  File "/zfs/aksggc/rpauly/gemini-master/TPDs/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 359, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load

Any thoughts?

~Rini

**Comment by chapmanb** [comment]
Rini;
Unless this is a bcbio problem, the best place to raise this issue would probably be the GEMINI repository (https://github.com/arq5x/gemini).

To try and help from our side, it looks like the `gemini` executable is not in your path so when it tries to run the load job in parallel can't find it. You should be able to add: `/zfs/aksggc/rpauly/gemini-master/TPDs/anaconda/bin` to your PATH and resolve the issue. Hope this helps.
