### ISSUE TITLE
ValueError:Check tool-data/*.loc files to ensure paths to reference data are correct.

### ISSUE THREAD

**Issue by npbhavya** [chapmanb/bcbio-nextgen#2046]
Here is my command 
bcbio_nextgen.py  /cancer-dream-syn3/config/cancer-dream-syn3.yaml. 

I have installed bcbio on out cluster and the genomes in another folder and symlinked it to bcbio folder. This is giving me the following error "Check tool-data/*.loc files to ensure paths to reference data are correct", which i cant find in my installation. 

Here is my complete blog.
Sun/Oracle Java Runtime Environment version 1.8.0_73 loaded.
bcbio version 1.0.4 loaded.
[2017-08-24T18:09Z] System YAML configuration: /gpfs/hps/soft/rhel6/bcbio/1.0.4/local/share/bcbio/galaxy/bcbio_system.yaml
[2017-08-24T18:09Z] Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2017-08-24T18:09Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2017-08-24T18:09Z] Timing: organize samples
[2017-08-24T18:09Z] multiprocessing: organize_samples
[2017-08-24T18:09Z] Using input YAML configuration: /N/dc2/scratch/bhnala/bcbioRuns/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2017-08-24T18:09Z] Checking sample YAML configuration: /N/dc2/scratch/bhnala/bcbioRuns/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2017-08-24T18:09Z] Downloading /N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/genomes/Hsapiens/GRCh37 samtools from AWS
[2017-08-24T18:09Z] Downloading /N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/genomes/Hsapiens/GRCh37 bwa from AWS
Traceback (most recent call last):
  File "/N/soft/rhel6/bcbio/1.0.4/local/bin//bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/N/soft/rhel6/bcbio/1.0.4/local/bin//bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 119, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 350, in organize_samples
    return run_info.organize(*args)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 70, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 163, in add_reference_resources
    _check_ref_files(data["reference"], data)
  File "/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 209, in _check_ref_files
    raise ValueError(msg + "\n".join(problems) + "\n")
ValueError: 
Problems with input reference file None
Did not find fasta reference file for genome /N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/genomes/Hsapiens/GRCh37.
Check tool-data/*.loc files to ensure paths to reference data are correct.

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issues. It sounds like your symlinking approach didn't let bcbio find the right files but it's tough to suggest specific fixes without knowing more about your setup. The files that point at the references and indices should be in:
```
 /N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/galaxy/tool-data/
```
Are these present and pointing to the correct files in ` /N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/genomes`? Hope that helps with debugging the issue. If not, providing more details about where the files are might help me suggest other ideas.

**Comment by npbhavya** [comment]
It seems that i dont have a a tool-data subdirectory under galaxy at all.
If i run the "bcbio_nextgen.py upgrade" will it help or do i have to
reinstall the whole tool.

Thank You,


Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by chapmanb** [comment]
Bhavya;
Thanks for following up on this. That's unexpected, is it possible the `tool-data` directory is available in the secondary install where you installed the data and then symlinked over?

Either way, if the data is in the right place you should be able to do:
```
bcbio_nextgen.py upgrade --data
```
and bcbio should find all the existing files and write out a `tool-data` directory for this existing install. Hope this works.

**Comment by npbhavya** [comment]
Thank You,

the command so far seems to work so hopefully it will download the missing
or maybe just deleted files.

Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by npbhavya** [comment]
Hi,

I am still running into the same error "ValueError:
Problems with input reference file None
Did not find fasta reference file for genome /N/dc2/projects/ncgas/genomes/
genomes/Hsapiens/GRCh37/.
Check tool-data/*.loc files to ensure paths to reference data are correct."

here are the commands i used to install bcbio

wget https://raw.github.com/chapmanb/bcbio-nextgen/master/
scripts/bcbio_nextgen_install.py

python bcbio_nextgen_install.py /N/soft/rhel6/bcbio/1.0.4/local/share/bcbio
--tooldir=/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio --nodata

./bcbio_nextgen.py upgrade --tools --toolplus gatk=/home/bhnala/
GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar

./bcbio_nextgen.py upgrade --tools --toolplus mutect=/home/bhnala/mutect

./bcbio_nextgen.py upgrade -u development

Downloaded the genomes in another directory due to space limitations on
rhel6 using the command
./bcbio_nextgen.py upgrade -u stable --data
/N/dc2/projects/ncgas/genomes/ --genome
GRCh37 --aligners bwa --aligners bowtie2

./bcbio_nextgen.py --data --genome GRCh37 --aligners bwa

I then symlinked these genomes to the bcbio/1.0.4/local/share/bcbio/ using
command ln -s

I found the *.loc files under galaxy/tool-data and made sure they were
consistently pointing to the genomes folder in rhel6/bcbio or
/dc2/projects. I still get the same error regardless. I have checked to
make sure the bwa file is present and the index files are present.

Do you know why this maybe happening?

Thank You

Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by chapmanb** [comment]
Bhavya;
Thanks for the details, it sounds like things are mostly right but something appears to still be off with the paths. Specifically, from the error messages it appears as if there are two nested genome directories in the end after you finish updating the `.loc` files:
```
/N/dc2/projects/ncgas/genomes/genomes/Hsapiens/GRCh37/
```
Is it possible that's causing the problem you're seeing? If you're still hitting issues this would be be recommendation for installing:

1. Install initially with `--nodata` as you've done.
2. Symlink the genomes directory to where you want it to go:
```
rmdir /N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/genomes
mkdir /N/dc2/projects/ncgas/genomes
ln -s /N/dc2/projects/ncgas/genomes /N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/genomes
```
3. Run the data install in your single installation:
```
/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/bin/bcbio_nextgen.py uprade --data --aligners bwa --aligners bowtie2 --genomes GRCh37
```
Hopefully having a single install will be easier to maintain over time as well. Hope this helps.

**Comment by npbhavya** [comment]
Hi,

Thank you for the single installation command, I haven't tried running the
command yet on our server. For now, I am working on setting up
bcbio instead on our cloud resource. I was able to install using the
automated installation there and run tests successfully.

So hopefully if I don't get the same error, I know it's an installation
problem on the server.

Thank You,

Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)
