### ISSUE TITLE
Bcbio installation hangs

### ISSUE THREAD

**Issue by amizeranschi** [chapmanb/bcbio-nextgen#2049]
Hello,

I've been trying to create a fresh installation of Bcbio. However, it hangs during the install, with no further progress for more than 12 hours. This is the command that I've run:

> cd /storage/brno3-cerit/home/amizeranschi/bcbio-new
> wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
> python bcbio_nextgen_install.py /storage/brno3-cerit/home/amizeranschi/bcbio-new --tooldir=/storage/brno3-cerit/home/amizeranschi/bcbio-new/tools \
>   --genomes sacCer3 --genomes mm10 --datatarget variation --datatarget rnaseq \
>   --datatarget smallrna --datatarget vep --datatarget kraken --datatarget gemini \
>   --aligners bwa --aligners bowtie2 --isolate --cores 16

And this is the last part of its output:

> [localhost] local: mv chromFa.tar.gz /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq_prep
> [localhost] local: rm -rf /storage/brno3-cerit/home/amizeranschi/tmp/cloudbiolinux/682f8fad-9643-3108-ad6b-7c80c0542a2f
> [localhost] local: tar -xzpf chromFa.tar.gz
> [localhost] local: find `pwd` -name '*.fa'
> [localhost] local: rm -f inputs.txt
> [localhost] local: cat `cat inputs.txt` > sacCer3.txt
> [localhost] local: mv sacCer3.txt sacCer3.fa
> [localhost] local: mkdir /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq
> [localhost] local: mv seq_prep/sacCer3.fa /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq
> [localhost] local: mv seq_prep/chromFa.tar.gz /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq
> [localhost] local: samtools faidx sacCer3.fa
> [localhost] local: picard -Xms500m -Xmx3500m CreateSequenceDictionary REFERENCE=/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq/sacCer3.fa OUTPUT=/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq/sacCer3.dict
> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

Based on the wording of the error message on the last line, the installation should have continued. However, there has been no activity for more than 12 hours now, and I must conclude that it hanged. How can I get the installation to finish successfully?

**Comment by chapmanb** [comment]
Sorry about the issue -- I'm not sure what is going on from the messages. Could you try interrupting the install with `ctrl-c` and then re-starting with the same command you ran? bcbio will pick up where it left off and hopefully finish cleanly if it's a transient problem. If it consistently hangs, the ctrl-c error message might give us some clue what it's working on so we can debug further. Hope this helps.

**Comment by amizeranschi** [comment]
Thank you for your answer. I tried restarting the installation, but it seems like it got stuck again. I also noticed that one of the required files failed to download, perhaps the URL is no longer valid:

> [localhost] local: wget --continue --no-check-certificate -O sacCer3-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/sacCer3-rtg.tar.xz'
> --2017-08-28 14:09:54--  https://s3.amazonaws.com/biodata/genomes/sacCer3-rtg.tar.xz
> Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.32.98
> Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.32.98|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2017-08-28 14:09:55 ERROR 404: Not Found.
> 
> Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O sacCer3-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/sacCer3-rtg.tar.xz''

I have canceled (Ctrl+C) the installation again. Here are the lines written when cancelling, including the error that I get:

> Processing "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq/sacCer3.fa"
> 
> Input Data
> Files              : sacCer3.fa
> Format             : FASTA
> Type               : DNA
> Number of sequences: 17
> Total residues     : 12157105
> Minimum length     : 85779
> Maximum length     : 1531933
> 
> Output Data
> SDF-ID             : 35e1b6d7-ea41-4dba-b8df-d40660ea44a9
> Number of sequences: 17
> Total residues     : 12157105
> Minimum length     : 85779
> Maximum length     : 1531933
> [localhost] local: picard -Xms500m -Xmx3500m CreateSequenceDictionary REFERENCE=/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq/sacCer3.fa OUTPUT=/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/genomes/Scerevisiae/sacCer3/seq/sacCer3.dict
> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
> ^CTraceback (most recent call last):
>   File "bcbio_nextgen_install.py", line 251, in <module>
> Traceback (most recent call last):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio-new/anaconda/bin/bcbio_nextgen.py", line 215, in <module>
>     main(parser.parse_args(), sys.argv[1:])
>     install.upgrade_bcbio(kwargs["args"])
>   File "bcbio_nextgen_install.py", line 44, in main
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio-new/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
>     subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
>   File "/usr/lib64/python2.7/subprocess.py", line 537, in check_call
>     retcode = call(*popenargs, **kwargs)
>   File "/usr/lib64/python2.7/subprocess.py", line 524, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/usr/lib64/python2.7/subprocess.py", line 1376, in wait
>     pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
>   File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call
>     return func(*args)
> KeyboardInterrupt
>     upgrade_bcbio_data(args, REMOTES)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio-new/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
>     cbl_deploy.deploy(s)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
>     _setup_vm(options, vm_launcher, actions)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
>     configure_instance(options, actions)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
>     setup_biodata(options)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
>     install_proc(options["genomes"], ["ggd", "s3", "raw"])
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 338, in install_data
>     _prep_genomes(env, genomes, genome_indexes, ready_approaches)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 484, in _prep_genomes
>     _index_to_galaxy(org_dir, ref_file, gid, genome_indexes, manager.config)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 529, in _index_to_galaxy
>     index_file = get_index_fn(idx)(ref_file)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 680, in _index_sam
>     galaxy.index_picard(ref_file)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/galaxy.py", line 123, in index_picard
>     .format(ref=ref_file, out=index_file))
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio-new/tmpbcbio-install/cloudbiolinux/cloudbio/fabutils.py", line 47, in _run
>     return local(command, capture=capture)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio-new/anaconda/lib/python2.7/site-packages/fabric/operations.py", line 1224, in local
>     (stdout, stderr) = p.communicate()
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio-new/anaconda/lib/python2.7/subprocess.py", line 476, in communicate
>     self.wait()
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio-new/anaconda/lib/python2.7/subprocess.py", line 1073, in wait
> [amizeranschi@ungu1 bcbio-new]$     pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio-new/anaconda/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
>     return func(*args)
> KeyboardInterrupt


So it does not seem to be a transient problem... What else could I be checking, in order to find the problem and get the installation to work?

**Comment by amizeranschi** [comment]
I have managed to install Bcbio successfully on a different machine. I still don't know what was causing the problems I experience earlier. 

I will close this issue now.

**Comment by chapmanb** [comment]
Thanks for following up. I'm glad it worked on a different machine and I'm also still confused about the issues with hanging during that picard call. It's creating an index from the reference fasta and shouldn't be too intensive. The only thing I can think of is that it tries to allocate 3.5Gb of memory -- maybe it was a very busy or low memory machine so ends up swapping trying to do this? Hope things work smoothly going forward for you.
