### ISSUE TITLE
multiqc_summary: PicklingError: Can't pickle <class 'sh.GlobResults'>: attribute lookup sh.GlobResults failed

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2064]
Hi, 

I a recent bcbio development version I repeatedly get the following error when using parallelization on a sun grid engine cluster (ie. `-t ipython -s sge`).  I am using the bcbio development version of 2 days ago.

Running without any parallelization does not result in the error, and thus finished the analysis. 

```
[2017-09-07T08:39Z] machine_18: copy qsignature
[2017-09-07T08:39Z] machine_18: summarize fastqc
[2017-09-07T08:39Z] machine_18: summarize target information
[2017-09-07T08:39Z] machine_18: summarize coverage
[2017-09-07T08:39Z] machine_18: summarize variants
Sending a shutdown signal to the controller and engines.
2017-09-07 10:39:10.157 [IPClusterStop] Using existing profile dir: u'/data/run/Projects/Freebayes_control/Freebayes_control/work/log/ipython'
2017-09-07 10:39:10.194 [IPClusterStop] Stopping cluster [pid=21117] with [signal=2]
2017-09-07 10:39:11.034 [IPClusterStop] Using existing profile dir: u'/data/run/Projects/Freebayes_control/Freebayes_control/work/log/ipython'
2017-09-07 10:39:11.041 [IPClusterStop] Stopping cluster [pid=21117] with [signal=2]
Traceback (most recent call last):
  File "/workspace/my_user/tmp_bcbio_latest4/tool_dir/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/workspace/my_user/tmp_bcbio_latest4/tool_dir/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 180, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 38, in generate_parallel
    samples = run_parallel("multiqc_summary", [samples])
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 136, in run
    for data in view.map_sync(fn, items, track=False):
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-140>", line 2, in map
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-139>", line 2, in map
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<decorator-gen-119>", line 2, in __call__
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: multiqc_summary
[0:apply]: PicklingError: Can't pickle <class 'sh.GlobResults'>: attribute lookup sh.GlobResults failed
```

**Comment by chapmanb** [comment]
Neill;
Sorry about the issue. This error looks like either an intermittent IPython pickling error, or reflecting that something failed during one of the QC steps. Could you try:

- Re-running to see if the error is persistent? Sometimes IPython fails due to network issues even though it's normally pretty robust to these. In these cases a restart just works fine.
- Looking into `log/bcbio-nextgen.log` and `log/bcbio-nextgen-debug.log` to see if there are other errors reported? This could reflect that something failed during one of the parallel steps and this would have the useful error message to debug.

Thanks for the help debugging.

**Comment by chapmanb** [comment]
Neill;
Thanks again for this report. I dug into the code a bit more and found that the `sh.GlobResults` part gets input by `sh` monkeypatching of glob. I'm not sure why this has suddenly become an issue since it's been present for a while but I removed the last use of `sh` in bcbio to avoid the input. This is a speculative fix but I hope will resolve the problem if you update to the latest development version. Let me know if you still have issues after this and happy to investigate more.
