### ISSUE TITLE
Fail to run bcbio_NA12878-chr20 of ga4gh workflow execution challenge

### ISSUE THREAD

**Issue by byoo** [chapmanb/bcbio-nextgen#2065]
Hello,
I got an error in running bcbio_NA12878-chr20 workflow. It seems that newly introduced codes deleting tabix index cause it to fail. Would you take a look? Below is a stack trace and let me know if you have any information.

Thanks!

>Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 219, in <module>
    runfn.process(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 56, in process
    out = fn(fnargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 306, in compare_to_rm
    return validate.compare_to_rm(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/validate.py", line 155, in compare_to_rm
    eval_files = _run_rtg_eval(vrn_file, rm_file, rm_interval_file, base_dir, toval_data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/validate.py", line 238, in _run_rtg_eval
    vrn_file, rm_file, interval_bed = _prepare_inputs(vrn_file, rm_file, rm_interval_file, base_dir, data)
  **File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/validate.py", line 224, in _prepare_inputs
    os.remove(vrn_file + ".tbi")**
OSError: [Errno 30] Read-only file system: '/var/lib/cwl/stgcaa5b7df-c37f-4ffc-bf2f-64bc29624cb2/NA12878-chr20-effects-filter.vcf.gz.tbi'
[job compare_to_rm] completed permanentFail
[step compare_to_rm] completed permanentFail
[workflow variantcall] completed permanentFail

**Comment by byoo** [comment]
I guess the issue belongs to the cwl better.

**Comment by chapmanb** [comment]
Thanks much for the report. Apologies, this is a bug in bcbio where we're trying to manipulate input files (which are read only). I pushed a fix so if you update your bcbio-vc container (`docker pull quay.io/bcbio/bcbio-vc`) to the latest and re-run it should hopefully work cleanly for you. Please let us know if you run into any other problems.

**Comment by byoo** [comment]
Thank you for your quick help. It worked for me.
