### ISSUE TITLE
missing one reference file "exac.vcf.gz"

### ISSUE THREAD

**Issue by jich-MCTP** [chapmanb/bcbio-nextgen#2076]
Hi Brad,

I build the latest version of bcbio and run some data. But I meet one problem, it seems one ref file is missing.

The error message is:

[2017-09-15T19:54Z] see: https://github.com/brentp/vcfanno
[2017-09-15T19:54Z] =============================================
[2017-09-15T19:54Z] vcfanno.go:112: [Flatten] unable to open file: /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38//usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/variation/exac.vcf.gz in /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38
[2017-09-15T19:54Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/share/bcbio-nextgen/anaconda/bin/vcfanno -p 8 -lua /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/config/vcfanno/gemini.lua -base-path /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38 /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/config/vcfanno/gemini.conf /bcbio/work/freebayes/MO_1541_SI_16903-effects-annotated-filter.vcf.gz | sed -e 's/Number=A/Number=1/g' | bgzip -c > /bcbio/work/bcbiotx/tmpUGlPLD/MO_1541_SI_16903-effects-annotated-filter-annotated-gemini.vcf.gz

=============================================
vcfanno version 0.2.8 [built with go1.8]
see: https://github.com/brentp/vcfanno
=============================================

vcfanno.go:112: [Flatten] unable to open file: /usr/local/share/bcbio-nextgen/genomes/Hsapiens
/hg38//usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/variation/exac.vcf.gz in /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 154, in variant2pipeline
    samples = run_parallel("postprocess_variants", samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 182, in postprocess_variants
    return variation.postprocess_variants(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 81, in postprocess_variants
    data[vrn_key] = prioritize.handle_vcf_calls(data[vrn_key], data, orig_items)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/prioritize.py", line 35, in handle_vcf_calls
    ann_vcf = vcfanno.run_vcfanno(vcf_file, ["gemini"], data, data_basepath)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfanno.py", line 82, in run_vcfanno
    out_file = vcfanno(vcf, out_file, conf_fns, data, data_basepath or basepath, lua_fns)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfanno.py", line 27, in vcfanno
    do.run(cmd.format(**locals()), message)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/share/bcbio-nextgen/anaconda/bin/vcfanno -p 8 -lua /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/config/vcfanno/gemini.lua -base-path /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38 /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/config/vcfanno/gemini.conf /bcbio/work/freebayes/MO_1541_SI_16903-effects-annotated-filter.vcf.gz | sed -e 's/Number=A/Number=1/g' | bgzip -c > /bcbio/work/bcbiotx/tmpUGlPLD/MO_1541_SI_16903-effects-annotated-filter-annotated-gemini.vcf.gz

=============================================
vcfanno version 0.2.8 [built with go1.8]
see: https://github.com/brentp/vcfanno
=============================================

vcfanno.go:112: [Flatten] unable to open file: /usr/local/share/bcbio-nextgen/genomes/Hsapiens
/hg38//usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/variation/exac.vcf.gz in /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38
' returned non-zero exit status 1
bcbio.MakeFile:14: recipe for target '/bcbioData/run.bcbio.done' failed
make: *** [/bcbioData/run.bcbio.done] Error 1

I run the command line to re-fetch the ref files:
bcbio_nextgen.py upgrade --data --genomes hg38 --aligners bwa

But there is still no file "exac.vcf.gz"

Could you please help me to figure out?

Thanks!

**Comment by chapmanb** [comment]
Jin;
Sorry about the issue and thanks for reporting. I wanted to follow up on this even though you closed it and may have it figured out. You want to install the gemini data target to get these files (`--datatarget gemini`):

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#datatarget-install

There was also a bug in the 1.0.5 release that sometimes would use vcfanno for prep even if these files weren't present. That is fixed in the latest development so upgrading with `bcbio_nextgen.py upgrade -u development` would hopefully let you skip the step if you don't want to install the extra data. Hope this helps.
