### ISSUE TITLE
Tweak code for merge fastqs and VEP annotation

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#2085]
Hi,

Is it possible to tweak the code for:
1) bcbio_prepare_samples.py - I have a bunch of fastq files with extension .R1.fq and .R2.fq and I suspect that the code is failing because the "." in front of "R" is not recognised. Or am I doing something wrong?
 Error:
[2017-09-28T08:06Z] Preparing 1414_010316_T files [['/mnt/projects/ngbhs/cirqseq/2017_plasma/HS006-PE-R00136_AH7GCWBBXX/L001/fastqumifiles/20170303_Pool_1_1414_010316_T_20170228.R1.fq', '/mnt/projects/ngbhs/cirqseq/2017_plasma/HS006-PE-R00136_AH7GCWBBXX/L001/fastqumifiles/20170303_Pool_1_1414_010316_T_20170228.R2.fq', '/mnt/projects/ngbhs/cirqseq/2017_plasma/HS006-PE-R00136_AH7GCWBBXX/L002/fastqumifiles/20170303_Pool_2_1414_010316_T_20170228.R2.fq'], ['/mnt/projects/ngbhs/cirqseq/2017_plasma/HS006-PE-R00136_AH7GCWBBXX/L002/fastqumifiles/20170303_Pool_2_1414_010316_T_20170228.R1.fq']] to merge into /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170927_exome8lane/mergedtest/1414_010316_T.fastq.gz.
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_prepare_samples.py", line 163, in <module>
    samples = run_parallel("prepare_bcbio_samples", samples)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 85, in prepare_bcbio_samples
    return sample.prepare_bcbio_samples(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 368, in prepare_bcbio_samples
    out_file = fq_merge(sample['files'], sample['out_file'], sample['config'])
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/fastq.py", line 112, in merge
    pair2 = [fastq_file[1] for fastq_file in files]
IndexError: list index out of range

2) I'm not sure whether bcbio already supports this but I was wondering whether --ALLELE_NUM can be output as one of the fields when VEP is used for annotation. This is so that I can track the annotations for multiallelic easier especially when using --pick which changes the order occasionally.

Thanks much!

**Comment by lpantano** [comment]
Hi,

I am working on the code, but the main reason this is a problem is because you have  Pool_1_ and Pool_2_ in your names, so sometimes R1 and R2 are detected as the separators and other _1_ and _2_. I will add an option in the script to set up custom separators, so you should use  --separators R. Meanwhile you can rename files if you want with rename command line and change Pool_1_ by Pool1r, the same for Pool_2_ . That maybe fixe it.

I let you know when I have the new code in place.

Cheers

**Comment by lpantano** [comment]
Hi again, 

I changed the code to allow specifying the separator used to detect pairs. You need to update bcbio and try something like:

`bcbio_prepare_samples.py --csv merge.csv --out fastq --separators R -`

Let me know if you find any more errors.

**Comment by phu5ion** [comment]
Hi,
bcbio_prepare_samples.py --csv merge.csv --out fastq --separators R -
Works! Thanks a lot for your help.

Just in case this was missed, copying from my first post above:
I'm not sure whether bcbio already supports this but I was wondering whether --ALLELE_NUM can be output as one of the fields when VEP is used for annotation. This is so that I can track the annotations for multiallelic easier especially when using --pick which changes the order occasionally.

According to the VEP website (http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html), the script just needs to specify a --allele_number flag, and an additional "ALLELE_NUM" under the --fields flag in the VEP command.

**Comment by chapmanb** [comment]
Thanks Lorena for the quick fix on the merging samples issues, and thanks for the suggestion on the useful VEP addition. I've added this as a default option in the latest development version (cc @matthdsm in case this affects anything he's doing downstream). Please let us know if you run into any issues.

**Comment by matthdsm** [comment]
Hi Brad, all,

No issue here, extra fields shouldn't pose any problem. The more the merrier!

Cheers
M

**Comment by phu5ion** [comment]
Hi Brad and all,

Thanks for the work! I'd like to enquire the default behaviour for "-canonical" in bcbio's VEP run - is it currently using --pick? If so, would it be possible to allow an option for --pick_allele instead so that one annotation is provided for each allele? This is because --pick only outputs a single annotation for all multiallelic positions in each row but I would prefer the annotations to correctly reflect that for each of the alleles...

**Comment by matthdsm** [comment]
Hi, 

I don't suppose this will cause any issues. As you said, using the `canonical` option activates VEP's `--pick` option. 
@chapmanb, correct me if I'm wrong, but I don't think there are any multiallelic sites left after decomposing? So changing to `--pick_allele` shouldn't change a thing.

Cheers
M

**Comment by phu5ion** [comment]
Hi @matthdsm ,

There's multiallelic output for scalpel calls when combined with mutect. Not sure whether this is intended...

**Comment by matthdsm** [comment]
Aha, 
that's outside of our use case, so I don't think I'll be of any help here.
Perhaps Brad can help you further.

Cheers
M

**Comment by chapmanb** [comment]
Thanks for the discussion and heads up on `--pick_allele`. It does seem like that's a better option and the behavior we'd probably prefer to have. We only do full decomposition for vcfanno/gemini preparation so the standard callsets will have multi-allelics there where this can help. Matthias, would you have an objection to switching over? It sounds like you use the decomposed output so won't have any changes but wanted to check. Anyone else have thoughts/opinions on the change?

**Comment by matthdsm** [comment]
Hi Brad, 
no objections here, as you said, we rely on the decomposed output, so this wouldn't affect us.

Cheers
M

**Comment by chapmanb** [comment]
Brilliant, thanks again for all the suggestions and feedback. The latest development version uses `--pick_allele` to replace the old behavior and provide a better default. Much appreciated.
