### ISSUE TITLE
kallisto index 

### ISSUE THREAD

**Issue by jefarrar** [chapmanb/bcbio-nextgen#2086]
Hi-

I'm poking around with with kallisto/pizzly in bcbio and running into an error with the quantification step in both stable and dev releases. Running 3 sample analyses on a cluster and either 1 or 2 of the kallisto jobs fail during index generation while the remaining job(s) returns quantification data. At termination, /work/inputs/transcriptome/hg38-noalt.fa is present but not the *.tmp so maybe this is a conflict between jobs running reporting back from separate nodes? 

Also, kallisto is building a new index for each sample; is this expected behavior?  If this works out I'd like to run quite a few samples so rebuilding the same index for each one seems inefficient in contrast to holding a centralized index with the genome data like for the read mapper indices. I can't tell if perhaps there should be a kallisto directory holding an index under hg38-noalt or hg38-noalt/rnaseq, but I don't have one. 

As always, thanks for your work on this fabulous Swiss army knife!

---
details:
  - analysis: RNA-seq
    genome_build: hg38-noalt
    algorithm:
      quality_format: standard
      strandedness: firststrand
      aligner: star
      trim_reads: false
      expression_caller: kallisto
      fusion_mode: true
      variantcaller: vardict
upload:
  dir: ../final
---
[2017-09-28T17:56Z] clusterhn.cluster.com: ipython: run_kallisto_rnaseq
[2017-09-28T17:56Z] n001.cluster.com: Converting /opt/bcbio/genomes/Hsapiens/hg38-noalt/rnaseq/ref-transcripts.gtf to FASTA format.
[2017-09-28T17:56Z] n002.cluster.com: Converting /opt/bcbio/genomes/Hsapiens/hg38-noalt/rnaseq/ref-transcripts.gtf to FASTA format.
[2017-09-28T17:56Z] n002.cluster.com: Converting /opt/bcbio/genomes/Hsapiens/hg38-noalt/rnaseq/ref-transcripts.gtf to FASTA format.
[2017-09-28T17:56Z] n001.cluster.com: Creating Kallisto index for /rnaseq/low-pass-test-config/work/inputs/transcriptome/hg38-noalt.fa.
[2017-09-28T17:56Z] n001.cluster.com: [build] loading fasta file /rnaseq/low-pass-test-config/work/inputs/transcriptome/hg38-noalt.fa
[2017-09-28T17:56Z] n001.cluster.com: [build] k-mer length: 31
[2017-09-28T17:56Z] n001.cluster.com: [build] warning: clipped off poly-A tail (longer than 10)
[2017-09-28T17:56Z] n001.cluster.com:         from 1521 target sequences
[2017-09-28T17:56Z] n001.cluster.com: [build] warning: replaced 86 non-ACGUT characters in the input sequence
[2017-09-28T17:56Z] n001.cluster.com:         with pseudorandom nucleotides
[2017-09-28T17:57Z] n002.cluster.com: Creating Kallisto index for /rnaseq/low-pass-test-config/work/inputs/transcriptome/hg38-noalt.fa.
[2017-09-28T17:57Z] n002.cluster.com: Unexpected error
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 133, in run_kallisto_rnaseq
    return ipython.zip_args(apply(kallisto.run_kallisto_rnaseq, *args))
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 34, in run_kallisto_rnaseq
    out_file = kallisto_rnaseq(fq1, fq2, kallisto_dir, gtf_file, fasta_file, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 45, in kallisto_rnaseq
    index = kallisto_index(gtf_file, fasta_file, data, kallisto_dir)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 114, in kallisto_index
    gtf_fa = sailfish.create_combined_fasta(data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", line 94, in create_combined_fasta
    out_file = gtf.gtf_to_fasta(gtf_file, ref_file, out_file=out_file)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 134, in gtf_to_fasta
    os.remove(tmp_file)
OSError: [Errno 2] No such file or directory: '/rnaseq/low-pass-test-config/work/inputs/transcriptome/hg38-noalt.fa.tmp'
[2017-09-28T17:57Z] n002.cluster.com: [build] loading fasta file /rnaseq/low-pass-test-config/work/inputs/transcriptome/hg38-noalt.fa
[2017-09-28T17:57Z] n002.cluster.com: [build] k-mer length: 31
[2017-09-28T17:57Z] n002.cluster.com: [build] warning: clipped off poly-A tail (longer than 10)
[2017-09-28T17:57Z] n002.cluster.com:         from 1521 target sequences
[2017-09-28T17:57Z] n002.cluster.com: [build] warning: replaced 86 non-ACGUT characters in the input sequence
[2017-09-28T17:57Z] n002.cluster.com:         with pseudorandom nucleotides
[2017-09-28T17:57Z] n001.cluster.com: [build] counting k-mers ... done.
[2017-09-28T17:58Z] n002.cluster.com: [build] counting k-mers ... done.
[2017-09-28T18:03Z] n001.cluster.com: [build] building target de Bruijn graph ...  done
[2017-09-28T18:03Z] n001.cluster.com: [build] creating equivalence classes ...  done
[2017-09-28T18:03Z] n001.cluster.com: [build] target de Bruijn graph has 1244439 contigs and contains 122835954 k-mers
[2017-09-28T18:04Z] n001.cluster.com: Quantifying transcripts with kallisto.
[2017-09-28T18:04Z] n001.cluster.com: [quant] fragment length distribution will be estimated from the data
[2017-09-28T18:04Z] n001.cluster.com: [index] k-mer length: 31
[2017-09-28T18:04Z] n001.cluster.com: [index] number of targets: 196,345
[2017-09-28T18:04Z] n001.cluster.com: [index] number of k-mers: 122,835,954
[2017-09-28T18:04Z] n001.cluster.com: [index] number of equivalence classes: 797,657
[2017-09-28T18:04Z] n001.cluster.com: [quant] running in paired-end mode
[2017-09-28T18:04Z] n001.cluster.com: [quant] will process pair 1: /rnaseq/fq/BM4203-1.fq.gz
[2017-09-28T18:04Z] n001.cluster.com:                              /rnaseq/fq/BM4203-2.fq.gz
[2017-09-28T18:05Z] n002.cluster.com: [build] building target de Bruijn graph ...  done
[2017-09-28T18:05Z] n001.cluster.com: [quant] finding pseudoalignments for the reads ... done
[2017-09-28T18:05Z] n001.cluster.com: [quant] processed 25,066,582 reads, 18,109,722 reads pseudoaligned
[2017-09-28T18:05Z] n001.cluster.com: [quant] estimated average fragment length: 195.048
[2017-09-28T18:06Z] n002.cluster.com: [build] creating equivalence classes ...  done
[2017-09-28T18:06Z] n002.cluster.com: [build] target de Bruijn graph has 1244439 contigs and contains 122835954 k-mers
[2017-09-28T18:06Z] n001.cluster.com: [   em] quantifying the abundances ... done
[2017-09-28T18:06Z] n001.cluster.com: [   em] the Expectation-Maximization algorithm ran for 1,069 rounds
[2017-09-28T18:06Z] n002.cluster.com: Quantifying transcripts with kallisto.
[2017-09-28T18:06Z] n002.cluster.com: [quant] fragment length distribution will be estimated from the data
[2017-09-28T18:06Z] n002.cluster.com: [index] k-mer length: 31
[2017-09-28T18:06Z] n002.cluster.com: [index] number of targets: 196,345
[2017-09-28T18:06Z] n002.cluster.com: [index] number of k-mers: 122,835,954
[2017-09-28T18:07Z] n002.cluster.com: [index] number of equivalence classes: 797,657
[2017-09-28T18:07Z] n002.cluster.com: [quant] running in paired-end mode
[2017-09-28T18:07Z] n002.cluster.com: [quant] will process pair 1: /rnaseq/fq/BM3969-1.fq.gz
[2017-09-28T18:07Z] n002.cluster.com:                              /rnaseq/fq/BM3969-2.fq.gz
[2017-09-28T18:07Z] n002.cluster.com: [quant] finding pseudoalignments for the reads ... done
[2017-09-28T18:07Z] n002.cluster.com: [quant] processed 16,439,951 reads, 14,151,744 reads pseudoaligned
[2017-09-28T18:08Z] n002.cluster.com: [quant] estimated average fragment length: 193.458
[2017-09-28T18:08Z] n001.cluster.com: [bstrp] number of EM bootstraps complete: 1
[bstrp] number of EM bootstraps complete: 2
[...]
[bstrp] number of EM bootstraps complete: 30
[2017-09-28T18:08Z] n002.cluster.com: [   em] quantifying the abundances ... done
[2017-09-28T18:08Z] n002.cluster.com: [   em] the Expectation-Maximization algorithm ran for 1,058 rounds
[2017-09-28T18:09Z] n002.cluster.com: [bstrp] number of EM bootstraps complete: 1
[bstrp] number of EM bootstraps complete: 2
[...]
[bstrp] number of EM bootstraps complete: 30

Same here, but 2 kallistos died and one survived; the example above was I believe from the release and the one below is from github, in any case it looks like the same problem:

[2017-09-28T20:34Z] n001.cluster.com: Converting /opt/bcbio/genomes/Hsapiens/hg38-noalt/rnaseq/ref-transcripts.gtf to FASTA format.
[2017-09-28T20:34Z] n002.cluster.com: Converting /opt/bcbio/genomes/Hsapiens/hg38-noalt/rnaseq/ref-transcripts.gtf to FASTA format.
[2017-09-28T20:34Z] n002.cluster.com: Converting /opt/bcbio/genomes/Hsapiens/hg38-noalt/rnaseq/ref-transcripts.gtf to FASTA format.
[2017-09-28T20:34Z] n001.cluster.com: Creating Kallisto index for /rnaseq/low-pass-test-config1/work/inputs/transcriptome/hg38-noalt.fa.
[2017-09-28T20:34Z] n001.cluster.com: [build] loading fasta file /rnaseq/low-pass-test-config1/work/inputs/transcriptome/hg38-noalt.fa
[2017-09-28T20:34Z] n001.cluster.com: [build] k-mer length: 31
[2017-09-28T20:34Z] n002.cluster.com: Unexpected error
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 133, in run_kallisto_rnaseq
    return ipython.zip_args(apply(kallisto.run_kallisto_rnaseq, *args))
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 34, in run_kallisto_rnaseq
    out_file = kallisto_rnaseq(fq1, fq2, kallisto_dir, gtf_file, fasta_file, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 45, in kallisto_rnaseq
    index = kallisto_index(gtf_file, fasta_file, data, kallisto_dir)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 114, in kallisto_index
    gtf_fa = sailfish.create_combined_fasta(data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", line 104, in create_combined_fasta
    out_file = gtf.gtf_to_fasta(gtf_file, ref_file, out_file=out_file)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 134, in gtf_to_fasta
    os.remove(tmp_file)
OSError: [Errno 2] No such file or directory: '/rnaseq/low-pass-test-config1/work/inputs/transcriptome/hg38-noalt.fa.tmp'
[2017-09-28T20:34Z] n002.cluster.com: Unexpected error
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 133, in run_kallisto_rnaseq
    return ipython.zip_args(apply(kallisto.run_kallisto_rnaseq, *args))
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 34, in run_kallisto_rnaseq
    out_file = kallisto_rnaseq(fq1, fq2, kallisto_dir, gtf_file, fasta_file, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 45, in kallisto_rnaseq
    index = kallisto_index(gtf_file, fasta_file, data, kallisto_dir)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/kallisto.py", line 114, in kallisto_index
    gtf_fa = sailfish.create_combined_fasta(data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", line 104, in create_combined_fasta
    out_file = gtf.gtf_to_fasta(gtf_file, ref_file, out_file=out_file)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 134, in gtf_to_fasta
    os.remove(tmp_file)
OSError: [Errno 2] No such file or directory: '/rnaseq/low-pass-test-config1/work/inputs/transcriptome/hg38-noalt.fa.tmp'
[2017-09-28T20:34Z] n001.cluster.com: [build] warning: clipped off poly-A tail (longer than 10)
[2017-09-28T20:34Z] n001.cluster.com:         from 1521 target sequences
[2017-09-28T20:34Z] n001.cluster.com: [build] warning: replaced 86 non-ACGUT characters in the input sequence
[2017-09-28T20:34Z] n001.cluster.com:         with pseudorandom nucleotides
[2017-09-28T20:35Z] n001.cluster.com: [build] counting k-mers ... done.
[2017-09-28T20:40Z] n001.cluster.com: [build] building target de Bruijn graph ...  done
[2017-09-28T20:41Z] n001.cluster.com: [build] creating equivalence classes ...  done
[2017-09-28T20:41Z] n001.cluster.com: [build] target de Bruijn graph has 1244439 contigs and contains 122835954 k-mers
[2017-09-28T20:41Z] n001.cluster.com: Quantifying transcripts with kallisto.
[2017-09-28T20:41Z] n001.cluster.com: [quant] fragment length distribution will be estimated from the data
[2017-09-28T20:41Z] n001.cluster.com: [index] k-mer length: 31
[2017-09-28T20:41Z] n001.cluster.com: [index] number of targets: 196,345
[2017-09-28T20:41Z] n001.cluster.com: [index] number of k-mers: 122,835,954
[2017-09-28T20:42Z] n001.cluster.com: [index] number of equivalence classes: 797,657
[2017-09-28T20:42Z] n001.cluster.com: [quant] running in paired-end mode
[2017-09-28T20:42Z] n001.cluster.com: [quant] will process pair 1: /rnaseq/fq/BM4203-1.fq.gz
[2017-09-28T20:42Z] n001.cluster.com:                              /rnaseq/fq/BM4203-2.fq.gz
[2017-09-28T20:43Z] n001.cluster.com: [quant] finding pseudoalignments for the reads ... done
[2017-09-28T20:43Z] n001.cluster.com: [quant] processed 25,066,582 reads, 18,109,722 reads pseudoaligned
[2017-09-28T20:43Z] n001.cluster.com: [quant] estimated average fragment length: 194.945
[2017-09-28T20:44Z] n001.cluster.com: [   em] quantifying the abundances ... done
[2017-09-28T20:44Z] n001.cluster.com: [   em] the Expectation-Maximization algorithm ran for 1,069 rounds
[2017-09-28T20:45Z] n001.cluster.com: [bstrp] number of EM bootstraps complete: 1
[...]
[bstrp] number of EM bootstraps complete: 30

**Comment by roryk** [comment]
Thanks @jefarrar, good catch. I fixed this issue so now it won't run on every sample; it will run on the first set if more than one sample is running at the same time but after that it won't run on each sample.
