### ISSUE TITLE
pizzly kallisto IOError: Unable to create file

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2089]
Hi Rorky,
I am having trouble running the RNA-seq pipeline since the pizzly was added to the default run. 

what look strange to me is that the IOError message report the filename all in lower case
5667_**az**/work/kallisto/**sudhl**10**igo**05667

do you have any idea?

Thanks!

my template: 

# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: hg19
    algorithm:
      aligner: star
      disambiguate: mm10
      strandedness: unstranded
      #transcriptome_align: true
      fusion_mode: true
upload:
  dir: ../final
resources:
  samtools:
    memory: 6g

[2017-10-03T23:34Z] gpu-2-8.local: [Tue Oct 03 19:34:46 EDT 2017] ==Tissue specific
[2017-10-03T23:34Z] gpu-2-8.local: [Tue Oct 03 19:34:46 EDT 2017] Initializing classifier
[2017-10-03T23:34Z] gpu-2-8.local: [Tue Oct 03 19:34:46 EDT 2017] Classifying fusions
[2017-10-03T23:34Z] gpu-2-8.local: [Tue Oct 03 19:34:46 EDT 2017] Writing output
[2017-10-03T23:34Z] gpu-2-8.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 313, in detect_fusions
    return ipython.zip_args(apply(rnaseq.detect_fusions, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 124, in detect_fusions
    pizzly_dir = pizzly.run_pizzly(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 45, in run_pizzly
    fraglength = get_fragment_length(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 30, in get_fragment_length
    with h5py.File(h5) as f:
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 126, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/h5f.c:2290)
IOError: Unable to create file (Unable to open file: name = '/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_az/5667_az/work/kallisto/ocily3igo05667/quant/abundance.h5', errno = 2, error message = 'no such file or directory', flags = 15, o_flags = c2)
[2017-10-03T23:34Z] gpu-1-6.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 313, in detect_fusions
    return ipython.zip_args(apply(rnaseq.detect_fusions, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 124, in detect_fusions
    pizzly_dir = pizzly.run_pizzly(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 45, in run_pizzly
    fraglength = get_fragment_length(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 30, in get_fragment_length
    with h5py.File(h5) as f:
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 126, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/h5f.c:2290)
IOError: Unable to create file (Unable to open file: name = '/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_az/5667_az/work/kallisto/ocily3igo05667/quant/abundance.h5', errno = 2, error message = 'no such file or directory', flags = 15, o_flags = c2)
[2017-10-03T23:34Z] gpu-2-12.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 313, in detect_fusions
    return ipython.zip_args(apply(rnaseq.detect_fusions, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 124, in detect_fusions
    pizzly_dir = pizzly.run_pizzly(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 45, in run_pizzly
    fraglength = get_fragment_length(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 30, in get_fragment_length
    with h5py.File(h5) as f:
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 126, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/h5f.c:2290)
IOError: Unable to create file (Unable to open file: name = '/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_az/5667_az/work/kallisto/ocily3igo05667/quant/abundance.h5', errno = 2, error message = 'no such file or directory', flags = 15, o_flags = c2)
[2017-10-03T23:34Z] gpu-2-12.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 313, in detect_fusions
    return ipython.zip_args(apply(rnaseq.detect_fusions, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 124, in detect_fusions
    pizzly_dir = pizzly.run_pizzly(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 45, in run_pizzly
    fraglength = get_fragment_length(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 30, in get_fragment_length
    with h5py.File(h5) as f:
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 126, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/h5f.c:2290)
IOError: Unable to create file (Unable to open file: name = '/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_az/5667_az/work/kallisto/ocily3igo05667/quant/abundance.h5', errno = 2, error message = 'no such file or directory', flags = 15, o_flags = c2)
[2017-10-03T23:35Z] gpu-2-10.local: [Tue Oct 03 19:35:00 EDT 2017] [Post-processing RNASTAR input] 500000 reads analyzed
2017-10-03 19:35:01.107 [IPClusterStop] Using existing profile dir: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/log/ipython'
2017-10-03 19:35:01.145 [IPClusterStop] Stopping cluster [pid=1029] with [signal=2]
2017-10-03 19:35:02.616 [IPClusterStop] Using existing profile dir: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/log/ipython'
2017-10-03 19:35:02.623 [IPClusterStop] Stopping cluster [pid=1029] with [signal=2]
14 Engines running
Sending a shutdown signal to the controller and engines.
20 Engines running
Sending a shutdown signal to the controller and engines.
15 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 243, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 116, in quantitate_expression_parallel
    samples = run_parallel("detect_fusions", samples)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 136, in run
    for data in view.map_sync(fn, items, track=False):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-139>", line 2, in map
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-138>", line 2, in map
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<decorator-gen-118>", line 2, in __call__
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 98, in get
    self.wait(timeout)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 129, in wait
    self._ready = self._client.wait(self.msg_ids, timeout)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/client.py", line 1080, in wait
    self.spin()
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/client.py", line 1027, in spin
    self._flush_iopub(self._iopub_socket)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/client.py", line 893, in _flush_iopub
    idents,msg = self.session.recv(sock, mode=zmq.NOBLOCK)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/jupyter_client/session.py", line 793, in recv
    raise e
ValueError: Invalid Signature: '7a974c6e50a4953f0200aef255641dfc6df6c5211f61d35bd2f4da7e3278f01f'

**Comment by schelhorn** [comment]
I have the same issue as well - also with the lower case origin. Some code in the `kallisto` context does not seem to like path names with upper case characters it seems.

**Comment by apastore** [comment]
Thanks !
Is possible to turn off pizzly and kallisto? In a specific run?


Thanks!

**Comment by roryk** [comment]
Thanks, sorry about that folks. Hm-- the lowercase returning of the path is due to this bug: https://github.com/h5py/h5py/issues/854, so it is a little bit of a red herring. Is the abundance.h5 not there for that sample if you use the correct path name?

**Comment by roryk** [comment]
Ok, I think I figured it out-- this is happening when fusion_mode is on and kallisto isn't listed in the expression_caller field. If you add expression_caller: [kallisto] to the entries, it will run kallisto and pizzly correctly. I'll push a fix that forces kallisto to run if fusion_mode is on and provide a way to turn it off for the next release.

**Comment by apastore** [comment]
Thanks!

**Comment by roryk** [comment]
Thanks all, I added the ability to turn individual fusion callers on via the fusion_caller field. fusion_mode will still work for the next several versions and will run oncofuse/pizzly but eventually we'll just switch over to fusion_caller only.

**Comment by apastore** [comment]
Thanks to you for implementing this so fast!

**Comment by apastore** [comment]
HI Rorky,

i am still getting a error message from puzzle
[2017-10-09T19:17Z] gpu-2-14.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 313, in detect_fusions
    return ipython.zip_args(apply(rnaseq.detect_fusions, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 134, in detect_fusions
    pizzly_dir = pizzly.run_pizzly(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 50, in run_pizzly
    fusions, samplename, data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 68, in pizzly
    do.run(cmd.format(**locals()), message)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /cbio/ski/abdelwao/nobackup/pastore/bcbio/galaxy/../anaconda/bin/pizzly -k 31 --gtf /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/pizzly/pizzly.gtf --cache /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/pizzly/pizzly.cache --align-score 2 --insert-size 233 --fasta /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/inputs/transcriptome/hg19-mm10.fa --output /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/bcbiotx/tmpy_mmEh/CNS13IGO05667/CNS13IGO05667 /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/kallisto/CNS13IGO05667/quant/fusion.txt
Opening cached file ... loaded 0 genes and 0 transcripts
Error, could not find any transcript sequences check that the ids in the FASTA file and GTF file match
' returned non-zero exit status 1
[2017-10-09T19:17Z] gpu-1-4.local: Running pizzly on /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/kallisto/SUDHL5IGO05667/quant/fusion.txt.
[2017-10-09T19:17Z] gpu-1-4.local: Opening cached file ... loaded 0 genes and 0 transcripts
[2017-10-09T19:17Z] gpu-1-12.local: Error, could not find any transcript sequences check that the ids in the FASTA file and GTF file match
[2017-10-09T19:17Z] gpu-1-12.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /cbio/ski/abdelwao/nobackup/pastore/bcbio/galaxy/../anaconda/bin/pizzly -k 31 --gtf /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/pizzly/pizzly.gtf --cache /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/pizzly/pizzly.cache --align-score 2 --insert-size 221 --fasta /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/inputs/transcriptome/hg19-mm10.fa --output /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/bcbiotx/tmpm_jT7X/SUDHL6IGO05667/SUDHL6IGO05667 /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/kallisto/SUDHL6IGO05667/quant/fusion.txt
Opening cached file ... loaded 0 genes and 0 transcripts
Error, could not find any transcript sequences check that the ids in the FASTA file and GTF file match
' returned non-zero exit status 1
[2017-10-09T19:17Z] gpu-1-12.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 313, in detect_fusions
    return ipython.zip_args(apply(rnaseq.detect_fusions, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 134, in detect_fusions
    pizzly_dir = pizzly.run_pizzly(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 50, in run_pizzly
    fusions, samplename, data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/pizzly.py", line 68, in pizzly
    do.run(cmd.format(**locals()), message)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /cbio/ski/abdelwao/nobackup/pastore/bcbio/galaxy/../anaconda/bin/pizzly -k 31 --gtf /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/pizzly/pizzly.gtf --cache /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/pizzly/pizzly.cache --align-score 2 --insert-size 221 --fasta /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/inputs/transcriptome/hg19-mm10.fa --output /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/bcbiotx/tmpm_jT7X/SUDHL6IGO05667/SUDHL6IGO05667 /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/5667_AZ/5667_AZ/work/kallisto/SUDHL6IGO05667/quant/fusion.txt
Opening cached file ... loaded 0 genes and 0 transcripts

**Comment by roryk** [comment]
Thanks, this is the same issue where we aren't handling disambiguated genomes correctly using pizzly. I'll push a workaround for this tomorrow; I think for now I'll disable pizzly calling on the paired transcriptome like this and just use the disambiguated calls from the target genome, else we'll end up with a bunch of false positive fusions.
