### ISSUE TITLE
Bcftools concat error in mutect

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#2093]
Hi,

Have met with this error which cannot be resolved by upgrading bcbio to the latest developmental version. The error seems to be specific to mutect.
[2017-10-10T01:32Z] bcftools concat variants
[2017-10-10T01:33Z] Different sample names in /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171009_BCMutations/BCasT/work/mutect/chr1_KI270766v1_alt/T0017CYC_230216-chr1_KI270766v1_alt_0_19654.vcf.gz. Perhaps "bcftools merge" is what you are looking for?
[2017-10-10T01:33Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/bcftools concat --allow-overlaps -O z --file-list /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171009_BCMutations/BCasT/work/mutect/T0017CYC_230216-files.list -o /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171009_BCMutations/BCasT/work/bcbiotx/tmpy8FfQG/T0017CYC_230216.vcf.gz
Different sample names in /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171009_BCMutations/BCasT/work/mutect/chr1_KI270766v1_alt/T0017CYC_230216-chr1_KI270766v1_alt_0_19654.vcf.gz. Perhaps "bcftools merge" is what you are looking for?
' returned non-zero exit status 255
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 142, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 194, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
    parallel_fn(combine_name, combine_args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 274, in concat_variant_files
    return vcfutils.concat_variant_files(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 342, in concat_variant_files
    out_file = _run_concat_variant_files_bcftools(input_file_list, out_file, config)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 462, in _run_concat_variant_files_bcftools
    do.run(cmd.format(**locals()), "bcftools concat variants")
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/bcftools concat --allow-overlaps -O z --file-list /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171009_BCMutations/BCasT/work/mutect/T0017CYC_230216-files.list -o /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171009_BCMutations/BCasT/work/bcbiotx/tmpy8FfQG/T0017CYC_230216.vcf.gz
Different sample names in /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171009_BCMutations/BCasT/work/mutect/chr1_KI270766v1_alt/T0017CYC_230216-chr1_KI270766v1_alt_0_19654.vcf.gz. Perhaps "bcftools merge" is what you are looking for?
' returned non-zero exit status 255

Would appreciate if you could look into this issue pls!

**Comment by chapmanb** [comment]
Thanks much for the report and sorry about the issue. Reading the code, I believe this is caused by empty VCFs without sample names which bcftools is apparently failing to merge with standard samples. If you update to the latest development version, remove the problem file that bcftools complains about (`/mnt/projects/ngbhs/cirqseq/2017_bcbio/20171009_BCMutations/BCasT/work/mutect/chr1_KI270766v1_alt/T0017CYC_230216-chr1_KI270766v1_alt_0_19654.vcf.gz.`) and re-run, it should regenerate this and hopefully be able to merge. If there are other problem variant files you may have to remove and regenerate those as well so it might make sense to re-do the mutect calling entirely if there are too many. Hope this works gets your analysis finished. Thanks again.
