### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by aadamk** [chapmanb/bcbio-nextgen#2131]
When running alignment via star, i get the following error: AttributeError: 'NoneType' object has no attribute 'endswith'. 

Any idea what may be the cause? 

A view of the processes running just prior to this:
[2017-10-26T21:17Z] [D] using incremental BAM header parser on parallel recoder.
[2017-10-26T21:17Z] [V] Marked 1048577 (1,0.0489852) time 1.48701 total 01:48700499 MemUsage(size=664.258,rss=32.2344,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 2097153 (2,0.0979703) time 1.44791 total 02:93496799 MemUsage(size=664.258,rss=33.0117,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 3145729 (3,0.146955) time 1.37114 total 04:30616299 MemUsage(size=664.258,rss=33.0117,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 4194305 (4,0.195941) time 1.60522 total 05:91163500 MemUsage(size=664.258,rss=33.0117,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 5242881 (5,0.244926) time 1.54918 total 07:46105100 MemUsage(size=664.258,rss=33.0156,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 6291457 (6,0.293911) time 1.32572 total 08:78684200 MemUsage(size=664.258,rss=33.0156,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 7340033 (7,0.342896) time 1.39414 total 10:18104699 MemUsage(size=664.258,rss=33.0156,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 8388609 (8,0.391881) time 1.59492 total 11:77600499 MemUsage(size=664.258,rss=33.0156,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 9437185 (9,0.440866) time 1.41266 total 13:18875199 MemUsage(size=664.258,rss=33.0156,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 10485761 (10,0.489852) time 1.45127 total 14:64023899 MemUsage(size=664.258,rss=33.0312,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 11534337 (11,0.538837) time 1.591 total 16:23144999 MemUsage(size=664.258,rss=33.0312,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 12582913 (12,0.587822) time 1.39019 total 17:62262600 MemUsage(size=664.258,rss=33.0312,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 13631489 (13,0.636807) time 1.46256 total 19:08541900 MemUsage(size=664.258,rss=33.0312,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 14680065 (14,0.685792) time 1.40268 total 20:48816499 MemUsage(size=664.258,rss=33.0312,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 15728641 (15,0.734777) time 1.50829 total 21:99652899 MemUsage(size=664.258,rss=33.0391,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 16777217 (16,0.783762) time 1.47898 total 23:47574499 MemUsage(size=664.258,rss=33.0391,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 17825793 (17,0.832748) time 1.34555 total 24:82134200 MemUsage(size=664.258,rss=33.0391,peak=1153.05)
[2017-10-26T21:17Z] [V] Marked 18874369 (18,0.881733) time 1.32623 total 26:14763299 MemUsage(size=664.258,rss=33.0391,peak=1153.05)
[2017-10-26T21:18Z] [V] Marked 19922945 (19,0.930718) time 1.53077 total 27:67844200 MemUsage(size=664.258,rss=33.0391,peak=1153.05)
[2017-10-26T21:18Z] [V] Marked 20971521 (20,0.979703) time 1.54952 total 29:22820400 MemUsage(size=664.258,rss=33.0469,peak=1153.05)
[2017-10-26T21:18Z] [V] Marked 1 total for marking time 31:21710900 MemUsage(size=664.711,rss=33.2578,peak=1153.05)
[2017-10-26T21:18Z] [V] MemUsage(size=632.695,rss=33.2617,peak=1153.05) 102.14 (01:42:14007200)
[2017-10-26T21:18Z] Index BAM file: FourPlexFFPE-dedup.bam
[2017-10-26T21:18Z] Counting duplicates in /home/aadam/bcbio/pilotRNA/work/align/FourPlexFFPE/1_10.26.2017_BRCA1BR72_star/FourPlexFFPE.bam.
[2017-10-26T21:18Z] Counting reads in /home/aadam/bcbio/pilotRNA/work/align/FourPlexFFPE/1_10.26.2017_BRCA1BR72_star/FourPlexFFPE.bam.
Traceback (most recent call last):
  File "/home/aadam/bcbio/tools/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/home/aadam/bcbio/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 258, in rnaseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 35, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 186, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 68, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 144, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 329, in run_rnaseq
    metrics.update(_detect_rRNA(data))
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 257, in _detect_rRNA
    quant = os.path.join(sailfish_dir, "quant", "quant.sf")
  File "/home/aadam/bcbio/genomes/anaconda/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by roryk** [comment]
Hi @aadamk,

This is a bug that has been squashed here: https://github.com/chapmanb/bcbio-nextgen/commit/5cdba7d08f0c835d1fa414346da4680042f42897 if you upgrade to the latest version this should get fixed.

**Comment by aadamk** [comment]
Upgraded to development version and it worked - thanks!

**Comment by roryk** [comment]
Great! Thanks for following up and closing the issue, sorry for the problems.
