### ISSUE TITLE
RNA-seq pipeline in bcbio1.0.5: vcfanno error

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#2135]
Hello, @roryk !

Thanks for the great pipeline! 

After upgrading to 1.0.5 stable version, and also upgrading with --datatarget rnaseq,
I encountered an error:

```
2017-10-26T16:24Z] Annotating variation/combined.vcf.gz with vcfanno, using /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/config/vcfanno/rnaedit.conf
[2017-10-26T16:24Z] =============================================
[2017-10-26T16:24Z] vcfanno version 0.2.8 [built with go1.8]
[2017-10-26T16:24Z] see: https://github.com/brentp/vcfanno
[2017-10-26T16:24Z] =============================================
[2017-10-26T16:24Z] vcfanno.go:115: found 1 sources from 1 files
[2017-10-26T16:24Z] bix.go:200: chromosome GL000229.1 not found in /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/editing/RADAR.bed.gz
[2017-10-26T16:24Z] panic: strconv.Atoi: parsing "position": invalid syntax
[2017-10-26T16:24Z] goroutine 16329 [running]:
[2017-10-26T16:24Z] github.com/brentp/irelate.newMerger(0x7cd780, 0x0, 0xc420b1de80, 0x2, 0x2, 0xc420039f58)
[2017-10-26T16:24Z] 	/home/brentp/go/src/github.com/brentp/irelate/irelate.go:229 +0x2d7
[2017-10-26T16:24Z] github.com/brentp/irelate.IRelate(0x7cd778, 0x0, 0x7cd780, 0xc420b1de80, 0x2, 0x2, 0xc420ccc090, 0x10000)
[2017-10-26T16:24Z] 	/home/brentp/go/src/github.com/brentp/irelate/irelate.go:135 +0x69
[2017-10-26T16:24Z] github.com/brentp/irelate.PIRelate.func3.1(0xc420d7a2a0, 0x7cd748, 0xc4201f4750, 0xc420b1de80, 0x2, 0x2)
[2017-10-26T16:24Z] 	/home/brentp/go/src/github.com/brentp/irelate/parallel.go:245 +0x7b
[2017-10-26T16:24Z] created by github.com/brentp/irelate.PIRelate.func3
[2017-10-26T16:24Z] 	/home/brentp/go/src/github.com/brentp/irelate/parallel.go:269 +0x160
[2017-10-26T16:24Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/galaxy/../anaconda/bin/vcfanno -p 1 -lua /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/config/vcfanno/rnaedit.lua -base-path /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37 /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/config/vcfanno/rnaedit.conf variation/combined.vcf.gz | sed -e 's/Number=A/Number=1/g' | bgzip -c > /hpf/largeprojects/ccmbio/naumenko/project_RNAseq_diagnostics/bcbio_buffer/S31_16-1-F/work/bcbiotx/tmpX62rIr/combined-annotated-rnaedit.vcf.gz
```

Could you please help debugging this?

Sergey

**Comment by roryk** [comment]
Thanks, is there a way you could pass along the VCF file that is breaking this so I can test the fix?

**Comment by naumenko-sa** [comment]
It looks like variants on GL* contigs and MT variants cause troubles. The rest annotates well. I don't care about these variants, maybe it is possible to filter them out somewhere in the middle of RNA-seq pipeline?
The example small vcf is here
[test1.vcf.gz](https://drive.google.com/open?id=1rBHTQBG1QOw6Jy29LKm4pSnEFCLBs1pL)

the script to reproduce:
```
#!/bin/bash

tabix $1

/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/galaxy/../anaconda/bin/vcfanno -p 1 \
    -lua /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/config/vcfanno/rnaedit.lua \
    -base-path /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37 \
    /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/config/vcfanno/rnaedit.conf $1 | sed -e 's/Number=A/Number=1/g' | bgzip -c > \
    test-annotated-rnaedit.vcf.gz
```

Thanks!
SN

**Comment by naumenko-sa** [comment]
Hello!
For me, throwing out variants on GL* and MT* helps to move on:
```
#!/bin/bash

#fixes issue https://github.com/chapmanb/bcbio-nextgen/issues/2135

#bcbio rnaseq crashes

cd work/variation

mv combined.vcf.gz combined.before_fixing.vcf.gz
mv combined.vcf.gz.tbi combined.before_fixing.vcf.gz.tbi

bcftools view -o combined.vcf.gz -O z combined.before_fixing.vcf.gz 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y
tabix combined.vcf.gz

cd ../../

#rerun bcbio
```
SN

**Comment by chapmanb** [comment]
Thanks much for this report and the proposed solution, and for your patience as we put it in place. The latest development version of bcbio now subsets to standard chromosomes to hopefully avoid this issue going forward. Please let us know if you run into any other problems at all.
