### ISSUE TITLE
IOError: [Errno 116] Stale file handle

### ISSUE THREAD

**Issue by xexpanderx** [chapmanb/bcbio-nextgen#2143]
I got this error:

```
[2017-11-07T06:31Z] compute03: Unexpected error
Traceback (most recent call last):
  File "/sw/pipelines/bcbio-nextgen/1.0.5/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/sw/pipelines/bcbio-nextgen/1.0.5/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 290, in pipeline_summary
    return ipython.zip_args(apply(qcsummary.pipeline_summary, *args))
  File "/sw/pipelines/bcbio-nextgen/1.0.5/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 68, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/sw/pipelines/bcbio-nextgen/1.0.5/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 146, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/sw/pipelines/bcbio-nextgen/1.0.5/anaconda/lib/python2.7/site-packages/bcbio/qc/coverage.py", line 41, in run
    samtools_stats = samtools.run(bam_file, data, samtools_stats_dir)
  File "/sw/pipelines/bcbio-nextgen/1.0.5/anaconda/lib/python2.7/site-packages/bcbio/qc/samtools.py", line 30, in run
    out = _parse_samtools_stats(stats_file)
  File "/sw/pipelines/bcbio-nextgen/1.0.5/anaconda/lib/python2.7/site-packages/bcbio/qc/samtools.py", line 43, in _parse_samtools_stats
    for line in in_handle:
IOError: [Errno 116] Stale file handle
```

I have no idea what the reason behind this error is. I run bcbio on 8 samples, one sample failed with this error. I attach bcbio-nextgen log files. I run bcbio on a cluster with 8 nodes allocation nodes 1-5. The job scheduler is Slurm.

[bcbio-nextgen.log](https://github.com/chapmanb/bcbio-nextgen/files/1450274/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/chapmanb/bcbio-nextgen/files/1450275/bcbio-nextgen-commands.log)

[bcbio-nextgen-debug.zip](https://github.com/chapmanb/bcbio-nextgen/files/1450281/bcbio-nextgen-debug.zip)

**Comment by roryk** [comment]
Heya, does this happen if you rerun it again? It looks like maybe gluster had a connectivity hiccup and if you restart it should be all good.

**Comment by xexpanderx** [comment]
Rerun bcbio-nextgen without removing the contents in the bcbio folder from which I started the bcbio_nextgen.py command? It will not rerun all commands again?

**Comment by roryk** [comment]
Yep, you can just restart it and it will pick up where it left off.

**Comment by xexpanderx** [comment]
Cool, thank you.

**Comment by xexpanderx** [comment]
It worked by rerunning it.
Thx!

**Comment by roryk** [comment]
Thanks for following up!
