### ISSUE TITLE
Error finding reference genome file GRCh37 samtools

### ISSUE THREAD

**Issue by davised** [chapmanb/bcbio-nextgen#2159]
Hi,

I get this error when running an rna-seq analysis using the best-practices template and my own reads.

```
[2017-11-15T17:34Z] System YAML configuration: /data/davised/bcbio/hsa_prostate/work/bcbio_system-merged.yaml
[2017-11-15T17:34Z] Resource requests: picard; memory: 3.00; cores: 16
[2017-11-15T17:34Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2017-11-15T17:34Z] Timing: organize samples
[2017-11-15T17:34Z] multiprocessing: organize_samples
[2017-11-15T17:34Z] Using input YAML configuration: /data/davised/bcbio/hsa_prostate/config/hsa_prostate.yaml
[2017-11-15T17:35Z] Checking sample YAML configuration: /data/davised/bcbio/hsa_prostate/config/hsa_prostate.yaml
[2017-11-15T17:35Z] Downloading GRCh37 samtools from AWS
Traceback (most recent call last):
  File "/nfs0/Hendrix_Lab/bin/bcbio-tools/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/nfs0/Hendrix_Lab/bin/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 230, in rnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 387, in rnaseq_prep_samples
    [x[0]["description"] for x in samples]]])
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 395, in organize_samples
    return run_info.organize(*args)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 70, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 162, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 226, in get_refs
    galaxy_config, data)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 172, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 310, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file GRCh37 samtools
```

I have installed bcbio using the install script into a local directory as I do not have administrator privileges to install into the default directory.

`
python bcbio_nextgen_install.py /nfs0/Hendrix_Lab/bin/bcbio-source --datatarget rnaseq --datatarget variation --datatarget smallrna --genomes GRCh37 --aligners hisat2 --tooldir=/nfs0/Hendrix_Lab/bin/bcbio-tools --distribution centos --isolate
`

I then manually add the bcbio-tools/bin directory to my path. bash can find the executable just fine.

```
[davised@cytosine bcbio]$ which bcbio_nextgen.py  
/nfs0/Hendrix_Lab/bin/bcbio-tools/bin/bcbio_nextgen.py
```

In case there were errors during installation, I updated the install with this command

`bcbio_nextgen.py upgrade -u stable --tools --data --genomes GRCh37`

I checked the .loc files to make sure the GRCh37 genome is there

```
[davised@cytosine bcbio]$ cat /nfs0/Hendrix_Lab/bin/bcbio-source/galaxy/tool-data/sam_fa_indices.loc
index   GRCh37  /nfs0/Hendrix_Lab/bin/bcbio-source/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
[davised@cytosine bcbio]$ ls /nfs0/Hendrix_Lab/bin/bcbio-source/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
/nfs0/Hendrix_Lab/bin/bcbio-source/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
```

Is there something else I can do to troubleshoot the problem? I examined the tool_data_table_conf.xml file and it seems to have the correct information as well. Is it possible there is a miscommunication between files somewhere?

Thanks!

**Comment by chapmanb** [comment]
Ed;
Sorry about the issues. From the log file, it looks like you have a `bcbio_system-merged.yaml` file in the work directory that is being picked up instead of the installed `bcbio_system.yaml` file in `/nfs0/Hendrix_Lab/bin/bcbio-source/`. It then looks for reference files relative to this work directory file instead of your correctly installed files.

Typically the `-merged` file is from running with `bcbio_vm.py` using a Docker container. It is possible this is an older file from previous attempts? If you remove this and use the `bcbio_system.yaml` shipping with your install, hopefully it'll work cleanly. Please let us know if this doesn't resolve the problem.

**Comment by davised** [comment]
Hi Brad,

Thanks for the speedy response. I've never run bcbio_vm.py, or used the Docker configuration for bcbio.

As far as I can tell, the bcbio_system-merged.yaml was generated when I ran the `bcbio_nextgen.py -w template` command previously.

If I attempt to force the use of the bcbio_system.yaml in the bcbio-source folder, the program still does not seem to recognize it. See below:

```
[davised@cytosine work]$ rm bcbio_system-merged.yaml
[davised@cytosine work]$ ls
bcbiotx  checkpoints_parallel  inputs  log
[davised@cytosine work]$ bcbio_nextgen.py /nfs0/Hendrix_Lab/bin/bcbio-source/galaxy/bcbio_system.yaml ../config/hsa_prostate.yaml
[2017-11-15T20:15Z] System YAML configuration: /data/davised/bcbio/hsa_prostate/work/bcbio_system-merged.yaml
[2017-11-15T20:15Z] Resource requests: picard; memory: 3.00; cores: 16
[2017-11-15T20:15Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2017-11-15T20:15Z] Timing: organize samples
[2017-11-15T20:15Z] multiprocessing: organize_samples
[2017-11-15T20:15Z] Using input YAML configuration: /data/davised/bcbio/hsa_prostate/config/hsa_prostate.yaml
[2017-11-15T20:15Z] Checking sample YAML configuration: /data/davised/bcbio/hsa_prostate/config/hsa_prostate.yaml
[2017-11-15T20:15Z] Downloading GRCh37 samtools from AWS
Traceback (most recent call last):
  File "/nfs0/Hendrix_Lab/bin/bcbio-tools/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/nfs0/Hendrix_Lab/bin/bcbio-tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 230, in rnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 387, in rnaseq_prep_samples
    [x[0]["description"] for x in samples]]])
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 395, in organize_samples
    return run_info.organize(*args)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 70, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 162, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 226, in get_refs
    galaxy_config, data)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 172, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/nfs0/Hendrix_Lab/bin/bcbio-source/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 310, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file GRCh37 samtools
```

Even after removing the bcbio_system-merged.yaml file and pointing to the system bcbio_system.yaml file, the command still gives the error.

**Comment by chapmanb** [comment]
Ed;
Sorry about that, I'm not totally sure what is going on with your install and creating this file. Does there happen to be multiple bcbio_system.yaml files in your install? The correct one should be in:
```
/nfs0/Hendrix_Lab/bin/bcbio-source/galaxy/bcbio_system.yaml
```
but is there also one in:
```
/nfs0/Hendrix_Lab/bin/bcbio-source/config/bcbio_system.yaml
```
Looking at the code that's the logic for creating the merged file. If not, when you remove the `bcbio_system-merged.yaml` file and re-run, does the file get recreated? Could you post the log from when it's removed so we can see if it's finding the same file or something else?

Hope this helps some for debugging.

**Comment by davised** [comment]
Brad,

There are bcbio_system.yaml files in both of those locations. 

If you re-check the previous post, I removed the bcbio_system-merged.yaml before running. The script seems to re-generate the file if it isn't present at startup.

Here's the relevant section:

```
[davised@cytosine work]$ ls
bcbio_system-merged.yaml  bcbiotx  checkpoints_parallel  inputs  log
[davised@cytosine work]$ rm bcbio_system-merged.yaml
[davised@cytosine work]$ ls
bcbiotx  checkpoints_parallel  inputs  log
[davised@cytosine work]$ bcbio_nextgen.py /nfs0/Hendrix_Lab/bin/bcbio-source/galaxy/bcbio_system.yaml ../config/hsa_prostate.yaml
[2017-11-16T16:23Z] System YAML configuration: /data/davised/bcbio/hsa_prostate/work/bcbio_system-merged.yaml
[2017-11-16T16:23Z] Resource requests: picard; memory: 3.00; cores: 16
[2017-11-16T16:23Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2017-11-16T16:23Z] Timing: organize samples
[2017-11-16T16:23Z] multiprocessing: organize_samples
[2017-11-16T16:23Z] Using input YAML configuration: /data/davised/bcbio/hsa_prostate/config/hsa_prostate.yaml
[2017-11-16T16:23Z] Checking sample YAML configuration: /data/davised/bcbio/hsa_prostate/config/hsa_prostate.yaml
[2017-11-16T16:23Z] Downloading GRCh37 samtools from AWS
Traceback (most recent call last):
....
```

Thanks for your help debugging this problem.

**Comment by chapmanb** [comment]
Ed;
Thanks for all the details. There shouldn't be `bcbio_system.yaml` files in both locations, which is likely the source of the issue. I'm not sure how this got into the `config` directory but if you remove that one and leave the one in `galaxy` it should use that, hopefully stop creating the merged file and work correctly. Fingers crossed this fixes it for you.

**Comment by davised** [comment]
Brad,

That seems to have fixed the problem! Nice and easy. Thank you!

**Comment by chapmanb** [comment]
Brilliant, thanks for reporting back.
