### ISSUE TITLE
rna-seq transcript_assembler: cufflinks run instead of sailfish and partition_gtf error

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2166]
Hi, 

I tried the analysis as in https://github.com/chapmanb/bcbio-nextgen/issues/2162 with also transcript_assembler activated.  

I used this yaml file

```
# Template for  RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: BGI_Solexa_pseudochr_2_0
    algorithm:
      aligner: star
      trim_reads: read_through
      adapters: [truseq, polya]
      strandedness: unstranded
      transcript_assembler: sailfish
      variantcaller: gatk-haplotype
upload:
   dir: ../final
```

The alignment with STAR worked and then a single invocation of cufflinks instead of the specified sailfish was run detect new transcripts.  I expected sailfish to be run, and also a sailfish run per sample.  See these log statements and also the final error message. 

```
[2017-11-17T17:03Z] node18: [bam_sort_core] merging from 30 files and 10 in-memory blocks...
[2017-11-17T17:10Z] node6.be.bayercropscience: Index BAM file: SAMPLE_744069.bam
[2017-11-17T17:11Z] node18: Index BAM file: SAMPLE_744068.bam
[2017-11-17T17:15Z] gquest: Resource requests: cufflinks, samtools; memory: 3.00, 3.00; cores: 10, 10
[2017-11-17T17:15Z] gquest: Configuring 10 jobs to run, using 10 cores each with 30.1g of memory reserved for each job
[2017-11-17T17:15Z] gquest: Timing: disambiguation
[2017-11-17T17:15Z] gquest: Timing: transcript assembly
[2017-11-17T17:15Z] gquest: ipython: cufflinks_merge
[2017-11-17T17:16Z] node24: Merging the following transcript assemblies with Cuffmerge:
[2017-11-17T17:16Z] node24: [Fri Nov 17 18:16:00 2017] Beginning transcriptome assembly merge
[2017-11-17T17:16Z] node24: -------------------------------------------
[2017-11-17T17:16Z] node24: [Fri Nov 17 18:16:00 2017] Preparing output location /data/run/Projects/DA-1051/DA_1051-merged/work/bcbiotx/tmpdkNLZq/cuffmerge/
[2017-11-17T17:16Z] node24: [Fri Nov 17 18:16:01 2017] Converting GTF files to SAM
[2017-11-17T17:16Z] node24: [Fri Nov 17 18:16:01 2017] Quantitating transcripts
[2017-11-17T17:16Z] node24: Warning: Could not connect to update server to verify current version. Please check at the Cufflinks website (http://cufflinks.cbcb.umd.edu).
[2017-11-17T17:16Z] node24: Command line:
[2017-11-17T17:16Z] node24: cufflinks -o /data/run/Projects/DA-1051/DA_1051-merged/work/bcbiotx/tmpdkNLZq/cuffmerge/ -F 0.05 -g /workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/genomes/BGI_Solexa_pseudochr_2_0/BGI_Solexa_pseudochr_2_0/rnaseq/ref-transcripts.gtf -q --overhang-tolerance 200 --library-type=transfrags -A 0.0 --min-frags-per-transfrag 0 --no-5-extend -p 10 /data/run/Projects/DA-1051/DA_1051-merged/work/bcbiotx/tmpdkNLZq/cuffmerge/tmp/mergeSam_filepkr1Dv
[2017-11-17T17:16Z] node24: [bam_header_read] EOF marker is absent. The input is probably truncated.
[2017-11-17T17:16Z] node24: [bam_header_read] invalid BAM binary header (this is not a BAM file).
[2017-11-17T17:16Z] node24: File /data/run/Projects/DA-1051/DA_1051-merged/work/bcbiotx/tmpdkNLZq/cuffmerge/tmp/mergeSam_filepkr1Dv doesn't appear to be a valid BAM file, trying SAM...
[2017-11-17T17:16Z] node24: [18:16:01] Loading reference annotation.
[2017-11-17T17:16Z] node24: [18:16:02] Inspecting reads and determining fragment length distribution.
[2017-11-17T17:16Z] node24: Processed 22423 loci.
[2017-11-17T17:16Z] node24: > Map Properties:
[2017-11-17T17:16Z] node24: >       Normalized Map Mass: 0.00
[2017-11-17T17:16Z] node24: >       Raw Map Mass: 0.00
[2017-11-17T17:16Z] node24: >       Fragment Length Distribution: Truncated Gaussian (default)
[2017-11-17T17:16Z] node24: >                     Default Mean: 200
[2017-11-17T17:16Z] node24: >                  Default Std Dev: 80
[2017-11-17T17:16Z] node24: [18:16:02] Assembling transcripts and estimating abundances.
[2017-11-17T17:16Z] node24: Processed 22423 loci.
[2017-11-17T17:16Z] node24: [Fri Nov 17 18:16:14 2017] Comparing against reference file /workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/genomes/BGI_Solexa_pseudochr_2_0/BGI_Solexa_pseudochr_2_0/rnaseq/ref-transcripts.gtf
[2017-11-17T17:16Z] node24: Warning: Could not connect to update server to verify current version. Please check at the Cufflinks website (http://cufflinks.cbcb.umd.edu).
[2017-11-17T17:16Z] node24: [Fri Nov 17 18:16:21 2017] Comparing against reference file /workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/genomes/BGI_Solexa_pseudochr_2_0/BGI_Solexa_pseudochr_2_0/rnaseq/ref-transcripts.gtf
[2017-11-17T17:16Z] node24: Warning: Could not connect to update server to verify current version. Please check at the Cufflinks website (http://cufflinks.cbcb.umd.edu).
[2017-11-17T17:17Z] node24: Cleaning features with an unknown strand from the assembly.
[2017-11-17T17:19Z] node24: Unexpected error
Traceback (most recent call last):
  File "/workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 499, in cufflinks_merge
    return ipython.zip_args(apply(rnaseq.cufflinks_merge, *args))
  File "/workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 246, in cufflinks_merge
    samples[0][0])
  File "/workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/cufflinks.py", line 258, in merge
    data)
  File "/workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/annotate_gtf.py", line 15, in annotate_novel_coding
    ref_fasta, data)
  File "/workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/cpat.py", line 22, in classify_with_cpat
    cutoff, hexamer, logit = get_coding_potential_cutoff(ref_gtf, ref_fasta, data)
  File "/workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/cpat.py", line 112, in get_coding_potential_cutoff
    coding_gtf = gtf.partition_gtf(train_gtf, coding=True)
  File "/workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 161, in partition_gtf
    biotype = biotype_lookup(feature)
TypeError: 'NoneType' object is not callable
```

In between the single `cufflinks` invocation and the final error  `cuffmerge `is also run according to the command log.

Strange thing is also that the `cufflink `command is written to the `debug log` and the `cuffmerge` command  to the `command log`.

`[2017-11-17T17:16Z] node24: cuffmerge -o //data/run/Projects/DA-1051/DA_1051-merged/work/bcbiotx/tmpdkNLZq/cuffmerge --ref-gtf /workspace/my_user/tmp_bcbio_stable_1.0.6/data_dir/genomes/BGI_Solexa_pseudochr_2_0/BGI_Solexa_pseudochr_2_0/rnaseq/ref-transcripts.gtf --num-threads 10 --ref-sequence /workspace/ggher/tmp_bcbio_stable_1.0.6/data_dir/genomes/BGI_Solexa_pseudochr_2_0/BGI_Solexa_pseudochr_2_0/seq/BGI_Solexa_pseudochr_2_0.fa /tmp/16251568.9.main/tmpJsUDqs`

I can find output in the assembly directory
```
assembly/
assembly/cuffmerge
assembly/cuffmerge/logs
assembly/cuffmerge/logs/run.log
assembly/cuffmerge/merged.clean.gtf
assembly/cuffmerge/merged.dirty.gtf
assembly/cuffmerge/merged.clean.clean.fixed.gtf
assembly/cuffmerge/merged.gtf
```

The final error that I get is in the `def partition_gtf` function on the `biotype = biotype_lookup(feature):` line here:
https://github.com/chapmanb/bcbio-nextgen/blob/aa5b67efb78ba0d92d1b621a581c927206ea77ba/bcbio/rnaseq/gtf.py#L161

I am not sure what exactly is going wrong and right here, and how the final error (state) is reached. 
And if this might be related to issue https://github.com/chapmanb/bcbio-nextgen/issues/2162

Could you please advice on how to debug and how  to get `sailfish `and or `cufflinks` working for transcript assembly?

Thank you very much.

**Comment by roryk** [comment]
Hi Neil,

Thanks-- I see you're using a custom genome installation; could you pass along what the ref-transcripts.gtf file is for me? I think what is happening is there are is no coding/non-coding annotation for CPAT to predict coding/non-coding status from and so this part is failing. It would be helpful to have a GTF file to check with.

**Comment by NeillGibson** [comment]
Hi Rory,

Below are the first genes from the gft file.  

```
Chr_01  BGI_GENES       exon    2952    3377    .       -       .       transcript_id "Csa1M000010.1"; gene_id "Csa1G000010"; gene_name "Csa1G000010";
Chr_01  BGI_GENES       exon    3837    4040    .       -       .       transcript_id "Csa1M000010.1"; gene_id "Csa1G000010"; gene_name "Csa1G000010";
Chr_01  BGI_GENES       exon    4131    4284    .       -       .       transcript_id "Csa1M000010.1"; gene_id "Csa1G000010"; gene_name "Csa1G000010";
Chr_01  BGI_GENES       CDS     3324    3377    .       -       0       transcript_id "Csa1M000010.1"; gene_id "Csa1G000010"; gene_name "Csa1G000010";
Chr_01  BGI_GENES       CDS     3837    4040    .       -       0       transcript_id "Csa1M000010.1"; gene_id "Csa1G000010"; gene_name "Csa1G000010";
Chr_01  BGI_GENES       CDS     4131    4199    .       -       0       transcript_id "Csa1M000010.1"; gene_id "Csa1G000010"; gene_name "Csa1G000010";
Chr_01  BGI_GENES       exon    5474    5957    .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    6447    6824    .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    8299    8493    .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    8572    8649    .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    8716    8904    .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    8976    9209    .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    9320    9670    .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    9747    9944    .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    10071   10241   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    10601   10708   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    10775   10990   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    11082   11288   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    12362   12466   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    12553   12666   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    12787   12861   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    13223   13403   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    13922   14089   .       -       .       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     5772    5957    .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     6447    6824    .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     8299    8493    .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     8572    8649    .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     8716    8904    .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     8976    9209    .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     9320    9670    .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     9747    9944    .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     10071   10241   .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     10601   10708   .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     10775   10990   .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     11082   11288   .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     12362   12466   .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     12553   12666   .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     12787   12861   .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       CDS     13223   13384   .       -       0       transcript_id "Csa1M000020.1"; gene_id "Csa1G000020"; gene_name "Csa1G000020";
Chr_01  BGI_GENES       exon    18684   19104   .       +       .       transcript_id "Csa1M000030.1"; gene_id "Csa1G000030"; gene_name "Csa1G000030";
Chr_01  BGI_GENES       exon    19747   20005   .       +       .       transcript_id "Csa1M000030.1"; gene_id "Csa1G000030"; gene_name "Csa1G000030";
Chr_01  BGI_GENES       exon    20244   20438   .       +       .       transcript_id "Csa1M000030.1"; gene_id "Csa1G000030"; gene_name "Csa1G000030";
Chr_01  BGI_GENES       exon    20992   21806   .       +       .       transcript_id "Csa1M000030.1"; gene_id "Csa1G000030"; gene_name "Csa1G000030";
Chr_01  BGI_GENES       CDS     19013   19104   .       +       0       transcript_id "Csa1M000030.1"; gene_id "Csa1G000030"; gene_name "Csa1G000030";
Chr_01  BGI_GENES       CDS     19747   20005   .       +       1       transcript_id "Csa1M000030.1"; gene_id "Csa1G000030"; gene_name "Csa1G000030";
Chr_01  BGI_GENES       CDS     20244   20438   .       +       0       transcript_id "Csa1M000030.1"; gene_id "Csa1G000030"; gene_name "Csa1G000030";
Chr_01  BGI_GENES       CDS     20992   21387   .       +       0       transcript_id "Csa1M000030.1"; gene_id "Csa1G000030"; gene_name "Csa1G000030";
Chr_01  BGI_GENES       exon    22969   23663   .       -       .       transcript_id "Csa1M000040.1"; gene_id "Csa1G000040"; gene_name "Csa1G000040";
Chr_01  BGI_GENES       exon    24572   24813   .       -       .       transcript_id "Csa1M000040.1"; gene_id "Csa1G000040"; gene_name "Csa1G000040";
Chr_01  BGI_GENES       exon    24940   25328   .       -       .       transcript_id "Csa1M000040.1"; gene_id "Csa1G000040"; gene_name "Csa1G000040";
Chr_01  BGI_GENES       exon    27352   27457   .       -       .       transcript_id "Csa1M000040.1"; gene_id "Csa1G000040"; gene_name "Csa1G000040";
Chr_01  BGI_GENES       CDS     23150   23663   .       -       1       transcript_id "Csa1M000040.1"; gene_id "Csa1G000040"; gene_name "Csa1G000040";
Chr_01  BGI_GENES       CDS     24572   24813   .       -       0       transcript_id "Csa1M000040.1"; gene_id "Csa1G000040"; gene_name "Csa1G000040";
Chr_01  BGI_GENES       CDS     24940   25328   .       -       2       transcript_id "Csa1M000040.1"; gene_id "Csa1G000040"; gene_name "Csa1G000040";
```

Let me know if you need the url to the public `gff3` file. This public `gff3` file was cleaned and corrected a bit and then converted to `gft` format via the `gffread` command below. 

`gffread -g sequences.fa -T -o-  genes.gff  > genes.gtf`

**Comment by NeillGibson** [comment]
@roryk  Is the above information enough for you to trouble shoot this issue. Or do you need the link to the public gff3 file. 

It would be nice if CPAT is skipped if the necessary annotation is not present in the genome gtf file. 
Or is there an easy way to add this coding/non coding annotation?

**Comment by NeillGibson** [comment]
@roryk  Also I am still wondering why cufflinks is run instead of sailfish for discovering new transcripts. And why cufflink is only run for a single sample, and not all 23 samples.

**Comment by roryk** [comment]
Hi @NeillGibson,

Thanks, yes it is enough to troubleshoot, I'll push a fix soon. sailfish doesn't do transcript discovery, it just does quantification so we need to use something else other than sailfish for that. Cufflinks for transcript discovery is run on each sample individually and then the assemblies are merged at the end; this is the setup recommended by the Cufflinks and Stringtie folks.

**Comment by roryk** [comment]
Thanks @NeillGibson, I fixed the issue with CPAT. The problem was we were not handling the case where no features labelled as protein_coding to use to try to train the classifier. I added a check for that prior to running CPAT so it should be all set now.

**Comment by NeillGibson** [comment]
Thank you @roryk .
