### ISSUE TITLE
Error on upgrading to include bowtie2

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#2176]
Hi guys - 

  I'm hitting an error when attempting to add the `bowtie2` aligner to one of my bcbio installs. My install configuration looks like this at the outset:

```
> cat config/install-params.yaml
aligners:
- bwa
- star
- rtg
- twobit
datatarget:
- variation
- rnaseq
- smallrna
- gemini
- cadd
- vep
genomes:
- hg19
- hg38-noalt
isolate: true
tooldir: /projects/rdocking_prj/software/bcbio-nextgen/tools
toolplus: []
```

And I run the upgrade command like so:

`> bcbio_nextgen.py upgrade --aligners bowtie2 --cores 16`

The installer errors out at this point:

```
--2017-12-07 08:50:34--  https://github.com/chapmanb/bcbio-nextgen/raw/c523b1a8e6a7c5ced53644894815c856de506f14/config/vcfanno/GRCh37-gnomad_genome.conf
Resolving github.com... 192.30.253.112, 192.30.253.113
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/c523b1a8e6a7c5ced53644894815c856de506f14/config/vcfanno/GRCh37-gnomad_genome.conf [following]
--2017-12-07 08:50:35--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/c523b1a8e6a7c5ced53644894815c856de506f14/config/vcfanno/GRCh37-gnomad_genome.conf
Resolving raw.githubusercontent.com... 151.101.52.133
Connecting to raw.githubusercontent.com|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 5429 (5.3K), 4994 (4.9K) remaining [text/plain]
Saving to: `dbscsnv.conf'

100%[+++++++++++++++=============================================================================================================================================================================>] 5,429       --.-K/s   in 0s

2017-12-07 08:50:35 (103 MB/s) - `dbscsnv.conf' saved [5429/5429]

Traceback (most recent call last):
  File "/projects/rdocking_prj/software/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 338, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 467, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 823, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file, gid)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 32, in install_recipe
    _move_files(tmpdir, base_dir, recipe["recipe"]["full"]["recipe_outfiles"])
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 75, in _move_files
    (out_file, tmp_dir))
AssertionError: Did not find expected output file config/vcfanno/gnomad_genome.conf in /projects/rdocking_prj/software/bcbio-nextgen/data/genomes/Hsapiens/hg19/txtmp
```

I do see an existing file at:

`genomes/Hsapiens/hg19/config/vcfanno/dbscsnv.conf`

But this directory is empty:

`genomes/Hsapiens/hg19/txtmp/config/vcfanno/`

Any thoughts on what could be happening here? This is running stable 1.0.6:

```
[2017-12-07 08:56:15]{rdocking@clingen01}/projects/rdocking_prj/software/bcbio-nextgen/data/> bcbio_nextgen.py --version
1.0.6
```

Thanks again for all your work on bcbio!

**Comment by rdocking** [comment]
Confirmed that I still see the same issue on the latest development version

**Comment by chapmanb** [comment]
Rod -- apologies about the issue. This was a bug from recent additions to the vcfanno configuration files. If you remove your temporary directories (`rm -rf tmpbcbio-install`) and re-run it should download the fixed CloudBioLinux ggd recipes and hopefully work correctly for you. Thanks much for the report and hope this gets your upgrade working cleanly.

**Comment by rdocking** [comment]
Thanks Brad! That seems to have done the trick.
