### ISSUE TITLE
hisat2 install issue

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#2182]
Hi guys, 

  Similar to #2176 , I'm having a bit of an issue getting `hisat2` to add itself to my bcbio install. Here's the relevant output from:

`> bcbio_nextgen.py upgrade --cores 16 --aligners hisat2`

```
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['hisat2', 'bwa', 'star', 'rtg', 'twobit', 'bowtie2'], 'genomes': [{'name': 'Human (hg19)', 'validation': ['giab-NA12878', 'platinum-genome-NA12878', 'giab-NA24385', 'giab-NA24631'], 'annotations': ['GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase', 'ericscript'], 'dbkey': 'hg19', 'indexes': ['seq', 'twobit']}, {'annotations': ['coverage', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'transcripts'], 'name': 'Human (hg38) without alternative alleles', 'dbkey': 'hg38-noalt'}], 'install_uniref': False}'): Human (hg19), Human (hg38) without alternative alleles
2017-12-13 09:16:44,467 - cloudbiolinux - INFO - List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['hisat2', 'bwa', 'star', 'rtg', 'twobit', 'bowtie2'], 'genomes': [{'name': 'Human (hg19)', 'validation': ['giab-NA12878', 'platinum-genome-NA12878', 'giab-NA24385', 'giab-NA24631'], 'annotations': ['GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase', 'ericscript'], 'dbkey': 'hg19', 'indexes': ['seq', 'twobit']}, {'annotations': ['coverage', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'transcripts'], 'name': 'Human (hg38) without alternative alleles', 'dbkey': 'hg38-noalt'}], 'install_uniref': False}'): Human (hg19), Human (hg38) without alternative alleles
INFO: Moving on to next genome prep method after trying ggd
2017-12-13 09:16:44,502 - cloudbiolinux - INFO - Moving on to next genome prep method after trying ggd
INFO: Downloading genome from s3: hg19 hisat2
2017-12-13 09:16:44,502 - cloudbiolinux - INFO - Downloading genome from s3: hg19 hisat2
[localhost] local: pwd
[localhost] local: wget --continue --no-check-certificate -O hg19-hisat2.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg19-hisat2.tar.xz'
--2017-12-13 09:16:44--  https://s3.amazonaws.com/biodata/genomes/hg19-hisat2.tar.xz
Resolving s3.amazonaws.com... 54.231.72.130
Connecting to s3.amazonaws.com|54.231.72.130|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-12-13 09:16:44 ERROR 404: Not Found.


Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O hg19-hisat2.tar.xz 'https://s3.amazonaws.com/biodata/genomes/hg19-hisat2.tar.xz''

INFO: Moving on to next genome prep method after trying s3
2017-12-13 09:16:44,857 - cloudbiolinux - INFO - Moving on to next genome prep method after trying s3
INFO: Preparing genome hg19 with index hisat2
2017-12-13 09:16:44,857 - cloudbiolinux - INFO - Preparing genome hg19 with index hisat2
INFO: Moving on to next genome prep method after trying raw
2017-12-13 09:16:44,931 - cloudbiolinux - INFO - Moving on to next genome prep method after trying raw
Traceback (most recent call last):
  File "/projects/rdocking_prj/software/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 338, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index hisat2 for hg19 by any method
```

Similar to the previous issue, I've tried deleting the `tmpbcbio` and `bcbiotx` directories, but I keep seeing the same issue (on both 1.0.6 and 1.0.7a). Any thoughts? Thanks again!

**Comment by roryk** [comment]
Hi @rdocking,

We only support hisat2 for hg38 or custom genomes at the moment-- we swapped to hisat2 from STAR for hg38 because STAR doesn't handle the alts properly. For hg19 using STAR should give you similar functionality.

**Comment by rdocking** [comment]
OK - thanks! I'll stick with STAR.
