### ISSUE TITLE
Prepare cleaned BED file final sort: cannot create temporary file 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2226]
Hi Brad, I do not know why I am getting this error now, but bcbio is trying to write a temporary file in the scratch folder instead of using the bcbiotx folder. 

The problem is that it fail because it use the PBS/Torque $TMPDIR, and in my case $TMPDIR is the scratch of the submitting Torque  script that call bcbio. 

Thanks a lot!
Alessandro 

[2018-01-18T20:38Z] gpu-2-5.local: Aligning lane P-0023847-T01 with bwa aligner
[2018-01-18T20:38Z] gpu-1-7.local: ipython: delayed_bam_merge
[2018-01-18T20:38Z] gpu-1-7.local: ipython: merge_split_alignments
[2018-01-18T20:38Z] gpu-1-7.local: Timing: callable regions
[2018-01-18T20:38Z] gpu-1-7.local: ipython: prep_samples
[2018-01-18T20:38Z] gpu-2-14.local: Prepare cleaned BED file : P-0021697-T01
[2018-01-18T20:38Z] gpu-2-14.local: sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
[2018-01-18T20:38Z] gpu-2-14.local: sed: couldn't write 1266 items to stdout: Broken pipe
[2018-01-18T20:39Z] gpu-2-14.local: iconv: I/O error
[2018-01-18T20:39Z] gpu-2-14.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpdIoRgP/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2
[2018-01-18T20:39Z] gpu-2-14.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 248, in prep_samples
    return ipython.zip_args(apply(sample.prep_samples, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 191, in prep_samples
    data = clean_inputs(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 210, in clean_inputs
    clean_cov_bed = clean_file(dd.get_coverage(data), data, prefix="cov-", simple=True)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 102, in clean_file
    do.run(cmd.format(**locals()), "Prepare cleaned BED file", data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpdIoRgP/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2
[2018-01-18T20:39Z] gpu-2-10.local: Prepare cleaned BED file : P-0021697-T01
[2018-01-18T20:39Z] gpu-2-10.local: sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
[2018-01-18T20:39Z] gpu-2-10.local: sed: couldn't write 1266 items to stdout: Broken pipe
[2018-01-18T20:39Z] gpu-2-10.local: iconv: I/O error
[2018-01-18T20:39Z] gpu-2-10.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpY5nQW3/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2
[2018-01-18T20:39Z] gpu-2-10.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 248, in prep_samples
    return ipython.zip_args(apply(sample.prep_samples, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 191, in prep_samples
    data = clean_inputs(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 210, in clean_inputs
    clean_cov_bed = clean_file(dd.get_coverage(data), data, prefix="cov-", simple=True)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 102, in clean_file
    do.run(cmd.format(**locals()), "Prepare cleaned BED file", data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpY5nQW3/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2
[2018-01-18T20:39Z] gpu-1-6.local: Prepare cleaned BED file : P-0021697-T01
[2018-01-18T20:40Z] gpu-1-6.local: sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
[2018-01-18T20:40Z] gpu-1-6.local: sed: couldn't write 1266 items to stdout: Broken pipe
[2018-01-18T20:40Z] gpu-1-6.local: iconv: I/O error
[2018-01-18T20:40Z] gpu-1-6.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpdmjv0s/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2
[2018-01-18T20:40Z] gpu-1-6.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 248, in prep_samples
    return ipython.zip_args(apply(sample.prep_samples, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 191, in prep_samples
    data = clean_inputs(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 210, in clean_inputs
    clean_cov_bed = clean_file(dd.get_coverage(data), data, prefix="cov-", simple=True)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 102, in clean_file
    do.run(cmd.format(**locals()), "Prepare cleaned BED file", data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpdmjv0s/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2
[2018-01-18T20:40Z] gpu-2-6.local: Prepare cleaned BED file : P-0021697-T01
[2018-01-18T20:40Z] gpu-2-6.local: sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
[2018-01-18T20:40Z] gpu-2-6.local: sed: couldn't write 1266 items to stdout: Broken pipe
[2018-01-18T20:40Z] gpu-2-6.local: iconv: I/O error
[2018-01-18T20:40Z] gpu-2-6.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpeIVGZc/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2
[2018-01-18T20:40Z] gpu-2-6.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 248, in prep_samples
    return ipython.zip_args(apply(sample.prep_samples, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 191, in prep_samples
    data = clean_inputs(data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 210, in clean_inputs
    clean_cov_bed = clean_file(dd.get_coverage(data), data, prefix="cov-", simple=True)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 102, in clean_file
    do.run(cmd.format(**locals()), "Prepare cleaned BED file", data)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpeIVGZc/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2
2018-01-18 15:40:38.417 [IPClusterStop] Using existing profile dir: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/Project_07951_H/work/log/ipython'
2018-01-18 15:40:38.467 [IPClusterStop] Stopping cluster [pid=2369] with [signal=2]
2018-01-18 15:40:41.120 [IPClusterStop] Using existing profile dir: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/Project_07951_H/work/log/ipython'
2018-01-18 15:40:41.127 [IPClusterStop] Stopping cluster [pid=2369] with [signal=2]
1 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
    fc_dir, run_info_yaml)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 129, in variant2pipeline
    samples = run_parallel("prep_samples", [samples])
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 137, in run
    for data in view.map_sync(fn, items, track=False):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-139>", line 2, in map
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-138>", line 2, in map
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<decorator-gen-118>", line 2, in __call__
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: prep_samples
[13:apply]: CalledProcessError: Command 'set -o pipefail; zcat /cbio/ski/abdelwao/home/pastore/nobackup/install/bcbio-vm/data/project/Project_07951_H/AgilentExon_51MB_b37_V4.bed.gz | grep -v ^track | grep -v ^browser | grep -v ^# | iconv -c -f utf-8 -t ascii | sed 's/ //g' | /cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpeIVGZc/cov-AgilentExon_51MB_b37_V4.bed
sort: cannot create temporary file in `/scratch/9294853.hal-sched1.local': No such file or directory
sed: couldn't write 1266 items to stdout: Broken pipe
iconv: I/O error
' returned non-zero exit status 2

**Comment by apastore** [comment]
I have add  to {sort_cmd} in bedutils.py -T {bedprep_dir}
and it work fine for me

**Comment by apastore** [comment]
I have also found the same issue in structural/regions.py and structural/annotate.py
in structural/prioritize.py is already fixed with {sort_cmd} -T {tmpdir} -k3,3 -k4,4n;

**Comment by chapmanb** [comment]
Thanks much for the report and digging into the underlying cause. I pushed a fix that should use the defined bcbio temporary directory for sort commands to avoid this problem. I generalized it and it should handle all of the cases you specifically call out. Please let us know if you run into any other issues.
