### ISSUE TITLE
Picard do not pick coda Java

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2228]
Hi Brad, it seams the Picard script in  Bcbio is picking my standard installed Java ( /usr/java/latest/bin/java ) and ignore the $JAVA_HOME or the conda Java. I have also tried to set .bashrc $JAVA_HOME to conda and also Torque pass conda $JAVA_HOME

I had to hardcoded $java and $JAVA_HOME in /cbio/ski/abdelwao/nobackup/pastore/bcbio/anaconda/share/picard-2.17.2-0/picard to make it run 

Thanks a lot!
Alessandro 

```
' returned non-zero exit status 1
[2018-01-19T23:50Z] gpu-1-12.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 387, in concat_variant_files
    return ipython.zip_args(apply(vcfutils.concat_variant_files, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 338, in concat_variant_files
    input_file_list = _get_file_list(orig_files, out_file, regions, ref_file, config)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 365, in _get_file_list
    exist_files = _fix_gatk_header(exist_files, out_file, config)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 399, in _fix_gatk_header
    "Reheader initial VCF file in merge")
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; picard FixVcfHeader HEADER=/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/bcbiotx/tmpOXCBG_/P-0023847-N01-1_0_15509832-fixheader-header.vcf INPUT=/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/Project_07951_H/work/platypus/1/P-0023847-N01-1_0_15509832.vcf.gz OUTPUT=/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/Project_07951_H/Project_07951_H/work/platypus/P-0023847-N01-1_0_15509832-fixheader.vcf.gz
/usr/java/latest/bin/java
/cbio/ski/abdelwao/nobackup/pastore/bcbio/anaconda/share/picard-2.17.2-0
Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
' returned non-zero exit status 1
```

 $qstat -f  <JOBID>
.....
Variable_List = PBS_O_QUEUE=batch,
	PBS_O_HOME=...... 
	JAVA_HOME=/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda,
.....

**Comment by chapmanb** [comment]
Alessandro;
Thank you for the detailed report and apologies about the issue. We weren't correctly setting the environmental variables for this call to correctly use the internal bcbio java. I pushed a fix to the latest development version that should resolve this. Please let us know if you run into any other issues at all and thank you again.
