### ISSUE TITLE
GATK4 command options format

### ISSUE THREAD

**Issue by ameynert** [chapmanb/bcbio-nextgen#2230]
See https://software.broadinstitute.org/gatk/documentation/article?id=11050 for specifications. Camel case and underscore-separated parameters are throwing up errors.

Bcbio 1.0.7, running tools_on: gatk4

Errors e.g.
```Exception in thread "main" org.broadinstitute.hellbender.exceptions.UserException: '--javaOptions' is not a valid command.

	at org.broadinstitute.hellbender.Main.extractCommandLineProgram(Main.java:341)
	at org.broadinstitute.hellbender.Main.setupConfigAndExtractProgram(Main.java:172)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:192)
	at org.broadinstitute.hellbender.Main.main(Main.java:275)
' returned non-zero exit status 1
```

and
```***********************************************************************

A USER ERROR has occurred: sparkMaster is not a recognized option

***********************************************************************
```

Fix locations as I worked to get BaseRecalibrator running:
```
line 524 broad/__init__.py javaOptions
line 114 variation/gatk.py sparkMaster
line 92,129 variation/recalibrate.py sparkMaster
line 106 variation/recalibrate.py knownSites
line 62 variation/gatk.py interval_set_rule
line 45 variation/mutect2.py interval_set_rule
lines 59,215 variation/mutect.py interval_set_rule
line 37 variation/realign.py interval_set_rule
line 108 variation/recalibrate.py interval_set_rule
line 504 variation/vcfutils.py interval_set_rule
```

**Comment by chapmanb** [comment]
Alison;
Sorry about this issue. A number of command line parameters changed for the GATK 4.0.0.0 release that were not in the GATK 4 beta versions. This is all fixed in the latest development version so you can either update to that or downgrade GATK4 to the last beta in your 1.0.7 install:
```
bcbio_conda install -c conda-forge -c bioconda gatk4=4.0b6
```
We hope to have a 1.0.8 release soon so we have a stable GATK 4.0.0.0 released version of bcbio. Thank you for bringing up this discussion.
