### ISSUE TITLE
GATK4 GenomicsDBImport can fail when parallelized via bcbio on a SGE cluster

### ISSUE THREAD

**Issue by WimSpee** [chapmanb/bcbio-nextgen#2232]
Hi,

GATK4 GenomicsDBImport can fail when parallelized via bcbio on a SGE cluster. It seems like the _genomicsdb directory can't be created sometimes for some not reported reason. 

According to the bcbio log I got this error for 16 regions before I aborted. 224 regions gave no error and had already produced merged vcf output files. 

```
16:19:49.986 INFO  GenotypeGVCFs - Initializing engine
terminate called after throwing an instance of 'VariantQueryProcessorException'
  what():  VariantQueryProcessorException : Could not open array genomicsdb_array at workspace: /data/run/Projects/analysis_1234/joint/gatk-haplotype-joint/DA_1052/Chr_01/DA_1052-Chr_01_5275959_5608907_genomicsdb
' returned non-zero exit status 250
[2018-01-22T15:31Z] my_clustern24: Uncaught exception occurred
Traceback (most recent call last):
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/my_cluster/workspace/my_user/tmp_bcbio_1.0.7_development/data_dir/anaconda/bin:$PATH && gatk-launch --java-options '-Xms500m -Xmx28665m -XX:+UseSer
ialGC -Djava.io.tmpdir=/data/run/Projects/analysis_1234/joint/gatk-haplotype-joint/DA_1052/Chr_01/bcbiotx/tmpvjKc9Y' GenomicsDBImport --reader-threads 10 --genomicsdb-workspace-path DA_1052-Chr_01_31142604_31604986_genomi
csdb -L Chr_01:31142605-31604986 --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_06.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_08.vcf.gz --variant /da
ta/run/Projects/analysis_1234/gatk-haplotype/DA_1052_03.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_11.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_10.vcf.gz
--variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_16.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_01.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-hap
lotype/DA_1052_12.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_05.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_02.vcf.gz --variant /data/run
/Projects/analysis_1234/gatk-haplotype/DA_1052_15.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_09.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_14.vcf.gz --vari
ant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_04.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype/DA_1052_07.vcf.gz --variant /data/run/Projects/analysis_1234/gatk-haplotype
/DA_1052_13.vcf.gz
```

- Running the above command separately works. 
- Running the GATK4 merge for all callable regions sequentially using 1 CPU also works, but this ofcourse is much slower than running all callable regions in parallel using multiple CPU. 

Sometimes the crash occurs after that the directory genomicsdb directory has been created. 
This makes it difficult to restart the analysis, since the restarted analysis will crash on the already existing directories, which have to be removed 1 by 1. 

Could you provided advice on how to debug fix the issue of running the `GenomicsDBImport  `step in parallel?

It would also be helpful if the `GenomicsDBImport `step was run inside a transaction like the rest of the computation steps in bcbio. Somewhere I read that `GenomicsDBImport  `is currently run outside of a transaction for a good reason, but I don't remember what the reason was and if that reason is still valid. 

Would it be possible to run `GenomicsDBImport` inside of a transaction? That would make it much easier to restart the bcbio analysis to let it finish the regions where  `GenomicsDBImport` for some reason crashed. 

Thank you.

**Comment by chapmanb** [comment]
Thanks for the detailed report and sorry about the issues. Unfortunately bcbio can't use transactional directories because the GenomicsDB workflow directory uses absolute paths and can't be moved after creation. More details on that are in the code comments here:

https://github.com/chapmanb/bcbio-nextgen/blob/72a55ac3abedc3c358e48fc1ed7717b6d74c5019/bcbio/variation/gatkjoint.py#L36

As far as I know that restriction is still in place, but if not we'd be happy to switch over to those.

We have code that tries to detect incomplete directories and remove them, but it appears to not be catching your case here:

https://github.com/chapmanb/bcbio-nextgen/blob/72a55ac3abedc3c358e48fc1ed7717b6d74c5019/bcbio/variation/gatkjoint.py#L63

Could you share the `tree` output of one of the crashed directories bcbio doesn't detect as incomplete? We could improve the checking so bcbio will automatically remove and recreate these.

Also, do you have a sense of why the initial runs fail? There is not much helpful to debug from what got spit out from the GenomicsDBImport run. Is this due to filesystem IO issues during the parallel run? I'd also love to fix that issue so you get clean runs on the first try without needing to restart.

Thanks again for the report and help debugging.

**Comment by WimSpee** [comment]
Hi @chapmanb . Most failed regions had empty `_genomicsdb` output directories. A simple bcbio restart produced seemingly correct output  for these regions.

A few regions had the following short file tree. I think here the GenotypeGVCF step either failed, or was even run on the partial output of a failed  `GenomicsDBImport` command. 

```
find   joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_22861982_23154816_genomicsdb/
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_22861982_23154816_genomicsdb/
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_22861982_23154816_genomicsdb/__tiledb_workspace.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_22861982_23154816_genomicsdb/vidmap.json
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_22861982_23154816_genomicsdb/callset.json
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_22861982_23154816_genomicsdb/vcfheader.vcf
```

For comparison this is how the file tree looks for regions that finished correctly:
```
find joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/__tiledb_workspace.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__array_schema.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/.__consolidation_lock
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/genomicsdb_meta.json
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/REF_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/ALT_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/ID_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/FILTER_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MLEAC_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MLEAF_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/AD_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/GT_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MMQ_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/PGT_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/PID_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/PL_var.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/END.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/REF.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/ALT.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/ID.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/QUAL.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/FILTER.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/BaseQRankSum.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/ClippingRankSum.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/DP.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/DS.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/ExcessHet.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/InbreedingCoeff.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MLEAC.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MLEAF.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MQ.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MQ0.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MQRankSum.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/RAW_MQ.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/ReadPosRankSum.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/AD.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/GQ.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/GT.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MIN_DP.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/MMQ.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/PGT.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/PID.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/PL.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/SB.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/DP_FORMAT.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/__coords.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/__book_keeping.tdb.gz
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/genomicsdb_array/__199ff967-98af-4d03-b28d-bbaae5bf57ef140634606425856_1516704137779/__tiledb_fragment.tdb
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/vidmap.json
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/callset.json
joint/gatk-haplotype-joint/DA_1052/Chr_06/DA_1052-Chr_06_0_340457_genomicsdb/vcfheader.vcf
```

Removing the `_genomicsdb` output directory and then restarting bcbio also fixed these issues.
rm -rf  joint/gatk-haplotype-joint/VSDA_1052/Chr_06/VSDA_1052-Chr_06_22861982_23154816_genomicsdb/

Doing an more elaborate check on (in)complete `_genomicsdb` output directories, and removing if incomplete, should results in bcbio restarts completing the previously failed regions. 

https://github.com/chapmanb/bcbio-nextgen/blob/72a55ac3abedc3c358e48fc1ed7717b6d74c5019/bcbio/variation/gatkjoint.py#L63

I still don't know what is causing the GVCF merge for the regions to fail in the first place.

**Comment by chapmanb** [comment]
Thanks much for the example of the problem directories that we're getting removed. I added an additional check to the command that looks for incomplete directories so bcbio should correctly identify and re-create these on a re-run. Hopefully this makes the process for recovering from these issues smoother. If you can identify any underlying causes for the original failures I'd also be happy to look at resolving that. Hope this gets your analysis finished and thanks again for all the help debugging.
