### ISSUE TITLE
GATK4 squaring off RNAseq gVCF variant calling:  AssertionError: Input file is bgzipped but not found

### ISSUE THREAD

**Issue by WimSpee** [chapmanb/bcbio-nextgen#2233]
Hi,

Squaring off GATK4 RNAseq variant calling results runs into an assertion error about the input vcf.gz file. 

My yaml is 
```
# Template for  RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: UC_Illumina_pseudochr_6
    algorithm:
      aligner: star
      strandedness: unstranded
      transcript_assembler: [stringtie, cufflinks]
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
upload:
   dir: ../final
```

The full error is:
```
Traceback (most recent call last):
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/tool_dir/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/tool_dir/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 261, in rnaseqpipeline
    samples = rnaseq.rnaseq_variant_calling(samples, run_parallel)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 53, in rnaseq_variant_calling
    for d in joint.square_off(samples, run_parallel):
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 143, in square_off
    "vrn_file", ["region", "sam_ref", "config"])
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 367, in square_batch_region
    return joint.square_batch_region(*args)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 184, in square_batch_region
    gatkjoint.run_region(data, region, vrn_files, out_file)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/variation/gatkjoint.py", line 22, in run_region
    genomics_db = _run_genomicsdb_import(vrn_files, region, out_file, data)
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/variation/gatkjoint.py", line 57, in _run_genomicsdb_import
    vcfutils.bgzip_and_index(vrn_file, data["config"])
  File "/home/my_user/workspace/tmp_bcbio_1.0.7_development/data_dir/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 601, in bgzip_and_index
    assert not in_file == out_file, "Input file is bgzipped but not found: %s" % in_file
AssertionError: Input file is bgzipped but not found: variation/rnaseq/gatk-haplotype/DA_1083_01-gatk-haplotype.vcf.gz
```

The file does actually exist relative to the work dir:

```
 ls -lh variation/rnaseq/gatk-haplotype/DA_1083_01-gatk-haplotype.vcf.gz
-rw-rw-r--+ 1 my_user users 103M Jan 23 08:37 variation/rnaseq/gatk-haplotype/DA_1083_01-gatk-haplotype.vcf.gz
```

This is the place in the bcbio code where the exception is thrown. 
https://github.com/chapmanb/bcbio-nextgen/blob/9aef0f904fec0a5fa8a7c54506677e2683b65e2f/bcbio/variation/vcfutils.py#L602

I am not sure how the state is reached that causes the assert to fail. Maybe the RNAseq script calls the `bgzip_and_index` function with 1 or more wrong arguments (.e.g. `out_dir` specified were it should be `None`)?

Thank you.

**Comment by chapmanb** [comment]
Thank you for the issue and apologies about the problem. `jointcaller` is not required for doing RNA-seq variant calling since it gets set internally in the code, but it should also not trigger this error. I pushed a fix for this by correctly providing a full path (instead of relative) for the problem file, so if you update to the latest development and re-run it should now work cleanly. Please let us know if you run into any other issues.
