### ISSUE TITLE
Spark timeout errors with BaseRecalibrator and GATK 4

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2252]
CC @LMannarino 

As the subject says, I *think* this is the error, but I'm not sure because the Spark errors are truly hard to read and very hard to debug.

What I see in the logs are errors like

```
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 124499 ms exceeds timeout 120000 ms
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 ERROR TaskSchedulerImpl: Lost executor driver on localhost: Executor heartbeat timed out after 124499 ms
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 WARN TaskSetManager: Lost task 2.0 in stage 0.0 (TID 2, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 124499 ms18-02-05T09:52Z] sonobe: 18/02/05 10:52:22 ERROR TaskSetManager: Task 2 in stage 0.0 failed 1 times; aborting job
```

Followed later by

```
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 INFO TaskSchedulerImpl: Cancelling stage 0
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 INFO BlockManagerInfo: Added broadcast_2_piece14 in memory on 192.168.0.235:44294 (size: 4.0 MB, free: 11.1 GB)
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 INFO BlockManagerInfo: Added broadcast_2_piece5 in memory on 192.168.0.235:44294 (size: 4.0 MB, free: 11.1 GB)
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 INFO BlockManagerInfo: Added broadcast_2_piece119 in memory on 192.168.0.235:44294 (size: 4.0 MB, free: 11.1 GB)
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 INFO DAGScheduler: ShuffleMapStage 0 (treeAggregate at BaseRecalibratorSparkFn.java:39) failed in 3338.634 s
```

And ultimately ending with

```
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 WARN Executor: Issue communicating with driver in heartbeater
[2018-02-05T09:52Z] sonobe: java.lang.NullPointerException
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.storage.memory.MemoryStore.getSize(MemoryStore.scala:127)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$getCurrentBlockStatus(BlockManager.scala:387)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.storage.BlockManager$$anonfun$reportAllBlocks$3.apply(BlockManager.scala:218)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.storage.BlockManager$$anonfun$reportAllBlocks$3.apply(BlockManager.scala:217)
[2018-02-05T09:52Z] sonobe:     at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[2018-02-05T09:52Z] sonobe:     at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.storage.BlockManager.reportAllBlocks(BlockManager.scala:217)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:236)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:522)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply$mcV$sp(Executor.scala:547)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:547)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:547)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1953)
[2018-02-05T09:52Z] sonobe:     at org.apache.spark.executor.Executor$$anon$1.run(Executor.scala:547)
[2018-02-05T09:52Z] sonobe:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2018-02-05T09:52Z] sonobe:     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
[2018-02-05T09:52Z] sonobe:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
[2018-02-05T09:52Z] sonobe:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
[2018-02-05T09:52Z] sonobe:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2018-02-05T09:52Z] sonobe:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2018-02-05T09:52Z] sonobe:     at java.lang.Thread.run(Thread.java:745)
[2018-02-05T09:52Z] sonobe: 18/02/05 10:52:22 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
```

It happens for all BAM files I've been testing (large exome-like data). How can I dig more?

**Comment by lbeltrame** [comment]
I've noticed that the java process simply dies at one point. No logs or information available prior to the timeout.

**Comment by chapmanb** [comment]
Luca;
Thanks for the report and apologies about the issue. I'm new to debugging Spark multiprocessing issues as well and haven't seen this but happy to try and walk through it and figure out what is going on.

From the messages you posted the underlying issue is that the sub-tasks are becoming unresponsive to pings from the master and then the master kills the overall process. It's not clear from what's here now why that happens. Specifically I'm not sure if the NullException error is a cause or consequence of the timeouts.

Would you be able to supply the command that's causing the issue? It would also be helpful to see the full error log as a gist in case there is anything else we can dig out. I'm specifically looking to see if there is some fundamental communication issue (the parent can never talk to the workers) or if there is a resource issue (workers get bogged down by processing and can't communicate with the parent).

Thanks much for the help debugging.

**Comment by lbeltrame** [comment]
Thanks Brad. I'll check later with a single BAM file which should show the problem to make sure there isn't anything off.

**Comment by lbeltrame** [comment]
FInally I was able to reproduce it with a fresh analysis. 

The used command was:

```
export SPARK_USER=einar && unset JAVA_HOME && export PATH=/opt/bcbio/anaconda/bin:$PATH && gatk-launch --java-options '-Xms500m -Xmx26209m -Djava.io.tmpdir=/scratch/tmprMGfL_' BaseRecalibratorSpark -I /data/bioinformatics/einar/M-250/work/align/20976/20976-sort.bam --spark-master local[8] --output /scratch/tmprMGfL_/20976-sort-recal.grp --reference /opt/bcbio/genomes/Hsapiens/hg19/ucsc/hg19.2bit --conf spark.local.dir=/scratch/tmprMGfL_ --known-sites /opt/bcbio/genomes/Hsapiens/hg19/variation/dbsnp-150.vcf.gz -L /data/bioinformatics/einar/M-250/work/bedprep/cleaned-Agilent_FocusedExome.bed --interval-set-rule INTERSECTION
```

The "FocusedExome" bed is the variant BED region of Agilent's OneSeq kit.
I'll be digging the log from the debug log and post it on a gist momentarily.

**Comment by lbeltrame** [comment]
And here's the full log from a single machine in the cluster:

https://gist.github.com/lbeltrame/b098694b3113f6b3e13e73e6bc41f70a

**Comment by lbeltrame** [comment]
As far as I can tell, the processes keep on going until the timeout is reached.  The best I can see through strace is that there are timeouts.  This happens once the `KnownSitesCache` is complete.

**Comment by lbeltrame** [comment]
Indeed that was the case, I had a process go on for more than an hour before timing out and strace showed timeouts all around. The `java` executable was still running though.

**Comment by lbeltrame** [comment]
I can confirm this only happens with `BaseRecalibrator`, because ot her tools like MuTect are completely unaffected.  I struggle to find a reason for this though. I might try a single BAM out of the pipeline, on local disks (to prevent possible network shares problems) and see what happens.

**Comment by chapmanb** [comment]
Luca;
Thanks for all this debugging and work. As far as I can tell you're right on in your diagnosis that there isn't an explicit failure reported beyond the timeouts. I did some digging and one suggestion for timeouts is memory issues which makes me think it might be getting overwhelmed on your machine:

https://github.com/broadinstitute/gatk/issues/3186#issuecomment-313197140

If you turn down memory usage and cores (`-Xmx` and `--spark-master local[8]`) and re-run on the same machines do you still see timeouts. It would be useful to start with something small (`-Xmx4g` and `local[1]` to see if that still works. It would also be helpful to know if you can get it to fail on other machines as well. Finally, if you could share a reproducible error case I could also try to run elsewhere.

Thanks again for all the work debugging this.

**Comment by lbeltrame** [comment]
I reproduced this outside the pipeline: it randomly dies when caching the known variants (no specific point).

I'm not too sure it has to do with the RAM as I chose a non-loaded machine (0 tasks running) and with plenty of RAM (128G) to do the testing. When running with `Xmx32g`, I see that the java process uses around 25G in total. 

I'll do some more experiments with RAM and core number.

**Comment by lbeltrame** [comment]
Doubling the allocated RAM made it (so far) not crash (currently sitting at ~30G). If this turns indeed to be a RAM problem, this needs to be "somehow" handled (or mentioned in the docs) as regression, because with the same data set GATK 3.8 handles with the allocated 24G just fine.

**Comment by lbeltrame** [comment]
Spoke too soon. It failed again. I'll run another test with more RAM for the executor. I'm doing the experiments with cores last because a single run can take more than one hour.

**Comment by lbeltrame** [comment]
I admit I'm kind of stuck.Memory doesn't seem to be an issue (it never ever came close to the lmit) but the whole process is surprisingly opaque and hard to debug.

**Comment by chapmanb** [comment]
Luca;
Thanks for all this work and sorry to not know exactly what to do here. Are you able to share a problem BAM file privately so I can try to reproduce? Or are you able to test one of your files on a non-cluster machine like AWS to determine if it is something specific to your architecture? If neither works, my best suggestion at this point would be to raise a ticket on the GATK issue tracker to see if they have additional ideas. I'm not sure why it's causing so many issues for your runs but keen to figure out what is happening and fix.

**Comment by lbeltrame** [comment]
Yes, before sending a report to the GATK I'll give you a link to download (it's large) a problematic BAM file privately.

**Comment by chapmanb** [comment]
Luca;
Thanks for sending the file and I wanted to update you on my testing so far. The file you sent works fine for me running on AWS (m4.2xlarge with 8 cores and 32Gb of memory) so I don't think the problem is anything data specific. However, I am able to reproduce the same issue you're seeing on one of our local clusters so can confirm there is something going on in regards to the networking or processing on different systems. I'm trying some spark configuration option tweaking to determine if I can avoid the issue. Sorry to not know exactly what is going on but I feel like I'm making some progress by being able to reproduce. Thanks again for the help debugging this and I'll follow up when I have more of an idea of what to try.

**Comment by lbeltrame** [comment]
Brilliant, thanks Brad! I'll be sure to check once the current run is over.

**Comment by lbeltrame** [comment]
I saw that you made a change in `ApplyBQSR` while I had the issue in `BaseRecalibrator`. Perhaps the same fix should be applied there.

**Comment by chapmanb** [comment]
Luca -- apologies for sticking the workaround in the wrong spot. I also added to BaseRecalibratorSpark now. Let me know if you spot any other issues at all.

**Comment by lbeltrame** [comment]
I'm running it standalone as we speak. I'll let you know.

**Comment by lbeltrame** [comment]
It's still really suboptimal. No timeouts in sight at the moment but not even a completion after more than 2 hours (!). How much did it take for you in your tests?

I'm considering filing a bug at the GATK, given that the performance regression compared with 3.8 is massive.

**Comment by chapmanb** [comment]
Luca;
Your BAM did take a few hours on an AWS machine, so that's in line with what I saw. We don't really use BQSR for runs so I don't have a ton of experience but the major downside to GATK4 is the lack of built in downsampling support which GATK3 had. The multi-core parallelization should offset a little bit of it but it'll get tough for larger files. I don't know about their plans for built in downsampling or how best to enable something equivalent in GATK4, so if you do raise a ticket please cc me on it so I can follow as well. Thanks again.

**Comment by lbeltrame** [comment]
I use BQSR mostly because I want "cleaner" calls for germline, IIRC there wasn't much difference for somatic variants. 
Glad to know that you had comparable runtimes (my machines are Opterons without AVX instructions, so everything runs slower). I'll make sure to CC you in the ticket.

**Comment by lbeltrame** [comment]
I wonder if the slow speed is somehow related to [this open ticket](https://github.com/broadinstitute/gatk/issues/4300)?

**Comment by lbeltrame** [comment]
Digging and commenting led me to https://github.com/broadinstitute/gatk/issues/4376, which mentions either a revert or a PR pending to fix this particular issue.

**Comment by heuermh** [comment]
@lbeltrame @chapmanb While waiting for the GATK team to investigate the suggestions [we](https://github.com/bigdatagenomics/adam) made on the above mentioned issue, I wonder if you'd be willing to share the BAM file and the source of the 2bit reference (`/opt/bcbio/genomes/Hsapiens/hg19/ucsc/hg19.2bit` in the command line above) so that we might independently see if there is anything happening on our side?

**Comment by chapmanb** [comment]
Michael -- I don't think this is specific to any BAM file so you could use anything you have convenient. Luca's BAM didn't show the problem for me on an AWS instance but I found the same issue with a totally different BAM on a different machine. So no need to pass anything along, just grab something you already have for testing. The 2bit is also not fancy, just the output for `faToTwoBit` on the bcbio reference fasta (https://s3.amazonaws.com/biodata/genomes/hg19-seq.tar.gz). Hope this helps.

**Comment by heuermh** [comment]
Thank you, Brad!  I'll do some testing on our internal cluster resources and on AWS EMR.

**Comment by lbeltrame** [comment]
It looks like the issue is now fixed according to https://github.com/broadinstitute/gatk/issues/4376. We might want to be on the lookout for a new GATK release.

**Comment by chapmanb** [comment]
Luca -- thanks for following up. There was a new release with this fix and it's in bioconda (4.0.2.0) so a bcbio update will grab it. I've been working on rebuilding the Docker containers with this for testing but feel free to update and test directly and let us know if you still have any issues. Thanks so much.

**Comment by heuermh** [comment]
@lbeltrame @chapmanb Please continue to update your experience here.  The fix above wasn't actually a fix, it simply rolled back to an earlier version.  As we mentioned in the linked issue, we have not been able to reproduce the performance issue in ADAM nor have identified any root cause in GATK4.

**Comment by mchimenti** [comment]
Hello, I am trying to run an exome validation on NA12878 and running into a similar issue: 

Here's an excerpt from the log: 
[2018-03-26T18:58Z] 13:58:55.345 INFO  KnownSitesCache - Number of variants read: 280600001
[2018-03-26T18:58Z] 13:58:55.647 INFO  KnownSitesCache - Number of variants read: 280700001
[2018-03-26T18:58Z] 13:58:55.959 INFO  KnownSitesCache - Number of variants read: 280800001
[2018-03-26T18:58Z] 13:58:56.279 INFO  KnownSitesCache - Number of variants read: 280900001
[2018-03-26T18:58Z] 13:58:56.599 INFO  KnownSitesCache - Number of variants read: 281000001
[2018-03-26T18:58Z] 13:58:56.905 INFO  KnownSitesCache - Number of variants read: 281100001
[2018-03-26T18:58Z] 13:58:57.214 INFO  KnownSitesCache - Number of variants read: 281200001
[2018-03-26T18:58Z] 13:58:57.543 INFO  KnownSitesCache - Number of variants read: 281300001
[2018-03-26T18:58Z] 13:58:57.851 INFO  KnownSitesCache - Number of variants read: 281400001
[2018-03-26T19:01Z] 18/03/26 14:01:40 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 167185 ms exceeds timeout 120000 ms
[2018-03-26T19:01Z] 18/03/26 14:01:40 ERROR TaskSchedulerImpl: Lost executor driver on localhost: Executor heartbeat timed out after 167185 ms
[2018-03-26T19:01Z] 18/03/26 14:01:40 WARN TaskSetManager: Lost task 8.0 in stage 0.0 (TID 8, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 167185 ms
[2018-03-26T19:01Z] 18/03/26 14:01:40 ERROR TaskSetManager: Task 8 in stage 0.0 failed 1 times; aborting job
[2018-03-26T19:01Z] 18/03/26 14:01:40 WARN TaskSetManager: Lost task 11.0 in stage 0.0 (TID 11, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 167185 ms
[2018-03-26T19:01Z] 18/03/26 14:01:40 WARN TaskSetManager: Lost task 2.0 in stage 0.0 (TID 2, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 167185 ms
[2018-03-26T19:01Z] 18/03/26 14:01:40 WARN TaskSetManager: Lost task 5.0 in stage 0.0 (TID 5, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 167185 ms
[2018-03-26T19:01Z] 18/03/26 14:01:40 WARN TaskSetManager: Lost task 14.0 in stage 0.0 (TID 14, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 167185 ms
[2018-03-26T19:01Z] 18/03/26 14:01:40 WARN TaskSetManager: Lost task 13.0 in stage 0.0 (TID 13, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 167185 ms
-------------

The errors continue like this for hundreds of lines.  Finally ending with this: 
----------------
org.apache.spark.SparkException: Job aborted due to stage failure: Task 8 in stage 0.0 failed 1 times, most recent failure: Lost task 8.0 in stage 0.0 (TID 8, localhost): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 167185 ms
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1936)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1002)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:984)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1.apply(RDD.scala:1127)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.treeAggregate(RDD.scala:1104)
	at org.apache.spark.api.java.JavaRDDLike$class.treeAggregate(JavaRDDLike.scala:438)
	at org.apache.spark.api.java.AbstractJavaRDDLike.treeAggregate(JavaRDDLike.scala:45)
	at org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.apply(BaseRecalibratorSparkFn.java:39)
	at org.broadinstitute.hellbender.tools.spark.BaseRecalibratorSpark.runTool(BaseRecalibratorSpark.java:159)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:387)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:30)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:153)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
	at org.broadinstitute.hellbender.Main.main(Main.java:277)
18/03/26 14:01:40 INFO ShutdownHookManager: Shutdown hook called
18/03/26 14:01:40 INFO ShutdownHookManager: Deleting directory /Shared/Bioinformatics/data/mchiment/bcbio_testbed/NA12878_exome_eval/work/bcbiotx/tmpRQGYVR/spark-a6602cea-cd89-4086-bf07-e5a2ec4b5815
' returned non-zero exit status 3

-----------
I'm running on SGE with a shared-mem parallel environment of 56 cores of a High Memory Node (256GB).  Number of threads = 28.  

System setup: 
resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 3G
    cores: 16
    jvm_opts: ["-Xms750m", "-Xmx3500m"]
  gatk:
    jvm_opts: ["-Xms500m", "-Xmx3500m"]
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
  qualimap:
    memory: 4g
  express:
    memory: 8g
  dexseq:
    memory: 10g
  macs2:
    memory: 8g
  seqcluster:
    memory: 8g

--------------
upload:
  dir: ../final
details:
  - files: [../input/NA12878_20180111000_S51_L002_R1_001.fastq.gz, ../input/NA12878_20180111000_S51_L002_R2_001.fastq.gz]
    description: NA12878-1
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      variantcaller: [freebayes, gatk-haplotype, samtools]
      recalibrate: gatk
      #realign: gatk
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: capture_regions/Exome-NGv3
      ensemble:
        numpass: 2

**Comment by chapmanb** [comment]
Michael;
Sorry about the issues. To confirm, are you running the latest development version of bcbio with the timeout increase and GATK 4.0.2.1 with the fix on the GATK side? I wanted to double check as one or both of those solved the problem with my local issues where I was able to replicate. Thanks for the help debugging.

**Comment by mchimenti** [comment]
Hi Brad.  No, I am running bcbio-stable (1.0.8) w/ GATK-4.0.1.2.  Do you expect these fixes will get pushed to stable?   Otherwise I can work with my sys-admin to create another bcbio install w/ the dev branch.  Thanks.

**Comment by chapmanb** [comment]
Michael;
We're hoping to have a new release with the fixes in the next week or so. In the short term you could update only GATK in your installation:
```
bcbio_conda install -y -c conda-forge -c bioconda gatk4
```
which will hopefully avoid the issue. Hope this helps.
