### ISSUE TITLE
Please check multiqc error in the latest dev

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#2261]
Hello, Brad!

Thanks for the great pipeline!

Upgraded to the latest dev because of the https://github.com/chapmanb/bcbio-nextgen/issues/2257,
and cannot pass multiqc step:

```
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/bin:$PATH &&  /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/bin/multiqc -f -l /hpf/largeprojects/ccmbio/naumenko/project_cheo/2018-02_N7/bcbio_fast/1223N/work/qc/multiqc/list_files.txt  -o /hpf/largeprojects/ccmbio/naumenko/project_cheo/2018-02_N7/bcbio_fast/1223N/work/bcbiotx/tmpKWyWri
[INFO   ]         multiqc : This is MultiQC v1.4
[INFO   ]         multiqc : Template    : default
Searching 122 files..
[INFO   ]           peddy : Found 6 reports
[INFO   ]           bcbio : Found 3 reports
[ERROR  ]         multiqc : Oops! The 'bcbio' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /hpf/largeprojects/ccmbio/naumenko/project_cheo/2018-02_N7/bcbio_fast/1223N/work/qc/multiqc/report/metrics/target_info.yaml
============================================================
Module bcbio raised an exception: Traceback (most recent call last):
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/bin/multiqc", line 427, in multiqc
    output = mod()
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/python2.7/site-packages/multiqc_bcbio/bcbio.py", line 111, in __init__
    if "coverage_avg_chart" in coverage_avg_plot:
TypeError: argument of type 'NoneType' is not iterable
============================================================
[INFO   ]        samtools : Found 3 stats reports
[INFO   ]        samtools : Found 3 idxstats reports
[INFO   ]        bcftools : Found 3 stats reports
[INFO   ]        qualimap : Found 3 BamQC reports
[INFO   ]          fastqc : Found 3 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : ../../bcbiotx/tmpKWyWri/multiqc_report.html
[INFO   ]         multiqc : Data        : ../../bcbiotx/tmpKWyWri/multiqc_data
[INFO   ]         multiqc : MultiQC complete
' returned non-zero exit status 1

```

target_info.yaml
```
coverage_bed_info: &id001 {bed: callable regions}
coverage_interval: regional
genome_info: {name: GRCh37, size: 3101804739}
variants_regions_info: *id001
```
Could you please check this?

Sergey

**Comment by naumenko-sa** [comment]
In the meanwhile running multiqc command from the command line and then rerunning bcbio_nextgen helps to finish the project.

**Comment by chapmanb** [comment]
Thanks much for this report and sorry about the issue. I pushed a fix that I hope will resolve this for you. You can either update to the latest development (`bcbio_nextgen.py upgrade -u development`) or just the multiqc bcbio package:
```
bcbio_conda install -c conda-forge -c bioconda multiqc-bcbio
```
Please let us know if you run into any other problems.
