### ISSUE TITLE
CNVkit

### ISSUE THREAD

**Issue by lemdcock** [chapmanb/bcbio-nextgen#2271]
Dear B. Chapman,

I was running BCBio to perform a structural variant calling using CNVkit and TitanCNA. However I ran into some troubles during the calculation of the antitarget coverage (CNVkit):

Calculating coverage: sample-1 antitarget
Traceback (most recent call last):
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 133, in variant2pipeline
    samples = run_parallel("calculate_sv_coverage", samples)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 295, in calculate_sv_coverage
    return svregions.calculate_sv_coverage(*args)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/regions.py", line 160, in calculate_sv_coverage
    out_target_file = _add_log2_depth(target_cov_genes, out_target_file, data)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/regions.py", line 178, in _add_log2_depth
    chrom, start, end, orig_name, depth, gene_name = parts
ValueError: need more than 5 values to unpack

I checked the corresponding antitarget file and it was indeed missing the gene_name column. Is there a way to resolve this issue? Or did I make a mistake in my configuration file? 

sampleConfig.yaml:

#!yaml
---
details:
  - analysis: variant2
    description: sample-1
    files:
      - sample-1-dedup-recal.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: false
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: tumor
  - analysis: variant2
    description: D1716647
    files:
      - sample-2-dedup-recal.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: false
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: normal
upload:
  dir: /home/lemdcock/output/

The input bam files had been deduplicated and recalibrated during a previous analysis.

Kind regards,
Laurenz

**Comment by chapmanb** [comment]
Laurenz;
Thanks for the report and apologies about the issue. The underlying problem appears to be that the `sv_regions: /home/lemdcock/RefSeqExomeAndPanels.bed` input file doesn't have any gene name annotations. The current CNVkit code assumed it did and uses this for adding gene names when present, rather than the default set of transcripts. I pushed a fix which will add empty gene names at this point, rather than erroring out. If you update to latest development (`bcbio_nextgen.py upgrade -u development`) and re-run your analysis it should pick up where it left off and hopefully finish cleanly for you. Thanks again for the report and please let us know if you run into any other issues.

**Comment by lemdcock** [comment]
B. Chapman,

Thank you for addressing this issue so quickly.

Kind regards,
Laurenz
