### ISSUE TITLE
Error after upgrading to 1.0.8: libsodium.so.23: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#2274]
I upgraded our bcbio installation to 1.0.8, however, I'm no longer able to start any runs, since it fails directly at the start after submission to the cluster with the following (and only the following) error message:

```
Traceback (most recent call last):
  File "/bcbio_ii2/local/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/bcbio_ii2/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
    fc_dir, run_info_yaml)
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 77, in _run_toplevel
    parallel = log.create_base_logger(config, parallel)
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/log/__init__.py", line 104, in create_base_logger
    from bcbio.log import logbook_zmqpush
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/log/logbook_zmqpush.py", line 12, in <module>
    import zmq
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/bcbio_ii2/local/share/bcbio/anaconda/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory
```

Any help is highly appreciated!

Thank you.

**Comment by leiendeckerlu** [comment]
Amazing! This did the job for me.

I highly appreciate the work you and the fellow contributors are doing here. 

Thanks a lot!

**Comment by mohSeSC** [comment]
Hi , even i upgraded the packages , the error still the same . 
-- OS : Linux mint .

**Comment by rohitpattnaik** [comment]
Thanks guys ... worked for me . was having an issue initializing spyder
... All good now

**Comment by prubbens** [comment]
Also had problems initializing spyder. 

Just running `conda update libsodium` did the trick for me.

**Comment by SHAHIR123** [comment]
I was facing problem to open Jupyter notebook in ubuntu.
Below solution worked for me
conda install -c conda-forge libsodium

**Comment by Vish-was** [comment]
> I was facing problem to open Jupyter notebook in ubuntu.
> Below solution worked for me
> conda install -c conda-forge libsodium

Still the same: 

```
rake db:create
rake aborted!
LoadError: Could not open library 'sodium': sodium: cannot open shared object file: No such file or directory.
Could not open library 'libsodium.so': libsodium.so: cannot open shared object file: No such file or directory
```

**Comment by roryk** [comment]
Hi @Vish-was,

Sorry, this is a repository totally unrelated to jupyter, I guess we just end up high on the google results when you search for this error.
