### ISSUE TITLE
CNVkit segmetrics error

### ISSUE THREAD

**Issue by lemdcock** [chapmanb/bcbio-nextgen#2278]
Dear B. Chapman, 

Unfortunately I ran into some trouble again running CNVkit. During the calculation of the segmetrics, bcbio gives me a NoneType error. Could this be due to the missing gene names in my structural variants file? 

Complete error message:
 CNVkit segmetrics
[2018-02-17T04:47Z] Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.0a0', 'bcbio_nextgen.py')
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
[2018-02-17T04:47Z]   File "/home/lemdcock/local/share/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
    exec(code, namespace, namespace)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0a0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0a0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 176, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 125, in run
    for xs in to_process.values()))
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
[2018-02-17T04:47Z]     args.func(args)
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
[2018-02-17T04:47Z]   File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1259, in _cmd_segmetrics
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
[2018-02-17T04:47Z]     args.interval_stats, args.alpha, args.bootstrap)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 220, in detect_sv
    return structural.detect_sv(*args)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 144, in detect_sv
    for svdata in caller_fn(items):
[2018-02-17T04:47Z]   File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/segmetrics.py", line 42, in do_segmetrics
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 29, in run
    return _cnvkit_by_type(items, background)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 41, in _cnvkit_by_type
    return _run_cnvkit_cancer(items, background)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 97, in _run_cnvkit_cancer
    tumor_data = _associate_cnvkit_out(ckouts, [paired.tumor_data])
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 56, in _associate_cnvkit_out
    ckout = _add_segmetrics_to_output(ckout, data)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 384, in _add_segmetrics_to_output
    do.run(cmd, "CNVkit segmetrics")
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
[2018-02-17T04:47Z]     for statname in location_stats:
    _do_run(cmd, checks, log_stdout)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError[2018-02-17T04:47Z] TypeError: 'NoneType' object is not iterable
: Command '/home/lemdcock/local/share/bcbio/anaconda/bin/cnvkit.py segmetrics --iqr --ci --pi -s /home/lemdcock/CNV_LOH/work/structural/sample-1/cnvkit/raw/sample-1.cns -o /home/lemdcock/CNV_LOH/work/structural/sample-1/cnvkit/raw/tx/tmpYmLQN3/sample-1-segmetrics.txt /home/lemdcock/CNV_LOH/work/structural/sample-1/cnvkit/raw/sample-1.cns
Traceback (most recent call last):
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1259, in _cmd_segmetrics
    args.interval_stats, args.alpha, args.bootstrap)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/segmetrics.py", line 42, in do_segmetrics
    for statname in location_stats:
TypeError: 'NoneType' object is not iterable
' returned non-zero exit status 1
[2018-02-17T04:47Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command '/home/lemdcock/local/share/bcbio/anaconda/bin/cnvkit.py segmetrics --iqr --ci --pi -s /home/lemdcock/CNV_LOH/work/structural/sample-1/cnvkit/raw/sample-1.cns -o /home/lemdcock/CNV_LOH/work/structural/sample-1/cnvkit/raw/tx/tmpYmLQN3/sample-1-segmetrics.txt /home/lemdcock/CNV_LOH/work/structural/sample-1/cnvkit/raw/sample-1.cns
Traceback (most recent call last):
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1259, in _cmd_segmetrics
    args.interval_stats, args.alpha, args.bootstrap)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/segmetrics.py", line 42, in do_segmetrics
    for statname in location_stats:
TypeError: 'NoneType' object is not iterable
' returned non-zero exit status 1

sample config file:
#!yaml
---
details:
  - analysis: variant2
    description: sample-1
    files:
      - sample-1-dedup-recal.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: false
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: tumor
  - analysis: variant2
    description: sample-2
    files:
      - sample-2-dedup-recal.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: false
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: normal
upload:
  dir: /home/lemdcock/output/

Kind regards, 
Laurenz

**Comment by chapmanb** [comment]
Laurenz;
Sorry about the issue. Could you try an upgrade with these commands (two development upgrades, then a library fix):
```
bcbio_nextgen.py upgrade -u development
bcbio_nextgen.py upgrade -u development
bcbio_conda install -y -c conda-forge libsodium
```
The introduction of htslib 1.7 in bioconda caused bcbio installations to revert to older versions, which I think is the underlying problem here. This is resolved now for updates but unfortunately you got caught in an upgrade during the time when it was an issue.

After you update you should be able to run in place and it'll work cleanly, please feel free to reopen this if not and we can debug further.

**Comment by lemdcock** [comment]
B. Chapman,

Thank you for the quick reply.

Kind regards,
Laurenz
