### ISSUE TITLE
peddy causing paired tumour/normal WGS variant calling pipeline crash

### ISSUE THREAD

**Issue by ameynert** [chapmanb/bcbio-nextgen#2283]
Command log:
```
[2018-02-23T11:13Z] /gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/bin/peddy -p 4 --plot --prefix /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/bcbiotx/tmpv4pRGT/WW00269 /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/mutect2/WW00269-vepeffects-annotated-ploidyfix.vcf.gz /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/mutect2/WW00269-vepeffects-annotated-ploidyfix.ped 2> /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/bcbiotx/tmpv4pRGT/run-stderr.log
```

Output:
```
[2018-02-23T11:13Z] Running peddy on /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/mutect2/WW00269-vepeffects-annotated-ploidyfix.vcf.gz against /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.W
W00269/mutect2/WW00269-vepeffects-annotated-ploidyfix.ped.
[2018-02-23T11:13Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/bin/peddy -p 4 --plot --prefix /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/bcbiotx/tmpv4pRGT/WW00269 /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/mutect2/WW00269-vepeffects-annotated-ploidyfix.vcf.gz /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/mutect2/WW00269-vepeffects-annotated-ploidyfix.ped 2> /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/bcbiotx/tmpv4pRGT/run-stderr.log
' returned non-zero exit status 1
[2018-02-23T11:13Z] 2018-02-23 11:13:32 node2e22.ecdf.ed.ac.uk peddy.cli[92700] INFO Running Peddy version 0.3.1
2018-02-23 11:13:32 node2e22.ecdf.ed.ac.uk peddy.cli[92700] INFO ESC[1;31mped_checkESC[0m
peddy: no hets found for sample WW00269b2

/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/peddy/peddy.py:1033: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['rel_difference'][df['rel_difference'] == 0] = 0.001
2018-02-23 11:13:46 node2e22.ecdf.ed.ac.uk peddy.peddy[92700] INFO plotting
2018-02-23 11:13:46 node2e22.ecdf.ed.ac.uk peddy.cli[92700] INFO ran in 14.0 seconds
2018-02-23 11:13:46 node2e22.ecdf.ed.ac.uk peddy.cli[92700] INFO ESC[1;31mhet_checkESC[0m
2018-02-23 11:13:52 node2e22.ecdf.ed.ac.uk peddy.pca[92700] INFO loaded and subsetted thousand-genomes genotypes (shape: (2504, 2)) in 0.8 seconds
/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)
2018-02-23 11:13:53 node2e22.ecdf.ed.ac.uk peddy.pca[92700] INFO ran randomized PCA on thousand-genomes samples at 2 sites in 1.5 seconds
Traceback (most recent call last):
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/bin/peddy", line 11, in <module>
    load_entry_point('peddy==0.3.1', 'console_scripts', 'peddy')()
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 204, in peddy
    in ("ped_check", "het_check", "sex_check")]):
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 43, in run
    prefix=prefix, **kwargs)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/peddy/peddy.py", line 863, in het_check
    pca_df, background_pca_df = pca(pca_plot, gt_types, sites)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/peddy/pca.py", line 86, in pca
    'PC3': tf[:, 2],
IndexError: index 2 is out of bounds for axis 1 with size 2

Traceback (most recent call last):
  File "/exports/igmm/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/tools/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/exports/igmm/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 184, in variant2pipeline
    samples = peddy.run_peddy_parallel(samples, run_parallel)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 29, in run_peddy_parallel
    samples = parallel_fn("run_peddy", [[x] for x in to_run])
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 22, in run_peddy
    return peddy.run_peddy(*args)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 64, in run_peddy
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /gpfs/igmmfs01/eddie/bioinfsvice/ameynert/software/bcbio-1.0.7/anaconda/bin/peddy -p 4 --plot --prefix /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/bcbiotx/tmpv4pRGT/WW00269 /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/mutect2/WW00269-vepeffects-annotated-ploidyfix.vcf.gz /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/mutect2/WW00269-vepeffects-annotated-ploidyfix.ped 2> /gpfs/igmmfs01/eddie/HGS-OvarianCancerA-SGP-WGS/work/2018-01-15.WW00269/bcbiotx/tmpv4pRGT/run-stderr.log
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Alison -- sorry about the issue. We have a fix for this but unfortunately it's not in the 1.0.7 version:

https://github.com/chapmanb/bcbio-nextgen/commit/96b35f1231e911cbf6002a416738d111a5b22636#diff-39b27a90b1c36de795c6dbdf94528855

If you're able to upgrade to the latest stable or development it will correctly catch and avoid failing out on these. Thanks much for the report and sorry again about the problem.

**Comment by ameynert** [comment]
This has re-occurred in bcbio-1.0.9.

**Comment by chapmanb** [comment]
Thanks Alison for the report, following up in #2400
