### ISSUE TITLE
$TMPDIR full

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2286]
Hi Brad, I have the following issues. My Cluster user /tmp/jobid as $TMPDIR (already not clever) on top of it /tmp is only 49GB per node .... really bad (just to get an idea the cluster have 5000CPU...) 

I have poit my concerns to the locals sysadmin, but response is low. 

Would be possible to reset $TMPDIR if bcbio see that is too small or almost full?
I am thinking to the bcbiotx/tmp. I know it will stress the network, but with the current setting even a simply STAR alignment or variant call  get kill. 

Thanks a lot for your ideas!
Alessandro

**Comment by apastore** [comment]
This is the error  log I get In case you what to have a look

[2018-02-24T12:58Z] lt09: Genotyping paired variants with FreeBayes
[2018-02-24T12:58Z] lt09: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 375, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 350, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 94, in run_freebayes
    ref_file, assoc_files, region, out_file)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 167, in _run_freebayes_paired
    opts, no_target_regions = _freebayes_options_from_config(items, config, out_file, region)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 51, in _freebayes_options_from_config
    target = shared.subset_variant_regions(variant_regions, region, out_file, items)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 211, in wrapper
    region_bed = f(variant_regions, region, out_file, items, do_merge, data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 252, in subset_variant_regions
    dd.get_ref_file(data), do_merge=do_merge)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 134, in _subset_bed_by_region
    orig_bed.intersect(region_bed, nonamecheck=True).saveas().sort(**sort_kwargs).saveas().\
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 806, in decorated
    result = method(self, *args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2996, in saveas
    compressed=compressed)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1242, in _collapse
    out_.writelines(in_)
IOError: [Errno 28] No space left on device
[2018-02-24T12:58Z] lt09: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 375, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 350, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 94, in run_freebayes
    ref_file, assoc_files, region, out_file)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 167, in _run_freebayes_paired
    opts, no_target_regions = _freebayes_options_from_config(items, config, out_file, region)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 51, in _freebayes_options_from_config
    target = shared.subset_variant_regions(variant_regions, region, out_file, items)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 211, in wrapper
    region_bed = f(variant_regions, region, out_file, items, do_merge, data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 252, in subset_variant_regions
    dd.get_ref_file(data), do_merge=do_merge)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 131, in _subset_bed_by_region
    from_string=True)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 438, in __init__
    fout.close()
IOError: [Errno 28] No space left on device
[2018-02-24T12:58Z] lt09: Unexpected error

**Comment by apastore** [comment]
This Is what I get from STAR. Thanks a lot 


[2018-02-24T20:12Z] lt11: Configuring 170 jobs to run, using 6 cores each with 48.1g of memory reserved for each job
2018-02-24 15:13:20.528 [IPClusterStart] Using existing profile dir: u'/lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython'
2018-02-24 15:13:20.529 [IPClusterStart] Searching path [u'/lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work', u'/lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython', '/home/pastore/data/bcbio/anaconda/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2018-02-24 15:13:20.530 [IPClusterStart] Attempting to load config file: ipython_config.py
2018-02-24 15:13:20.530 [IPClusterStart] Looking for ipython_config in /etc/ipython
2018-02-24 15:13:20.530 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2018-02-24 15:13:20.530 [IPClusterStart] Looking for ipython_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2018-02-24 15:13:20.532 [IPClusterStart] Looking for ipython_config in /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython
2018-02-24 15:13:20.639 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython/ipython_config.py
2018-02-24 15:13:20.639 [IPClusterStart] Looking for ipython_config in /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work
2018-02-24 15:13:20.641 [IPClusterStart] Attempting to load config file: ipcluster_13f0e0e6_efc6_4fcd_a0cf_3a35145504f3_config.py
2018-02-24 15:13:20.641 [IPClusterStart] Looking for ipcontroller_config in /etc/ipython
2018-02-24 15:13:20.641 [IPClusterStart] Looking for ipcontroller_config in /usr/local/etc/ipython
2018-02-24 15:13:20.642 [IPClusterStart] Looking for ipcontroller_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2018-02-24 15:13:20.642 [IPClusterStart] Looking for ipcontroller_config in /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython
2018-02-24 15:13:20.660 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython/ipcontroller_config.py
2018-02-24 15:13:20.660 [IPClusterStart] Looking for ipcontroller_config in /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work
2018-02-24 15:13:20.662 [IPClusterStart] Attempting to load config file: ipcluster_13f0e0e6_efc6_4fcd_a0cf_3a35145504f3_config.py
2018-02-24 15:13:20.662 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2018-02-24 15:13:20.662 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2018-02-24 15:13:20.662 [IPClusterStart] Looking for ipengine_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2018-02-24 15:13:20.662 [IPClusterStart] Looking for ipengine_config in /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython
2018-02-24 15:13:20.684 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython/ipengine_config.py
2018-02-24 15:13:20.685 [IPClusterStart] Looking for ipengine_config in /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work
2018-02-24 15:13:20.686 [IPClusterStart] Attempting to load config file: ipcluster_13f0e0e6_efc6_4fcd_a0cf_3a35145504f3_config.py
2018-02-24 15:13:20.686 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2018-02-24 15:13:20.687 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2018-02-24 15:13:20.687 [IPClusterStart] Looking for ipcluster_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2018-02-24 15:13:20.687 [IPClusterStart] Looking for ipcluster_config in /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython
2018-02-24 15:13:20.721 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/log/ipython/ipcluster_config.py
2018-02-24 15:13:20.722 [IPClusterStart] Looking for ipcluster_config in /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work
[2018-02-24T20:14Z] lt11: Timing: alignment
[2018-02-24T20:14Z] lt11: ipython: disambiguate_split
[2018-02-24T20:14Z] lt11: ipython: process_alignment
[2018-02-24T20:14Z] ls16: Aligning lane CNS11_PDX_untreated with star aligner
[2018-02-24T20:14Z] ls16: Running STAR aligner on /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/input/merged/CNS11_PDX_untreated_R1.fastq.gz and /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Hsapiens/hg19/star/
......

[2018-02-24T20:34Z] ls07: Running STAR aligner on /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/input/merged/TMD-08_IGO_05667_R1.fastq.gz and /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Hsapiens/hg19/star/
[2018-02-24T20:36Z] ls17: Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 86, in _do_run
    line = s.stdout.readline()
KeyboardInterrupt
[2018-02-24T20:36Z] ls17: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 230, in process_alignment
    return ipython.zip_args(apply(sample.process_alignment, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 123, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 77, in align_to_sort_bam
    names, align_dir, data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 146, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/star.py", line 92, in align
    do.run(cmd.format(**locals()), run_message, None)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 86, in _do_run
    line = s.stdout.readline()
KeyboardInterrupt
[2018-02-24T20:36Z] ls08: Aligning lane TMD-08_IGO_05667 with star aligner
[2018-02-24T20:36Z] ls08: Running STAR aligner on /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/input/merged/TMD-08_IGO_05667_R1.fastq.gz and /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Mmusculus/mm10/star/
[2018-02-24T20:36Z] lt12: Aligning lane CNS10_PDX_untreated with star aligner
[2018-02-24T20:36Z] lt12: Running STAR aligner on /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/input/merged/CNS10_PDX_untreated_R1.fastq.gz and /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Mmusculus/mm10/star/
[2018-02-24T20:37Z] ls16: gzip: stdout: Broken pipe
[2018-02-24T20:37Z] ls16: gzip: stdout: Broken pipe
[2018-02-24T20:37Z] ls16: /bin/bash: line 1: 62477 Bus error               (core dumped) /lila/data/abdelwao-lab/pastorea/bcbio/galaxy/../anaconda/bin/STAR --genomeDir /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Hsapiens/hg19/star/ --readFilesIn <(gunzip -c /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/input/merged/CNS11_PDX_untreated_R1.fastq.gz) <(gunzip -c /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/input/merged/CNS11_PDX_untreated_R2.fastq.gz) --runThreadN 6 --outFileNamePrefix /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/bcbiotx/tmp4S4IYB/hg19/CNS11_PDX_untreated --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd BAM_Unsorted --limitOutSJcollapsed 2000000 --outSAMtype BAM Unsorted --outSAMmapqUnique 60 --outSAMunmapped Within --outSAMattributes NH HI NM MD AS --sjdbGTFfile /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf --sjdbOverhang 49 --outSAMattrRGline ID:CNS11_PDX_untreated PL:illumina PU:CNS11_PDX_untreated SM:CNS11_PDX_untreated --outSAMstrandField intronMotif --quantMode TranscriptomeSAM
[2018-02-24T20:37Z] ls16: Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /lila/data/abdelwao-lab/pastorea/bcbio/galaxy/../anaconda/bin/STAR --genomeDir /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Hsapiens/hg19/star/ --readFilesIn <(gunzip -c /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/input/merged/CNS11_PDX_untreated_R1.fastq.gz) <(gunzip -c /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/input/merged/CNS11_PDX_untreated_R2.fastq.gz) --runThreadN 6 --outFileNamePrefix /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/bcbiotx/tmp4S4IYB/hg19/CNS11_PDX_untreated --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd BAM_Unsorted  --limitOutSJcollapsed 2000000 --outSAMtype BAM Unsorted --outSAMmapqUnique 60 --outSAMunmapped Within --outSAMattributes NH HI NM MD AS  --sjdbGTFfile /lila/data/abdelwao-lab/pastorea/bcbio/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf  --sjdbOverhang 49  --outSAMattrRGline ID:CNS11_PDX_untreated PL:illumina PU:CNS11_PDX_untreated SM:CNS11_PDX_untreated  --outSAMstrandField intronMotif  --quantMode TranscriptomeSAM  | /lila/data/abdelwao-lab/pastorea/bcbio/galaxy/../anaconda/bin/samtools sort -@ 6 -m 4G  -T /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/bcbiotx/tmp4S4IYB/hg19/CNS11_PDX_untreated_star/CNS11_PDX_untreated-sorttmp -o /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/bcbiotx/tmp4S4IYB/hg19/CNS11_PDX_untreated_star/CNS11_PDX_untreated.bam /dev/stdin > /lila/data/abdelwao-lab/pastorea/Project/christian/5667_AZ/5667_AZ/work/bcbiotx/tmp4S4IYB/hg19/CNS11_PDX_untreated_star/CNS11_PDX_untreated.bam 
gzip: stdout: Broken pipe
gzip: stdout: Broken pipe

**Comment by apastore** [comment]
I have fount the tmp  in the resource section of bcbio_system.yaml. 
It seems to write all tmp files there. I will report if something still goes to /tmp. 

Thanks

**Comment by chapmanb** [comment]
Alessandro -- thanks for all the details and for following up with your solution. That's exactly what I was going to suggest so hope it resolves your issues. Please let us know if you still have any problems and we can re-open this discussion to fix.

**Comment by apastore** [comment]
Hi @chapmanb,
I have configure  in bcbio_system.yaml and as you expect it runs fine, except pybedtools its still writing in /tmp instead of  /scratch/pastore

bcbio_system.yaml : 
tmp:
    dir: /scratch/pastore


ipyparallel.error.CompositeError: one or more exceptions from call to method: variantcall_sample
[47:apply]: OSError: [Errno 28] No space left on device: '/tmp/1872327_13.tmpdir/pybedtools.Z2SlVS.tmp'
[29:apply]: OSError: [Errno 28] No space left on device: '/tmp/1872327_4.tmpdir/pybedtools.DeEZFo.tmp'
[18:apply]: OSError: [Errno 28] No space left on device: '/tmp/1872327_10.tmpdir/pybedtools.cAuxmy.tmp'
[49:apply]: OSError: [Errno 28] No space left on device: '/tmp/1872327_12.tmpdir/pybedtools.b7zSsT.tmp'

**Comment by chapmanb** [comment]
Following up on this in #2294. We do get messages from closed threads and happy to tackle them here so no need to double post issues.

**Comment by apastore** [comment]
Thanks a lot and sorry for the double post!
