### ISSUE TITLE
bcbio crashes on lsf

### ISSUE THREAD

**Issue by alongalor** [chapmanb/bcbio-nextgen#2292]
Upon running:

```
/n/data1/hms/dbmi/park/alon/software/bcbio/bin/bcbio_nextgen.py /n/data1/hms/dbmi/park/DATA/BSMCommonExperiment/ReferenceTissueProject/.Pipeline/PreProcessing/PreProcessing/config/PreProcessing.yaml -t ipython -n 256 -s lsf -q park_long -r t=4-00:00 --timeout 6000
```

I get the following error in `ipcluster-2c58584b-4eb2-449e-96ce-eb1d78967e6b-33791.log`:

```
2018-02-26 21:35:51.280 [IPClusterStart] WARNING | Config option `mem` not recognized by `BcbioLSFControllerLauncher`.
2018-02-26 21:35:51.290 [IPClusterStart] Starting ipcluster with [daemon=True]
2018-02-26 21:35:51.365 [IPClusterStart] Creating pid file: /n/data1/hms/dbmi/park/DATA/BSMCommonExperiment/ReferenceTissueProject/.Pipeline/PreProcessing/PreProcessing_GATK3/work/log/ipython/pid/ipcluster-2c58584b-4eb2-449e-96ce-eb1d78967e6b.pid
2018-02-26 21:35:51.370 [IPClusterStart] Starting Controller with cluster_helper.cluster.BcbioLSFControllerLauncher
2018-02-26 21:35:51.371 [IPClusterStart] adding queue settings to batch script
2018-02-26 21:35:51.371 [IPClusterStart] adding job array settings to batch script
2018-02-26 21:35:51.372 [IPClusterStart] Writing batch script: ./lsf_controller0e6a4682-fb1d-4950-8b30-fd772a521d7c
2018-02-26 21:35:51.385 [IPClusterStart] Starting BcbioLSFControllerLauncher: bsub<"./lsf_controller0e6a4682-fb1d-4950-8b30-fd772a521d7c"
2018-02-26 21:35:51.457 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/n/data1/hms/dbmi/park/alon/software/bcbio/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 537, in start_controller
    self.controller_launcher.start()
  File "/n/data1/hms/dbmi/park/alon/software/bcbio/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 226, in start
    return super(BcbioLSFControllerLauncher, self).start()
  File "/n/data1/hms/dbmi/park/alon/software/bcbio/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1421, in start
    return super(LSFControllerLauncher, self).start(1)
  File "/n/data1/hms/dbmi/park/alon/software/bcbio/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1402, in start
    job_id = self.parse_job_id(output)
  File "/n/data1/hms/dbmi/park/alon/software/bcbio/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1111, in parse_job_id
    raise LauncherError("Job id couldn't be determined: %s" % output)
LauncherError: Job id couldn't be determined: 
```

Also attaching log files below:

[bcbio-nextgen-debug.log.txt](https://github.com/chapmanb/bcbio-nextgen/files/1763173/bcbio-nextgen-debug.log.txt)
[bcbio-nextgen.log.txt](https://github.com/chapmanb/bcbio-nextgen/files/1763174/bcbio-nextgen.log.txt)
command log is empty.

Any help here would be much appreciated.

Thanks a lot!

Alon

**Comment by chapmanb** [comment]
Alon;
Sorry about the issues and thanks for the report. IPython swallows the useful error messages here so it's hard to tell what the LSF setup does not like about the submission script if you manually run:
```
bsub < ./lsf_controller0e6a4682-fb1d-4950-8b30-fd772a521d7c
```
Does that provide a useful error message about the problem it's finding? Hope this helps identify the underlying issue.

**Comment by alongalor** [comment]
Thanks for your help Brad! Unfortunately upon running `bsub < ./lsf_controller552809f9-553e-46fc-83b8-ced31c2635e3` I get the following error: `4-00:00: Bad time specification. Job not submitted.` In the file it specifies time as follows: `#BSUB -t 4-00:00`. I usually specify time when submitting jobs to LSF as follows: `#BSUB -W 96:00` I made this edit in this file and the job was submitted. Currently waiting for this job to run and can let you know what it returns when it does!

**Comment by chapmanb** [comment]
Alon;
Thanks for helping debug, this helps me spot the issue. The submission script has:
```
-r t=4-00:00
```
which I believe got copied over from earlier SLURM runs. This SLURM specific resource specification now gets put into the LSF batch script and gives you the wrong submission parameters here. If you swap to:
```
-r W=96:00
```
bcbio will put this into your batch scripts instead. Alternatively you can just leave out the time specification if it's not requires for your LSF setup. Hope this helps.

**Comment by alongalor** [comment]
Thanks a lot for your help Brad! Silly mistake on my end! Really appreciate it!
