### ISSUE TITLE
sourceforge snpeff v4_3_1 migrate to  v4_3

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2303]
I have seen that snpeff v4_3_1 is dowloaded But only v4_3 is present on sourceforge. 

Thanks!

--2018-03-04 10:04:18--  http://downloads.sourceforge.net/project/snpeff/databases/v4_3_1/snpEff_v4_3_1_GRCh37.75.zip
Resolving downloads.sourceforge.net... 216.105.38.13
Connecting to downloads.sourceforge.net|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-04 10:04:18 ERROR 404: Not Found.

Traceback (most recent call last):
  File "/lila/home/pastore/data/bcbio_tool/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 98, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 308, in upgrade_bcbio_data
    _upgrade_snpeff_data(s["fabricrc_overrides"]["galaxy_home"], args, remotes)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 373, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "--no-check-certificate", "-c", "-O", dl_file, dl_url])
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', '-c', '-O', 'snpEff_v4_3_1_GRCh37.75.zip', 'http://downloads.sourceforge.net/project/snpeff/databases/v4_3_1/snpEff_v4_3_1_GRCh37.75.zip']' returned non-zero exit status 8

-bash-4.2$ wget http://downloads.sourceforge.net/project/snpeff/databases/v4_3_1/snpEff_v4_3_1_GRCh37.75.zip 
--2018-03-04 10:08:32--  http://downloads.sourceforge.net/project/snpeff/databases/v4_3_1/snpEff_v4_3_1_GRCh37.75.zip
Resolving downloads.sourceforge.net... 216.105.38.13
Connecting to downloads.sourceforge.net|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-04 10:08:33 ERROR 404: Not Found.

-bash-4.2$ wget http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh37.75.zip 
--2018-03-04 10:09:48--  http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh37.75.zip
Resolving downloads.sourceforge.net... 216.105.38.13
Connecting to downloads.sourceforge.net|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://versaweb.dl.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh37.75.zip [following]
--2018-03-04 10:09:48--  https://versaweb.dl.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh37.75.zip
Resolving versaweb.dl.sourceforge.net... 104.238.205.251
Connecting to versaweb.dl.sourceforge.net|104.238.205.251|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 694058191 (662M) [application/octet-stream]
Saving to: ‘snpEff_v4_3_GRCh37.75.zip’

snpEff_v4_3_GRCh37.75.zip                            1%[>                                                                                                             ]  11.27M   817KB/s    eta 13m 24s

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. The latest snpEff is reporting 4.3.1 for the version although we needed 4.3 for the database download lookup. I pushed a fix to the latest development version to resolve this if you do:
```
bcbio_nextgen.py upgrade -u development
```
prior to running your data install command. Thank you again.

**Comment by apastore** [comment]
Perfect! Thanks!

**Comment by apastore** [comment]
I have update with 

`bcbio_nextgen.py upgrade -u development  --tools --data`

but still snpeff get deleted are replace by the v4_3_1. my only fix is to 
manually modify tmpbcbio-install/cloudbiolinux/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml

```
ls -latr data/bcbio/genomes/Hsapiens/GRCh37/snpeff/
total 0
drwxr-sr-x  2 pastore abdelwao-lab 4096 Jan 10 17:36 transcripts
drwxr-sr-x 21 pastore abdelwao-lab 4096 Feb 27 20:54 ..
-rw-r--r--  1 pastore abdelwao-lab    0 Mar  5 09:08 snpEff_v4_3_1_GRCh37.75.zip
drwxr-sr-x  3 pastore abdelwao-lab 4096 Mar  5 09:08 .
```
Thanks a lot!

**Comment by chapmanb** [comment]
Sorry for the continued problems. Could you try running two separate updates:
```
bcbio_nextgen.py upgrade -u development --tools
bcbio_nextgen.py upgrade --data
```
The snpEff fix requires the development code installed and will need a separate process to make that available. Hope this resolves the issue for you.

**Comment by apastore** [comment]
Thanks I will try. at the moment I can not connect 

```
INFO: Moving on to next genome prep method after trying s3
Failure to retrieve remote file: https://s3.amazonaws.com/biodata/genomes/mm10-twobit.tar.xz
INFO: Moving on to next genome prep method after trying s3
Failure to retrieve remote file: https://s3.amazonaws.com/biodata/genomes/mm10-twobit.tar.xz
INFO: Preparing genome mm10 with index twobit
INFO: Preparing genome mm10 with index twobit
Traceback (most recent call last):
  File "/lila/home/pastore/data/bcbio_tool/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 98, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 307, in upgrade_bcbio_data
    remotes["genome_resources"])
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 328, in _upgrade_genome_resources
    r = requests.get(remote_url, verify=False)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /chapmanb/bcbio-nextgen/master/config/genomes/GRCh37-resources.yaml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9be944c250>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```
