### ISSUE TITLE
CNVkit error during conversion of cnr to bed format

### ISSUE THREAD

**Issue by lemdcock** [chapmanb/bcbio-nextgen#2310]
Dear B. Chapman, 

I had also tried to run CNVkit and TitanCNA using your fix. However, I also ran into trouble using this option, namely during the conversion of cnr to bed format. I'll include the error output and my input sample yaml file as extra information.

Could this again be related to a missing value in one of my input files, like the gene name or is something else entirely? 

Kind regards and my apologies for the many issues,
Laurenz

Error output:
```
[2018-03-02T17:05Z] Converting cnr to bed format
Traceback (most recent call last):
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 174, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 177, in run
    for xs in to_process.values()))
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 311, in detect_sv
    return structural.detect_sv(*args)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 197, in detect_sv
    for svdata in caller_fn(items):
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 28, in run
    het_file = _titan_het_file(heterogeneity.get_variants(paired.tumor_data), work_dir, paired)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 127, in _titan_het_file
    work_dir, paired, OutWriter)
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 132, in prep_vrn_file
    out_file = os.path.join(work_dir, "%s-%s-prep.csv" % (utils.splitext_plus(os.path.basename(in_file))[0],
  File "/home/lemdcock/local/share/bcbio/anaconda/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

Sample configuration file:
```
#!yaml
---
details:
  - analysis: variant2
    description: sample-1
    files:
      - sample-1.bam
    vrn_files: /home/lemdcock/output/batch1-mutect2-annotated-decomposed.vcf.gz
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      aligner: false
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: false
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: tumor
  - analysis: variant2
    description: sample-2
    files:
      - sample-2.bam
    genome_build: hg38
    algorithm:
      platform: illumina
      coverage_interval: regional
      aligner: false
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: false
      indelcaller: false
      svcaller: [cnvkit, titancna]
      variant_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      sv_regions: /home/lemdcock/RefSeqExomeAndPanels_20171003.bed
      effects: false
      tools_off: gatk4
    metadata:
      batch: CNV_LOH
      phenotype: normal
upload:
  dir: /home/lemdcock/CNV_LOH/output/
```

**Comment by chapmanb** [comment]
Laurenz;
Thanks for the report. The underlying problem here is that the input VCF file has a typo: you should change from `vrn_files` to `vrn_file` (avoid the extra s on the end). This will allow us to feed the pre-called VCF into TitanCNA for heterogeneity analysis.

I've checked in an improvement to the bcbio YAML linting which should hopefully catch these types of typos up front rather than providing a confusing error downstream. Hope this helps get your analysis run.
