### ISSUE TITLE
indelcaller error

### ISSUE THREAD

**Issue by michaelxu2014** [chapmanb/bcbio-nextgen#603]
Hi,

I am trying to add indelcaller to my yaml file, but I got the error message,

Traceback (most recent call last):
  File "/bcbio/bin/bcbio_nextgen.py", line 216, in <module>
[2014-09-22 19:00] Checking sample YAML configuration: /home/WGSData/bcbio_sample.yaml
    main(**kwargs)
  File "/bcbio/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 35, in run_main
    fc_dir, run_info_yaml)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 73, in _run_toplevel
    samples = run_info.organize(dirs, config, run_info_yaml)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 34, in organize
    run_details = _run_info_from_yaml(dirs["flowcell"], run_info_yaml, config)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 415, in _run_info_from_ya
ml
    _check_sample_config(run_details, run_info_yaml)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 304, in _check_sample_con
fig
    [_check_algorithm_keys(x) for x in items]
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 196, in _check_algorithm_
keys
    % (problem_keys, url))
ValueError: Unexpected configuration keyword in 'algorithm' section: ['indelcaller']
See configuration documentation for supported options:
https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#algorithm-parameters

I want to run mutect only for SNP calling and other indel callers pind and sid for indel calling. I am not sure if I added indelcaller to wrong place in my yaml file. Please take a look and thanks a lot! 
 
![screen shot 2014-09-22 at 12 23 11 pm](https://cloud.githubusercontent.com/assets/1004430/4362595/136cd92c-428e-11e4-8fef-4e70b366fd3b.png)

**Comment by roryk** [comment]
Hi @michaelxu2014, closing this out because it's pretty stale and the issue might have resolved itself by now. Feel free to reopen if you're still having the problem. Thanks!
