### ISSUE TITLE
error for gene fusion calling using bcbio

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#625]
Hi Brad,

I am using bcbio-nextgen to call gene fusion based on RNA-seq data, my yaml is

fc_date: '2014-09-24'
fc_name: EC_RS
upload:
  dir: ../final
details:
  - files: [ /newdata4/RS/EC_RS/input/ECT100_R1.fq.gz, /newdata4/RS/EC_RS/input/ECT100_R2.fq.gz ]
    description: 'EC_Tumor'
    genome_build: GRCh37
    analysis: RNA-seq
    algorithm:
      aligner: star
      quality_format: Standard
      trim_reads: read_through
      adapters: [truseq, polya]
      strandedness: unstranded 
      fusion_mode: true
  - files: [ /newdata4/RS/EC_RS/input/ECN99_R1.fq.gz, /newdata4/RS/EC_RS/input/ECN99_R2.fq.gz ]
    description: 'EC_Normal'
    genome_build: GRCh37
    analysis: RNA-seq
    algorithm:
      aligner: star
      quality_format: Standard
      trim_reads: read_through
      adapters: [truseq, polya]
      strandedness: unstranded 
      fusion_mode: true

The error message is

[2014-10-02 13:15] Timing: alignment
[2014-10-02 13:15] multiprocessing: process_alignment
[2014-10-02 13:15] Aligning lane 1_2014-09-24_EC_RS with star aligner
[2014-10-02 13:15] Running STAR aligner on /newdata4/RS/EC_RS/work/trimmed/ECT100_R1.trimmed.fq.gz and .
[2014-10-02 13:15] 
[2014-10-02 13:15] EXITING: FATAL INPUT ERROR: empty value for paramter "genomeDir" in input "Command-Line"
[2014-10-02 13:15] SOLUTION: use non-empty value for this parameter
[2014-10-02 13:15] 
[2014-10-02 13:15] Oct 02 13:15:44 ...... FATAL ERROR, exiting
[2014-10-02 13:15] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 20, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 93, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/bin/STAR --genomeDir  --readFilesIn /newdata4/RS/EC_RS/work/trimmed/ECT100_R1.trimmed.fq.gz /newdata4/RS/EC_RS/work/trimmed/ECT100_R2.trimmed.fq.gz --runThreadN 30 --outFileNamePrefix /newdata4/RS/EC_RS/work/align/EC_Tumor/1_2014-09-24_EC_RS --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd SAM --outSAMunmapped Within --outSAMattributes NH HI NM MD AS --readFilesCommand zcat  --outSAMattrRGline ID:1 PL:illumina PU:1_2014-09-24_EC_RS SM:EC_Tumor  --chimSegmentMin 15 --chimJunctionOverhangMin 15 --outSAMstrandField intronMotif |  /usr/local/bin/sambamba view --format=bam -S -t 30 /dev/stdin  | /usr/local/bin/sambamba sort --tmpdir /usr/local/share/java/null/bcbiotx/2832863d-49f3-11e4-ad21-00259058b4c8/tmpCfqZrp -t 30  /dev/stdin -o /usr/local/share/java/null/bcbiotx/2832863e-49f3-11e4-ad21-00259058b4c8/tmp2kfi9b/EC_Tumor.bam 

EXITING: FATAL INPUT ERROR: empty value for paramter "genomeDir" in input "Command-Line"
SOLUTION: use non-empty value for this parameter

Oct 02 13:15:44 ...... FATAL ERROR, exiting
' returned non-zero exit status 102
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 36, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline.run(config, config_file, parallel, dirs, pipeline_items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 306, in run
    samples = run_parallel("process_alignment", samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 644, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 391, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 129, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 63, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 27, in process_alignment
    return sample.process_alignment(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 104, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
    names, align_dir, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 98, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/star.py", line 46, in align
    do.run(cmd.format(**locals()), run_message, None)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 20, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 93, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/bin/STAR --genomeDir  --readFilesIn /newdata4/RS/EC_RS/work/trimmed/ECT100_R1.trimmed.fq.gz /newdata4/RS/EC_RS/work/trimmed/ECT100_R2.trimmed.fq.gz --runThreadN 30 --outFileNamePrefix /newdata4/RS/EC_RS/work/align/EC_Tumor/1_2014-09-24_EC_RS --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd SAM --outSAMunmapped Within --outSAMattributes NH HI NM MD AS --readFilesCommand zcat  --outSAMattrRGline ID:1 PL:illumina PU:1_2014-09-24_EC_RS SM:EC_Tumor  --chimSegmentMin 15 --chimJunctionOverhangMin 15 --outSAMstrandField intronMotif |  /usr/local/bin/sambamba view --format=bam -S -t 30 /dev/stdin  | /usr/local/bin/sambamba sort --tmpdir /usr/local/share/java/null/bcbiotx/2832863d-49f3-11e4-ad21-00259058b4c8/tmpCfqZrp -t 30  /dev/stdin -o /usr/local/share/java/null/bcbiotx/2832863e-49f3-11e4-ad21-00259058b4c8/tmp2kfi9b/EC_Tumor.bam 

EXITING: FATAL INPUT ERROR: empty value for paramter "genomeDir" in input "Command-Line"
SOLUTION: use non-empty value for this parameter

Oct 02 13:15:44 ...... FATAL ERROR, exiting
' returned non-zero exit status 102

I used tophat2 for align was fine, but star seems something wrong, could you please give me some suggestion? 

Thanks so much!

**Comment by roryk** [comment]
Thanks glad this eventually got going.
