### ISSUE TITLE
Issue running RNASeq example pipeline

### ISSUE THREAD

**Issue by pfaucon** [chapmanb/bcbio-nextgen#632]
Hi again, I'm running into issues running the [RNA Seq example](http://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines) pipeline (though the test now passes fine for me).  Specifically I'm able to complete the download and it looks like is passes the first phase (adapter trimming), although I had to re-download one of the files that appears to have been corrupted in transit (are the MD5 checksums anywhere?).  The trace of the run is [here](https://gist.github.com/pfaucon/51a49ddbf347e805d269).

It dies with the stack trace below that seems to appear because there was a file passed in with no name (ref_file = "").  I'm going to look into it a bit but with my limited knowledge of the framework any suggestions would be greatly appreciated.

Traceback (most recent call last):
File "/usr/local/bin/bcbio_nextgen.py", line 216, in <module>
main(**kwargs)
File "/usr/local/bin/bcbio_nextgen.py", line 42, in main
run_main(**kwargs)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 36, in run_main
fc_dir, run_info_yaml)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
for xs in pipeline.run(config, config_file, parallel, dirs, pipeline_items):
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 306, in run
samples = run_parallel("process_alignment", samples)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
return run_multicore(fn, items, config, parallel=parallel)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 653, in __call__
self.dispatch(function, args, kwargs)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 400, in dispatch
job = ImmediateApply(func, args, kwargs)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 138, in __init__
self.results = func(*args, **kwargs)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 63, in wrapper
return apply(f, *args, **kwargs)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 27, in process_alignment
return sample.process_alignment(*args)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 104, in process_alignment
data = align_to_sort_bam(fastq1, fastq2, aligner, data)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
names, align_dir, data)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 98, in _align_from_fastq
out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 260, in align
align_dir, data, names)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 115, in tophat_align
if _ref_version(ref_file) == 1 or options.get("fusion-search", False):
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 370, in _ref_version
"(bowtie2)." % (ref_file))
ValueError: Cannot detect which reference version &&filename should be here&&  is. Should end in either .ebwt (bowtie) or .bt2 (bowtie2).

**Comment by roryk** [comment]
Looks like this ended up running okay.
