### ISSUE TITLE
cryptic error

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#672]
I'm getting a cryptic error when running bcbio-nextgen 8.3 (exerpt below). It might not be the pipeline's fault but I'm having problems figuring out what's going on. Any advice is greatly appreciated.
>
[2014-11-27 22:43] Configuring 16 jobs to run, using 1 cores each with 1.2g of memory reserved for each job
[2014-11-27 22:43] multiprocessing: calc_callable_loci
[2014-11-27 22:43] bedtools genomecov: chr1 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr2 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr3 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr4 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr5 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr6 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr7 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr9 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr10 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr11 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr12 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr14 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr15 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr16 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr17 : 08-1855-sort.bam
[2014-11-27 22:43] bedtools genomecov: chr18 : 08-1855-sort.bam
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
[2014-11-27 22:43] bedtools genomecov: chr19 : 08-1855-sort.bam
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
[2014-11-27 22:43] bedtools genomecov: chr20 : 08-1855-sort.bam
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
[2014-11-27 22:43] bedtools genomecov: chr21 : 08-1855-sort.bam
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
[2014-11-27 22:43] bedtools genomecov: chrX : 08-1855-sort.bam
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (962, 0))
>
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 35, in run_main
    fc_dir, run_info_yaml, samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline.run(config, config_file, parallel, dirs, pipeline_items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 169, in run
    samples = run_parallel("postprocess_alignment", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 653, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 138, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 142, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 31, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 155, in postprocess_alignment
    callable.block_regions(data["work_bam"], data["sam_ref"], data["config"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 301, in block_regions
    callable_bed = parallel_callable_loci(in_bam, ref_file, config)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 45, in parallel_callable_loci
    "callable_bed", ["config"])[0]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 660, in __call__
    self.retrieve()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 543, in retrieve
    raise exception_type(report)
TypeError: __init__() takes exactly 3 arguments (2 given)

**Comment by jgbaum** [comment]
Hi @chapmanb.  I'm trying to get the dream3 cancer pipeline to run and it seems it has gone most of the way through, but I'm getting a similar error message.  Here are the last 80 lines or so of STDERR:

https://gist.github.com/jgbaum/43e7bdd7d354c50c780f#file-dream3_error

At the same time, I've tried to adapt the pipeline to my own samples and am receiving a related error:

https://gist.github.com/jgbaum/388fc5500d706373e6ab#file-tumor_normal_error

Any advice you could offer would be appreciated.  Let me know if you need any additional information to investigate.

**Comment by chapmanb** [comment]
Unfortunately that `__init__` argument error is just joblib saying that a job has failed (I need to work on a patch upstream to joblib to fix it), so doesn't have any information about the actual cause of the error. Can you follow the same advice I gave to Pär above and re-run on a single core with `-n 1`. That should provide more useful details about what is happening. Sorry about the extra work and thanks for the help debugging.

**Comment by jgbaum** [comment]
OK, thanks for the advice.  I will try it now.  As I'm a newbie to
bcbio-nextgen, I have a couple of questions as to how to rerun:

1) if I restart the run, will it resume from where it left off or is it
going to start from the beginning?

2) If it is going to start over, should I rerun in a new directory or clear
out some files?

Thanks again.
ᐧ

**Comment by roryk** [comment]
Hi @jgbaum,

You can usually just restart it and it will pick up where it left off. No need to clear out anything.

**Comment by roryk** [comment]
This seems stale so closing it out, hope everything got going eventually. Thanks!
