### ISSUE TITLE
Error with FastQC

### ISSUE THREAD

**Issue by inti** [chapmanb/bcbio-nextgen#690]
Hi,
I got the following error while analysing data with the poplar genome.
Any suggestion for what can be going wrong?
Thanks in advance
```
[2014-12-09 15:55] multiprocessing: concat_variant_files
[2014-12-09 15:55] Timing: variant post-processing
[2014-12-09 15:55] multiprocessing: postprocess_variants
[2014-12-09 15:55] Finalizing variant calls: BESC-105, freebayes
[2014-12-09 15:55] Calculating variation effects for BESC-105, freebayes
[2014-12-09 15:55] Filtering for BESC-105, freebayes
[2014-12-09 15:55] multiprocessing: split_variants_by_sample
[2014-12-09 15:55] Timing: prepped BAM merging
[2014-12-09 15:55] Timing: validation
[2014-12-09 15:55] multiprocessing: compare_to_rm
[2014-12-09 15:55] Timing: ensemble calling
[2014-12-09 15:55] Timing: validation summary
[2014-12-09 15:55] Timing: structural variation
[2014-12-09 15:55] Timing: population database
[2014-12-09 15:55] multiprocessing: prep_gemini_db
[2014-12-09 15:55] Timing: quality control
[2014-12-09 15:55] multiprocessing: pipeline_summary
[2014-12-09 15:55] Generating summary files: ['', 'BESC-105']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'BESC-52']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'BESC-015']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'BESC-366']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'DENA-17-3']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'GW-10958']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'CA-05-06']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'VNDL-27-4']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'BESC-246']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'BESC-313']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'BESC-79']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'BESC-418']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'CA-01-01']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'Nisqually-1']
[2014-12-09 15:55] Generating summary files: ['', '93-968']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] Generating summary files: ['', 'BESC-460']
[2014-12-09 15:55] There is no qsignature for this species: ptri_v3
[2014-12-09 15:55] FastQC: Nisqually-1
[2014-12-09 15:55] Started analysis of 15_2014-09-26_populus_trichocarpa_diversity_1-sort-downsample.bam
[2014-12-09 15:55] Exception in thread "Thread-1" java.lang.ArrayIndexOutOfBoundsException: 2
[2014-12-09 15:55]      at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.processSequence(PerTileQualityScores.java:207)
[2014-12-09 15:55]      at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
[2014-12-09 15:55]      at java.lang.Thread.run(Thread.java:745)
```

**Comment by roryk** [comment]
Hi @inti,

Closing this out as it is stale, hopefully this ended up working out. We bumped up the FastQC version a couple of times since this issue so maybe that resolved it. Please reopen if you're still encountering the problem.
