### ISSUE TITLE
Installation on Vagrant image fails

### ISSUE THREAD

**Issue by nuin** [chapmanb/bcbio-nextgen#713]
Hi

I am having trouble installing on a vagrant VM, tried a couple of times and the same error is returned

```
[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit  glia

Warning: local() encountered an error (return code 1) while executing 'export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit  glia'

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 75, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 335, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 255, in configure_instance
    install_biolinux(options)
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 279, in install_biolinux
    _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/fabfile.py", line 118, in _perform_install
    install_brew(flavor=flavor, automated=True)
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/fabfile.py", line 308, in install_brew
    brew.install_packages(env, to_install=pkg_install)
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 47, in install_packages
    _install_pkg(env, pkg_str, brew_cmd, ipkgs)
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 83, in _install_pkg
    _install_pkg_latest(env, pkg, args, brew_cmd, ipkgs)
  File "/home/vagrant/tmp/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 196, in _install_pkg_latest
    raise ValueError("Failed to install brew formula: %s" % pkg)
ValueError: Failed to install brew formula: glia
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

Any help appreciated.

**Comment by nuin** [comment]
It was an error on connecting to github in one of the initial requirements (bamtools) before even getting to glia, and the connection was timing out.

```
Submodule 'bamtools' (git://github.com/pezmaster31/bamtools.git) registered for path 'bamtools'
Submodule 'fastahack' (git://github.com/ekg/fastahack.git) registered for path 'fastahack'
Submodule 'gssw' (https://github.com/ekg/gssw.git) registered for path 'gssw'
Submodule 'rapidjson' (https://github.com/kennytm/rapidjson.git) registered for path 'rapidjson'
Submodule 'vcflib' (git://github.com/ekg/vcflib.git) registered for path 'vcflib'
Cloning into 'bamtools'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection timed out
```

Setting git to access only https as alternative and using the command you suggested allowed the full installation of glia.

**Comment by nuin** [comment]
Just an extra comment on the installation procedure, using the command line from the documentation, it fails on R package installs, as it doesn't have root access to the system-packages directory. Either manually running the Rscript command with sudo or adding the --sudo at the end of the command line from the documentation work fine.

**Comment by chapmanb** [comment]
Paulo;
Thanks for the report. That's unexpected as the installer should be installing these R packages into a local site library inside the isolated installation, rather than the global system-packages. Would you be able to post a traceback of the error you're seeing and we can try to investigate more? Any help would be appreciated; I'm definitely not an expert on installing isolated R packages. Thanks again.
