### ISSUE TITLE
GATK CombineVariants throws error for "exome with validation" example pipeline

### ISSUE THREAD

**Issue by nhansen** [chapmanb/bcbio-nextgen#716]
Even though this same error has been reported and closed in #675, I am now experiencing it with a fresh (isolated) install/upgrade on 12/31/2014 for the "exome with validation" pipeline at http://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html.  Context is below:

[2015-01-03 00:49] INFO  00:49:52,419 HelpFormatter - ---------------------------------------------------------------------------------
[2015-01-03 00:49] INFO  00:49:52,419 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.2-12-g034abb9, Compiled 2014/07/16 15:53:02
[2015-01-03 00:49] INFO  00:49:52,420 HelpFormatter - Copyright (c) 2010 The Broad Institute
[2015-01-03 00:49] INFO  00:49:52,420 HelpFormatter - For support and documentation go to http://www.broadinstitute.org/gatk
[2015-01-03 00:49] INFO  00:49:52,420 HelpFormatter - Program Args: -T CombineVariants --unsafe LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter
 NotPrimaryAlignment -R /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -o /cluster/ifs/projects/seqSim/bcbio_testan
alysis/NA12878-exome-eval/work/ensemble/NA12878-1/NA12878-1-ensemble-work/prep/txtmp8909166886680937091/NA12878-1-combo-nomnp-mincombine.vcf --rod_priority
_list combo,gatk,freebayes,gatk_haplotype --variant:combo /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/ensemble/NA12878-1/NA1287
8-1-ensemble-work/prep/NA12878-1-combo-nomnp.vcf --variant:gatk /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/ensemble/NA12878-1/
NA12878-1-ensemble-work/prep/NA12878-1-gatk-nomnp.vcf --variant:freebayes /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/ensemble/
NA12878-1/NA12878-1-ensemble-work/prep/NA12878-1-freebayes-nomnp.vcf --variant:gatk_haplotype /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome
-eval/work/ensemble/NA12878-1/NA12878-1-ensemble-work/prep/NA12878-1-gatk-haplotype-nomnp.vcf -L /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-ex
ome-eval/work/align/NA12878-1/NA12878-1-sort-callable_sample-sorted.bed --interval_set_rule INTERSECTION --sites_only --minimalVCF
[2015-01-03 00:49] INFO  00:49:52,421 HelpFormatter - Executing as nhansen@kcompute87.gc.nih.gov on Linux 2.6.18-348.18.1.el5.centos.plus amd64; Java HotSp
ot(TM) 64-Bit Server VM 1.7.0_60-b19.
[2015-01-03 00:49] INFO  00:49:52,421 HelpFormatter - Date/Time: 2015/01/03 00:49:52
[2015-01-03 00:49] INFO  00:49:52,421 HelpFormatter - ---------------------------------------------------------------------------------
[2015-01-03 00:49] INFO  00:49:52,422 HelpFormatter - ---------------------------------------------------------------------------------
[2015-01-03 00:49] INFO  00:49:52,447 GenomeAnalysisEngine - Strictness is SILENT
[2015-01-03 00:49] INFO  00:49:52,509 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 1000
[2015-01-03 00:49] INFO  00:49:55,693 RMDTrackBuilder - Writing Tribble index to disk for file /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exom
e-eval/work/ensemble/NA12878-1/NA12878-1-ensemble-work/prep/NA12878-1-combo-nomnp.vcf.idx
[2015-01-03 00:50] INFO  00:50:04,748 RMDTrackBuilder - Writing Tribble index to disk for file /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exom
e-eval/work/ensemble/NA12878-1/NA12878-1-ensemble-work/prep/NA12878-1-gatk-nomnp.vcf.idx
[2015-01-03 00:50] INFO  00:50:15,585 RMDTrackBuilder - Writing Tribble index to disk for file /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exom
e-eval/work/ensemble/NA12878-1/NA12878-1-ensemble-work/prep/NA12878-1-freebayes-nomnp.vcf.idx
[2015-01-03 00:50] INFO  00:50:21,872 RMDTrackBuilder - Writing Tribble index to disk for file /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exom
e-eval/work/ensemble/NA12878-1/NA12878-1-ensemble-work/prep/NA12878-1-gatk-haplotype-nomnp.vcf.idx
[2015-01-03 00:50] INFO  00:50:27,737 IntervalUtils - Processing 121648238 bp from intervals
[2015-01-03 00:50] INFO  00:50:27,780 GenomeAnalysisEngine - Preparing for traversal
[2015-01-03 00:50] INFO  00:50:27,858 GenomeAnalysisEngine - Done preparing for traversal
[2015-01-03 00:50] INFO  00:50:27,859 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING]
[2015-01-03 00:50] INFO  00:50:27,859 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining
[2015-01-03 00:50] INFO  00:50:27,859 ProgressMeter -        Location |     sites | elapsed |     sites | completed | runtime |   runtime
[2015-01-03 00:50] INFO  00:50:27,860 CombineVariants - Pre-stripping genotypes for performance
[2015-01-03 00:50] Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
[2015-01-03 00:50]      at htsjdk.variant.variantcontext.CommonInfo.getAttributeAsInt(CommonInfo.java:242)
[2015-01-03 00:50]      at htsjdk.variant.variantcontext.VariantContext.getAttributeAsInt(VariantContext.java:703)
[2015-01-03 00:50]      at org.broadinstitute.gatk.utils.variant.GATKVariantContextUtils.simpleMerge(GATKVariantContextUtils.java:946)
[2015-01-03 00:50]      at org.broadinstitute.gatk.tools.walkers.variantutils.CombineVariants.map(CombineVariants.java:309)
[2015-01-03 00:50]      at org.broadinstitute.gatk.tools.walkers.variantutils.CombineVariants.map(CombineVariants.java:117)
[2015-01-03 00:50]      at org.broadinstitute.gatk.engine.traversals.TraverseLociNano$TraverseLociMap.apply(TraverseLociNano.java:267)
[2015-01-03 00:50]      at org.broadinstitute.gatk.engine.traversals.TraverseLociNano$TraverseLociMap.apply(TraverseLociNano.java:255)
[2015-01-03 00:50]      at org.broadinstitute.gatk.utils.nanoScheduler.NanoScheduler.executeSingleThreaded(NanoScheduler.java:274)
[2015-01-03 00:50]      at org.broadinstitute.gatk.utils.nanoScheduler.NanoScheduler.execute(NanoScheduler.java:245)
[2015-01-03 00:50]      at org.broadinstitute.gatk.engine.traversals.TraverseLociNano.traverse(TraverseLociNano.java:144)
[2015-01-03 00:50]      at org.broadinstitute.gatk.engine.traversals.TraverseLociNano.traverse(TraverseLociNano.java:92)
[2015-01-03 00:50]      at org.broadinstitute.gatk.engine.traversals.TraverseLociNano.traverse(TraverseLociNano.java:48)
[2015-01-03 00:50]      at org.broadinstitute.gatk.engine.executive.LinearMicroScheduler.execute(LinearMicroScheduler.java:99)
[2015-01-03 00:50]      at org.broadinstitute.gatk.engine.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:314)
[2015-01-03 00:50]      at org.broadinstitute.gatk.engine.CommandLineExecutable.execute(CommandLineExecutable.java:121)
[2015-01-03 00:50]      at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:248)
[2015-01-03 00:50]      at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:155)
[2015-01-03 00:50]      at bcbio.run.broad$run_gatk$fn__1805.invoke(broad.clj:34)
[2015-01-03 00:50]      at bcbio.run.broad$run_gatk.invoke(broad.clj:31)
[2015-01-03 00:50]      at bcbio.variation.combine$combine_variants.doInvoke(combine.clj:71)
[2015-01-03 00:50]      at clojure.lang.RestFn.invoke(RestFn.java:1557)
[2015-01-03 00:50]      at bcbio.variation.recall$get_min_merged.invoke(recall.clj:158)
[2015-01-03 00:50]      at bcbio.variation.recall$fn__7040.invoke(recall.clj:173)
[2015-01-03 00:50]      at clojure.lang.MultiFn.invoke(MultiFn.java:249)
[2015-01-03 00:50]      at bcbio.variation.recall$create_merged$fn__7045.invoke(recall.clj:187)
[2015-01-03 00:50]      at clojure.core$map$fn__4207.invoke(core.clj:2487)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.RT.seq(RT.java:484)
[2015-01-03 00:50]      at clojure.core$seq.invoke(core.clj:133)
[2015-01-03 00:50]      at clojure.core$map$fn__4214.invoke(core.clj:2496)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.RT.seq(RT.java:484)
[2015-01-03 00:50]      at clojure.core$seq.invoke(core.clj:133)
[2015-01-03 00:50]      at clojure.core$map$fn__4207.invoke(core.clj:2479)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.RT.seq(RT.java:484)
[2015-01-03 00:50]      at clojure.core$seq.invoke(core.clj:133)
[2015-01-03 00:50]      at clojure.core$map$fn__4211.invoke(core.clj:2490)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.RT.seq(RT.java:484)
[2015-01-03 00:50]      at clojure.core$seq.invoke(core.clj:133)
[2015-01-03 00:50]      at clojure.core$map$fn__4207.invoke(core.clj:2479)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.RT.seq(RT.java:484)
[2015-01-03 00:50]      at clojure.core$seq.invoke(core.clj:133)
[2015-01-03 00:50]      at clojure.core$map$fn__4214.invoke(core.clj:2496)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.RT.seq(RT.java:484)
[2015-01-03 00:50]      at clojure.core$seq.invoke(core.clj:133)
[2015-01-03 00:50]      at clojure.core$map$fn__4207.invoke(core.clj:2479)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.RT.seq(RT.java:484)
[2015-01-03 00:50]      at clojure.core$seq.invoke(core.clj:133)
[2015-01-03 00:50]      at clojure.core$reduce1.invoke(core.clj:890)
[2015-01-03 00:50]      at clojure.core$reverse.invoke(core.clj:904)
[2015-01-03 00:50]      at clojure.math.combinatorics$combinations.invoke(combinatorics.clj:73)
[2015-01-03 00:50]      at bcbio.variation.compare$variant_comparison_from_config$iter__7582__7586$fn__7587.invoke(compare.clj:255)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.RT.seq(RT.java:484)
[2015-01-03 00:50]      at clojure.core$seq.invoke(core.clj:133)
[2015-01-03 00:50]      at clojure.core$tree_seq$walk__4647$fn__4648.invoke(core.clj:4475)
[2015-01-03 00:50]      at clojure.lang.LazySeq.sval(LazySeq.java:42)
[2015-01-03 00:50]      at clojure.lang.LazySeq.seq(LazySeq.java:60)
[2015-01-03 00:50]      at clojure.lang.LazySeq.more(LazySeq.java:96)
[2015-01-03 00:50]      at clojure.lang.RT.more(RT.java:607)
[2015-01-03 00:50]      at clojure.core$rest.invoke(core.clj:73)
[2015-01-03 00:50]      at clojure.core$flatten.invoke(core.clj:6478)
[2015-01-03 00:50]      at bcbio.variation.compare$variant_comparison_from_config.invoke(compare.clj:254)
[2015-01-03 00:50]      at bcbio.variation.ensemble$consensus_calls.invoke(ensemble.clj:113)
[2015-01-03 00:50]      at bcbio.variation.ensemble$_main.doInvoke(ensemble.clj:133)
[2015-01-03 00:50]      at clojure.lang.RestFn.applyTo(RestFn.java:137)
[2015-01-03 00:50]      at clojure.core$apply.invoke(core.clj:617)
[2015-01-03 00:50]      at bcbio.variation.core$_main.doInvoke(core.clj:35)
[2015-01-03 00:50]      at clojure.lang.RestFn.applyTo(RestFn.java:137)
[2015-01-03 00:50]      at bcbio.variation.core.main(Unknown Source)
[2015-01-03 00:50] INFO  00:50:57,863 ProgressMeter -       1:9011292      1198.0    30.0 s       7.0 h        0.5%    93.7 m      93.2 m
[2015-01-03 00:51] INFO  00:51:27,869 ProgressMeter -       1:9011292      1198.0    60.0 s      13.9 h        0.5%     3.1 h       3.1 h
[2015-01-03 00:51] INFO  00:51:57,874 ProgressMeter -       1:9011292      1198.0    90.0 s      20.9 h        0.5%     4.7 h       4.7 h
[2015-01-03 00:52] INFO  00:52:27,877 ProgressMeter -       1:9011292      1198.0   120.0 s      27.8 h        0.5%     6.2 h       6.2 h
[2015-01-03 00:52] INFO  00:52:57,879 ProgressMeter -       1:9011292      1198.0     2.5 m      34.8 h        0.5%     7.8 h       7.8 h
[2015-01-03 00:53] INFO  00:53:27,884 ProgressMeter -       1:9011292      1198.0     3.0 m      41.7 h        0.5%     9.4 h       9.3h

and so on...

All four VCFs passed as arguments to GATK look complete and well-formatted, although I haven't run any formal validation on them.

Thanks very much for all of your work on this pipeline!

Best,
--Nancy

**Comment by chapmanb** [comment]
Nancy;
Sorry about the issue. This is fixed but not yet in a release version. We're hoping to push a new release in the next couple of days and are just testing some recent additions before doing that. If you upgrade to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
It should now work cleanly. You'll unfortunately need to remove the old `freebayes` directory to regenerate those calls. You'll probably also want to tell bcbio to parallelize the rerun, so this cleanup should do it:
```
rm -rf freebayes
rm -f checkpoints_parallel/full.done
```
and then re-run with the upgraded development version. Sorry again about the issue and hope this works for you.

**Comment by nhansen** [comment]
Thanks, Brad.  I did the development upgrade as you suggested, then tried to run the analysis from the beginning.  Now it fails with the following error:

[2015-01-05T01:38Z] Index BAM file: NA12878-1-sort-Y_15591349_59373566-prep.bam
[2015-01-05T01:38Z] Index BAM file: NA12878-1-sort-nochrom-prep.bam
Traceback (most recent call last):
  File "../../../bcbio-nextgen/bcbio/anaconda/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "../../../bcbio-nextgen/bcbio/anaconda/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 81, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 164, in run
    samples = region.parallel_prep_region(samples, run_parallel)
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 121, in parallel_prep_region
    "piped_bamprep", _add_combine_info, file_key, ["config"])
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 660, in __call__
    self.retrieve()
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 543, in retrieve
    raise exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by chapmanb** [comment]
Nancy;
Sorry about the continued issues. It's failing during the BAM post-preparation step but this posted traceback is the generic one that Python produces when it fails running multicore, so doesn't indicate the underlying issue. Can you re-run with a single core:
```
bcbio_nextgen.py your_config.yaml -n 1
```
to see what it reports. That might give us more information to dig into the problem. Thanks much.

**Comment by nhansen** [comment]
Hi Brad,
I'm running it in single-core mode now, but hadn't noticed this error from earlier in the multicore run, which seems more informative:

[2015-01-06T02:24Z] Select unanalyzed reads
[2015-01-06T02:24Z] ERROR: File /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work_parallel/regions/NA12878-1-noanalysis_bloc
ks.bed has inconsistent naming convention (leading zero) for record:
[2015-01-06T02:24Z] GL000207.1  0       4262
[2015-01-06T02:24Z] sambamba-view: unable to write to stream
[2015-01-06T02:24Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/sambamba view -f bam -L /cluster/ifs/projects/s
eqSim/bcbio_testanalysis/NA12878-exome-eval/work_parallel/regions/NA12878-1-noanalysis_blocks.bed /cluster/ifs/projects/seqSim/bcbio_testanalysis/
NA12878-exome-eval/work_parallel/align/NA12878-1/NA12878-1-sort.bam | /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/bedtools intersect -aba
m - -b /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work_parallel/regions/NA12878-1-noanalysis_blocks.bed -f 1.0 > /cluster/
ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work_parallel/bamprep/NA12878-1/noanalysis/tx/tmpySPyFd/NA12878-1-sort-noanalysis-prep.b
am
ERROR: File /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work_parallel/regions/NA12878-1-noanalysis_blocks.bed has inconsist
ent naming convention (leading zero) for record:
GL000207.1      0       4262

**Comment by chapmanb** [comment]
Nancy;
Apologies, this is an issue with the latest bedtools (arq5x/bedtools2#166). We're still working on an automated fix but you can resolve it locally by reverting bedtools to the previous version:
```
wget https://raw.githubusercontent.com/Homebrew/homebrew-science/efa5450b192c13d2f6b4aa62233222bd9a48ef69/bedtools.rb
/cluster/ifs/projects/seqSim/bcbio-nextgen/bin/brew uninstall --force bedtools
export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && /cluster/ifs/projects/seqSim/bcbio-nextgen/bin/brew install --env=inherit -v bedtools.rb
```
Hope this gets things working for you.

**Comment by chapmanb** [comment]
Nancy;
We rolled back the bedtools version so this should be fixed now if you do another upgrade:
```
bcbio_nextgen.py upgrade --tools
```
Sorry again about the problem and hope this fixes everything for you. Feel free to re-open this if you run into any other problems.
