### ISSUE TITLE
Docker build failed 

### ISSUE THREAD

**Issue by tetron** [chapmanb/bcbio-nextgen#717]
Ran `$ docker build .` on current master (a2dab3d)

```
(... lots of stuff ...)
installing: conda-3.5.5-py27_0 ...
Python 2.7.7 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /usr/local/share/bcbio-nextgen/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.7.4                |           py27_0         160 KB
    numpy-1.9.1                |           py27_0         7.7 MB
    openssl-1.0.1j             |                5         2.6 MB
    python-2.7.9               |                1        13.4 MB
    requests-2.5.1             |           py27_0         587 KB
    zlib-1.2.8                 |                0         100 KB
    ------------------------------------------------------------
                                           Total:        24.5 MB

The following packages will be UN-linked:

    package                    |            build
    ---------------------------|-----------------
    conda-3.5.5                |           py27_0
    openssl-1.0.1h             |                0
    python-2.7.7               |                0
    requests-2.3.0             |           py27_0
    zlib-1.2.7                 |                0

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    conda-3.7.4                |           py27_0   hard-link
    numpy-1.9.1                |           py27_0   hard-link
    openssl-1.0.1j             |                5   hard-link
    python-2.7.9               |                1   hard-link
    requests-2.5.1             |           py27_0   hard-link
    zlib-1.2.8                 |                0   hard-link

Fetching packages ...
conda-3.7.4-py 100% |###############################| Time: 0:00:00   1.73 MB/s
numpy-1.9.1-py 100% |###############################| Time: 0:00:03   2.45 MB/s
openssl-1.0.1j 100% |###############################| Time: 0:00:00   3.34 MB/s
python-2.7.9-1 100% |###############################| Time: 0:00:01  10.51 MB/s
requests-2/usr/local/share/bcbio-nextgen/anaconda/bin/.openssl-post-link.sh: line 28: hexdump: command not found
/usr/local/share/bcbio-nextgen/anaconda/bin/.openssl-post-link.sh: line 28: hexdump: command not found
/usr/local/share/bcbio-nextgen/anaconda/bin/.openssl-post-link.sh: line 28: hexdump: command not found
/usr/local/share/bcbio-nextgen/anaconda/bin/.openssl-post-link.sh: line 28: hexdump: command not found
/usr/local/share/bcbio-nextgen/anaconda/bin/.openssl-post-link.sh: line 28: hexdump: command not found
/usr/local/share/bcbio-nextgen/anaconda/bin/.openssl-post-link.sh: line 28: hexdump: command not found
/usr/local/share/bcbio-nextgen/anaconda/bin/.openssl-post-link.sh: line 28: hexdump: command not found
requests-2.5.1 100% |###############################| Time: 0:00:00   1.18 MB/s
zlib-1.2.8-0.t 100% |###############################| Time: 0:00:00   1.53 MB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/bin/conda", line 3, in <module>
    from conda.cli import main
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from conda.cli.main import main
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 48, in <module>
    from conda.cli import main_create
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 11, in <module>
    from conda.cli import common, install
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 18, in <module>
    import conda.plan as plan
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/conda/plan.py", line 22, in <module>
    from conda.fetch import fetch_pkg
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 24, in <module>
    from conda.connection import CondaSession, unparse_url, RETRIES
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/conda/connection.py", line 22, in <module>
    import requests
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .ssl_ import (
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 2, in <module>
    from hashlib import md5, sha1
ImportError: cannot import name md5
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 35, in main
    install_conda_pkgs(anaconda)
  File "bcbio_nextgen_install.py", line 95, in install_conda_pkgs
    subprocess.check_call([anaconda["conda"], "install", "--yes"] + channels + pkgs)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio-nextgen/anaconda/bin/conda', 'install', '--yes', '-c', 'https://conda.binstar.org/bcbio', 'biopython', 'boto', 'cnvkit', 'cpat', 'cython', 'ipython', 'lxml', 'matplotlib', 'msgpack-python', 'nose', 'numpy', 'pandas', 'patsy', 'pycrypto', 'pip', 'pysam', 'pyvcf', 'pyyaml', 'pyzmq', 'reportlab', 'requests', 'scikit-learn', 'scipy', 'seaborn', 'setuptools', 'sqlalchemy', 'statsmodels', 'toolz', 'tornado']' returned non-zero exit status 1
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
2015/01/09 09:41:54 The command [/bin/sh -c mkdir -p /tmp/bcbio-nextgen-install && cd /tmp/bcbio-nextgen-install &&     wget --no-check-certificate       https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py &&     python bcbio_nextgen_install.py /usr/local/share/bcbio-nextgen       --nodata -u development] returned a non-zero code: 1
```

**Comment by tetron** [comment]
See pull request #718
