### ISSUE TITLE
error specifying account in slurm

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#731]
Not sure if this was expected. If I ignore adding account it defaults to my primary group.

```
bcbio_nextgen.py  project_n143-fb/config/project_n143-fb.yaml  -t ipython -n 500 -q normal -s slurm -r "account:dwaggott;timelimit=48:00:00"

reate] Generating default config file: u'/scratch/PI/euan/projects/athletes/bcbio/log/ipython/ipython_config.py'
[ProfileCreate] Generating default config file: u'/scratch/PI/euan/projects/athletes/bcbio/log/ipython/ipython_notebook_config.py'
[ProfileCreate] Generating default config file: u'/scratch/PI/euan/projects/athletes/bcbio/log/ipython/ipython_nbconvert_config.py'
[ProfileCreate] Generating default config file: u'/scratch/PI/euan/projects/athletes/bcbio/log/ipython/ipcontroller_config.py'
[ProfileCreate] Generating default config file: u'/scratch/PI/euan/projects/athletes/bcbio/log/ipython/ipengine_config.py'
[ProfileCreate] Generating default config file: u'/scratch/PI/euan/projects/athletes/bcbio/log/ipython/ipcluster_config.py'
[ProfileCreate] Generating default config file: u'/scratch/PI/euan/projects/athletes/bcbio/log/ipython/iplogger_config.py'
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 81, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 140, in run
    multiplier=alignprep.parallel_multiplier(samples)) as run_parallel:
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 53, in start
 with ipython.create(parallel, dirs, config) as view:
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/dwaggott/.local/lib/python2.7/site-packages/cluster_helper/cluster.py", line 894, in cluster_view
    _start(scheduler, profile, queue, num_jobs, cores_per_job, cluster_id, extra_params)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/cluster_helper/cluster.py", line 780, in _start
    resources, slurm_atrs = get_slurm_attributes(queue, resources)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/cluster_helper/slurm.py", line 67, in get_slurm_attributes
    k, v = [ a.strip() for a in  parm.split('=') ]
ValueError: need more than 1 value to unpack

$ echo $USER
dwaggott

```

**Comment by chapmanb** [comment]
Daryl;
Thanks for the detailed report. I think you want:
```
-r "account=dwaggott;timelimit=48:00:00"
```
so `account=` instead of `account:`. Hope this fixes it for you.

**Comment by dwaggott** [comment]
Sigh... :+1:
