### ISSUE TITLE
Ensamble error running the SV calling 50x example

### ISSUE THREAD

**Issue by druvus** [chapmanb/bcbio-nextgen#732]
Hi Brad, 
I am getting the following error running the [SV calling 50x example](https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#structural-variant-calling-whole-genome-trio-50x) using the development version. It might be related to the #604 fix. 
  
<pre>
[2015-01-23T10:35Z] Select sample: NA12878
[2015-01-23T10:35Z] tabix index 3_2014-07-05_ceu-sort-ceu-svs-NA12878.vcf.gz
[2015-01-23T10:35Z] bgzip 3_2014-07-05_ceu-sort-ceu-svs-NA12878-filter.vcf
[2015-01-23T10:35Z] tabix index 3_2014-07-05_ceu-sort-ceu-svs-NA12878-filter.vcf.gz
Traceback (most recent call last):
  File "/media/data/bin/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/media/data/bin/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 81, in _run_toplev
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 188, in run
    samples = structural.run(samples, run_parallel)
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 87, in run
    return extras + _combine_multiple_svcallers(processed)
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 55, in _comb
    final_calls = ensemble.summarize(final_calls, final, highdepths)
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/structural/ensemble.py", line 184, in summ
    filter_file = _filter_ensemble(out_file, data)
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/structural/ensemble.py", line 154, in _fil
    for event, caller in [x.split("_") for x in caller_strs.split(",")]:
ValueError: too many values to unpack
</pre>

The output in bcbio-nextgen-debug.log
<pre>
[2015-01-23T10:33Z] INFO  11:33:01,381 ProgressMeter -       Y:5392809   2.796980455E9   115.5 m       2.0 s       99.8%   115.7 m      13.0 s
[2015-01-23T10:33Z] INFO  11:33:29,729 ProgressMeter -            done   2.798728658E9   116.0 m       2.0 s       99.8%   116.2 m      11.0 s
[2015-01-23T10:33Z] INFO  11:33:29,729 ProgressMeter - Total runtime 6958.84 secs, 115.98 min, 1.93 hours
[2015-01-23T10:33Z] Select sample: NA12892
[2015-01-23T10:33Z] tabix index 3_2014-07-05_ceu-sort-ceu-svs-NA12892.vcf.gz
[2015-01-23T10:34Z] bgzip 3_2014-07-05_ceu-sort-ceu-svs-NA12892-filter.vcf
[2015-01-23T10:34Z] tabix index 3_2014-07-05_ceu-sort-ceu-svs-NA12892-filter.vcf.gz
[2015-01-23T10:34Z] Select sample: NA12891
[2015-01-23T10:34Z] tabix index 3_2014-07-05_ceu-sort-ceu-svs-NA12891.vcf.gz
[2015-01-23T10:34Z] bgzip 3_2014-07-05_ceu-sort-ceu-svs-NA12891-filter.vcf
[2015-01-23T10:34Z] tabix index 3_2014-07-05_ceu-sort-ceu-svs-NA12891-filter.vcf.gz
[2015-01-23T10:35Z] Select sample: NA12878
[2015-01-23T10:35Z] tabix index 3_2014-07-05_ceu-sort-ceu-svs-NA12878.vcf.gz
[2015-01-23T10:35Z] bgzip 3_2014-07-05_ceu-sort-ceu-svs-NA12878-filter.vcf
[2015-01-23T10:35Z] tabix index 3_2014-07-05_ceu-sort-ceu-svs-NA12878-filter.vcf.gz
</pre>

**Comment by chapmanb** [comment]
Andreas;
Thanks much for the heads up. Apologies, I was not handling `cn_mops` correctly in the new ensemble based calling. If you update to the latest development it should hopefully work as expected. Let me know if you run into anything else at all.
