### ISSUE TITLE
Error in alignment stage: sambamba-sort: work/tx/tmpxxxxxx/.... Directory not empty

### ISSUE THREAD

**Issue by rronen** [chapmanb/bcbio-nextgen#747]
Hi guys,

Getting an error during alignment that I haven't seen before. This is for a paired tumor/normal exome-seq analysis with BAM as input. It is failing on the first command (`samtools sort | bam2fq | bwa mem | samtools view | sambamba sort | ....` :).

Initially there's an uncaught exception:
```
[2015-02-06T22:44Z] Timing: organize samples
[2015-02-06T22:44Z] multiprocessing: organize_samples
[2015-02-06T22:44Z] Using input YAML configuration: /bcbio_work/ubuntu/encrypted/config/p3_1_B1_tumor_normal_fullbamprep_fb_vb.yaml
[2015-02-06T22:44Z] Checking sample YAML configuration: /bcbio_work/ubuntu/encrypted/config/p3_1_B1_tumor_normal_fullbamprep_fb_vb.yaml
[2015-02-06T22:44Z] Testing minimum versions of installed programs
[2015-02-06T22:44Z] Timing: alignment preparation
[2015-02-06T22:44Z] multiprocessing: prep_align_inputs
[2015-02-06T22:44Z] multiprocessing: disambiguate_split
[2015-02-06T22:44Z] Timing: alignment
[2015-02-06T22:44Z] multiprocessing: process_alignment
[2015-02-06T22:44Z] Aligning lane 1_2015-02-02_p3_1_B1_tumor_normal with bwa aligner
[2015-02-07T04:04Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/ubuntu/bcbio_tooldir/bin/samtools sort -n -o -l 1 -@ 8 -m 682M /bcbio_work/ubuntu/encrypted/input/03-1-B1.merged.sorted.bam /bcbio_work/ubuntu/encrypted/work/align/p3_T_1B1/tx/tmplp7A0j/1_2015-02-02_p3_1_B1_tumor_normal-sort-in1 | /home/ubuntu/bcbio_tooldir/bin/bedtools bamtofastq -i /dev/stdin -fq /dev/stdout -fq2 /dev/stdout | /home/ubuntu/bcbio_tooldir/bin/bwa mem -p -M -t 8  -R '@RG\tID:1\tPL:illumina\tPU:1_2015-02-02_p3_1_B1_tumor_normal\tSM:p3_T_1B1' -v 1 /home/ubuntu/bcbio_datadir/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa - | /home/ubuntu/bcbio_tooldir/bin/samblaster --splitterFile >(/home/ubuntu/bcbio_tooldir/bin/samtools view -S -u /dev/stdin | /home/ubuntu/bcbio_tooldir/bin/sambamba sort -t 8 -m 1G --tmpdir /bcbio_work/ubuntu/encrypted/work/tx/tmpr6XGCn/spl -o /bcbio_work/ubuntu/encrypted/work/align/p3_T_1B1/tx/tmp0hMcSa/1_2015-02-02_p3_1_B1_tumor_normal-sort-sr.bam /dev/stdin) --discordantFile >(/home/ubuntu/bcbio_tooldir/bin/samtools view -S -u /dev/stdin | /home/ubuntu/bcbio_tooldir/bin/sambamba sort -t 8 -m 1G --tmpdir /bcbio_work/ubuntu/encrypted/work/tx/tmpr6XGCn/disc -o /bcbio_work/ubuntu/encrypted/work/align/p3_T_1B1/tx/tmpFXMwfe/1_2015-02-02_p3_1_B1_tumor_normal-sort-disc.bam /dev/stdin) | /home/ubuntu/bcbio_tooldir/bin/samtools view -S -u /dev/stdin | /home/ubuntu/bcbio_tooldir/bin/sambamba sort -t 8 -m 1G --tmpdir /bcbio_work/ubuntu/encrypted/work/tx/tmpr6XGCn/full -o /bcbio_work/ubuntu/encrypted/work/align/p3_T_1B1/tx/tmplp7A0j/1_2015-02-02_p3_1_B1_tumor_normal-sort.bam /dev/stdin
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 2508)
[M::mem_pestat] mean and std.dev: (694.80, 633.87)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 3296)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
```

However it goes on to do alignment for several hours and then crashes with:
```
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[main] Version: 0.7.12-r1039
samblaster: Output 1145493 discordant read pairs to /dev/fd/62
[main] CMD:samblaster: Output 357202 split reads to /dev/fd/63
 /home/ubuntu/bcbio_tooldir/bin/bwa mem -p -M -t 8 -R @RG\tID:1\tPL:illumina\tPU:1_2015-02-02_p3_1_B1_tumor_normal\tSM:p3_T_1B1 -v 1 /home/ubuntu/bcbio_datadir/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa -samblaster: Marked 7756695 of 139024119 (5.58%) read ids as duplicates
[main] Real time: 17296.688 sec; CPU: 90402.252 sec
 using 2807792k memory in 6M10S(369.872S) CPU seconds and 4H48M16S(17296S) wall time.
sambamba-sort: /bcbio_work/ubuntu/encrypted/work/tx/tmpr6XGCn/disc/sambamba-pid4162-ksxx: Directory not empty
sambamba-sort: /bcbio_work/ubuntu/encrypted/work/tx/tmpr6XGCn/full/sambamba-pid4156-qane: Directory not empty
' returned non-zero exit status 1
```

Let me know if there's any additional info that might help in figuring it out.

EDIT: the `work/align` and `work/align/tx` dirs are empty. 

Thanks,
Roy

**Comment by chapmanb** [comment]
Roy;
Sorry about the issue. Could you try upgrading to the latest development (which will be a new release hopefully soon) and retrying the run:
```
bcbio_nextgen.py upgrade -u devel --tools
```
We re-did the sorting code to simplifying it a bit by using only samtools sort, which I hope will resolve the problem. If you still have issues please let us know and we'll dig more before the next release. Thanks much.

**Comment by rronen** [comment]
Hi Brad,

Thanks -- I've updated and will update as soon as I know if it's resolved.

R.

**Comment by rronen** [comment]
Hi Brad,

I've updated with `bcbio_nextgen.py  upgrade -u development --tools` but still seeing some issues in the alignment stage. I've re-copied from s3 and also tried with a different set of inputs (BAMs) to make sure the problem isn't actually truncated/damaged input files on my end.

The only command that runs (from log/bcbio-nextgen-commands.log) is:
```
[2015-02-08T22:53Z] /home/ubuntu/bcbio_tooldir/bin/samtools sort -n -o -l 1 -@ 8 -m 682M /bcbio_work/ubuntu/encrypted/p2/input/p2_Tumor_1B1.bam /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpYQDNxd/1_2015-02-02_p3_1_B1_tumor_normal-sort-in1 | /home/ubuntu/bcbio_tooldir/bin/bedtools bamtofastq -i /dev/stdin -fq /dev/stdout -fq2 /dev/stdout | /home/ubuntu/bcbio_tooldir/bin/bwa mem -p -M -t 8  -R '@RG\tID:1\tPL:illumina\tPU:1_2015-02-02_p3_1_B1_tumor_normal\tSM:p2_T_1B1' -v 1 /home/ubuntu/bcbio_datadir/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa - | /home/ubuntu/bcbio_tooldir/bin/samblaster --splitterFile >(/home/ubuntu/bcbio_tooldir/bin/samtools sort -@ 8 -m 1G -T /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpYQDNxd/1_2015-02-02_p3_1_B1_tumor_normal-sort-sorttmp-spl -o /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpKPaJk_/1_2015-02-02_p3_1_B1_tumor_normal-sort-sr.bam /dev/stdin) --discordantFile >(/home/ubuntu/bcbio_tooldir/bin/samtools sort -@ 8 -m 1G -T /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpYQDNxd/1_2015-02-02_p3_1_B1_tumor_normal-sort-sorttmp-disc -o /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmptK3Lz1/1_2015-02-02_p3_1_B1_tumor_normal-sort-disc.bam /dev/stdin) | /home/ubuntu/bcbio_tooldir/bin/samtools sort -@ 8 -m 1G -T /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpYQDNxd/1_2015-02-02_p3_1_B1_tumor_normal-sort-sorttmp-full -o /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpYQDNxd/1_2015-02-02_p3_1_B1_tumor_normal-sort.bam /dev/stdin
```

I see is a lot of:
```
*****WARNING: Query H7G53ADXX:2:2216:21310:34852 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
*****WARNING: Query H7G53ADXX:2:2216:21310:45020 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
*****WARNING: Query H7G53ADXX:2:2216:21310:49239 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
*****WARNING: Query H7G53ADXX:2:2216:21310:64697 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
...
...
...
```
eventually followed by:
```
/bin/bash: line 1:  3661 Done                    /home/ubuntu/bcbio_tooldir/bin/samtools sort -n -o -l 1 -@ 8 -m 682M /bcbio_work/ubuntu/encrypted/p2/input/p2_Tumor_1B1.bam /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpKvey2G/1_2015-02-02_p3_1_B1_tumor_normal-sort-in1
      3662                       | /home/ubuntu/bcbio_tooldir/bin/bedtools bamtofastq -i /dev/stdin -fq /dev/stdout -fq2 /dev/stdout
      3663 Exit 1                  | /home/ubuntu/bcbio_tooldir/bin/bwa mem -p -M -t 8 -R '@RG\tID:1\tPL:illumina\tPU:1_2015-02-02_p3_1_B1_tumor_normal\tSM:p2_T_1B1' -v 1 /home/ubuntu/bcbio_datadir/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa -
      3664 Exit 1                  | /home/ubuntu/bcbio_tooldir/bin/samblaster --splitterFile >(/home/ubuntu/bcbio_tooldir/bin/samtools sort -@ 8 -m 1G -T /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpKvey2G/1_2015-02-02_p3_1_B1_tumor_normal-sort-sorttmp-spl -o /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpM8FLTr/1_2015-02-02_p3_1_B1_tumor_normal-sort-sr.bam /dev/stdin) --discordantFile >(/home/ubuntu/bcbio_tooldir/bin/samtools sort -@ 8 -m 1G -T /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpKvey2G/1_2015-02-02_p3_1_B1_tumor_normal-sort-sorttmp-disc -o /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpIfKUHq/1_2015-02-02_p3_1_B1_tumor_normal-sort-disc.bam /dev/stdin)
      3665 Killed                  | /home/ubuntu/bcbio_tooldir/bin/samtools sort -@ 8 -m 1G -T /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpKvey2G/1_2015-02-02_p3_1_B1_tumor_normal-sort-sorttmp-full -o /bcbio_work/ubuntu/encrypted/p2/work/align/p2_T_1B1/tx/tmpKvey2G/1_2015-02-02_p3_1_B1_tumor_normal-sort.bam /dev/stdin
' returned non-zero exit status 137
```

Any pointers on this would be great.

Thanks,
Roy

**Comment by chapmanb** [comment]
Roy;
Sorry about the problems. Perhaps we're being too aggressive trying to convert and stream BAMs directly into alignment this way. It looks like the operating system is killing this but I'm not sure exactly why. At scale, most of the BAM input work we've done has first converted to fastq and indexed, then aligned in regions. I pushed a fix to separate this fastq prep from the alignment step so it'll happen even without setting `align_split_size`. I hope this will get you clean fastq preps from the BAMs and then non-failing runs. If you do one more update:
```
bcbio_nextgen.py upgrade -u development
```
can you see if that resolves the issue? Thanks for all the patience getting this fixed.

**Comment by rronen** [comment]
Hi Brad,

Thanks for your help sorting this out. I've upgraded and have a couple of full-sized datasets going all day -- both well past the alignment stage. Probably safe to close this issue. There may be some minor trouble ahead merging the calls - but that is for [another issue](https://github.com/chapmanb/bcbio-nextgen/issues/744) :).

Thanks again!
Roy
