### ISSUE TITLE
install on openSUSE 13.2

### ISSUE THREAD

**Issue by szuszmok** [chapmanb/bcbio-nextgen#759]
Hi,
sorry for the silly question, but when I tried to install on my openSUSE:

wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local \
  --genomes GRCh37 --aligners bwa --aligners bowtie2

finally got this error message (with the traceback):

INFO: <cloudbio.flavor.Flavor instance at 0x7fd5d6022d40>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 75, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 335, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 101, in _setup_vm
    _setup_cloudbiolinux(options)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 193, in _setup_cloudbiolinux
    _configure_fabric_environment(env, flavor, fabricrc_loader=fabricrc_loader)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/utils.py", line 93, in _configure_fabric_environment
    _setup_distribution_environment(ignore_distcheck=ignore_distcheck)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/distribution.py", line 33, in _setup_distribution_environment
    env.distribution = _determine_distribution(env)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/distribution.py", line 299, in _determine_distribution
    raise Exception("Attempt to automatically determine Linux distribution of target machine failed, please manually specify distribution in fabricrc.txt")
Exception: Attempt to automatically determine Linux distribution of target machine failed, please manually specify distribution in fabricrc.txt
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

How should I determine my distribution in "fabricrc.txt"? distribution = suse ?

Thank you very much!

**Comment by chapmanb** [comment]
Sorry about the issues. We're in the progress on getting a build working on SUSE Enterprise 11 SP3 which we hope will translate to OpenSUSE as well (#745).

For the immediate issue you're running into, we need to add detection of this as suse within the CloudBioLinux build. Can you pass along the result of:
```
cat /etc/*release
```
I can apply that fix and a couple of in-progress fixes for the build and then hopefully it'll proceed cleanly. Thanks much for the report and help debugging.

**Comment by szuszmok** [comment]
the requested result:

NAME=openSUSE
VERSION="13.2 (Harlequin)"
VERSION_ID="13.2"
PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:13.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
openSUSE 13.2 (x86_64)
VERSION = 13.2
CODENAME = Harlequin
# /etc/SuSE-release is deprecated and will be removed in the future, use /etc/os-release instead

Thank you!

**Comment by chapmanb** [comment]
Thanks much for this. I pushed fixes to the build and bcbio should hopefully build cleanly on SUSE. Please feel free to re-open this issue if you run into any other problems. Thanks again.
