### ISSUE TITLE
Error finding GATK on Vagrant instance

### ISSUE THREAD

**Issue by nuin** [chapmanb/bcbio-nextgen#760]
Hi

I am getting an error running one of the tests available on the documentation, on a Vagrant installed instance of bcbio.

My command is
```
bcbio_nextgen.py ../config/NA12878-exome-methodcmp.yaml -n 8
```

and the tail end of the error is this:

```
[2015-02-12T23:32Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 416)
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 81, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 153, in run
    samples = run_parallel("postprocess_alignment", samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 653, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 138, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 149, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 31, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 155, in postprocess_alignment
    data = _recal_no_markduplicates(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 161, in _recal_no_markduplicates
    data = recalibrate.prep_recal(data)[0][0]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 42, in prep_recal
    platform, dbsnp_file, intervals, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 81, in _gatk_base_recalibrator
    if broad_runner.gatk_type() == "lite":
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 315, in gatk_type
    if LooseVersion(self.gatk_major_version()) > LooseVersion("2.3"):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 326, in gatk_major_version
    full_version = self.get_gatk_version()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 298, in get_gatk_version
    gatk_jar = self._get_jar("GenomeAnalysisTK", ["GenomeAnalysisTKLite"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 377, in _get_jar
    raise ValueError("Could not find jar %s in %s:%s" % (command, self._picard_ref, self._gatk_dir))
ValueError: Could not find jar GenomeAnalysisTK in /usr/local/share/java/picard:/usr/local/share/java/gatk
vagrant@vagrant-ubuntu-trusty-64:/vagrant/NA12878-exome-eval/work$
vagrant@vagrant-ubuntu-trusty-64:/vagrant/NA12878-exome-eval/work$
vagrant@vagrant-ubuntu-trusty-64:/vagrant/NA12878-exome-eval/work$
vagrant@vagrant-ubuntu-trusty-64:/vagrant/NA12878-exome-eval/work$
vagrant@vagrant-ubuntu-trusty-64:/vagrant/NA12878-exome-eval/work$
vagrant@vagrant-ubuntu-trusty-64:/vagrant/NA12878-exome-eval/work$ Write failed: Broken pipe
```

I checked past issues for solutions and couldn't find anything. My Vagrant VM has about 16Gb os memory and working with 8 cores.

Thanks

**Comment by roryk** [comment]
Hi Paulo,

Did you download the GATK JAR? We can't distribute GATK so you have to install that manually. Instructions for doing that are here:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#extra-software-and-data

**Comment by nuin** [comment]
I thought I did it but I will double check and close the issue then.

Thanks

**Comment by nuin** [comment]
I had done the update on the pipeline and didn't notice an error occurred at the time of update, on running again I got this issue:

```
[localhost] local: /usr/local/bin/brew tap --repair
Pruned 0 dead formulae
Warning: Could not create link for chapmanb/cbl/snap-aligner, as it
conflicts with homebrew/science/snap-aligner. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install chapmanb/cbl/snap-aligner
Tapped 465 formulae
```

The update completed fine this time. Thanks.

**Comment by roryk** [comment]
Hi Paulo,

Thanks for following up, hope that gets things going.
