### ISSUE TITLE
error: lumpy-sv 

### ISSUE THREAD

**Issue by szuszmok** [chapmanb/bcbio-nextgen#762]
Hi,

the following error occured during the installation:

[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit   lumpy-sv

Warning: local() encountered an error (return code 1) while executing 'export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit   lumpy-sv'

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 75, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 335, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 255, in configure_instance
    install_biolinux(options)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 279, in install_biolinux
    _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/fabfile.py", line 118, in _perform_install
    install_brew(flavor=flavor, automated=True)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/fabfile.py", line 308, in install_brew
    brew.install_packages(env, to_install=pkg_install)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 49, in install_packages
    _install_pkg(env, pkg_str, brew_cmd, ipkgs)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 87, in _install_pkg
    _install_pkg_latest(env, pkg, args, brew_cmd, ipkgs)
  File "/home/szandra/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 205, in _install_pkg_latest
    raise ValueError("Failed to install brew formula: %s" % pkg)
ValueError: Failed to install brew formula: lumpy-sv
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

Thank you for checking it!

**Comment by chapmanb** [comment]
Sorry about the issue. I'm not sure what exactly is causing this from the error message. Would you be able to run the failing install command with the verbose flag:
```
export CC=${CC:-which gcc} && export CXX=${CXX:-which g++} && /usr/local/bin/brew install -v --env=inherit lumpy-sv
```
This should provide more details about why it is failing. It would also be helpful to know what type of system you're installing on and your compiler (`gcc --version`). Thanks much.

**Comment by szuszmok** [comment]
Sorry, it doesn't need to be fixed, it was just a permission problem related to the path (/usr/local/Cellar). Thank you very much!
