### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

### ISSUE THREAD

**Issue by ggrimes** [chapmanb/bcbio-nextgen#764]
I get an SSL: CERTIFICATE_VERIFY_FAILED error when running the bcbio_nextgen_install.py command 

" python bcbio_nextgen_install.py  /export/users/bcbio/bcbn --tooldir=/export/users/bcbio/bcbn --isolate  --genomes GRCh37 --aligners bwa --aligners bowtie2 "

The error message is below.

Downloading http://pypi.gocept.com/packages/2.7/e/ecdsa/ecdsa-0.13-py2.py3-none-any.whl (86kB)
    100% |################################| 90kB 11.6MB/s
Requirement already satisfied (use --upgrade to upgrade): pycrypto!=2.4,>=2.1 in /export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages (from paramiko>=1.10->fabric)
Installing collected packages: ecdsa, paramiko, fabric

  Running setup.py install for fabric
    Installing fab script to /export/users/bcbio/bcbn/anaconda/bin
Successfully installed ecdsa-0.13 fabric-1.10.1 paramiko-1.15.2
Exception:
Traceback (most recent call last):
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 321, in run
    finder=finder, options=options, session=session):
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/req/req_file.py", line 31, in parse_requirements
    session=session,
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/download.py", line 396, in get_file_content
    resp = session.get(url)
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/download.py", line 365, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 43, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/export/users/bcbio/bcbn/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 36, in main
    bcbio = bootstrap_bcbionextgen(anaconda, args, remotes)
  File "bcbio_nextgen_install.py", line 69, in bootstrap_bcbionextgen
    subprocess.check_call([anaconda["pip"], "install", "-r", remotes["requirements"]])
  File "/opt/gridware/apps/gcc/python/2.7.6/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/export/users/bcbio/bcbn/anaconda/bin/pip', 'install', '-r', 'https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt']' returned non-zero exit status 2

Thanks

Graeme

**Comment by chapmanb** [comment]
Graeme;
Sorry about the install issues. This looks like some sort of system specific error loading certificates, although the pip issue thread doesn't yet resolve the underlying issue:

https://github.com/pypa/pip/issues/2130

I'm sure exactly what to suggest at this point beyond providing more information on your system and openssl setup and digging into Google to see if there are any tips/tweak specific to those versions. Sorry to not have a better answer but hope this helps some.

**Comment by chapmanb** [comment]
Graeme;
Thanks to some work debugging a similar issue on the GEMINI mailing list, we were finally able to push a fix for this problem. If you get the latest installer, it should set pip certificates to point at the ones installed via conda, so it no longer needs to correctly find system certificates. I hope if you get the latest installer and re-run it will now work cleanly. Sorry again about the problem and hope it works for you now.

**Comment by ggrimes** [comment]
Thanks that seems to have fixed the certificate problems for pip.
Graeme
