### ISSUE TITLE
qsignature 

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#777]
Should qsignature or any sample mixup / contamination tools be run on the joint pipeline? I see this in the logs:

`There is no qsignature for this species: GRCh37`

**Comment by lpantano** [comment]
Hi,

Is not implemented by default, you need to activate using `mixup_check`. More here: https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#quality-control

I will change the message because it shouldn't say that, is only that you don't have the option in the yaml file in this case.

thanks for notice this!

**Comment by dwaggott** [comment]
Great! The reason I ask is that sample mixups picked up by sex mismatch, plate infidelity, or blatant IBD irregularities are the norm. A few basic checks in the joint cohort calling would be very very helpful.

**Comment by dwaggott** [comment]
Okay, I accidently added `mixup_check: true` instead of `mixup_check: qsignature`. The joint pipeline crashed the controller and submission jobs. Maybe worth some config checking to avoid the whole pipeline going down.

This was in the log.

```
[2015-03-18T22:46Z] sh-5-15.local: Approx 95% complete for 20_2015-03-15_project_batch3_n24_fb_joint-sort-prep-downsample.bam
[2015-03-18T22:46Z] sh-5-15.local: Approx 100% complete for 20_2015-03-15_project_batch3_n24_fb_joint-sort-prep-downsample.bam
[2015-03-18T22:46Z] sh-5-15.local: Analysis complete for 20_2015-03-15_project_batch3_n24_fb_joint-sort-prep-downsample.bam
[2015-03-18T22:46Z] sh-5-15.local: bamtools stats : 2_04
[2015-03-18T22:46Z] sh-2-36.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 145, in pipeline_summary
    return ipython.zip_args(apply(qcsummary.pipeline_summary, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 61, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, data)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 114, in _run_qc_tools
    cur_metrics = qc_fn(bam_file, data, cur_qc_dir)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 628, in _run_qsignature_generator
    if mixup_check and mixup_check.startswith("qsignature"):
AttributeError: 'bool' object has no attribute 'startswith'
[2015-03-18T22:46Z] sh-2-36.local: Generating summary files: ['', '1_28']
...
2015-03-18 15:57:49.987 [IPClusterStop] Using existing profile dir: u'/scratch/PI/euan/projects/athletes/bcbio/project_batch3_n24_fb_joint/work/log/ipython'
2015-03-18 15:57:50.133 [IPClusterStop] Stopping cluster [pid=27392] with [signal=2]
2015-03-18 15:57:50.897 [IPClusterStop] Using existing profile dir: u'/scratch/PI/euan/projects/athletes/bcbio/project_batch3_n24_fb_joint/work/log/ipython'
2015-03-18 15:57:50.922 [IPClusterStop] Stopping cluster [pid=27392] with [signal=2]
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 81, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 192, in run
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 40, in generate_parallel
    sum_samples = run_parallel("pipeline_summary", samples)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 129, in run
    for data in view.map_sync(fn, items, track=False):
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 366, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<string>", line 2, in map
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 66, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in map
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 51, in save_ids
    ret = f(self, *args, **kwargs)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 1123, in map
    return pf.map(*sequences)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 271, in map
    ret = self(*sequences)
  File "<string>", line 2, in __call__
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 78, in sync_view_results
    return f(self, *args, **kwargs)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 254, in __call__
    return r.get()
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/asyncresult.py", line 118, in get
    raise self._exception
IPython.parallel.error.CompositeError: one or more exceptions from call to method: pipeline_summary
[3:apply]: AttributeError: 'bool' object has no attribute 'startswith'
[3:apply]: AttributeError: 'bool' object has no attribute 'startswith'
[3:apply]: AttributeError: 'bool' object has no attribute 'startswith'
[6:apply]: AttributeError: 'bool' object has no attribute 'startswith'
.... 20 more exceptions ...
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issue and thanks for the feedback. I pushed a fix to do better error checking of inputs to catch these issues up front. Please let us know if you run into any other problems.

**Comment by schelhorn** [comment]
I now (after b72dc4c) receive an error for 'kraken', which is supposed to accept a boolean (per the documentation), but is not part of the whitelist `ALG_ALLOW_BOOLEANS` in pipeline.run_info, resulting in `ValueError: Incorrect settings in 'algorithm' section for sample_01: kraken set as true`

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for the heads up and apologies for missing that one. If I missed any other's please do let us know -- the downside of having a separate validation step is being sure they are in sync. Thanks again.

**Comment by lpantano** [comment]
Hi,

as a follow up, the documentation was wrong, and kraken shouldn't accept booleans. I changed documentation to specify the correct values that should be `minikraken` or a `custom path`.

Sorry about that error in the docs. I fixed it, and hope now run again smoothly.
