### ISSUE TITLE
ImportError: cannot import name install

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#778]
Got this on error on the joint pipeline. Code was updated March 1st.

```
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 33, in <module>
    from bcbio import install, workflow
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 21, in <module>
    from bcbio.pipeline import genome
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 12, in <module>
    from bcbio import install, utils
ImportError: cannot import name install
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the problem. I inadvertantly checked in a circular import yesterday. The fix got pushed less than an hour later but you must have updated from development in that window. If you update again to the latest development it should hopefully work cleanly. If this broke things so you can't update automatically you can manually remove the `install` import from that file and it'll get things working again. Sorry about the problem.
