### ISSUE TITLE
Installing bcbio on a Cray XC30

### ISSUE THREAD

**Issue by luiceur** [chapmanb/bcbio-nextgen#779]
Hi Brad,

Our first go installing bcbio on a Cray XC30 reported us the following error:

```    
    failed to import Cython: /work/y07/y07/cse/python/modules/cython/0.21.1/lib/python2.7/site-packages/Cython-0.21.1-py2.7-linux-x86_64.egg/Cython/Compiler/Scanning.so: undefined symbol: PyUnicodeUCS2_Format
    
    error: Cython does not appear to be installed
    
    ----------------------------------------
    Command "/home1/z01/z01/lcebaman/EdinGen/bcbio/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-c9AkxW/pybedtools/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tUGGbo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-c9AkxW/pybedtools
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 259, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 36, in main
    bcbio = bootstrap_bcbionextgen(anaconda, args, remotes)
  File "bcbio_nextgen_install.py", line 73, in bootstrap_bcbionextgen
    subprocess.check_call([anaconda["pip"], "install", "-r", remotes["requirements"]])
  File "/work/y07/y07/cse/python/2.7.6/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home1/z01/z01/lcebaman/EdinGen/bcbio/anaconda/bin/pip', 'install', '-r', 'https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt']' returned non-zero exit status 1
```
Have you seen this problem before?

Regards,
Luis

**Comment by chapmanb** [comment]
Luis;
It looks like you have other Python libraries loaded into your PYTHONPATH which are compiled with a different version of Python that has an alternative Unicode representation (http://effbot.org/pyfaq/when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2.htm):
```
/work/y07/y07/cse/python/modules/cython/
```
bcbio installs everything needed and tries to isolate itself as much as possible, but often modules inject themselves into all other processes. You can either try unloading those modules, or unsetting environmental variables that might conflict:
```
unset PYTHONHOME
unset PYTHONPATH
```
This will hopefully let bcbio pick up the Cython installed with it instead of the module one and work cleanly. Hope this helps.

**Comment by luiceur** [comment]
Brad;
Thanks! That helped! It seems we are now at `bamtools`:
```
Warning: local() encountered an error (return code 1) while executing
 'export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} &&
export PERL5LIB=/home/z01/z01/lcebaman/EdinGen/bcbio/lib/perl5:${PERL5LIB} &&
 /home/z01/z01/lcebaman/EdinGen/bcbio/bin/brew install --env=inherit   bamtools'

Traceback (most recent call last):
  File "/home1/z01/z01/lcebaman/EdinGen/bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home1/z01/z01/lcebaman/EdinGen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 74, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/home1/z01/z01/lcebaman/EdinGen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 343, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 255, in configure_instance
    install_biolinux(options)
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 279, in install_biolinux
    _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/fabfile.py", line 118, in _perform_install
    install_brew(flavor=flavor, automated=True)
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/fabfile.py", line 308, in install_brew
    brew.install_packages(env, to_install=pkg_install)
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 49, in install_packages
    _install_pkg(env, pkg_str, brew_cmd, ipkgs)
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 87, in _install_pkg
    _install_pkg_latest(env, pkg, args, brew_cmd, ipkgs)
  File "/home1/z01/z01/lcebaman/EdinGen/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 205, in _install_pkg_latest
    raise ValueError("Failed to install brew formula: %s" % pkg)
ValueError: Failed to install brew formula: bamtools
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 259, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/work/y07/y07/cse/python/2.7.6/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home1/z01/z01/lcebaman/EdinGen/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/z01/z01/lcebaman/EdinGen/bcbio/', '--isolate', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Luis;
Thanks for the update. Offline, I got setup with an account on the machine and was able to look at some of the compile problems. It looks like the underlying issue is that it uses Cray specific compilers by default. After swapping to gcc (http://www.archer.ac.uk/documentation/user-guide/development.php#sec-4.5.1), everything builds cleanly for me. Here's what my `~/.bashrc` looks like:
```
unset PYTHONPATH
module load cmake
module swap PrgEnv-cray PrgEnv-gnu
export PATH=~/local/bin:$PATH
export LD_LIBRARY_PATH=~/local/lib:$LD_LIBRARY_PATH
export PERL5LIB=~/local/lib/perl5:$PERL5LIB
```
I did have problems with Perl, both module installation and VEP installation on the interactive nodes (`espp1` and `espp2`). I don't understand exactly what was wrong as the errors weren't very helpful, but they built fine on the head node if I re-ran there. There is a fully finished tool installation, without data, here: `/home/d75/d75/chapmanb/local`, so hopefully you'll be able to run the full build yourself cleanly after swapping the compiler. Hope this gets you up and running.

**Comment by luiceur** [comment]
Brad;

Thanks for getting hands on. Unfortunately for me I was already swapping cray with gnu, but I am still getting the same error building `bamtools`. Here is the command I use to install bcbio after loading and swapping modules:
```
 python bcbio_nextgen_install.py bcbio/ --tooldir=/home/z01/z01/lcebaman/EdinGen/bcbio/ --isolate --genomes GRCh37 --aligners bwa --aligners bowtie2
````

**Comment by chapmanb** [comment]
Luis;
Thanks for the report and sorry you're still having trouble. I'm a bit stumped as this built for me with that setup above. What node are you building on and I'll see if I can reproduce. Could you also try adding the verbose flag to the brew build to see if that provides more details:
```
export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} &&
 /home/z01/z01/lcebaman/EdinGen/bcbio/bin/brew install --env=inherit -v  bamtools'
```
Thanks much.

**Comment by luiceur** [comment]
Brad;
From the login node `eslogin004`:
```
./src/liblzma/delta -I../../src/liblzma/simple -I../../src/common -DTUKLIB_SYMBOL_PREFIX=lzma_ -isystem/home1/z01/z01/lcebaman/EdinGen/bcbio/include -pthread -fvisibility=hidden -Wall -Wextra -Wvla -Wformat=2 -Winit-self -Wmissing-include-dirs -Wstrict-aliasing -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wlogical-op -Waggregate-return -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wredundant-decls -Os -w -pipe -c common/easy_encoder.c  -fPIC -DPIC -o .libs/liblzma_la-easy_encoder.o
/opt/gcc/4.9.1/bin/gcc: fork: Resource temporarily unavailable
/opt/gcc/4.9.1/bin/gcc: fork: Resource temporarily unavailable
make[3]: *** [liblzma_la-filter_flags_encoder.lo] Error 1
make[3]: *** [liblzma_la-easy_encoder.lo] Error 1
../../libtool: fork: Resource temporarily unavailable
....
libtool: compile:  /opt/gcc/4.9.1/bin/gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. 
-I../../src/liblzma/api -I../../src/liblzma/common -I../../src/liblzma/check 
-I../../src/liblzma/lz -I../../src/liblzma/rangecoder -I../../src/liblzma/lzma
 -I../../src/liblzma/delta -I../../src/liblzma/simple 
-I../../src/common -DTUKLIB_SYMBOL_PREFIX=lzma_ 
-isystem/home1/z01/z01/lcebaman/EdinGen/bcbio/include -pthread -fvisibility=hidden 
-Wall -Wextra -Wvla -Wformat=2 -Winit-self -Wmissing-include-dirs -Wstrict-aliasing -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wlogical-op -Waggregate-return -Wstrict-prototypes -Wold-style-definition 
-Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wredundant-decls -Os -w -pipe -c common/hardware_physmem.c -o liblzma_la-hardware_physmem.o >/dev/null 2>&1
make[3]: Leaving directory `/tmp/xz-tekk1b/xz-5.2.0/src/liblzma'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/tmp/xz-tekk1b/xz-5.2.0/src/liblzma'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/tmp/xz-tekk1b/xz-5.2.0/src'
make: *** [install-recursive] Error 1
........
Error: xz 5.2.0 did not build
Logs:
     /home/z01/z01/lcebaman/Library/Logs/Homebrew/xz/01.configure
     /home/z01/z01/lcebaman/Library/Logs/Homebrew/xz/02.make
     /home/z01/z01/lcebaman/Library/Logs/Homebrew/xz/config.log

```

**Comment by chapmanb** [comment]
Luis;
I believe that's from trying to run this on the login node. It may be limiting processes so is not letting you fork. If you run on an interactive node (https://www.archer.ac.uk/documentation/user-guide/connecting.php#sec-2.1.2) it should compile cleanly without these issues. On the interactive node it will fail on VEP, but you can get through this by running the VEP install from a login node. Sorry for needing the back in forth but there is something strange about the setup causing issues that I didn't dig into. Hope this gets it compiled for you.

**Comment by luiceur** [comment]
Brad;
I can confirm that going back and forth from `espp1` I have managed to install bcbio. As you said, it failed at `VEP` on the `espp1` node, then I continued the installation back on the login node until it failed at `bwa`. Back to `espp1`, I could finished the installation.
Thanks for all your support Brad.

**Comment by roryk** [comment]
Thanks for following up! Closing this issue as its stale.
