### ISSUE TITLE
vt fails upgrade on dev 

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#787]
works after I cleared the brew cache.

```
[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/home/dwaggott/apps/lib/perl5:${PERL5LIB} && /home/dwaggott/apps/bin/brew install --env=inherit  --with-binary vt

Warning: local() encountered an error (return code 1) while executing 'export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/home/dwaggott/apps/lib/perl5:${PERL5LIB} && /home/dwaggott/apps/bin/brew install --env=inherit  --with-binary vt'

Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 76, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 353, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 255, in configure_instance
    install_biolinux(options)
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 279, in install_biolinux
    _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/fabfile.py", line 118, in _perform_install
    install_brew(flavor=flavor, automated=True)
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/fabfile.py", line 308, in install_brew
    brew.install_packages(env, to_install=pkg_install)
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 49, in install_packages
    _install_pkg(env, pkg_str, brew_cmd, ipkgs)
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 87, in _install_pkg
    _install_pkg_latest(env, pkg, args, brew_cmd, ipkgs)
  File "/share/PI/euan/apps/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 205, in _install_pkg_latest
    raise ValueError("Failed to install brew formula: %s" % pkg)
ValueError: Failed to install brew formula: vt
```

```
$ /home/dwaggott/apps/bin/brew install --env=inherit  --with-binary vt
==> Installing vt from chapmanb/homebrew-cbl
==> Downloading https://github.com/atks/vt/archive/10b7b2b.tar.gz
Already downloaded: /home/dwaggott/.cache/Homebrew/vt-2015-03-12.tar.gz
==> Downloading https://s3.amazonaws.com/cloudbiolinux/binaries/vt-centos5-2015-03-12
Already downloaded: /home/dwaggott/.cache/Homebrew/vt--vt-binary-2015-0
Error: SHA1 mismatch
Expected: ba3060c4074fa8f9b4d6d0ce38730ee856e1dad8
Actual: 87b7d1ab1cdf7df5a6807f46da1f7fe38705a773
Archive: /home/dwaggott/.cache/Homebrew/vt--vt-binary-2015-0
To retry an incomplete download, remove the file above.
```

```
$ /home/dwaggott/apps/bin/brew install --env=inherit  --with-binary vt
==> Installing vt from chapmanb/homebrew-cbl
==> Downloading https://github.com/atks/vt/archive/10b7b2b.tar.gz
Already downloaded: /home/dwaggott/.cache/Homebrew/vt-2015-03-12.tar.gz
==> Downloading https://s3.amazonaws.com/cloudbiolinux/binaries/vt-centos5-2015-03-12
######################################################################## 100.0%
/share/PI/euan/apps/Cellar/vt/2015-03-12: 4 files, 52M, built in 8 seconds
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issue. It looks like that date-based versioning on the binary confused brew and it truncated the binary name, erroring out because you have a previous download with the truncated name from the earlier version. I updated the formula to use a different binary name which is likes better and should avoid the problem. Thanks much for reporting this and all the information to track it down.
