### ISSUE TITLE
problem with fastqs

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#789]
I'm running the joint freebayes pipeline on a small batch of 24 exomes. It seems to be failing due to some issue with the fastqs. Anything obvious jump out? 

These were the fastqs merged using bcbio. The paths in the logs checked out fine.

```
[2015-03-15T00:17Z] sh-5-22.local: Testing minimum versions of installed programs
[2015-03-15T00:17Z] sh-2-21.local: Timing: alignment preparation
[2015-03-15T00:17Z] sh-2-21.local: ipython: prep_align_inputs
[2015-03-15T00:17Z] sh-2-21.local: ipython: disambiguate_split
[2015-03-15T00:17Z] sh-2-21.local: Timing: alignment
[2015-03-15T00:17Z] sh-2-21.local: ipython: process_alignment
[2015-03-15T00:17Z] sh-5-20.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 79, in process_alignment
    return ipython.zip_args(apply(sample.process_alignment, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 126, in process_alignment
    raise ValueError("Could not process input file: %s" % fastq1)
ValueError: Could not process input file: /home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_09_R1.fastq.gz
[2015-03-15T00:17Z] sh-5-1.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 79, in process_alignment
    return ipython.zip_args(apply(sample.process_alignment, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 126, in process_alignment
    raise ValueError("Could not process input file: %s" % fastq1)
ValueError: Could not process input file: /home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_14_R1.fastq.gz
[2015-03-15T00:17Z] sh-5-22.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 79, in process_alignment
    return ipython.zip_args(apply(sample.process_alignment, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 126, in process_alignment
    raise ValueError("Could not process input file: %s" % fastq1)
ValueError: Could not process input file: /home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_12_R1.fastq.gz
[2015-03-15T00:17Z] sh-3-11.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 79, in process_alignment
    return ipython.zip_args(apply(sample.process_alignment, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 126, in process_alignment
    raise ValueError("Could not process input file: %s" % fastq1)
ValueError: Could not process input file: /home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_27_R1.fastq.gz
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the uninformative error message. I pushed a fix to provide more useful feedback. There are two potential causes here:

- The path to the fastq file `/home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_27_R1.fastq.gz` is not correct.
- The input sample YAML file does not have an aligner specified.

To either of these help explain the problem?

**Comment by dwaggott** [comment]
Sigh, I had the align turned off.
