### ISSUE TITLE
bcbio memory calc error

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#790]
I got this trying when trying to submit to slurm. There was an error in my config. I recommend a bit more info in the error.

```
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 81, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 140, in run
    multiplier=alignprep.parallel_multiplier(samples)) as run_parallel:
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 43, in start
    max_multicore=max_multicore)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/resources.py", line 154, in calculate
    progs=", ".join(progs), memory=", ".join("%.2f" % x for x in all_memory),
TypeError: sequence item 0: expected string, bool found
/var/spool/slurmd/job1791115/slurm_script: line 59:  7319 Segmentation fault      bcbio_nextgen.py --timeout 10000 --retries 2 ../config/project_batch3_n24_fb_joint.yaml -t ipython -n 320 -q normal -s slurm -r "timelimit=2-00:00:00" -r "conmem=6"
```

My config looks like:

```
details:
- algorithm:
    aligner: true
    jointcaller: freebayes-joint
    mark_duplicates: true
    mixup_check: true
    platform: illumina
    quality_format: Standard
    realign: true
    recalibrate: true
    variantcaller: freebayes
  analysis: variant2
  description: '1_09'
  files:
  - /home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_09_R1.fastq.gz
  - /home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_09_R2.fastq.gz
  genome_build: GRCh37
- algorithm:
    aligner: true
    jointcaller: freebayes-joint
    mark_duplicates: true
    mixup_check: true
    platform: illumina
    quality_format: Standard
    realign: true
    recalibrate: true
    variantcaller: freebayes
  analysis: variant2
  description: '1_10'
  files:
  - /home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_10_R1.fastq.gz
  - /home/dwaggott/projects1/athletes/genotype/merged_fastqs/1_10_R2.fastq.gz
...
```

**Comment by chapmanb** [comment]
Daryl;
You currently have `aligner` set to true. It should be a specific aligner to use. If you want the standard, change it to `aligner: bwa`. Hope this gets it running.

**Comment by dwaggott** [comment]
Another dumb one. I got mixed up after I'd set it to `false` for another
pipeline.
