### ISSUE TITLE
ssl problem, cont...

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#791]
It appears that disabling ssl did not solve the issue completely (with reference to  upgrade fails #788 ).

It runs with no problem for a while and then exists with this error message below. 

However, when I run manually: 

/usr/local/share/bcbio/anaconda/bin/pip install -r https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt

Then tt works fine. I guess the installer is set to specifically use "/usr/local/share/bcbio/anaconda/ssl/cert.pem".  Not sure how to resolve this, how to update this specific certificate or use another certificate.

Kind regards,

Pär

Exception:
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 321, in run
    finder=finder, options=options, session=session):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/req/req_file.py", line 31, in parse_requirements
    session=session,
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/download.py", line 396, in get_file_content
    resp = session.get(url)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/download.py", line 365, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 43, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 53, in upgrade_bcbio
    subprocess.check_call(sudo_cmd + [pip_bin, "install", "-r", REMOTES["requirements"]])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/pip', 'install', '-r', 'https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt']' returned non-zero exit status 2

**Comment by chapmanb** [comment]
Pär;
Sorry about the issues, I'm not sure what is going on here. We added in the pointer to the locally installed certificates (instead of system certificates) to avoid this problem in #764 so I'm confused as to why it's now causing the issue. What type of system are you running on? Is there anything else about the SSL library setup between the systems where it works and doesn't work that might give us clues? Sorry, this is a bit out of my areas of expertise so just searching for potential starting points. Thanks for the help.

**Comment by parlar** [comment]
Tried different things, no success. Doing a complete reinstall now and hope that this will solve it.

**Comment by parlar** [comment]
The setup is identical between the machines, running ubuntu 14.04. However, the one that works is on a university network (no corporate firewall / filtering) and the other one is at the university hospital (with firewall/filtering but no proxy). I don't know how this might impact? I'll see if I can use the hospital's root certificate instead. (Just have to figure out how.)

**Comment by parlar** [comment]
I obviously don't know what I'm doing but it seems to work now. Just using the company root certificate did not work. However, when I linked /etc/ssl/certs/ca-certificates.crt with /usr/local/share/bcbio/anaconda/ssl/cert.pem the errors disappeared. With the caveat that the install is not yet finished.

**Comment by chapmanb** [comment]
Pär;
Apologies, I wish I understood more to help with this. If you find any generalizable solutions for your setup that would help, I'd be happy to roll them into bcbio.

**Comment by parlar** [comment]
No ... still fails! By redirecting the cert.pem link to "/etc/ssl/certs/ca-certificates.crt" the installation process  goes almost to completion.

But eventually it fails with the error enclosed below. Is there a way to disable the need to validate certificates?  I read that you can use "requests.get('https://www.reporo.com/', verify=False)", but I'm not sure how to modify the install script. I read also that one way is to create a new SSLContext. (I am aware of the security risks.) 

I'm getting desperate. 

INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa'], 'genomes': [{'rnaseq': True, 'dbsnp': True, 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}], 'install_uniref': False}'): Human (GRCh37)
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 239, in upgrade_bcbio_data
    remotes["genome_resources"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 256, in _upgrade_genome_resources
    r = requests.get(remote_url)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by chapmanb** [comment]
Sorry I wish I knew what to suggest. I guess your firewall is somehow modifying SSL requests causing these to fail, but I don't know why. If you want to hack around these issues, you could directly modify:
```
/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py
```
so the two `requests.get` calls there don't use validation, and then re-run the data download. I wish I had a more long term solution but hope this helps.

**Comment by parlar** [comment]
It worked. To summarize, the following steps were required for the installation process:

1. Start installation using bcbio_nextgen_install.py
When it fails:
2. Relink: usr/local/share/bcbio/anaconda/ssl/cert.pem to /etc/ssl/certs/ca-certificates.crt
3. Add verify=False to the two requests.get() in /usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py

I have contacted our network people at the hospital to see if something is wrong here, or if they have suggestions for changes in the bcbio-nextgen install script. 

//Pär

**Comment by chapmanb** [comment]
Pär;
Glad that worked, and thank you for following up. I pushed use of `verify=False` by default to those two requests calls. They're only pulling configuration and requirements files from GitHub so I'll prioritize it actually installing. I wish I knew a fix for the certificate issue but thanks for documenting the workaround. Thanks again for all the patience getting this running.
