### ISSUE TITLE
joint pipeline fails on gemini step

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#797]
Not sure what happened. Any ideas?

I restarted a failed pipeline using a bit of cleanup  i.e. `rm -rf gemini/ && rm -f freebayes/*-effects* && rm -f checkpoints_parallel/multicore2.done`. 

```
[2015-03-20T07:44Z] sh-3-34.local: Storing in local filesystem: /home/dwaggott/projects1/athletes/bcbio/project_batch3_n24_fb_joint/final/2015-03-15_project_batch3_n24_fb_joint/bcbio-nextgen-commands.log
[2015-03-20T07:44Z] sh-3-34.local: Storing in local filesystem: /home/dwaggott/projects1/athletes/bcbio/project_batch3_n24_fb_joint/final/2015-03-15_project_batch3_n24_fb_joint/project-summary.yaml
[2015-03-20T07:44Z] sh-3-34.local: Storing in local filesystem: /home/dwaggott/projects1/athletes/bcbio/project_batch3_n24_fb_joint/final/2015-03-15_project_batch3_n24_fb_joint/1_11-freebayes-joint.db
[2015-03-20T07:45Z] sh-3-34.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 312, in upload_samples
    return ipython.zip_args(apply(upload.from_sample, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 100, in zip_args
    return [msgpack.packb(x, use_single_float=True, use_bin_type=True) for x in args]
TypeError: 'NoneType' object is not iterable
[2015-03-20T07:45Z] sh-2-12.local: Storing in local filesystem: /home/dwaggott/projects1/athletes/bcbio/project_batch3_n24_fb_joint/final/2015-03-15_project_batch3_n24_fb_joint/bcbio-nextgen.log
[2015-03-20T07:45Z] sh-2-12.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 312, in upload_samples
    return ipython.zip_args(apply(upload.from_sample, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 100, in zip_args
    return [msgpack.packb(x, use_single_float=True, use_bin_type=True) for x in args]
TypeError: 'NoneType' object is not iterable
[2015-03-20T07:45Z] sh-5-31.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 312, in upload_samples
    return ipython.zip_args(apply(upload.from_sample, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 100, in zip_args
    return [msgpack.packb(x, use_single_float=True, use_bin_type=True) for x in args]
TypeError: 'NoneType' object is not iterable
2015-03-20 00:45:10.333 [IPClusterStop] Using existing profile dir: u'/scratch/PI/euan/projects/athletes/bcbio/project_batch3_n24_fb_joint/work/log/ipython'
2015-03-20 00:45:10.380 [IPClusterStop] Stopping cluster [pid=5459] with [signal=2]
2015-03-20 00:45:10.990 [IPClusterStop] Using existing profile dir: u'/scratch/PI/euan/projects/athletes/bcbio/project_batch3_n24_fb_joint/work/log/ipython'
2015-03-20 00:45:11.017 [IPClusterStop] Stopping cluster [pid=5459] with [signal=2]
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 193, in run
    run_parallel("upload_samples", [sample])
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 129, in run
    for data in view.map_sync(fn, items, track=False):
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 366, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<string>", line 2, in map
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 66, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in map
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 51, in save_ids
    ret = f(self, *args, **kwargs)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/view.py", line 1123, in map
    return pf.map(*sequences)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 271, in map
    ret = self(*sequences)
  File "<string>", line 2, in __call__
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 78, in sync_view_results
    return f(self, *args, **kwargs)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/remotefunction.py", line 254, in __call__
    return r.get()
  File "/home/dwaggott/.local/lib/python2.7/site-packages/IPython/parallel/client/asyncresult.py", line 118, in get
    raise self._exception
IPython.parallel.error.CompositeError: one or more exceptions from call to method: upload_samples
[3:apply]: TypeError: 'NoneType' object is not iterable
~
```

**Comment by chapmanb** [comment]
Daryl;
Thanks for the report and sorry about the problem. In the recent changes where we moved uploading to run within a distributed job, I didn't return the sample information so we can get an unexpected None message. I pushed a fix to resolve this so it will now finish cleanly. Practically, this was the last step in the processing so everything finished correctly on your previous run in terms of processing. Thanks again for letting us know about the issue.
