### ISSUE TITLE
Constraints violation when using coverage - claims non unique sample IDs

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#811]
I've made a quite large sample sheet (98 samples), ensuring unique sample names, yet chanjo when run on bcbio-nextgen chokes on some of them:

````
2015-04-03T08:18Z] uni31: Unexpected error
Traceback (most recent call last):
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 206, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 246, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect.py", line 110, in mutect_caller
    region, out_file_mutect)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect.py", line 93, in _mutect_call_prep
    params += _config_params(base_config, assoc_files, region, out_file)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect.py", line 58, in _config_params
    region = subset_variant_regions(variant_regions, region, out_file)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 171, in wrapper
    region_bed = f(variant_regions, region, out_file, items, do_merge)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 195, in subset_variant_regions
    with file_transaction(items[0] if items else None, subset_file) as tx_subset_file:
  File "/mnt/data/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 74, in file_transaction
    with _flatten_plus_safe(data_and_files) as (safe_names, orig_names):
  File "/mnt/data/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 126, in _flatten_plus_safe
    with tx_tmpdir(data, os.path.dirname(base_fname)) as tmpdir:
  File "/mnt/data/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/chanjo/importer/core.py", line 48, in import_bed
    chanjo_db.save()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/chanjo/store/core.py", line 155, in save
    self.session.commit()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 788, in commit
    self.transaction.commit()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 384, in commit
    self._prepare_impl()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 364, in _prepare_impl
    self.session.flush()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1985, in flush
    self._flush(objects)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2103, in _flush
    transaction.rollback(_capture_exception=True)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2067, in _flush
    flush_context.execute()
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 570, in _emit_insert_statements
    execute(statement, multiparams)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (IntegrityError) UNIQUE constraint failed: sample.id u'INSERT INTO sample (id, group_id, cutoff, extension, coverage_source, element_source, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' (u'20935-blood', u'20935-case_vs_blood', 4, 0, u'/mnt/data/projects/OV198/OV198/work/align/20935-blood/70_2015-04-02_OV198-sort.bam', None, '2015-04-03 09:46:18.104809', '2015-04-03 09:46:18.104837')
' returned non-zero exit status 1
```
I've checked and ``20935-blood`` appears exactly once in the samplesheet and in the YAML file. What could be happening here? I can reproduce it 100%.

(CCing @LMannarino, new entry in the group ;) since she's the one who saw it first)

**Comment by chapmanb** [comment]
Luca;
Sorry about the issue, I'm not sure what is going on here. It sounds like things are correct but I don't know enough about the internals of Chanjo to speculate about what might be going on. The traceback is also confusing, as it seems to be coming from an unrelated component: subsetting a BED file during MuTect calling.

If you look at the `log/bcbio-nextgen-commands.log` file when running in a single core mode, is it dying at a particular call to `chanjo annotate`? Is it possible we're feeding in the `20935-blood` sample multiple times when preparing the coverage database? Any other details about what is happening could help try and identify the underlying issue. Thanks much for the help debugging.

**Comment by lbeltrame** [comment]
Hello Brad,

> it possible we're feeding in the `20935-blood` sample multiple times when
> preparing the coverage database? Any other details about what is happening

It looks like it's being called twice on the same database. In case this 
helps, bear in mind that this sample is part of multiple batches (normal to 
several other tumor samples).

**Comment by lbeltrame** [comment]
Ok, a big SNAFU on our part. ;) The batch name was duplicated once and that caused issues. I wonder if you could warn if a batch name is used more than once when generating the YAML file?

**Comment by chapmanb** [comment]
Luca;
Glad you got it sorted out. If you can provide a small example of a YAML that causes the error we can see if there is a workaround for Chanjo or way to detect it. It's not possible to error out on duplicated batch names directly, since we use those to group sample and expect duplicates, but maybe there is a way to identify incorrectly specified batches. Thanks much.
