### ISSUE TITLE
freebayes unrecognized option

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#812]
Joint exome calling on 167 using freebayes. It doesn't seem to like the `-experimental-gls` flag.

```
[2015-04-06T00:39Z] sh-5-17.local: 2015-04-05 17:39:15 sh-5-17.local INFO [bcbio.run.itx] - freebayes: unrecognized option '--experimental-gls'
[2015-04-06T00:39Z] sh-5-17.local: 2015-04-05 17:39:15 sh-5-17.local INFO [bcbio.run.itx] - did you mean --use-best-n-alleles ?
[2015-04-06T00:39Z] sh-5-17.local: 2015-04-05 17:39:15 sh-5-17.local INFO [bcbio.run.itx] - terminate called after throwing an instance of 'std::out_of_range'
[2015-04-06T00:39Z] sh-5-17.local: 2015-04-05 17:39:15 sh-5-17.local INFO [bcbio.run.itx] -   what():  basic_string::substr
[2015-04-06T00:39Z] sh-5-17.local: 2015-04-05 17:39:15 sh-5-17.local INFO [bcbio.run.itx] - terminate called after throwing an instance of 'std::out_of_range'
[2015-04-06T00:39Z] sh-5-17.local: 2015-04-05 17:39:15 sh-5-17.local INFO [bcbio.run.itx] -   what():  basic_string::substr
[2015-04-06T00:39Z] sh-5-18.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'bcbio-variation-recall square -Xms250m -Xmx8g -XX:+UseSerialGC -c 16 -r 1:15510533-31019659 --caller freebayes /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/elite167-1_15510532_31019659.vcf.gz /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /scratch/PI/euan/pr
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doExecESC[m  ESC[32m        ForkJoinTask.java:  334ESC[m
    ESC[37mjava.util.concurrent.ForkJoinWorkerThread.execTaskESC[m  ESC[32mForkJoinWorkerThread.java:  604ESC[m
                ESC[37mjava.util.concurrent.ForkJoinPool.scanESC[m  ESC[32m        ForkJoinPool.java:  762ESC[m
                ESC[37mjava.util.concurrent.ForkJoinPool.workESC[m  ESC[32m        ForkJoinPool.java:  646ESC[m
         ESC[37mjava.util.concurrent.ForkJoinWorkerThread.runESC[m  ESC[32mForkJoinWorkerThread.java:  398ESC[m

2015-04-05 17:39:14 sh-5-18.local ERROR [bcbio.variation.recall.main] - 
ESC[1;31mjava.lang.RuntimeExceptionESC[m: ESC[3mjava.lang.RuntimeException: java.lang.Exception: Shell command failed: freebayes -b /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/prealign/1_02/1_02-ready.bam --variant-input /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1
                              what():  basic_string::substr
                            terminate called after throwing an instance of 'std::out_of_range'
                              what():  basic_string::substr
                            terminate called after throwing an instance of 'std::out_of_range'
                            did you mean --use-best-n-alleles ?
                            freebayes: unrecognized option '--experimental-gls'ESC[m
ESC[1;31mjava.lang.RuntimeExceptionESC[m: ESC[3mjava.lang.Exception: Shell command failed: freebayes -b /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/prealign/1_02/1_02-ready.bam --variant-input /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_30028506_31015312/1_02-1_30
                              what():  basic_string::substr
                            terminate called after throwing an instance of 'std::out_of_range'
                              what():  basic_string::substr

```

full log

**Comment by chapmanb** [comment]
Daryl;
Apologies, there were some parameter changes in the updated version of FreeBayes we recently validated. If you upgrade to the latest development version (`bcbio_nextgen.py upgrade -u development`) it has these fixes in place. We're hoping to have a new release in the next couple of days with these fixes. Sorry about the confusion.

**Comment by dwaggott** [comment]
Excellent!
