### ISSUE TITLE
AttributeError: 'module' object has no attribute 'dumps'

### ISSUE THREAD

**Issue by szuszmok** [chapmanb/bcbio-nextgen#820]
When I tried to run the bcbio on my local machine I got an error.
There are some 'json.py' in the subdirectories of '/usr/local/share/bcbio/anaconda' and one in the 'usr/lib64/python2.7/site-packages'. Probably this caused the following error:

Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 33, in <module>
    from bcbio import install, workflow
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 17, in <module>
    import requests
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 59, in <module>
    from .models import Request, Response, PreparedRequest
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/requests/models.py", line 49, in <module>
    json_dumps = json.dumps
AttributeError: 'module' object has no attribute 'dumps'

I didn't find here any reported issue like this, so maybe I did something wrong.
Sorry for the issue and thanks for any help!

**Comment by chapmanb** [comment]
Sorry about the issue. It sounds like you injected an old version of json into your system path somehow. The very latest version of bcbio development does even more work to try and avoid this, but to upgrade you might try the combination of commands in the docs to avoid the issue:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#importerrors

Hope this fixes it.

**Comment by szuszmok** [comment]
Thanks!
