### ISSUE TITLE
vcfintersect segfault

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#826]
I checked the vcf's referenced in the `vcfintersect`. One was only a header.

joint freebayes pipeline on 143

p.s. you can close most of the issues I have open

```
[2015-04-14T17:58Z] sh-5-15.local:     ESC[37mjava.util.concurrent.ForkJoinWorkerThread.execTaskESC[m  ESC[32mForkJoinWorkerThread.java:  604ESC[m
[2015-04-14T17:58Z] sh-5-15.local:                 ESC[37mjava.util.concurrent.ForkJoinPool.scanESC[m  ESC[32m        ForkJoinPool.java:  762ESC[m
[2015-04-14T17:58Z] sh-5-15.local:                 ESC[37mjava.util.concurrent.ForkJoinPool.workESC[m  ESC[32m        ForkJoinPool.java:  646ESC[m
[2015-04-14T17:58Z] sh-5-15.local:          ESC[37mjava.util.concurrent.ForkJoinWorkerThread.runESC[m  ESC[32mForkJoinWorkerThread.java:  398ESC[m
[2015-04-14T17:58Z] sh-5-15.local: 
[2015-04-14T17:58Z] sh-5-15.local: 2015-04-14 10:58:24 sh-5-15.local INFO [bcbio.run.itx] - /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_229266_258454/4_207-1_229266_258454-work/txtmp4750927248451122394/run.sh: line 3: 43869 Segmentation fault      vcfintersect -r /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -i /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/union/union-1_229266_258454.vcf.gz /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_229266_258454/4_207-1_229266_258454-work/region.vcf.gz
[2015-04-14T17:58Z] sh-5-15.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'bcbio-variation-recall square -Xms250m -Xmx8g -XX:+UseSerialGC -c 16 -r 1:1-15509804 --caller freebayes /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/elite167-1_0_15509804.vcf.gz /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/elite167-1_0_15509804.vcf-inputs.txt
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doJoinESC[m  ESC[32m        ForkJoinTask.java:  355ESC[m
                ESC[37mjava.util.concurrent.ForkJoinTask.joinESC[m  ESC[32m        ForkJoinTask.java:  639ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mfjjoinESC[m  ESC[32m             reducers.clj:   53ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doJoinESC[m  ESC[32m        ForkJoinTask.java:  355ESC[m
                ESC[37mjava.util.concurrent.ForkJoinTask.joinESC[m  ESC[32m        ForkJoinTask.java:  639ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mfjjoinESC[m  ESC[32m             reducers.clj:   53ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doJoinESC[m  ESC[32m        ForkJoinTask.java:  355ESC[m
                ESC[37mjava.util.concurrent.ForkJoinTask.joinESC[m  ESC[32m        ForkJoinTask.java:  639ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mfjjoinESC[m  ESC[32m             reducers.clj:   53ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                              ESC[33mclojure.core.reducers/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  357ESC[m
                            ESC[33mclojure.core.reducers/fn/ESC[1;33mGESC[m  ESC[32m             reducers.clj:   81ESC[m
          ESC[33mclojure.core.reducers/folder/reify/ESC[1;33mcoll-foldESC[m  ESC[32m             reducers.clj:  130ESC[m
                            ESC[33mclojure.core.reducers/ESC[1;33mfoldESC[m  ESC[32m             reducers.clj:   98ESC[m
                               ESC[33mbcbio.run.parallel/ESC[1;33mrmapESC[m  ESC[32m             parallel.clj:   17ESC[m
                               ESC[33mbcbio.run.parallel/ESC[1;33mrmapESC[m  ESC[32m             parallel.clj:   22ESC[m
               ESC[33mbcbio.variation.recall.square/ESC[1;33mby-regionESC[m  ESC[32m               square.clj:  220ESC[m
         ESC[33mbcbio.variation.recall.square/combine-vcfs/ESC[1;33mfnESC[m  ESC[32m               square.clj:  275ESC[m
        ESC[33mbcbio.variation.recall.merge/prep-by-region/ESC[1;33mfnESC[m  ESC[32m                merge.clj:  141ESC[m
                       ESC[33mclojure.core.reducers/map/fn/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  167ESC[m
                             ESC[33mclojure.core.protocols/ESC[1;33mfnESC[m  ESC[32m            protocols.clj:   79ESC[m
                           ESC[33mclojure.core.protocols/fn/ESC[1;33mGESC[m  ESC[32m            protocols.clj:   13ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mreduceESC[m  ESC[32m             reducers.clj:   79ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  330ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doExecESC[m  ESC[32m        ForkJoinTask.java:  334ESC[m
    ESC[37mjava.util.concurrent.ForkJoinWorkerThread.execTaskESC[m  ESC[32mForkJoinWorkerThread.java:  604ESC[m
                ESC[37mjava.util.concurrent.ForkJoinPool.scanESC[m  ESC[32m        ForkJoinPool.java:  762ESC[m
                ESC[37mjava.util.concurrent.ForkJoinPool.workESC[m  ESC[32m        ForkJoinPool.java:  646ESC[m
         ESC[37mjava.util.concurrent.ForkJoinWorkerThread.runESC[m  ESC[32mForkJoinWorkerThread.java:  398ESC[m

2015-04-14 10:58:24 sh-5-15.local ERROR [bcbio.run.itx] - 
ESC[1;31mjava.lang.ExceptionESC[m: ESC[3mShell command failed: vcfintersect -r /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -i /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/union/union-1_384136_422950.vcf.gz /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_384136_422950/2_02-1_384136_422950-work/region.vcf.gz | bgzip > /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_384136_422950/2_02-1_384136_422950-work/txtmp4808095487234696415/existing.vcf.gz
                          43834 Done                    | bgzip > /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_384136_422950/2_02-1_384136_422950-work/txtmp4808095487234696415/existing.vcf.gz
                     /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_384136_422950/2_02-1_384136_422950-work/txtmp4808095487234696415/run.sh: line 3: 43833 Segmentation fault      vcfintersect -r /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -i /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/union/union-1_384136_422950.vcf.gz /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_384136_422950/2_02-1_384136_422950-work/region.vcf.gzESC[m
                               ESC[33mbcbio.run.itx/ESC[1;33mcheck-runESC[m  ESC[32m                  itx.clj:  151ESC[m
   ESC[33mbcbio.variation.recall.square/intersect-variants/ESC[1;33mfnESC[m  ESC[32m               square.clj:   38ESC[m
      ESC[33mbcbio.variation.recall.square/ESC[1;33mintersect-variantsESC[m  ESC[32m               square.clj:   38ESC[m
     ESC[33mbcbio.variation.recall.square/sample-by-region/ESC[1;33mfnESC[m  ESC[32m               square.clj:  161ESC[m
        ESC[33mbcbio.variation.recall.square/ESC[1;33msample-by-regionESC[m  ESC[32m               square.clj:  158ESC[m
   ESC[33mbcbio.variation.recall.square/ESC[1;33msample-by-region-prepESC[m  ESC[32m               square.clj:  174ESC[m
            ESC[33mbcbio.variation.recall.square/by-region/ESC[1;33mfnESC[m  ESC[32m               square.clj:  215ESC[m
                       ESC[33mclojure.core.reducers/map/fn/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  167ESC[m
                             ESC[33mclojure.core.protocols/ESC[1;33mfnESC[m  ESC[32m            protocols.clj:   79ESC[m
                           ESC[33mclojure.core.protocols/fn/ESC[1;33mGESC[m  ESC[32m            protocols.clj:   13ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mreduceESC[m  ESC[32m             reducers.clj:   79ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  330ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doJoinESC[m  ESC[32m        ForkJoinTask.java:  355ESC[m
                ESC[37mjava.util.concurrent.ForkJoinTask.joinESC[m  ESC[32m        ForkJoinTask.java:  639ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mfjjoinESC[m  ESC[32m             reducers.clj:   53ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doExecESC[m  ESC[32m        ForkJoinTask.java:  334ESC[m
    ESC[37mjava.util.concurrent.ForkJoinWorkerThread.execTaskESC[m  ESC[32mForkJoinWorkerThread.java:  604ESC[m
                ESC[37mjava.util.concurrent.ForkJoinPool.scanESC[m  ESC[32m        ForkJoinPool.java:  762ESC[m
                ESC[37mjava.util.concurrent.ForkJoinPool.workESC[m  ESC[32m        ForkJoinPool.java:  646ESC[m
         ESC[37mjava.util.concurrent.ForkJoinWorkerThread.runESC[m  ESC[32mForkJoinWorkerThread.java:  398ESC[m

2015-04-14 10:58:24 sh-5-15.local INFO [bcbio.run.itx] - /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_229266_258454/4_207-1_229266_258454-work/txtmp4750927248451122394/run.sh: line 3: 43869 Segmentation fault      vcfintersect -r /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -i /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/union/union-1_229266_258454.vcf.gz /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/square/1/1_229266_258454/4_207-1_229266_258454-work/region.vcf.gz
' returned non-zero exit status 1
[2015-04-14T17:58Z] sh-5-15.local: Unexpected error
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 38, in _setup_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 294, in square_batch_region
    return ipython.zip_args(apply(joint.square_batch_region, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 123, in square_batch_region
    _square_batch_bcbio_variation(data, region, bam_files, vrn_files, out_file, "square")
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 173, in _square_batch_bcbio_variation
    do.run(cmd, "%s in region: %s" % (cmd, bamprep.region_to_gatk(region)))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'bcbio-variation-recall square -Xms250m -Xmx8g -XX:+UseSerialGC -c 16 -r 1:1-15509804 --caller freebayes /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/elite167-1_0_15509804.vcf.gz /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /scratch/PI/euan/projects/athletes/bcbio/project_elite167_fb_joint/work/joint/freebayes-joint/elite167/1/elite167-1_0_15509804.vcf-inputs.txt
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doJoinESC[m  ESC[32m        ForkJoinTask.java:  355ESC[m
                ESC[37mjava.util.concurrent.ForkJoinTask.joinESC[m  ESC[32m        ForkJoinTask.java:  639ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mfjjoinESC[m  ESC[32m             reducers.clj:   53ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doJoinESC[m  ESC[32m        ForkJoinTask.java:  355ESC[m
                ESC[37mjava.util.concurrent.ForkJoinTask.joinESC[m  ESC[32m        ForkJoinTask.java:  639ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mfjjoinESC[m  ESC[32m             reducers.clj:   53ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m
                   ESC[33mclojure.core.reducers/foldvec/fc/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  335ESC[m
                                 ESC[37mclojure.lang.AFn.callESC[m  ESC[32m                 AFn.java:   18ESC[m
ESC[37mjava.util.concurrent.ForkJoinTask$AdaptedCallable.execESC[m  ESC[32m        ForkJoinTask.java: 1288ESC[m
              ESC[37mjava.util.concurrent.ForkJoinTask.doJoinESC[m  ESC[32m        ForkJoinTask.java:  355ESC[m
                ESC[37mjava.util.concurrent.ForkJoinTask.joinESC[m  ESC[32m        ForkJoinTask.java:  639ESC[m
                          ESC[33mclojure.core.reducers/ESC[1;33mfjjoinESC[m  ESC[32m             reducers.clj:   53ESC[m
                      ESC[33mclojure.core.reducers/foldvec/ESC[1;33mfnESC[m  ESC[32m             reducers.clj:  340ESC[m
                        ESC[33mclojure.core.reducers/ESC[1;33mfjinvokeESC[m  ESC[32m             reducers.clj:   48ESC[m
                         ESC[33mclojure.core.reducers/ESC[1;33mfoldvecESC[m  ESC[32m             reducers.clj:  336ESC[m

**Comment by dwaggott** [comment]
Looks like the pipeline continues without dying. Do you think regular `vcfintersect` segfaults, where one table has data and the other doesn't, will ultimately result in data loss?

**Comment by chapmanb** [comment]
Daryl;
Thanks for the detailed bug report. I pushed a fix, so if you update tools (`bcbio_nextgen.py upgrade --tools`) the latest bcbio.variation.recall will avoid doing a vcfintersect if one of the files is empty.

I wouldn't be too worried about data loss here since the fix for this is to skip doing an intersection and return an empty file, but you can re-run and bcbio should pick up if anything did not complete correctly.

Sorry about the problem and thanks again.
