### ISSUE TITLE
Installation of bcbio-nextgen fails because cloudbiolinux fails to automatically determine Linux distribution on machine with CentOS 7

### ISSUE THREAD

**Issue by kajetanb** [chapmanb/bcbio-nextgen#830]
Hi,
during the "isolate" installation of bcbio-nextgen I got the error
```
INFO: <cloudbio.flavor.Flavor instance at 0x7f0e5bb20248>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /opt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 76, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 353, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/opt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/opt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 101, in _setup_vm
    _setup_cloudbiolinux(options)
  File "/opt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 193, in _setup_cloudbiolinux
    _configure_fabric_environment(env, flavor, fabricrc_loader=fabricrc_loader)
  File "/opt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/utils.py", line 93, in _configure_fabric_environment
    _setup_distribution_environment(ignore_distcheck=ignore_distcheck)
  File "/opt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/distribution.py", line 33, in _setup_distribution_environment
    env.distribution = _determine_distribution(env)
  File "/opt/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/distribution.py", line 303, in _determine_distribution
    raise Exception("Attempt to automatically determine Linux distribution of target machine failed, please manually specify distribution in fabricrc.txt")
Exception: Attempt to automatically determine Linux distribution of target machine failed, please manually specify distribution in fabricrc.txt
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 259, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/opt/bcbio/', '--isolate', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```
I saw that people had this issue with other OS and from what I understand from fabricrc.txt is that there should be an option for centos but maybe there was some change in in CentOS 7?

Here the output of  cat /etc/*release
```
CentOS Linux release 7.1.1503 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core) 
CentOS Linux release 7.1.1503 (Core) 
```
Thanks a lot!

**Comment by chapmanb** [comment]
Thanks much for the heads up on the problem. I pushed a fix for this that should identify this correctly as CentOS. If you remove any temporary download directories (`rm -rf tmpbcbio-install`) and re-run it should hopefully pick it up correctly. Sorry about the problem and hope this fixes it for you.

**Comment by kajetanb** [comment]
Great! It's working now. Thanks a lot!
