### ISSUE TITLE
Error: uncompressed size is too large

### ISSUE THREAD

**Issue by rronen** [chapmanb/bcbio-nextgen#837]
Seeing this on a high coverage tumor/normal variant calling run (normal BAM~50GB; tumor BAM~56GB) during the first stage converting BAM to FASTQs.

```
[V] 140 28.5913MB/s     120159
[V] 141 28.5877MB/s     120144
[V] 142 28.5775MB/s     120101
[V] 143 28.58MB/s       120112
BgzfInflateBase::readData(): uncompressed size is too large
/home/ubuntu/bcbio_tooldir/Cellar/biobambam/0.0.182/libexec/bin/../lib/libmaus.so.0(_ZN7libmaus4util10StackTraceC2Ev+0x54) [0x7fd324b290e4]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq(_ZN7libmaus9exception16LibMausExceptionC2Ev+0x20) [0x417280]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x427213]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x4274c3]
/home/ubuntu/bcbio_tooldir/Cellar/biobambam/0.0.182/libexec/bin/../lib/libstdc++.so.6(_ZNSt15basic_streambufIcSt11char_traitsIcEE6xsgetnEPcl+0xb5) [0x7fd324669155]
/home/ubuntu/bcbio_tooldir/Cellar/biobambam/0.0.182/libexec/bin/../lib/libstdc++.so.6(_ZNSi4readEPcl+0x5b) [0x7fd32464892b]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x430952]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x45bd3b]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x460188]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x41214b]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x413f61]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x40b902]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fd32240bea5]
/home/ubuntu/bcbio_tooldir/bin/bamtofastq() [0x40d412]

' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/ubuntu/bcbio_tooldir/bin/bcbio_nextgen.py", line 216, in <module>
    main(**kwargs)
  File "/home/ubuntu/bcbio_tooldir/bin/bcbio_nextgen.py", line 42, in main
    run_main(**kwargs)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 81, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 145, in run
    samples = run_parallel("prep_align_inputs", samples)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 653, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 138, in __init__
    self.results = func(*args, **kwargs)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 149, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 39, in prep_align_inputs
    return alignprep.create_inputs(*args)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 36, in create_inputs
    ready_files = _prep_grabix_indexes(data["files"], data["dirs"], data)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 158, in _prep_grabix_indexes
    out = _bgzip_from_bam(in_files[0], dirs, data["config"])
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 333, in _bgzip_from_bam
    log_error=False)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/ubuntu/bcbio_datadir/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/ubuntu/bcbio_tooldir/bin/bamtofastq filename=/bcbio_work/ubuntu/encrypted/input/12-1-B2.12.15-10170.2-39307.bina.alignment.recal.bam T=/bcbio_work/ubuntu/encrypted/work/align_prep/tx/tmpIzSWJz/12-1-B2.12.15-10170.2-39307.bina.alignment.recal-1.fq-sort F=>(/home/ubuntu/bcbio_tooldir/bin/bgzip -c /dev/stdin > /bcbio_work/ubuntu/encrypted/work/align_prep/tx/tmpIzSWJz/12-1-B2.12.15-10170.2-39307.bina.alignment.recal-1.fq.gz) F2=>(/home/ubuntu/bcbio_tooldir/bin/bgzip -c /dev/stdin > /bcbio_work/ubuntu/encrypted/work/align_prep/12-1-B2.12.15-10170.2-39307.bina.alignment.recal-2.fq.gz) S=/dev/null O=/dev/null O2=/dev/null collate=1 colsbs=15032385536
```

Any ideas on how to fix or work-around this would be most welcome.

**Comment by chapmanb** [comment]
Roy;
Sorry about the issue. The error looks like something is going wrong with reading the BAM file. Do other tools like samtools read this file correctly if you do something like:
```
samtools view /bcbio_work/ubuntu/encrypted/input/12-1-B2.12.15-10170.2-39307.bina.alignment.recal.bam > /dev/null
```
Hopefully that helps explain the issue.

**Comment by rronen** [comment]
Err.. yes, thanks for that and sorry for being a bit trigger happy.
