### ISSUE TITLE
IndexError with GEMINI and joint calling via FreeBayes

### ISSUE THREAD

**Issue by LMannarino** [chapmanb/bcbio-nextgen#843]
CC @lbeltrame 

Latest master.

Traceback: 

````
[2015-05-07T13:50Z] uni17: Traceback (most recent call last):
[2015-05-07T13:50Z] uni17:   File "/mnt/data/bcbio/anaconda/bin/gemini", line 6, in <module>
[2015-05-07T13:50Z] uni17:     gemini.gemini_main.main()
[2015-05-07T13:50Z] uni17:   File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1076, in main
[2015-05-07T13:50Z] uni17:     args.func(parser, args)
[2015-05-07T13:50Z] uni17:   File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 271, in loadchunk_fn
[2015-05-07T13:50Z] uni17:     gemini_load_chunk.load(parser, args)
[2015-05-07T13:50Z] uni17:   File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 733, in load
[2015-05-07T13:50Z] uni17:     gemini_loader.populate_from_vcf()
[2015-05-07T13:50Z] uni17:   File "/mnt/data/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 130, in populate_from_vcf
[2015-05-07T13:50Z] uni17:     for var in self.vcf_reader:
[2015-05-07T13:50Z] uni17:   File "parser.pyx", line 1063, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:19124)
[2015-05-07T13:50Z] uni17:   File "parser.pyx", line 1112, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19838)
[2015-05-07T13:50Z] uni17:   File "parser.pyx", line 869, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16607)
[2015-05-07T13:50Z] uni17: IndexError: list index out of range
````

**Comment by chapmanb** [comment]
Laura;
Sorry about the issue. This looks like something internal to GEMINI -- do you know what version of gemini you're running (`gemini --version`)? This looks like this bug:

https://github.com/arq5x/gemini/issues/431

which should be fixed in the most recent GEMINI (0.14.0) and cyvcf (0.1.14). Hope this helps sort it out.

**Comment by LMannarino** [comment]
````
gemini --version
gemini 0.14.0
````

cyvcf:

````
pip show cyvcf
---
Metadata-Version: 1.1
Name: cyvcf
Version: 0.1.14
Summary: A fast Python library for VCF files using Cython for speed.
Home-page: none
Author: Aaron Quinlan, James Casbon, John Dougherty, Martin Vermaat, Brent Pedersen
Author-email: arq5x@virginia.edu
License: UNKNOWN
Location: /mnt/data/bcbio/anaconda/lib/python2.7/site-packages
Requires: 
````

**Comment by chapmanb** [comment]
Laura;
Sorry this is still causing issues even with the latest version. Is it possible to share the problem VCF? If you could post it on dropbox and share via e-mail I could try to dig into why it fails in this input files. Thanks much.

**Comment by schelhorn** [comment]
I now have the same problem, after [my last issue with GEMINI](https://github.com/chapmanb/bcbio-nextgen/issues/841) was resolved. I will try to investigate.

**Comment by schelhorn** [comment]
Alright, the problem seems to be tightly linked to [issue 841](https://github.com/chapmanb/bcbio-nextgen/issues/841) indeed. The cyvcf parser stumbles at reading vcf entries that have empty fields `;;` (see issue 841, long read). The empty field seem to originate from a missing `EPR` entry. For whatever reason, FreeBayes analyses or downstream merging seem to generate these non-compliant empty VCF fields if a variant row does not have a specific field. Upon removal of the `;;` entity, the parser can read the VCF file successfully.

Minimal example (with full header and two variant rows; the first row with `;;` triggers the error. Upon replacement of `;;` with `;`, the file is parsed just fine. From the second row, it can be inferred that the `EPR` may be the reason for the malformed empty field)

```
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=AO,Number=A,Type=Integer,Description="Alternate allele observation count">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood, log10-scaled likelihoods of the data given the called genotype for each possible genotype generated from the reference and alternate alleles given the sample ploidy">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=QA,Number=A,Type=Integer,Description="Sum of quality of the alternate observations">
##FORMAT=<ID=QR,Number=1,Type=Integer,Description="Sum of quality of the reference observations">
##FORMAT=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count">
##INFO=<ID=AB,Number=A,Type=Float,Description="Allele balance at heterozygous sites: a number between 0 and 1 representing the ratio of reads showing the reference allele to all reads, considering only reads from individuals called as heterozygous">
##INFO=<ID=ABP,Number=A,Type=Float,Description="Allele balance probability at heterozygous sites: Phred-scaled upper-bounds estimate of the probability of observing the deviation between ABR and ABA given E(ABR/ABA) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AO,Number=A,Type=Integer,Description="Alternate allele observations, with partial observations recorded fractionally">
##INFO=<ID=CIGAR,Number=A,Type=String,Description="The extended CIGAR representation of each alternate allele, with the exception that '=' is replaced by 'M' to ease VCF parsing.  Note that INDEL alleles do not have the first matched base (which is provided by default, per the spec) referred to by the CIGAR.">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=DPB,Number=1,Type=Float,Description="Total read depth per bp at the locus; bases in reads overlapping / bases in haplotype">
##INFO=<ID=DPRA,Number=A,Type=Float,Description="Alternate allele depth ratio.  Ratio between depth in samples with each called alternate allele and those without.">
##INFO=<ID=EPP,Number=A,Type=Float,Description="End Placement Probability: Phred-scaled upper-bounds estimate of the probability of observing the deviation between EL and ER given E(EL/ER) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=EPPR,Number=1,Type=Float,Description="End Placement Probability for reference observations: Phred-scaled upper-bounds estimate of the probability of observing the deviation between EL and ER given E(EL/ER) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=GTI,Number=1,Type=Integer,Description="Number of genotyping iterations required to reach convergence or bailout.">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="allele length">
##INFO=<ID=MEANALT,Number=A,Type=Float,Description="Mean number of unique non-reference allele observations per sample with the corresponding alternate alleles.">
##INFO=<ID=MQM,Number=A,Type=Float,Description="Mean mapping quality of observed alternate alleles">
##INFO=<ID=MQMR,Number=1,Type=Float,Description="Mean mapping quality of observed reference alleles">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=NUMALT,Number=1,Type=Integer,Description="Number of unique non-reference alleles in called genotypes at this position.">
##INFO=<ID=ODDS,Number=1,Type=Float,Description="The log odds ratio of the best genotype combination to the second-best.">
##INFO=<ID=OLD_VARIANT,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding">
##INFO=<ID=PAIRED,Number=A,Type=Float,Description="Proportion of observed alternate alleles which are supported by properly paired read fragments">
##INFO=<ID=PAIREDR,Number=1,Type=Float,Description="Proportion of observed reference alleles which are supported by properly paired read fragments">
##INFO=<ID=PAO,Number=A,Type=Float,Description="Alternate allele observations, with partial observations recorded fractionally">
##INFO=<ID=PQA,Number=A,Type=Float,Description="Alternate allele quality sum in phred for partial observations">
##INFO=<ID=PQR,Number=1,Type=Float,Description="Reference allele quality sum in phred for partial observations">
##INFO=<ID=PRO,Number=1,Type=Float,Description="Reference allele observation count, with partial observations recorded fractionally">
##INFO=<ID=QA,Number=A,Type=Integer,Description="Alternate allele quality sum in phred">
##INFO=<ID=QR,Number=1,Type=Integer,Description="Reference allele quality sum in phred">
##INFO=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count, with partial observations recorded fractionally">
##INFO=<ID=RPL,Number=A,Type=Float,Description="Reads Placed Left: number of reads supporting the alternate balanced to the left (5') of the alternate allele">
##INFO=<ID=RPP,Number=A,Type=Float,Description="Read Placement Probability: Phred-scaled upper-bounds estimate of the probability of observing the deviation between RPL and RPR given E(RPL/RPR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RPPR,Number=1,Type=Float,Description="Read Placement Probability for reference observations: Phred-scaled upper-bounds estimate of the probability of observing the deviation between RPL and RPR given E(RPL/RPR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RPR,Number=A,Type=Float,Description="Reads Placed Right: number of reads supporting the alternate balanced to the right (3') of the alternate allele">
##INFO=<ID=RUN,Number=A,Type=Integer,Description="Run length: the number of consecutive repeats of the alternate allele in the reference genome">
##INFO=<ID=SAF,Number=A,Type=Integer,Description="Number of alternate observations on the forward strand">
##INFO=<ID=SAP,Number=A,Type=Float,Description="Strand balance probability for the alternate allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SAF and SAR given E(SAF/SAR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=SAR,Number=A,Type=Integer,Description="Number of alternate observations on the reverse strand">
##INFO=<ID=SRF,Number=1,Type=Integer,Description="Number of reference observations on the forward strand">
##INFO=<ID=SRP,Number=1,Type=Float,Description="Strand balance probability for the reference allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SRF and SRR given E(SRF/SRR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=SRR,Number=1,Type=Integer,Description="Number of reference observations on the reverse strand">
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of allele, either snp, mnp, ins, del, or complex.">
##INFO=<ID=technology.illumina,Number=A,Type=Float,Description="Fraction of observations supporting the alternate observed in reads from illumina">
##commandline="/cluster/software/bcbio_dev/app/bin/freebayes -f /cluster/software/bcbio_dev/lib/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -b /auto/USERNAME/mbio_wes_2013-11/dataset1_comp1/align/SAMPLENAME-001/GRCh37/1_150429_mbio_wes_2013-11_dataset1_comp1-sort.bam --ploidy 2 --targets /auto/USERNAME/mbio_wes_2013-11/dataset1_comp1/freebayes/1/SAMPLENAME-001-1_0_15541935-raw-regions-nolcr.bed --min-repeat-entropy 1 --min-alternate-fraction 0.1 --pooled-discrete --pooled-continuous --genotype-qualities --report-genotype-likelihood-max --allele-balance-priors-off"
##fileDate=20150508
##filter="QUAL > 5"
##phasing=none
##reference=/cluster/software/bcbio_dev/lib/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
##source=freeBayes v0.9.21-7-g7dd41db
##VEP=v79 cache=/cluster/software/bcbio_dev/lib/genomes/Hsapiens/GRCh37/vep/homo_sapiens/79_GRCh37 db=.
##contig=<ID=1>
##contig=<ID=2>
##contig=<ID=3>
##contig=<ID=4>
##contig=<ID=5>
##contig=<ID=6>
##contig=<ID=7>
##contig=<ID=8>
##contig=<ID=9>
##contig=<ID=10>
##contig=<ID=11>
##contig=<ID=12>
##contig=<ID=13>
##contig=<ID=14>
##contig=<ID=15>
##contig=<ID=16>
##contig=<ID=17>
##contig=<ID=18>
##contig=<ID=19>
##contig=<ID=20>
##contig=<ID=21>
##contig=<ID=22>
##contig=<ID=X>
##FILTER=<ID=FBQualDepth,Description="Set if true: (AF[0] <= 0.5 && (DP < 4 || (DP < 13 && %QUAL < 10))) || (AF[0] > 0.5 && (DP < 4 && %QUAL < 50))">
##bcftools_filterVersion=1.2+htslib-1.2.1
##bcftools_filterCommand=filter -O v -T /auto/USERNAME/mbio_wes_2013-11/dataset1_comp1/bedprep/Agilent_SureSelect_Human_All_Exon_V1_38mbp_GRCh37_Regions.bed.gz --soft-filter FBQualDepth -e '(AF[0] <= 0.5 && (DP < 4 || (DP < 13 && %QUAL < 10))) || (AF[0] > 0.5 && (DP < 4 && %QUAL < 50))' -m + /auto/USERNAME/mbio_wes_2013-11/dataset1_comp1/freebayes/SAMPLENAME-001-vepeffects-ploidyfix.vcf.gz
##INFO=<ID=EPR,Number=.,Type=String,Description="Prioritization based on external annotations">
##bcftools_annotateVersion=1.2+htslib-1.2.1
##bcftools_annotateCommand=annotate -a /auto/USERNAME/mbio_wes_2013-11/dataset1_comp1/freebayes/SAMPLENAME-001-vepeffects-ploidyfix-filter-priority.tsv.gz -h /tmp/bcbiotx/2bccbb87-7840-4989-afc6-3441a88d51fe/tmpzltkCQ/SAMPLENAME-001-vepeffects-ploidyfix-filter-priority-repeatheader.txt -c CHROM,FROM,TO,REF,ALT,INFO/EPR /auto/USERNAME/mbio_wes_2013-11/dataset1_comp1/freebayes/SAMPLENAME-001-vepeffects-ploidyfix-filter.vcf.gz
##FILTER=<ID=LowPriority,Description="Set if true: EPR[*] != pass">
##bcftools_filterCommand=filter -m + -s LowPriority -e 'EPR[*] != "pass"'
##INFO=<ID=OLD_MULTIALLELIC,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding">
##VEP=v79 cache=/cluster/software/bcbio_dev/lib/genomes/Hsapiens/GRCh37/vep/homo_sapiens/79_GRCh37 db=.
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Consequence|Codons|Amino_acids|Gene|SYMBOL|Feature|EXON|PolyPhen|SIFT|Protein_position|BIOTYPE|CANONICAL|CCDS|LoF|LoF_filter|LoF_flags">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLENAME-001
1	69270	.	A	G	7.33	FBQualDepth	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=2;CIGAR=1X;DP=2;DPB=2;DPRA=0;EPP=7.35324;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=13;MQMR=0;NS=1;NUMALT=1;ODDS=1.48215;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=76;QR=0;RO=0;RPL=0;RPP=7.35324;RPPR=0;RPR=2;RUN=1;SAF=2;SAP=7.35324;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.illumina=1;;CSQ=synonymous_variant|tcA/tcG|S|ENSG00000186092|OR4F5|ENST00000335137|1/1|||60/305|protein_coding|YES|CCDS30547.1|||SINGLE_EXON	GT:GQ:DP:RO:QR:AO:QA:GL	1/1:7:2:0:0:2:76:-2.44987,-0.60206,0
1	69511	.	A	G	2413.8	LowPriority	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=123;CIGAR=1X;DP=124;DPB=124;DPRA=0;EPP=9.38348;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=28.9187;MQMR=0;NS=1;NUMALT=1;ODDS=89.8623;PAIRED=0.99187;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=3917;QR=0;RO=0;RPL=54;RPP=6.98251;RPPR=0;RPR=69;RUN=1;SAF=33;SAP=60.3689;SAR=90;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.illumina=1;EPR=esp,exac;CSQ=missense_variant|Aca/Gca|T/A|ENSG00000186092|OR4F5|ENST00000335137|1/1|benign(0.003)|tolerated(0.82)|141/305|protein_coding|YES|CCDS30547.1|||SINGLE_EXON	GT:GQ:DP:RO:QR:AO:QA:GL	1/1:154:124:0:0:123:3917:-251.75,-37.0267,0
```

**Comment by schelhorn** [comment]
Following my analysis of issue 841, it may be the case that `vep` introduces these fields if a field is defined in the header of an input VCF file but a given variant row does not have an entry for that field. Since `GATK` complains upon reading such files with empty fields, and the VCF 4.0 spec does not seem to cover their use, it seems to me as if empty fields are not standard-compliant. So it may be an issue in `vep`. In any case, it would make sense for either `cyvcf` to be able to parse such malformed files, or for bcbio to `sed`-replace `;;` with `;` in all variant rows (using a regex) to be able to run analyses again. Since `;` is a protected symbol in VCF, such a search-replace should be safe.

**Comment by schelhorn** [comment]
If going the `cyvcf` route seems to be sufficiently elegant, the fix would probably have to be made around [here in the tokenizer](https://github.com/arq5x/cyvcf/blob/master/cyvcf/parser.pyx#L852) where empty fields would have to be omitted.

**Comment by schelhorn** [comment]
I my analysis was about right  (which is not necessarily the case), the problematic code in `vep` may be [around here](https://github.com/Ensembl/ensembl-tools/blob/release/79/scripts/variant_effect_predictor/variant_effect_predictor.pl#L2216). Perhaps someone with better perl mastery than I (so about anyone) could look into the issue and see, if indeed empty fields are generated under any circumstances, especially for header INFO definitions that do not have counterparts in INFO fields of the actual variant rows.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the additional details and diagnosis. I pushed a fix which removes the empty fields and would love to know if this resolves your issue. I could re-create the empty fields with a bit of manual work and this does seem to fix it. It appears to happen if you're running tumor only samples so prioritization is introduced, and have multi-alleles that need to be split. In that case `vt` leaves an empty EPR field which is propagated through VEP and then causes issues. It seems like the sed fix is the least work to fix this, so hopefully it resolves it for everyone.

Laura, let us know if this fixes/doesn't fix the issue for you as well. Sven-Eric, thanks again for all the help debugging.

**Comment by schelhorn** [comment]
Great, thanks! Your diagnosis seems to be correct and I'll give it a spin for functional effectivity. One nit-picky comment, though: perhaps it is better to use `sed '/^#/! s/;;/;/g'` for the `sed` replace, since `;` only is a protected symbol in the actual _variant rows_ and seems to a legal string expression in the VCF _header_, the latter of which may be erroneously be affected by b17ebd4bd8f4f674c4826d0f2dda63755bf350af. The modified replace string above will only replace the problematic sequence in lines that are _not_ header lines (i.e., do not start with the hash).

Should we try to propagate the issue to `vep`, or could anyone with perl knowledge look at the `vep` sources as suggested above?

**Comment by schelhorn** [comment]
That seems to have fixed it, Brad. Thanks again. You may close the issue if no further action concerning `vep` should be taken. As a side note, I now get `sqlite3.OperationalError: disk I/O error` on the chunks, though. Perhaps the NFS/sqlite bug in GEMINI is creeping up again - I'll investigate that later. Does bcbio already play nice with GEMINI concerning the temp directory NFS workround?

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for the sed level-up. Glad this is working for you. @LMannarino -- does this fix your issue as well? If so, happy to close.

The next GEMINI release will use temporary directories correctly, as I checked in fixes to use temporary directories correctly for split multicore loads. You can upgrade to the latest GEMINI development to get the fixes right now (`gemini update --devel`). Thanks again.

**Comment by lbeltrame** [comment]
> Thanks much for the sed level-up. Glad this is working for you. @LMannarino
> -- does this fix your issue as well? If so, happy to close.

We'll be able to test in a few days (backlog....). I'll let you know ASAP.

**Comment by lpantano** [comment]
Closing this since I guess at the end that fix got everything working.

let us know otherwise.

thanks!
