### ISSUE TITLE
vep genome reference error on upgrade

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#846]
Sorry no gist, does the upgrade produce a log if you don't send to stdout/stderr?

```
bcbio_nextgen.py upgrade -u development --tools --data
...
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'novoalign', 'seq', 'ucsc'], 'genomes': [{'rnaseq': True, 'dbsnp': True, 'name': 'Hu
man (GRCh37)', 'dbkey': 'GRCh37'}], 'install_uniref': False}'): Human (GRCh37)
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'novoalign', 'seq', 'ucsc'], 'genomes': [{'rnaseq': True, 'dbsnp': True, 'name': 'Hu
man (GRCh37)', 'dbkey': 'GRCh37'}], 'install_uniref': False}'): Human (GRCh37)
Updating GRCh37 genome resources configuration
[2015-05-08 15:16:30.973633] DEBUG: bcbio-nextgen: Prepare VEP directory for homo_sapiens_vep_79_GRCh37
[2015-05-08 15:16:30.974149] DEBUG: bcbio-nextgen-commands: vep_install.pl -a c -s homo_sapiens_vep_79_GRCh37 -c /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/vep
[2015-05-08 15:16:31.468923] DEBUG: bcbio-nextgen: Getting list of available cache files
[2015-05-08 15:16:35.755355] DEBUG: bcbio-nextgen:  - downloading ftp://ftp.ensembl.org/pub/release-79/variation/VEP/homo_sapiens_vep_79_GRCh37.tar.gz

[2015-05-08 15:33:55.330290] DEBUG: bcbio-nextgen:  - unpacking homo_sapiens_vep_79_GRCh37.tar.gz
[2015-05-08 15:40:33.606993] DEBUG: bcbio-nextgen: 
[2015-05-08 15:40:33.607171] DEBUG: bcbio-nextgen: All done
[2015-05-08 15:40:33.613603] DEBUG: bcbio-nextgen: Convert VEP cache to tabix homo_sapiens_vep_79_GRCh37
[2015-05-08 15:40:33.613708] DEBUG: bcbio-nextgen-commands: vep_convert_cache.pl -species homo_sapiens_vep_79_GRCh37 -version 79 -d /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/vep
[2015-05-08 15:40:34.239214] DEBUG: bcbio-nextgen: ERROR: Species homo_sapiens_vep_79_GRCh37 not found
[2015-05-08 15:40:34.247410] ERROR: bcbio-nextgen: Uncaught exception occurred
Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'vep_convert_cache.pl -species homo_sapiens_vep_79_GRCh37 -version 79 -d /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/vep
ERROR: Species homo_sapiens_vep_79_GRCh37 not found
' returned non-zero exit status 255
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 199, in <module>
    kwargs = parse_cl_args(sys.argv[1:])
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 245, in upgrade_bcbio_data
    s["genomes"] = _get_biodata(cbl["biodata"], args)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 280, in _upgrade_vep_data
    if needs_update:
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 105, in prep_vep_cache
    assert in_file.endswith(".gz") and out_file.endswith(".gz")
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'vep_convert_cache.pl -species homo_sapiens_vep_79_GRCh37 -version 79 -d /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/vep
ERROR: Species homo_sapiens_vep_79_GRCh37 not found
' returned non-zero exit status 255
```

**Comment by chapmanb** [comment]
Daryl;
Apologies, this VEP update touches a lot of things. You actually need a two part upgrade, first get the tools and development code (with the fixes for handling the new databases):
```
bcbio_nextgen.py upgrade -u development --tools
```
then update the data with the fixed installation code:
```
bcbio_nextgen.py upgrade --data
```
You already got the tools and code so re-running the data command should hopefully work cleanly for you now. Sorry again about the confusion and difficult upgrade process.

**Comment by dwaggott** [comment]
A few missing dependencies

```
$ bcbio_nextgen.py upgrade --data
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 38, in <module>
    from bcbio.graph import graph
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/graph/graph.py", line 16, in <module>
    from bcbio.graph.collectl import load_collectl
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/graph/collectl.py", line 9, in <module>
    import progressbar
ImportError: No module named progressbar
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about this. I'm confused as to why this doesn't get installed as it's listed in the requirements file to be pulled in. I made it a soft import to avoid the issue in the future and you can fix your install now with:
```
/share/PI/euan/apps/bcbio/anaconda/bin/conda install -c bcbio progressbar
```
Thanks again for all the patience getting this going.
