### ISSUE TITLE
SHA1sum mismatch and error

### ISSUE THREAD

**Issue by ssvbio** [chapmanb/bcbio-nextgen#855]
Today, I tried to install bcbio on my laptop (ubuntu trusty, 3.13.0-53-generic, Python 2.7.6, 4 GB RAM). My installation argument was/is:

sudo python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local   --genomes GRCh37 --aligners bwa --aligners bowtie2 --sudo --nodata (adapted from commands listed on landing page of the bcbio)

I encountered following issues:
1) SHA1sums for https://github.com/Ensembl/ensembl-tools/archive/4a86cbf.zip, https://github.com/ensembl-variation/VEP_plugins/archive/5b4db9b.zip, https://github.com/konradjk/loftee/archive/0c833d3.zip were incorrect, in /usr/local/Library/Taps/chapmanb/homebrew-cbl/vep.rb, due to which VEP installation failed.

Correct sha1sums are provided below:

a) 'https://github.com/Ensembl/ensembl-tools/archive/4a86cbf.zip'
  sha1 "63064909ffbda19c4238996be85abfef61d09f43"
b)  "https://github.com/ensembl-variation/VEP_plugins/archive/5b4db9b.zip"
    sha1 "6860674311dffcde868f82d134d7da8fcc9d36f2"
c)  'https://github.com/konradjk/loftee/archive/0c833d3.zip'
    sha1 "308a9141e0c0ceb6470402544668fe2190d2c390"

2) Currently, installation is stalled due to following issue. Any help would be greatly appreciated and would be happy to provide further information on this, if necessary:

error message:

==============
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2'], 'genomes': [{'rnaseq': True, 'dbsnp': True, 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}], 'install_uniref': False}'): Human (GRCh37)
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 201, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 248, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/suresh/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/suresh/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/suresh/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 266, in configure_instance
    setup_biodata(options)
  File "/home/suresh/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 248, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/suresh/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/home/suresh/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 478, in _prep_genomes
    if idx in manager.config["annotations"] and method == "ggd":
KeyError: 'annotations'
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 261, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--sudo']' returned non-zero exit status 1

================================

regards
vs

**Comment by chapmanb** [comment]
Apologies about the install issues and thank you for the report. I'm not sure why those sha1sums are different now but I replicated and updated so VEP should not install cleanly. I also updated CloudBioLinux to fix the error message for genomes with GGD annotations. If you remove your locally cached temp directory (`rm -rf tmpbcbio-install`) and re-run the install command it'll pull in these changes, pick up where it left off, and hopefully finish cleanly.

Thanks again for trying out bcbio and for the detailed report.
