### ISSUE TITLE
Allow excluding FastQC runs

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#856]
For some reason FastQC on my server is erroring out:

````java
[2015-05-22T10:16Z] uni13: Exception in thread "Thread-1" java.lang.ArrayIndexOutOfBoundsException: 4
[2015-05-22T10:16Z] uni13:      at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.processSequence(PerTileQualityScores.java:202)
[2015-05-22T10:16Z] uni13:      at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
[2015-05-22T10:16Z] uni13:      at java.lang.Thread.run(Thread.java:744)
```
However I do not need FastQC as I ran a run only to get variant calls to be used elsewhere. This step completely blocks finishing the pipeline. Ideally, it should be optional (``tools_off`` perhaps?) or tied to other parameters (I'm thinking about ``merge_bamprep``).

**Comment by chapmanb** [comment]
Luca;
Sorry about the issue, I haven't seen that problem before. I added a `tools_off: [fastqc]` option allowing skipping fastqc which will hopefully let you finish the analysis. Hope this gets things working for you.
