### ISSUE TITLE
[IPEngineApp] WARNING | No heartbeat in the last 60010 ms (1 time(s) in a row).

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#858]
Hi Brad

I am getting an error again when trying to run bcbio. However this time I have no clue as to why this happens. It seems something times out somewhere in the iPython engine. Perhaps you could clarify?

The process runs nicely and gives this as output:

2015-05-20 12:22:39.606 [IPEngineApp] Using existing profile dir: u'/scratch/matdsmet/IonXpress_016_rawlib_GRCh37/work/log/ipython'
2015-05-20 12:22:39.658 [IPEngineApp] Loading url_file u'/scratch/matdsmet/IonXpress_016_rawlib_GRCh37/work/log/ipython/security/ipcontroller-9f312bce-14eb-46c9-ac2b-df74913daf79-engine.json'
2015-05-20 12:22:39.786 [IPEngineApp] Registering with controller at tcp://127.0.0.1:57166
2015-05-20 12:22:40.430 [IPEngineApp] Starting to monitor the heartbeat signal from the hub every 60010 ms.
2015-05-20 12:22:40.462 [IPEngineApp] Using existing profile dir: u'/scratch/matdsmet/IonXpress_016_rawlib_GRCh37/work/log/ipython'
2015-05-20 12:22:40.522 [IPEngineApp] Completed registration with id 0

after which it starts processing a bunch of references, but then the process errors out with the following message
[IPEngineApp] WARNING | No heartbeat in the last 60010 ms (1 time(s) in a row).

and I get this output.

[2015-05-20T17:49Z] pbsnode10: Timing: coverage
2015-05-20 19:50:12.837 [IPClusterStop] Using existing profile dir: u'/scratch/matdsmet/IonXpress_016_rawlib_GRCh37/work/log/ipython'
2015-05-20 19:50:12.930 [IPClusterStop] Stopping cluster [pid=12012] with [signal=2]
[2015-05-20T17:50Z] pbsnode10: Resource requests: freebayes, gatk, gatk-haplotype, picard, samtools; memory: 2.00, 8.00, 8.00, 2.00, 2.00; cores: 16, 1, 1, 1, 16
[2015-05-20T17:50Z] pbsnode10: Configuring 3 jobs to run, using 1 cores each with 8.00g of memory reserved for each job
Traceback (most recent call last):
  File "/scratch/bcbio/tools/bin/bcbio_nextgen.py", line 220, in <module>
    main(**kwargs)
  File "/scratch/bcbio/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 44, in run_main
    fc_dir, run_info_yaml)
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 79, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 157, in run
    multiplier=region.get_max_counts(samples), max_multicore=1) as run_parallel:
  File "/scratch/bcbio/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 53, in start
    with ipython.create(parallel, dirs, config) as view:
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 50, in create
    cores = per_machine_target_cores(cores, parallel["num_jobs"] // cores)
ZeroDivisionError: integer division or modulo by zero
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/scratch/bcbio/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/scratch/bcbio/anaconda/lib/python2.7/threading.py", line 763, in run
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/logbook/queues.py", line 265, in _target
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/logbook/base.py", line 239, in pop_thread
  File "/scratch/bcbio/anaconda/lib/python2.7/site-packages/logbook/base.py", line 204, in pop_thread
  File "logbook/_speedups.pyx", line 233, in logbook._speedups.ContextStackManager.pop_thread (logbook/_speedups.c:5857)
  File "logbook/_speedups.pyx", line 236, in logbook._speedups.ContextStackManager.pop_thread (logbook/_speedups.c:5678)
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

Any idea where I could have done something wrong? The node the process runs on has 16 cores and 32G of memory.

Thanks!
Matthias

**Comment by chapmanb** [comment]
Matthias;
Sorry about the issue. This looks like a problem with our calculation of core usage -- we were rounding by memory and didn't set a minimum of 1 core, causing the division by zero error. I pushed a fix, so if you update with:
```
bcbio_nextgen.py upgrade -u development
```
it should hopefully work cleanly now. FYI, the heartbeat issue happens intermittently but is not an issue unless it happens a large number of times in a row. It just reflects temporary inability of a worker node to communicate with the controller, which is expected to happen occasionally on busy networks.

Hope this gets things running cleanly for you.

**Comment by matthdsm** [comment]
Thanks, problem fixed! 

Matthias
