### ISSUE TITLE
Installation of bcbio-nextgen fails during vep_install.pl on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by kajetanb** [chapmanb/bcbio-nextgen#863]
I tried to install bcbio-nextgen on Ubuntu 14.04.2 LTS

    $uname -srvm
    Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64

but it failed during the execution of `vep_install.pl`

    [2015-05-27 11:33:20.053614] DEBUG: bcbio-nextgen: Prepare VEP directory for homo_sapiens_vep_79_GRCh37
    [2015-05-27 11:33:20.053779] DEBUG: bcbio-nextgen-commands: vep_install.pl -a c -s homo_sapiens_vep_79_GRCh37 -c /extra/kbentele/bcbio/genomes/Hsapiens/GRCh37/vep
    [2015-05-27 11:33:20.064841] ERROR: bcbio-nextgen: Uncaught exception occurred
    Traceback (most recent call last):
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
        _do_run(cmd, checks, log_stdout)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
        stderr=subprocess.STDOUT, close_fds=True)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    Traceback (most recent call last):
      File "/extra/kbentele/bcbio/anaconda/bin/bcbio_nextgen.py", line 201, in <module>
        install.upgrade_bcbio(kwargs["args"])
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
        upgrade_bcbio_data(args, REMOTES)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 252, in upgrade_bcbio_data
        _upgrade_vep_data(s["fabricrc_overrides"]["galaxy_home"], tooldir)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 287, in _upgrade_vep_data
        effects.prep_vep_cache(dbkey, ref_file, tooldir)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 88, in prep_vep_cache
        do.run(cmd, "Prepare VEP directory for %s" % ensembl_name)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
        _do_run(cmd, checks, log_stdout)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 75, in _do_run
        stderr=subprocess.STDOUT, close_fds=True)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    Traceback (most recent call last):
      File "bcbio_nextgen_install.py", line 261, in <module>
        main(parser.parse_args(), sys.argv[1:])
      File "bcbio_nextgen_install.py", line 41, in main
        subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/extra/kbentele/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/extra/kbentele/bcbio', '--isolate', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for reporting this. The code was implicitly assuming the `vep_install.pl` is available on your PATH. I pushed a fix that will avoid this problem so you can practically fix it for your case either by updating your PATH to include `/path/to/bcbio/tooldir/bin` or updating to the latest development version (`bcbio_nextgen.py upgrade -u development` or add `-u development` to the install command). Hope this gets it working cleanly for you.

**Comment by kajetanb** [comment]
Thanks for the quick response. Updating PATH worked well.
