### ISSUE TITLE
RNAseq pipeline with tophat2 on test data fails in alignment step 

### ISSUE THREAD

**Issue by kajetanb** [chapmanb/bcbio-nextgen#867]
Hi, 
I downloaded test data for the RNASeq-pipeline as described in the
bcbio docs
(<https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#rnaseq-example>)
and then ran

    bcbio_nextgen.py -w template rnaseq-seqc.yaml input/seqc.csv input
    cd seqc/work
    nohup bcbio_nextgen.py ../config/seqc.yaml > bcbio_nextgen.log 2> bcbio_nextgen.err &

trimming workded, but the alignment steps failed from the very beginning on:

    [2015-05-28T04:49Z] Resource requests: picard, tophat2; memory: 3.50, 24.00; cores: 1, 6
    [2015-05-28T04:49Z] Configuring 1 jobs to run, using 1 cores each with 24.00g of memory reserved for each job
    [2015-05-28T04:49Z] Timing: alignment
    [2015-05-28T04:49Z] multiprocessing: disambiguate_split
    [2015-05-28T04:49Z] multiprocessing: process_alignment
    [2015-05-28T04:49Z] Aligning lane 1_2015-05-27_seqc with tophat2 aligner
    Traceback (most recent call last):
      File "/extra/kbentele/bcbio/bin/bcbio_nextgen.py", line 220, in <module>
        main(**kwargs)
      File "/extra/kbentele/bcbio/bin/bcbio_nextgen.py", line 43, in main
        run_main(**kwargs)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 36, in run_main
        fc_dir, run_info_yaml)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 79, in _run_toplevel
        for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 291, in run
        samples = run_parallel("process_alignment", samples)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
        return run_multicore(fn, items, config, parallel=parallel)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
        for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
        self.dispatch(function, args, kwargs)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
        job = ImmediateApply(func, args, kwargs)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
        self.results = func(*args, **kwargs)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
        return apply(f, *args, **kwargs)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 31, in process_alignment
        return sample.process_alignment(*args)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 100, in process_alignment
        data = align_to_sort_bam(fastq1, fastq2, aligner, data)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
        names, align_dir, data)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 99, in _align_from_fastq
        out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 260, in align
        align_dir, data, names)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 98, in tophat_align
        options = _set_quality_flag(options, config)
      File "/extra/kbentele/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 35, in _set_quality_flag
        if qual_format.lower() == "illumina":
    AttributeError: 'NoneType' object has no attribute 'lower'

Thanks for any help!

**Comment by roryk** [comment]
Hi @kajetanb,

Sorry about that, we weren't setting the default value correctly if the quality format wasn't explicitly defined in the configuration file. I fixed that, if you pull down the current version in the github repository you should be good to go.

**Comment by roryk** [comment]
I also added quality format to the rnaseq-seqc.yaml configuration file, so if you pull that down, delete the seqc directory and re-run the template step with that file, it will set the quality format correctly.

**Comment by kajetanb** [comment]
Great, thanks a lot! I am rerunning the script now and will report the outcome.
