### ISSUE TITLE
AttributeError in merging fastq files

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#881]
Hi, 

I was trying to merge multiple exome-seq fastq files for the same sample by using bcbio_prepare_samples.py and met the following error:

Traceback (most recent call last):
  File "/.../parallel/bcbio/scripts/bcbio_prepare_samples.py", line 125, in <module>
    samples = run_parallel("prepare_bcbio_samples", samples)
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 121, in run
    fn = _get_ipython_fn(fn_name, parallel)
  File "/work/unmc_ngs/acornish/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 94, in _get_ipython_fn
    import_fn_name)
AttributeError: 'module' object has no attribute 'prepare_bcbio_samples'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/.../parallel/bcbio/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner

Can anyone help me to figure it out?

Thank you!

**Comment by lpantano** [comment]
Hi pengxiao78,

so sorry about this. Could you tell me the version of bcbio and the command line you tried?

**Comment by pengxiao78** [comment]
Hi Ipantano,
I have updated the version from 0.8.6 to 0.8.9. It seems that the merging is running well. Hopefully, the following variant calling should be fine. Thank you for your reminder!
