### ISSUE TITLE
Workdir path problem (?)

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#898]
Hi

I just ran into a problem as I indicated the workdir in the command.

My command was as follows: `bcbio_nextgen.py config/rnaseq.test.yaml --workdir work -t local -n 16`. 

First, I didnt have the directory `work` created and bcbio_nextgen complained. So I created the directory 'work'. The upload dir in the config/rnaseq.test.yaml is specified as follows: 
`dir: ../output`.

Cutadapt (RNA-seq pipeline) then stored the trimmed sequences in the folder `work/work/trimmed`, so an extra work-folder. In the next step, when the STAR aligner is running (or has run), an exception is produces, which says:  `IOError: [Errno 2] No such file or directory: 'work/align/Patient_6L002/1_19.06.12_rnaseq_experiment_star/Patient_6L002.bam'
`. There is a file under `work/work....` with exactly this name and path.

My guess is, that the error was produces, because I indicated the workdir flag in the command?

```
The complete error log:
[2015-06-19T11:48Z] multiprocessing: process_alignment
[2015-06-19T11:48Z] Aligning lane 1_19.06.12_rnaseq_experiment with star aligner
[2015-06-19T11:48Z] Running STAR aligner on work/trimmed/6_ACTGAT_L002_1.trimmed.fastq.gz and /home/mpschr/bin/bcbionextgen/data/genomes/Hsapiens/GRCh37/star/
[2015-06-19T11:58Z] [bam_sort_core] merging from 32 files...
Traceback (most recent call last):
  File "/home/mpschr/bin/bcbionextgen/tools/bin/bcbio_nextgen.py", line 220, in <module>
    main(**kwargs)
  File "/home/mpschr/bin/bcbionextgen/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 36, in run_main
    fc_dir, run_info_yaml)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 79, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 291, in run
    samples = run_parallel("process_alignment", samples)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 84, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 31, in process_alignment
    return sample.process_alignment(*args)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 100, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 67, in align_to_sort_bam
    bam.index(data["work_bam"], data["config"])
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 50, in index
    utils.symlink_plus(in_bam, tx_bam_file)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 278, in symlink_plus
    shutil.copyfile(orig + ext, new + ext)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'work/align/Patient_6L002/1_19.06.12_rnaseq_experiment_star/Patient_6L002.bam'

```

```
Here is the command log:
[2015-06-19T10:14Z] /home/mpschr/bin/bcbionextgen/data/anaconda/bin/cutadapt --times=2 --quality-base=33 --quality-cutoff=5 --format=fastq --adapter=AACACTCTTTCCCT --adapter=AGATCGGAAGAGCG --adapter=AGGGAAAGAGTGTT --adapter=CGCTCTTCCGATCT  --minimum-length=25  -o work/trimmed/6_ACTGAT_L002_1.trimmed.tmp.fastq.gz -p work/trimmed/6_ACTGAT_L002_2.trimmed.tmp.fastq.gz /home/mpschr/Documents/projects/rnaseq-raw/samples/6_ACTGAT_L002_1.fastq.gz /home/mpschr/Documents/projects/rnaseq-raw/samples/6_ACTGAT_L002_2.fastq.gz;/home/mpschr/bin/bcbionextgen/data/anaconda/bin/cutadapt --times=2 --quality-base=33 --quality-cutoff=5 --format=fastq --adapter=AACACTCTTTCCCT --adapter=AGATCGGAAGAGCG --adapter=AGGGAAAGAGTGTT --adapter=CGCTCTTCCGATCT  --minimum-length=25  -o work/trimmed/6_ACTGAT_L002_2.trimmed.fastq.gz -p work/trimmed/6_ACTGAT_L002_1.trimmed.fastq.gz work/trimmed/6_ACTGAT_L002_2.trimmed.tmp.fastq.gz work/trimmed/6_ACTGAT_L002_1.trimmed.tmp.fastq.gz; rm work/trimmed/6_ACTGAT_L002_1.trimmed.tmp.fastq.gz work/trimmed/6_ACTGAT_L002_2.trimmed.tmp.fastq.gz 
[2015-06-19T11:03Z] /home/mpschr/bin/bcbionextgen/data/anaconda/bin/cutadapt --times=2 --quality-base=33 --quality-cutoff=5 --format=fastq --adapter=AACACTCTTTCCCT --adapter=AGATCGGAAGAGCG --adapter=AGGGAAAGAGTGTT --adapter=CGCTCTTCCGATCT  --minimum-length=25  -o work/trimmed/6_ACTGAT_L001_1.trimmed.tmp.fastq.gz -p work/trimmed/6_ACTGAT_L001_2.trimmed.tmp.fastq.gz /home/mpschr/Documents/projects/rnaseq-raw/samples/6_ACTGAT_L001_1.fastq.gz /home/mpschr/Documents/projects/rnaseq-raw/samples/6_ACTGAT_L001_2.fastq.gz;/home/mpschr/bin/bcbionextgen/data/anaconda/bin/cutadapt --times=2 --quality-base=33 --quality-cutoff=5 --format=fastq --adapter=AACACTCTTTCCCT --adapter=AGATCGGAAGAGCG --adapter=AGGGAAAGAGTGTT --adapter=CGCTCTTCCGATCT  --minimum-length=25  -o work/trimmed/6_ACTGAT_L001_2.trimmed.fastq.gz -p work/trimmed/6_ACTGAT_L001_1.trimmed.fastq.gz work/trimmed/6_ACTGAT_L001_2.trimmed.tmp.fastq.gz work/trimmed/6_ACTGAT_L001_1.trimmed.tmp.fastq.gz; rm work/trimmed/6_ACTGAT_L001_1.trimmed.tmp.fastq.gz work/trimmed/6_ACTGAT_L001_2.trimmed.tmp.fastq.gz 
[2015-06-19T11:48Z] /home/mpschr/bin/bcbionextgen/tools/bin/STAR --genomeDir /home/mpschr/bin/bcbionextgen/data/genomes/Hsapiens/GRCh37/star/ --readFilesIn work/trimmed/6_ACTGAT_L002_1.trimmed.fastq.gz work/trimmed/6_ACTGAT_L002_2.trimmed.fastq.gz --runThreadN 16 --outFileNamePrefix work/align/Patient_6L002/1_19.06.12_rnaseq_experiment --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd SAM --outSAMunmapped Within --outSAMattributes NH HI NM MD AS --readFilesCommand zcat  --outSAMattrRGline ID:1 PL:illumina PU:1_19.06.12_rnaseq_experiment SM:Patient_6L002  --outSAMstrandField intronMotif  | /home/mpschr/bin/bcbionextgen/tools/bin/samtools sort -@ 16 -m 1G  -T work/align/Patient_6L002/1_19.06.12_rnaseq_experiment_star/tx/tmpkKmCic/Patient_6L002-sorttmp -o work/align/Patient_6L002/1_19.06.12_rnaseq_experiment_star/tx/tmpkKmCic/Patient_6L002.bam /dev/stdin
```

**Comment by mpschr** [comment]
I have comfirmed the behaviour changing the directory name from `work` to `tmp` and the same happened: The pipeline created `tmp/tmp/...` folder hierarchy and failed at the same point.

Before I had run the pipeline without from within the workdir, without the workdir flag. This worked fine and did not create extra subdirectories

**Comment by chapmanb** [comment]
Michael;
Sorry about the issues with using `--workdir`. The code was assuming that the directory would exist and be a full non-relative path (ie. /path/to/wherever/work`). Apologies. I pushed a fix that will create the directories and make them absolute if not specified, and will hopefully resolve the issue for you. You can either update to the latest development version or specify the full path, or just change to the work directory since that's essentially all this option does. Hope this gets things running for you and thanks again for the report.

**Comment by mpschr** [comment]
Hi Brad

Thanks for the quick reaction. I'll try to use `--workdir` as soon as the current run is done and will report back.

**Comment by mpschr** [comment]
Hi Brad. 

I can confirm now, that the --workdir argument is not causing anymore the above exception and STAR aligner could be run
