### ISSUE TITLE
Errors with installing of extra software 

### ISSUE THREAD

**Issue by wangx677** [chapmanb/bcbio-nextgen#899]
My computer system is Ubuntu 14.04.2 LTS.

I'm installing GATK with the following command: 
bcbio_nextgen.py upgrade --tools --toolplus gatk=/project/csbio/wwang/NGS/gatk/GenomeAnalysisTK.jar

1) The first issue is with DNAcopy and the output on the screen shows:

gcc -std=gnu99 -shared -L/soft/r/3.1.2/linux_x86_64_precise/lib/R/lib -L/usr/local/lib -o DNAcopy.so cbsWtstats.o cbststats.o changepoints-wtd.o changepoints.o esegment.o flchoose.o fphyper.o fpnorm.o getbdry.o prune.o rshared.o segmentp.o smoothCNA.o tailprobs.o -R/soft/gcc-4.5.2/ubuntuamd1/lib64 -lgfortran -lm -L/soft/r/3.1.2/linux_x86_64_precise/lib/R/lib -lR
gcc: error: unrecognized option '-R'
make: *** [DNAcopy.so] Error 1
ERROR: compilation failed for package 'DNAcopy'
* removing '/project/csbio/wwang/NGS/bcbio/lib/R/site-library/DNAcopy'

2) The second issue is with Rsamtools, the output on the screen is:

** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/project/csbio/wwang/NGS/bcbio/lib/R/site-library/Rsamtools/libs/Rsamtools.so':
  /soft/gcc-4.5.2/ubuntuamd1/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /project/csbio/wwang/NGS/bcbio/lib/R/site-library/Rsamtools/libs/Rsamtools.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/project/csbio/wwang/NGS/bcbio/lib/R/site-library/Rsamtools'

The installer is looking for `GLIBCXX_3.4.15' from "/soft/gcc-4.5.2/ubuntuamd1/lib64/libstdc++.so.6", but my `GLIBCXX_3.4.15' is under directory "/usr/lib/x86_64-linux-gnu/libstdc++.so.6". How to change the searching path?

3) The 3rd issue is with GATK. 

Installing additional tools
Traceback (most recent call last):
  File "/project/csbio/wwang/NGS/bcbio/bin/bcbio_nextgen.py", line 201, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/project/csbio/wwang/NGS/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 84, in upgrade_bcbio
    _install_toolplus(args)
  File "/project/csbio/wwang/NGS/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 389, in _install_toolplus
    _install_gatk_jar(tool.name, tool.fname, toolplus_manifest, system_config, toolplus_dir)
  File "/project/csbio/wwang/NGS/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 410, in _install_gatk_jar
    version = get_gatk_jar_version(name, fname)
  File "/project/csbio/wwang/NGS/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 399, in get_gatk_jar_version
    return broad.get_gatk_version(fname)
  File "/project/csbio/wwang/NGS/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 100, in get_gatk_version
    _check_for_bad_version(version, "GATK")
  File "/project/csbio/wwang/NGS/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 83, in _check_for_bad_version
    "This often indicates you're not running Java 1.7:\n%s" % (program, version))
ValueError: Problem getting version for GATK. This often indicates you're not running Java 1.7:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/gatk/engine/CommandLineGATK : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: org.broadinstitute.gatk.engine.CommandLineGATK. Program will exit.
maximus{wwang} 67:bcbio_nextgen.py upgrade --tools --toolplus gatk=/project/csbio/wwang/NGS/gatk/GenomeAnalysisTK.jarst

Thanks for helping!
Wen

**Comment by chapmanb** [comment]
Wen;
Sorry about the issues. I can try to help some but you might need to also coordinate with someone locally who has a better idea of your cluster system setup. It appears as if you're using modules or another similar approach to inject software into your path, so local research computing should have specific suggestions about what to load. To answer your specific questions:

- For 1 and 2, it looks like you have an older gcc installation and it's not properly configured. Ubuntu 14.04 should have gcc 4.8 (in `/usr/bin`) so it would be worth trying to use this instead of the 4.5.2 version you're pulling in.
- For 3, GATK requires Java 1.7. It looks like you have 1.6 on your PATH instead of 1.7.

Hope this helps.

**Comment by mpschr** [comment]
@chapmanb, I was running into the Java problem because I had Java 1.8 installed for another software. I am now switching between versions as needed.

I am not sure if it is possible and worth the effort, but maybe `bcbio_nextgen` can set the JAVA_HOME just that `bcbio_nextgen` can point to a custom JAVA_HOME, if needed? The only thing which I am not sure if the subprocesses will inherit the custom JAVA_HOME and modified PATH env. variables if the default system java version is e.g. 1.8

**Comment by chapmanb** [comment]
Michael;
bcbio and all the subprocess commands inherit all of the environmental variables, so we don't need to anything special within bcbio-itself to handle this. Setting your shell environment (PATH + JAVA_HOME) to point to Java 1.7 should make everything just work.

Sorry for the specific Java version requirements. I'm hoping more tools will support 1.8 soon.

**Comment by roryk** [comment]
@mpschr, closing this out since it is a pretty old issue and it the switch to 1.7 should solve the problem. Feel free to reopen if this never actually got working. Thanks!
