### ISSUE TITLE
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'seqtk' {} None

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#902]
Hi Brad,

Could you pls help me check the error when I update bcbio:

[2015-06-24T16:16Z] Resource requests: bwa, sambamba, samtools; memory: 2.00; cores: 16, 1, 16
[2015-06-24T16:16Z] Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job
[2015-06-24T16:16Z] Timing: organize samples
[2015-06-24T16:16Z] multiprocessing: organize_samples
[2015-06-24T16:16Z] Using input YAML configuration: /home/CHD_WE21/config/CHD_WE.yaml
[2015-06-24T16:16Z] Checking sample YAML configuration: /home/CHD_WE21/config/CHD_WE.yaml
[2015-06-24T16:16Z] Testing minimum versions of installed programs
[2015-06-24T16:16Z] Timing: alignment preparation
[2015-06-24T16:16Z] multiprocessing: prep_align_inputs
[2015-06-24T16:16Z] multiprocessing: disambiguate_split
[2015-06-24T16:16Z] Timing: alignment
[2015-06-24T16:16Z] multiprocessing: process_alignment
[2015-06-24T16:16Z] Aligning lane F42_2015-6-18_CHD_WE21 with bwa aligner
Traceback (most recent call last):
  File "/home/bcbio_install/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/home/bcbio_install/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 144, in run
    samples = run_parallel("process_alignment", samples)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 31, in process_alignment
    return sample.process_alignment(*args)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 100, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
    names, align_dir, data)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 99, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 134, in align_pipe
    or not _can_use_mem(fastq_file, data)):
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 96, in _can_use_mem
    seqtk = config_utils.get_program("seqtk", data["config"])
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 181, in get_program
    return _get_program_cmd(name, pconfig, default)
  File "/home/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 198, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.func_name, name, config, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'seqtk' {} None

Thanks so much!

**Comment by chapmanb** [comment]
Sorry about the problem, it looks like bcbio can't find `seqtk` for some reason. bcbio does install that as part of the standard process so either something happened to it, or your PATH is not set correctly. You could try re-running an upgrade `bcbio_nextgen.py upgrade --tools` or manually checking that your PATH points to the location of the installed bcbio tools. Hope this helps some.

**Comment by lpantano** [comment]
Hi,

I will close this since it seems it worked at the end? please, feel free to come again if you have any further problem! Thanks!
