### ISSUE TITLE
New, fresh installation fails

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#914]
This occurs on a Ubuntu machine:

````
2015-06-30 14:38:17 (65.6 MB/s) - ‘gemini_install.py’ saved [18448/18448]

Traceback (most recent call last):
  File "/home/bcbio/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 85, in upgrade_bcbio
    _install_toolplus(args)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 391, in _install_toolplus
    _install_gemini(args.tooldir, _get_data_dir(), args)
  File "/home/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 474, in _install_gemini
    subprocess.check_call(cmd)
  File "/home/bcbio/anaconda/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/bcbio/anaconda/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/home/bcbio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 265, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '-u', 'development', '--genomes', 'hg19', '--aligners', 'bwa', '--sudo', '--distribution', 'ubuntu', '--toolplus', 'data', '--data']' returned non-zero exit status 1
````

**Comment by chapmanb** [comment]
Luca;
Sorry about the issue -- could you paste the initial command line you used to call the installer? Is it possible you forgot to specify `--tooldir` on the input line? I'm trying to come up with other reasons why the command would fail but this seems like the most likely culprit. Hope this explains it.

**Comment by lbeltrame** [comment]
Indeed ``tooldir`` was missing. However, (at least IMO), specifying ``--toolplus data`` without ``tooldir`` should cause an error (no tool dir specified).

**Comment by chapmanb** [comment]
Luca;
Thanks for confirming the issue and for the suggestion. I pushed a fix to check for this issue and report a more useful error message.
