### ISSUE TITLE
snpeff errors

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#916]
Looking through the logs for gatk joint pipeline highlights a large number of snpeff errors. I bumped the memory in bcbio_system.yaml just in case. I'll just ignore the parsing errors.

```
[2015-06-30T17:01Z] scg1-3-14.local:    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:797)
[2015-06-30T17:01Z] scg1-3-14.local:    at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:127)
[2015-06-30T17:01Z] scg1-3-14.local: Error: Error while processing VCF entry (line 1399831) :
[2015-06-30T17:01Z] scg1-3-14.local:    5       14265   rs112160631     C       CA      49.77   .       AC=1;AF=0.500;AN=2;BaseQRankSum=0.405;ClippingRankSum=-3.040e-01;DB;DP=48;FS=4.474;MLEAC=1;MLEAF=0.500;MQ=55.73;MQ0=0;MQRankSum
[2015-06-30T17:01Z] scg1-3-14.local: java.lang.RuntimeException: Error parsing line 852 from file '/srv/gsfs0/projects/ashley/apps/bcbio/genomes/Hsapiens/GRCh37/snpeff/GRCh37.75/sequence.5.bin'
[2015-06-30T17:01Z] scg1-3-14.local:    SEQUENCE        851     45      65892175        66465422        5:65892175-66465422     false   caaggagaagccgcagtacccgcggctcgggtgcagcgcgggagcacagtggagcgcagatcgcggacccgagcgggcatgtccccgcgcgcggg
[2015-06-30T17:01Z] scg1-3-14.local:    Field [8] : '-'
[2015-06-30T17:04Z] scg1-3-15.local: Error: Error while processing VCF entry (line 1418693) :
[2015-06-30T17:04Z] scg1-3-15.local:    5       14056   rs200852786     C       CT      56.77   .       AC=1;AF=0.500;AN=2;BaseQRankSum=-1.071e+00;ClippingRankSum=-2.100e-02;DB;DP=40;FS=8.563;MLEAC=1;MLEAF=0.500;MQ=58.07;MQ0=0;MQRa
[2015-06-30T17:04Z] scg1-3-15.local: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issue. I think you're right on that this is a memory issue with snpEff and you might need to provide it additional memory. The default in the `bcbio_system.yaml` file is 6g which normally works but if you have very large number of samples there might be increased requirements. Hopefully increasing memory fixes the underlying issue and please let us know if not.

**Comment by dwaggott** [comment]
This was only 4 whole genome samples so I was a bit surprised. So far the logs look good after I doubled the memory. I'll post back after things finish.

**Comment by roryk** [comment]
Hi @dwaggott,

Closing this out since it is pretty stale and it should be working. Feel free to reopen if things never worked out.
