### ISSUE TITLE
path to tophat 

### ISSUE THREAD

**Issue by YiChingTang** [chapmanb/bcbio-nextgen#926]
hi, I ran the example pipleine for rna-seq and encounter the following problem.
it looks like it can't find tophat at the path /opt/bcbio/tools/bin/
So, i ls -lrht the /opt/bcbio/tools/bin and it shows tophat is there!

          tophat -> ../Cellar/tophat-binary/2.0.14/bin/tophat
any idea?
btw, tool-path for bcbio tool-dir was /opt/bcbio/tools
and I ran the example pipeline at the directory of somewhere other than /opt/bcbio/tools

[2015-07-05T10:01Z] Aligning lane 1_2015-07-01_seqc with tophat2 aligner
Traceback (most recent call last):
  File "/opt/bcbio/tools/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/opt/bcbio/tools/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 297, in run
    samples = run_parallel("process_alignment", samples)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 31, in process_alignment
    return sample.process_alignment(*args)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 100, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
:
 File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 64, in align_to_sort_bam
    names, align_dir, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 99, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 260, in align
    align_dir, data, names)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 110, in tophat_align
    if _tophat_major_version(config) == 1:
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/tophat.py", line 357, in _tophat_major_version
    version_string = str(tophat_runner(version=True)).strip().split()[1]
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/sh.py", line 486, in __init__
    self.wait()
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/opt/bcbio/tools/bin/tophat --version'

  STDOUT:

  STDERR:
  File "/opt/bcbio/tools/bin/tophat", line 1003
    except getopt.error, msg:
                       ^
SyntaxError: invalid syntax

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. The main tophat executable is a Python script which was using the default Python (first one in your PATH). It looks like the Python you had was incompatible with the script, which I believe requires 2.x. I pushed fixes which will use bcbio's internal Python to call TopHat instead of the PATH one, which should resolve this issue without needing to change your external environment. You can upgrade with `bcbio_nextgen.py upgrade -u development`.

Thanks again for the report and hope this gets it running for you.
