### ISSUE TITLE
ValueError: Processing failed on GEMINI chunk load

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#954]
Hi,
I am using the following yaml file for the basic germline calling. 
```
resources:
    tmp:
      dir: /tmp
details:
- algorithm:
    align_split_size: 5000000
    aligner: bwa
    ensemble:
      numpass: 2
    mark_duplicates: picard
    merge_bamprep: true
    realign: gatk
    recalibrate: gatk
    variantcaller:
    - freebayes
    - gatk-haplotype
    - samtools
  analysis: variant2
  description: M1
  files:
  - /../M1_R1.trimmed.fastq.gz
  - /../M1_R2.trimmed.fastq.gz
  genome_build: GRCh37
  metadata:
    sex: female
....
....
```
I have tested this yaml configuration for two samples and successfully generated *.emsemble.vcf.gz and all other final files in the final folder. Then I am running it for the remaining 34 samples but found the error as the follows.
```
Traceback (most recent call last):
  File "/.../parallel/bcbio/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1117, in main
    args.func(parser, args)
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 183, in load_fn
    gemini_load.load(parser, args)
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 50, in load
    load_multicore(args)
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 80, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 247, in load_chunks_multicore
    wait_until_finished(procs)
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 338, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load
' returned non-zero exit status 1
```
Thank you!

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. It's tough to provide a diagnosis from this traceback only, as it tells us GEMINI is erroring out during the database build process but not exactly where. The actual error messages are likely located earlier in `log/bcbio-nextgen-debug.log` or in stdout (or logs from the scheduler if this is distributed). This might be due to scaling up, filesystem IO stress but that is only a guess based on your description of when the problem appeared.

If you can't identify an issue, are stuck and don't need GEMINI databases you can disable creation with `tools_off: [gemini]`:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#post-processing

Hope this helps.

**Comment by pengxiao78** [comment]
Hi, I extracted more info from log/bcbio-nextgen-debug.log. Can you further help me to see if there is any help.

Thank you.

Indexing /.../work/gemini/M1-freebayes-decompose-effects.vcf.gz with grabix.
Loading 793045 variants.
Breaking /.../work/gemini/M1-freebayes-decompose-effects.vcf.gz into 10 chunks.
Loading chunk 0.
Loading chunk 1.
Loading chunk 2.
Loading chunk 3.
Loading chunk 4.
Loading chunk 5.
Loading chunk 6.
Loading chunk 7.
Loading chunk 8.
Loading chunk 9.

Traceback (most recent call last):
File "/.../parallel/bcbio/bin/gemini", line 6, in <module>
gemini.gemini_main.main()
File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1117, in main
args.func(parser, args)
File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 183, in load_fn
gemini_load.load(parser, args)
File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 50, in load
load_multicore(args)
File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 80, in load_multicore
chunks = load_chunks_multicore(grabix_file, args)
File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 247, in load_chunks_multicore
wait_until_finished(procs)
File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 338, in wait_until_finished
raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load
pid 13568: 39999 variants processed.
Uncaught exception occurred
Traceback (most recent call last):
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /.../parallel/bcbio/bin/gemini load  --passonly --skip-cadd --skip-gerp-bp  -v /.../work/gemini/M1-freebayes-decompose-effects.vcf.gz -t snpEff --cores 10 --tempdir /tmp/bcbiotx/8066ceeb-6f6c-46c0-a5b7-00fded609509/tmprBtb_T /tmp/bcbiotx/8066ceeb-6f6c-46c0-a5b7-00fded609509/tmprBtb_T/M1-freebayes.db
  File "/.../parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 450, in _prepare_variation
    gt_phred_likelihoods = get_phred_lik(var.gt_phred_likelihoods)
  File "/work/unmc_ngs/acornish/parallel/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 41, in get_phred_lik
    if row is not None and len(row) == 3:
TypeError: object of type 'int' has no len()

**Comment by chapmanb** [comment]
Thanks, this does help a lot. This is a bug in GEMINI that was fixed in the 0.16.x releases. If you have an older version so you can update just gemini with:
```
/.../parallel/bcbio/bin/gemini update
```
Hope this helps.

**Comment by pengxiao78** [comment]
I see. Thanks  a lot!

**Comment by lpantano** [comment]
Closing this since it seems that fixed the issue.

thanks a lot!
