### ISSUE TITLE
sambamba depth python float casting problem

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#961]
Hi -

My pipeline fails on this command: 

```
set -o pipefail; sambamba depth window -t 10 -c 47.36 --window-size 250 -T 947 /home/mpschr/Documents/projects/exon/scratch_AL06/align/AL06_CR/1_AL06_hirvi20150724-sort.bam | /home/mpschr/bin/bcbionextgen/data/anaconda/bin/py -fx 'float(x.split()[5]) >= 25.0' | cut -f 1-3,7
```

The otuput from the log file:

```
[2015-08-05T12:07Z] multiprocessing: combine_bed
[2015-08-05T12:14Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; sambamba depth window -t 10 -c 47.36 --window-size 250 -T 947 /home/mpschr/Documents/projects/exon/scratch_AL06/align/AL06_CR/1_AL06_hirvi20150724-sort.bam | /home/mpschr/bin/bcbionextgen/data/anaconda/bin/py -fx 'float(x.split()[5]) >= 25.0' | cut -f 1-3,7 > /home/mpschr/Documents/projects/exon/scratch_AL06/align/AL06_CR/tx/tmpZK1FAh/1_AL06_hirvi20150724-sort-highdepth-raw.bed
Processing reference #1 (1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    float(x.split()[5]) >= 25.0
ValueError: could not convert string to float: meanCoverage
sambamba-depth:  (Broken pipe)
' returned non-zero exit status 1

```

The output before the pipe into python looks like this:

```
 set -o pipefail; sambamba depth window -t 10 -c 47.36 --window-size 250 -T 947 /home/mpschr/Documents/projects/exon/scratch_AL06/align/AL06_CR/1_AL06_hirvi20150724-sort.bam | head# chrom	chromStart	chromEnd	readCount	meanCoverage	percentage947	sampleName
Processing reference #1 (1)
1	721500	721750	200	67.564	0	AL06_CR	
1	762000	762250	600	213.8	0	AL06_CR	
1	762250	762500	232	52.092	0	AL06_CR	
1	777250	777500	204	72.076	0	AL06_CR	
1	792250	792500	159	55.904	0	AL06_CR	
1	861250	861500	306	110.224	0	AL06_CR	
1	871000	871250	220	76.02	0	AL06_CR	
1	874250	874500	211	63.868	0	AL06_CR	
1	874500	874750	276	75.964	0	AL06_CR	
```

So I am not sure what is failing here

**Comment by mpschr** [comment]
I saw that I was missing a line of code on my local installation: https://github.com/chapmanb/bcbio-nextgen/blob/b9b3e73dc357b61df2fbea587c9af84de008b31b/bcbio/bam/highdepth.py#L50
sdf

I made an update and now it seems to work if I run the extracted example. Closing issue
