### ISSUE TITLE
Install problem ValueError: Distribution does not match machine

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#964]
I tried to use the automatic install from your documents page 
```wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py```

```python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local \
  --genomes GRCh37 --aligners bwa --aligners bowtie2```

When I ran the python script in the second line it generated the following error

```python
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 81, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 372, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 101, in _setup_vm
    _setup_cloudbiolinux(options)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 193, in _setup_cloudbiolinux
    _configure_fabric_environment(env, flavor, fabricrc_loader=fabricrc_loader)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/utils.py", line 93, in _configure_fabric_environment
    _setup_distribution_environment(ignore_distcheck=ignore_distcheck)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/distribution.py", line 57, in _setup_distribution_environment
    _validate_target_distribution(env.distribution, env.get('dist_name', None))
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/distribution.py", line 94, in _validate_target_distribution
    raise ValueError("Distribution does not match machine; are you using correct fabconfig for " + dist)
ValueError: Distribution does not match machine; are you using correct fabconfig for debian
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--data']' returned non-zero exit status 1
```

I am trying to install it on a Linux Mint machine running Ubuntu 14.04. How do I find out if I am using the correct fabconfig for debian? Any help would be appreciated.

**Comment by chapmanb** [comment]
Sorry about the install issues and thanks for the report. The script tries to guess your distribution and it looks like it doesn't do a good job on Mint. I'm happy to fix this if you could provide output of some of the files it checks:
```
cat /etc/*release
cat /proc/version
cat /etc/issue
```
My guess is that `/etc/*release` reports something about Mint and the others 'Ubuntu' and the installer is getting confused. 

Thanks much for the help debugging.

**Comment by kevjp** [comment]
```
cat /etc/*release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
NAME="Ubuntu"
VERSION="14.04, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
```
cat /proc/version
Linux version 3.13.0-24-generic (buildd@panlong) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014
```

```
cat /etc/issue
Linux Mint 17 Qiana \n \l
```

Thank you I appreciate the help.

**Comment by chapmanb** [comment]
Thanks much for this. I pushed a fix to CloudBioLinux that should resolve the detection issue and hopefully let everything proceed cleanly. If you remove the cached version (`rm -rf tmpbcbio-install`) and re-run the initial command it'll kick off again. Hope this gets everything installed for you.

**Comment by kevjp** [comment]
Re-ran the initial command and now it is errors out with message

```python
 Warning: local() encountered an error (return code 6) while executing 'wget --continue --no-check-certificate -O hapmap_3.3.b37.vcf.gz 'ftp://gsapubftp-anonymous:@ftp.broadinstitute.org/bundle/2.8/b37/hapmap_3.3.b37.vcf.gz''

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 254, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 266, in configure_instance
    setup_biodata(options)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 248, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 351, in install_data
    _install_additional_data(genomes, genome_indexes, config)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 391, in _install_additional_data
    download_dbsnp(genomes, BROAD_BUNDLE_VERSION, DBSNP_VERSION)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/dbsnp.py", line 39, in download_dbsnp
    _dbsnp_human(env, gid, manager, bundle_version, dbsnp_version)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/dbsnp.py", line 66, in _dbsnp_human
    _download_broad_bundle(manager.dl_name, bundle_version, dl_name, ext)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/dbsnp.py", line 90, in _download_broad_bundle
    out_file = shared._remote_fetch(env, base_url)
  File "/home/kevin/tmpbcbio-install/cloudbiolinux/cloudbio/custom/shared.py", line 201, in _remote_fetch
    raise IOError("Failure to retrieve remote file")
IOError: Failure to retrieve remote file
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Sorry about the issue. This is reporting a connectivity issue downloading a file from Broad. The command that fails is:
```
wget --continue --no-check-certificate -O hapmap_3.3.b37.vcf.gz 'ftp://gsapubftp-anonymous:@ftp.broadinstitute.org/bundle/2.8/b37/hapmap_3.3.b37.vcf.gz
```
It could be an intermittent issue due to connectivity, and if you re-run the same command it'll pick up where it left off and hopefully work cleanly. If it's a persistent issue, you might need to look into why you can't connect to the server from your machine. Hope that a re-run fixes it for you.

**Comment by kevjp** [comment]
Thanks I kept re-running the same command and eventually I got through all of the connectivity hiccups. Appreciate all the help.
