### ISSUE TITLE
ImportError: No module named seqcluster.libs.fastq

### ISSUE THREAD

**Issue by scatreux** [chapmanb/bcbio-nextgen#969]
Hello,

I tried a bcbio_nextgen RNASEQ run (using the standard SEQC samples) and i ran
into the following issue:
[severinec@glaurung work]$ bcbio_nextgen.py ../config/seqc.yaml -n 48
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 35, in <module>
    from bcbio.distributed import runfn, clargs
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 11, in <module>
    from bcbio.distributed import multitasks
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 5, in <module>
    from bcbio.srna import sample as srna
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 6, in <module>
    from seqcluster.libs.fastq import collapse, write_output
ImportError: No module named seqcluster.libs.fastq

**Comment by lpantano** [comment]
Hi,

sorry about that. I added the smallRNA pipeline and it breaks with this dependency. @chapmanb fixed yesterday night. So if you update to the development version it should work.

`bcbio_nextgen.py upgrade -u development`

sorry about that problem.

**Comment by lpantano** [comment]
hi @scatreux,
I hope this fixed the issue.
will close this, please let us know if you continue with this problem.
