### ISSUE TITLE
region.py KeyError: 'callable_regions'

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#972]
I have tried running "Exome with validation against reference materials" pipeline http://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#exome-with-validation-against-reference-materials
When I tried running the pipeline with your reference material it worked as expected. I then tried to re-run the pipeline with my own fastq files sequencing HapMap NA12878 and using my own bed file. When I ran the pipeline it ends up throwing up an error which I think is happening when I am labelling up callable regions in the bed file. The error that is thrown is:

```python

[2015-08-12T15:51Z] Resource requests: freebayes, gatk, gatk-haplotype, picard, samtools; memory: 2.00, 3.50, 3.50, 3.50, 2.00; cores: 16, 1, 1, 1, 16
[2015-08-12T15:51Z] Configuring 4 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2015-08-12T15:51Z] Timing: alignment post-processing
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in run
    samples = region.parallel_prep_region(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 121, in parallel_prep_region
    "piped_bamprep", _add_combine_info, file_key, ["config"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 58, in parallel_split_combine
    split_outfile_i)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 126, in _get_split_tasks
    out_final, out_parts = split_fn(data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 43, in _do_work
    with open(data["config"]["algorithm"]["callable_regions"]) as in_handle:
KeyError: 'callable_regions'
``` 
When I print out the data dictionary that region.py is referencing I generate the following output below. As you can see there is no reference to `callable_regions`

```
 {'validate': '/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/input/Pan81NA12878intersect_targetted_exome.recode.vcf', 'callable_count': 195363, 'coverage_interval': 'regional', 'archive': [], 'recalibrate': 'gatk', 'num_cores': 1, 'quality_format': 'standard', 'aligner': 'bwa', 'validate_regions': '/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/input/Pan81NA12878intersectformatted.bed', 'realign': 'gatk', 'tools_off': [], 'highdepth_regions': '/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/NA12878-sort-highdepth.bed', 'align_split_size': 5000000, 'ensemble': {'numpass': 2}, 'variant_regions': '/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/bedprep/Pan81dataformatted.bed', 'variantcaller': ['freebayes', 'gatk-haplotype', 'samtools'], 'merge_bamprep': True, 'tools_on': []}
```

I am not sure where I have gone wrong. I think I have provided all the equivalent files in the correct format. Here is my project YAML file:

```yaml
---
upload:
  dir: ../final
details:
  - files: [../input/NGS43a_H_141105A_HapMapNA12878_Pan81_ACTTGA_L001_R1_001.fastq.gz, ../input/NGS43a_H_141105A_HapMapNA12878_Pan81_ACTTGA_L001_R2_001.fastq.gz]
    description: NA12878
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      align_split_size: 5000000
      variantcaller: [freebayes, gatk-haplotype, samtools]
      recalibrate: gatk
      realign: gatk
      merge_bamprep: true
      validate: ../input/Pan81NA12878intersect_targetted_exome.recode.vcf
      validate_regions: ../input/Pan81NA12878intersectformatted.bed
      variant_regions: ../input/Pan81dataformatted.bed
      ensemble:
        numpass: 2
```
Appreciate any help you can give.
Thanks

**Comment by chapmanb** [comment]
Sorry about the issue and the confusing error message. I pushed a fix which should provide a more useful error here in the future.

Practically, missing the `callable_regions` file here means something went wrong with alignment of your input sample and bcbio couldn't find any regions to parallelize it. It would be worth looking at the callable BED files in `align/NA12878` to see if bcbio finds callable blocks. If you could post any more details from there we'd be happy to try and debug further if digging around doesn't reveal the issue. Hope this helps.

**Comment by kevjp** [comment]
Thank you very much for responding so quickly. The file NA12878-sort-callable-nblocks.bed reads as such

```
1	0	249250621
2	0	243199373
3	0	198022430
4	0	191154276
5	0	180915260
6	0	171115067
7	0	159138663
8	0	146364022
9	0	141213431
10	0	135534747
11	0	135006516
12	0	133851895
13	0	115169878
14	0	107349540
15	0	102531392
16	0	90354753
17	0	81195210
18	0	78077248
19	0	59128983
20	0	63025520
21	0	48129895
22	0	51304566
X	0	155270560
Y	0	59373566
MT	0	16569
GL000207.1	0	4262
GL000226.1	0	15008
GL000229.1	0	19913
GL000231.1	0	27386
GL000210.1	0	27682
GL000239.1	0	33824
GL000235.1	0	34474
GL000201.1	0	36148
GL000247.1	0	36422
GL000245.1	0	36651
GL000197.1	0	37175
GL000203.1	0	37498
GL000246.1	0	38154
GL000249.1	0	38502
GL000196.1	0	38914
GL000248.1	0	39786
GL000244.1	0	39929
GL000238.1	0	39939
GL000202.1	0	40103
GL000234.1	0	40531
GL000232.1	0	40652
GL000206.1	0	41001
GL000240.1	0	41933
GL000236.1	0	41934
GL000241.1	0	42152
GL000243.1	0	43341
GL000242.1	0	43523
GL000230.1	0	43691
GL000237.1	0	45867
GL000233.1	0	45941
GL000204.1	0	81310
GL000198.1	0	90085
GL000208.1	0	92689
GL000191.1	0	106433
GL000227.1	0	128374
GL000228.1	0	129120
GL000214.1	0	137718
GL000221.1	0	155397
GL000209.1	0	159169
GL000218.1	0	161147
GL000220.1	0	161802
GL000213.1	0	164239
GL000211.1	0	166566
GL000199.1	0	169874
GL000217.1	0	172149
GL000216.1	0	172294
GL000215.1	0	172545
GL000205.1	0	174588
GL000219.1	0	179198
GL000224.1	0	179693
GL000223.1	0	180455
GL000195.1	0	182896
GL000212.1	0	186858
GL000222.1	0	186861
GL000200.1	0	187035
GL000193.1	0	189789
GL000194.1	0	191469
GL000225.1	0	211173
GL000192.1	0	547496
```

The initial alignment seems to have generated a bam file as expected not sure why bcbio could not find any regions to parallelize it. The inital bed files are quite large but I can send them to you if required.
Thanks for all your help.

**Comment by chapmanb** [comment]
Thanks much. The `nblocks` file is a list of regions of the genome without alignment coverage > 4 -- places where bcbio could parallelize. So the file is telling you it found no callable regions anywhere, which is why it fails at trying to determine how to split it up.

It's definitely unusual that nothing at all would map. It might be worth looking at the aligned BAM file with `samtools idxstats` or `fastqc` to see what is wrong. Do you have aligned reads? 

Hope this helps.

**Comment by kevjp** [comment]
I have viewed the BAM file in Savant and I can see that I have aligned reads with high coverage in the expected regions. 
![image](https://cloud.githubusercontent.com/assets/6606060/9248692/d3fc6640-41b5-11e5-8fa3-6677be81d768.png)

 I also ran the BAM file through fastqc and the two areas that didn't pass were 'Per sequence GC content'

![image](https://cloud.githubusercontent.com/assets/6606060/9248610/10bbf7ae-41b5-11e5-9abe-d93d77875054.png)

and 'Kmer content'

![image](https://cloud.githubusercontent.com/assets/6606060/9248627/3679d484-41b5-11e5-9f15-f901780c1101.png)

The 'Per base sequence quality' looks fine to me

![image](https://cloud.githubusercontent.com/assets/6606060/9248668/a7d6e8ba-41b5-11e5-8459-81e324cf1d3a.png)

I am at a loss as to why it has not found any callable regions.

Does this trigger any ideas with you?

**Comment by lpantano** [comment]
Hi,

it could be the bam files uses chrN annotation and bcbio yaml file configuration has another thing different of hg19? 

i am saying this because the files with the regions are without chr in the name but the image you sent had chr1 there.


sent not from my computer

**Comment by kevjp** [comment]
Thank you for replying. I made sure that the bed files etc. had the chr strings removed. The chr string that you see in the screen shot was added by me when I was searching the BAM file using the Savant UI.

**Comment by kevjp** [comment]
My validate_regions bed file (first few lines)  is set out as shown below (no headers for each of the columns)
```
1	865529	865560
1	865592	865649
1	865696	865721
1	866413	866474
1	874414	874514
1	874679	874845
1	876518	876691
1	879087	879193
1	879282	879356
1	879359	879510
1	879512	879519
1	879521	879538
1	880068	880185
1	880431	880444
1	880489	880531
1	880892	880957
```
My variant_regions bed file (first few lines) is set out as:
```
1	69085	70013
1	861316	861398
1	865529	865721
1	866413	866474
1	871146	871281
1	874414	874514
1	874649	874845
1	876518	876691
1	877510	877636
1	877784	877873
1	877933	878443
1	878627	878762
1	879072	879193
```
Not sure if this shines any more light on the issue. Thanks for all your help.

**Comment by lpantano** [comment]
sorry about that. 

I think I would try to look into the `-debug.log` file to see if there was any warning beside that one. 
As well I think the `samtools idxstats` command will give us a general idea of the BAM file. 
thanks for your patient.

**Comment by kevjp** [comment]
Here is the output from `samtools idxstats`
```
1	249250621	13001726	18275
2	243199373	10646248	15115
3	198022430	7972862	10781
4	191154276	5861741	7898
5	180915260	6439000	8733
6	171115067	7019039	9374
7	159138663	6928410	10173
8	146364022	4923762	7557
9	141213431	5744004	8457
10	135534747	5813342	8256
11	135006516	7780042	11654
12	133851895	7338692	10157
13	115169878	2735437	3632
14	107349540	4498129	6276
15	102531392	4810649	6464
16	90354753	5902611	9630
17	81195210	7453419	11519
18	78077248	2346834	3170
19	59128983	7802706	13519
20	63025520	3243964	5066
21	48129895	1540059	2382
22	51304566	2833274	4702
X	155270560	5604609	7626
Y	59373566	82832	419
MT	16569	33982	62
GL000207.1	4262	31	0
GL000226.1	15008	2975	4
GL000229.1	19913	4933	9
GL000231.1	27386	3247	4
GL000210.1	27682	159	0
GL000239.1	33824	870	3
GL000235.1	34474	10319	43
GL000201.1	36148	2900	6
GL000247.1	36422	270	0
GL000245.1	36651	194	0
GL000197.1	37175	1448	4
GL000203.1	37498	84	0
GL000246.1	38154	625	0
GL000249.1	38502	933	1
GL000196.1	38914	894	1
GL000248.1	39786	156	0
GL000244.1	39929	186	1
GL000238.1	39939	1960	2
GL000202.1	40103	348	1
GL000234.1	40531	3319	6
GL000232.1	40652	1116	2
GL000206.1	41001	223	0
GL000240.1	41933	331	0
GL000236.1	41934	932	0
GL000241.1	42152	10851	17
GL000243.1	43341	589	2
GL000242.1	43523	4727	4
GL000230.1	43691	6767	6
GL000237.1	45867	2638	3
GL000233.1	45941	360	0
GL000204.1	81310	800	3
GL000198.1	90085	695	1
GL000208.1	92689	440	1
GL000191.1	106433	2019	8
GL000227.1	128374	761	2
GL000228.1	129120	207008	660
GL000214.1	137718	3943	10
GL000221.1	155397	2509	1
GL000209.1	159169	22949	42
GL000218.1	161147	10180	14
GL000220.1	161802	253946	815
GL000213.1	164239	1328	5
GL000211.1	166566	2001	2
GL000199.1	169874	3438	11
GL000217.1	172149	1137	2
GL000216.1	172294	21469	122
GL000215.1	172545	2224	4
GL000205.1	174588	6571	10
GL000219.1	179198	7965	12
GL000224.1	179693	8161	12
GL000223.1	180455	7775	10
GL000195.1	182896	5935	12
GL000212.1	186858	4756	4
GL000222.1	186861	77537	222
GL000200.1	187035	1884	3
GL000193.1	189789	2863	5
GL000194.1	191469	4031	8
GL000225.1	211173	115427	667
GL000192.1	547496	56091	60
*	0	0	137776
```

**Comment by chapmanb** [comment]
Thanks for all the additional information and sorry again about all this debugging. Like Lorena, I'm confused as to what is going on as the results look good. I'm suspecting something is wrong with the calculation of callable regions. If you look at the files output during calculation of callable regions: 
```
align/NA12878/NA12878-sort-callable-split/NA12878-sort-1-callable.bed
```
Do they have the correct coverage, or look like something is off? Could we also look at the first few aligned reads for the BAM file:
```
samtools view align/NA12878/NA12878-sort.bam | head -10
```
To see if we notice anything problematic? Thanks again and hopefully this reveals something.

**Comment by kevjp** [comment]
`NA12878-sort-1-callable.bed` contains `1	0	249250621	NO_COVERAGE` as do the rest of these files 

`samtools view align/NA12878/NA12878-sort.bam | head -10` outputs:
```
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:2214:15445:39978	145	1	9999	0	20S77M3S	11	130064010	0	AACGTCCTGCTCATCACACTGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAAAC	B<FFFFFFBFFFFBBBB<FFFFFBFFFFBB<FFFFBBFFFFFBIIIFFBFIIFFBFIIFFBFIIIFBIIIFF<IIFFFBIIIFFBIIFFFFFFFFFFBBB	NM:i:0	MD:Z:77	AS:i:77	XS:i:76	RG:Z:1	MQ:i:60	MS:i:3737	MC:i:130064010
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:2314:14994:25817	145	1	9999	0	17S83M	=	160253908	160243826	TTGGCCTGATCTCTGCAGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA	BBFBBBBBBBFBBBFFBBBBB<FFFBBBFFFBFFFFFFFFFBFB<0BFFBB<IFFFBBFIFFF7FFBFBBIFFFFFFFFFBBFIIIFFFFFFFBBFFBBB	NM:i:0	MD:Z:83	AS:i:83	XS:i:81	RG:Z:1	MQ:i:60	MS:i:3759	MC:i:160253908
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:1301:19874:39745	435	1	10000	0	67H33M	=	118476099	118466167	ATAACCCTAACCCTAACCCTAACCCTAACCCTA	IFFFIIIFFBIIIFFFIIFFFBFFFFFBFFBBB	NM:i:0	MD:Z:33	AS:i:33	XS:i:33	RG:Z:1	SA:Z:1,118476052,+,28S72M,41,0;
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:1301:20868:98251	339	1	10000	0	58H42M	=	36307834	36297794	ATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	IIFFIIIIFFIIIIFFIIIFFFIIIFFBIFFFFFFFFFFBBB	NM:i:0	MD:Z:42	AS:i:42	XS:i:41	RG:Z:1	SA:Z:1,36307850,-,60M40S,35,0;
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:1203:11363:90567	435	1	10000	0	53H47M	6	10874760	0	ATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	FFFFIIIFFBIIIFFFIIFFFFIIFFFFIIIIFFFFFFFFFFFFBBB	NM:i:0	MD:Z:47	AS:i:47	XS:i:46	RG:Z:1	SA:Z:6,10874664,+,40S60M,32,0;
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:1103:17607:38114	145	1	10000	0	33S67M	11	94473082	0	TCCTCCCCCACTTCTCCCTCACATACCCCTACCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCC	'7<7FFFBB<BB7B<BBFFFBBB<7FBFFBBFFFBB7FFBBBBIIFFF<FFFFFBIIFFFFIFFFFBBFFB<FIIIFFFFIFFFBIIFFFBFFFBFBBBB	NM:i:0	MD:Z:67	AS:i:67	XS:i:66	RG:Z:1	SA:Z:11,94473166,-,37M63S,0,0;	MQ:i:60	MS:i:3781	MC:i:94473082
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:1314:1662:48716	177	1	10000	0	9S91M	12	27826698	0	GTTCTAAAAATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCC	BB<<<BFBBBBBBBBBBBBFFBBBBFFFBBBFFFBB0FFFFFFIIFFFBFIIIIFIIFBBFIIFFFFIIIFFFFIFFFBIFFFFFIFFFFBFFFFFFBBB	NM:i:0	MD:Z:91	AS:i:91	XS:i:90	RG:Z:1	MQ:i:60	MS:i:3669	MC:i:27826797
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:1112:16549:37937	353	1	10000	0	55H45M	2	243152479	0	ATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA	<B'7BFF<<BBBBFB<B<BB<<BBB<B<B7BB<'7770<77'77<	NM:i:0	MD:Z:45	AS:i:45	XS:i:44	RG:Z:1	SA:Z:1,179335349,+,62M38S,34,1;
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:1311:14171:63657	353	1	10000	0	65H35M	=	10000	90	ATAACCCTAACCCTAACCCTAACCCTAACCCTAAC	IIIIFFFFFFBFFFFFFFFFFFFFFFFFFFFFF<B	NM:i:0	MD:Z:35	AS:i:35	XS:i:35	RG:Z:1	SA:Z:11,47660455,+,70M30S,40,0;
HISEQ:51:141105_D00505_0051_Ac51ufacxx:1:1311:14171:63657	145	1	10000	0	10S90M	11	47660455	0	GGCACTTACCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC	BFBBBFBBBFBBB<FFBBB<FBBBBBFFFFB<FFFFBBFFFIFFIIFFB<IFBFFBIIIFFBIIFFFFIIIFFBIIIFFBIIFFFBIFFFFFFFFFFBBB	NM:i:0	MD:Z:90	AS:i:90	XS:i:89	RG:Z:1	MQ:i:40	MS:i:3829	MC:i:47660455
```

**Comment by kevjp** [comment]
I also found two further errors in the `-debug.log` file

```python
[2015-08-11T17:20Z] [M::mem_pestat] mean and std.dev: (139.57, 52.56)
[2015-08-11T17:20Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 389)
[2015-08-11T17:20Z] [M::mem_pestat] skip orientation FF
[2015-08-11T17:20Z] [M::mem_pestat] skip orientation RR
[2015-08-11T17:20Z] samtools: writing to "/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/split/tx/tmpRfI1Bk/NA12878-sort-60000001_80000000.bam" failed: No space left on device
[2015-08-11T17:20Z] samtools: error closing "/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/split/tx/tmpRfI1Bk/NA12878-sort-60000001_80000000.bam": -1
[2015-08-11T17:20Z] cat: write error: Broken pipe
[2015-08-11T17:20Z] samblaster: Unable to write to output file.
[2015-08-11T17:20Z] 
[2015-08-11T17:20Z] [fputs] Broken pipe
[2015-08-11T17:20Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/bin/bwa mem  -c 250 -M -t 7  -R '@RG\tID:1\tPL:illumina\tPU:NA12878\tSM:NA12878' -v 1 /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(/usr/local/bin/grabix grab /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align_prep/NGS43a_H_141105A_HapMapNA12878_Pan81_ACTTGA_L001_R1_001.fastq.gz 60000001 80000000) <(/usr/local/bin/grabix grab /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align_prep/NGS43a_H_141105A_HapMapNA12878_Pan81_ACTTGA_L001_R2_001.fastq.gz 60000001 80000000)  | /usr/local/bin/samblaster -M --splitterFile >(/usr/local/bin/samtools sort -@ 7 -m 682M -T /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/split/tx/tmpRfI1Bk/NA12878-sort-60000001_80000000-sorttmp-spl -o /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/split/tx/tmpuQJovC/NA12878-sort-60000001_80000000-sr.bam /dev/stdin) --discordantFile >(/usr/local/bin/samtools sort -@ 7 -m 682M -T /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/split/tx/tmpRfI1Bk/NA12878-sort-60000001_80000000-sorttmp-disc -o /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/split/tx/tmpoNBFfG/NA12878-sort-60000001_80000000-disc.bam /dev/stdin) | (echo '@HD	VN:1.3	SO:queryname' && cat) | /usr/local/bin/samtools view -b - -o /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/split/tx/tmpRfI1Bk/NA12878-sort-60000001_80000000.bam
```

and

```python
[2015-08-12T11:02Z] bamsormadup()[0x4f77fd:]
[2015-08-12T11:02Z] bamsormadup()[0x41ccdb:]
[2015-08-12T11:02Z] bamsormadup()[0x41119e:]
[2015-08-12T11:02Z] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f00639f3ec5:??:0]
[2015-08-12T11:02Z] bamsormadup()[0x413e32:]
[2015-08-12T11:02Z] 
[2015-08-12T11:02Z] /bin/bash: line 1: 11626 Segmentation fault      bammerge IL=/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/tx/tmp2EPyrz/NA12878-sort.list SO=queryname level=0 tmpfile=/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/tx/tmpmQXZZS/NA12878-sort.bam-bammerge
[2015-08-12T11:02Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; bammerge IL=/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/tx/tmp2EPyrz/NA12878-sort.list SO=queryname level=0 tmpfile=/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/tx/tmpmQXZZS/NA12878-sort.bam-bammerge | bamsormadup threads=7 tmpfile=/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/tx/tmpmQXZZS/NA12878-sort.bam-bamsormaduptmp > /home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/tx/tmpmQXZZS/NA12878-sort.bam
```

**Comment by lpantano** [comment]
Hi @kevjp 

glad you find something else. I am seeing this:

`[2015-08-11T17:20Z] samtools: writing to "/home/kevin/Documents/NGS_Pipeline/INDELanalysis/validationrun/NA12878validation/NA12878-exome-eval/work/align/NA12878/split/tx/tmpRfI1Bk/NA12878-sort-60000001_80000000.bam" failed: No space left on device`

any chance you are out of space?

**Comment by chapmanb** [comment]
Thanks for all this additional information. Lorena is right on about the failures -- it looks like you ran out of disk space. Did bcbio not error out at any point? I would have expected this to be an unrecoverable error.

Beyond that, the issue with coverage looks like all of the reads have 0 mapping quality, indicating an issue with alignment. Only non-unique alignments in the genome should get this, which shouldn't be all of the reads. If you try:
```
sambamba view -F 'mapping_quality > 0' align/NA12878/NA12878-sort.bam
```
do you see any non-zero mapped reads? If not, this could indicate an issue with your input files. Is it possible the two paired ends are not sorted correctly so they're not matching pairs in both files? Hope this helps explain it.

**Comment by kevjp** [comment]
Thank you @chapmanb and @lpantano for your help. I was aware that I had ran out of space on my initial run. Subsequently I cleared some space and re-ran the script. I think I made a bit of an error in assuming that the script would pick up where it left and since no error came up immediately I assumed there were no issues. Eventually another error popped up and I assumed that it was related to another issue. A bit of a silly mistake on my part, my apologies. 

`sambamba view -F 'mapping_quality > 0' align/NA12878/NA12878-sort.bam`

generated many reads where the mapping quality was greater than 0 and greater than 20. So hopefully the alignment is working fine but got rudely interrupted by a memory issue last time. I am currently re-running the pipeline from the start and will keep you posted as to what the outcome will be. Thank you once again for all your help.

**Comment by chapmanb** [comment]
Sorry about this. It should be able to restart cleanly from a failure like that so I'm still not sure what happened. I'll keep my fingers crossed that a re-run fixes the issues.

**Comment by kevjp** [comment]
Just wanted to provide some feedback. When I re-started the run it ran without error so it seems to be that the original run where I ran out of disk space was the source of my problem. That being said it would be really great if the pipeline could pick up from where the issue had arisen. This is one of the really nice features of the bcbio pipeline so it would be really useful to get to the bottom as to why it did not re-start correctly on this occasion. I will let you know if I come across anything from my end. Thank you for all your help.

**Comment by chapmanb** [comment]
Thanks for following up on this. I'm glad it worked on the re-run, although also am not overjoyed that it failed to restart cleanly. If you're able to identify the underlying issue with the original run (truncated files or something else) I'd be happy to dig into it more and fix any places where we're not allowing clean failures. I'll close this for now but please feel free to re-open if you find anything to work from. Thanks again.
