### ISSUE TITLE
dexseq_count.py issue in a RNAseq run

### ISSUE THREAD

**Issue by scatreux** [chapmanb/bcbio-nextgen#973]
Hi

I'm hitting an issue consistently on a RNASeq run.
Below is the error:

[2015-08-12T23:53Z] multiprocessing: run_cufflinks
[2015-08-12T23:53Z] Resource requests: dexseq, express; memory: 1.00; cores: 1, 1
[2015-08-12T23:53Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2015-08-12T23:53Z] Timing: estimate expression (single threaded)
[2015-08-12T23:53Z] multiprocessing: run_express
[2015-08-12T23:53Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-08-12T23:53Z] multiprocessing: run_dexseq
[2015-08-12T23:53Z] Counting exon-level counts with /staging/edico_s/results/seqc_SRR950078_15M/work/align/UHRR_rep1/1_2015-03-10_seqc_star/UHRR_rep1.bam and /mnt/vault/reference_genomes/Hsapiens/GRCh37/rnaseq/../rnaseq/ref-transcripts.dexseq.gff.
[2015-08-12T23:54Z] Traceback (most recent call last):
[2015-08-12T23:54Z]   File "/usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_count.py", line 239, in <module>
[2015-08-12T23:54Z]     if current_chromosome != a.iv.chrom:
[2015-08-12T23:54Z] AttributeError: 'NoneType' object has no attribute 'chrom'
[2015-08-12T23:54Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/share/bcbio-nextgen/anaconda/bin/python /usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_count.py -f bam -r pos -p yes -s no /mnt/vault/reference_genomes/Hsapiens/GRCh37/rnaseq/../rnaseq/ref-transcripts.dexseq.gff /staging/edico_s/results/seqc_SRR950078_15M/work/align/UHRR_rep1/1_2015-03-10_seqc_star/UHRR_rep1.bam /staging/edico_s/results/seqc_SRR950078_15M/work/dexseq/tx/tmpbXBA0u/UHRR_rep1.dexseq
Traceback (most recent call last):
  File "/usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_count.py", line 239, in <module>
    if current_chromosome != a.iv.chrom:
AttributeError: 'NoneType' object has no attribute 'chrom'
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 311, in run
    samples = rnaseq.quantitate_expression_noparallel(samples, run_parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 53, in quantitate_expression_noparallel
    samples = run_parallel("run_dexseq", samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 118, in run_dexseq
    return rnaseq.run_dexseq(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 93, in run_dexseq
    data = dexseq.bcbio_run(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/dexseq.py", line 23, in bcbio_run
    counts = run_count(bam_file, dexseq_gff, stranded, out_file, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/dexseq.py", line 64, in run_count
    do.run(cmd.format(**locals()), message)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/share/bcbio-nextgen/anaconda/bin/python /usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_count.py -f bam -r pos -p yes -s no /mnt/vault/reference_genomes/Hsapiens/GRCh37/rnaseq/../rnaseq/ref-transcripts.dexseq.gff /staging/edico_s/results/seqc_SRR950078_15M/work/align/UHRR_rep1/1_2015-03-10_seqc_star/UHRR_rep1.bam /staging/edico_s/results/seqc_SRR950078_15M/work/dexseq/tx/tmpbXBA0u/UHRR_rep1.dexseq
Traceback (most recent call last):
  File "/usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_count.py", line 239, in <module>
    if current_chromosome != a.iv.chrom:
AttributeError: 'NoneType' object has no attribute 'chrom'
' returned non-zero exit status 1

**Comment by roryk** [comment]
Hi @scatreux,

Sorry for the problem and thanks for the error report. I think this is due to having an old version of DEXSeq installed; older versions had problems with paired-end reads with a BAM file with reads that are unmapped, if you update DEXSeq with:

```r
source("http://bioconductor.org/biocLite.R")
biocLite("DEXSeq")
```

It should fix this problem. Let us know if that does the trick or not.

**Comment by scatreux** [comment]
Hi Rory

i ran the 2 command lines you gave me under the R environment, then reran, but the same
error occurs. how can i check which version of dexseq it's using?

thanks
Severine

**Comment by lpantano** [comment]
Hi @scatreux 

with `sessionInfo()` you see all versions of loaded packages.

**Comment by scatreux** [comment]
this is what I'm getting:
sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.6 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by roryk** [comment]
Hi @scatreux,

If you do library(DEXSeq) first and then sessionInfo(), what does it say?

**Comment by scatreux** [comment]
R version 3.2.1 (2015-06-18)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.6 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] DEXSeq_1.8.0       Biobase_2.22.0     BiocGenerics_0.8.0

loaded via a namespace (and not attached):
 [1] IRanges_1.20.7       XML_3.98-1.3         Biostrings_2.30.1   
 [4] Rsamtools_1.14.3     bitops_1.0-6         stats4_3.2.1        
 [7] magrittr_1.5         zlibbioc_1.8.0       stringi_0.5-5       
[10] XVector_0.2.0        hwriter_1.3.2        statmod_1.4.21      
[13] tools_3.2.1          stringr_1.0.0        biomaRt_2.18.0      
[16] RCurl_1.95-4.7       GenomicRanges_1.14.4

**Comment by scatreux** [comment]
i was able to run this pipeline sucessfully a week ago, so this is a new issue..

**Comment by scatreux** [comment]
hmm... additional piece of info: I launched the same test on a different server (which worked
for me last week), and i don't get the error there. so.. it seems it is server specific.
what info should i look for that must be different between those 2 servers?

**Comment by scatreux** [comment]
both servers have a different version of 
/usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_count.py.
the server that fails has a more recent version.

**Comment by roryk** [comment]
Hi @scatreux,

Thanks for debugging. Which version of DEXseq is installed on the one that works vs. the one that doesn't?

**Comment by roryk** [comment]
DEXSeq_1.8.0 is pretty old-- 1.14 is the current version that should have the fix. I think if you upgrade DEXSeq it should work. Did:

```r
source("http://bioconductor.org/biocLite.R")
biocLite("DEXSeq")
```
not upgrade it at all? I think even 1.10 should have the change. If that doesn't install a newer version, you might have to upgrade biocLite. You can do that like this:

```r
biocLite("BiocUpgrade")
```

Let me know what happens with either of those. Thanks!

**Comment by scatreux** [comment]
ah ah... the server that works seems to have

DEXSeq_1.10.8 

ok, let me try to upgrade DEXSeq and I'll let you know. Thanks!

**Comment by scatreux** [comment]
the biocLite("DEXSeq") is not updated it at all.
trying biocLite("BiocUpgrade")

**Comment by scatreux** [comment]
Warning message:
package 'biocUpgrade' is not available (for R version 3.2.1) 

do i need to update R as well?

**Comment by lpantano** [comment]
Maybe you can try just:

```
source("http://bioconductor.org/biocLite.R")
biocLite()
```

**Comment by scatreux** [comment]
the DEXSeq is still stuck at 1.8.0. i'm obviously doing something wrong.
will try to get help around here.
seems like the problem is related to the DEXSeq version. I just need to find a way to upgrade it it seems...
thanks!

**Comment by roryk** [comment]
Hi @scatreux,

I think the B needs to be capitalized in BiocUpgrade:
```r
biocLite("BiocUpgrade")
```

**Comment by scatreux** [comment]
I got some help over here and we managed to install DexSeq 1.10.8 on the server
that wasn't working, and the error is gone. thanks!!

**Comment by bcantarel** [comment]
I am actually having a similar issue:  First I used HiSAT for the alignment.  But it doesn't contain the NH flags -- so I had to do this:
samtools view cDNA2029.align/cDNA2029.sort.bam |./getnh | /usr/bin/python /home/bcantarel/R/x86_64-redhat-linux-gnu-library/3.1/DEXSeq/python_scripts/dexseq_count.py -s no -p yes /illumina/refdata/b38/gencode.v20.annotation.gtf - cDNA2029.align/cDNA2029.exomect.txt

but a similar error:
/usr/lib64/python2.6/site-packages/HTSeq-0.6.1-py2.6-linux-x86_64.egg/HTSeq/__init__.py:589: UserWarning: Read HWI-ST1189:158:C73A6ACXX:1:2304:4730:24401 claims to have an aligned mate which could not be found in an adjacent line.
  "which could not be found in an adjacent line." )
/usr/lib64/python2.6/site-packages/HTSeq-0.6.1-py2.6-linux-x86_64.egg/HTSeq/__init__.py:536: UserWarning: Malformed SAM line: MRNM != '*' although flag bit &0x0008 set
  algnt = SAM_Alignment.from_SAM_line( line )
/usr/lib64/python2.6/site-packages/HTSeq-0.6.1-py2.6-linux-x86_64.egg/HTSeq/__init__.py:536: UserWarning: Malformed SAM line: RNAME != '*' although flag bit &0x0004 set
  algnt = SAM_Alignment.from_SAM_line( line )
/usr/lib64/python2.6/site-packages/HTSeq-0.6.1-py2.6-linux-x86_64.egg/HTSeq/__init__.py:536: UserWarning: Malformed SAM line: MRNM == '=' although read is not aligned.
  algnt = SAM_Alignment.from_SAM_line( line )
Traceback (most recent call last):
  File "/home/bcantarel/R/x86_64-redhat-linux-gnu-library/3.1/DEXSeq/python_scripts/dexseq_count.py", line 221, in <module>
    elif af.iv.chrom != ar.iv.chrom:
AttributeError: 'NoneType' object has no attribute 'chrom'


I have tried to update the package through R -- but since my R is older, I can only get version 12.2 of the package.  Would it be possible to download just the python code so I can have the latest version without having to do all of the updates associated with updating R?_

**Comment by lpantano** [comment]
Hi,

sorry about that.

https://github.com/Bioconductor-mirror/DEXSeq/tree/release-3.1/inst/python_scripts

here you have the python scripts from the last version. But maybe that breaks something else. So not sure if the python would be compatible with that.

Did you use bcbio to align? I didn't know that we supported hisat.

hope this help

**Comment by bcantarel** [comment]
Thanks so much, it appears to be working with the newest python scripts!!

**Comment by roryk** [comment]
Thanks everyone for the feedback and figuring out what was wrong!
