### ISSUE TITLE
Installation aborted at pysam

### ISSUE THREAD

**Issue by xtYaoNYU** [chapmanb/bcbio-nextgen#974]
Dear Brad and bcbio developers,

I was trying to install bcbio isolatedly in my local directory ~/Applications/bcbio/ on a server running RedHat 6.4 with Python 2.7.1.

Everything went smoothly up to the point where the script attempts to install pysam-0.8.3, while there was pysam-0.8.1 preinstalled on the machine. Trying to uninstall the old version, the access is denied, installation stopped, and I received the following error message:

  Found existing installation: pysam 0.8.1
    Uninstalling pysam-0.8.1:
Exception:
Traceback (most recent call last):
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/site-packages/pip/req/req_install.py", line 726, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/site-packages/pip/utils/__init__.py", line 314, in renames
    shutil.move(old, new)
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/home/xy293/Applications/bcbio/anaconda/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/programs/python/lib/python2.7/site-packages/pysam-0.8.1-py2.7-linux-x86_64.egg/pysam/Pileup.pyc'

Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    bcbio = bootstrap_bcbionextgen(anaconda, args, remotes)
  File "bcbio_nextgen_install.py", line 78, in bootstrap_bcbionextgen
    subprocess.check_call([anaconda["pip"], "install", "-r", remotes["requirements"]])
  File "/usr/local/lib/python2.7/subprocess.py", line 504, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/xy293/Applications/bcbio/anaconda/bin/pip', 'install', '-r', 'https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt']' returned non-zero exit status 2

Is there any way I can prevent the program from uninstalling the system version of dependencies to which I have no access to modify?

Thank you!
Xiaotong Yao

**Comment by lpantano** [comment]
Hi @xtYaoNYU !

sorry about that. 

bcbio will install an isolate python environment, so is possible you have `$PYTHONPATH` or `$PYTHONHOME` ? this will lead to this kind of errors.

can you post as well the command you use for the installation?

thanks!

**Comment by xtYaoNYU** [comment]
Hi @lpantano ,

I found out the $PYTHONPATH is set to the system installed directory. I shall follow your suggestion and rerun the installation script.

The command I used is:

python bcbio_nextgen_install.py /home/xy293/Applications/bcbio/ --tooldir=/home/xy293/Applications/bcbio/ --isolate --genomes GRCh37 --aligners bwa --aligners bowtie2

Xiaotong

**Comment by lpantano** [comment]
Hi,

let us know if you have more problems and feel free to reopen in that case.

thanks for using bcbio.
