### ISSUE TITLE
ShimWarning: The `IPython.parallel` package has been deprecated. 

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#978]
I get the following error when trying any upgrade.

```
$ bcbio_nextgen.py upgrade  --data  --genomes hg19                                                                                                            
/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprec
ated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)
Traceback (most recent call last):
  File "/srv/gsfs0/projects/ashley/apps/bin/bcbio_nextgen.py", line 35, in <module>
    from bcbio.distributed import runfn, clargs
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/runfn.py", line 11, in <module>
    from bcbio.distributed import multitasks
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 3, in <module>
    from bcbio import heterogeneity, structural, utils, chipseq, upload
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/__init__.py", line 10, in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 17, in <module>
    from bcbio.structural import regions
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 10, in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly, ensemble,
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cn_mops.py", line 20, in <module>
    from bcbio.structural import shared as sshared
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/shared.py", line 17, in <module>
    from bcbio.bam import callable
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 29, in <module>
    from bcbio.distributed import multi, prun
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 9, in <module>
    from bcbio.distributed import clusterk, ipython, multi, resources
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 31, in <module>
    from cluster_helper import cluster as ipython_cluster
  File "/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 21, in <module>
    from IPython.parallel import Client
ImportError: cannot import name Client
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issue. The newest version upgrades to the latest IPython which is a tricky change as the interfaces in IPython change. For some reason, it doesn't look like you got the latest version of ipython-cluster-helper as part of the upgrade process. You can try manually upgrading with:
```
/srv/gsfs0/projects/ashley/apps/bcbio/anaconda/bin/conda install -c bcbio ipython-cluster-helper
```
which will hopefully get things running again. Hope this fixes it for you.

**Comment by dwaggott** [comment]
Works, thank you.
