### ISSUE TITLE
The `IPython.parallel` package has been deprecated

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#980]
Hi,
I was running bcbio for exome-seq data and found the following error, which had not shown previously. Could you please help me to debug it?
Thank you.

2015-08-20 09:42:11.291 [IPClusterStart] Attempting to load config file ipcluster_config.json in path /.../work
/.../bcbio/anaconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)
[2015-08-20T14:45Z] c0321.xxx.edu: Timing: organize samples
[2015-08-20T14:45Z] c0321.xxx.edu: ipython: organize_samples
2015-08-20 09:45:45.355 [IPClusterStop] Using existing profile dir: u'/.../work/log/ipython'
2015-08-20 09:45:45.371 [IPClusterStop] Stopping cluster [pid=185819] with [signal=2]
2015-08-20 09:45:46.278 [IPClusterStop] Using existing profile dir: u'/.../work/log/ipython'
2015-08-20 09:45:46.286 [IPClusterStop] Stopping cluster [pid=185819] with [signal=2]

0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
42 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/.../bcbio/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/.../bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 139, in run
    [x[0]["description"] for x in samples]]])
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 130, in run
    for data in view.map_sync(fn, items, track=False):
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<string>", line 2, in map
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in map
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<string>", line 2, in __call__
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "/.../bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: organize_samples
[15:apply]: ExtraData: unpack(b) received extra data.

**Comment by roryk** [comment]
Hi @pengxiao78,

Sorry about that, I think this is the same issue as #978. Could you give upgrading ipython-cluster-helper similar to that thread and see if it fixes the problem?

**Comment by pengxiao78** [comment]
Got it, thank you!

**Comment by roryk** [comment]
Sweet, two birds with one stone. Thanks for following up.

**Comment by pengxiao78** [comment]
I have re-installed the bcbio and ran the command. /bcbio/anaconda/bin/conda install -c bcbio ipython-cluster-helper. It was shown

Fetching package metadata: ......
Solving package specifications: .
# All requested packages already installed.
# packages in environment at ./bcbio/anaconda:
#
ipython-cluster-helper    0.4.9                    py27_0

Then I ran the bcbio and found exactly the same error as I mentioned previously. Could you please me to debug it? Thank you!

**Comment by pengxiao78** [comment]
I have re-installed the bcbio and ran the command. /bcbio/anaconda/bin/conda install -c bcbio ipython-cluster-helper. It was shown

Fetching package metadata: ......
Solving package specifications: .

All requested packages already installed.

packages in environment at ./bcbio/anaconda:

#
ipython-cluster-helper 0.4.9 py27_0

Then I ran the bcbio and found exactly the same error as I mentioned previously. Could you please me to debug it? Thank you!

**Comment by chapmanb** [comment]
This is a duplicate of #996 -- will follow up over there.
