### ISSUE TITLE
Error running freebayes pipeline with hg38

### ISSUE THREAD

**Issue by danhalligan** [chapmanb/bcbio-nextgen#991]
I received the following obscure error message running variant calling using genome version hg38 with a freebayes pipeline in bcbio version 0.9.0. I thought it might be useful to post this to help bcbio development...

template.yaml file:

    details:
      - analysis: variant2
        genome_build: hg38-noalt
        algorithm:
          aligner: bwa
          mark_duplicates: true
          recalibrate: false
          realign: false
          variantcaller: freebayes

error (output to screen):

    [2015-09-01T04:09Z] multiprocessing: combine_bed
    Traceback (most recent call last):
      File "/path/to/bcbio/bcbio_nextgen.py", line 226, in <module>
        main(**kwargs)
      File "/path/to/bcbio/bcbio_nextgen.py", line 43, in main
        run_main(**kwargs)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
        fc_dir, run_info_yaml)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
        for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 149, in run
        samples = run_parallel("postprocess_alignment", samples)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
        return run_multicore(fn, items, config, parallel=parallel)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
        for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
        self.dispatch(function, args, kwargs)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
        job = ImmediateApply(func, args, kwargs)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
        self.results = func(*args, **kwargs)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
        return apply(f, *args, **kwargs)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 35, in postprocess_alignment
        return sample.postprocess_alignment(*args)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 156, in postprocess_alignment
        callable.block_regions(data["work_bam"], ref_file, data)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 329, in block_regions
        if len(ref_regions.subtract(nblock_regions)) > 0:
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 668, in decorated
        result = method(self, *args, **kwargs)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 243, in wrapped
        check_stderr=check_stderr)
      File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/helpers.py", line 440, in call_bedtools
        raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
    pybedtools.helpers.BEDToolsError: 
    Command was:

        bedtools subtract -b /path/to/data/work/tx/tmpbJwQda/pybedtools.bO9rgc.tmp -a /path/to/data/work/tx/tmpbJwQda/pybedtools.nV7sE1.tmp

    Error message was:
    ***** WARNING: File /path/to/data/work/tx/tmpbJwQda/pybedtools.bO9rgc.tmp has inconsistent naming convention for record:
    HLA-A*01:01:01:01   0   3503

    ***** WARNING: File /path/to/data/work/tx/tmpbJwQda/pybedtools.bO9rgc.tmp has inconsistent naming convention for record:
    HLA-A*01:01:01:01   0   3503

**Comment by chapmanb** [comment]
Dan;
Thanks much for the report. This was due to a problem with how bedtools handles hg38 chromosome naming, and we pushed a fix for it as part of the 0.9.1 release (https://github.com/chapmanb/bcbio-nextgen/commit/a2e85b671c0d6116cb9074562280e5866adebb30).

We just pushed a new 0.9.2 release so if you update with:
```
bcbio_nextgen.py upgrade -u stable --tools --data
```
it should hopefully work correctly for you now. Thanks again.
