### ISSUE TITLE
Error for qualimap in the process of rnaseq

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#993]
Hi Brad and Roky,

An error was for rnaseq module when using bcbio 0.9.2a:

Processed 58618983 reads in total

BAM file analysis finished
Creating plots
Failed to run rnaseq

java.lang.ArrayIndexOutOfBoundsException: -248849
        at org.bioinfo.ngs.qc.qualimap.common.TranscriptDataHandler.computeMeanTranscriptCoverageHist(TranscriptDataHandler.java:342)
        at org.bioinfo.ngs.qc.qualimap.common.TranscriptDataHandler.createPlots(TranscriptDataHandler.java:525)
        at org.bioinfo.ngs.qc.qualimap.process.RNASeqQCAnalysis.createCharts(RNASeqQCAnalysis.java:188)
        at org.bioinfo.ngs.qc.qualimap.process.RNASeqQCAnalysis.createResultReport(RNASeqQCAnalysis.java:175)
        at org.bioinfo.ngs.qc.qualimap.process.RNASeqQCAnalysis.run(RNASeqQCAnalysis.java:70)
        at org.bioinfo.ngs.qc.qualimap.main.RnaSeqQcTool.execute(RnaSeqQcTool.java:188)
        at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:187)
        at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:103)
Tue Aug 25 23:31:15 CST 2015            WARNING Cleanup output dir
' returned non-zero exit status 255
[2015-08-25T15:31Z] Generating summary files: ['', '99ET']
[2015-08-25T23:34Z] run local -- checkpoint passed: trimming
[2015-08-25T23:34Z] Timing: organize samples
[2015-08-25T23:34Z] multiprocessing: organize_samples
[2015-08-25T23:34Z] Using input YAML configuration: /mnt/data/Project_EC_TOTALRNA-seq/config/EC_totalRNA-seq.yaml
[2015-08-25T23:34Z] Checking sample YAML configuration: /mnt/data/Project_EC_TOTALRNA-seq/config/EC_totalRNA-seq.yaml
[2015-08-25T23:34Z] Testing minimum versions of installed programs
[2015-08-25T23:34Z] Timing: adapter trimming
[2015-08-25T23:34Z] multiprocessing: prepare_sample
[2015-08-25T23:34Z] multiprocessing: trim_sample
[2015-08-25T23:34Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/95EN_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/95EN_R2_trim.fq.gz.
[2015-08-25T23:34Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/95ET_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/95ET_R2_trim.fq.gz.
[2015-08-25T23:34Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/97EN_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/97EN_R2_trim.fq.gz.
[2015-08-25T23:34Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/97ET_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/97ET_R2_trim.fq.gz.
[2015-08-25T23:34Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/99EN_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/99EN_R2_trim.fq.gz.
[2015-08-25T23:34Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/99ET_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/99ET_R2_trim.fq.gz.
[2015-08-25T23:34Z] run local -- checkpoint passed: alignment
[2015-08-25T23:34Z] Timing: alignment
[2015-08-25T23:34Z] multiprocessing: disambiguate_split
[2015-08-25T23:34Z] multiprocessing: process_alignment
[2015-08-25T23:34Z] Aligning lane 1_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-08-25T23:34Z] Aligning lane 2_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-08-25T23:34Z] Aligning lane 3_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-08-25T23:34Z] Aligning lane 4_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-08-25T23:34Z] Aligning lane 5_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-08-25T23:34Z] Aligning lane 6_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-08-25T23:34Z] run local -- checkpoint passed: rnaseqcount
[2015-08-25T23:34Z] Timing: disambiguation
[2015-08-25T23:34Z] Timing: transcript assembly
[2015-08-25T23:34Z] Timing: estimate expression (threaded)
[2015-08-25T23:34Z] multiprocessing: generate_transcript_counts
[2015-08-25T23:34Z] multiprocessing: run_cufflinks
[2015-08-25T23:34Z] run local -- checkpoint passed: rnaseqcount-singlethread
[2015-08-25T23:34Z] Timing: estimate expression (single threaded)
[2015-08-25T23:34Z] multiprocessing: run_express
[2015-08-25T23:34Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-08-25T23:34Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-08-25T23:34Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-08-25T23:34Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-08-25T23:34Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-08-25T23:34Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-08-25T23:34Z] multiprocessing: run_dexseq
[2015-09-01T23:39Z] run local -- checkpoint passed: trimming
[2015-09-01T23:39Z] Timing: organize samples
[2015-09-01T23:39Z] multiprocessing: organize_samples
[2015-09-01T23:39Z] Using input YAML configuration: /mnt/data/Project_EC_TOTALRNA-seq/config/EC_totalRNA-seq.yaml
[2015-09-01T23:39Z] Checking sample YAML configuration: /mnt/data/Project_EC_TOTALRNA-seq/config/EC_totalRNA-seq.yaml
[2015-09-01T23:39Z] Testing minimum versions of installed programs
[2015-09-01T23:39Z] Timing: adapter trimming
[2015-09-01T23:39Z] multiprocessing: prepare_sample
[2015-09-01T23:39Z] multiprocessing: trim_sample
[2015-09-01T23:39Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/95EN_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/95EN_R2_trim.fq.gz.
[2015-09-01T23:39Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/95ET_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/95ET_R2_trim.fq.gz.
[2015-09-01T23:39Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/97EN_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/97EN_R2_trim.fq.gz.
[2015-09-01T23:39Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/97ET_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/97ET_R2_trim.fq.gz.
[2015-09-01T23:39Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/99EN_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/99EN_R2_trim.fq.gz.
[2015-09-01T23:39Z] Skipping trimming of /mnt/data/Project_EC_TOTALRNA-seq/input/99ET_R1_trim.fq.gz, /mnt/data/Project_EC_TOTALRNA-seq/input/99ET_R2_trim.fq.gz.
[2015-09-01T23:39Z] run local -- checkpoint passed: alignment
[2015-09-01T23:39Z] Timing: alignment
[2015-09-01T23:39Z] multiprocessing: disambiguate_split
[2015-09-01T23:39Z] multiprocessing: process_alignment
[2015-09-01T23:39Z] Aligning lane 1_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-09-01T23:39Z] Aligning lane 2_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-09-01T23:39Z] Aligning lane 3_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-09-01T23:39Z] Aligning lane 4_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-09-01T23:39Z] Aligning lane 5_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-09-01T23:39Z] Aligning lane 6_2015-08-20_EC_totalRNA-seq with tophat2 aligner
[2015-09-01T23:39Z] run local -- checkpoint passed: rnaseqcount
[2015-09-01T23:39Z] Timing: disambiguation
[2015-09-01T23:39Z] Timing: transcript assembly
[2015-09-01T23:39Z] Timing: estimate expression (threaded)
[2015-09-01T23:39Z] multiprocessing: generate_transcript_counts
[2015-09-01T23:39Z] multiprocessing: run_cufflinks
[2015-09-01T23:39Z] run local -- checkpoint passed: rnaseqcount-singlethread
[2015-09-01T23:39Z] Timing: estimate expression (single threaded)
[2015-09-01T23:39Z] multiprocessing: run_express
[2015-09-01T23:39Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-09-01T23:39Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-09-01T23:39Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-09-01T23:39Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-09-01T23:39Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-09-01T23:39Z] Transcriptome-mapped BAM file not found, skipping eXpress.
[2015-09-01T23:39Z] multiprocessing: run_dexseq
[2015-09-01T23:56Z] run local -- checkpoint passed: rnaseq-variation
[2015-09-01T23:56Z] Timing: RNA-seq variant calling
[2015-09-01T23:56Z] multiprocessing: run_rnaseq_variant_calling
[2015-09-01T23:56Z] multiprocessing: run_rnaseq_joint_genotyping
[2015-09-01T23:56Z] Timing: quality control
[2015-09-01T23:56Z] multiprocessing: pipeline_summary
[2015-09-01T23:56Z] Generating summary files: ['', '95EN']
[2015-09-01T23:56Z] Generating summary files: ['', '95ET']
[2015-09-01T23:56Z] Generating summary files: ['', '97EN']
[2015-09-02T00:04Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/data/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/data/bcbio_install/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset DISPLAY && /mnt/data/bcbio_install/bin/qualimap rnaseq -outdir /mnt/data/Project_EC_TOTALRNA-seq/work/qc/95EN/qualimap -a proportional -bam /mnt/data/Project_EC_TOTALRNA-seq/work/align/95EN/1_2015-08-20_EC_totalRNA-seq_tophat/95EN.bam -gtf /mnt/data/bcbio_install/genomes/Hsapiens/GRCh37/rnaseq/ref-transcripts.gtf --java-mem-size=4G
Analyzed 18500000 reads...
Analyzed 19000000 reads...
Analyzed 19500000 reads...
Analyzed 20000000 reads...
Analyzed 20500000 reads...
Analyzed 21000000 reads...
Analyzed 21500000 reads...
Analyzed 22000000 reads...
Analyzed 22500000 reads...
Analyzed 23000000 reads...
Analyzed 23500000 reads...
Analyzed 24000000 reads...
Analyzed 24500000 reads...
Analyzed 25000000 reads...
Analyzed 25500000 reads...
Analyzed 26000000 reads...
Analyzed 26500000 reads...
Analyzed 27000000 reads...
Analyzed 27500000 reads...
Analyzed 28000000 reads...
Analyzed 28500000 reads...
Analyzed 29000000 reads...
Analyzed 29500000 reads...
Analyzed 30000000 reads...
Analyzed 30500000 reads...
Analyzed 31000000 reads...
Analyzed 31500000 reads...
Analyzed 32000000 reads...
Analyzed 32500000 reads...
Analyzed 33000000 reads...
Analyzed 33500000 reads...
Analyzed 34000000 reads...
Analyzed 34500000 reads...
Analyzed 35000000 reads...
Analyzed 35500000 reads...
Analyzed 36000000 reads...
Analyzed 36500000 reads...
Analyzed 37000000 reads...
Analyzed 37500000 reads...
Analyzed 38000000 reads...
Analyzed 38500000 reads...
Analyzed 39000000 reads...
Analyzed 39500000 reads...
Analyzed 40000000 reads...
Analyzed 40500000 reads...
Analyzed 41000000 reads...
Analyzed 41500000 reads...
Analyzed 42000000 reads...
Analyzed 42500000 reads...
Analyzed 43000000 reads...
Analyzed 43500000 reads...
Analyzed 44000000 reads...
Analyzed 44500000 reads...
Analyzed 45000000 reads...
Analyzed 45500000 reads...
Analyzed 46000000 reads...
Analyzed 46500000 reads...
Analyzed 47000000 reads...
Analyzed 47500000 reads...
Analyzed 48000000 reads...
Analyzed 48500000 reads...
Analyzed 49000000 reads...
Analyzed 49500000 reads...
Analyzed 50000000 reads...
Analyzed 50500000 reads...
Analyzed 51000000 reads...
Analyzed 51500000 reads...
Analyzed 52000000 reads...
Analyzed 52500000 reads...
Analyzed 53000000 reads...
Analyzed 53500000 reads...
Analyzed 54000000 reads...
Analyzed 54500000 reads...
Analyzed 55000000 reads...
Analyzed 55500000 reads...
Analyzed 56000000 reads...
Analyzed 56500000 reads...
Analyzed 57000000 reads...
Analyzed 57500000 reads...
Analyzed 58000000 reads...
Analyzed 58500000 reads...
Chromosome GL000217.1 from read is not found in annotations.
Chromosome GL000200.1 from read is not found in annotations.

Processed 58618983 reads in total

BAM file analysis finished
Creating plots
Failed to run rnaseq

java.lang.ArrayIndexOutOfBoundsException: -248849
        at org.bioinfo.ngs.qc.qualimap.common.TranscriptDataHandler.computeMeanTranscriptCoverageHist(TranscriptDataHandler.java:342)
        at org.bioinfo.ngs.qc.qualimap.common.TranscriptDataHandler.createPlots(TranscriptDataHandler.java:525)
        at org.bioinfo.ngs.qc.qualimap.process.RNASeqQCAnalysis.createCharts(RNASeqQCAnalysis.java:188)
        at org.bioinfo.ngs.qc.qualimap.process.RNASeqQCAnalysis.createResultReport(RNASeqQCAnalysis.java:175)
        at org.bioinfo.ngs.qc.qualimap.process.RNASeqQCAnalysis.run(RNASeqQCAnalysis.java:70)
        at org.bioinfo.ngs.qc.qualimap.main.RnaSeqQcTool.execute(RnaSeqQcTool.java:188)
        at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:187)
        at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:103)
Wed Sep 02 08:04:55 CST 2015            WARNING Cleanup output dir
' returned non-zero exit status 255

It looks qualimap rnaseq can't go through, could please help me check it ?

Thanks so much !

**Comment by roryk** [comment]
Hi @junchend,

We were a couple of versions behind with qualimap, and that bug looks to me like it is probably fixed in this commit from earlier this month:

https://bitbucket.org/kokonech/qualimap/commits/5e688f83256e8643a3511b2637a518d4c87538e7

There is a release of qualimap that should have that fix. I updated the homebrew-science formula so that it pulls in that version:

https://github.com/Homebrew/homebrew-science/pull/2702

but it won't get pulled in automatically until the homebrew-science folks get around to it. 

In the meantime if you:

```bash
wget https://raw.githubusercontent.com/roryk/homebrew-science/master/qualimap.rb
brew install qualimap.rb
```

it should pull in the new version and get you going.

**Comment by junchend** [comment]
Hi roryk,


Thanks so much!

It can go through, that's the point.

**Comment by roryk** [comment]
Great!
