### ISSUE TITLE
ipyparallel.error

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#996]
I know that I have posted this error before but it was closed without solving. I have re-installed the bcbio and ran the command. /bcbio/anaconda/bin/conda install -c bcbio ipython-cluster-helper. It was shown
Fetching package metadata: ......
Solving package specifications: .
All requested packages already installed.
packages in environment at ./bcbio/anaconda:
#
ipython-cluster-helper 0.4.9 py27_0

Then I ran the bcbio and found exactly the same error as follows as I mentioned previously. Could you please help me to debug it? Thank you!

2015-09-03 09:47:03.714 [IPClusterStart] Attempting to load config file ipcluster_config.json in path ./project/work
[2015-09-03T14:50Z] ***.edu: Timing: organize samples
./bcbio/anaconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)
[2015-09-03T14:50Z] ***.edu: ipython: organize_samples
2015-09-03 09:50:12.130 [IPClusterStop] Using existing profile dir: u'./project/work/log/ipython'
2015-09-03 09:50:12.141 [IPClusterStop] Stopping cluster [pid=110591] with [signal=2]
2015-09-03 09:50:13.387 [IPClusterStop] Using existing profile dir: u'./project/work/log/ipython'
2015-09-03 09:50:13.394 [IPClusterStop] Stopping cluster [pid=110591] with [signal=2]

0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
1 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "./bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "./bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 139, in run
    [x[0]["description"] for x in samples]]])
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 130, in run
    for data in view.map_sync(fn, items, track=False):
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<string>", line 2, in map
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<string>", line 2, in map
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<string>", line 2, in __call__
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: organize_samples
[0:apply]: ExtraData: unpack(b) received extra data.

**Comment by roryk** [comment]
Hi @pengxiao78,

Hmm, I thought we fixed that issue in 0.9.2-- is your bcbio-nextgen installation current or is it at 0.9.1?

**Comment by pengxiao78** [comment]
How can I check the version? I juts used the command 
python bcbio_nextgen_install.py /path_to_bcbio --tooldir=/path_to_bcbio --isolate \
   --genomes GRCh37 --aligners bwa --aligners bowtie2
to install it. Thank you.

**Comment by chapmanb** [comment]
Running:
```
bcbio_nextgen.py --version
```
will tell you what you have. If you have < 0.9.2 doing:
```
bcbio_nextgen.py upgrade -u stable
```
should hopefully resolve the problem. Hope this fixes it for you.

**Comment by pengxiao78** [comment]
Thank you! I found that the version was 0.9.1 and I updated it into 0.9.2 according to your command. However, a new error appeared as follows. Should I further update something?
[2015-09-04T15:00Z] *.edu: sambamba-view: Unable to write to stream
[2015-09-04T15:00Z] *.edu: Uncaught exception occurred
Traceback (most recent call last):
  File ./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File ./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; ./bcbio/bin/sambamba view -F 'mapping_quality > 0' -L /tmp/bcbiotx/761c7ecb-1dca-49f3-a198-ae445c41409c/tmpH_ISwF/4_2015-08-06_goldner_1-6-merged-sort-2-callable-coverageregions.bed -f bam -l 1 ./project/work/align/3121Germ/4_2015-08-06_goldner_1-6-merged-sort.bam | ./bcbio/bin/bedtools genomecov -split -ibam stdin -bga -g ./bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa.fai -max 70001 > /tmp/bcbiotx/afb96c10-a8ee-465f-8175-6680ddc22c26/tmpdOOpTc/4_2015-08-06_goldner_1-6-merged-sort-2-callable-genomecov.bed
./bcbio/bin/bedtools: /util/comp/gcc/4.8/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./bcbio/bin/bedtools)
sambamba-view: Unable to write to stream

' returned non-zero exit status 1

**Comment by pengxiao78** [comment]
I have solved the following error by change compiler/gcc/4.8 into  ./4.9. Please ignore it. Thank you!

From: Xiao, Peng
Sent: Friday, September 04, 2015 10:12 AM
To: 'chapmanb/bcbio-nextgen' <reply@reply.github.com>
Subject: RE: [bcbio-nextgen] ipyparallel.error (#996)


Thank you! I found that the version was 0.9.1 and I updated it into 0.9.2 according to your command. However, a new error appeared as follows. Should I further update something?
[2015-09-04T15:00Z] *.edu: sambamba-view: Unable to write to stream
[2015-09-04T15:00Z] *.edu: Uncaught exception occurred
Traceback (most recent call last):
  File ./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File ./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; ./bcbio/bin/sambamba view -F 'mapping_quality > 0' -L /tmp/bcbiotx/761c7ecb-1dca-49f3-a198-ae445c41409c/tmpH_ISwF/4_2015-08-06_goldner_1-6-merged-sort-2-callable-coverageregions.bed -f bam -l 1 ./project/work/align/3121Germ/4_2015-08-06_goldner_1-6-merged-sort.bam | ./bcbio/bin/bedtools genomecov -split -ibam stdin -bga -g ./bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa.fai -max 70001 > /tmp/bcbiotx/afb96c10-a8ee-465f-8175-6680ddc22c26/tmpdOOpTc/4_2015-08-06_goldner_1-6-merged-sort-2-callable-genomecov.bed
./bcbio/bin/bedtools: /util/comp/gcc/4.8/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./bcbio/bin/bedtools)
sambamba-view: Unable to write to stream

' returned non-zero exit status 1

**Comment by roryk** [comment]
Hi @pengxiao78,

Thanks, glad it is working now.
